//@version=5
indicator('SMA on Daily', overlay=true)

sma50 = request.security(syminfo.tickerid, 'D', ta.sma(close, 50))
sma100 = request.security(syminfo.tickerid, 'D', ta.sma(close, 100))
sma200 = request.security(syminfo.tickerid, 'D', ta.sma(close, 200))

plot(sma50, color=color.new(color.blue, 0), linewidth=3)
plot(sma100, color=color.new(color.green, 0), linewidth=3)
plot(sma200, color=color.rgb(247, 7, 167, 19), linewidth=3)
