// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ramazankaansahin

//@version=6
indicator(title = 'EMA 20/50/100/200', overlay = true)

shortest = ta.ema(close, 20)
short = ta.ema(close, 50)
longer = ta.ema(close, 100)
longest = ta.ema(close, 200)

plot(shortest, color = color.red, linewidth = 1, title = 'EMA 20')
plot(short, color = color.orange, linewidth = 1, title = 'EMA 50')
plot(longer, color = color.aqua, linewidth = 1, title = 'EMA 100')
plot(longest, color = color.blue, linewidth = 1, title = 'EMA 200')

// Sağ tarafa label yaz (sadece son bar'da)
if barstate.islast
    label.new(bar_index, shortest, 'EMA 20', color = color.red, textcolor = color.white, style = label.style_label_left, size = size.small)
    label.new(bar_index, short, 'EMA 50', color = color.orange, textcolor = color.white, style = label.style_label_left, size = size.small)
    label.new(bar_index, longer, 'EMA 100', color = color.aqua, textcolor = color.black, style = label.style_label_left, size = size.small)
    label.new(bar_index, longest, 'EMA 200', color = color.blue, textcolor = color.white, style = label.style_label_left, size = size.small)
