//@version=5
indicator("Ema (9, 50, 200) Buy Sell Strategy", overlay=true)

// === INPUTS ===
ema9Length = input.int(9, title="Ema 9")
ema50Length = input.int(50, title="Ema 50")
ema200Length = input.int(200, title="Ema 200")

// === CALCULATIONS ===
ema9 = ta.ema(close, ema9Length)
ema50 = ta.ema(close, ema50Length)
ema200 = ta.ema(close, ema200Length)

// === CONDITIONS ===

// TREND FILTER
upTrend = ema50 > ema200
downTrend = ema50 < ema200

// ENTRY SIGNALS
buyCondition = ta.crossover(ema9, ema50) and upTrend
sellCondition = ta.crossunder(ema9, ema50) and downTrend

// === PLOTS ===
plot(ema9, color=color.yellow, title="Ema 9", linewidth=1)
plot(ema50, color=color.blue, title="Ema 50", linewidth=3)
plot(ema200, color=color.red, title="Ema 200", linewidth=3)

// === SIGNALS ===
plotshape(buyCondition, title="Buy", location=location.belowbar, color=color.green, style=shape.labelup, text="Buy")
plotshape(sellCondition, title="Sell", location=location.abovebar, color=color.red, style=shape.labeldown, text="Sell")

// === ALERTS ===
alertcondition(buyCondition, title="Buy Alert", message="Buy Signal Generated")
alertcondition(sellCondition, title="Sell Alert", message="Sell Signal Generated")
