//@version=6
indicator("Ratio Between Two Symbols", shorttitle="Ratio", format=format.inherit, precision=4, overlay=false)

var label lb1 = na
label.delete(lb1)

truncate(number, decimals) =>
    factor = math.pow(10, decimals)
    int(number * factor) / factor

// Add the script's inputs
symbol2 = input.symbol(title="Benchmark", defval="TVC:SPX")
maDuration1 = input.int(title="Moving Average", defval=36)
showtext = input.bool(title="Show Text", defval=true)
Multiplier = input.float(title="Ratio Multiplier", defval=1.0)
digits = input.int(title="Digits", defval=3)

ratio = (request.security(syminfo.tickerid, timeframe.period, close) / request.security(symbol2, timeframe.period, close)) * Multiplier
ma = ta.sma(ratio, maDuration1)

// Plot a line
plot(series=ratio, color=color.black, style=plot.style_stepline, linewidth=1)
plot(series=ma, color=color.red, linewidth=1)
labeltext = syminfo.tickerid + " vs " + symbol2 + " : " + str.tostring(truncate(ratio, digits)) + " (" + str.tostring(Multiplier) + ")"

if (showtext)
    lb1 := label.new(x=bar_index, y=ratio, text=labeltext, color=#8B008B, textcolor=color.white, style=label.style_label_left, size=size.small)
