//@version=5
indicator("T", overlay=false)

var bool intrade = false
var bool isafterred = false

// ───── Inputs ─────
length      = input.int(20)

newDay = ta.change(time("D"))

if newDay
    intrade := false
    isafterred := true

// ───── Calculations ─────
lower = ta.lowest(low, length)
upper = ta.highest(high, length)

ema = ta.vwap(lower  )
distance = close - ema

greenCount  = input.int(20, "Number of Green Bars")

// Green condition
isGreen = close > open //or close<open

var float[] greenArray = array.new_float()

// Store only green bars
if isGreen and distance>1
    array.unshift(greenArray, high - ema)
    
    if array.size(greenArray) > greenCount
        array.pop(greenArray)

// Average
float avgLast20Green = na

if array.size(greenArray) > 0
    float sum = 0.0
    for i = 0 to array.size(greenArray) - 1
        sum += array.get(greenArray, i)
    avgLast20Green := sum / array.size(greenArray)

plot(avgLast20Green, color=color.green, linewidth=2)

plot(distance,
     style = plot.style_histogram,
     color = close > ema ? color.green : color.red,
     title = "Histogram")

// =====================================================
// 🔥 BUY IGNITION
// =====================================================
var bool isent=false
avgDist = ta.wma(distance,length )


plot(avgDist,     style = plot.style_line,     color = color.black ,     title = "vv")




// ───── FINAL BUY SIGNAL ─────
//buyIgnition = open==low and  distance>4 //and distance>avgLast20Green //and distance>avgLast20Green//  avgDist>0 and avgDist[1]<0  //distance>distance[1] and distance>avgLast20Green and  avgDist>avgDist[1] and avgLast20Green>avgDist and avgLast20Green>avgLast20Green[1] and avgDist<distance // and avgDist <avgDist[1] //and distance>0,

buyIgnition = distance>0 and open<close //open<close and distance>20 and distance>ta.highest(avgLast20Green[1],20) // distance>2   and avgDist>0 and avgLast20Green>0//and distance>avgLast20Green //and distance>avgLast20Green//  avgDist>0 and avgDist[1]<0  //distance>distance[1] and distance>avgLast20Green and  avgDist>avgDist[1] and avgLast20Green>avgDist and avgLast20Green>avgLast20Green[1] and avgDist<distance // and avgDist <avgDist[1] //and distance>0,


//buyIgnition=  open<close and distance>0 and distance[1]<0
// ───── Plot BUY Arrow ─────
plotshape(buyIgnition and not intrade[1],
     title="BUY Ignition",
     style=shape.labelup,
     location=location.belowbar,
     color=color.green,
     text="🔥",
     size=size.small,
     force_overlay=true)

if buyIgnition and not intrade[1]
    label.new(bar_index, low,
         str.tostring(close, format.mintick),
         style = label.style_label_up,
         color = color.green,
         textcolor = color.white,
         size = size.small,
         force_overlay = true)
    intrade := true

// ───── SL = Buy Candle Low ─────
var float buySL = na
var float buydis = na



if buyIgnition and not intrade[1]
    buySL := low
    buydis:=distance

plot(intrade ? buySL : na,
     title="Buy SL",
     color=color.lime,
     linewidth=2,
     style=plot.style_line,
     force_overlay=true)

// SL Hit Condition
slHit = intrade[1] and (distance<0  ) //or ( distance<avgLast20Green and distance<avgDist and  distance[1]>avgLast20Green[1] and distance[1]>avgDist[1]))

if distance < 0
    isafterred := true

plotshape(slHit,
     title="sell Ignition",
     style=shape.labeldown,
     location=location.abovebar,
     color=color.red,
     text="S",
     size=size.small,
     force_overlay=true)

if slHit 
    intrade := false
    isafterred := false
    label.new(bar_index, buySL,        "SL\n" + str.tostring(close, format.mintick),        style=label.style_label_down,        color=color.orange,        textcolor=color.white,        size=size.small,        force_overlay=true)

alertcondition(buyIgnition and not intrade[1], "Buy")
alertcondition(slHit, "SL Hit")
