//@version=5
indicator('SMT Divergences & BOS Detector Synthicator', overlay = true, max_labels_count = 500, max_lines_count = 500, max_bars_back=5000)
BULLISH_LEG                     = 1
BEARISH_LEG                     = 0

BULLISH                         = +1
BEARISH                         = -1

GREEN                           = #089981
RED                             = #F23645
GRAY                            = #878b94
MONO_BULLISH                    = #b2b5be
MONO_BEARISH                    = #5d606b

HISTORICAL                      = 'Historical'
PRESENT                         = 'Present'

COLORED                         = 'Colored'
MONOCHROME                      = 'Monochrome'

ALL                             = 'All'
BOS                             = 'BOS'

TINY                            = size.tiny
SMALL                           = size.small
NORMAL                          = size.normal

BOS_GROUP                       = 'BOS Detector Settings'
SMT_GROUP                       = 'SMT Divergences Settings'

modeTooltip                     = 'Allows to display historical Structure or only the recent ones'
styleTooltip                    = 'Indicator color theme'
showTrendTooltip                = 'Display additional candles with a color reflecting the current trend detected by structure'
showInternalsTooltip            = 'Display internal market structure'
internalFilterConfluenceTooltip = 'Filter non significant internal structure breakouts'
showStructureTooltip            = 'Display swing market Structure'
showSwingsTooltip               = 'Display swing point as labels on the chart'
showHighLowSwingsTooltip        = 'Highlight most recent strong and weak high/low points on the chart'

enableBOS                       = input.bool(true,  'Enable BOS Detector', group = BOS_GROUP, display = display.data_window)
modeInput                       = input.string(HISTORICAL, 'Mode', group = BOS_GROUP, tooltip = modeTooltip, options = [HISTORICAL, PRESENT], display = display.data_window)
styleInput                      = input.string(COLORED,    'Style', group = BOS_GROUP, tooltip = styleTooltip, options = [COLORED, MONOCHROME], display = display.data_window)
showTrendInput                  = input(false,     'Color Candles', group = BOS_GROUP, tooltip = showTrendTooltip, display = display.data_window)

showInternalsInput              = input(true,      'Show Internal Structure', group = BOS_GROUP, tooltip = showInternalsTooltip, display = display.data_window)
showInternalBullInput           = input.string(ALL, 'Bullish Structure', group = BOS_GROUP, inline = 'ibull', options = [ALL, BOS], display = display.data_window)
internalBullColorInput          = input(GREEN,     '', group = BOS_GROUP, inline = 'ibull', display = display.data_window)
showInternalBearInput           = input.string(ALL, 'Bearish Structure', group = BOS_GROUP, inline = 'ibear', options = [ALL, BOS], display = display.data_window)
internalBearColorInput          = input(RED,       '', group = BOS_GROUP, inline = 'ibear', display = display.data_window)
internalFilterConfluenceInput   = input(false,     'Confluence Filter', group = BOS_GROUP, tooltip = internalFilterConfluenceTooltip, display = display.data_window)
internalStructureSize           = input.string(TINY,'Internal Label Size', group = BOS_GROUP, options = [TINY, SMALL, NORMAL], display = display.data_window)

showStructureInput              = input(true,      'Show Swing Structure', group = BOS_GROUP, tooltip = showStructureTooltip, display = display.data_window)
showSwingBullInput              = input.string(ALL, 'Bullish Structure', group = BOS_GROUP, inline = 'bull', options = [ALL, BOS], display = display.data_window)
swingBullColorInput             = input(GREEN,     '', group = BOS_GROUP, inline = 'bull', display = display.data_window)
showSwingBearInput              = input.string(ALL, 'Bearish Structure', group = BOS_GROUP, inline = 'bear', options = [ALL, BOS], display = display.data_window)
swingBearColorInput             = input(RED,       '', group = BOS_GROUP, inline = 'bear', display = display.data_window)
swingStructureSize              = input.string(SMALL, 'Swing Label Size', group = BOS_GROUP, options = [TINY, SMALL, NORMAL], display = display.data_window)
showSwingsInput                 = input(false,     'Show Swings Points', group = BOS_GROUP, tooltip = showSwingsTooltip, inline = 'swings', display = display.data_window)
swingsLengthInput               = input.int(50,    '', group = BOS_GROUP, minval = 10, inline = 'swings', display = display.data_window)
showHighLowSwingsInput          = input(true,      'Show Strong/Weak High/Low', group = BOS_GROUP, tooltip = showHighLowSwingsTooltip, display = display.data_window)

enableSMT                       = input.bool(true, 'Enable SMT Divergences', group = SMT_GROUP, display = display.data_window)
HIST                            = input.bool(true, 'Show Historical', group = SMT_GROUP, inline = 's000', display = display.data_window)

Simb_1                          = input.bool(true, '', group = SMT_GROUP, inline = 's0', display = display.data_window)
Simb_Compar                     = input.symbol('OANDA:XAUUSD', 'Sym 1', group = SMT_GROUP, inline = 's0', display = display.data_window)
invert_symbol                   = input.bool(false, 'Invert Symbol', group = SMT_GROUP, inline = 's0', display = display.data_window)
Simb_2                          = input.bool(true, '', group = SMT_GROUP, inline = 's00', display = display.data_window)
Simb_Compar_2                    = input.symbol('OANDA:XAGUSD', 'Sym 2', group = SMT_GROUP, inline = 's00', display = display.data_window)
invert_symbol_2                 = input.bool(false, 'Invert Symbol', group = SMT_GROUP, inline = 's00', display = display.data_window)

hLine_c                         = color.blue
lLine_c                         = color.blue

n1_true                         = input.bool(true, 'Enable N1', group = SMT_GROUP, inline = 'n1', display = display.data_window)
n1                              = input.int(9, 'N1', group = SMT_GROUP, minval = 1, inline = 'n1', display = display.data_window)
n2_true                         = input.bool(true, 'Enable N2', group = SMT_GROUP, inline = 'n2', display = display.data_window)
n2                              = input.int(14, 'N2', group = SMT_GROUP, minval = 1, inline = 'n2', display = display.data_window)
n3_true                         = input.bool(true, 'Enable N3', group = SMT_GROUP, inline = 'n3', display = display.data_window)
n3                              = input.int(10, 'N3', group = SMT_GROUP, minval = 1, inline = 'n3', display = display.data_window)
n4_true                         = input.bool(true, 'Enable N4', group = SMT_GROUP, inline = 'n4', display = display.data_window)
n4                              = input.int(8, 'N4', group = SMT_GROUP, minval = 1, inline = 'n4', display = display.data_window)

color_labels                    = input.color(#c7c7c7, "Labels", group = SMT_GROUP, display = display.data_window)

Line_UP                         = input.bool(true, 'Show SMT UP', group = SMT_GROUP, display = display.data_window)
Label_UP                        = Line_UP == true ? true : false
Line_DOWN                       = input.bool(true, 'Show SMT DOWN', group = SMT_GROUP, display = display.data_window)
Label_DOWN                      = Line_DOWN == true ? true : false

type alerts
    bool internalBullishBOS         = false
    bool internalBearishBOS         = false
    bool swingBullishBOS            = false
    bool swingBearishBOS            = false

type trailingExtremes
    float top
    float bottom
    int barTime
    int barIndex
    int lastTopTime
    int lastBottomTime

type trend
    int bias

type pivot
    float currentLevel
    float lastLevel
    bool crossed
    int barTime     = time
    int barIndex    = bar_index

var pivot swingHigh                 = pivot.new(na,na,false)
var pivot swingLow                  = pivot.new(na,na,false)
var pivot internalHigh              = pivot.new(na,na,false)
var pivot internalLow               = pivot.new(na,na,false)
var trend swingTrend                = trend.new(0)
var trend internalTrend             = trend.new(0)
var array<float> parsedHighs        = array.new<float>()
var array<float> parsedLows         = array.new<float>()
var array<float> highs              = array.new<float>()
var array<float> lows               = array.new<float>()
var array<int> times                = array.new<int>()
var trailingExtremes trailing       = trailingExtremes.new()
var swingBullishColor               = styleInput == MONOCHROME ? MONO_BULLISH : swingBullColorInput
var swingBearishColor               = styleInput == MONOCHROME ? MONO_BEARISH : swingBearColorInput
varip int currentBarIndex           = bar_index
varip int lastBarIndex               = bar_index
alerts currentAlerts                = alerts.new()
var initialTime                     = time

parsedHigh                          = high
parsedLow                           = low

if enableBOS
    parsedHighs.push(parsedHigh)
    parsedLows.push(parsedLow)
    highs.push(high)
    lows.push(low)
    times.push(time)


[Open, High, Low, Close] = request.security(Simb_Compar, timeframe.period, [open, high, low, close])
if invert_symbol and enableSMT
    Open  := 1 / Open
    High  := 1 / High
    Low   := 1 / Low
    Close := 1 / Close

[Open_2, High_2, Low_2, Close_2] = request.security(Simb_Compar_2, timeframe.period, [open, high, low, close])
if invert_symbol_2 and enableSMT
    Open_2  := 1 / Open_2
    High_2  := 1 / High_2
    Low_2   := 1 / Low_2
    Close_2 := 1 / Close_2

normPrice(p) =>
    math.round(p / syminfo.mintick) * syminfo.mintick

mkKey(x1, y1, x2, y2) =>
    str.tostring(x1) + "|" + str.tostring(x2) + "|" + str.tostring(y1) + "|" + str.tostring(y2)

var string[] __smt_keys = array.new_string()

if barstate.isnew and not HIST and enableSMT
    array.clear(__smt_keys)

isNewLine(x1, y1, x2, y2) =>
    _y1 = normPrice(y1)
    _y2 = normPrice(y2)
    _k  = mkKey(x1, _y1, x2, _y2)
    _ix = array.indexof(__smt_keys, _k)
    if _ix == -1
        array.push(__smt_keys, _k)
        true
    else
        false

get_slope(price1, price2, bar1, bar2) =>
    (price2 - price1) / (bar2 - bar1)

leg(int size) =>
    var leg     = 0
    newLegHigh  = high[size] > ta.highest( size)
    newLegLow   = low[size]  < ta.lowest(  size)

    if newLegHigh
        leg := BEARISH_LEG
    else if newLegLow
        leg := BULLISH_LEG
    leg

startOfNewLeg(int leg)      => ta.change(leg) != 0
startOfBearishLeg(int leg)  => ta.change(leg) == -1
startOfBullishLeg(int leg)  => ta.change(leg) == +1

drawLabel(int labelTime, float labelPrice, string tag, color labelColor, string labelStyle) =>
    var label l_abel = na

    if modeInput == PRESENT
        l_abel.delete()

    l_abel := label.new(chart.point.new(labelTime,na,labelPrice),tag,xloc.bar_time,color=color(na),textcolor=color.new(color.white, 100),style = labelStyle,size = size.small)

getCurrentStructure(int size, bool internal = false) =>
    currentLeg              = leg(size)
    newPivot                = startOfNewLeg(currentLeg)
    pivotLow                = startOfBullishLeg(currentLeg)
    pivotHigh               = startOfBearishLeg(currentLeg)

    if newPivot
        if pivotLow
            pivot p_ivot    = internal ? internalLow : swingLow

            p_ivot.lastLevel    := p_ivot.currentLevel
            p_ivot.currentLevel := low[size]
            p_ivot.crossed      := false
            p_ivot.barTime      := time[size]
            p_ivot.barIndex     := bar_index[size]

            if not internal
                trailing.bottom         := p_ivot.currentLevel
                trailing.barTime        := p_ivot.barTime
                trailing.barIndex       := p_ivot.barIndex
                trailing.lastBottomTime := p_ivot.barTime

            if showSwingsInput and not internal
                drawLabel(time[size], p_ivot.currentLevel, p_ivot.currentLevel < p_ivot.lastLevel ? 'LL' : 'HL', swingBullishColor, label.style_label_up)
        else
            pivot p_ivot = internal ? internalHigh : swingHigh

            p_ivot.lastLevel    := p_ivot.currentLevel
            p_ivot.currentLevel := high[size]
            p_ivot.crossed      := false
            p_ivot.barTime      := time[size]
            p_ivot.barIndex     := bar_index[size]

            if not internal
                trailing.top            := p_ivot.currentLevel
                trailing.barTime        := p_ivot.barTime
                trailing.barIndex       := p_ivot.barIndex
                trailing.lastTopTime    := p_ivot.barTime

            if showSwingsInput and not internal
                drawLabel(time[size], p_ivot.currentLevel, p_ivot.currentLevel > p_ivot.lastLevel ? 'HH' : 'LH', swingBearishColor, label.style_label_down)

drawStructure(pivot p_ivot, string tag, color structureColor, string lineStyle, string labelStyle, string labelSize) =>
    var line l_ine      = line.new(na,na,na,na,xloc = xloc.bar_time)
    var label l_abel    = label.new(na,na)

    if modeInput == PRESENT
        l_ine.delete()
        l_abel.delete()

    l_ine   := line.new(chart.point.new(p_ivot.barTime,na,p_ivot.currentLevel), chart.point.new(time,na,p_ivot.currentLevel), xloc.bar_time, color=structureColor, style=lineStyle)
    l_abel  := label.new(chart.point.new(na,math.round(0.5*(p_ivot.barIndex+bar_index)),p_ivot.currentLevel), tag, xloc.bar_index, color=color(na), textcolor=structureColor, style=labelStyle, size = labelSize)

displayStructure(bool internal = false) =>
    var bullishBar = true
    var bearishBar = true

    if internalFilterConfluenceInput
        bullishBar := high - math.max(close, open) > math.min(close, open - low)
        bearishBar := high - math.max(close, open) < math.min(close, open - low)

    pivot p_ivot    = internal ? internalHigh : swingHigh
    trend t_rend    = internal ? internalTrend : swingTrend

    lineStyle       = internal ? line.style_dashed : line.style_solid
    labelSize       = internal ? internalStructureSize : swingStructureSize

    extraCondition  = internal ? internalHigh.currentLevel != swingHigh.currentLevel and bullishBar : true
    bullishColor    = styleInput == MONOCHROME ? MONO_BULLISH : internal ? internalBullColorInput : swingBullColorInput

    if ta.crossover(close,p_ivot.currentLevel) and not p_ivot.crossed and extraCondition
        if t_rend.bias == BULLISH
            string tag = BOS

            if internal
                currentAlerts.internalBullishBOS    := true
            else
                currentAlerts.swingBullishBOS    := true

            displayCondition = internal ? showInternalsInput and (showInternalBullInput == ALL or showInternalBullInput == BOS) : showStructureInput and (showSwingBullInput == ALL or showSwingBullInput == BOS)

            if displayCondition
                drawStructure(p_ivot,tag,bullishColor,lineStyle,label.style_label_down,labelSize)

        p_ivot.crossed  := true
        t_rend.bias     := BULLISH

    p_ivot          := internal ? internalLow : swingLow
    extraCondition  := internal ? internalLow.currentLevel != swingLow.currentLevel and bearishBar : true
    bearishColor    = styleInput == MONOCHROME ? MONO_BEARISH : internal ? internalBearColorInput : swingBearColorInput

    if ta.crossunder(close,p_ivot.currentLevel) and not p_ivot.crossed and extraCondition
        if t_rend.bias == BEARISH
            string tag = BOS

            if internal
                currentAlerts.internalBearishBOS    := true
            else
                currentAlerts.swingBearishBOS    := true

            displayCondition = internal ? showInternalsInput and (showInternalBearInput == ALL or showInternalBearInput == BOS) : showStructureInput and (showSwingBearInput == ALL or showSwingBearInput == BOS)

            if displayCondition
                drawStructure(p_ivot,tag,bearishColor,lineStyle,label.style_label_up,labelSize)

        p_ivot.crossed := true
        t_rend.bias := BEARISH

updateTrailingExtremes() =>
    trailing.top            := math.max(high,trailing.top)
    trailing.lastTopTime    := trailing.top == high ? time : trailing.lastTopTime
    trailing.bottom         := math.min(low,trailing.bottom)
    trailing.lastBottomTime := trailing.bottom == low ? time : trailing.lastBottomTime

drawHighLowSwings() =>
    var line topLine        = line.new(na, na, na, na, color = swingBearishColor, xloc = xloc.bar_time)
    var line bottomLine     = line.new(na, na, na, na, color = swingBullishColor, xloc = xloc.bar_time)
    var label topLabel      = label.new(na, na, color=color(na), textcolor = color.new(color.white, 100), xloc = xloc.bar_time, style = label.style_label_down, size = size.tiny)
    var label bottomLabel   = label.new(na, na, color=color(na), textcolor = color.new(color.white, 100), xloc = xloc.bar_time, style = label.style_label_up, size = size.tiny)

    rightTimeBar            = last_bar_time + 20 * (time - time[1])

    topLine.set_first_point(    chart.point.new(trailing.lastTopTime, na, trailing.top))
    topLine.set_second_point(   chart.point.new(rightTimeBar, na, trailing.top))
    topLabel.set_point(         chart.point.new(rightTimeBar, na, trailing.top))
    topLabel.set_text(          swingTrend.bias == BEARISH ? 'Strong High' : 'Weak High')

    bottomLine.set_first_point( chart.point.new(trailing.lastBottomTime, na, trailing.bottom))
    bottomLine.set_second_point(chart.point.new(rightTimeBar, na, trailing.bottom))
    bottomLabel.set_point(      chart.point.new(rightTimeBar, na, trailing.bottom))
    bottomLabel.set_text(       swingTrend.bias == BULLISH ? 'Strong Low' : 'Weak Low')

calc_divergence(n, label_suffix) =>
    Pivot_UP   = ta.pivothigh(n, n)
    Pivot_Down = ta.pivotlow(n, n)

    High1_Price = ta.valuewhen(Pivot_UP, high[n], 0)
    High2_Price = ta.valuewhen(Pivot_UP, high[n], 1)
    High1_Bar   = ta.valuewhen(Pivot_UP, bar_index[n], 0)
    High2_Bar   = ta.valuewhen(Pivot_UP, bar_index[n], 1)

    Simb_Compar_High1_Price = invert_symbol ? ta.valuewhen(Pivot_UP, Low[n], 0) : ta.valuewhen(Pivot_UP, High[n], 0)
    Simb_Compar_High2_Price = invert_symbol ? ta.valuewhen(Pivot_UP, Low[n], 1) : ta.valuewhen(Pivot_UP, High[n], 1)
    Simb_Compar_High1_Bar   = ta.valuewhen(Pivot_UP, bar_index[n], 0)
    Simb_Compar_High2_Bar   = ta.valuewhen(Pivot_UP, bar_index[n], 1)

    Simb_Compar_High1_Price_2 = invert_symbol_2 ? ta.valuewhen(Pivot_UP, Low_2[n], 0) : ta.valuewhen(Pivot_UP, High_2[n], 0)
    Simb_Compar_High2_Price_2 = invert_symbol_2 ? ta.valuewhen(Pivot_UP, Low_2[n], 1) : ta.valuewhen(Pivot_UP, High_2[n], 1)
    Simb_Compar_High1_Bar_2   = ta.valuewhen(Pivot_UP, bar_index[n], 0)
    Simb_Compar_High2_Bar_2   = ta.valuewhen(Pivot_UP, bar_index[n], 1)

    Low1_Price = ta.valuewhen(Pivot_Down, low[n], 0)
    Low2_Price = ta.valuewhen(Pivot_Down, low[n], 1)
    Low1_Bar   = ta.valuewhen(Pivot_Down, bar_index[n], 0)
    Low2_Bar   = ta.valuewhen(Pivot_Down, bar_index[n], 1)

    Simb_Compar_Low1_Price = invert_symbol ? ta.valuewhen(Pivot_Down, High[n], 0) : ta.valuewhen(Pivot_Down, Low[n], 0)
    Simb_Compar_Low2_Price = invert_symbol ? ta.valuewhen(Pivot_Down, High[n], 1) : ta.valuewhen(Pivot_Down, Low[n], 1)
    Simb_Compar_Low1_Bar   = ta.valuewhen(Pivot_Down, bar_index[n], 0)
    Simb_Compar_Low2_Bar   = ta.valuewhen(Pivot_Down, bar_index[n], 1)

    Simb_Compar_Low1_Price_2 = invert_symbol_2 ? ta.valuewhen(Pivot_Down, High_2[n], 0) : ta.valuewhen(Pivot_Down, Low_2[n], 0)
    Simb_Compar_Low2_Price_2 = invert_symbol_2 ? ta.valuewhen(Pivot_Down, High_2[n], 1) : ta.valuewhen(Pivot_Down, Low_2[n], 1)
    Simb_Compar_Low1_Bar_2   = ta.valuewhen(Pivot_Down, bar_index[n], 0)
    Simb_Compar_Low2_Bar_2   = ta.valuewhen(Pivot_Down, bar_index[n], 1)

    Slope_High_Graph            = get_slope(High2_Price, High1_Price, High2_Bar, High1_Bar)
    Slope_High_Simb_Comparbol   = get_slope(Simb_Compar_High2_Price, Simb_Compar_High1_Price, Simb_Compar_High2_Bar, Simb_Compar_High1_Bar)
    Slope_High_Simb_Comparbol_2 = get_slope(Simb_Compar_High2_Price_2, Simb_Compar_High1_Price_2, Simb_Compar_High2_Bar_2, Simb_Compar_High1_Bar_2)

    Slope_Low_Graph            = get_slope(Low2_Price, Low1_Price, Low2_Bar, Low1_Bar)
    Slope_Low_Simb_Comparbol   = get_slope(Simb_Compar_Low2_Price, Simb_Compar_Low1_Price, Simb_Compar_Low2_Bar, Simb_Compar_Low1_Bar)
    Slope_Low_Simb_Comparbol_2 = get_slope(Simb_Compar_Low2_Price_2, Simb_Compar_Low1_Price_2, Simb_Compar_Low2_Bar_2, Simb_Compar_Low1_Bar_2)

    Bearish_Divergence   = (Slope_High_Graph > 0 and Slope_High_Simb_Comparbol < 0)   or (Slope_High_Graph < 0 and Slope_High_Simb_Comparbol > 0)
    Bearish_Divergence_2 = (Slope_High_Graph > 0 and Slope_High_Simb_Comparbol_2 < 0) or (Slope_High_Graph < 0 and Slope_High_Simb_Comparbol_2 > 0)

    Bullish_Divergence   = (Slope_Low_Graph > 0 and Slope_Low_Simb_Comparbol < 0)   or (Slope_Low_Graph < 0 and Slope_Low_Simb_Comparbol > 0)
    Bullish_Divergence_2 = (Slope_Low_Graph > 0 and Slope_Low_Simb_Comparbol_2 < 0) or (Slope_Low_Graph < 0 and Slope_Low_Simb_Comparbol_2 > 0)

    var line bull_1   = na
    var line bull_2   = na
    var line bear_1   = na
    var line bear_2   = na
    var label lbull_1 = na
    var label lbull_2 = na
    var label lbear_1 = na
    var label lbear_2 = na

    if Bearish_Divergence and Line_DOWN and (Simb_1 == true)
        if isNewLine(High2_Bar, High2_Price, High1_Bar, High1_Price)
            bear_1 := line.new(High2_Bar, High2_Price, High1_Bar, High1_Price, color=hLine_c, width=1)
            lbear_1 := label.new((High2_Bar + High1_Bar) / 2, (High2_Price + High1_Price) / 2, "Bearish SMT", style=label.style_label_down, color=#ff525200, textcolor=hLine_c, size=size.small)
        if HIST == false
            line.delete(bear_1[1])
            label.delete(lbear_1[1])

    if Bullish_Divergence and Line_UP and (Simb_1 == true)
        if isNewLine(Low2_Bar, Low2_Price, Low1_Bar, Low1_Price)
            bull_1 := line.new(Low2_Bar, Low2_Price, Low1_Bar, Low1_Price, color=lLine_c, width=1)
            lbull_1 := label.new((Low2_Bar + Low1_Bar) / 2, (Low2_Price + Low1_Price) / 2, "Bullish SMT", style=label.style_label_up, color=#4caf4f00, textcolor=lLine_c, size=size.small)
        if HIST == false
            line.delete(bull_1[1])
            label.delete(lbull_1[1])

    if Bearish_Divergence_2 and Line_DOWN and (Simb_2 == true)
        if isNewLine(High2_Bar, High2_Price, High1_Bar, High1_Price)
            bear_2  := line.new(High2_Bar, High2_Price, High1_Bar, High1_Price, color=hLine_c, width=1)
            lbear_2 := label.new((High2_Bar + High1_Bar) / 2, (High2_Price + High1_Price) / 2, "Bearish SMT", style=label.style_label_down, color=#ff525200, textcolor=hLine_c, size=size.small)
        if HIST == false
            line.delete(bear_2[1])
            label.delete(lbear_2[1])

    if Bullish_Divergence_2 and Line_UP and (Simb_2 == true)
        if isNewLine(Low2_Bar, Low2_Price, Low1_Bar, Low1_Price)
            bull_2  := line.new(Low2_Bar, Low2_Price, Low1_Bar, Low1_Price, color=lLine_c, width=1)
            lbull_2 := label.new((Low2_Bar + Low1_Bar) / 2, (Low2_Price + Low1_Price) / 2, "Bullish SMT", style=label.style_label_up, color=#4caf4f00, textcolor=lLine_c, size=size.small)
        if HIST == false
            line.delete(bull_2[1])
            label.delete(lbull_2[1])

parsedOpen  = enableBOS and showTrendInput ? open : na
candleColor = enableBOS ? (internalTrend.bias == BULLISH ? swingBullishColor : swingBearishColor) : na

plotcandle(parsedOpen, high, low, close, color = candleColor, wickcolor = candleColor, bordercolor = candleColor)

if enableBOS
    if showHighLowSwingsInput
        updateTrailingExtremes()
        drawHighLowSwings()

    getCurrentStructure(swingsLengthInput,false)
    getCurrentStructure(5,true)

    if showInternalsInput or showTrendInput
        displayStructure(true)

    if showStructureInput or showHighLowSwingsInput
        displayStructure()

    lastBarIndex    := currentBarIndex
    currentBarIndex := bar_index

if enableSMT
    if n1_true and not (timeframe.isminutes and timeframe.multiplier == 60) and not (timeframe.isminutes and timeframe.multiplier == 240) and not (timeframe.isminutes and timeframe.multiplier == 15) and not (timeframe.isminutes and timeframe.multiplier == 5)
        calc_divergence(n1, "D1")

    if n2_true and (timeframe.period == "5" or timeframe.period == "15")
        calc_divergence(n2, "D2")

    if n3_true and timeframe.period == "60"
        calc_divergence(n3, "D3")

    if n4_true and timeframe.period == "240"
        calc_divergence(n4, "D4")

alertcondition(currentAlerts.internalBullishBOS, 'Internal Bullish BOS', 'Internal Bullish BOS formed')
alertcondition(currentAlerts.internalBearishBOS, 'Internal Bearish BOS', 'Internal Bearish BOS formed')
alertcondition(currentAlerts.swingBullishBOS, 'Bullish BOS', 'Bullish BOS formed')
alertcondition(currentAlerts.swingBearishBOS, 'Bearish BOS', 'Bearish BOS formed')

//-----------------------------------------------SYNTHICATOR--------------------------------------------------------
