//@version=5
indicator("TA Capital Research SMAs", overlay=true)

// Inputs for SMA lengths
smaShort = input.int(20, "SMA 20")
smaMedium = input.int(50, "SMA 50")
smaLong = input.int(200, "SMA 200")

// Calculate SMAs
sma20 = ta.sma(close, smaShort)
sma50 = ta.sma(close, smaMedium)
sma200 = ta.sma(close, smaLong)

// Plot SMAs with colors
plot(sma20, title="SMA 20", color=color.new(#9f1c1c, 0), linewidth=1)
plot(sma50, title="SMA 50", color=color.new(#009be3, 0), linewidth=1)
plot(sma200, title="SMA 200", color=color.new(#ff0000, 0), linewidth=1)
