// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © jwatt123

//@version=6
indicator("Webby's Simple Fib. Trend", "WSFT", overlay=false)


//---------------------------------------------------------
// User settings
//---------------------------------------------------------

src = input.source(close, "Comparison point", display=display.none)

showIdx = input.bool(false, "Show index for comparison", inline="i1")
idx = input.symbol("SP:SPX", "", inline="i1", active=showIdx)


//---------------------------------------------------------
// Plot moving averages on main chart
//---------------------------------------------------------

var disp = display.all - display.status_line

ma1 = ta.ema(src, 3)
ma2 = ta.ema(src, 5)
ma3 = ta.ema(src, 8)
ma4 = ta.ema(src, 13)
ma5 = ta.ema(src, 21)
ma6 = ta.ema(src, 34)
ma7 = ta.ema(src, 55)
ma8 = ta.ema(src, 89)
ma9 = ta.ema(src, 144)
ma10 = ta.ema(src, 233)

plot(ma1, "3-day", #DF2D49, 1, display=disp, force_overlay=true)
plot(ma2, "5-day", #FF9B35, 1, display=disp, force_overlay=true)
plot(ma3, "8-day", #E4E800, 1, display=disp, force_overlay=true)
plot(ma4, "13-day", #037306, 1, display=disp, force_overlay=true)
plot(ma5, "21-day", #1B85EC, 2, display=disp, force_overlay=true)
plot(ma6, "34-day", #0300B7, 1, display=disp, force_overlay=true)
plot(ma7, "55-day", #7C29CF, 1, display=disp, force_overlay=true)
plot(ma8, "89-day", #E6754A, 1, display=disp, force_overlay=true)
plot(ma9, "144-day", #E401E0, 1, display=disp, force_overlay=true)
plot(ma10, "233-day", #02E5E4, 1, display=disp, force_overlay=true)


//---------------------------------------------------------
// Plot Webby's Simple Fibonacci Trend Indicator for the current instrument
//---------------------------------------------------------

getScore(ma1, ma2, ma3, ma4, ma5, ma6, ma7, ma8, ma9, ma10) => (
    (ma1 > ma2 ? 1 : 0) +
    (ma1 > ma3 ? 1 : 0) +
    (ma1 > ma4 ? 1 : 0) +
    (ma1 > ma5 ? 1 : 0) +
    (ma1 > ma6 ? 1 : 0) +
    (ma1 > ma7 ? 1 : 0) +
    (ma1 > ma8 ? 1 : 0) +
    (ma1 > ma9 ? 1 : 0) +
    (ma1 > ma10 ? 1 : 0) +

    (ma2 > ma3 ? 1 : 0) +
    (ma2 > ma4 ? 1 : 0) +
    (ma2 > ma5 ? 1 : 0) +
    (ma2 > ma6 ? 1 : 0) +
    (ma2 > ma7 ? 1 : 0) +
    (ma2 > ma8 ? 1 : 0) +
    (ma2 > ma9 ? 1 : 0) +
    (ma2 > ma10 ? 1 : 0) +

    (ma3 > ma4 ? 1 : 0) +
    (ma3 > ma5 ? 1 : 0) +
    (ma3 > ma6 ? 1 : 0) +
    (ma3 > ma7 ? 1 : 0) +
    (ma3 > ma8 ? 1 : 0) +
    (ma3 > ma9 ? 1 : 0) +
    (ma3 > ma10 ? 1 : 0) +

    (ma4 > ma5 ? 1 : 0) +
    (ma4 > ma6 ? 1 : 0) +
    (ma4 > ma7 ? 1 : 0) +
    (ma4 > ma8 ? 1 : 0) +
    (ma4 > ma9 ? 1 : 0) +
    (ma4 > ma10 ? 1 : 0) +

    (ma5 > ma6 ? 1 : 0) +
    (ma5 > ma7 ? 1 : 0) +
    (ma5 > ma8 ? 1 : 0) +
    (ma5 > ma9 ? 1 : 0) +
    (ma5 > ma10 ? 1 : 0) +

    (ma6 > ma7 ? 1 : 0) +
    (ma6 > ma8 ? 1 : 0) +
    (ma6 > ma9 ? 1 : 0) +
    (ma6 > ma10 ? 1 : 0) +

    (ma7 > ma8 ? 1 : 0) +
    (ma7 > ma9 ? 1 : 0) +
    (ma7 > ma10 ? 1 : 0) +

    (ma8 > ma9 ? 1 : 0) +
    (ma8 > ma10 ? 1 : 0) +

    (ma9 > ma10 ? 1 : 0)
)


hline(40, color=color.green, linestyle=hline.style_solid)
hline(35, color=color.yellow, linestyle=hline.style_solid)
hline(30, color=color.red, linestyle=hline.style_solid)
plot(getScore(ma1, ma2, ma3, ma4, ma5, ma6, ma7, ma8, ma9, ma10), "WSFT", color=#1A87E5, linewidth=2)


//---------------------------------------------------------
// Optional: Additionally plot Webby's Simple Fibonacci Trend Indicator for a user supplied index
//---------------------------------------------------------

float ima1 = na
float ima2 = na
float ima3 = na
float ima4 = na
float ima5 = na
float ima6 = na
float ima7 = na
float ima8 = na
float ima9 = na
float ima10 = na
float iScore = na

if showIdx
    [m1, m2, m3, m4, m5, m6, m7, m8, m9, m10] = request.security(idx, "", [
        ta.ema(src, 3),
        ta.ema(src, 5),
        ta.ema(src, 8),
        ta.ema(src, 13),
        ta.ema(src, 21),
        ta.ema(src, 34),
        ta.ema(src, 55),
        ta.ema(src, 89),
        ta.ema(src, 144),
        ta.ema(src, 233)
    ], lookahead=barmerge.lookahead_on)
    ima1 := m1
    ima2 := m2
    ima3 := m3
    ima4 := m4
    ima5 := m5
    ima6 := m6
    ima7 := m7
    ima8 := m8
    ima9 := m9
    ima10 := m10
    iScore := getScore(ima1, ima2, ima3, ima4, ima5, ima6, ima7, ima8, ima9, ima10)

plot(iScore, "Index WSFT", color=color.gray, linewidth=1)
