"""
DS-TV Backtest Results: 1w-strategy-scanner
============================================================

--- SPY ---
  ERROR: -1

--- BTC ---
  ERROR: -1

--- QQQ ---
  ERROR: -1

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 1w-strategy-scanner
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema50_len = 50
    ema200_len = 200
    rsi_len = 14
    rsi_min = 50
    rsi_max = 80
    ext_max = 20.0
    vol_min = 500000

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        self.w_ema50 = self.I(pta.ema, close, length=self.ema50_len)
        self.w_ema200 = self.I(pta.ema, close, length=self.ema200_len)
        self.w_rsi = self.I(pta.rsi, close, length=self.rsi_len)

        self.w_52h = self.I(lambda: high.rolling(52).max())
        self.w_52l = self.I(lambda: low.rolling(52).min())

        self.w_volume = volume

    def next(self):
        if len(self.data) < max(self.ema50_len, self.ema200_len, 52):
            return

        w_close = self.data.Close[-1]
        w_volume = self.w_volume[-1]
        w_ema50 = self.w_ema50[-1]
        w_ema200 = self.w_ema200[-1]
        w_rsi = self.w_rsi[-1]
        w_52h = self.w_52h[-1]
        w_52l = self.w_52l[-1]

        if pd.isna(w_ema50) or pd.isna(w_ema200) or pd.isna(w_rsi) or pd.isna(w_52h) or pd.isna(w_52l):
            return

        c1 = w_close > w_ema200
        c2 = w_close > w_ema50
        c3 = w_rsi >= self.rsi_min and w_rsi <= self.rsi_max
        dist_from_ema50 = (w_close - w_ema50) / w_ema50 * 100 if w_ema50 != 0 else 0
        c4 = dist_from_ema50 <= self.ext_max
        c5 = w_ema50 > w_ema200
        
        w_ema200_4 = self.w_ema200[-5] if len(self.w_ema200) >= 5 else self.w_ema200[-1]
        c6 = w_ema200 > w_ema200_4
        
        c7 = w_volume >= self.vol_min
        
        mid52 = (w_52h + w_52l) / 2
        c8 = w_close >= mid52

        score = sum([c1, c2, c3, c4, c5, c6, c7, c8])

        signal_strong = c1 and c2 and c3 and c4 and c5 and c6 and c7 and c8
        signal_watch = c1 and c2 and c3 and c7 and score >= 6

        if signal_strong and not self.position:
            self.buy()
        elif not signal_strong and not signal_watch and self.position:
            self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()