"""
DS-TV Backtest Results: adaptive-volatility-squeeze-ukutalabs
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(λ,29)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "ema(λ,29)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(λ,29)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — adaptive-volatility-squeeze-ukutalabs
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    LengthBB = 20
    MultiplierBB = 2.0
    LengthKC = 20
    MultiplierKC = 1.5
    PressureFast = 8
    PressureSlow = 21
    LengthVolume = 20
    MultiplierVolume = 1.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Bollinger Bands
        basis = self.I(pta.sma, close, length=self.LengthBB)
        deviation = self.I(lambda x: x.rolling(self.LengthBB).std(), close)
        self.upper_bb = self.I(lambda: basis + deviation * self.MultiplierBB)
        self.lower_bb = self.I(lambda: basis - deviation * self.MultiplierBB)
        self.width_bb = self.I(lambda: self.upper_bb - self.lower_bb)
        
        # Keltner Channel
        ema_kc = self.I(pta.ema, close, length=self.LengthKC)
        atr_kc = self.I(pta.atr, high, low, close, length=self.LengthKC)
        self.upper_kc = self.I(lambda: ema_kc + atr_kc * self.MultiplierKC)
        self.lower_kc = self.I(lambda: ema_kc - atr_kc * self.MultiplierKC)
        self.width_kc = self.I(lambda: self.upper_kc - self.lower_kc)
        
        # Squeeze Ratio
        self.squeeze_ratio = self.I(lambda: self.width_bb / self.width_kc)
        
        # Directional Pressure
        fast_ema = self.I(pta.ema, close, length=self.PressureFast)
        slow_ema = self.I(pta.ema, close, length=self.PressureSlow)
        self.pressure = self.I(lambda: fast_ema - slow_ema)
        self.pressure_ma = self.I(pta.ema, self.pressure, length=self.PressureFast + self.PressureSlow)
        
        # Volume Expansion
        volume_ma = self.I(pta.sma, close, length=self.LengthVolume)
        self.volume_expansion = self.I(lambda: close > volume_ma * self.MultiplierVolume)
        
        # Squeeze On
        self.squeeze_on = self.I(lambda: self.squeeze_ratio < 1.0)

    def next(self):
        squeeze_on = self.squeeze_on[-1]
        pressure = self.pressure[-1]
        volume_exp = self.volume_expansion[-1]
        squeeze_ratio = self.squeeze_ratio[-1]
        
        # Entry signals based on squeeze and pressure
        if squeeze_on and pressure > 0 and volume_exp:
            if not self.position:
                self.buy()
        elif squeeze_on and pressure < 0 and volume_exp:
            if self.position:
                self.sell()
        
        # Exit based on pressure reversal
        if self.position:
            if crossover(self.pressure_ma, self.pressure):
                self.sell()
        
        # Entry on pressure crossover with squeeze
        if not self.position:
            if crossover(self.pressure, self.pressure_ma) and squeeze_on:
                self.buy()


if __name__ == "__main__":
    from datetime import datetime
    
    bt = Backtest(pd.read_csv('data.csv', index_col=0, parse_dates=True), 
                  TvStrategy, 
                  cash=10000, 
                  commission=.002)
    
    stats = bt.run()
    print(stats)