"""
DS-TV Backtest Results: adx-squeeze-breakout-screener
============================================================

--- SPY ---
  Return                    -47.91%
  Buy & Hold Return         17.90%
  Max Drawdown              -54.31%
  Sharpe Ratio              -2.75
  Sortino Ratio             -2.47
  Calmar Ratio              -0.52
  Profit Factor             0.52
  Expectancy                -0.26%
  SQN                       -2.34
  # Trades                  241
  Win Rate                  36.10%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.27%
  Exposure Time             49.60%
  Equity Final              52086.28$
  Equity Peak               113992.15$
  Avg Drawdown              -7.35%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -28.02%
  Ann. Volatility           10.19%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         17.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    -48.09%
  Buy & Hold Return         22.08%
  Max Drawdown              -57.71%
  Sharpe Ratio              -2.31
  Sortino Ratio             -2.12
  Calmar Ratio              -0.49
  Profit Factor             0.61
  Expectancy                -0.26%
  SQN                       -1.93
  # Trades                  238
  Win Rate                  37.39%
  Best Trade                6.54%
  Worst Trade               -9.35%
  Avg Trade                 -0.27%
  Exposure Time             49.60%
  Equity Final              51907.25$
  Equity Peak               121249.48$
  Avg Drawdown              -7.91%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        10 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -28.14%
  Ann. Volatility           12.16%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — adx-squeeze-breakout-screener
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema200_period = 200
    sma18_period = 18
    sma_lookback = 10
    adx_period = 14
    adx_coil_level = 12.0
    adx_lookback = 10

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema200 = self.I(pta.ema, close, length=self.ema200_period)
        self.sma18 = self.I(pta.sma, close, length=self.sma18_period)
        
        self.sma_slope = self.I(self._calculate_sma_slope, close, high, low)
        self.adx_value = self.I(self._calculate_adx, high, low, close)
        self.min_adx = self.I(self._calculate_min_adx, high, low, close)

    def _calculate_sma_slope(self, close, high, low):
        sma18 = pta.sma(close, length=self.sma18_period)
        if sma18 is None or len(sma18) < self.sma_lookback + 1:
            return pd.Series(0, index=close.index)
        sma18_ago = sma18.shift(self.sma_lookback)
        slope = sma18 - sma18_ago
        return slope.fillna(0)

    def _calculate_adx(self, high, low, close):
        up = high.diff()
        down = -low.diff()
        
        plus_dm = pd.Series(0.0, index=high.index)
        minus_dm = pd.Series(0.0, index=high.index)
        
        for i in range(1, len(high)):
            if up.iloc[i] > down.iloc[i] and up.iloc[i] > 0:
                plus_dm.iloc[i] = up.iloc[i]
            if down.iloc[i] > up.iloc[i] and down.iloc[i] > 0:
                minus_dm.iloc[i] = down.iloc[i]
        
        tr = pd.concat([
            high - low,
            (high - close.shift(1)).abs(),
            (low - close.shift(1)).abs()
        ], axis=1).max(axis=1)
        
        atr_v = tr.ewm(span=self.adx_period, adjust=False).mean()
        atr_v = atr_v.replace(0, 1e-10)
        
        plus_di = (plus_dm.ewm(span=self.adx_period, adjust=False).mean() / atr_v * 100).fillna(0)
        minus_di = (minus_dm.ewm(span=self.adx_period, adjust=False).mean() / atr_v * 100).fillna(0)
        
        di_sum = plus_di + minus_di
        di_sum = di_sum.replace(0, 1e-10)
        
        dx = ((plus_di - minus_di).abs() / di_sum * 100).fillna(0)
        adx_v = dx.ewm(span=self.adx_period, adjust=False).mean()
        
        return adx_v.fillna(0)

    def _calculate_min_adx(self, high, low, close):
        adx_v = self._calculate_adx(high, low, close)
        adx_prev = adx_v.shift(1)
        min_adx = adx_prev.rolling(window=self.adx_lookback).min()
        return min_adx.fillna(adx_v)

    def next(self):
        if len(self.data) < max(self.ema200_period, self.sma18_period + self.sma_lookback, self.adx_lookback + 1):
            return
        
        close = self.data.Close[-1]
        ema200_val = self.ema200[-1]
        sma_slope_val = self.sma_slope[-1]
        adx_val = self.adx_value[-1]
        adx_prev_val = self.adx_value[-2] if len(self.adx_value) > 1 else adx_val
        min_adx_val = self.min_adx[-1]
        
        f1 = close > ema200_val
        f2 = sma_slope_val > 0
        f3a = min_adx_val < self.adx_coil_level
        f3b = adx_val > adx_prev_val
        
        passes = f1 and f2 and f3a and f3b
        
        if passes and not self.position:
            self.buy()
        elif not passes and self.position:
            self.sell()