"""
DS-TV Backtest Results: aethix-3-market-cipher-g-ultimate
============================================================

--- SPY ---
  Return                    4.85%
  Buy & Hold Return         37.08%
  Max Drawdown              -12.47%
  Sharpe Ratio              0.28
  Sortino Ratio             0.38
  Calmar Ratio              0.19
  Profit Factor             1.19
  Expectancy                0.14%
  SQN                       0.33
  # Trades                  41
  Win Rate                  51.22%
  Best Trade                5.72%
  Worst Trade               -7.60%
  Avg Trade                 0.12%
  Exposure Time             52.60%
  Equity Final              104853.64$
  Equity Peak               107109.31$
  Avg Drawdown              -3.27%
  Max Drawdown Duration     300 days 00:00:00
  Max Trade Duration        19 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               2.42%
  Ann. Volatility           8.78%

--- BTC ---
  Return                    28.33%
  Buy & Hold Return         1.03%
  Max Drawdown              -13.31%
  Sharpe Ratio              0.54
  Sortino Ratio             0.99
  Calmar Ratio              1.00
  Profit Factor             1.62
  Expectancy                0.73%
  SQN                       0.95
  # Trades                  58
  Win Rate                  36.21%
  Best Trade                16.05%
  Worst Trade               -6.95%
  Avg Trade                 0.62%
  Exposure Time             51.16%
  Equity Final              128334.70$
  Equity Peak               142852.34$
  Avg Drawdown              -4.45%
  Max Drawdown Duration     176 days 00:00:00
  Max Trade Duration        17 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               13.27%
  Ann. Volatility           24.38%

--- QQQ ---
  Return                    8.16%
  Buy & Hold Return         40.87%
  Max Drawdown              -12.07%
  Sharpe Ratio              0.32
  Sortino Ratio             0.44
  Calmar Ratio              0.33
  Profit Factor             1.27
  Expectancy                0.23%
  SQN                       0.42
  # Trades                  42
  Win Rate                  52.38%
  Best Trade                8.50%
  Worst Trade               -10.16%
  Avg Trade                 0.19%
  Exposure Time             53.40%
  Equity Final              108160.12$
  Equity Peak               110794.25$
  Avg Drawdown              -4.16%
  Max Drawdown Duration     276 days 00:00:00
  Max Trade Duration        19 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               4.03%
  Ann. Volatility           12.69%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — aethix-3-market-cipher-g-ultimate
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # WaveTrend parameters
    wtChLen = 9
    wtAvgLen = 12
    wtMALen = 3
    
    # Money Flow parameters
    mfiLen = 60
    mfiMult = 150.0
    mfiPosY = 0.0
    
    # RSI parameters
    rsiLen = 14
    rsiOB = 60
    rsiOS = 30
    rsiOffset = 25.0
    
    # Divergence parameters
    divLookback = 5

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        hlc3 = (high + low + close) / 3
        
        # WaveTrend calculation
        def calc_wavetrend():
            esa = pta.ema(hlc3, length=self.wtChLen)
            de = pta.ema((hlc3 - esa).abs(), length=self.wtChLen)
            ci = (hlc3 - esa) / (0.015 * de)
            wt1 = pta.ema(ci, length=self.wtAvgLen)
            wt2 = pta.sma(wt1, length=self.wtMALen)
            return wt1, wt2
        
        self.wt1_series = self.I(lambda: calc_wavetrend()[0])
        self.wt2_series = self.I(lambda: calc_wavetrend()[1])
        
        # Money Flow calculation
        def calc_mfi():
            mfi = pta.sma(((close - open_) / (high - low)) * self.mfiMult, length=self.mfiLen) + self.mfiPosY
            return mfi
        
        self.mfi = self.I(calc_mfi)
        
        # RSI calculation
        self.rsi_val = self.I(pta.rsi, close, length=self.rsiLen)
        
        # Create final RSI with offset
        def calc_final_rsi():
            rsi = pta.rsi(close, length=self.rsiLen)
            if rsi is None:
                return pd.Series(self.rsiOffset, index=close.index)
            return rsi + self.rsiOffset
        
        self.final_rsi = self.I(calc_final_rsi)

    def next(self):
        # Simple trading logic based on WaveTrend crossovers
        if len(self.data) < self.divLookback + 1:
            return
        
        # Buy signal: wt1 crosses above wt2
        if crossover(self.wt1_series, self.wt2_series):
            if not self.position:
                self.buy()
        
        # Sell signal: wt1 crosses below wt2
        elif crossover(self.wt2_series, self.wt1_series):
            if self.position:
                self.position.close()