"""
DS-TV Backtest Results: ao-31-williams-fraktal-alligator-sinyali
============================================================

--- SPY ---
  Return                    -20.29%
  Buy & Hold Return         35.76%
  Max Drawdown              -20.91%
  Sharpe Ratio              -1.01
  Sortino Ratio             -1.13
  Calmar Ratio              -0.52
  Profit Factor             0.57
  Expectancy                -0.39%
  SQN                       -1.72
  # Trades                  51
  Win Rate                  37.25%
  Best Trade                3.35%
  Worst Trade               -4.62%
  Avg Trade                 -0.41%
  Exposure Time             59.40%
  Equity Final              79710.25$
  Equity Peak               100778.02$
  Avg Drawdown              -5.44%
  Max Drawdown Duration     573 days 00:00:00
  Max Trade Duration        22 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               -10.80%
  Ann. Volatility           10.73%

--- BTC ---
  Return                    -21.78%
  Buy & Hold Return         -2.17%
  Max Drawdown              -34.05%
  Sharpe Ratio              -0.65
  Sortino Ratio             -0.79
  Calmar Ratio              -0.34
  Profit Factor             0.74
  Expectancy                -0.64%
  SQN                       -0.84
  # Trades                  34
  Win Rate                  26.47%
  Best Trade                22.85%
  Worst Trade               -11.25%
  Avg Trade                 -0.81%
  Exposure Time             28.18%
  Equity Final              78223.83$
  Equity Peak               118611.20$
  Avg Drawdown              -8.02%
  Max Drawdown Duration     445 days 00:00:00
  Max Trade Duration        19 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               -11.54%
  Ann. Volatility           17.74%

--- QQQ ---
  Return                    -6.79%
  Buy & Hold Return         39.41%
  Max Drawdown              -18.41%
  Sharpe Ratio              -0.22
  Sortino Ratio             -0.30
  Calmar Ratio              -0.19
  Profit Factor             0.88
  Expectancy                -0.12%
  SQN                       -0.40
  # Trades                  49
  Win Rate                  44.90%
  Best Trade                5.76%
  Worst Trade               -6.49%
  Avg Trade                 -0.14%
  Exposure Time             60.00%
  Equity Final              93206.42$
  Equity Peak               114228.38$
  Avg Drawdown              -3.28%
  Max Drawdown Duration     559 days 00:00:00
  Max Trade Duration        25 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               -3.48%
  Ann. Volatility           15.57%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ao-31-williams-fraktal-alligator-sinyali
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        hl2 = (high + low) / 2
        
        # SMMA calculation using EMA with adjusted alpha
        self.jaw = self.I(self._smma_calc, hl2, 13)
        self.teeth = self.I(self._smma_calc, hl2, 8)
        self.lips = self.I(self._smma_calc, hl2, 5)
        
        # Awesome Oscillator
        sma5_hl2 = self.I(pta.sma, hl2, length=5)
        sma34_hl2 = self.I(pta.sma, hl2, length=34)
        self.ao = self.I(lambda: sma5_hl2 - sma34_hl2)
        
        # Fractal detection (shifted values)
        self.high_vals = high
        self.low_vals = low
        self.close_vals = close
        self.hl2_vals = hl2
        
        # State tracking
        self.position_state = 0
        self.entry_price = np.nan
        self.ever_in_profit = False
        
        self.green_count = 0
        self.red_count = 0
        self.after_red = False
        self.after_green = False
        self.third_green_high = np.nan
        self.third_red_low = np.nan
        self.waiting_for_buy = False
        self.waiting_for_sell = False
        
        self.ao_buy_blocked = False
        self.ao_sell_blocked = False
        
        self.last_valid_fractal_up_level = np.nan
        self.last_valid_fractal_down_level = np.nan
        
    def _smma_calc(self, series, length):
        result = pd.Series(index=series.index, dtype=float)
        smma_val = np.nan
        for i in range(len(series)):
            if np.isnan(smma_val):
                smma_val = series.iloc[:i+1].rolling(length).mean().iloc[i]
            else:
                smma_val = (smma_val * (length - 1) + series.iloc[i]) / length
            result.iloc[i] = smma_val
        return result
    
    def _get_fractal_up(self, idx):
        if idx < 4:
            return False
        h = self.data.High
        return h[idx-2] > h[idx-4] and h[idx-2] > h[idx-3] and h[idx-2] > h[idx-1] and h[idx-2] > h[idx]
    
    def _get_fractal_down(self, idx):
        if idx < 4:
            return False
        l = self.data.Low
        return l[idx-2] < l[idx-4] and l[idx-2] < l[idx-3] and l[idx-2] < l[idx-1] and l[idx-2] < l[idx]
    
    def next(self):
        idx = len(self.data) - 1
        
        if idx < 34:
            return
        
        current_high = self.data.High[idx]
        current_low = self.data.Low[idx]
        current_close = self.data.Close[idx]
        
        # AO tracking
        ao_positive = self.ao[-1] > (self.ao[-2] if len(self.ao) > 1 else self.ao[-1])
        ao_negative = self.ao[-1] < (self.ao[-2] if len(self.ao) > 1 else self.ao[-1])
        
        if ao_negative:
            self.after_red = True
            self.green_count = 0
            self.third_green_high = np.nan
            self.waiting_for_buy = False
            if self.after_green:
                self.red_count += 1
                if self.red_count == 3:
                    self.third_red_low = current_low
                    self.waiting_for_sell = True
        
        if ao_positive:
            self.after_green = True
            self.red_count = 0
            self.third_red_low = np.nan
            self.waiting_for_sell = False
            if self.after_red:
                self.green_count += 1
                if self.green_count == 3:
                    self.third_green_high = current_high
                    self.waiting_for_buy = True
        
        # AO signals
        ao_buy_raw = self.waiting_for_buy and ao_positive and current_high > self.third_green_high
        ao_sell_raw = self.waiting_for_sell and ao_negative and current_low < self.third_red_low
        
        # Block mechanism
        if self.ao_buy_blocked and ao_negative:
            self.ao_buy_blocked = False
        if self.ao_sell_blocked and ao_positive:
            self.ao_sell_blocked = False
        
        ao_buy = ao_buy_raw and not self.ao_buy_blocked
        ao_sell = ao_sell_raw and not self.ao_sell_blocked
        
        if ao_buy:
            self.ao_buy_blocked = True
        if ao_sell:
            self.ao_sell_blocked = True
        
        # Fractal signals
        fractal_up = self._get_fractal_up(idx)
        fractal_down = self._get_fractal_down(idx)
        
        teeth_at_fractal = self.teeth[-8] if len(self.teeth) > 7 else self.teeth[-1]
        
        valid_fractal_up = fractal_up and current_high > teeth_at_fractal
        valid_fractal_down = fractal_down and current_low < teeth_at_fractal
        
        fractal_up_break = not np.isnan(self.last_valid_fractal_up_level) and current_high > self.last_valid_fractal_up_level
        fractal_down_break = not np.isnan(self.last_valid_fractal_down_level) and current_low < self.last_valid_fractal_down_level
        
        if valid_fractal_up:
            self.last_valid_fractal_up_level = self.data.High[idx-2]
        if fractal_up_break:
            self.last_valid_fractal_up_level = np.nan
        
        if valid_fractal_down:
            self.last_valid_fractal_down_level = self.data.Low[idx-2]
        if fractal_down_break:
            self.last_valid_fractal_down_level = np.nan
        
        # Exit conditions
        lowest_3 = min(self.data.Low[idx-1], self.data.Low[idx-2], self.data.Low[idx-3])
        highest_3 = max(self.data.High[idx-1], self.data.High[idx-2], self.data.High[idx-3])
        
        any_buy = ao_buy or fractal_up_break
        any_sell = ao_sell or fractal_down_break
        
        exit_long_reverse = self.position_state == 1 and any_sell
        exit_short_reverse = self.position_state == -1 and any_buy
        
        exit_long_stop = self.position_state == 1 and self.ever_in_profit and current_low < lowest_3
        exit_short_stop = self.position_state == -1 and self.ever_in_profit and current_high > highest_3
        
        exit_long = exit_long_reverse or exit_long_stop
        exit_short = exit_short_reverse or exit_short_stop
        
        if exit_long or exit_short:
            if self.position:
                self.position.close()
            self.position_state = 0
            self.entry_price = np.nan
            self.ever_in_profit = False
        
        # Entry conditions
        if any_buy and self.position_state == 0:
            self.buy()
            self.position_state = 1
            self.entry_price = current_close
            self.ever_in_profit = False
        
        if any_sell and self.position_state == 0:
            self.sell()
            self.position_state = -1
            self.entry_price = current_close
            self.ever_in_profit = False
        
        # Update profit status
        if self.position_state == 1 and current_high > self.entry_price:
            self.ever_in_profit = True
        if self.position_state == -1 and current_low < self.entry_price:
            self.ever_in_profit = True


if __name__ == '__main__':
    from backtesting.test import SMA
    
    bt = Backtest(SMA, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)