"""
DS-TV Backtest Results: average-directional-index-adx-trend-thresholds-and-color
============================================================

--- SPY ---
  Return                    27.68%
  Buy & Hold Return         40.21%
  Max Drawdown              -17.36%
  Sharpe Ratio              0.82
  Sortino Ratio             1.46
  Calmar Ratio              0.75
  Profit Factor             9.26
  Expectancy                1.90%
  SQN                       3.71
  # Trades                  13
  Win Rate                  92.31%
  Best Trade                4.37%
  Worst Trade               -3.00%
  Avg Trade                 1.89%
  Exposure Time             40.00%
  Equity Final              127676.14$
  Equity Peak               127943.31$
  Avg Drawdown              -2.61%
  Max Drawdown Duration     253 days 00:00:00
  Max Trade Duration        78 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               13.10%
  Ann. Volatility           15.90%

--- BTC ---
  Return                    12.33%
  Buy & Hold Return         35.02%
  Max Drawdown              -29.02%
  Sharpe Ratio              0.21
  Sortino Ratio             0.34
  Calmar Ratio              0.21
  Profit Factor             2.77
  Expectancy                3.27%
  SQN                       1.20
  # Trades                  12
  Win Rate                  75.00%
  Best Trade                11.70%
  Worst Trade               -14.89%
  Avg Trade                 3.00%
  Exposure Time             52.53%
  Equity Final              112326.22$
  Equity Peak               148182.89$
  Avg Drawdown              -4.96%
  Max Drawdown Duration     126 days 00:00:00
  Max Trade Duration        79 days 00:00:00
  Avg Trade Duration        31 days 00:00:00
  Ann. Return               5.98%
  Ann. Volatility           28.13%

--- QQQ ---
  Return                    19.72%
  Buy & Hold Return         42.44%
  Max Drawdown              -21.89%
  Sharpe Ratio              0.48
  Sortino Ratio             0.79
  Calmar Ratio              0.43
  Profit Factor             3.33
  Expectancy                1.23%
  SQN                       1.58
  # Trades                  16
  Win Rate                  81.25%
  Best Trade                4.91%
  Worst Trade               -7.89%
  Avg Trade                 1.19%
  Exposure Time             50.80%
  Equity Final              119721.46$
  Equity Peak               122014.55$
  Avg Drawdown              -4.03%
  Max Drawdown Duration     284 days 00:00:00
  Max Trade Duration        82 days 00:00:00
  Avg Trade Duration        22 days 00:00:00
  Ann. Return               9.50%
  Ann. Volatility           19.67%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — average-directional-index-adx-trend-thresholds-and-color
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    adxlen = 14
    dilen = 14

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ADX using pandas_ta
        adx_result = self.I(lambda: pta.adx(high, low, close, length=self.dilen))
        self.adx = adx_result

    def next(self):
        # Trading logic based on ADX levels
        # Buy when ADX crosses above 25 (trend beginning/strong trend)
        # Sell when ADX crosses below 25 (trend weakening)
        
        if len(self.adx) < 2:
            return
        
        current_adx = self.adx[-1]
        prev_adx = self.adx[-2]
        
        # Buy signal: ADX crosses above 25
        if prev_adx <= 25 and current_adx > 25:
            if not self.position:
                self.buy()
        
        # Sell signal: ADX crosses below 25
        elif prev_adx >= 25 and current_adx < 25:
            if self.position:
                self.position.close()
        
        # Additional sell signal: ADX reaches extreme levels (>75) and starts declining
        elif len(self.adx) >= 2:
            if current_adx > 75 and current_adx < prev_adx:
                if self.position:
                    self.position.close()