"""
DS-TV Backtest Results: beginner-trading-assistant-educational
============================================================

--- SPY ---
  Return                    15.68%
  Buy & Hold Return         17.90%
  Max Drawdown              -18.67%
  Sharpe Ratio              0.51
  Sortino Ratio             0.83
  Calmar Ratio              0.41
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              115681.01$
  Equity Peak               115936.65$
  Avg Drawdown              -1.90%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               7.62%
  Ann. Volatility           14.90%

--- BTC ---
  Return                    23.57%
  Buy & Hold Return         17.39%
  Max Drawdown              -21.69%
  Sharpe Ratio              0.40
  Sortino Ratio             0.69
  Calmar Ratio              0.51
  Profit Factor             nan
  Expectancy                34.48%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                34.48%
  Worst Trade               34.48%
  Avg Trade                 34.48%
  Exposure Time             54.04%
  Equity Final              123569.89$
  Equity Peak               156319.99$
  Avg Drawdown              -5.74%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        394 days 00:00:00
  Avg Trade Duration        394 days 00:00:00
  Ann. Return               11.15%
  Ann. Volatility           27.56%

--- QQQ ---
  Return                    15.05%
  Buy & Hold Return         22.08%
  Max Drawdown              -22.73%
  Sharpe Ratio              0.41
  Sortino Ratio             0.66
  Calmar Ratio              0.32
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              115050.02$
  Equity Peak               118908.20$
  Avg Drawdown              -2.88%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               7.32%
  Ann. Volatility           17.80%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — beginner-trading-assistant-educational
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    emaShortLen = 50
    emaLongLen = 200
    rsiLen = 14
    atrLen = 14
    swingLen = 5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.emaShort = self.I(pta.ema, close, length=self.emaShortLen)
        self.emaLong = self.I(pta.ema, close, length=self.emaLongLen)
        self.rsi = self.I(pta.rsi, close, length=self.rsiLen)
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        self.lastHigh = None
        self.lastLow = None
        self.pivotHighValues = self._calculate_pivot_highs()
        self.pivotLowValues = self._calculate_pivot_lows()

    def _calculate_pivot_highs(self):
        high = pd.Series(self.data.High)
        pivots = []
        swing_len = self.swingLen
        
        for i in range(len(high)):
            if i < swing_len or i >= len(high) - swing_len:
                pivots.append(np.nan)
            else:
                left_high = high[i - swing_len:i].max()
                center_high = high[i]
                right_high = high[i + 1:i + swing_len + 1].max()
                
                if center_high > left_high and center_high > right_high:
                    pivots.append(center_high)
                else:
                    pivots.append(np.nan)
        
        return pivots

    def _calculate_pivot_lows(self):
        low = pd.Series(self.data.Low)
        pivots = []
        swing_len = self.swingLen
        
        for i in range(len(low)):
            if i < swing_len or i >= len(low) - swing_len:
                pivots.append(np.nan)
            else:
                left_low = low[i - swing_len:i].min()
                center_low = low[i]
                right_low = low[i + 1:i + swing_len + 1].min()
                
                if center_low < left_low and center_low < right_low:
                    pivots.append(center_low)
                else:
                    pivots.append(np.nan)
        
        return pivots

    def next(self):
        idx = len(self.data) - 1
        
        if not np.isnan(self.pivotHighValues[idx]):
            self.lastHigh = self.pivotHighValues[idx]
        
        if not np.isnan(self.pivotLowValues[idx]):
            self.lastLow = self.pivotLowValues[idx]
        
        upTrend = self.emaShort[-1] > self.emaLong[-1]
        downTrend = self.emaShort[-1] < self.emaLong[-1]
        
        strongBull = self.rsi[-1] > 55
        strongBear = self.rsi[-1] < 45
        
        bullishBreak = self.lastHigh is not None and self.data.Close[-1] > self.lastHigh
        bearishBreak = self.lastLow is not None and self.data.Close[-1] < self.lastLow
        
        bullSignal = upTrend and strongBull and bullishBreak
        bearSignal = downTrend and strongBear and bearishBreak
        
        if bullSignal and not self.position:
            self.buy()
        elif bearSignal and self.position:
            self.position.close()