"""
DS-TV Backtest Results: ben-bot-entry-alerts
============================================================

--- SPY ---
  Return                    12.04%
  Buy & Hold Return         38.66%
  Max Drawdown              -8.38%
  Sharpe Ratio              0.77
  Sortino Ratio             1.14
  Calmar Ratio              0.70
  Profit Factor             nan
  Expectancy                12.09%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                12.09%
  Worst Trade               12.09%
  Avg Trade                 12.09%
  Exposure Time             30.20%
  Equity Final              112044.31$
  Equity Peak               115267.45$
  Avg Drawdown              -1.38%
  Max Drawdown Duration     430 days 00:00:00
  Max Trade Duration        217 days 00:00:00
  Avg Trade Duration        217 days 00:00:00
  Ann. Return               5.90%
  Ann. Volatility           7.64%

--- BTC ---
  Return                    8.65%
  Buy & Hold Return         37.68%
  Max Drawdown              -21.06%
  Sharpe Ratio              0.12
  Sortino Ratio             0.19
  Calmar Ratio              0.20
  Profit Factor             1.59
  Expectancy                3.46%
  SQN                       0.28
  # Trades                  3
  Win Rate                  66.67%
  Best Trade                20.98%
  Worst Trade               -17.44%
  Avg Trade                 2.19%
  Exposure Time             81.12%
  Equity Final              108651.25$
  Equity Peak               136222.18$
  Avg Drawdown              -8.70%
  Max Drawdown Duration     238 days 00:00:00
  Max Trade Duration        389 days 00:00:00
  Avg Trade Duration        197 days 00:00:00
  Ann. Return               4.23%
  Ann. Volatility           34.49%

--- QQQ ---
  Return                    15.42%
  Buy & Hold Return         39.38%
  Max Drawdown              -13.51%
  Sharpe Ratio              0.57
  Sortino Ratio             0.85
  Calmar Ratio              0.55
  Profit Factor             nan
  Expectancy                16.93%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                16.93%
  Worst Trade               16.93%
  Avg Trade                 16.93%
  Exposure Time             38.60%
  Equity Final              115415.88$
  Equity Peak               119534.31$
  Avg Drawdown              -3.01%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        284 days 00:00:00
  Avg Trade Duration        284 days 00:00:00
  Ann. Return               7.49%
  Ann. Volatility           13.19%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ben-bot-entry-alerts
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    dmiLength = 14
    adxSmooth = 14

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate DMI and ADX
        adx_result = self.I(lambda: pta.adx(high, low, close, length=self.dmiLength))
        
        # Extract DI+ and DI- from ADX result
        self.di_plus = self.I(lambda: pta.adx(high, low, close, length=self.dmiLength)['DMP_14'] if pta.adx(high, low, close, length=self.dmiLength) is not None else pd.Series(0, index=close.index))
        self.di_minus = self.I(lambda: pta.adx(high, low, close, length=self.dmiLength)['DMN_14'] if pta.adx(high, low, close, length=self.dmiLength) is not None else pd.Series(0, index=close.index))
        self.adx = self.I(lambda: pta.adx(high, low, close, length=self.dmiLength)['ADX_14'] if pta.adx(high, low, close, length=self.dmiLength) is not None else pd.Series(20, index=close.index))
        
        # OR High/Low tracking
        self.or_high = None
        self.or_low = None
        self.or_complete = False
        self.last_session_state = False

    def next(self):
        # Update OR levels (simplified - assumes opening range 0930-1000)
        # For backtesting, we'll use a simplified approach based on bar count
        bar_index = len(self.data) - 1
        
        # Reset OR at start of each trading day (simplified)
        if bar_index > 0:
            # Check if we're in opening range window (first 30 bars approximately)
            if bar_index % 390 == 1:  # Reset per trading day (390 bars = 1 day on 1-min)
                self.or_high = self.data.High[-1]
                self.or_low = self.data.Low[-1]
                self.or_complete = False
            elif bar_index % 390 <= 30:  # Within opening range
                self.or_high = max(self.or_high if self.or_high else self.data.High[-1], self.data.High[-1])
                self.or_low = min(self.or_low if self.or_low else self.data.Low[-1], self.data.Low[-1])
            elif bar_index % 390 == 31 and not self.or_complete:  # OR just completed
                self.or_complete = True
        
        # Signal 1: DMI Crossover + ADX Rising
        if len(self.di_plus) > 1 and len(self.di_minus) > 1 and len(self.adx) > 1:
            bullish_cross = crossover(self.di_plus, self.di_minus)
            bearish_cross = crossover(self.di_minus, self.di_plus)
            adx_rising = self.adx[-1] > self.adx[-2]
            
            dmi_call = bullish_cross and adx_rising
            dmi_put = bearish_cross and adx_rising
            
            if dmi_call and not self.position:
                self.buy()
            elif dmi_put and self.position:
                self.position.close()
        
        # Signal 2: ORB Breakout + ADX Rising
        if self.or_complete and len(self.adx) > 1:
            adx_rising = self.adx[-1] > self.adx[-2]
            
            # ORB Call: Close breaks above OR High
            orb_call = (self.data.Close[-1] > self.or_high and 
                       self.data.Close[-2] <= self.or_high and 
                       adx_rising)
            
            # ORB Put: Close breaks below OR Low
            orb_put = (self.data.Close[-1] < self.or_low and 
                      self.data.Close[-2] >= self.or_low and 
                      adx_rising)
            
            if orb_call and not self.position:
                self.buy()
            elif orb_put and self.position:
                self.position.close()