"""
DS-TV Backtest Results: bk-ak-crosswind-falcon
============================================================

--- SPY ---
  Return                    -1.64%
  Buy & Hold Return         27.40%
  Max Drawdown              -18.71%
  Sharpe Ratio              -0.05
  Sortino Ratio             -0.08
  Calmar Ratio              -0.04
  Profit Factor             1.00
  Expectancy                -0.01%
  SQN                       -0.10
  # Trades                  12
  Win Rate                  66.67%
  Best Trade                6.11%
  Worst Trade               -16.11%
  Avg Trade                 -0.18%
  Exposure Time             75.60%
  Equity Final              98357.65$
  Equity Peak               111786.47$
  Avg Drawdown              -5.37%
  Max Drawdown Duration     266 days 00:00:00
  Max Trade Duration        152 days 00:00:00
  Avg Trade Duration        46 days 00:00:00
  Ann. Return               -0.83%
  Ann. Volatility           15.71%

--- BTC ---
  Return                    -18.82%
  Buy & Hold Return         5.39%
  Max Drawdown              -40.58%
  Sharpe Ratio              -0.53
  Sortino Ratio             -0.65
  Calmar Ratio              -0.24
  Profit Factor             0.42
  Expectancy                -6.14%
  SQN                       -0.50
  # Trades                  5
  Win Rate                  80.00%
  Best Trade                9.40%
  Worst Trade               -53.22%
  Avg Trade                 -10.27%
  Exposure Time             28.73%
  Equity Final              81180.44$
  Equity Peak               121202.92$
  Avg Drawdown              -7.95%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        94 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               -9.89%
  Ann. Volatility           18.56%

--- QQQ ---
  Return                    -24.82%
  Buy & Hold Return         24.82%
  Max Drawdown              -31.01%
  Sharpe Ratio              -0.76
  Sortino Ratio             -0.95
  Calmar Ratio              -0.43
  Profit Factor             0.28
  Expectancy                -2.04%
  SQN                       -1.18
  # Trades                  12
  Win Rate                  58.33%
  Best Trade                2.66%
  Worst Trade               -20.00%
  Avg Trade                 -2.24%
  Exposure Time             72.00%
  Equity Final              75177.70$
  Equity Peak               105907.89$
  Avg Drawdown              -8.54%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        130 days 00:00:00
  Avg Trade Duration        44 days 00:00:00
  Ann. Return               -13.39%
  Ann. Volatility           17.67%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — bk-ak-crosswind-falcon
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Core parameters
    lenDI = 14
    lenADX = 14
    sigLen = 5
    sigMAType = "EMA"
    zenMode = "DX Signed"
    
    # Regime
    trendThresh = 25.0
    
    # Bands
    bandMode = "Dynamic"
    dynLen = 100
    dynMult = 1.6
    staticBand = 40.0
    extremePct = 0.65
    extremeLookback = 3
    
    # Signal
    signalMode = "Instant Cross"
    cooldownBars = 6
    zenPivotLeft = 3
    zenPivotRight = 3
    
    # Session
    useSessionFilter = True
    sessStartHour = 6
    sessStartMin = 0
    sessEndHour = 18
    sessEndMin = 0
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate core indicators
        self.plus_di = self.I(self._calc_plus_di, high, low, close)
        self.minus_di = self.I(self._calc_minus_di, high, low, close)
        self.adx = self.I(self._calc_adx, high, low, close)
        self.diff = self.I(lambda: self.plus_di - self.minus_di)
        
        self.zenRaw = self.I(self._calc_zenRaw, high, low, close)
        self.zenSig = self.I(self._calc_zenSig, high, low, close)
        self.zenVel = self.I(lambda: np.gradient(self.zenRaw) if len(self.zenRaw) > 0 else 0)
        
        self.band = self.I(self._calc_band, high, low, close)
        self.upper = self.I(lambda: self.band)
        self.lower = self.I(lambda: -self.band)
        
        # Tracking
        self.bars_since_short = 0
        self.bars_since_long = 0
        self.in_long = False
        self.in_short = False
    
    def _calc_plus_di(self, high, low, close):
        h = high.values if isinstance(high, pd.Series) else high
        l = low.values if isinstance(low, pd.Series) else low
        
        up = np.diff(h, prepend=h[0])
        down = -np.diff(l, prepend=l[0])
        
        plusDM = np.where((up > down) & (up > 0), up, 0)
        tr = self._true_range(high, low, close)
        trur = pd.Series(tr).rolling(self.lenDI).mean().values
        trur = np.where(trur == 0, 1, trur)
        plus = 100 * pd.Series(plusDM).rolling(self.lenDI).mean().values / trur
        return pd.Series(np.nan_to_num(plus, nan=0))
    
    def _calc_minus_di(self, high, low, close):
        h = high.values if isinstance(high, pd.Series) else high
        l = low.values if isinstance(low, pd.Series) else low
        
        up = np.diff(h, prepend=h[0])
        down = -np.diff(l, prepend=l[0])
        
        minusDM = np.where((down > up) & (down > 0), down, 0)
        tr = self._true_range(high, low, close)
        trur = pd.Series(tr).rolling(self.lenDI).mean().values
        trur = np.where(trur == 0, 1, trur)
        minus = 100 * pd.Series(minusDM).rolling(self.lenDI).mean().values / trur
        return pd.Series(np.nan_to_num(minus, nan=0))
    
    def _true_range(self, high, low, close):
        h = high.values if isinstance(high, pd.Series) else high
        l = low.values if isinstance(low, pd.Series) else low
        c = close.values if isinstance(close, pd.Series) else close
        
        tr1 = h - l
        tr2 = np.abs(h - np.roll(c, 1))
        tr3 = np.abs(l - np.roll(c, 1))
        return np.maximum(tr1, np.maximum(tr2, tr3))
    
    def _calc_adx(self, high, low, close):
        plus = self._calc_plus_di(high, low, close).values
        minus = self._calc_minus_di(high, low, close).values
        
        sum_di = plus + minus
        diff = plus - minus
        dxFrac = np.divide(np.abs(diff), sum_di, where=sum_di!=0, out=np.zeros_like(diff))
        dx = 100 * dxFrac
        
        adx = pd.Series(dx).rolling(self.lenADX).mean().values
        return pd.Series(np.nan_to_num(adx, nan=0))
    
    def _calc_zenRaw(self, high, low, close):
        plus = self._calc_plus_di(high, low, close).values
        minus = self._calc_minus_di(high, low, close).values
        adx = self._calc_adx(high, low, close).values
        
        sum_di = plus + minus
        diff = plus - minus
        
        if self.zenMode == "DX Signed":
            dxSigned = np.divide(diff, sum_di, where=sum_di!=0, out=np.zeros_like(diff)) * 100
            return pd.Series(dxSigned)
        else:
            return pd.Series(diff)
    
    def _calc_zenSig(self, high, low, close):
        zenRaw = self._calc_zenRaw(high, low, close)
        if self.sigMAType == "EMA":
            sig = pta.ema(zenRaw, length=self.sigLen)
        else:
            sig = pta.sma(zenRaw, length=self.sigLen)
        return sig if sig is not None else pd.Series(0)
    
    def _calc_band(self, high, low, close):
        zenRaw = self._calc_zenRaw(high, low, close)
        if self.bandMode == "Dynamic":
            band = self.dynMult * pta.stdev(zenRaw, length=self.dynLen)
        else:
            band = pd.Series([self.staticBand] * len(zenRaw))
        return band if band is not None else pd.Series(self.staticBand)
    
    def _in_session(self):
        return True
    
    def next(self):
        self.bars_since_short += 1
        self.bars_since_long += 1
        
        if len(self.data) < max(self.lenDI, self.lenADX, self.sigLen, self.dynLen) + 10:
            return
        
        zenRaw = self.zenRaw[-1]
        zenSig = self.zenSig[-1]
        zenVel = self.zenVel[-1]
        band = self.band[-1]
        upper = self.upper[-1]
        lower = self.lower[-1]
        adx = self.adx[-1]
        
        if pd.isna(zenRaw) or pd.isna(zenSig) or pd.isna(band):
            return
        
        extremeUpper = upper * self.extremePct
        extremeLower = lower * self.extremePct
        
        inOB = zenRaw > upper
        inOS = zenRaw < lower
        nearOB = zenRaw >= extremeUpper
        nearOS = zenRaw <= extremeLower
        
        inTrend = adx >= self.trendThresh
        
        sessionOK = self._in_session()
        
        # Instant cross signals
        sig_cross_down = (len(self.zenRaw) > 1 and 
                         self.zenRaw[-2] > self.zenSig[-2] and 
                         zenRaw < zenSig)
        sig_cross_up = (len(self.zenRaw) > 1 and 
                       self.zenRaw[-2] < self.zenSig[-2] and 
                       zenRaw > zenSig)
        
        # Check if was in extreme recently
        wasInUpperExtreme = any(self.zenRaw[-min(self.extremeLookback, len(self.zenRaw)):] >= extremeUpper)
        wasInLowerExtreme = any(self.zenRaw[-min(self.extremeLookback, len(self.zenRaw)):] <= extremeLower)
        
        inOrNearUpperExtreme = nearOB or wasInUpperExtreme
        inOrNearLowerExtreme = nearOS or wasInLowerExtreme
        
        peak_signal = (sig_cross_down and inOrNearUpperExtreme and 
                      zenVel < 0 and self.bars_since_short >= self.cooldownBars and 
                      sessionOK)
        valley_signal = (sig_cross_up and inOrNearLowerExtreme and 
                        zenVel > 0 and self.bars_since_long >= self.cooldownBars and 
                        sessionOK)
        
        if peak_signal:
            self.bars_since_short = 0
            if self.in_long:
                self.position.close()
                self.in_long = False
            if not self.in_short:
                self.sell()
                self.in_short = True
        
        if valley_signal:
            self.bars_since_long = 0
            if self.in_short:
                self.position.close()
                self.in_short = False
            if not self.in_long:
                self.buy()
                self.in_long = True