"""
DS-TV Backtest Results: blackcat-l3-enhanced-kdj-indicator
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — blackcat-l3-enhanced-kdj-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    kdjPeriodN = 18
    kdjM1 = 4
    kdjM2 = 4

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate previous day's low
        prev_low = low.shift(1)
        
        # Calculate RSI volatility indicator
        rsi_vol = (np.abs(low - prev_low) / (np.maximum(low - prev_low, 0) + 1e-10)) * 100
        rsi_vol = rsi_vol.fillna(100)
        
        # Calculate adjusted volatility
        close_up = (close > close.shift(1)).astype(float)
        adj_vol_raw = close_up * rsi_vol * 10 + (1 - close_up) * rsi_vol / 10
        
        # Use rolling mean to simulate EMA approximation
        adj_vol = adj_vol_raw.rolling(window=3, min_periods=1).mean()
        
        # Calculate lowest price within 38 days
        lowest_38 = low.rolling(window=38, min_periods=1).min()
        
        # Calculate highest adjusted volatility within 38 days
        highest_adj_vol_38 = adj_vol.rolling(window=38, min_periods=1).max()
        
        # Determine if 90-day low
        is_90_day_low = (low.rolling(window=90, min_periods=1).min() > 0).astype(float)
        
        # Calculate main force accumulation
        main_force_cond = (low <= lowest_38).astype(float)
        main_force_raw = main_force_cond * (adj_vol + highest_adj_vol_38 * 2) / 2
        main_force_raw = main_force_raw.rolling(window=3, min_periods=1).mean()
        self.main_force_accumulation = (main_force_raw / 618) * is_90_day_low
        
        # Calculate RSV for 21 period
        rsv21_num = close - low.rolling(window=21, min_periods=1).min()
        rsv21_den = high.rolling(window=21, min_periods=1).max() - low.rolling(window=21, min_periods=1).min()
        rsv21 = (rsv21_num / (rsv21_den + 1e-10)) * 100
        rsv21 = rsv21.fillna(50)
        
        # Calculate smoothed RSV21
        smoothed_rsv21 = rsv21.rolling(window=13, min_periods=1).mean()
        
        # Calculate RSV for KDJ
        rsv_num = close - low.rolling(window=self.kdjPeriodN, min_periods=1).min()
        rsv_den = high.rolling(window=self.kdjPeriodN, min_periods=1).max() - low.rolling(window=self.kdjPeriodN, min_periods=1).min()
        rsv = (rsv_num / (rsv_den + 1e-10)) * 100
        rsv = rsv.fillna(50)
        
        # Calculate K line
        self.k_line = self.I(lambda: rsv.rolling(window=self.kdjM1, min_periods=1).mean())
        
        # Calculate D line
        self.d_line = self.I(lambda: self.k_line.rolling(window=self.kdjM2, min_periods=1).mean())
        
        # Calculate J line
        self.j_line = self.I(lambda: 3 * self.k_line - 2 * self.d_line)
        
        # Crossover/Crossunder signals
        self.j_above_k = self.I(lambda: (self.j_line > self.k_line).astype(float))

    def next(self):
        # Golden Cross: J crosses above K (buy signal)
        if len(self.data) > 1:
            if self.j_above_k[-1] > self.j_above_k[-2] and self.j_above_k[-2] <= 0:
                if not self.position:
                    self.buy()
            # Death Cross: J crosses below K (sell signal)
            elif self.j_above_k[-1] < self.j_above_k[-2] and self.j_above_k[-2] > 0:
                if self.position:
                    self.position.close()
            # Oversold condition: J < 10 and starts recovering
            elif self.j_line[-1] < 10 and len(self.data) > 1 and self.j_line[-1] > self.j_line[-2]:
                if not self.position:
                    self.buy()
            # Overbought condition: J > 90 and starts declining
            elif self.j_line[-1] > 90 and len(self.data) > 1 and self.j_line[-1] < self.j_line[-2]:
                if self.position:
                    self.position.close()
            # Main force entry: main force accumulation > 0
            elif self.main_force_accumulation.iloc[-1] > 0 and len(self.data) > 1:
                if self.main_force_accumulation.iloc[-2] <= 0:
                    if not self.position:
                        self.buy()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)