"""
DS-TV Backtest Results: chande-momentum-oscillator-cmo-tr
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — chande-momentum-oscillator-cmo-tr
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length_cmo = 14
    length_ma_cmo = 365
    source_ma_cmo = 'EMA'

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate CMO
        cmo = self.I(lambda: pta.cmo(close, length=self.length_cmo) or pd.Series(0, index=close.index))
        
        # Calculate MA of CMO based on source_ma_cmo
        if self.source_ma_cmo == 'EMA':
            cmo_ma = self.I(lambda: pta.ema(cmo, length=self.length_ma_cmo) or pd.Series(0, index=close.index))
        elif self.source_ma_cmo == 'SMA':
            cmo_ma = self.I(lambda: pta.sma(cmo, length=self.length_ma_cmo) or pd.Series(0, index=close.index))
        elif self.source_ma_cmo == 'RMA':
            cmo_ma = self.I(lambda: pta.rma(cmo, length=self.length_ma_cmo) or pd.Series(0, index=close.index))
        elif self.source_ma_cmo == 'WMA':
            cmo_ma = self.I(lambda: pta.wma(cmo, length=self.length_ma_cmo) or pd.Series(0, index=close.index))
        elif self.source_ma_cmo == 'VWMA':
            volume = pd.Series(self.data.Volume)
            cmo_ma = self.I(lambda: pta.vwma(cmo, volume, length=self.length_ma_cmo) or pd.Series(0, index=close.index))
        else:  # HMA
            cmo_ma = self.I(lambda: pta.hma(cmo, length=self.length_ma_cmo) or pd.Series(0, index=close.index))
        
        self.cmo = cmo
        self.cmo_ma = cmo_ma

    def next(self):
        # Buy signal: CMO crosses above CMO_MA
        if crossover(self.cmo, self.cmo_ma):
            self.buy()
        # Sell signal: CMO crosses below CMO_MA
        elif crossover(self.cmo_ma, self.cmo):
            self.sell()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()