"""
DS-TV Backtest Results: commodity-channel-index-cci-tr
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — commodity-channel-index-cci-tr
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Default parameters from the Pine Script
    length_cci = 55
    length_ma_cci = 365
    source_ma_cci = 'EMA'
    signal_cci = 'CCI MA'

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate CCI
        self.cci = self.I(lambda: pta.cci(high, low, close, length=self.length_cci) or pd.Series(0, index=close.index))
        
        # Calculate CCI MA based on source
        def calc_cci_ma():
            cci_vals = pta.cci(high, low, close, length=self.length_cci)
            if cci_vals is None:
                return pd.Series(0, index=close.index)
            
            if self.source_ma_cci == 'EMA':
                ma_vals = pta.ema(cci_vals, length=self.length_ma_cci)
            elif self.source_ma_cci == 'SMA':
                ma_vals = pta.sma(cci_vals, length=self.length_ma_cci)
            elif self.source_ma_cci == 'RMA':
                ma_vals = pta.rma(cci_vals, length=self.length_ma_cci)
            elif self.source_ma_cci == 'WMA':
                ma_vals = pta.wma(cci_vals, length=self.length_ma_cci)
            elif self.source_ma_cci == 'VWMA':
                ma_vals = pta.vwma(close, volume, length=self.length_ma_cci)
            else:
                ma_vals = pta.ema(cci_vals, length=self.length_ma_cci)
            
            return ma_vals if ma_vals is not None else pd.Series(0, index=close.index)
        
        self.cci_ma = self.I(calc_cci_ma)
        
        # Determine entry signal level
        if self.signal_cci == 'CCI MA':
            self.entry_level = self.cci_ma
        else:
            self.entry_level = self.I(lambda: pd.Series(0, index=close.index))

    def next(self):
        # Bull signal: CCI crosses above entry level
        if crossover(self.cci, self.entry_level):
            if not self.position:
                self.buy()
        
        # Bear signal: CCI crosses below entry level
        elif crossover(self.entry_level, self.cci):
            if self.position:
                self.position.close()