"""
DS-TV Backtest Results: fvg-pro-auto-adaptive-st
============================================================

--- SPY ---
  Return                    0.96%
  Buy & Hold Return         40.21%
  Max Drawdown              -13.68%
  Sharpe Ratio              0.04
  Sortino Ratio             0.06
  Calmar Ratio              0.04
  Profit Factor             1.26
  Expectancy                0.88%
  SQN                       0.09
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                12.71%
  Worst Trade               -6.04%
  Avg Trade                 0.54%
  Exposure Time             44.40%
  Equity Final              100961.30$
  Equity Peak               113713.73$
  Avg Drawdown              -2.86%
  Max Drawdown Duration     199 days 00:00:00
  Max Trade Duration        139 days 00:00:00
  Avg Trade Duration        108 days 00:00:00
  Ann. Return               0.48%
  Ann. Volatility           13.27%

--- BTC ---
  Return                    9.93%
  Buy & Hold Return         35.02%
  Max Drawdown              -32.98%
  Sharpe Ratio              0.18
  Sortino Ratio             0.30
  Calmar Ratio              0.15
  Profit Factor             2.27
  Expectancy                7.57%
  SQN                       0.27
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                40.53%
  Worst Trade               -12.88%
  Avg Trade                 5.18%
  Exposure Time             48.15%
  Equity Final              109933.84$
  Equity Peak               147011.55$
  Avg Drawdown              -7.14%
  Max Drawdown Duration     308 days 00:00:00
  Max Trade Duration        268 days 00:00:00
  Avg Trade Duration        117 days 00:00:00
  Ann. Return               4.84%
  Ann. Volatility           26.19%

--- QQQ ---
  Return                    -18.13%
  Buy & Hold Return         42.44%
  Max Drawdown              -35.27%
  Sharpe Ratio              -0.53
  Sortino Ratio             -0.70
  Calmar Ratio              -0.27
  Profit Factor             0.33
  Expectancy                -3.63%
  SQN                       -0.90
  # Trades                  5
  Win Rate                  20.00%
  Best Trade                9.09%
  Worst Trade               -15.14%
  Avg Trade                 -3.95%
  Exposure Time             95.20%
  Equity Final              81873.61$
  Equity Peak               122351.65$
  Avg Drawdown              -5.35%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        291 days 00:00:00
  Avg Trade Duration        139 days 00:00:00
  Ann. Return               -9.59%
  Ann. Volatility           18.14%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fvg-pro-auto-adaptive-st
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        # Pre-calculate all data we need
        self.close = pd.Series(self.data.Close)
        self.open = pd.Series(self.data.Open)
        self.high = pd.Series(self.data.High)
        self.low = pd.Series(self.data.Low)
        self.volume = pd.Series(self.data.Volume) if len(self.data.Volume) > 0 else pd.Series(0, index=self.close.index)
        
        # ATR calculation
        self.atr = self.I(pta.atr, self.high, self.low, self.close, length=14)
        
        # Parameters (auto-adaptive based on timeframe - using default 15min parameters)
        self.lookback = 15
        self.memory = 12
        self.buffer = 0.25
        self.atr_multiplier = 1.2
        self.min_gap_perc = 0.015
        
        # Highest/Lowest for liquidity
        self.range_high = self.I(lambda: self.high.shift(1).rolling(self.lookback).max())
        self.range_low = self.I(lambda: self.low.shift(1).rolling(self.lookback).min())
        
        # Track FVG boxes: (bar_index_start, top, bottom, is_bullish, mid_price, touched_mid, fully_closed)
        self.fvgs = []
        self.last_fvg_check = -10
        self.bar_count = 0

    def next(self):
        self.bar_count = len(self.data)
        idx = len(self.data) - 1
        
        # Need at least 3 bars of history
        if idx < 2:
            return
        
        # Get current and previous candles
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_close = self.data.Close[-1]
        
        prev_high = self.data.High[-2]
        prev_low = self.data.Low[-2]
        prev_open = self.data.Open[-2]
        prev_close = self.data.Close[-2]
        
        prev_prev_high = self.data.High[-3]
        prev_prev_low = self.data.Low[-3]
        
        if self.atr[-1] is None or self.range_high[-1] is None or self.range_low[-1] is None:
            return
        
        atr_val = self.atr[-1]
        range_high_val = self.range_high[-1]
        range_low_val = self.range_low[-1]
        
        # ===== IMPULSE CHECK =====
        candle_range = prev_high - prev_low
        candle_body = abs(prev_close - prev_open)
        body_ratio = candle_body / candle_range if candle_range > 0 else 0
        impulse_valid = candle_range > atr_val * self.atr_multiplier and body_ratio >= 0.5
        
        # ===== SWEEP CHECK =====
        bull_sweep_now = prev_low <= (range_low_val + atr_val * self.buffer)
        bear_sweep_now = prev_high >= (range_high_val - atr_val * self.buffer)
        
        # Track bars since sweep (simplified)
        bull_sweep_recent = bull_sweep_now
        bear_sweep_recent = bear_sweep_now
        
        # ===== GAP CHECK =====
        bull_gap = current_low > prev_prev_high
        bear_gap = current_high < prev_prev_low
        
        bull_size = ((current_low - prev_prev_high) / prev_prev_high * 100.0) if prev_prev_high > 0 else 0
        bear_size = ((prev_prev_low - current_high) / prev_prev_low * 100.0) if prev_prev_low > 0 else 0
        
        valid_bull = bull_gap and bull_size >= self.min_gap_perc and impulse_valid and bull_sweep_recent
        valid_bear = bear_gap and bear_size >= self.min_gap_perc and impulse_valid and bear_sweep_recent
        
        # ===== CREATE FVG =====
        if valid_bull:
            top = current_low
            bottom = prev_prev_high
            mid = (top + bottom) / 2.0
            self.fvgs.append({
                'start_idx': idx - 2,
                'top': top,
                'bottom': bottom,
                'is_bull': True,
                'mid': mid,
                'touched_mid': False,
                'fully_closed': False
            })
        elif valid_bear:
            top = prev_prev_low
            bottom = current_high
            mid = (top + bottom) / 2.0
            self.fvgs.append({
                'start_idx': idx - 2,
                'top': top,
                'bottom': bottom,
                'is_bull': False,
                'mid': mid,
                'touched_mid': False,
                'fully_closed': False
            })
        
        # ===== UPDATE AND PROCESS FVGs =====
        for fvg in self.fvgs:
            if fvg['fully_closed']:
                continue
            
            is_bull = fvg['is_bull']
            mid = fvg['mid']
            top = fvg['top']
            bottom = fvg['bottom']
            
            # Check if mid-level touched
            if not fvg['touched_mid']:
                if (is_bull and current_low <= mid) or (not is_bull and current_high >= mid):
                    fvg['touched_mid'] = True
                    # Generate trading signal at mid-level touch
                    if is_bull:
                        if not self.position:
                            self.buy()
                    else:
                        if self.position:
                            self.sell()
            
            # Check if fully filled
            fully_filled = (is_bull and current_low <= bottom) or (not is_bull and current_high >= top)
            
            if fully_filled:
                fvg['fully_closed'] = True
                # Close position if filled
                if is_bull and self.position:
                    self.sell()
                elif not is_bull and not self.position:
                    self.buy()