"""
DS-TV Backtest Results: gcm-rsi-ultra-scalper
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gcm-rsi-ultra-scalper
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 5
    rsiSmoothLen = 7
    shortMaLen = 5
    bbLength = 20
    bbMult1 = 2.0
    bbMult2 = 1.5
    lbR = 1
    lbL = 1
    maxDivBars = 5

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Raw RSI
        raw_rsi = self.I(pta.rsi, close, length=self.length)
        
        # Smooth RSI using LSMA (linear regression)
        def get_lsma(src, length):
            result = pta.linreg(src, length=length)
            if result is not None:
                return result
            return pd.Series(0, index=src.index)
        
        smooth_rsi = self.I(lambda: get_lsma(raw_rsi, self.rsiSmoothLen))
        
        # Short MA (EMA by default on smoothed RSI)
        def get_short_ma(src, length):
            result = pta.ema(src, length=length)
            if result is not None:
                return result
            return pd.Series(50, index=src.index)
        
        self.smooth_rsi = smooth_rsi
        self.short_ma = self.I(lambda: get_short_ma(smooth_rsi, self.shortMaLen))
        
        # Bollinger Bands on smoothed RSI
        bb_basis = self.I(pta.sma, smooth_rsi, length=self.bbLength)
        
        def get_bb_stdev(src, length):
            return src.rolling(length).std()
        
        bb_stdev = self.I(lambda: get_bb_stdev(smooth_rsi, self.bbLength))
        
        self.bb_upper1 = self.I(lambda: bb_basis + (self.bbMult1 * bb_stdev))
        self.bb_lower1 = self.I(lambda: bb_basis - (self.bbMult1 * bb_stdev))
        self.bb_upper2 = self.I(lambda: bb_basis + (self.bbMult2 * bb_stdev))
        self.bb_lower2 = self.I(lambda: bb_basis - (self.bbMult2 * bb_stdev))

    def next(self):
        # Simple trading logic based on RSI crossing Short MA
        if len(self.data) < 2:
            return
        
        smooth_rsi_curr = self.smooth_rsi[-1]
        smooth_rsi_prev = self.smooth_rsi[-2]
        short_ma_curr = self.short_ma[-1]
        short_ma_prev = self.short_ma[-2]
        
        # Avoid NaN values
        if pd.isna(smooth_rsi_curr) or pd.isna(short_ma_curr):
            return
        
        # Buy signal: RSI crosses above Short MA (bullish)
        if smooth_rsi_prev <= short_ma_prev and smooth_rsi_curr > short_ma_curr:
            if not self.position:
                self.buy()
        
        # Sell signal: RSI crosses below Short MA (bearish)
        elif smooth_rsi_prev >= short_ma_prev and smooth_rsi_curr < short_ma_curr:
            if self.position:
                self.position.close()
        
        # Additional exit: RSI hits overbought (80)
        if self.position and smooth_rsi_curr >= 80:
            self.position.close()
        
        # Additional exit: RSI hits oversold (20)
        if self.position and smooth_rsi_curr <= 20:
            self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()