"""
DS-TV Backtest Results: golden-ratio-levels-static-range-anchor
============================================================

--- SPY ---
  Return                    -37.87%
  Buy & Hold Return         23.76%
  Max Drawdown              -39.95%
  Sharpe Ratio              -1.67
  Sortino Ratio             -1.66
  Calmar Ratio              -0.53
  Profit Factor             0.12
  Expectancy                -2.47%
  SQN                       -0.79
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                0.67%
  Worst Trade               -5.62%
  Avg Trade                 -2.52%
  Exposure Time             2.20%
  Equity Final              62129.61$
  Equity Peak               102987.65$
  Avg Drawdown              -39.95%
  Max Drawdown Duration     308 days 00:00:00
  Max Trade Duration        13 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               -21.33%
  Ann. Volatility           12.78%

--- BTC ---
  Return                    -8.81%
  Buy & Hold Return         21.81%
  Max Drawdown              -66.30%
  Sharpe Ratio              -0.07
  Sortino Ratio             -0.12
  Calmar Ratio              -0.07
  Profit Factor             1.47
  Expectancy                0.27%
  SQN                       0.50
  # Trades                  20
  Win Rate                  55.00%
  Best Trade                8.55%
  Worst Trade               -3.42%
  Avg Trade                 0.25%
  Exposure Time             5.88%
  Equity Final              91186.58$
  Equity Peak               107674.20$
  Avg Drawdown              -25.39%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -4.50%
  Ann. Volatility           60.35%

--- QQQ ---
  Return                    37.70%
  Buy & Hold Return         28.12%
  Max Drawdown              -7.88%
  Sharpe Ratio              1.44
  Sortino Ratio             2.65
  Calmar Ratio              2.22
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              137698.61$
  Equity Peak               142320.17$
  Avg Drawdown              -1.49%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               17.50%
  Ann. Volatility           12.18%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — golden-ratio-levels-static-range-anchor
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    n1 = 150  # Lookback Period
    m1 = 3    # Offset Bars

    def init(self):
        # Calculate highest high and lowest low over the lookback period with offset
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Create offset series (shift by m1 bars)
        high_offset = high.shift(self.m1)
        low_offset = low.shift(self.m1)
        
        # Calculate rolling highest and lowest
        self.src_hh = self.I(lambda: high_offset.rolling(window=self.n1).max())
        self.src_ll = self.I(lambda: low_offset.rolling(window=self.n1).min())
        
        # Initialize anchor values (will be set on first calculation)
        self.anchor_hh = None
        self.anchor_ll = None
        self.fib_levels = {}
        self.anchor_set = False

    def next(self):
        # Set anchor values only once (simulating barstate.islast behavior)
        if not self.anchor_set and len(self.data) > self.n1 + self.m1:
            self.anchor_hh = self.src_hh[-1]
            self.anchor_ll = self.src_ll[-1]
            
            if self.anchor_hh is not None and self.anchor_ll is not None and not np.isnan(self.anchor_hh) and not np.isnan(self.anchor_ll):
                diff = self.anchor_hh - self.anchor_ll
                
                # Calculate Fibonacci retracement levels
                self.fib_levels['p191'] = self.anchor_hh - diff * 0.191
                self.fib_levels['p382'] = self.anchor_hh - diff * 0.382
                self.fib_levels['pmid'] = (self.anchor_hh + self.anchor_ll) / 2
                self.fib_levels['p618'] = self.anchor_hh - diff * 0.618
                self.fib_levels['p809'] = self.anchor_hh - diff * 0.809
                
                self.anchor_set = True
        
        # Trading logic based on Fibonacci levels
        if self.anchor_set:
            current_price = self.data.Close[-1]
            
            # Buy signal: Price touches or bounces from lower Fibonacci levels (oversold)
            if current_price <= self.fib_levels['p618'] and current_price >= self.fib_levels['p809']:
                if not self.position:
                    self.buy()
            
            # Sell signal: Price touches or pulls back from upper Fibonacci levels (overbought)
            elif current_price >= self.fib_levels['p191'] and current_price <= self.fib_levels['p382']:
                if self.position:
                    self.sell()
            
            # Exit on midpoint reversal
            elif current_price <= self.fib_levels['pmid'] * 0.99:
                if self.position:
                    self.sell()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()