"""
DS-TV Backtest Results: ibs-internal-bar-strength-intraday
============================================================

--- SPY ---
  ERROR: Indicator "calc_ibs(calc_raw_…)" error. See traceback above.

--- BTC ---
  ERROR: Indicator "calc_ibs(calc_raw_…)" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "calc_ibs(calc_raw_…)" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ibs-internal-bar-strength-intraday
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ibsLen = 1
    smoothLen = 3
    obLevel = 0.7
    osLevel = 0.3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate raw IBS: (close - low) / (high - low)
        def calc_raw_ibs():
            raw = (close - low) / (high - low)
            return raw.fillna(0.5)
        
        raw_ibs = self.I(calc_raw_ibs)
        
        # Smooth IBS with EMA
        def calc_ibs(raw):
            ema_result = pta.ema(raw, length=self.smoothLen)
            if ema_result is None:
                return pd.Series(0.5, index=raw.index)
            return ema_result.fillna(0.5)
        
        self.ibs = self.I(calc_ibs, raw_ibs)
        
        # Bounce signal: IBS crosses above oversold level
        self.bounce_signal = self.I(lambda: crossover(self.ibs, self.osLevel * np.ones(len(self.ibs))))
        
        # Fade signal: IBS crosses below overbought level
        self.fade_signal = self.I(lambda: crossover(self.obLevel * np.ones(len(self.ibs)), self.ibs))

    def next(self):
        # Bounce setup: IBS crosses above oversold level (potential long)
        if len(self.data) > self.smoothLen and not self.position:
            if self.ibs[-1] > self.osLevel and self.ibs[-2] <= self.osLevel:
                self.buy()
        
        # Fade setup: IBS crosses below overbought level (potential short)
        if len(self.data) > self.smoothLen and self.position:
            if self.ibs[-1] < self.obLevel and self.ibs[-2] >= self.obLevel:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()