"""
DS-TV Backtest Results: info-panel
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — info-panel
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # ADR% - Average Daily Range % over 20 trading days
        daily_range = ((high - low) / close * 100)
        self.adr20 = self.I(lambda: daily_range.rolling(20).mean())
        
        # ATR% - Average True Range % over 20 trading days
        atr20 = self.I(pta.atr, high, low, close, length=20)
        self.atr_pct = self.I(lambda: (atr20 / close) * 100 if atr20 is not None else pd.Series(0, index=close.index))
        
        # % Off 52-Week High (252 trading days)
        high52 = self.I(lambda: high.rolling(252).max())
        self.off_high = self.I(lambda: (close - high52) / high52 * 100)
        
        # Average Dollar Volume (20-day)
        dol_vol = close * volume
        self.avg_dol_vol = self.I(lambda: dol_vol.rolling(20).mean())
        
        # RS Rating calculation
        self.perf_3m = self.I(lambda: ((close - close.shift(63)) / close.shift(63) * 100) if len(close) > 63 else pd.Series(0, index=close.index))
        self.perf_6m = self.I(lambda: ((close - close.shift(126)) / close.shift(126) * 100) if len(close) > 126 else pd.Series(0, index=close.index))
        self.perf_9m = self.I(lambda: ((close - close.shift(189)) / close.shift(189) * 100) if len(close) > 189 else pd.Series(0, index=close.index))
        self.perf_12m = self.I(lambda: ((close - close.shift(252)) / close.shift(252) * 100) if len(close) > 252 else pd.Series(0, index=close.index))

    def next(self):
        # Simple trading logic based on RS Rating concept
        # Buy when off 52-week high is improving (getting closer to 0) and ATR is reasonable
        # Sell when off 52-week high is worsening
        
        if len(self) < 252:
            return
        
        current_off_high = self.off_high[-1]
        prev_off_high = self.off_high[-2] if len(self) > 1 else current_off_high
        
        current_atr_pct = self.atr_pct[-1]
        
        # Buy signal: price recovering toward 52-week high with reasonable volatility
        if current_off_high > prev_off_high and current_off_high < -5 and current_atr_pct > 0.5:
            if not self.position:
                self.buy()
        
        # Sell signal: price moving away from 52-week high or hitting it
        elif current_off_high < prev_off_high or current_off_high > -2:
            if self.position:
                self.sell()


if __name__ == "__main__":
    import yfinance as yf
    
    # Download sample data
    data = yf.download("SPY", start="2020-01-01", end="2024-01-01", progress=False)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()