"""
DS-TV Backtest Results: lucky-mtf-trend-breakout-dashboard
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — lucky-mtf-trend-breakout-dashboard
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Moving Average parameters
    ma_short_len = 10
    ma_med_len = 20
    ma_long_len = 200
    ma_fast_type = "EMA"
    ma_med_type = "EMA"
    ma_long_type = "SMA"

    # MACD parameters
    macd_fast = 12
    macd_slow = 26
    macd_sig = 9
    atr_len = 14
    macd_sep_factor = 0.1

    # UT Bot parameters
    ut_key = 1.2
    ut_atr_period = 7
    ut_use_swing_filter = True
    swing_len = 8

    # Supertrend parameters
    st_atr_period = 10
    st_mult = 2.0
    st_use_atr = True
    st_neutral_bars = 0

    # ADX/RSI filters
    use_adx_filter = False
    adx_len = 14
    adx_min = 20.0
    use_rsi_pullback = False
    rsi_len = 14
    rsi_buy_min = 40.0
    rsi_buy_max = 55.0

    # Volume filter
    use_vol_filter = False
    vol_lookback = 20
    vol_min_factor = 1.2

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        # Moving Averages
        self.ma_short = self.I(lambda: self._calc_ma(close, self.ma_short_len, self.ma_fast_type))
        self.ma_med = self.I(lambda: self._calc_ma(close, self.ma_med_len, self.ma_med_type))
        self.ma_long = self.I(lambda: self._calc_ma(close, self.ma_long_len, self.ma_long_type))

        # MACD
        macd_result = self.I(lambda: pta.macd(close, fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_sig))
        self.macd_line = self.I(lambda: macd_result.iloc[:, 0] if macd_result is not None else pd.Series(0, index=close.index))
        self.macd_signal = self.I(lambda: macd_result.iloc[:, 1] if macd_result is not None else pd.Series(0, index=close.index))

        # ATR
        self.atr = self.I(lambda: pta.atr(high, low, close, length=self.atr_len))

        # RSI (optional)
        if self.use_rsi_pullback:
            self.rsi = self.I(lambda: pta.rsi(close, length=self.rsi_len))

        # ADX (optional)
        if self.use_adx_filter:
            adx_result = self.I(lambda: pta.adx(high, low, close, length=self.adx_len))
            self.adx = self.I(lambda: adx_result.iloc[:, 0] if adx_result is not None else pd.Series(20, index=close.index))

        # Volume SMA
        if self.use_vol_filter:
            self.vol_sma = self.I(lambda: pta.sma(volume, length=self.vol_lookback))

        # UT Bot trailing stop
        self.xatr = self.I(lambda: self._calc_ut_trailing_stop(close, high, low, volume))

        # Supertrend
        st_result = self.I(lambda: pta.supertrend(high, low, close, length=self.st_atr_period, multiplier=self.st_mult) if hasattr(pta, 'supertrend') else pd.DataFrame())
        if not st_result.empty:
            self.st_direction = self.I(lambda: self._get_st_direction(st_result))
        else:
            self.st_direction = self.I(lambda: pd.Series(0, index=close.index))

        self.close_series = close
        self.high_series = high
        self.low_series = low
        self.volume_series = volume

    def _calc_ma(self, series, length, ma_type):
        if ma_type == "EMA":
            return pta.ema(series, length=length)
        elif ma_type == "SMA":
            return pta.sma(series, length=length)
        elif ma_type == "WMA":
            return pta.wma(series, length=length)
        else:
            return pta.sma(series, length=length)

    def _calc_ut_trailing_stop(self, close, high, low, volume):
        xatr = pta.atr(high, low, close, length=self.ut_atr_period)
        vol_sma = pta.sma(volume, length=20)
        momentum = close.pct_change(5)
        vol_ratio = volume / vol_sma
        adaptive_key = self.ut_key * (1 + np.abs(momentum) * 2) * np.clip(vol_ratio, 0.8, 1.2)
        trail_dist = xatr * adaptive_key

        trailing_stop = close.copy()
        for i in range(1, len(close)):
            if close.iloc[i] > trailing_stop.iloc[i - 1]:
                trailing_stop.iloc[i] = max(trailing_stop.iloc[i - 1], close.iloc[i] - trail_dist.iloc[i])
            elif close.iloc[i] < trailing_stop.iloc[i - 1]:
                trailing_stop.iloc[i] = min(trailing_stop.iloc[i - 1], close.iloc[i] + trail_dist.iloc[i])
            else:
                trailing_stop.iloc[i] = trailing_stop.iloc[i - 1]

        return trailing_stop

    def _get_st_direction(self, st_result):
        return st_result.iloc[:, 0]

    def next(self):
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]

        # Check basic conditions
        ma_short_val = self.ma_short[-1]
        ma_med_val = self.ma_med[-1]
        ma_long_val = self.ma_long[-1]
        macd_line_val = self.macd_line[-1]
        macd_signal_val = self.macd_signal[-1]
        atr_val = self.atr[-1] if not np.isnan(self.atr[-1]) else 0.01
        xatr_val = self.xatr[-1]

        # Validate MA ordering
        if np.isnan(ma_short_val) or np.isnan(ma_med_val) or np.isnan(ma_long_val):
            return

        ma_distance_ok = (ma_short_val != ma_med_val and abs(ma_short_val - ma_med_val) / ma_med_val * 100 > 0.2)
        macd_sep_ok = abs(macd_line_val - macd_signal_val) > atr_val * self.macd_sep_factor

        # Volume filter
        vol_ok = True
        if self.use_vol_filter:
            vol_sma_val = self.vol_sma[-1]
            vol_ok = volume >= vol_sma_val * self.vol_min_factor

        # RSI filter
        rsi_ok_long = True
        if self.use_rsi_pullback:
            rsi_val = self.rsi[-1]
            rsi_ok_long = self.rsi_buy_min <= rsi_val <= self.rsi_buy_max

        # ADX filter
        adx_ok = True
        if self.use_adx_filter:
            adx_val = self.adx[-1]
            adx_ok = adx_val >= self.adx_min

        # UT Bot signals
        ut_buy = crossover(self.close_series[-2:], self.xatr[-2:])
        ut_sell = crossover(self.xatr[-2:], self.close_series[-2:])

        # Long conditions
        long_cond = (
            crossover(self.ma_short[-2:], self.ma_med[-2:]) and
            ma_distance_ok and
            macd_sep_ok and
            close > ma_long_val and
            macd_line_val > macd_signal_val and
            vol_ok and
            rsi_ok_long and
            adx_ok
        )

        # Short conditions
        short_cond = (
            crossover(self.ma_med[-2:], self.ma_short[-2:]) and
            ma_distance_ok and
            macd_sep_ok and
            close < ma_long_val and
            macd_line_val < macd_signal_val and
            vol_ok and
            adx_ok
        )

        # Entry logic
        if long_cond or ut_buy:
            if not self.position:
                self.buy()
        elif short_cond or ut_sell:
            if self.position:
                self.position.close()