"""
DS-TV Backtest Results: macd-dmiadx-context-mtf
============================================================

--- SPY ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- BTC ---
  ERROR: '_Indicator' object has no attribute 'iloc'

--- QQQ ---
  ERROR: '_Indicator' object has no attribute 'iloc'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — macd-dmiadx-context-mtf
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # MACD parameters
    fast_length = 12
    slow_length = 26
    signal_length = 9
    
    # DMI/ADX parameters
    dmi_length = 7
    dmi_smoothing = 7
    adx_threshold = 25
    
    # Mode selection
    mode = "MACD"  # "MACD" or "DMI/ADX"
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # MACD calculation
        macd_result = self.I(lambda: pta.macd(close, fast=self.fast_length, slow=self.slow_length, signal=self.signal_length))
        self.macd_line = macd_result.iloc[:, 0] if macd_result is not None else pd.Series(0, index=close.index)
        self.signal_line = macd_result.iloc[:, 1] if macd_result is not None else pd.Series(0, index=close.index)
        self.histogram = macd_result.iloc[:, 2] if macd_result is not None else pd.Series(0, index=close.index)
        
        # DMI/ADX calculation
        adx_result = self.I(lambda: pta.adx(high, low, close, length=self.dmi_length, scalar=100, drift=0))
        self.adx = adx_result.iloc[:, 2] if adx_result is not None else pd.Series(25, index=close.index)
        self.di_plus = adx_result.iloc[:, 0] if adx_result is not None else pd.Series(20, index=close.index)
        self.di_minus = adx_result.iloc[:, 1] if adx_result is not None else pd.Series(20, index=close.index)
        
        self.in_position = False
    
    def next(self):
        if self.mode == "MACD":
            self._macd_logic()
        elif self.mode == "DMI/ADX":
            self._dmi_logic()
    
    def _macd_logic(self):
        """MACD-based trading logic"""
        # MACD histogram zero-cross signals
        if len(self.histogram) < 2:
            return
        
        hist_now = self.histogram[-1]
        hist_prev = self.histogram[-2]
        
        # Histogram crosses above zero (bullish)
        if hist_prev <= 0 and hist_now > 0:
            if not self.position:
                self.buy()
        
        # Histogram crosses below zero (bearish)
        elif hist_prev >= 0 and hist_now < 0:
            if self.position:
                self.position.close()
    
    def _dmi_logic(self):
        """DMI/ADX-based trading logic"""
        if len(self.di_plus) < 2 or len(self.di_minus) < 2 or len(self.adx) < 2:
            return
        
        di_plus_now = self.di_plus[-1]
        di_minus_now = self.di_minus[-1]
        di_plus_prev = self.di_plus[-2]
        di_minus_prev = self.di_minus[-2]
        adx_now = self.adx[-1]
        
        # +DI crosses above -DI with strong ADX (bullish)
        if di_plus_prev <= di_minus_prev and di_plus_now > di_minus_now and adx_now >= self.adx_threshold:
            if not self.position:
                self.buy()
        
        # -DI crosses above +DI with strong ADX (bearish)
        elif di_minus_prev <= di_plus_prev and di_minus_now > di_plus_now and adx_now >= self.adx_threshold:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    # Load sample data (OHLCV format)
    # Example: using Yahoo Finance data
    import yfinance as yf
    
    data = yf.download("AAPL", start="2020-01-01", end="2023-12-31", interval="1d")
    
    # Run backtest with MACD mode
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.001)
    stats = bt.run()
    print(stats)
    bt.plot()