"""
DS-TV Backtest Results: merged-rsi-dual-macd-oscillator-with-macd-signal
============================================================

--- SPY ---
  Return                    20.20%
  Buy & Hold Return         40.20%
  Max Drawdown              -11.07%
  Sharpe Ratio              0.83
  Sortino Ratio             1.26
  Calmar Ratio              0.88
  Profit Factor             1.11
  Expectancy                0.20%
  SQN                       0.03
  # Trades                  3
  Win Rate                  66.67%
  Best Trade                5.41%
  Worst Trade               -5.20%
  Avg Trade                 0.10%
  Exposure Time             38.20%
  Equity Final              120201.84$
  Equity Peak               120468.26$
  Avg Drawdown              -1.82%
  Max Drawdown Duration     229 days 00:00:00
  Max Trade Duration        146 days 00:00:00
  Avg Trade Duration        92 days 00:00:00
  Ann. Return               9.72%
  Ann. Volatility           11.65%

--- BTC ---
  Return                    2.43%
  Buy & Hold Return         0.29%
  Max Drawdown              -29.36%
  Sharpe Ratio              0.05
  Sortino Ratio             0.08
  Calmar Ratio              0.04
  Profit Factor             1.31
  Expectancy                2.32%
  SQN                       0.05
  # Trades                  7
  Win Rate                  28.57%
  Best Trade                50.19%
  Worst Trade               -16.71%
  Avg Trade                 0.27%
  Exposure Time             49.25%
  Equity Final              102433.86$
  Equity Peak               142755.52$
  Avg Drawdown              -6.46%
  Max Drawdown Duration     181 days 00:00:00
  Max Trade Duration        142 days 00:00:00
  Avg Trade Duration        51 days 00:00:00
  Ann. Return               1.21%
  Ann. Volatility           24.00%

--- QQQ ---
  Return                    13.04%
  Buy & Hold Return         45.93%
  Max Drawdown              -20.55%
  Sharpe Ratio              0.41
  Sortino Ratio             0.57
  Calmar Ratio              0.31
  Profit Factor             0.30
  Expectancy                -2.31%
  SQN                       -0.89
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                2.95%
  Worst Trade               -6.23%
  Avg Trade                 -2.38%
  Exposure Time             35.60%
  Equity Final              113039.61$
  Equity Peak               116835.89$
  Avg Drawdown              -3.54%
  Max Drawdown Duration     449 days 00:00:00
  Max Trade Duration        166 days 00:00:00
  Avg Trade Duration        87 days 00:00:00
  Ann. Return               6.37%
  Ann. Volatility           15.69%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — merged-rsi-dual-macd-oscillator-with-macd-signal
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    smoothLen = 5
    macdNormLen = 50
    histScale = 1.8

    def init(self):
        close = pd.Series(self.data.Close)
        
        # RSI MERGE (14-21-28)
        rsi1 = self.I(pta.rsi, close, length=14)
        rsi2 = self.I(pta.rsi, close, length=21)
        rsi3 = self.I(pta.rsi, close, length=28)
        
        def calc_rsi_norm():
            r1 = pta.rsi(close, length=14)
            r2 = pta.rsi(close, length=21)
            r3 = pta.rsi(close, length=28)
            if r1 is None or r2 is None or r3 is None:
                return pd.Series(0, index=close.index)
            rsi_avg = (r1 + r2 + r3) / 3
            rsi_norm = (rsi_avg - 50) / 50
            return rsi_norm
        
        self.rsiNorm = self.I(calc_rsi_norm)
        
        # MACD MERGE (8-17-9 & 19-39-9)
        def calc_macd_norm():
            macd1_result = pta.macd(close, fast=8, slow=17, signal=9)
            macd2_result = pta.macd(close, fast=19, slow=39, signal=9)
            
            if macd1_result is None or macd2_result is None:
                return pd.Series(0, index=close.index), pd.Series(0, index=close.index), pd.Series(0, index=close.index)
            
            macd1_line = macd1_result.iloc[:, 0]
            sig1 = macd1_result.iloc[:, 1]
            hist1 = macd1_result.iloc[:, 2]
            
            macd2_line = macd2_result.iloc[:, 0]
            sig2 = macd2_result.iloc[:, 1]
            hist2 = macd2_result.iloc[:, 2]
            
            macd_line_avg = (macd1_line + macd2_line) / 2
            signal_line_avg = (sig1 + sig2) / 2
            macd_hist_avg = (hist1 + hist2) / 2
            
            norm_base = pta.ema(np.abs(macd_hist_avg), length=self.macdNormLen)
            if norm_base is None:
                norm_base = pd.Series(1, index=close.index)
            norm_base = norm_base.replace(0, 1)
            
            macd_norm = macd_line_avg / norm_base
            signal_norm = signal_line_avg / norm_base
            hist_norm = macd_hist_avg / norm_base
            
            return macd_norm, signal_norm, hist_norm
        
        def get_macd_norm():
            result = calc_macd_norm()
            return result[0] if isinstance(result, tuple) else result
        
        def get_signal_norm():
            result = calc_macd_norm()
            return result[1] if isinstance(result, tuple) else pd.Series(0, index=close.index)
        
        def get_hist_norm():
            result = calc_macd_norm()
            return result[2] if isinstance(result, tuple) else pd.Series(0, index=close.index)
        
        self.macdNorm = self.I(get_macd_norm)
        self.signalNorm = self.I(get_signal_norm)
        self.histNorm = self.I(get_hist_norm)
        
        # FINAL OSCILLATOR
        def calc_merged_osc():
            merged = (self.rsiNorm[-1] + self.histNorm[-1]) / 2
            return merged
        
        def calc_merged_smooth():
            rsi_norm_series = pd.Series([self.rsiNorm[i] if i < len(self.rsiNorm) else 0 for i in range(len(close))])
            hist_norm_series = pd.Series([self.histNorm[i] if i < len(self.histNorm) else 0 for i in range(len(close))])
            merged_osc = (rsi_norm_series + hist_norm_series) / 2
            merged_smooth = pta.ema(merged_osc, length=self.smoothLen)
            if merged_smooth is None:
                return pd.Series(0, index=close.index)
            return merged_smooth
        
        self.mergedSmooth = self.I(calc_merged_smooth)

    def next(self):
        if len(self.data) < 2:
            return
        
        current_osc = self.mergedSmooth[-1]
        prev_osc = self.mergedSmooth[-2] if len(self.mergedSmooth) > 1 else current_osc
        
        # Buy when oscillator crosses above zero
        if crossover(self.mergedSmooth, 0):
            if not self.position:
                self.buy()
        
        # Sell when oscillator crosses below zero
        elif crossover(0, self.mergedSmooth):
            if self.position:
                self.position.close()