"""
DS-TV Backtest Results: momentum-surge-screener-version-by-tomert
============================================================

--- SPY ---
  Return                    -70.80%
  Buy & Hold Return         40.20%
  Max Drawdown              -70.95%
  Sharpe Ratio              -5.31
  Sortino Ratio             -3.48
  Calmar Ratio              -0.65
  Profit Factor             0.46
  Expectancy                -0.27%
  SQN                       -4.89
  # Trades                  438
  Win Rate                  33.11%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.28%
  Exposure Time             88.40%
  Equity Final              29196.77$
  Equity Peak               100519.66$
  Avg Drawdown              -70.95%
  Max Drawdown Duration     643 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -46.23%
  Ann. Volatility           8.71%

--- BTC ---
  Return                    -26.48%
  Buy & Hold Return         0.29%
  Max Drawdown              -33.49%
  Sharpe Ratio              -1.11
  Sortino Ratio             -1.17
  Calmar Ratio              -0.43
  Profit Factor             0.74
  Expectancy                -0.28%
  SQN                       -1.28
  # Trades                  152
  Win Rate                  47.37%
  Best Trade                6.90%
  Worst Trade               -12.38%
  Avg Trade                 -0.32%
  Exposure Time             21.20%
  Equity Final              73516.42$
  Equity Peak               110539.42$
  Avg Drawdown              -5.18%
  Max Drawdown Duration     583 days 00:00:00
  Max Trade Duration        2 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -14.24%
  Ann. Volatility           12.86%

--- QQQ ---
  Return                    -72.58%
  Buy & Hold Return         45.93%
  Max Drawdown              -73.08%
  Sharpe Ratio              -4.50
  Sortino Ratio             -2.96
  Calmar Ratio              -0.66
  Profit Factor             0.55
  Expectancy                -0.28%
  SQN                       -4.02
  # Trades                  439
  Win Rate                  35.08%
  Best Trade                6.54%
  Worst Trade               -9.35%
  Avg Trade                 -0.29%
  Exposure Time             88.40%
  Equity Final              27421.11$
  Equity Peak               100572.37$
  Avg Drawdown              -73.08%
  Max Drawdown Duration     644 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -47.91%
  Ann. Volatility           10.65%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — momentum-surge-screener-version-by-tomert
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.ema50 = self.I(pta.ema, close, length=50)
        self.ema20 = self.I(pta.ema, close, length=20)
        self.rsi = self.I(pta.rsi, close, length=14)
        
        macd_result = self.I(lambda: pta.macd(close, fast=12, slow=26, signal=9))
        self.macd_line = self.I(lambda: pta.macd(close, fast=12, slow=26, signal=9)['MACD_12_26_9'] if pta.macd(close, fast=12, slow=26, signal=9) is not None else pd.Series(0, index=close.index))
        self.signal_line = self.I(lambda: pta.macd(close, fast=12, slow=26, signal=9)['MACDs_12_26_9'] if pta.macd(close, fast=12, slow=26, signal=9) is not None else pd.Series(0, index=close.index))
        
        self.avg_vol = self.I(pta.sma, volume, length=20)

    def next(self):
        if len(self.data) < 26:
            return
        
        close_price = self.data.Close[-1]
        ema50_val = self.ema50[-1]
        ema20_val = self.ema20[-1]
        rsi_val = self.rsi[-1]
        macd_val = self.macd_line[-1]
        signal_val = self.signal_line[-1]
        vol = self.data.Volume[-1]
        avg_vol_val = self.avg_vol[-1]
        
        long_signal = (
            close_price > ema50_val and
            close_price > ema20_val and
            rsi_val > 50 and
            rsi_val < 70 and
            crossover(self.macd_line, self.signal_line) and
            vol > avg_vol_val
        )
        
        if long_signal:
            if not self.position:
                self.buy()
        else:
            if self.position:
                self.sell()