"""
DS-TV Backtest Results: momentum-composite-oscillator-pro
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — momentum-composite-oscillator-pro
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsiLen = 14
    rocLen = 14
    macdFast = 12
    macdSlow = 26
    macdSignal = 9
    normLookback = 100
    smoothLen = 8
    signalLen = 5
    wRSI = 1.25
    wMACD = 1.50
    wROC = 1.00
    upperBand = 65.0
    lowerBand = 35.0
    midLine = 50.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # RSI calculation
        self.rsiVal = self.I(pta.rsi, close, length=self.rsiLen)

        # MACD calculation
        ema_fast = self.I(pta.ema, close, length=self.macdFast)
        ema_slow = self.I(pta.ema, close, length=self.macdSlow)
        self.macdLine = self.I(lambda: ema_fast - ema_slow)

        # ROC calculation
        def roc_calc():
            roc_series = pta.roc(close, length=self.rocLen)
            return roc_series if roc_series is not None else pd.Series(0, index=close.index)
        self.rocRaw = self.I(roc_calc)

        # Normalization function
        def normalize_to_100(src):
            hi = src.rolling(window=self.normLookback).max()
            lo = src.rolling(window=self.normLookback).min()
            rng = hi - lo
            result = pd.Series(50, index=src.index)
            mask = rng != 0
            result[mask] = 100 * (src[mask] - lo[mask]) / rng[mask]
            return result

        # MACD normalized
        self.macdNorm = self.I(lambda: normalize_to_100(self.macdLine))

        # ROC normalized
        self.rocNorm = self.I(lambda: normalize_to_100(self.rocRaw))

        # Composite calculation
        def calc_composite():
            weight_sum = self.wRSI + self.wMACD + self.wROC
            if weight_sum > 0:
                raw = (self.rsiVal * self.wRSI + 
                       self.macdNorm * self.wMACD + 
                       self.rocNorm * self.wROC) / weight_sum
            else:
                raw = pd.Series(50, index=close.index)
            return raw

        self.rawComposite = self.I(calc_composite)
        self.composite = self.I(pta.ema, self.rawComposite, length=self.smoothLen)
        self.signal = self.I(pta.ema, self.composite, length=self.signalLen)

    def next(self):
        if len(self.data) < max(self.normLookback, self.macdSlow, self.signalLen) + 5:
            return

        composite_val = self.composite[-1]
        signal_val = self.signal[-1]

        # Bullish cross: composite crosses above signal
        if crossover(self.composite, self.signal):
            if not self.position:
                self.buy()
        # Bearish cross: composite crosses below signal
        elif crossover(self.signal, self.composite):
            if self.position:
                self.position.close()