"""
DS-TV Backtest Results: multi-timeframe-rsi-regime-oscillator
============================================================

--- SPY ---
  Return                    -31.51%
  Buy & Hold Return         43.93%
  Max Drawdown              -34.03%
  Sharpe Ratio              -1.34
  Sortino Ratio             -1.56
  Calmar Ratio              -0.51
  Profit Factor             0.28
  Expectancy                -1.42%
  SQN                       -2.32
  # Trades                  23
  Win Rate                  34.78%
  Best Trade                5.31%
  Worst Trade               -10.85%
  Avg Trade                 -1.48%
  Exposure Time             94.00%
  Equity Final              68490.05$
  Equity Peak               103788.33$
  Avg Drawdown              -12.20%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        130 days 00:00:00
  Avg Trade Duration        35 days 00:00:00
  Ann. Return               -17.37%
  Ann. Volatility           12.97%

--- BTC ---
  Return                    -50.55%
  Buy & Hold Return         44.64%
  Max Drawdown              -77.89%
  Sharpe Ratio              -0.69
  Sortino Ratio             -0.77
  Calmar Ratio              -0.38
  Profit Factor             0.52
  Expectancy                -2.42%
  SQN                       -0.63
  # Trades                  16
  Win Rate                  62.50%
  Best Trade                23.78%
  Worst Trade               -61.17%
  Avg Trade                 -4.60%
  Exposure Time             42.68%
  Equity Final              49445.14$
  Equity Peak               146184.40$
  Avg Drawdown              -13.13%
  Max Drawdown Duration     699 days 00:00:00
  Max Trade Duration        71 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               -29.65%
  Ann. Volatility           42.72%

--- QQQ ---
  Return                    -34.10%
  Buy & Hold Return         44.93%
  Max Drawdown              -39.88%
  Sharpe Ratio              -1.20
  Sortino Ratio             -1.41
  Calmar Ratio              -0.48
  Profit Factor             0.20
  Expectancy                -1.91%
  SQN                       -2.43
  # Trades                  28
  Win Rate                  35.71%
  Best Trade                3.00%
  Worst Trade               -10.22%
  Avg Trade                 -1.97%
  Exposure Time             91.00%
  Equity Final              65897.04$
  Equity Peak               106400.71$
  Avg Drawdown              -13.54%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        161 days 00:00:00
  Avg Trade Duration        36 days 00:00:00
  Ann. Return               -18.96%
  Ann. Volatility           15.86%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — multi-timeframe-rsi-regime-oscillator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Macro settings
    rsiLenMacro = 14
    upperMacro = 50
    lowerMacro = 50
    
    # Micro settings
    rsiLenMicro = 14
    upperMicro = 50
    lowerMicro = 50
    
    # Macro timeframe in minutes (1W = 10080 minutes)
    macroTF = 10080
    # Micro timeframe in minutes (240 = 4H)
    microTF = 240
    
    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate RSI on current timeframe
        rsi_macro = self.I(pta.rsi, close, length=self.rsiLenMacro)
        rsi_micro = self.I(pta.rsi, close, length=self.rsiLenMicro)
        
        self.rsi_macro = rsi_macro
        self.rsi_micro = rsi_micro
        
        # Regime states
        self.macro_is_bull = None
        self.macro_is_bear = None
        self.macro_in_ntz = None
        
        self.macro_osc = None
        self.micro_osc = None
        
        # Signal flags
        self.macro_buy_signal = False
        self.macro_sell_signal = False
        self.micro_buy_signal = False
        self.micro_sell_signal = False
        
        # Previous states for transition detection
        self.prev_macro_is_bull = False
        self.prev_macro_is_bear = False
        self.prev_micro_above_upper = False
        self.prev_micro_below_lower = False

    def next(self):
        if len(self.data) < 2:
            return
        
        # Get current RSI values
        macro_rsi = self.rsi_macro[-1]
        micro_rsi = self.rsi_micro[-1]
        
        if macro_rsi is None or np.isnan(macro_rsi):
            return
        if micro_rsi is None or np.isnan(micro_rsi):
            return
        
        # Determine macro regime
        macro_is_bull = macro_rsi >= self.upperMacro
        macro_is_bear = macro_rsi <= self.lowerMacro
        macro_in_ntz = not (macro_is_bull or macro_is_bear)
        
        # Calculate oscillator values
        if macro_is_bull:
            macro_osc = macro_rsi - self.upperMacro
        elif macro_is_bear:
            macro_osc = macro_rsi - self.lowerMacro
        else:
            macro_osc = 0.0
        
        # Micro oscillator is gated by macro regime
        if not macro_in_ntz:
            if micro_rsi >= self.upperMicro:
                micro_osc = micro_rsi - self.upperMicro
            elif micro_rsi <= self.lowerMicro:
                micro_osc = micro_rsi - self.lowerMicro
            else:
                micro_osc = 0.0
        else:
            micro_osc = 0.0
        
        # Signal detection: macro signals on regime transitions
        macro_buy_signal = macro_is_bull and not self.prev_macro_is_bull
        macro_sell_signal = macro_is_bear and not self.prev_macro_is_bear
        
        # Micro signals: only when macro regime is active and micro crosses threshold
        micro_above_upper = micro_rsi >= self.upperMicro
        micro_below_lower = micro_rsi <= self.lowerMicro
        
        micro_buy_signal = macro_is_bull and micro_above_upper and not self.prev_micro_above_upper
        micro_sell_signal = macro_is_bear and micro_below_lower and not self.prev_micro_below_lower
        
        # Trading logic
        # Buy on macro bull transition or micro bull alignment
        if macro_buy_signal or micro_buy_signal:
            if not self.position:
                self.buy()
        
        # Sell on macro bear transition or micro bear alignment
        if macro_sell_signal or micro_sell_signal:
            if self.position:
                self.sell()
        
        # Alternative: close on regime exit
        if self.position and macro_sell_signal and not macro_is_bull:
            self.sell()
        if not self.position and macro_buy_signal and macro_is_bull:
            self.buy()
        
        # Update previous states
        self.prev_macro_is_bull = macro_is_bull
        self.prev_macro_is_bear = macro_is_bear
        self.prev_micro_above_upper = micro_above_upper
        self.prev_micro_below_lower = micro_below_lower


if __name__ == '__main__':
    import yfinance as yf
    
    # Download sample data
    data = yf.download('SPY', start='2020-01-01', end='2023-12-31', progress=False)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()