"""
DS-TV Backtest Results: optimal-buy-time-60-vs-252-sessions-comparison
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — optimal-buy-time-60-vs-252-sessions-comparison
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime, timedelta


class TvStrategy(Strategy):
    thresh_good = 0.1
    lookback_short = 60
    lookback_long = 252

    def init(self):
        self.day_count = 0
        self.last_day = None
        self.slot_data = {}
        
        self.sum_s = [0.0] * 13
        self.sum_l = [0.0] * 13
        self.cnt_s = [0] * 13
        self.cnt_l = [0] * 13
        self.wins_s = [0] * 13
        self.wins_l = [0] * 13
        
        self.avg_s = [0.0] * 13
        self.avg_l = [0.0] * 13
        self.wr_s = [0.0] * 13
        self.wr_l = [0.0] * 13

    def next(self):
        try:
            current_time = pd.Timestamp(self.data.index[-1])
        except:
            return
        
        if current_time.weekday() >= 5:
            return
        
        et_hour = (current_time.hour - 5) % 24
        et_minute = current_time.minute
        
        if not (9 <= et_hour < 16 or (et_hour == 9 and et_minute >= 30)):
            return
        
        if self.last_day is None or current_time.date() != self.last_day:
            self.last_day = current_time.date()
            self.day_count += 1
        
        slot = (et_hour - 9) * 2 + (1 if et_minute >= 30 else 0) - 1
        
        if slot < 0 or slot >= 13:
            return
        
        if len(self.data) > 0:
            high = self.data.High[-1]
            low = self.data.Low[-1]
            close = self.data.Close[-1]
            
            mid = (high + low) / 2.0
            
            if mid > 0:
                ret = (close - mid) / mid * 100.0
            else:
                ret = 0.0
            
            if self.day_count <= self.lookback_long:
                self.sum_l[slot] += ret
                self.cnt_l[slot] += 1
                if ret > 0.0:
                    self.wins_l[slot] += 1
            
            if self.day_count <= self.lookback_short:
                self.sum_s[slot] += ret
                self.cnt_s[slot] += 1
                if ret > 0.0:
                    self.wins_s[slot] += 1
            
            for i in range(13):
                if self.cnt_s[i] > 0:
                    self.avg_s[i] = self.sum_s[i] / self.cnt_s[i]
                    self.wr_s[i] = (self.wins_s[i] / self.cnt_s[i]) * 100.0
                
                if self.cnt_l[i] > 0:
                    self.avg_l[i] = self.sum_l[i] / self.cnt_l[i]
                    self.wr_l[i] = (self.wins_l[i] / self.cnt_l[i]) * 100.0
            
            if slot >= 0 and slot < 13:
                av_s = self.avg_s[slot]
                
                if av_s >= self.thresh_good and not self.position:
                    self.buy()
                elif av_s < -self.thresh_good and self.position:
                    self.sell()