"""
DS-TV Backtest Results: oscillateur-pro-goldplusinfinity
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(rsi(7),3)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "ema(rsi(7),3)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "ema(rsi(7),3)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — oscillateur-pro-goldplusinfinity
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsiLen = 7
    rsiSmooth = 3
    rsiOB = 70
    rsiOS = 30
    tsiLen = 14
    tsiSmooth = 5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        bar_index = pd.Series(range(len(close)))
        
        # RSI calculation with smoothing
        raw_rsi = self.I(pta.rsi, close, length=self.rsiLen)
        self.smoothed_rsi = self.I(pta.ema, raw_rsi, length=self.rsiSmooth)
        
        # TSI calculation - correlation with bar_index normalized
        def calc_tsi_normalized():
            corr = close.rolling(self.tsiLen).corr(bar_index)
            norm = np.minimum(np.maximum((corr + 1) * 50, 0), 100)
            return norm
        
        raw_tsi_norm = self.I(calc_tsi_normalized)
        self.tsi = self.I(pta.wma, raw_tsi_norm, length=self.tsiSmooth)
        
        # Convergence signals
        self.convergence_long_signal = self.I(self._convergence_long)
        self.convergence_short_signal = self.I(self._convergence_short)

    def _convergence_long(self):
        result = pd.Series(0, index=pd.Series(self.data.Close).index)
        for i in range(1, len(self.data.Close)):
            if (self.smoothed_rsi[i] > self.rsiOS and 
                self.smoothed_rsi[i-1] <= self.rsiOS and 
                self.tsi[i] < 40):
                result.iloc[i] = 1
        return result

    def _convergence_short(self):
        result = pd.Series(0, index=pd.Series(self.data.Close).index)
        for i in range(1, len(self.data.Close)):
            if (self.smoothed_rsi[i] < self.rsiOB and 
                self.smoothed_rsi[i-1] >= self.rsiOB and 
                self.tsi[i] > 60):
                result.iloc[i] = 1
        return result

    def next(self):
        if len(self.data.Close) < 2:
            return
        
        # Buy signal: RSI crosses above OS (oversold) and TSI below 40
        if self.convergence_long_signal[-1] > 0:
            if not self.position:
                self.buy()
        
        # Sell signal: RSI crosses below OB (overbought) and TSI above 60
        elif self.convergence_short_signal[-1] > 0:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    results = bt.run()
    print(results)
    bt.plot()