"""
DS-TV Backtest Results: panda-oracle-oscillator
============================================================

--- SPY ---
  Return                    -14.27%
  Buy & Hold Return         5.75%
  Max Drawdown              -15.81%
  Sharpe Ratio              -1.76
  Sortino Ratio             -2.00
  Calmar Ratio              -0.47
  Profit Factor             0.54
  Expectancy                -0.19%
  SQN                       -2.06
  # Trades                  74
  Win Rate                  33.78%
  Best Trade                2.46%
  Worst Trade               -2.04%
  Avg Trade                 -0.19%
  Exposure Time             14.40%
  Equity Final              85730.11$
  Equity Peak               101828.54$
  Avg Drawdown              -4.05%
  Max Drawdown Duration     81 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -7.47%
  Ann. Volatility           4.24%

--- BTC ---
  Return                    -23.16%
  Buy & Hold Return         -17.18%
  Max Drawdown              -33.82%
  Sharpe Ratio              -1.02
  Sortino Ratio             -1.11
  Calmar Ratio              -0.36
  Profit Factor             0.00
  Expectancy                -13.66%
  SQN                       -1.40
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -3.81%
  Worst Trade               -23.51%
  Avg Trade                 -14.22%
  Exposure Time             9.30%
  Equity Final              76836.39$
  Equity Peak               104663.15$
  Avg Drawdown              -13.02%
  Max Drawdown Duration     308 days 00:00:00
  Max Trade Duration        63 days 00:00:00
  Avg Trade Duration        34 days 00:00:00
  Ann. Return               -12.33%
  Ann. Volatility           12.08%

--- QQQ ---
  Return                    -14.96%
  Buy & Hold Return         4.17%
  Max Drawdown              -16.94%
  Sharpe Ratio              -1.30
  Sortino Ratio             -1.56
  Calmar Ratio              -0.46
  Profit Factor             0.64
  Expectancy                -0.19%
  SQN                       -1.63
  # Trades                  75
  Win Rate                  36.00%
  Best Trade                3.75%
  Worst Trade               -2.64%
  Avg Trade                 -0.20%
  Exposure Time             14.60%
  Equity Final              85041.90$
  Equity Peak               100435.74$
  Avg Drawdown              -8.54%
  Max Drawdown Duration     110 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -7.84%
  Ann. Volatility           6.03%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — panda-oracle-oscillator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema_fast_len = 25
    ema_slow_len = 200
    smooth_len = 3
    overbought = 60.0
    oversold = -60.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate EMA25 and EMA200
        ema25 = self.I(pta.ema, close, length=self.ema_fast_len)
        ema200 = self.I(pta.ema, close, length=self.ema_slow_len)
        
        # Raw oscillator: % spread between EMA25 and EMA200
        def calculate_raw_osc():
            ema25_vals = pta.ema(close, length=self.ema_fast_len)
            ema200_vals = pta.ema(close, length=self.ema_slow_len)
            raw = ((ema25_vals - ema200_vals) / ema200_vals) * 100
            return raw
        
        raw_osc = self.I(calculate_raw_osc)
        
        # Dynamic normalization over last 200 bars
        def calculate_normalized_osc():
            raw = calculate_raw_osc()
            max_val = pd.Series(np.abs(raw)).rolling(window=200).max()
            osc = pd.Series(np.where(max_val != 0.0, (raw / max_val) * 100.0, 0.0), index=raw.index)
            return osc
        
        self.osc = self.I(calculate_normalized_osc)
        
        # Smoothed signal line
        def calculate_signal():
            osc_vals = calculate_normalized_osc()
            signal = pta.ema(osc_vals, length=self.smooth_len)
            return signal if signal is not None else pd.Series(0, index=osc_vals.index)
        
        self.signal_line = self.I(calculate_signal)
        
        # Momentum (1-bar delta)
        def calculate_momentum():
            osc_vals = calculate_normalized_osc()
            mom = osc_vals.diff()
            return mom
        
        self.mom = self.I(calculate_momentum)

    def next(self):
        # Buy on oscillator crossing above signal line (bullish signal)
        if len(self.osc) < 2 or len(self.signal_line) < 2:
            return
        
        if crossover(self.osc, self.signal_line):
            if not self.position:
                self.buy()
        # Sell on oscillator crossing below signal line (bearish signal)
        elif crossover(self.signal_line, self.osc):
            if self.position:
                self.sell()
        
        # Additional exit: take profit in overbought zone
        if self.position and self.osc[-1] >= self.overbought:
            self.sell()
        
        # Additional entry confirmation: buy in oversold zone if crossing up
        if not self.position and self.osc[-1] <= self.oversold:
            if crossover(self.osc, self.signal_line):
                self.buy()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()