"""
DS-TV Backtest Results: rescaled-rsi-adaptiversi
============================================================

--- SPY ---
  Return                    2.43%
  Buy & Hold Return         41.94%
  Max Drawdown              -23.06%
  Sharpe Ratio              0.08
  Sortino Ratio             0.12
  Calmar Ratio              0.05
  Profit Factor             1.36
  Expectancy                0.63%
  SQN                       0.22
  # Trades                  15
  Win Rate                  20.00%
  Best Trade                24.41%
  Worst Trade               -8.00%
  Avg Trade                 0.38%
  Exposure Time             86.60%
  Equity Final              102432.87$
  Equity Peak               110109.74$
  Avg Drawdown              -2.72%
  Max Drawdown Duration     497 days 00:00:00
  Max Trade Duration        169 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               1.22%
  Ann. Volatility           15.05%

--- BTC ---
  Return                    -45.91%
  Buy & Hold Return         46.22%
  Max Drawdown              -54.95%
  Sharpe Ratio              -1.09
  Sortino Ratio             -1.10
  Calmar Ratio              -0.48
  Profit Factor             0.00
  Expectancy                -37.84%
  SQN                       -2.45
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -26.19%
  Worst Trade               -49.50%
  Avg Trade                 -38.95%
  Exposure Time             41.45%
  Equity Final              54089.98$
  Equity Peak               101070.84$
  Avg Drawdown              -54.95%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        278 days 00:00:00
  Avg Trade Duration        151 days 00:00:00
  Ann. Return               -26.42%
  Ann. Volatility           24.27%

--- QQQ ---
  Return                    13.65%
  Buy & Hold Return         42.67%
  Max Drawdown              -25.66%
  Sharpe Ratio              0.33
  Sortino Ratio             0.53
  Calmar Ratio              0.26
  Profit Factor             1.65
  Expectancy                1.58%
  SQN                       0.37
  # Trades                  12
  Win Rate                  33.33%
  Best Trade                31.08%
  Worst Trade               -12.39%
  Avg Trade                 1.04%
  Exposure Time             86.60%
  Equity Final              113649.38$
  Equity Peak               119367.04$
  Avg Drawdown              -2.76%
  Max Drawdown Duration     410 days 00:00:00
  Max Trade Duration        161 days 00:00:00
  Avg Trade Duration        53 days 00:00:00
  Ann. Return               6.66%
  Ann. Volatility           20.38%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rescaled-rsi-adaptiversi
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    Length_in = 70
    Length_out = 14

    def init(self):
        close = pd.Series(self.data.Close)
        
        def calculate_adaptive_rsi():
            result = pd.Series(index=close.index, dtype=float)
            middle = 0.0
            CC_vol = 1e-10
            myRSI = 50.0
            
            for i in range(len(close)):
                length = min(self.Length_in, i + 1)
                SF = 1.0 / length
                
                if i == 0:
                    middle = close.iloc[i]
                    CC_vol = 1e-10
                    myRSI = 50.0
                else:
                    middle = (1.0 - SF) * middle + SF * close.iloc[i]
                    CC_vol = (1.0 - SF) * CC_vol + SF * abs(close.iloc[i] - close.iloc[i-1])
                    myRSI = 50.0 + 50.0 * ((close.iloc[i] - middle) / CC_vol / (length - 1.0))
                
                logit_StDev_in = 2.0 / np.sqrt(self.Length_in - 1.0)
                logit_StDev_out = 2.0 / np.sqrt(self.Length_out - 1.0)
                
                eps = 1e-10
                safe_RSI = np.clip(myRSI, eps, 100.0 - eps)
                
                RSI_Zscore = np.log(safe_RSI / (100.0 - safe_RSI)) / logit_StDev_in
                output_RSI = 100.0 * np.exp(RSI_Zscore * logit_StDev_out) / (1.0 + np.exp(RSI_Zscore * logit_StDev_out))
                
                result.iloc[i] = output_RSI
            
            return result
        
        self.adaptive_rsi = self.I(calculate_adaptive_rsi)

    def next(self):
        if len(self.data) < 2:
            return
        
        if crossover(self.adaptive_rsi, 30):
            self.buy()
        elif crossover(70, self.adaptive_rsi):
            self.sell()