"""
DS-TV Backtest Results: rsi-multi-stock-table-prepost-mkt-howlytr
============================================================

--- SPY ---
  Return                    -14.82%
  Buy & Hold Return         43.93%
  Max Drawdown              -20.00%
  Sharpe Ratio              -0.60
  Sortino Ratio             -0.85
  Calmar Ratio              -0.39
  Profit Factor             0.10
  Expectancy                -3.03%
  SQN                       -1.16
  # Trades                  5
  Win Rate                  40.00%
  Best Trade                0.83%
  Worst Trade               -13.15%
  Avg Trade                 -3.18%
  Exposure Time             53.60%
  Equity Final              85175.98$
  Equity Peak               101065.92$
  Avg Drawdown              -7.10%
  Max Drawdown Duration     620 days 00:00:00
  Max Trade Duration        182 days 00:00:00
  Avg Trade Duration        76 days 00:00:00
  Ann. Return               -7.77%
  Ann. Volatility           12.87%

--- BTC ---
  Return                    -6.20%
  Buy & Hold Return         44.64%
  Max Drawdown              -34.84%
  Sharpe Ratio              -0.08
  Sortino Ratio             -0.12
  Calmar Ratio              -0.09
  Profit Factor             0.92
  Expectancy                -0.53%
  SQN                       0.07
  # Trades                  10
  Win Rate                  60.00%
  Best Trade                20.62%
  Worst Trade               -39.55%
  Avg Trade                 -2.08%
  Exposure Time             66.35%
  Equity Final              93796.83$
  Equity Peak               131649.20$
  Avg Drawdown              -8.02%
  Max Drawdown Duration     488 days 00:00:00
  Max Trade Duration        148 days 00:00:00
  Avg Trade Duration        48 days 00:00:00
  Ann. Return               -3.15%
  Ann. Volatility           37.48%

--- QQQ ---
  Return                    -4.03%
  Buy & Hold Return         44.93%
  Max Drawdown              -25.14%
  Sharpe Ratio              -0.11
  Sortino Ratio             -0.17
  Calmar Ratio              -0.08
  Profit Factor             0.86
  Expectancy                -0.41%
  SQN                       -0.19
  # Trades                  6
  Win Rate                  50.00%
  Best Trade                7.38%
  Worst Trade               -14.27%
  Avg Trade                 -0.68%
  Exposure Time             62.20%
  Equity Final              95969.99$
  Equity Peak               114387.48$
  Avg Drawdown              -6.00%
  Max Drawdown Duration     451 days 00:00:00
  Max Trade Duration        184 days 00:00:00
  Avg Trade Duration        75 days 00:00:00
  Ann. Return               -2.05%
  Ann. Volatility           18.66%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rsi-multi-stock-table-prepost-mkt-howlytr
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsi_length = 8
    lvl_ob = 70
    lvl_os = 30

    def init(self):
        close = pd.Series(self.data.Close)
        self.rsi = self.I(pta.rsi, close, length=self.rsi_length)

    def next(self):
        if len(self.data) < self.rsi_length + 1:
            return
        
        current_rsi = self.rsi[-1]
        
        if current_rsi is None or np.isnan(current_rsi):
            return
        
        if not self.position:
            if current_rsi < self.lvl_os and len(self.rsi) > 1:
                if self.rsi[-1] > self.rsi[-2]:
                    self.buy()
            elif current_rsi > self.lvl_ob and len(self.rsi) > 1:
                if self.rsi[-1] < self.rsi[-2]:
                    self.sell()
        else:
            if self.position.is_long:
                if current_rsi > self.lvl_ob:
                    self.position.close()
            elif self.position.is_short:
                if current_rsi < self.lvl_os:
                    self.position.close()