"""
DS-TV Backtest Results: rsi-suite-foundation
============================================================

--- SPY ---
  Return                    15.36%
  Buy & Hold Return         43.93%
  Max Drawdown              -7.33%
  Sharpe Ratio              0.73
  Sortino Ratio             1.08
  Calmar Ratio              1.02
  Profit Factor             2.00
  Expectancy                0.80%
  SQN                       0.82
  # Trades                  19
  Win Rate                  42.11%
  Best Trade                14.58%
  Worst Trade               -3.24%
  Avg Trade                 0.73%
  Exposure Time             73.60%
  Equity Final              115361.74$
  Equity Peak               123795.85$
  Avg Drawdown              -1.38%
  Max Drawdown Duration     303 days 00:00:00
  Max Trade Duration        101 days 00:00:00
  Avg Trade Duration        27 days 00:00:00
  Ann. Return               7.47%
  Ann. Volatility           10.21%

--- BTC ---
  Return                    10.92%
  Buy & Hold Return         44.64%
  Max Drawdown              -20.90%
  Sharpe Ratio              0.20
  Sortino Ratio             0.33
  Calmar Ratio              0.25
  Profit Factor             1.35
  Expectancy                0.78%
  SQN                       0.25
  # Trades                  33
  Win Rate                  27.27%
  Best Trade                55.86%
  Worst Trade               -8.88%
  Avg Trade                 0.30%
  Exposure Time             53.08%
  Equity Final              110920.37$
  Equity Peak               129110.46$
  Avg Drawdown              -6.10%
  Max Drawdown Duration     225 days 00:00:00
  Max Trade Duration        69 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               5.31%
  Ann. Volatility           26.19%

--- QQQ ---
  Return                    32.87%
  Buy & Hold Return         44.93%
  Max Drawdown              -10.01%
  Sharpe Ratio              1.06
  Sortino Ratio             1.71
  Calmar Ratio              1.54
  Profit Factor             2.87
  Expectancy                1.36%
  SQN                       1.22
  # Trades                  23
  Win Rate                  43.48%
  Best Trade                19.63%
  Worst Trade               -3.58%
  Avg Trade                 1.25%
  Exposure Time             70.80%
  Equity Final              132867.02$
  Equity Peak               147644.65$
  Avg Drawdown              -1.81%
  Max Drawdown Duration     147 days 00:00:00
  Max Trade Duration        101 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               15.40%
  Ann. Volatility           14.49%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rsi-suite-foundation
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsi_length = 14
    rsi_source = "close"
    regime_mode = "Mid (50)"
    regime_low = 45.0
    regime_high = 55.0
    mid_level = 50.0
    ob_level = 70.0
    os_level = 30.0
    smooth_on = False
    smooth_len = 5
    div_enabled = True
    div_type = "Both"
    div_left = 3
    div_right = 3
    div_preview_right = 1
    div_min_bars_between = 5
    div_max_bars_between = 120
    div_cooldown_bars = 10
    div_min_rsi_delta = 2.0
    div_min_price_delta_pct = 0.1
    div_context_filter = "Off"
    sig_type = "RSI Mid Cross"
    fr_left = 1
    fr_right = 1
    sig_once_per_pivot = True
    sig_tl_min_step = 0.0
    sig_tl_extend_right = True
    filter_signals_by_regime = False

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        rsi_raw = self.I(pta.rsi, close, length=self.rsi_length)
        
        if self.smooth_on:
            self.rsi_plot = self.I(lambda: pta.sma(rsi_raw, length=self.smooth_len) or pd.Series(50, index=close.index))
        else:
            self.rsi_plot = rsi_raw
        
        self.mid_level_val = self.mid_level
        self.ob_level_val = self.ob_level
        self.os_level_val = self.os_level
        
        self.regime_low_eff = min(self.regime_low, self.regime_high)
        self.regime_high_eff = max(self.regime_low, self.regime_high)
        
        self.bull_thresh = self._get_bull_thresh()
        self.bear_thresh = self._get_bear_thresh()
        
        if self.div_enabled:
            self.price_low = low
            self.price_high = high
            self.div_src_low = low
            self.div_src_high = high
            self.last_bull_div_bar = None
            self.last_bear_div_bar = None
        
        self.last_signal_bar = None
        self.in_long_from_signal = False
        self.in_short_from_signal = False

    def _get_bull_thresh(self):
        if self.regime_mode == "Mid (50)":
            return self.mid_level
        elif self.regime_mode == "Range (40/60)":
            return 60.0
        elif self.regime_mode == "Trend (20/80)":
            return 80.0
        else:
            return self.regime_high_eff

    def _get_bear_thresh(self):
        if self.regime_mode == "Mid (50)":
            return self.mid_level
        elif self.regime_mode == "Range (40/60)":
            return 40.0
        elif self.regime_mode == "Trend (20/80)":
            return 20.0
        else:
            return self.regime_low_eff

    def _get_regime_state(self, rsi_val):
        if self.regime_mode == "Mid (50)":
            return 1 if rsi_val >= self.bull_thresh else -1
        else:
            if rsi_val >= self.bull_thresh:
                return 1
            elif rsi_val <= self.bear_thresh:
                return -1
            else:
                return 0

    def next(self):
        if len(self.data) < max(self.rsi_length + 5, self.div_left + self.div_right + 5):
            return
        
        rsi_val = self.rsi_plot[-1]
        regime_state = self._get_regime_state(rsi_val)
        
        if self.sig_type == "RSI Mid Cross":
            if crossover(self.rsi_plot, self.mid_level_val):
                regime_ok = not self.filter_signals_by_regime or regime_state <= 0
                if regime_ok and not self.position:
                    self.buy()
                    self.in_long_from_signal = True
            elif crossover(self.mid_level_val, self.rsi_plot):
                regime_ok = not self.filter_signals_by_regime or regime_state >= 0
                if regime_ok and self.position:
                    self.position.close()
                    self.in_long_from_signal = False
        
        elif self.sig_type == "None":
            if rsi_val <= self.os_level_val and len(self.data) > 1:
                if self.rsi_plot[-1] > self.rsi_plot[-2] and not self.position:
                    self.buy()
            elif rsi_val >= self.ob_level_val and len(self.data) > 1:
                if self.rsi_plot[-1] < self.rsi_plot[-2] and self.position:
                    self.position.close()
        
        if self.div_enabled and self.position and len(self.data) > self.div_right + 5:
            if rsi_val >= self.ob_level_val and self._check_bearish_divergence():
                self.position.close()
        
        if self.div_enabled and not self.position and len(self.data) > self.div_right + 5:
            if rsi_val <= self.os_level_val and self._check_bullish_divergence():
                self.buy()

    def _check_bullish_divergence(self):
        if len(self.data) < self.div_left + self.div_right + 2:
            return False
        
        current_idx = len(self.data) - 1
        
        low_window = self.data.Low[-self.div_left - self.div_right - 1:]
        if len(low_window) < self.div_left + self.div_right + 1:
            return False
        
        rsi_window = self.rsi_plot[-self.div_left - self.div_right - 1:]
        
        min_idx = np.argmin(low_window)
        if min_idx <= self.div_left or min_idx >= len(low_window) - self.div_right:
            return False
        
        if min_idx > 0:
            prev_min_idx = np.argmin(low_window[:min_idx - 1]) if min_idx > 1 else None
            if prev_min_idx is not None and prev_min_idx > 0:
                low_curr = low_window.iloc[min_idx]
                low_prev = low_window.iloc[prev_min_idx]
                rsi_curr = rsi_window.iloc[min_idx]
                rsi_prev = rsi_window.iloc[prev_min_idx]
                
                bars_between = min_idx - prev_min_idx
                if self.div_min_bars_between <= bars_between <= self.div_max_bars_between:
                    if low_curr < low_prev and rsi_curr > rsi_prev:
                        if abs(rsi_curr - rsi_prev) >= self.div_min_rsi_delta:
                            price_delta_pct = abs(low_curr - low_prev) / low_prev * 100
                            if price_delta_pct >= self.div_min_price_delta_pct:
                                if self.last_bull_div_bar is None or (current_idx - self.last_bull_div_bar) >= self.div_cooldown_bars:
                                    self.last_bull_div_bar = current_idx
                                    return True
        return False

    def _check_bearish_divergence(self):
        if len(self.data) < self.div_left + self.div_right + 2:
            return False
        
        current_idx = len(self.data) - 1
        
        high_window = self.data.High[-self.div_left - self.div_right - 1:]
        if len(high_window) < self.div_left + self.div_right + 1:
            return False
        
        rsi_window = self.rsi_plot[-self.div_left - self.div_right - 1:]
        
        max_idx = np.argmax(high_window)
        if max_idx <= self.div_left or max_idx >= len(high_window) - self.div_right:
            return False
        
        if max_idx > 0:
            prev_max_idx = np.argmax(high_window[:max_idx - 1]) if max_idx > 1 else None
            if prev_max_idx is not None and prev_max_idx > 0:
                high_curr = high_window.iloc[max_idx]
                high_prev = high_window.iloc[prev_max_idx]
                rsi_curr = rsi_window.iloc[max_idx]
                rsi_prev = rsi_window.iloc[prev_max_idx]
                
                bars_between = max_idx - prev_max_idx
                if self.div_min_bars_between <= bars_between <= self.div_max_bars_between:
                    if high_curr > high_prev and rsi_curr < rsi_prev:
                        if abs(rsi_curr - rsi_prev) >= self.div_min_rsi_delta:
                            price_delta_pct = abs(high_curr - high_prev) / high_prev * 100
                            if price_delta_pct >= self.div_min_price_delta_pct:
                                if self.last_bear_div_bar is None or (current_idx - self.last_bear_div_bar) >= self.div_cooldown_bars:
                                    self.last_bear_div_bar = current_idx
                                    return True
        return False