"""
DS-TV Backtest Results: rsi-dss-bressert-crlmx
============================================================

--- SPY ---
  Return                    20.59%
  Buy & Hold Return         38.96%
  Max Drawdown              -11.14%
  Sharpe Ratio              0.94
  Sortino Ratio             1.51
  Calmar Ratio              0.89
  Profit Factor             3.96
  Expectancy                1.90%
  SQN                       1.70
  # Trades                  10
  Win Rate                  90.00%
  Best Trade                4.99%
  Worst Trade               -6.41%
  Avg Trade                 1.85%
  Exposure Time             34.00%
  Equity Final              120594.98$
  Equity Peak               121879.07$
  Avg Drawdown              -1.90%
  Max Drawdown Duration     277 days 00:00:00
  Max Trade Duration        36 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               9.90%
  Ann. Volatility           10.49%

--- BTC ---
  Return                    -19.90%
  Buy & Hold Return         11.75%
  Max Drawdown              -41.75%
  Sharpe Ratio              -0.40
  Sortino Ratio             -0.50
  Calmar Ratio              -0.25
  Profit Factor             1.22
  Expectancy                0.78%
  SQN                       -0.01
  # Trades                  15
  Win Rate                  53.33%
  Best Trade                20.81%
  Worst Trade               -21.47%
  Avg Trade                 0.23%
  Exposure Time             43.09%
  Equity Final              80099.05$
  Equity Peak               125230.49$
  Avg Drawdown              -7.10%
  Max Drawdown Duration     285 days 00:00:00
  Max Trade Duration        57 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               -10.49%
  Ann. Volatility           26.51%

--- QQQ ---
  Return                    14.86%
  Buy & Hold Return         41.48%
  Max Drawdown              -14.13%
  Sharpe Ratio              0.51
  Sortino Ratio             0.75
  Calmar Ratio              0.51
  Profit Factor             2.57
  Expectancy                1.64%
  SQN                       1.03
  # Trades                  10
  Win Rate                  80.00%
  Best Trade                6.42%
  Worst Trade               -9.75%
  Avg Trade                 1.54%
  Exposure Time             40.60%
  Equity Final              114859.87$
  Equity Peak               118375.27$
  Avg Drawdown              -2.63%
  Max Drawdown Duration     287 days 00:00:00
  Max Trade Duration        64 days 00:00:00
  Avg Trade Duration        29 days 00:00:00
  Ann. Return               7.23%
  Ann. Volatility           14.27%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rsi-dss-bressert-crlmx
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsi_length = 14
    period_k = 10
    smooth_k = 9
    period_d = 5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # RSI calculation
        change = close.diff()
        up = change.clip(lower=0).ewm(span=self.rsi_length, adjust=False).mean()
        down = -change.clip(upper=0).ewm(span=self.rsi_length, adjust=False).mean()
        rs = up / down.replace(0, np.nan)
        self.rsi = self.I(lambda: 100 - (100 / (1 + rs)))
        
        # Stochastic calculation
        lowest_low = low.rolling(window=self.period_k).min()
        highest_high = high.rolling(window=self.period_k).max()
        stoch_raw = 100 * (close - lowest_low) / (highest_high - lowest_low).replace(0, np.nan)
        
        # DSS Bressert calculation - K line is EMA of Stochastic
        k = stoch_raw.ewm(span=self.smooth_k, adjust=False).mean()
        
        # D line is EMA of K
        d = k.ewm(span=self.period_d, adjust=False).mean()
        
        # Double Smoothed Stochastic - apply stochastic to K values
        lowest_k = k.rolling(window=self.period_k).min()
        highest_k = k.rolling(window=self.period_k).max()
        dss_raw = 100 * (k - lowest_k) / (highest_k - lowest_k).replace(0, np.nan)
        
        # DSS K and D
        self.dss_k = self.I(lambda: dss_raw.ewm(span=self.smooth_k, adjust=False).mean())
        self.dss_d = self.I(lambda: self.dss_k.ewm(span=self.period_d, adjust=False).mean() if isinstance(self.dss_k, pd.Series) else pd.Series(50, index=close.index))

    def next(self):
        # Buy signal: RSI or DSS crossing above oversold levels with upward momentum
        if len(self.data) < 2:
            return
        
        # RSI oversold crossover (below 30, crossing up)
        if self.rsi[-2] <= 30 and self.rsi[-1] > 30:
            if not self.position:
                self.buy()
        
        # DSS oversold crossover (below 20, crossing up)
        elif self.dss_k[-2] <= 20 and self.dss_k[-1] > 20:
            if not self.position:
                self.buy()
        
        # Sell signal: RSI or DSS crossing below overbought levels with downward momentum
        # RSI overbought crossover (above 70, crossing down)
        if self.rsi[-2] >= 70 and self.rsi[-1] < 70:
            if self.position:
                self.position.close()
        
        # DSS overbought crossover (above 80, crossing down)
        elif self.dss_k[-2] >= 80 and self.dss_k[-1] < 80:
            if self.position:
                self.position.close()