"""
DS-TV Backtest Results: rsi-mean-reversion
============================================================

--- SPY ---
  Return                    -3.02%
  Buy & Hold Return         43.93%
  Max Drawdown              -16.99%
  Sharpe Ratio              -0.11
  Sortino Ratio             -0.17
  Calmar Ratio              -0.09
  Profit Factor             0.94
  Expectancy                -0.04%
  SQN                       -0.19
  # Trades                  43
  Win Rate                  46.51%
  Best Trade                5.40%
  Worst Trade               -5.97%
  Avg Trade                 -0.06%
  Exposure Time             70.40%
  Equity Final              96984.61$
  Equity Peak               110864.40$
  Avg Drawdown              -3.73%
  Max Drawdown Duration     521 days 00:00:00
  Max Trade Duration        27 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -1.53%
  Ann. Volatility           13.74%

--- BTC ---
  Return                    4.67%
  Buy & Hold Return         44.64%
  Max Drawdown              -28.75%
  Sharpe Ratio              0.08
  Sortino Ratio             0.13
  Calmar Ratio              0.08
  Profit Factor             1.21
  Expectancy                0.37%
  SQN                       0.15
  # Trades                  50
  Win Rate                  60.00%
  Best Trade                25.62%
  Worst Trade               -17.65%
  Avg Trade                 0.19%
  Exposure Time             63.06%
  Equity Final              104665.95$
  Equity Peak               127278.88$
  Avg Drawdown              -8.01%
  Max Drawdown Duration     373 days 00:00:00
  Max Trade Duration        28 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               2.30%
  Ann. Volatility           27.91%

--- QQQ ---
  Return                    -12.20%
  Buy & Hold Return         44.93%
  Max Drawdown              -19.51%
  Sharpe Ratio              -0.39
  Sortino Ratio             -0.56
  Calmar Ratio              -0.33
  Profit Factor             0.70
  Expectancy                -0.25%
  SQN                       -0.91
  # Trades                  40
  Win Rate                  37.50%
  Best Trade                5.01%
  Worst Trade               -4.11%
  Avg Trade                 -0.27%
  Exposure Time             64.00%
  Equity Final              87801.65$
  Equity Peak               104267.90$
  Avg Drawdown              -3.96%
  Max Drawdown Duration     595 days 00:00:00
  Max Trade Duration        31 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -6.35%
  Ann. Volatility           16.35%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rsi-mean-reversion
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsiLength = 3
    oversold = 40
    overbought = 70
    tradeDirection = 'Both'
    awaitBarConfirmation = True

    def init(self):
        close = pd.Series(self.data.Close)
        self.rsi = self.I(pta.rsi, close, length=self.rsiLength)

    def next(self):
        if len(self.data) < self.rsiLength + 1:
            return

        rsi_current = self.rsi[-1]
        rsi_prev = self.rsi[-2]

        canLong = self.tradeDirection == 'Long Only' or self.tradeDirection == 'Both'
        canShort = self.tradeDirection == 'Short Only' or self.tradeDirection == 'Both'

        longSignal = rsi_prev <= self.oversold and rsi_current > self.oversold
        shortSignal = rsi_prev >= self.overbought and rsi_current < self.overbought

        if longSignal:
            if canShort and self.position.is_short:
                self.position.close()
            if canLong and not self.position:
                self.buy()

        if shortSignal:
            if canLong and self.position.is_long:
                self.position.close()
            if canShort and not self.position:
                self.sell()