"""
DS-TV Backtest Results: rsistoch
============================================================

--- SPY ---
  ERROR: Indicator "calc_rsi(14)" error. See traceback above.

--- BTC ---
  ERROR: Indicator "calc_rsi(14)" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "calc_rsi(14)" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — rsistoch
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len = 14
    smoothK = 3
    smoothD = 3
    lengthStoch = 5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # RSI calculation
        def calc_rsi(src, length):
            up = pta.rma(np.maximum(np.diff(src, prepend=src.iloc[0]), 0), length=length)
            down = pta.rma(-np.minimum(np.diff(src, prepend=src.iloc[0]), 0), length=length)
            rsi = pd.Series(index=src.index, dtype='float64')
            for i in range(len(src)):
                if down.iloc[i] == 0:
                    rsi.iloc[i] = 100 if up.iloc[i] > 0 else 0
                elif up.iloc[i] == 0:
                    rsi.iloc[i] = 0
                else:
                    rsi.iloc[i] = 100 - (100 / (1 + up.iloc[i] / down.iloc[i]))
            return rsi
        
        self.rsi = self.I(calc_rsi, close, self.len)
        
        # Stochastic calculation
        def calc_stoch(c, h, l, length, smoothk, smoothd):
            stoch_raw = pta.stoch(h, l, c, k=length, d=smoothd, smooth_k=smoothk)
            if stoch_raw is not None:
                k_col = stoch_raw.iloc[:, 0] if stoch_raw.shape[1] > 0 else pd.Series(50, index=c.index)
                return k_col
            return pd.Series(50, index=c.index)
        
        self.stoch_k = self.I(calc_stoch, close, high, low, self.lengthStoch, self.smoothK, self.smoothD)

    def next(self):
        if len(self.data) < 2:
            return
        
        rsi = self.rsi[-1]
        stoch = self.stoch_k[-1]
        
        if crossover(self.rsi, 30) and self.stoch_k[-1] < 30:
            self.buy()
        elif crossover(70, self.rsi) and self.stoch_k[-1] > 70:
            self.sell()