"""
DS-TV Backtest Results: st-scalping
============================================================

--- SPY ---
  Return                    10.24%
  Buy & Hold Return         40.20%
  Max Drawdown              -5.19%
  Sharpe Ratio              0.76
  Sortino Ratio             1.11
  Calmar Ratio              0.97
  Profit Factor             7.51
  Expectancy                5.23%
  SQN                       0.76
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                12.06%
  Worst Trade               -1.61%
  Avg Trade                 5.01%
  Exposure Time             31.00%
  Equity Final              110240.53$
  Equity Peak               114561.76$
  Avg Drawdown              -1.16%
  Max Drawdown Duration     202 days 00:00:00
  Max Trade Duration        182 days 00:00:00
  Avg Trade Duration        110 days 00:00:00
  Ann. Return               5.04%
  Ann. Volatility           6.60%

--- BTC ---
  Return                    -2.75%
  Buy & Hold Return         0.29%
  Max Drawdown              -2.75%
  Sharpe Ratio              -0.81
  Sortino Ratio             -0.80
  Calmar Ratio              -0.50
  Profit Factor             0.00
  Expectancy                -2.93%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -2.93%
  Worst Trade               -2.93%
  Avg Trade                 -2.93%
  Exposure Time             0.41%
  Equity Final              97247.51$
  Equity Peak               100000.00$
  Avg Drawdown              -2.75%
  Max Drawdown Duration     36 days 00:00:00
  Max Trade Duration        2 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -1.38%
  Ann. Volatility           1.70%

--- QQQ ---
  Return                    8.61%
  Buy & Hold Return         45.93%
  Max Drawdown              -9.76%
  Sharpe Ratio              0.49
  Sortino Ratio             0.69
  Calmar Ratio              0.44
  Profit Factor             2.61
  Expectancy                4.78%
  SQN                       0.42
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                15.48%
  Worst Trade               -5.92%
  Avg Trade                 4.23%
  Exposure Time             28.40%
  Equity Final              108606.52$
  Equity Peak               115249.64$
  Avg Drawdown              -2.42%
  Max Drawdown Duration     376 days 00:00:00
  Max Trade Duration        182 days 00:00:00
  Avg Trade Duration        101 days 00:00:00
  Ann. Return               4.25%
  Ann. Volatility           8.59%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — st-scalping
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema_length = 50
    zone_percent = 0.2
    wick_tolerance = 0.0

    def init(self):
        close = pd.Series(self.data.Close)
        self.ema = self.I(pta.ema, close, length=self.ema_length)
        
        self.zone_size = self.I(
            lambda: self.ema * self.zone_percent / 100
        )
        self.upper_zone = self.I(
            lambda: self.ema + self.zone_size
        )
        self.lower_zone = self.I(
            lambda: self.ema - self.zone_size
        )

    def next(self):
        if len(self.data) < self.ema_length + 1:
            return

        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]

        ema_val = self.ema[-1]
        upper = self.upper_zone[-1]
        lower = self.lower_zone[-1]
        zone_sz = self.zone_size[-1]

        bull_candle = close > open_
        bear_candle = close < open_

        bull_no_wick = bull_candle and (open_ - low) <= self.wick_tolerance
        bear_no_wick = bear_candle and (high - open_) <= self.wick_tolerance

        above_zone = close > upper
        below_zone = close < lower

        bull_signal = bull_no_wick and above_zone
        bear_signal = bear_no_wick and below_zone

        if bull_signal:
            if not self.position:
                self.buy()
        elif bear_signal:
            if self.position:
                self.position.close()

        if self.position and close < ema_val:
            self.position.close()

        if not self.position and close > ema_val and not bull_signal:
            pass