"""
DS-TV Backtest Results: stochastic-rsi-super-trend-support-and-resistant-strategy
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         40.54%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         34.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.28%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — stochastic-rsi-super-trend-support-and-resistant-strategy
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    longTrailPerc = 0.015
    shortTrailPerc = 0.015
    atrPeriod = 5
    factor = 3.0
    smoothK = 3
    lengthRSI = 20
    lengthStoch = 11
    LB = 6
    HB = 99
    sup = 5
    res = 9
    S_R = True
    tradedir = 'Both'
    SZZ = 1000

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate RSI
        self.rsi = self.I(pta.rsi, close, length=self.lengthRSI)
        
        # Calculate Stochastic of RSI
        def stoch_rsi():
            rsi_vals = pta.rsi(close, length=self.lengthRSI)
            if rsi_vals is None:
                return pd.Series(50, index=close.index)
            stoch_vals = pta.stoch(rsi_vals, rsi_vals, rsi_vals, k=self.lengthStoch, d=3, smooth_k=1)
            if stoch_vals is None or stoch_vals.empty:
                return pd.Series(50, index=close.index)
            stoch_k = stoch_vals.iloc[:, 0] if stoch_vals.shape[1] > 0 else pd.Series(50, index=close.index)
            return stoch_k
        
        stoch_rsi_raw = self.I(stoch_rsi)
        
        # Smooth K with SMA
        self.k = self.I(lambda: pta.sma(stoch_rsi_raw, length=self.smoothK) or pd.Series(50, index=close.index))
        
        # Support and Resistance using rolling min/max
        def support_calc():
            return low.shift(1).rolling(window=self.sup).min()
        
        def resistance_calc():
            return high.shift(1).rolling(window=self.res).max()
        
        self.support = self.I(support_calc)
        self.resistance = self.I(resistance_calc)
        
        # Calculate SuperTrend manually
        def supertrend_calc():
            hl2 = (high + low) / 2
            atr = pta.atr(high, low, close, length=self.atrPeriod)
            if atr is None:
                atr = pd.Series(0, index=close.index)
            basic_ub = hl2 + self.factor * atr
            basic_lb = hl2 - self.factor * atr
            
            final_ub = pd.Series(index=close.index, dtype='float64')
            final_lb = pd.Series(index=close.index, dtype='float64')
            supertrend = pd.Series(index=close.index, dtype='float64')
            direction = pd.Series(index=close.index, dtype='float64')
            
            for i in range(len(close)):
                if i == 0:
                    final_ub.iloc[i] = basic_ub.iloc[i]
                    final_lb.iloc[i] = basic_lb.iloc[i]
                    direction.iloc[i] = 1
                    supertrend.iloc[i] = final_lb.iloc[i]
                else:
                    final_ub.iloc[i] = basic_ub.iloc[i] if basic_ub.iloc[i] < final_ub.iloc[i-1] or close.iloc[i-1] > final_ub.iloc[i-1] else final_ub.iloc[i-1]
                    final_lb.iloc[i] = basic_lb.iloc[i] if basic_lb.iloc[i] > final_lb.iloc[i-1] or close.iloc[i-1] < final_lb.iloc[i-1] else final_lb.iloc[i-1]
                    
                    if close.iloc[i] <= final_ub.iloc[i]:
                        direction.iloc[i] = 1
                        supertrend.iloc[i] = final_ub.iloc[i]
                    else:
                        direction.iloc[i] = -1
                        supertrend.iloc[i] = final_lb.iloc[i]
            
            return supertrend, direction
        
        self.supertrend_val, self.direction = self.I(supertrend_calc)
    
    def next(self):
        close_price = self.data.Close[-1]
        high_price = self.data.High[-1]
        low_price = self.data.Low[-1]
        
        if len(self.data) < max(self.lengthRSI, self.lengthStoch, self.sup, self.res, self.atrPeriod) + 10:
            return
        
        direction_val = self.direction[-1]
        k_val = self.k[-1]
        support_val = self.support[-1]
        resistance_val = self.resistance[-1]
        
        b = direction_val < 0
        s = direction_val > 0
        
        buy_signal = k_val < self.LB and b
        sell_signal = k_val > self.HB and s
        
        entrysup = low_price >= support_val if pd.notna(support_val) else False
        entryres = high_price <= resistance_val if pd.notna(resistance_val) else False
        
        if self.S_R:
            Buy = entrysup and buy_signal
            Sell = entryres and sell_signal
        else:
            Buy = buy_signal
            Sell = sell_signal
        
        if self.position:
            if self.position.is_long:
                longStopPrice = close_price * (1 - self.longTrailPerc)
                if self.position.open_price > 0:
                    longStopPrice = max(longStopPrice, self.position.open_price * (1 - self.longTrailPerc))
                
                if close_price <= longStopPrice:
                    self.position.close()
            
            elif self.position.is_short:
                shortStopPrice = close_price * (1 + self.shortTrailPerc)
                if self.position.open_price > 0:
                    shortStopPrice = min(shortStopPrice, self.position.open_price * (1 + self.shortTrailPerc))
                
                if close_price >= shortStopPrice:
                    self.position.close()
        
        else:
            if Buy and (self.tradedir == "Long" or self.tradedir == "Both"):
                self.buy()
            
            elif Sell and (self.tradedir == "Short" or self.tradedir == "Both"):
                self.sell()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()