"""
DS-TV Backtest Results: structured-trend-score-ema-entry-distance
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — structured-trend-score-ema-entry-distance
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len_fast = 20
    len_slow = 50
    ema_length = 100
    mult_tp = 1.7
    mult_entry = 0.7
    near_zone_pct = 2.0
    mid_zone_pct = 5.0
    hi_thresh = 62
    lo_thresh = 38

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        len_slow = max(2, self.len_slow)
        len_fast = max(1, min(self.len_fast, len_slow - 1))
        
        self.sma_fast = self.I(pta.sma, close, length=len_fast)
        self.sma_slow = self.I(pta.sma, close, length=len_slow)
        self.rsi14 = self.I(pta.rsi, close, length=14)
        self.atr14 = self.I(pta.atr, high, low, close, length=14)
        
        self.ema_base = self.I(pta.ema, close, length=self.ema_length)
        
        self.sma_20_trend = self.I(lambda: pta.sma(self._calc_trend_score(), length=20) or pd.Series(0, index=close.index))
        
        self.prev_crossover = False
        self.prev_crossunder = False
        self.prev_cross_up = False
        self.prev_cross_down = False

    def _calc_trend_score(self):
        close = pd.Series(self.data.Close)
        trend_scores = []
        
        for i in range(len(close)):
            if i < max(len(self.sma_fast.s), len(self.sma_slow.s), len(self.rsi14.s), len(self.atr14.s)):
                trend_scores.append(np.nan)
            else:
                fast_ma = self.sma_fast.s.iloc[i]
                slow_ma = self.sma_slow.s.iloc[i]
                rsi_val = self.rsi14.s.iloc[i]
                atr_val = self.atr14.s.iloc[i]
                price = close.iloc[i]
                
                if pd.isna(fast_ma) or pd.isna(slow_ma) or pd.isna(rsi_val) or pd.isna(atr_val):
                    trend_scores.append(np.nan)
                else:
                    ma_score = 40 if fast_ma > slow_ma else 10
                    rsi_score = np.clip(rsi_val, 0, 100) * 0.4
                    price_score = (10 if price > fast_ma else 0) + (10 if price > slow_ma else 0)
                    denom = max(price, 1e-10)
                    atr_score = np.clip((atr_val / denom) * 1000.0, 0, 10)
                    score = np.clip(ma_score + rsi_score + price_score + atr_score, 0, 100)
                    trend_scores.append(score)
        
        return pd.Series(trend_scores, index=close.index)

    def next(self):
        if len(self.data) < 50:
            return
        
        trend_score = self._get_trend_score_at(len(self.data) - 1)
        sma_20_trend = self._get_sma_20_trend_at(len(self.data) - 1)
        sma_fast_val = self.sma_fast[-1]
        sma_slow_val = self.sma_slow[-1]
        ema_base_val = self.ema_base[-1]
        close = self.data.Close[-1]
        
        if pd.isna(trend_score) or pd.isna(sma_20_trend):
            return
        
        ts_safe = trend_score if not np.isnan(trend_score) else 0.0
        sma_safe = sma_20_trend if not np.isnan(sma_20_trend) else 0.0
        
        entry_level_long = ema_base_val * self.mult_entry
        tp_level_long = ema_base_val * self.mult_tp
        
        denom_close = max(close, 1e-10)
        dist_pct_to_entry = 100.0 * abs(entry_level_long - close) / denom_close
        
        bull_cross = ts_safe > self.hi_thresh
        bear_cross = ts_safe < self.lo_thresh
        cross_up = ts_safe > sma_safe and self.prev_cross_up == False
        cross_down = ts_safe < sma_safe and self.prev_cross_down == False
        near_entry = dist_pct_to_entry <= self.near_zone_pct
        
        if bull_cross and not self.position:
            self.buy()
        elif bear_cross and self.position:
            self.sell()
        
        if cross_up and not self.position:
            self.buy()
        elif cross_down and self.position:
            self.sell()
        
        if near_entry and not self.position:
            self.buy()
        
        if self.position and close >= tp_level_long:
            self.sell()
        
        self.prev_cross_up = ts_safe > sma_safe
        self.prev_cross_down = ts_safe < sma_safe

    def _get_trend_score_at(self, idx):
        if idx < 0 or idx >= len(self.data):
            return np.nan
        
        fast_ma = self.sma_fast[idx] if idx < len(self.sma_fast.s) else np.nan
        slow_ma = self.sma_slow[idx] if idx < len(self.sma_slow.s) else np.nan
        rsi_val = self.rsi14[idx] if idx < len(self.rsi14.s) else np.nan
        atr_val = self.atr14[idx] if idx < len(self.atr14.s) else np.nan
        price = self.data.Close[idx]
        
        if pd.isna(fast_ma) or pd.isna(slow_ma) or pd.isna(rsi_val) or pd.isna(atr_val):
            return np.nan
        
        ma_score = 40 if fast_ma > slow_ma else 10
        rsi_score = np.clip(rsi_val, 0, 100) * 0.4
        price_score = (10 if price > fast_ma else 0) + (10 if price > slow_ma else 0)
        denom = max(price, 1e-10)
        atr_score = np.clip((atr_val / denom) * 1000.0, 0, 10)
        score = np.clip(ma_score + rsi_score + price_score + atr_score, 0, 100)
        
        return score

    def _get_sma_20_trend_at(self, idx):
        if idx < 0 or idx >= len(self.sma_20_trend.s):
            return np.nan
        return self.sma_20_trend.s.iloc[idx]


if __name__ == "__main__":
    bt = Backtest(
        pd.read_csv("data.csv", parse_dates=True, index_col=0),
        TvStrategy,
        cash=10000,
        commission=0.002,
        exclusive_orders=True
    )
    stats = bt.run()
    print(stats)
    bt.plot()