"""
DS-TV Backtest Results: super-trend-stochrsi-tolerance-3-tp
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         40.54%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         34.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.28%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — super-trend-stochrsi-tolerance-3-tp
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # SuperTrend parameters
    atr_period = 10
    multiplier = 3.0
    change_atr = True
    tolerance = 0.1
    
    # Stoch/RSI parameters
    smooth_k = 3
    length_rsi = 14
    length_stoch = 14
    lb = 5
    hb = 95
    
    # Take Profit parameters
    tp_level1 = 1.0
    tp_level2 = 2.0
    tp_level3 = 3.0
    tp_percent1 = 30.0
    tp_percent2 = 20.0
    tp_percent3 = 15.0
    
    # Trade sizing
    increase_trade = True
    trade_size_usd = 1000
    nl = 2.0
    
    trade_direction = "Both"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate True Range manually
        def calc_tr():
            tr1 = high - low
            tr2 = np.abs(high - close.shift(1))
            tr3 = np.abs(low - close.shift(1))
            return pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        
        tr = self.I(calc_tr)
        
        # Calculate ATR
        if self.change_atr:
            atr = self.I(pta.atr, high, low, close, length=self.atr_period)
        else:
            atr = self.I(pta.sma, tr, length=self.atr_period)
        
        # Calculate SuperTrend components
        hl2 = (high + low) / 2
        
        def calc_supertrend():
            result_up = pd.Series(index=close.index, dtype=float)
            result_dn = pd.Series(index=close.index, dtype=float)
            result_trend = pd.Series(index=close.index, dtype=float)
            
            up = hl2 - self.multiplier * atr
            dn = hl2 + self.multiplier * atr
            
            trend = 1
            
            for i in range(len(close)):
                if i == 0:
                    result_up.iloc[i] = up.iloc[i]
                    result_dn.iloc[i] = dn.iloc[i]
                    result_trend.iloc[i] = trend
                else:
                    up_val = up.iloc[i]
                    up1 = result_up.iloc[i-1]
                    if close.iloc[i-1] > up1:
                        up_val = max(up_val, up1)
                    
                    dn_val = dn.iloc[i]
                    dn1 = result_dn.iloc[i-1]
                    if close.iloc[i-1] < dn1:
                        dn_val = min(dn_val, dn1)
                    
                    result_up.iloc[i] = up_val
                    result_dn.iloc[i] = dn_val
                    
                    trend_val = result_trend.iloc[i-1]
                    if trend_val == -1 and close.iloc[i] > dn1:
                        trend_val = 1
                    elif trend_val == 1 and close.iloc[i] < up1:
                        trend_val = -1
                    
                    result_trend.iloc[i] = trend_val
            
            return result_up, result_dn, result_trend
        
        self.st_up, self.st_dn, self.trend = self.I(lambda: calc_supertrend())
        
        # Calculate Stoch/RSI
        rsi = self.I(pta.rsi, close, length=self.length_rsi)
        
        def calc_stoch_rsi():
            stoch = pta.stoch(rsi, rsi, rsi, k=self.length_stoch)
            if stoch is None:
                return pd.Series(50, index=close.index)
            k_line = stoch.iloc[:, 0]
            k_smooth = pta.sma(k_line, length=self.smooth_k)
            if k_smooth is None:
                return pd.Series(50, index=close.index)
            return k_smooth
        
        self.k_line = self.I(calc_stoch_rsi)
        
        self.last_position_size = 0
        self.losing_streak = 0
        self.win_count = 0
        self.loss_count = 0

    def next(self):
        current_close = self.data.Close[-1]
        current_trend = self.trend[-1]
        current_st_up = self.st_up[-1]
        current_st_dn = self.st_dn[-1]
        current_k = self.k_line[-1]
        
        # Calculate tolerance ranges
        buy_range = current_st_up * (1 + self.tolerance / 100)
        sell_range = current_st_dn * (1 - self.tolerance / 100)
        
        # Buy conditions
        buy_signal = (current_trend == 1 and current_k < self.lb and 
                     buy_range > current_close and 
                     self.trade_direction in ["Long", "Both"])
        
        # Sell conditions
        sell_signal = (current_trend == -1 and current_k > self.hb and 
                      sell_range < current_close and 
                      self.trade_direction in ["Short", "Both"])
        
        # Close positions based on trend reversal
        if self.position and self.position.is_long and current_trend == -1:
            self.position.close()
        
        if self.position and self.position.is_short and current_trend == 1:
            self.position.close()
        
        # Calculate position size
        base_qty = self.trade_size_usd / current_close
        qty = base_qty
        
        if self.increase_trade:
            qty = base_qty * 2
        
        # Enter long
        if buy_signal and not self.position:
            self.buy(size=qty)
        
        # Enter short
        if sell_signal and not self.position:
            self.sell(size=qty)
        
        # Take profit management for long positions
        if self.position and self.position.is_long:
            tp1 = self.position.open_price * (1 + self.tp_level1 / 100)
            tp2 = self.position.open_price * (1 + self.tp_level2 / 100)
            tp3 = self.position.open_price * (1 + self.tp_level3 / 100)
            
            if current_close >= tp3:
                self.position.close(portion=self.tp_percent3 / 100)
            elif current_close >= tp2:
                self.position.close(portion=self.tp_percent2 / 100)
            elif current_close >= tp1:
                self.position.close(portion=self.tp_percent1 / 100)
        
        # Take profit management for short positions
        if self.position and self.position.is_short:
            tp1 = self.position.open_price * (1 - self.tp_level1 / 100)
            tp2 = self.position.open_price * (1 - self.tp_level2 / 100)
            tp3 = self.position.open_price * (1 - self.tp_level3 / 100)
            
            if current_close <= tp3:
                self.position.close(portion=self.tp_percent3 / 100)
            elif current_close <= tp2:
                self.position.close(portion=self.tp_percent2 / 100)
            elif current_close <= tp1:
                self.position.close(portion=self.tp_percent1 / 100)


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=6000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()