"""
DS-TV Backtest Results: takashi-kotegawa-bnf-cis-ma-divergence
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         17.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         17.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — takashi-kotegawa-bnf-cis-ma-divergence
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # MA Settings
    i_ma25Len = 25
    i_ma75Len = 75
    i_ma200Len = 200
    
    # Divergence
    i_longDiv = 0.15
    i_shortDiv = 0.10
    
    # Exit
    i_exitMode = "ATR TP/SL"
    i_tp = 0.5
    i_sl = 0.25
    i_atrLen = 14
    i_atrTP = 2.0
    i_atrSL = 1.0
    
    # Filters
    i_rsiLen = 14
    i_rsiOS = 40
    i_rsiOB = 50
    i_useVol = False
    i_volLen = 20
    i_volMult = 1.5
    i_useCandle = True
    
    # Direction
    i_long = True
    i_short = False

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        open_ = pd.Series(self.data.Open)
        
        # Calculate indicators
        self.ma25 = self.I(pta.sma, close, length=self.i_ma25Len)
        self.ma75 = self.I(pta.sma, close, length=self.i_ma75Len)
        if self.i_ma200Len > 0:
            self.ma200 = self.I(pta.sma, close, length=self.i_ma200Len)
        else:
            self.ma200 = self.I(lambda: pd.Series(np.inf, index=close.index))
        
        self.rsi = self.I(pta.rsi, close, length=self.i_rsiLen)
        self.atr = self.I(pta.atr, high, low, close, length=self.i_atrLen)
        self.volAvg = self.I(pta.sma, volume, length=self.i_volLen)
        
        # Divergence measurement
        self.pctVsMA = self.I(lambda: (close - self.ma25) / self.ma25 * 100)
        
        # Candle patterns
        body = self.I(lambda: np.abs(close - open_))
        loShad = self.I(lambda: np.minimum(close, open_) - low)
        hiShad = self.I(lambda: high - np.maximum(close, open_))
        
        self.hammer = self.I(lambda: (body > 0) & (loShad >= 1.5 * body) & (hiShad <= body * 0.5))
        self.bullEng = self.I(lambda: (close > open_) & (close > high.shift(1)) & (open_ <= close.shift(1)))
        self.shootStar = self.I(lambda: (body > 0) & (hiShad >= 1.5 * body) & (loShad <= body * 0.5))
        self.bearEng = self.I(lambda: (close < open_) & (close < low.shift(1)) & (open_ >= close.shift(1)))
        
        # State tracking
        self.entry_price = None
        self.long_on = False
        self.short_on = False

    def next(self):
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        open_ = self.data.Open[-1]
        
        ma25 = self.ma25[-1]
        ma75 = self.ma75[-1]
        ma200 = self.ma200[-1]
        rsi = self.rsi[-1]
        atr = self.atr[-1]
        volAvg = self.volAvg[-1]
        pctVsMA = self.pctVsMA[-1]
        
        # Core divergence
        belowPct = -pctVsMA if pctVsMA < 0 else 0
        abovePct = pctVsMA if pctVsMA > 0 else 0
        
        # Trend
        trendUp = self.i_ma200Len == 0 or close > ma200
        trendDown = self.i_ma200Len == 0 or close < ma200
        
        # Volume
        volOk = not self.i_useVol or volume > volAvg * self.i_volMult
        
        # Candle filters
        body = abs(close - open_)
        loShad = min(close, open_) - low
        hiShad = high - max(close, open_)
        
        hammer = body > 0 and loShad >= 1.5 * body and hiShad <= body * 0.5
        bullEng = close > open_ and close > self.data.High[-2] and open_ <= self.data.Close[-2]
        shootStar = body > 0 and hiShad >= 1.5 * body and loShad <= body * 0.5
        bearEng = close < open_ and close < self.data.Low[-2] and open_ >= self.data.Close[-2]
        
        bullCdl = not self.i_useCandle or (hammer or bullEng)
        bearCdl = not self.i_useCandle or (shootStar or bearEng)
        
        # Entry conditions
        lDiv = belowPct >= self.i_longDiv
        lRsi = rsi <= self.i_rsiOS
        sDiv = abovePct >= self.i_shortDiv
        sRsi = rsi >= self.i_rsiOB
        
        noPos = not self.position
        isLong = self.position and self.position.size > 0
        
        goLong = (self.i_long and lDiv and lRsi and bullCdl and volOk and trendUp and noPos)
        goShort = (self.i_short and sDiv and sRsi and bearCdl and volOk and trendDown and noPos)
        
        # Entry logic
        if goLong:
            self.buy()
            self.long_on = True
            self.short_on = False
        
        if goShort:
            self.sell()
            self.short_on = True
            self.long_on = False
        
        # Capture entry price
        if self.position:
            if self.entry_price is None:
                self.entry_price = self.position.open_price
        else:
            self.entry_price = None
            self.long_on = False
            self.short_on = False
        
        # Exit logic
        if isLong and self.entry_price is not None:
            if self.i_exitMode == "ATR TP/SL":
                tp = self.entry_price + atr * self.i_atrTP if not np.isnan(atr) else None
                sl = self.entry_price - atr * self.i_atrSL if not np.isnan(atr) else self.entry_price * (1 - self.i_sl / 100)
            elif self.i_exitMode == "Fixed TP/SL":
                tp = self.entry_price * (1 + self.i_tp / 100)
                sl = self.entry_price * (1 - self.i_sl / 100)
            else:  # MA Cross
                tp = None
                sl = self.entry_price * (1 - self.i_sl / 100)
            
            # Check for MA cross for exit
            if self.i_exitMode == "MA Cross" and len(self.data) >= 2:
                if crossover(self.data.Close[-2:], self.ma25[-2:]):
                    self.position.close()
                elif sl is not None and close <= sl:
                    self.position.close()
            elif tp is not None or sl is not None:
                if tp is not None and close >= tp:
                    self.position.close()
                elif sl is not None and close <= sl:
                    self.position.close()
        
        elif self.position and self.position.size < 0 and self.entry_price is not None:
            if self.i_exitMode == "ATR TP/SL":
                tp = self.entry_price - atr * self.i_atrTP if not np.isnan(atr) else None
                sl = self.entry_price + atr * self.i_atrSL if not np.isnan(atr) else self.entry_price * (1 + self.i_sl / 100)
            elif self.i_exitMode == "Fixed TP/SL":
                tp = self.entry_price * (1 - self.i_tp / 100)
                sl = self.entry_price * (1 + self.i_sl / 100)
            else:  # MA Cross
                tp = None
                sl = self.entry_price * (1 + self.i_sl / 100)
            
            # Check for MA cross for exit
            if self.i_exitMode == "MA Cross" and len(self.data) >= 2:
                if crossover(self.ma25[-2:], self.data.Close[-2:]):
                    self.position.close()
                elif sl is not None and close >= sl:
                    self.position.close()
            elif tp is not None or sl is not None:
                if tp is not None and close <= tp:
                    self.position.close()
                elif sl is not None and close >= sl:
                    self.position.close()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.001, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()