"""
DS-TV Backtest Results: trend-indicatorbeyramazan
============================================================

--- SPY ---
  Return                    8.62%
  Buy & Hold Return         38.81%
  Max Drawdown              -14.58%
  Sharpe Ratio              0.42
  Sortino Ratio             0.59
  Calmar Ratio              0.29
  Profit Factor             1.46
  Expectancy                0.48%
  SQN                       0.45
  # Trades                  21
  Win Rate                  38.10%
  Best Trade                16.70%
  Worst Trade               -4.62%
  Avg Trade                 0.40%
  Exposure Time             73.40%
  Equity Final              108622.89$
  Equity Peak               117644.83$
  Avg Drawdown              -1.84%
  Max Drawdown Duration     257 days 00:00:00
  Max Trade Duration        102 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               4.26%
  Ann. Volatility           10.15%

--- BTC ---
  Return                    15.11%
  Buy & Hold Return         35.44%
  Max Drawdown              -25.16%
  Sharpe Ratio              0.28
  Sortino Ratio             0.46
  Calmar Ratio              0.29
  Profit Factor             1.37
  Expectancy                0.71%
  SQN                       0.41
  # Trades                  39
  Win Rate                  33.33%
  Best Trade                26.68%
  Worst Trade               -7.65%
  Avg Trade                 0.48%
  Exposure Time             56.09%
  Equity Final              115106.99$
  Equity Peak               134527.37$
  Avg Drawdown              -5.95%
  Max Drawdown Duration     233 days 00:00:00
  Max Trade Duration        49 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               7.28%
  Ann. Volatility           26.09%

--- QQQ ---
  Return                    -0.97%
  Buy & Hold Return         39.88%
  Max Drawdown              -23.64%
  Sharpe Ratio              -0.04
  Sortino Ratio             -0.05
  Calmar Ratio              -0.02
  Profit Factor             1.06
  Expectancy                0.08%
  SQN                       -0.04
  # Trades                  28
  Win Rate                  35.71%
  Best Trade                21.93%
  Worst Trade               -6.19%
  Avg Trade                 -0.04%
  Exposure Time             74.00%
  Equity Final              99026.99$
  Equity Peak               110616.30$
  Avg Drawdown              -6.10%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        103 days 00:00:00
  Avg Trade Duration        19 days 00:00:00
  Ann. Return               -0.49%
  Ann. Volatility           13.44%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trend-indicatorbeyramazan
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 14
    offset_val = 0.1

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ATR
        atr = self.I(pta.atr, high, low, close, length=self.length)
        
        # Calculate RWI High and RWI Low
        def calc_rwi_high():
            result = pd.Series(index=close.index, dtype=float)
            sqrt_len = np.sqrt(self.length)
            for i in range(len(close)):
                if i < self.length:
                    result.iloc[i] = np.nan
                else:
                    lowest_low = low.iloc[i - self.length:i].min()
                    atr_val = atr[i]
                    if atr_val and atr_val > 0:
                        result.iloc[i] = (high.iloc[i] - lowest_low) / (atr_val * sqrt_len)
                    else:
                        result.iloc[i] = np.nan
            return result
        
        def calc_rwi_low():
            result = pd.Series(index=close.index, dtype=float)
            sqrt_len = np.sqrt(self.length)
            for i in range(len(close)):
                if i < self.length:
                    result.iloc[i] = np.nan
                else:
                    highest_high = high.iloc[i - self.length:i].max()
                    atr_val = atr[i]
                    if atr_val and atr_val > 0:
                        result.iloc[i] = (highest_high - low.iloc[i]) / (atr_val * sqrt_len)
                    else:
                        result.iloc[i] = np.nan
            return result
        
        self.rwi_high = self.I(calc_rwi_high)
        self.rwi_low = self.I(calc_rwi_low)

    def next(self):
        if len(self.data) < self.length + 1:
            return
        
        # Check for crossover: rwi_high crosses above rwi_low
        if crossover(self.rwi_high, self.rwi_low):
            if not self.position:
                self.buy()
        
        # Check for crossunder: rwi_high crosses below rwi_low
        elif crossover(self.rwi_low, self.rwi_high):
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()