"""
DS-TV Backtest Results: trend-rsi-with-flip-signals-trix-direction-bands-rci
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "rma(rsi(20),10)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "rma(rsi(20),10)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "rma(rsi(20),10)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trend-rsi-with-flip-signals-trix-direction-bands-rci
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    rsiLen = 20
    maLen = 10
    maType = "RMA"
    atrLen = 14
    factor = 4.0
    baseMode = "RSI MA"
    trixLen = 9
    trixSlopeLen = 1
    flatTh = 0.0
    invertTrixBand = True
    lenRCI1 = 9
    lenRCI2 = 26
    mapToRSI = True
    rciSlopeLen = 1
    rciFlatTh = 0.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # RSI and MA
        self.rsi = self.I(pta.rsi, close, length=self.rsiLen)
        
        if self.maType == "SMA":
            self.rsiMA = self.I(pta.sma, self.rsi, length=self.maLen)
        elif self.maType == "EMA":
            self.rsiMA = self.I(pta.ema, self.rsi, length=self.maLen)
        elif self.maType == "RMA":
            self.rsiMA = self.I(pta.rma, self.rsi, length=self.maLen)
        else:  # WMA
            self.rsiMA = self.I(pta.wma, self.rsi, length=self.maLen)

        # Base for trend calculation
        def get_base():
            if self.baseMode == "RSI MA":
                return self.rsiMA
            else:
                return self.rsi

        # Trend RSI calculation with ATR
        def calc_trend_line():
            base_vals = self.rsiMA if self.baseMode == "RSI MA" else self.rsi
            
            def compute_trend():
                results = np.full(len(close), np.nan)
                fUpper = np.full(len(close), np.nan)
                fLower = np.full(len(close), np.nan)
                direction = np.full(len(close), 1, dtype=int)
                trend = np.full(len(close), np.nan)
                
                for i in range(1, len(close)):
                    if pd.isna(base_vals[i]):
                        continue
                    
                    # Calculate TR and ATR
                    if i < self.atrLen:
                        tr_list = [abs(base_vals[j] - (base_vals[j-1] if j > 0 else base_vals[j])) for j in range(max(0, i-self.atrLen+1), i+1)]
                        atr_rsi = np.mean(tr_list) if tr_list else 0
                    else:
                        tr_list = [abs(base_vals[j] - base_vals[j-1]) for j in range(i-self.atrLen+1, i+1)]
                        atr_rsi = np.mean(tr_list)
                    
                    upper = base_vals[i] + self.factor * atr_rsi
                    lower = base_vals[i] - self.factor * atr_rsi
                    
                    # Floating band logic
                    if i == 1 or np.isnan(fUpper[i-1]):
                        fUpper[i] = upper
                        fLower[i] = lower
                    else:
                        fUpper[i] = upper if (upper < fUpper[i-1] or base_vals[i-1] > fUpper[i-1]) else fUpper[i-1]
                        fLower[i] = lower if (lower > fLower[i-1] or base_vals[i-1] < fLower[i-1]) else fLower[i-1]
                    
                    # Direction logic
                    if i == 1:
                        direction[i] = 1
                    else:
                        if direction[i-1] == 1:
                            direction[i] = -1 if base_vals[i] < fLower[i-1] else 1
                        else:
                            direction[i] = 1 if base_vals[i] > fUpper[i-1] else -1
                    
                    trend[i] = fLower[i] if direction[i] == 1 else fUpper[i]
                
                return trend, direction
            
            return compute_trend()

        self.trend_line, self.direction = self.I(calc_trend_line)

        # Flip signals
        def calc_flips():
            flips_up = np.zeros(len(close), dtype=bool)
            flips_dn = np.zeros(len(close), dtype=bool)
            
            for i in range(1, len(close)):
                if self.direction[i] == 1 and self.direction[i-1] == -1:
                    flips_up[i] = True
                elif self.direction[i] == -1 and self.direction[i-1] == 1:
                    flips_dn[i] = True
            
            return flips_up, flips_dn

        self.flip_up, self.flip_dn = self.I(calc_flips)

        # TRIX calculation
        def calc_trix():
            ema1 = pta.ema(close, length=self.trixLen)
            ema2 = pta.ema(ema1, length=self.trixLen)
            ema3 = pta.ema(ema2, length=self.trixLen)
            
            trix_vals = np.full(len(close), np.nan)
            for i in range(1, len(ema3)):
                if not pd.isna(ema3[i]) and not pd.isna(ema3[i-1]) and ema3[i-1] != 0:
                    trix_vals[i] = 100.0 * (ema3[i] - ema3[i-1]) / abs(ema3[i-1])
            
            return trix_vals
        
        self.trix = self.I(calc_trix)

        # TRIX slope
        def calc_trix_slope():
            slope = np.full(len(close), np.nan)
            for i in range(self.trixSlopeLen, len(close)):
                if not pd.isna(self.trix[i]) and not pd.isna(self.trix[i-self.trixSlopeLen]):
                    slope[i] = self.trix[i] - self.trix[i-self.trixSlopeLen]
            return slope

        self.trix_slope = self.I(calc_trix_slope)

        # RCI calculation
        def calc_rci(src_series, length):
            rci_vals = np.full(len(src_series), np.nan)
            for i in range(length, len(src_series)):
                window = src_series[i-length+1:i+1]
                sum_d2 = 0.0
                for k in range(length):
                    rank_time = k + 1
                    rank_price = 1
                    for j in range(length):
                        if window[j] > window[k]:
                            rank_price += 1
                    d = rank_time - rank_price
                    sum_d2 += d * d
                
                n = float(length)
                rci_vals[i] = 100.0 * (1.0 - (6.0 * sum_d2) / (n * (n * n - 1.0)))
            
            return rci_vals

        self.rci1_raw = self.I(lambda: calc_rci(close, self.lenRCI1))
        self.rci2_raw = self.I(lambda: calc_rci(close, self.lenRCI2))

        # Map RCI to 0-100
        def map_rci():
            rci1 = (self.rci1_raw + 100.0) * 0.5 if self.mapToRSI else self.rci1_raw
            rci2 = (self.rci2_raw + 100.0) * 0.5 if self.mapToRSI else self.rci2_raw
            return rci1, rci2

        self.rci1, self.rci2 = self.I(map_rci)

    def next(self):
        if len(self) < 2:
            return

        # Buy on flip up
        if self.flip_up[-1]:
            if not self.position:
                self.buy()
        # Sell on flip down
        elif self.flip_dn[-1]:
            if self.position:
                self.position.close()
            else:
                # Can also sell short
                pass


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()