"""
DS-TV Backtest Results: trinity-signal-cythos
============================================================

--- SPY ---
  ERROR: expected ':' (trinity-signal-cythos.py, line 294)

--- BTC ---
  ERROR: expected ':' (trinity-signal-cythos.py, line 294)

--- QQQ ---
  ERROR: expected ':' (trinity-signal-cythos.py, line 294)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trinity-signal-cythos
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Regime Detection
    i_adxLen = 14
    i_adxThresh = 25
    i_useHysteresis = True
    i_adxEntryTh = 22
    i_adxExitTh = 16
    i_pctThresh = 35
    i_rsiLen = 14
    
    # RSI Divergence
    i_useDiv = True
    i_pivotLeft = 14
    i_pivotRight = 1
    i_minPriceDiff = 0.3
    i_minRsiDiff = 2.0
    
    # SuperTrend Filter
    i_useST = False
    i_stPeriod = 10
    i_stMult = 3.0
    
    # Volume Breakout
    i_useBo = True
    i_dcLen = 20
    i_volMult = 2.5
    i_boAdxMin = 25
    i_atrExpMult = 1.2
    
    # Mean Reversion
    i_useMr = True
    i_bbLen = 20
    i_bbMult = 2.0
    i_mrLowVolZ = 1.5
    i_mrHighVolZ = 2.5
    i_mrStopZ = 3.0
    i_mrVolMult = 0.8
    i_mrAtrPct = 65
    
    # TP/SL
    i_boTp = 5.0
    i_boSl = 4.0
    i_divTp = 3.5
    i_divSl = 2.5
    i_mrTp = 3.0
    i_mrSl = 7.0
    i_mrSlMaxPct = 2.0
    
    # Cooldown & Entry
    i_cooldown = 8
    i_mrCooldown = 25
    i_maxHoldBars = 200
    i_minTpPct = 0.5
    
    # Signal Quality
    i_useVbLongTrend = True
    i_useVbRsiFilter = True
    i_vbRsiHigh = 75
    i_vbRsiLow = 25
    i_useOiFilter = True
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Core indicators
        self.rsi = self.I(pta.rsi, close, length=self.i_rsiLen)
        
        adx_result = self.I(lambda: pta.adx(high, low, close, length=self.i_adxLen))
        self.adx = self.I(lambda: adx_result.iloc[:, 2] if adx_result is not None else pd.Series(25, index=close.index))
        self.di_plus = self.I(lambda: adx_result.iloc[:, 0] if adx_result is not None else pd.Series(20, index=close.index))
        self.di_minus = self.I(lambda: adx_result.iloc[:, 1] if adx_result is not None else pd.Series(20, index=close.index))
        
        self.atr = self.I(pta.atr, high, low, close, length=14)
        self.atr_pct = self.I(lambda: (self.atr[-1] / close.iloc[-1] * 100) if self.atr[-1] else 0)
        
        self.atr_sma50 = self.I(pta.sma, self.atr, length=50)
        
        self.atr_rank = self.I(lambda: pta.percentrank(self.atr, length=200))
        
        bb_result = self.I(lambda: pta.bbands(close, length=self.i_bbLen, std=self.i_bbMult))
        self.bb_basis = self.I(lambda: bb_result.iloc[:, 1] if bb_result is not None else pd.Series(close.mean(), index=close.index))
        self.bb_stdev = self.I(lambda: (close - self.bb_basis[-1]).rolling(self.i_bbLen).std())
        self.zscore = self.I(lambda: (close.iloc[-1] - self.bb_basis[-1]) / self.bb_stdev[-1] if self.bb_stdev[-1] > 0 else 0)
        
        bb20_width = self.I(lambda: (2 * close.rolling(20).std() / close.rolling(20).mean()) if close.rolling(20).mean().iloc[-1] > 0 else 0)
        self.bb_width_rank = self.I(lambda: pta.percentrank(bb20_width, length=200))
        
        self.ema20 = self.I(pta.ema, close, length=20)
        self.ema50 = self.I(pta.ema, close, length=50)
        
        self.vol_sma20 = self.I(pta.sma, volume, length=20)
        self.vol_ratio = self.I(lambda: volume.iloc[-1] / self.vol_sma20[-1] if self.vol_sma20[-1] > 0 else 1.0)
        
        self.dc_high = self.I(lambda: high.rolling(self.i_dcLen).max().shift(1))
        self.dc_low = self.I(lambda: low.rolling(self.i_dcLen).min().shift(1))
        
        # Tracking variables
        self.adx_trend_state = False
        self.prev_low_price = None
        self.prev_low_rsi = None
        self.prev_high_price = None
        self.prev_high_rsi = None
        
        self.last_bo_bull_bar = -9999
        self.last_bo_bear_bar = -9999
        self.last_div_bull_bar = -9999
        self.last_div_bear_bar = -9999
        self.last_mr_bull_bar = -9999
        self.last_mr_bear_bar = -9999
        
        self.vpos = 0
        self.ventry_px = 0.0
        self.ventry_atr = 0.0
        self.ventry_bar = -1
        self.vpos_type = 0
        self.vexit_bar = -1
        
        self.bars_since_entry = 0
    
    def next(self):
        if len(self.data) < max(self.i_pivotLeft + self.i_pivotRight + 5, 50):
            return
        
        bar_idx = len(self.data) - 1
        
        # Regime detection
        adx_vote = False
        if self.i_useHysteresis:
            if not self.adx_trend_state and self.adx[-1] > self.i_adxEntryTh:
                self.adx_trend_state = True
            elif self.adx_trend_state and self.adx[-1] < self.i_adxExitTh:
                self.adx_trend_state = False
            adx_vote = self.adx_trend_state
        else:
            adx_vote = self.adx[-1] > self.i_adxThresh
        
        bb_vote = self.bb_width_rank[-1] > self.i_pctThresh if not np.isnan(self.bb_width_rank[-1]) else False
        atr_vote = self.atr_rank[-1] > self.i_pctThresh if not np.isnan(self.atr_rank[-1]) else False
        
        all_trend = adx_vote and bb_vote and atr_vote
        
        regime = 1 if (all_trend and self.data.Close[-1] > self.ema50[-1]) else (2 if all_trend else 0)
        is_sideways = regime == 0
        is_trending = regime == 1 or regime == 2
        is_bull = regime == 1
        is_bear = regime == 2
        
        # Signal 1: RSI Divergence
        bull_div = False
        bear_div = False
        
        if self.i_useDiv and len(self.data) >= self.i_pivotLeft + self.i_pivotRight:
            reg_ok_bull = regime != 2
            reg_ok_bear = regime != 1
            st_ok_bull = True
            st_ok_bear = True
            
            price_lows = self.data.Low[-self.i_pivotLeft-self.i_pivotRight:]
            price_highs = self.data.High[-self.i_pivotLeft-self.i_pivotRight:]
            
            if len(price_lows) > self.i_pivotRight:
                min_idx = price_lows[:-self.i_pivotRight].argmin()
                if min_idx > 0 and min_idx < len(price_lows) - self.i_pivotRight:
                    cp = price_lows.iloc[-self.i_pivotRight]
                    cr = self.rsi[-self.i_pivotRight]
                    if self.prev_low_price is not None and reg_ok_bull and st_ok_bull:
                        pd_pct = (self.prev_low_price - cp) / self.prev_low_price * 100
                        rsi_diff = cr - self.prev_low_rsi
                        if pd_pct >= self.i_minPriceDiff and rsi_diff >= self.i_minRsiDiff:
                            bull_div = True
                    self.prev_low_price = cp
                    self.prev_low_rsi = cr
            
            if len(price_highs) > self.i_pivotRight:
                max_idx = price_highs[:-self.i_pivotRight].argmax()
                if max_idx > 0 and max_idx < len(price_highs) - self.i_pivotRight:
                    cp = price_highs.iloc[-self.i_pivotRight]
                    cr = self.rsi[-self.i_pivotRight]
                    if self.prev_high_price is not None and reg_ok_bear and st_ok_bear:
                        pd_pct = (cp - self.prev_high_price) / self.prev_high_price * 100
                        rsi_diff = self.prev_high_rsi - cr
                        if pd_pct >= self.i_minPriceDiff and rsi_diff >= self.i_minRsiDiff:
                            bear_div = True
                    self.prev_high_price = cp
                    self.prev_high_rsi = cr
        
        # Signal 2: Volume Breakout
        bo_long = False
        bo_short = False
        
        if self.i_useBo:
            vol_spike = self.data.Volume[-1] > self.vol_sma20[-1] * self.i_volMult
            adx_strong = self.adx[-1] > self.i_boAdxMin
            adx_rising = self.adx[-1] > self.adx[-6] and self.adx[-1] > 15
            atr_expand = self.atr[-1] > self.atr_sma50[-1] * self.i_atrExpMult
            
            st_ok_long = True
            st_ok_bear = True
            
            ema_trend = self.ema20[-1] > self.ema50[-1] if self.i_useVbLongTrend else True
            
            bo_long = (self.data.Close[-1] > self.dc_high[-1] and vol_spike and adx_strong and 
                      adx_rising and self.di_plus[-1] > self.di_minus[-1] and atr_expand and 
                      is_trending and st_ok_long and ema_trend)
            bo_short = (self.data.Close[-1] < self.dc_low[-1] and vol_spike and adx_strong and 
                       adx_rising and self.di_minus[-1] > self.di_plus[-1] and atr_expand and 
                       is_trending and st_ok_bear)
        
        # Signal 3: Mean Reversion
        mr_long = False
        mr_short = False
        
        if self.i_useMr:
            vol_ok = self.vol_ratio[-1] >= self.i_mrVolMult
            atr_ok = self.atr_rank[-1] <= self.i_mrAtrPct if not np.isnan(self.atr_rank[-1]) else False
            
            entry_z = self.i_mrLowVolZ if self.vol_ratio[-1] < 1.0 else self.i_mrHighVolZ
            z_long = self.zscore < -entry_z and self.zscore > -self.i_mrStopZ
            z_short = self.zscore > entry_z and self.zscore < self.i_mrStopZ
            
            mr_long = is_sideways and z_long and vol_ok and atr_ok
            mr_short = is_sideways and z_short and vol_ok and atr_ok
        
        # Signal merger + cooldown
        bull_type = 0
        bear_type = 0
        final_bull = False
        final_bear = False
        
        mr_long_ok = mr_long and (bar_idx - self.last_mr_bull_bar > self.i_mrCooldown)
        mr_short_ok = mr_short and (bar_idx - self.last_mr_bear_bar > self.i_mrCooldown)
        if mr_long_ok:
            final_bull = True
            bull_type = 3
            self.last_mr_bull_bar = bar_idx
        if mr_short_ok:
            final_bear = True
            bear_type = 3
            self.last_mr_bear_bar = bar_idx
        
        bo_long_ok = bo_long and (bar_idx - self.last_bo_bull_bar > self.i_cooldown)
        bo_short_ok = bo_short and (bar_idx - self.last_bo_bear_bar > self.i_cooldown)
        if bo_long_ok:
            final_bull = True
            bull_type = 1
            self.last_bo_bull_bar = bar_idx
        if bo_short_ok:
            final_bear = True
            bear_type = 1
            self.last_bo_bear_bar = bar_idx
        
        div_long_ok = bull_div and (bar_idx - self.last_div_bull_bar > self.i_cooldown)
        div_short_ok = bear_div and (bar_idx - self.last_div_bear_bar > self.i_cooldown)
        if div_long_ok:
            final_bull = True
            bull_type = 2
            self.last_div_bull_bar = bar_idx
        if div_short_ok:
            final_bear = True
            bear_type = 2
            self.last_div_bear_bar = bar_idx
        
        if final_bull and final_bear:
            if bull_type >= bear_type:
                final_bear = False
                bear_type = 0
            else:
                final_bull = False
                bull_type = 0
        
        # Exit detection
        entered_long = False
        entered_short = False
        exited_tp = False
        exited_sl = False
        
        if self.vpos != 0