"""
DS-TV Backtest Results: true-range-percentage-macd
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         43.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         44.64%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         44.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — true-range-percentage-macd
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Parameters from the Pine Script
    fast_len = 12
    slow_len = 26
    sig_len = 9
    tr_len = 14
    tr_gaps = True
    osc_type = "EMA"
    sig_type = "EMA"
    tr_type = "NONE"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate True Range
        def calc_tr():
            tr1 = high - low
            tr2 = np.abs(high - close.shift(1))
            tr3 = np.abs(low - close.shift(1))
            tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
            return tr
        
        tr = self.I(calc_tr)
        
        # Calculate TR% (True Range Percentage)
        def calc_trp(tr_series):
            hl2 = (high + low) / 2
            denom = np.maximum(np.abs(hl2.shift(1)), 1e-10)
            trp_raw = tr_series * 100.0 / denom
            return trp_raw
        
        trp_raw = self.I(calc_trp, tr)
        
        # Apply MA to TR%
        def apply_ma_to_trp(trp_series, length, ma_type):
            if ma_type == "NONE":
                return trp_series
            elif ma_type == "EMA":
                result = pta.ema(trp_series, length=length)
                return result if result is not None else trp_series
            elif ma_type == "SMA":
                result = pta.sma(trp_series, length=length)
                return result if result is not None else trp_series
            elif ma_type == "RMA":
                result = pta.rma(trp_series, length=length)
                return result if result is not None else trp_series
            elif ma_type == "VWMA":
                result = pta.vwma(trp_series, volume, length=length)
                return result if result is not None else trp_series
            elif ma_type == "WMA":
                result = pta.wma(trp_series, length=length)
                return result if result is not None else trp_series
            elif ma_type == "ALMA":
                result = pta.alma(trp_series, length=length, offset=0.85, sigma=6)
                return result if result is not None else trp_series
            elif ma_type == "SWMA":
                result = pta.swma(trp_series)
                return result if result is not None else trp_series
            elif ma_type == "HMA":
                result = pta.hma(trp_series, length=length)
                return result if result is not None else trp_series
            else:
                return trp_series
        
        atrp = self.I(apply_ma_to_trp, trp_raw, self.tr_len, self.tr_type)
        
        # Calculate fast and slow MA of atrp
        def apply_ma_osc(atrp_series, length, ma_type):
            if ma_type == "NONE":
                return atrp_series
            elif ma_type == "EMA":
                result = pta.ema(atrp_series, length=length)
                return result if result is not None else atrp_series
            elif ma_type == "SMA":
                result = pta.sma(atrp_series, length=length)
                return result if result is not None else atrp_series
            elif ma_type == "RMA":
                result = pta.rma(atrp_series, length=length)
                return result if result is not None else atrp_series
            elif ma_type == "VWMA":
                result = pta.vwma(atrp_series, volume, length=length)
                return result if result is not None else atrp_series
            elif ma_type == "WMA":
                result = pta.wma(atrp_series, length=length)
                return result if result is not None else atrp_series
            elif ma_type == "ALMA":
                result = pta.alma(atrp_series, length=length, offset=0.85, sigma=6)
                return result if result is not None else atrp_series
            elif ma_type == "SWMA":
                result = pta.swma(atrp_series)
                return result if result is not None else atrp_series
            elif ma_type == "HMA":
                result = pta.hma(atrp_series, length=length)
                return result if result is not None else atrp_series
            else:
                return atrp_series
        
        ma_fast = self.I(apply_ma_osc, atrp, self.fast_len, self.osc_type)
        ma_slow = self.I(apply_ma_osc, atrp, self.slow_len, self.osc_type)
        
        # Calculate MACD
        def calc_macd(fast, slow):
            return fast - slow
        
        self.macd = self.I(calc_macd, ma_fast, ma_slow)
        
        # Calculate Signal line
        def calc_signal(macd_series, length, sig_type):
            if sig_type == "NONE":
                return macd_series
            elif sig_type == "EMA":
                result = pta.ema(macd_series, length=length)
                return result if result is not None else macd_series
            elif sig_type == "SMA":
                result = pta.sma(macd_series, length=length)
                return result if result is not None else macd_series
            elif sig_type == "RMA":
                result = pta.rma(macd_series, length=length)
                return result if result is not None else macd_series
            elif sig_type == "VWMA":
                result = pta.vwma(macd_series, volume, length=length)
                return result if result is not None else macd_series
            elif sig_type == "WMA":
                result = pta.wma(macd_series, length=length)
                return result if result is not None else macd_series
            elif sig_type == "ALMA":
                result = pta.alma(macd_series, length=length, offset=0.85, sigma=6)
                return result if result is not None else macd_series
            elif sig_type == "SWMA":
                result = pta.swma(macd_series)
                return result if result is not None else macd_series
            elif sig_type == "HMA":
                result = pta.hma(macd_series, length=length)
                return result if result is not None else macd_series
            else:
                return macd_series
        
        self.signal = self.I(calc_signal, self.macd, self.sig_len, self.sig_type)
        
        # Calculate histogram
        def calc_hist(macd_series, signal_series):
            return macd_series - signal_series
        
        self.hist = self.I(calc_hist, self.macd, self.signal)

    def next(self):
        # Buy when MACD crosses above signal line
        if crossover(self.macd, self.signal):
            if not self.position:
                self.buy()
        
        # Sell when MACD crosses below signal line
        elif crossover(self.signal, self.macd):
            if self.position:
                self.position.close()
        
        # Alternative: Buy when histogram goes from negative to positive
        elif len(self.hist) > 1 and self.hist[-2] <= 0 and self.hist[-1] > 0:
            if not self.position:
                self.buy()
        
        # Sell when histogram goes from positive to negative
        elif len(self.hist) > 1 and self.hist[-2] >= 0 and self.hist[-1] < 0:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()