"""
DS-TV Backtest Results: ttp-universal-divergence-detector
============================================================

--- SPY ---
  Return                    14.36%
  Buy & Hold Return         41.94%
  Max Drawdown              -18.38%
  Sharpe Ratio              0.49
  Sortino Ratio             0.81
  Calmar Ratio              0.38
  Profit Factor             nan
  Expectancy                4.67%
  SQN                       1.72
  # Trades                  3
  Win Rate                  100.00%
  Best Trade                10.12%
  Worst Trade               1.38%
  Avg Trade                 4.60%
  Exposure Time             39.80%
  Equity Final              114358.29$
  Equity Peak               114429.34$
  Avg Drawdown              -1.72%
  Max Drawdown Duration     126 days 00:00:00
  Max Trade Duration        241 days 00:00:00
  Avg Trade Duration        96 days 00:00:00
  Ann. Return               7.00%
  Ann. Volatility           14.14%

--- BTC ---
  Return                    -27.74%
  Buy & Hold Return         46.22%
  Max Drawdown              -48.90%
  Sharpe Ratio              -0.57
  Sortino Ratio             -0.69
  Calmar Ratio              -0.31
  Profit Factor             1.11
  Expectancy                0.90%
  SQN                       -0.23
  # Trades                  5
  Win Rate                  20.00%
  Best Trade                45.64%
  Worst Trade               -20.61%
  Avg Trade                 -1.36%
  Exposure Time             45.55%
  Equity Final              72261.68$
  Equity Peak               127420.26$
  Avg Drawdown              -13.15%
  Max Drawdown Duration     429 days 00:00:00
  Max Trade Duration        209 days 00:00:00
  Avg Trade Duration        66 days 00:00:00
  Ann. Return               -14.97%
  Ann. Volatility           26.50%

--- QQQ ---
  Return                    18.05%
  Buy & Hold Return         42.67%
  Max Drawdown              -22.68%
  Sharpe Ratio              0.48
  Sortino Ratio             0.79
  Calmar Ratio              0.38
  Profit Factor             10.25
  Expectancy                9.27%
  SQN                       0.82
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                20.55%
  Worst Trade               -2.01%
  Avg Trade                 8.69%
  Exposure Time             51.40%
  Equity Final              118047.85$
  Equity Peak               120384.86$
  Avg Drawdown              -3.07%
  Max Drawdown Duration     308 days 00:00:00
  Max Trade Duration        356 days 00:00:00
  Avg Trade Duration        187 days 00:00:00
  Ann. Return               8.72%
  Ann. Volatility           18.10%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ttp-universal-divergence-detector
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Pivot Settings
    leftBars = 5
    rightBars = 5
    
    # Divergence Type Selection
    showRegularBull = True
    showRegularBear = True
    showHiddenBull = True
    showHiddenBear = True
    
    # Lookback Settings
    maxLookback = 60
    minLookback = 5

    def init(self):
        self.priceHighs = []
        self.priceHighBars = []
        self.indicatorHighs = []
        
        self.priceLows = []
        self.priceLowBars = []
        self.indicatorLows = []
        
        self.MAX_ARRAY_SIZE = 100
        
        self.last_signal_bar = -999
        
    def detect_pivot_high(self, idx):
        if idx < self.leftBars + self.rightBars:
            return False, 0.0, 0.0
        
        left_start = idx - self.leftBars
        right_end = idx + self.rightBars
        
        if right_end >= len(self.data.High):
            return False, 0.0, 0.0
        
        pivot_bar = idx
        pivot_high = self.data.High[pivot_bar]
        pivot_indicator = self.data.Close[pivot_bar]
        
        for i in range(left_start, pivot_bar):
            if self.data.High[i] >= pivot_high:
                return False, 0.0, 0.0
        
        for i in range(pivot_bar + 1, right_end + 1):
            if self.data.High[i] >= pivot_high:
                return False, 0.0, 0.0
        
        return True, pivot_high, pivot_indicator
    
    def detect_pivot_low(self, idx):
        if idx < self.leftBars + self.rightBars:
            return False, 0.0, 0.0
        
        left_start = idx - self.leftBars
        right_end = idx + self.rightBars
        
        if right_end >= len(self.data.Low):
            return False, 0.0, 0.0
        
        pivot_bar = idx
        pivot_low = self.data.Low[pivot_bar]
        pivot_indicator = self.data.Close[pivot_bar]
        
        for i in range(left_start, pivot_bar):
            if self.data.Low[i] <= pivot_low:
                return False, 0.0, 0.0
        
        for i in range(pivot_bar + 1, right_end + 1):
            if self.data.Low[i] <= pivot_low:
                return False, 0.0, 0.0
        
        return True, pivot_low, pivot_indicator
    
    def detect_regular_bullish(self):
        if len(self.priceLows) < 2:
            return False
        
        current_low_price = self.priceLows[0]
        current_low_bar = self.priceLowBars[0]
        current_low_ind = self.indicatorLows[0]
        
        for i in range(1, min(len(self.priceLows), self.maxLookback + 1)):
            prev_low_price = self.priceLows[i]
            prev_low_bar = self.priceLowBars[i]
            prev_low_ind = self.indicatorLows[i]
            
            bar_diff = current_low_bar - prev_low_bar
            
            if self.minLookback <= bar_diff <= self.maxLookback:
                if current_low_price < prev_low_price and current_low_ind > prev_low_ind:
                    return True
        
        return False
    
    def detect_regular_bearish(self):
        if len(self.priceHighs) < 2:
            return False
        
        current_high_price = self.priceHighs[0]
        current_high_bar = self.priceHighBars[0]
        current_high_ind = self.indicatorHighs[0]
        
        for i in range(1, min(len(self.priceHighs), self.maxLookback + 1)):
            prev_high_price = self.priceHighs[i]
            prev_high_bar = self.priceHighBars[i]
            prev_high_ind = self.indicatorHighs[i]
            
            bar_diff = current_high_bar - prev_high_bar
            
            if self.minLookback <= bar_diff <= self.maxLookback:
                if current_high_price > prev_high_price and current_high_ind < prev_high_ind:
                    return True
        
        return False
    
    def detect_hidden_bullish(self):
        if len(self.priceLows) < 2:
            return False
        
        current_low_price = self.priceLows[0]
        current_low_bar = self.priceLowBars[0]
        current_low_ind = self.indicatorLows[0]
        
        for i in range(1, min(len(self.priceLows), self.maxLookback + 1)):
            prev_low_price = self.priceLows[i]
            prev_low_bar = self.priceLowBars[i]
            prev_low_ind = self.indicatorLows[i]
            
            bar_diff = current_low_bar - prev_low_bar
            
            if self.minLookback <= bar_diff <= self.maxLookback:
                if current_low_price > prev_low_price and current_low_ind < prev_low_ind:
                    return True
        
        return False
    
    def detect_hidden_bearish(self):
        if len(self.priceHighs) < 2:
            return False
        
        current_high_price = self.priceHighs[0]
        current_high_bar = self.priceHighBars[0]
        current_high_ind = self.indicatorHighs[0]
        
        for i in range(1, min(len(self.priceHighs), self.maxLookback + 1)):
            prev_high_price = self.priceHighs[i]
            prev_high_bar = self.priceHighBars[i]
            prev_high_ind = self.indicatorHighs[i]
            
            bar_diff = current_high_bar - prev_high_bar
            
            if self.minLookback <= bar_diff <= self.maxLookback:
                if current_high_price < prev_high_price and current_high_ind > prev_high_ind:
                    return True
        
        return False

    def next(self):
        current_idx = len(self.data) - 1
        
        # Check for pivot high at the confirmed position (rightBars back)
        if current_idx >= self.rightBars:
            confirm_idx = current_idx - self.rightBars
            pivot_high_found, pivot_high_val, pivot_high_ind = self.detect_pivot_high(confirm_idx)
            
            if pivot_high_found:
                bar_idx = confirm_idx
                self.priceHighs.insert(0, pivot_high_val)
                self.priceHighBars.insert(0, bar_idx)
                self.indicatorHighs.insert(0, pivot_high_ind)
                
                if len(self.priceHighs) > self.MAX_ARRAY_SIZE:
                    self.priceHighs.pop()
                    self.priceHighBars.pop()
                    self.indicatorHighs.pop()
        
        # Check for pivot low at the confirmed position (rightBars back)
        if current_idx >= self.rightBars:
            confirm_idx = current_idx - self.rightBars
            pivot_low_found, pivot_low_val, pivot_low_ind = self.detect_pivot_low(confirm_idx)
            
            if pivot_low_found:
                bar_idx = confirm_idx
                self.priceLows.insert(0, pivot_low_val)
                self.priceLowBars.insert(0, bar_idx)
                self.indicatorLows.insert(0, pivot_low_ind)
                
                if len(self.priceLows) > self.MAX_ARRAY_SIZE:
                    self.priceLows.pop()
                    self.priceLowBars.pop()
                    self.indicatorLows.pop()
        
        # Detect divergences and generate signals
        signal_regular_bull = self.showRegularBull and self.detect_regular_bullish()
        signal_regular_bear = self.showRegularBear and self.detect_regular_bearish()
        signal_hidden_bull = self.showHiddenBull and self.detect_hidden_bullish()
        signal_hidden_bear = self.showHiddenBear and self.detect_hidden_bearish()
        
        # Enter on bullish signals
        if (signal_regular_bull or signal_hidden_bull) and self.last_signal_bar != current_idx:
            if not self.position:
                self.buy()
            self.last_signal_bar = current_idx
        
        # Exit on bearish signals
        if (signal_regular_bear or signal_hidden_bear) and self.last_signal_bar != current_idx:
            if self.position:
                self.position.close()
            self.last_signal_bar = current_idx


if __name__ == "__main__":
    import yfinance as yf
    
    # Download sample data
    data = yf.download("AAPL", start="2022-01-01", end="2023-12-31", progress=False)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    
    print(results)
    bt.plot()