"""
DS-TV Backtest Results: viprasol-sniper-confluence-entryexit
============================================================

--- SPY ---
  Return                    11.98%
  Buy & Hold Return         35.76%
  Max Drawdown              -17.30%
  Sharpe Ratio              0.57
  Sortino Ratio             0.85
  Calmar Ratio              0.34
  Profit Factor             1.68
  Expectancy                0.83%
  SQN                       0.50
  # Trades                  17
  Win Rate                  29.41%
  Best Trade                22.24%
  Worst Trade               -4.12%
  Avg Trade                 0.67%
  Exposure Time             65.40%
  Equity Final              111981.39$
  Equity Peak               116233.98$
  Avg Drawdown              -3.02%
  Max Drawdown Duration     409 days 00:00:00
  Max Trade Duration        146 days 00:00:00
  Avg Trade Duration        28 days 00:00:00
  Ann. Return               5.87%
  Ann. Volatility           10.30%

--- BTC ---
  Return                    -16.06%
  Buy & Hold Return         -2.17%
  Max Drawdown              -24.07%
  Sharpe Ratio              -0.55
  Sortino Ratio             -0.69
  Calmar Ratio              -0.35
  Profit Factor             0.25
  Expectancy                -1.65%
  SQN                       -1.63
  # Trades                  13
  Win Rate                  30.77%
  Best Trade                4.32%
  Worst Trade               -8.87%
  Avg Trade                 -1.71%
  Exposure Time             23.12%
  Equity Final              83942.24$
  Equity Peak               110551.88$
  Avg Drawdown              -5.88%
  Max Drawdown Duration     583 days 00:00:00
  Max Trade Duration        32 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               -8.37%
  Ann. Volatility           15.19%

--- QQQ ---
  Return                    24.94%
  Buy & Hold Return         39.41%
  Max Drawdown              -12.61%
  Sharpe Ratio              0.82
  Sortino Ratio             1.35
  Calmar Ratio              0.94
  Profit Factor             2.12
  Expectancy                1.63%
  SQN                       0.81
  # Trades                  18
  Win Rate                  38.89%
  Best Trade                26.78%
  Worst Trade               -4.71%
  Avg Trade                 1.39%
  Exposure Time             62.40%
  Equity Final              124937.73$
  Equity Peak               140319.37$
  Avg Drawdown              -2.17%
  Max Drawdown Duration     149 days 00:00:00
  Max Trade Duration        139 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               11.88%
  Ann. Volatility           14.49%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — viprasol-sniper-confluence-entryexit
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Signal Settings
    fast_ma_period = 9
    slow_ma_period = 21
    bar_close_confirm = True
    
    # Confluence Filter
    use_confluence_filter = True
    min_confluence_score = 4
    
    # Risk Management
    atr_sl_multiplier = 1.5
    atr_period = 14
    target_count = 5
    trail_sl_to_breakeven = True
    
    # Secondary Timeframe RSI (we'll use 14-period RSI on main timeframe for simplicity)
    secondary_rsi_period = 14
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Core indicators
        self.fast_ma = self.I(pta.ema, close, length=self.fast_ma_period)
        self.slow_ma = self.I(pta.ema, close, length=self.slow_ma_period)
        
        # VWAP calculation
        hlc3 = (high + pd.Series(self.data.High) + low + close) / 3
        vwap_result = self.I(lambda: pta.vwap(high, low, close, volume) or pd.Series(close.iloc[0], index=close.index))
        self.vwap = vwap_result
        
        # ATR for risk management
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_period)
        
        # RSI
        self.rsi = self.I(pta.rsi, close, length=14)
        
        # MACD
        macd_result = self.I(lambda: pta.macd(close, fast=12, slow=26, signal=9))
        self.macd_main = self.I(lambda: pta.macd(close, fast=12, slow=26, signal=9))
        
        # DMI/ADX
        adx_result = self.I(pta.adx, high, low, close, length=14)
        self.adx = adx_result
        
        # Volume average
        self.volume_avg = self.I(pta.sma, volume, length=20)
        
        # State tracking
        self.active_direction = 0  # 0: flat, 1: long, -1: short
        self.entry_price = 0.0
        self.stop_loss_price = 0.0
        self.target_prices = [0.0] * 5
        self.targets_reached = [False] * 5
        self.sl_moved_to_breakeven = False
        self.last_signal_index = -1

    def next(self):
        # Skip if not enough data
        if len(self.data) < max(self.slow_ma_period, self.atr_period) + 1:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        open_price = self.data.Open[-1]
        
        # Get indicator values
        fast_ma = self.fast_ma[-1] if len(self.fast_ma) > 0 else close
        slow_ma = self.slow_ma[-1] if len(self.slow_ma) > 0 else close
        vwap = self.vwap[-1] if len(self.vwap) > 0 else close
        atr = self.atr[-1] if len(self.atr) > 0 else 0
        rsi = self.rsi[-1] if len(self.rsi) > 0 else 50
        adx = self.adx[-1] if len(self.adx) > 0 else 20
        vol_avg = self.volume_avg[-1] if len(self.volume_avg) > 0 else volume
        
        # Get MACD values
        macd_data = self.macd_main[-1]
        if isinstance(macd_data, (pd.Series, dict)):
            if isinstance(macd_data, pd.Series):
                macd_main = macd_data.iloc[0] if len(macd_data) > 0 else 0
                macd_signal = macd_data.iloc[1] if len(macd_data) > 1 else 0
            else:
                macd_main = macd_data.get('MACD_12_26_9', 0)
                macd_signal = macd_data.get('MACDs_12_26_9', 0)
        else:
            macd_main = 0
            macd_signal = 0
        
        # Confluence scoring
        bullish_score = 0
        bullish_score += 1 if close > vwap else 0
        bullish_score += 1 if rsi > 50 else 0
        bullish_score += 1 if macd_main > macd_signal else 0
        bullish_score += 1 if fast_ma > slow_ma else 0
        bullish_score += 1 if adx > 25 and close > fast_ma else 0
        bullish_score += 1 if volume > vol_avg and close > open_price else 0
        bullish_score += 1 if rsi > 50 else 0  # Secondary RSI approximation
        
        bearish_score = 0
        bearish_score += 1 if close < vwap else 0
        bearish_score += 1 if rsi < 50 else 0
        bearish_score += 1 if macd_main < macd_signal else 0
        bearish_score += 1 if fast_ma < slow_ma else 0
        bearish_score += 1 if adx > 25 and close < fast_ma else 0
        bearish_score += 1 if volume > vol_avg and close < open_price else 0
        bearish_score += 1 if rsi < 50 else 0  # Secondary RSI approximation
        
        # Signal detection
        bullish_cross = crossover(self.fast_ma, self.slow_ma)
        bearish_cross = crossover(self.slow_ma, self.fast_ma)
        
        # Apply confluence filter
        confluence_bull_pass = bullish_score >= self.min_confluence_score if self.use_confluence_filter else True
        confluence_bear_pass = bearish_score >= self.min_confluence_score if self.use_confluence_filter else True
        
        # Entry signals
        entry_long_signal = bullish_cross and self.active_direction <= 0 and confluence_bull_pass
        entry_short_signal = bearish_cross and self.active_direction >= 0 and confluence_bear_pass
        
        # Process new entries
        if entry_long_signal:
            if self.position:
                self.position.close()
            self.active_direction = 1
            self.entry_price = close
            risk_amount = atr * self.atr_sl_multiplier if atr > 0 else close * 0.02
            self.stop_loss_price = self.entry_price - risk_amount
            for i in range(self.target_count):
                self.target_prices[i] = self.entry_price + (risk_amount * (i + 1))
            self.targets_reached = [False] * 5
            self.sl_moved_to_breakeven = False
            self.buy()
            
        elif entry_short_signal:
            if self.position:
                self.position.close()
            self.active_direction = -1
            self.entry_price = close
            risk_amount = atr * self.atr_sl_multiplier if atr > 0 else close * 0.02
            self.stop_loss_price = self.entry_price + risk_amount
            for i in range(self.target_count):
                self.target_prices[i] = self.entry_price - (risk_amount * (i + 1))
            self.targets_reached = [False] * 5
            self.sl_moved_to_breakeven = False
            self.sell()
        
        # Manage active position
        if self.active_direction == 1:  # Long position
            # Check target hits
            if high >= self.target_prices[0]:
                self.targets_reached[0] = True
            if high >= self.target_prices[1]:
                self.targets_reached[1] = True
            if high >= self.target_prices[2]:
                self.targets_reached[2] = True
            if high >= self.target_prices[3]:
                self.targets_reached[3] = True
            if high >= self.target_prices[4]:
                self.targets_reached[4] = True
            
            # Trail SL to breakeven at TP1
            if self.trail_sl_to_breakeven and self.targets_reached[0] and not self.sl_moved_to_breakeven:
                self.stop_loss_price = self.entry_price
                self.sl_moved_to_breakeven = True
            
            # Exit on stop loss
            if low <= self.stop_loss_price:
                self.position.close()
                self.active_direction = 0
            # Exit on last target
            elif self.target_count >= 5 and high >= self.target_prices[4]:
                self.position.close()
                self.active_direction = 0
                
        elif self.active_direction == -1:  # Short position
            # Check target hits
            if low <= self.target_prices[0]:
                self.targets_reached[0] = True
            if low <= self.target_prices[1]:
                self.targets_reached[1] = True
            if low <= self.target_prices[2]:
                self.targets_reached[2] = True
            if low <= self.target_prices[3]:
                self.targets_reached[3] = True
            if low <= self.target_prices[4]:
                self.targets_reached[4] = True
            
            # Trail SL to breakeven at TP1
            if self.trail_sl_to_breakeven and self.targets_reached[0] and not self.sl_moved_to_breakeven:
                self.stop_loss_price = self.entry_price
                self.sl_moved_to_breakeven = True
            
            # Exit on stop loss
            if high >= self.stop_loss_price:
                self.position.close()
                self.active_direction = 0
            # Exit on last target
            elif self.target_count >= 5 and low <= self.target_prices[4]:
                self.position.close()
                self.active_direction = 0


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()