"""
DS-TV Backtest Results: volume-shift-money-flow-vsmf
============================================================

--- SPY ---
  Return                    12.35%
  Buy & Hold Return         38.09%
  Max Drawdown              -9.12%
  Sharpe Ratio              0.69
  Sortino Ratio             1.04
  Calmar Ratio              0.66
  Profit Factor             1.82
  Expectancy                0.56%
  SQN                       0.78
  # Trades                  23
  Win Rate                  52.17%
  Best Trade                13.01%
  Worst Trade               -4.62%
  Avg Trade                 0.51%
  Exposure Time             58.60%
  Equity Final              112346.92$
  Equity Peak               120383.62$
  Avg Drawdown              -1.65%
  Max Drawdown Duration     300 days 00:00:00
  Max Trade Duration        43 days 00:00:00
  Avg Trade Duration        17 days 00:00:00
  Ann. Return               6.04%
  Ann. Volatility           8.77%

--- BTC ---
  Return                    18.68%
  Buy & Hold Return         10.58%
  Max Drawdown              -16.92%
  Sharpe Ratio              0.38
  Sortino Ratio             0.65
  Calmar Ratio              0.53
  Profit Factor             1.57
  Expectancy                0.90%
  SQN                       0.48
  # Trades                  38
  Win Rate                  39.47%
  Best Trade                38.91%
  Worst Trade               -6.69%
  Avg Trade                 0.63%
  Exposure Time             49.52%
  Equity Final              118681.77$
  Equity Peak               137963.32$
  Avg Drawdown              -5.00%
  Max Drawdown Duration     220 days 00:00:00
  Max Trade Duration        44 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               8.93%
  Ann. Volatility           23.36%

--- QQQ ---
  Return                    4.85%
  Buy & Hold Return         41.44%
  Max Drawdown              -12.91%
  Sharpe Ratio              0.20
  Sortino Ratio             0.28
  Calmar Ratio              0.19
  Profit Factor             1.22
  Expectancy                0.24%
  SQN                       0.22
  # Trades                  29
  Win Rate                  44.83%
  Best Trade                18.15%
  Worst Trade               -6.19%
  Avg Trade                 0.16%
  Exposure Time             57.80%
  Equity Final              104846.77$
  Equity Peak               117013.21$
  Avg Drawdown              -2.72%
  Max Drawdown Duration     210 days 00:00:00
  Max Trade Duration        40 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               2.41%
  Ann. Volatility           11.87%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volume-shift-money-flow-vsmf
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 14
    smooth = 10

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Typical Price
        tp = (high + low + close) / 3
        
        # Volume Shift Factor
        avgVol = self.I(pta.sma, volume, length=self.length)
        
        # VSMF calculation
        def calc_vsmf():
            avg_vol_series = pta.sma(volume, length=self.length)
            if avg_vol_series is None:
                return pd.Series(0, index=close.index)
            vol_shift = volume / avg_vol_series.replace(0, 1)
            tp_diff = tp.diff()
            vsmf = tp_diff * vol_shift
            return vsmf
        
        vsmf = self.I(calc_vsmf)
        
        # Smoothed Indicator
        def calc_vsmf_ma():
            vsmf_raw = calc_vsmf()
            vsmf_smooth = pta.sma(vsmf_raw, length=self.smooth)
            if vsmf_smooth is None:
                return pd.Series(0, index=close.index)
            return vsmf_smooth
        
        self.vsmf_ma = self.I(calc_vsmf_ma)

    def next(self):
        if len(self.data) < self.smooth + self.length + 1:
            return
        
        # Buy when VSMF crosses above zero line
        if crossover(self.vsmf_ma, 0):
            if not self.position:
                self.buy()
        
        # Sell when VSMF crosses below zero line
        elif crossover(0, self.vsmf_ma):
            if self.position:
                self.position.close()