"""
DS-TV Backtest Results: 10ema-strategy-indicator
============================================================

--- SPY ---
  Return                    -34.11%
  Buy & Hold Return         40.54%
  Max Drawdown              -37.47%
  Sharpe Ratio              -1.40
  Sortino Ratio             -1.56
  Calmar Ratio              -0.51
  Profit Factor             0.41
  Expectancy                -1.09%
  SQN                       -1.53
  # Trades                  31
  Win Rate                  54.84%
  Best Trade                5.79%
  Worst Trade               -12.52%
  Avg Trade                 -1.18%
  Exposure Time             86.40%
  Equity Final              65885.80$
  Equity Peak               105113.86$
  Avg Drawdown              -8.28%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        99 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               -18.97%
  Ann. Volatility           13.60%

--- BTC ---
  Return                    -34.32%
  Buy & Hold Return         34.90%
  Max Drawdown              -49.81%
  Sharpe Ratio              -0.79
  Sortino Ratio             -0.87
  Calmar Ratio              -0.38
  Profit Factor             0.52
  Expectancy                -1.96%
  SQN                       -0.84
  # Trades                  27
  Win Rate                  55.56%
  Best Trade                14.06%
  Worst Trade               -57.71%
  Avg Trade                 -3.13%
  Exposure Time             40.49%
  Equity Final              65681.29$
  Equity Peak               114347.36$
  Avg Drawdown              -11.40%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        76 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -18.93%
  Ann. Volatility           23.81%

--- QQQ ---
  Return                    -42.47%
  Buy & Hold Return         42.28%
  Max Drawdown              -47.23%
  Sharpe Ratio              -1.41
  Sortino Ratio             -1.49
  Calmar Ratio              -0.51
  Profit Factor             0.43
  Expectancy                -1.21%
  SQN                       -1.26
  # Trades                  38
  Win Rate                  50.00%
  Best Trade                5.92%
  Worst Trade               -30.29%
  Avg Trade                 -1.42%
  Exposure Time             97.80%
  Equity Final              57529.15$
  Equity Peak               105877.56$
  Avg Drawdown              -13.36%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        148 days 00:00:00
  Avg Trade Duration        19 days 00:00:00
  Ann. Return               -24.32%
  Ann. Volatility           17.28%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 10ema-strategy-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        self.ema10 = self.I(pta.ema, close, length=10)

    def next(self):
        # Bullish trend: price above 10 EMA
        bullish_trend = self.data.Close[-1] > self.ema10[-1]
        # Bearish bar: close < open
        bearish_bar = self.data.Close[-1] < self.data.Open[-1]
        # Bar above EMA: low > EMA
        bar_above_ema = self.data.Low[-1] > self.ema10[-1]
        
        # Bearish setup: bearish bar above 10EMA in bullish trend
        bearish_setup = bullish_trend and bearish_bar and bar_above_ema
        
        # Bearish trend: price below 10 EMA
        bearish_trend = self.data.Close[-1] < self.ema10[-1]
        # Bullish bar: close > open
        bullish_bar = self.data.Close[-1] > self.data.Open[-1]
        # Bar below EMA: high < EMA
        bar_below_ema = self.data.High[-1] < self.ema10[-1]
        
        # Bullish setup: bullish bar below 10EMA in bearish trend
        bullish_setup = bearish_trend and bullish_bar and bar_below_ema
        
        # Trading logic
        if bearish_setup and not self.position:
            self.buy()
        elif bullish_setup and self.position:
            self.sell()
        elif bullish_setup and not self.position:
            self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()