"""
DS-TV Backtest Results: 15-sma-trend-friend-mtf
============================================================

--- SPY ---
  Return                    5.86%
  Buy & Hold Return         38.81%
  Max Drawdown              -13.12%
  Sharpe Ratio              0.32
  Sortino Ratio             0.44
  Calmar Ratio              0.22
  Profit Factor             1.26
  Expectancy                0.19%
  SQN                       0.37
  # Trades                  32
  Win Rate                  56.25%
  Best Trade                8.99%
  Worst Trade               -4.62%
  Avg Trade                 0.16%
  Exposure Time             70.40%
  Equity Final              105864.03$
  Equity Peak               113440.00$
  Avg Drawdown              -2.15%
  Max Drawdown Duration     231 days 00:00:00
  Max Trade Duration        46 days 00:00:00
  Avg Trade Duration        15 days 00:00:00
  Ann. Return               2.91%
  Ann. Volatility           9.18%

--- BTC ---
  Return                    9.56%
  Buy & Hold Return         35.44%
  Max Drawdown              -20.20%
  Sharpe Ratio              0.18
  Sortino Ratio             0.29
  Calmar Ratio              0.23
  Profit Factor             1.27
  Expectancy                0.49%
  SQN                       0.24
  # Trades                  46
  Win Rate                  26.09%
  Best Trade                32.38%
  Worst Trade               -8.88%
  Avg Trade                 0.26%
  Exposure Time             54.72%
  Equity Final              109560.55$
  Equity Peak               132741.06$
  Avg Drawdown              -8.03%
  Max Drawdown Duration     221 days 00:00:00
  Max Trade Duration        48 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               4.66%
  Ann. Volatility           25.69%

--- QQQ ---
  Return                    0.22%
  Buy & Hold Return         39.88%
  Max Drawdown              -17.70%
  Sharpe Ratio              0.01
  Sortino Ratio             0.01
  Calmar Ratio              0.01
  Profit Factor             1.05
  Expectancy                0.06%
  SQN                       0.01
  # Trades                  42
  Win Rate                  45.24%
  Best Trade                15.32%
  Worst Trade               -6.19%
  Avg Trade                 0.00%
  Exposure Time             73.00%
  Equity Final              100216.97$
  Equity Peak               108030.58$
  Avg Drawdown              -5.93%
  Max Drawdown Duration     334 days 00:00:00
  Max Trade Duration        60 days 00:00:00
  Avg Trade Duration        12 days 00:00:00
  Ann. Return               0.11%
  Ann. Volatility           12.89%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 15-sma-trend-friend-mtf
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    smaLen = 15

    def init(self):
        close = pd.Series(self.data.Close)
        self.sma = self.I(pta.sma, close, length=self.smaLen)

    def next(self):
        if len(self.data) < self.smaLen:
            return

        close_current = self.data.Close[-1]
        sma_current = self.sma[-1]

        if sma_current is None or np.isnan(sma_current):
            return

        if close_current > sma_current and (len(self.data) < 2 or self.data.Close[-2] <= self.sma[-2]):
            if not self.position:
                self.buy()
        elif close_current < sma_current and (len(self.data) < 2 or self.data.Close[-2] >= self.sma[-2]):
            if self.position:
                self.position.close()


if __name__ == "__main__":
    bt = Backtest(
        pd.read_csv("data.csv", index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.002
    )

    stats = bt.run()
    print(stats)
    bt.plot()