"""
DS-TV Backtest Results: 250300350-weekly-sma
============================================================

--- SPY ---
  Return                    11.93%
  Buy & Hold Return         12.45%
  Max Drawdown              -5.06%
  Sharpe Ratio              0.91
  Sortino Ratio             1.39
  Calmar Ratio              1.15
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              111932.08$
  Equity Peak               112180.02$
  Avg Drawdown              -1.30%
  Max Drawdown Duration     42 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               5.85%
  Ann. Volatility           6.41%

--- BTC ---
  Return                    -47.07%
  Buy & Hold Return         -33.36%
  Max Drawdown              -71.18%
  Sharpe Ratio              -0.69
  Sortino Ratio             -0.80
  Calmar Ratio              -0.38
  Profit Factor             0.00
  Expectancy                -27.75%
  SQN                       -12.06
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -22.09%
  Worst Trade               -33.41%
  Avg Trade                 -27.97%
  Exposure Time             37.76%
  Equity Final              52934.98$
  Equity Peak               103626.64$
  Avg Drawdown              -71.18%
  Max Drawdown Duration     372 days 00:00:00
  Max Trade Duration        210 days 00:00:00
  Avg Trade Duration        138 days 00:00:00
  Ann. Return               -27.21%
  Ann. Volatility           39.17%

--- QQQ ---
  Return                    10.92%
  Buy & Hold Return         11.56%
  Max Drawdown              -7.86%
  Sharpe Ratio              0.62
  Sortino Ratio             0.90
  Calmar Ratio              0.68
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              110915.49$
  Equity Peak               114629.24$
  Avg Drawdown              -1.68%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               5.36%
  Ann. Volatility           8.69%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 250300350-weekly-sma
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len200 = 200
    len250 = 250
    len300 = 300
    len350 = 350

    def init(self):
        close = pd.Series(self.data.Close)
        
        self.sma200 = self.I(pta.sma, close, length=self.len200)
        self.sma250 = self.I(pta.sma, close, length=self.len250)
        self.sma300 = self.I(pta.sma, close, length=self.len300)
        self.sma350 = self.I(pta.sma, close, length=self.len350)

    def next(self):
        if len(self.data) < self.len350 + 1:
            return
        
        current_price = self.data.Close[-1]
        
        sma200_val = self.sma200[-1]
        sma250_val = self.sma250[-1]
        sma300_val = self.sma300[-1]
        sma350_val = self.sma350[-1]
        
        if (sma200_val is None or sma250_val is None or 
            sma300_val is None or sma350_val is None):
            return
        
        all_smas = [sma200_val, sma250_val, sma300_val, sma350_val]
        
        if not self.position:
            if current_price > max(all_smas):
                self.buy()
            elif current_price < min(all_smas):
                pass
        else:
            if current_price < min(all_smas):
                self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()