"""
DS-TV Backtest Results: amanda-strat
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         17.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         17.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — amanda-strat
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len9 = 9
    len21 = 21
    len200 = 200
    pivotLen = 10
    require200 = True
    requireGP = True
    oneSignalPerBOS = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema9 = self.I(pta.ema, close, length=self.len9)
        self.ema21 = self.I(pta.ema, close, length=self.len21)
        self.ema200 = self.I(pta.ema, close, length=self.len200)
        
        self.pivot_highs = self.I(self._get_pivot_highs, high, self.pivotLen)
        self.pivot_lows = self.I(self._get_pivot_lows, low, self.pivotLen)
        
        self.lastMajHigh = np.nan
        self.lastMajLow = np.nan
        self.lastMajHighBar = -1
        self.lastMajLowBar = -1
        self.majHighActive = False
        self.majLowActive = False
        self.fibBull = np.nan
        self.fibA = np.nan
        self.fibB = np.nan
        self.entryFired = False
        self.last_bos_bar = -1

    def _get_pivot_highs(self, high_series, period):
        result = pd.Series(np.nan, index=high_series.index)
        for i in range(period, len(high_series) - period):
            if high_series.iloc[i] == high_series.iloc[i-period:i+period+1].max():
                result.iloc[i] = high_series.iloc[i]
        return result

    def _get_pivot_lows(self, low_series, period):
        result = pd.Series(np.nan, index=low_series.index)
        for i in range(period, len(low_series) - period):
            if low_series.iloc[i] == low_series.iloc[i-period:i+period+1].min():
                result.iloc[i] = low_series.iloc[i]
        return result

    def next(self):
        current_idx = len(self.data) - 1
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        if not np.isnan(self.pivot_highs[-1]):
            self.lastMajHigh = self.pivot_highs[-1]
            self.lastMajHighBar = current_idx - self.pivotLen
            self.majHighActive = True
        
        if not np.isnan(self.pivot_lows[-1]):
            self.lastMajLow = self.pivot_lows[-1]
            self.lastMajLowBar = current_idx - self.pivotLen
            self.majLowActive = True
        
        bullBOS = (self.majHighActive and not np.isnan(self.lastMajHigh) and 
                   crossover(self.data.Close, np.full(len(self.data), self.lastMajHigh)))
        bearBOS = (self.majLowActive and not np.isnan(self.lastMajLow) and 
                   crossover(np.full(len(self.data), self.lastMajLow), self.data.Close))
        
        if bullBOS and current_idx > self.last_bos_bar:
            self.majHighActive = False
            self.fibBull = True
            self.fibA = self.lastMajLow
            self.fibB = high
            self.entryFired = False
            self.last_bos_bar = current_idx
        
        if bearBOS and current_idx > self.last_bos_bar:
            self.majLowActive = False
            self.fibBull = False
            self.fibA = self.lastMajHigh
            self.fibB = low
            self.entryFired = False
            self.last_bos_bar = current_idx
        
        hasFib = not np.isnan(self.fibA) and not np.isnan(self.fibB) and self.fibA != self.fibB
        
        if hasFib:
            fibRange = abs(self.fibB - self.fibA)
            if self.fibBull:
                lvl618 = self.fibB - fibRange * 0.618
                lvl705 = self.fibB - fibRange * 0.705
            else:
                lvl618 = self.fibB + fibRange * 0.618
                lvl705 = self.fibB + fibRange * 0.705
            
            gpTop = max(lvl618, lvl705)
            gpBot = min(lvl618, lvl705)
            inGP = close <= gpTop and close >= gpBot
        else:
            inGP = False
        
        bullBias = close > self.ema200[-1]
        bearBias = close < self.ema200[-1]
        
        bullCross = crossover(self.ema9, self.ema21)
        bearCross = crossover(self.ema21, self.ema9)
        
        bullEntry = (hasFib and self.fibBull and bullCross and 
                     (not self.require200 or bullBias) and 
                     (not self.requireGP or inGP))
        bearEntry = (hasFib and not self.fibBull and bearCross and 
                     (not self.require200 or bearBias) and 
                     (not self.requireGP or inGP))
        
        finalBull = bullEntry and (not self.oneSignalPerBOS or not self.entryFired)
        finalBear = bearEntry and (not self.oneSignalPerBOS or not self.entryFired)
        
        if finalBull:
            if not self.position:
                self.buy()
            self.entryFired = True
        
        if finalBear:
            if self.position:
                self.position.close()
            self.entryFired = True