"""
DS-TV Backtest Results: asset-executive-orb-4am-breakout
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         17.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         17.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — asset-executive-orb-4am-breakout
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    emaFastLen = 50
    emaSlowLen = 200
    volAvgLen = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.ema50 = self.I(pta.ema, close, length=self.emaFastLen)
        self.ema200 = self.I(pta.ema, close, length=self.emaSlowLen)
        self.volAvg = self.I(pta.sma, volume, length=self.volAvgLen)
        
        self.signal_fired_today = False
        self.last_day = None

    def next(self):
        if len(self.data) < max(self.emaFastLen, self.emaSlowLen, self.volAvgLen):
            return
        
        # Reset signal flag on new day
        current_date = pd.Timestamp(self.data.index[-1]).date()
        if self.last_day is None or current_date != self.last_day:
            self.signal_fired_today = False
            self.last_day = current_date
        
        # Get current values
        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        current_time = pd.Timestamp(self.data.index[-1])
        hour = current_time.hour
        minute = current_time.minute
        
        # Update 4AM levels at 4:00
        if not hasattr(self, 'high4am'):
            self.high4am = None
            self.low4am = None
        
        if hour == 4 and minute == 0:
            self.high4am = high
            self.low4am = low
        
        # Volume bias logic
        vol_avg_val = self.volAvg[-1] if self.volAvg[-1] is not None else volume
        is_buying_vol = close > open_ and volume > vol_avg_val
        is_selling_vol = close < open_ and volume > vol_avg_val
        
        # EMA values
        ema50_val = self.ema50[-1]
        ema200_val = self.ema200[-1]
        
        if ema50_val is None or ema200_val is None:
            return
        
        # Trade window: 09:45 to 11:00
        is_trade_window = (hour == 9 and minute >= 45) or (hour == 10)
        
        # Signals
        buy_signal = (
            not self.signal_fired_today and
            is_trade_window and
            self.high4am is not None and
            close > self.high4am and
            close > ema50_val and
            close > ema200_val and
            is_buying_vol
        )
        
        sell_signal = (
            not self.signal_fired_today and
            is_trade_window and
            self.low4am is not None and
            close < self.low4am and
            close < ema50_val and
            close < ema200_val and
            is_selling_vol
        )
        
        if buy_signal:
            self.signal_fired_today = True
            if not self.position:
                self.buy()
        
        if sell_signal:
            self.signal_fired_today = True
            if self.position:
                self.position.close()
            else:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()