"""
DS-TV Backtest Results: buying-vs-selling-moving-averages-scalp-meter
============================================================

--- SPY ---
  Return                    2.45%
  Buy & Hold Return         38.66%
  Max Drawdown              -19.42%
  Sharpe Ratio              0.11
  Sortino Ratio             0.15
  Calmar Ratio              0.06
  Profit Factor             1.12
  Expectancy                0.11%
  SQN                       0.15
  # Trades                  37
  Win Rate                  32.43%
  Best Trade                9.26%
  Worst Trade               -6.25%
  Avg Trade                 0.07%
  Exposure Time             76.40%
  Equity Final              102453.11$
  Equity Peak               115758.23$
  Avg Drawdown              -2.23%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        72 days 00:00:00
  Avg Trade Duration        14 days 00:00:00
  Ann. Return               1.23%
  Ann. Volatility           10.72%

--- BTC ---
  Return                    -26.63%
  Buy & Hold Return         37.68%
  Max Drawdown              -40.19%
  Sharpe Ratio              -0.65
  Sortino Ratio             -0.81
  Calmar Ratio              -0.36
  Profit Factor             0.79
  Expectancy                -0.64%
  SQN                       -0.65
  # Trades                  36
  Win Rate                  25.00%
  Best Trade                51.26%
  Worst Trade               -11.58%
  Avg Trade                 -1.02%
  Exposure Time             39.81%
  Equity Final              73371.93$
  Equity Peak               122683.55$
  Avg Drawdown              -8.21%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        65 days 00:00:00
  Avg Trade Duration        8 days 00:00:00
  Ann. Return               -14.32%
  Ann. Volatility           22.04%

--- QQQ ---
  Return                    6.19%
  Buy & Hold Return         39.38%
  Max Drawdown              -23.07%
  Sharpe Ratio              0.21
  Sortino Ratio             0.29
  Calmar Ratio              0.13
  Profit Factor             1.19
  Expectancy                0.26%
  SQN                       0.26
  # Trades                  35
  Win Rate                  28.57%
  Best Trade                13.77%
  Worst Trade               -6.43%
  Avg Trade                 0.17%
  Exposure Time             75.60%
  Equity Final              106186.70$
  Equity Peak               118445.48$
  Avg Drawdown              -3.91%
  Max Drawdown Duration     277 days 00:00:00
  Max Trade Duration        70 days 00:00:00
  Avg Trade Duration        15 days 00:00:00
  Ann. Return               3.07%
  Ann. Volatility           14.69%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — buying-vs-selling-moving-averages-scalp-meter
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    maType = "EMA"
    buyLength = 14
    sellLength = 14

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        # Calculate volume delta components
        def calc_buy_vol():
            candle_range = high - low
            buy_ratio = np.where(
                candle_range > 0,
                (close - low) / candle_range,
                0.5
            )
            return volume * buy_ratio

        def calc_sell_vol():
            candle_range = high - low
            sell_ratio = np.where(
                candle_range > 0,
                (high - close) / candle_range,
                0.5
            )
            return volume * sell_ratio

        buy_vol_series = pd.Series(calc_buy_vol(), index=close.index)
        sell_vol_series = pd.Series(calc_sell_vol(), index=close.index)

        # Calculate MAs based on maType
        if self.maType == "EMA":
            self.buyMA = self.I(pta.ema, buy_vol_series, length=self.buyLength)
            self.sellMA = self.I(pta.ema, sell_vol_series, length=self.sellLength)
        elif self.maType == "SMA":
            self.buyMA = self.I(pta.sma, buy_vol_series, length=self.buyLength)
            self.sellMA = self.I(pta.sma, sell_vol_series, length=self.sellLength)
        elif self.maType == "WMA":
            self.buyMA = self.I(pta.wma, buy_vol_series, length=self.buyLength)
            self.sellMA = self.I(pta.wma, sell_vol_series, length=self.sellLength)
        elif self.maType == "VWMA":
            self.buyMA = self.I(pta.vwma, buy_vol_series, volume, length=self.buyLength)
            self.sellMA = self.I(pta.vwma, sell_vol_series, volume, length=self.sellLength)
        elif self.maType == "HMA":
            self.buyMA = self.I(pta.hma, buy_vol_series, length=self.buyLength)
            self.sellMA = self.I(pta.hma, sell_vol_series, length=self.sellLength)
        else:
            self.buyMA = self.I(pta.ema, buy_vol_series, length=self.buyLength)
            self.sellMA = self.I(pta.ema, sell_vol_series, length=self.sellLength)

    def next(self):
        # Buy when buying volume MA crosses above selling volume MA
        if crossover(self.buyMA, self.sellMA):
            if not self.position:
                self.buy()
        # Sell when buying volume MA crosses below selling volume MA
        elif crossover(self.sellMA, self.buyMA):
            if self.position:
                self.position.close()