"""
DS-TV Backtest Results: configurable-ema-stack-strategy
============================================================

--- SPY ---
  Return                    4.54%
  Buy & Hold Return         17.90%
  Max Drawdown              -6.73%
  Sharpe Ratio              0.32
  Sortino Ratio             0.43
  Calmar Ratio              0.34
  Profit Factor             1.75
  Expectancy                0.75%
  SQN                       0.35
  # Trades                  7
  Win Rate                  14.29%
  Best Trade                12.21%
  Worst Trade               -1.81%
  Avg Trade                 0.64%
  Exposure Time             41.40%
  Equity Final              104538.05$
  Equity Peak               111566.89$
  Avg Drawdown              -1.32%
  Max Drawdown Duration     209 days 00:00:00
  Max Trade Duration        168 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               2.26%
  Ann. Volatility           7.05%

--- BTC ---
  Return                    30.98%
  Buy & Hold Return         17.39%
  Max Drawdown              -15.66%
  Sharpe Ratio              0.66
  Sortino Ratio             1.27
  Calmar Ratio              0.92
  Profit Factor             1.94
  Expectancy                1.91%
  SQN                       0.49
  # Trades                  10
  Win Rate                  40.00%
  Best Trade                28.30%
  Worst Trade               -6.04%
  Avg Trade                 1.51%
  Exposure Time             27.77%
  Equity Final              130983.95$
  Equity Peak               138131.91$
  Avg Drawdown              -4.01%
  Max Drawdown Duration     415 days 00:00:00
  Max Trade Duration        45 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               14.43%
  Ann. Volatility           21.95%

--- QQQ ---
  Return                    4.77%
  Buy & Hold Return         22.08%
  Max Drawdown              -11.85%
  Sharpe Ratio              0.24
  Sortino Ratio             0.33
  Calmar Ratio              0.20
  Profit Factor             1.60
  Expectancy                0.81%
  SQN                       0.30
  # Trades                  7
  Win Rate                  28.57%
  Best Trade                13.96%
  Worst Trade               -3.89%
  Avg Trade                 0.67%
  Exposure Time             41.60%
  Equity Final              104774.80$
  Equity Peak               118859.76$
  Avg Drawdown              -2.40%
  Max Drawdown Duration     221 days 00:00:00
  Max Trade Duration        169 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               2.38%
  Ann. Volatility           9.82%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — configurable-ema-stack-strategy
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema1Len = 5
    ema2Len = 20
    ema3Len = 50
    ema4Len = 90
    ema5Len = 140
    ema6Len = 200
    
    useEma1 = True
    useEma2 = True
    useEma3 = True
    useEma4 = True
    useEma5 = True
    useEma6 = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema1 = self.I(pta.ema, close, length=self.ema1Len)
        self.ema2 = self.I(pta.ema, close, length=self.ema2Len)
        self.ema3 = self.I(pta.ema, close, length=self.ema3Len)
        self.ema4 = self.I(pta.ema, close, length=self.ema4Len)
        self.ema5 = self.I(pta.ema, close, length=self.ema5Len)
        self.ema6 = self.I(pta.ema, close, length=self.ema6Len)
        
        self.prev_bull_bias = False
        self.prev_bear_bias = False

    def next(self):
        if len(self.data) < max(self.ema1Len, self.ema2Len, self.ema3Len, self.ema4Len, self.ema5Len, self.ema6Len) + 1:
            return
        
        ema_vals = []
        if self.useEma1:
            ema_vals.append(self.ema1[-1])
        if self.useEma2:
            ema_vals.append(self.ema2[-1])
        if self.useEma3:
            ema_vals.append(self.ema3[-1])
        if self.useEma4:
            ema_vals.append(self.ema4[-1])
        if self.useEma5:
            ema_vals.append(self.ema5[-1])
        if self.useEma6:
            ema_vals.append(self.ema6[-1])
        
        bull_bias = True
        bear_bias = True
        
        if len(ema_vals) >= 2:
            for i in range(len(ema_vals) - 1):
                if ema_vals[i] <= ema_vals[i + 1]:
                    bull_bias = False
                if ema_vals[i] >= ema_vals[i + 1]:
                    bear_bias = False
        
        new_bull_bias = bull_bias and not self.prev_bull_bias
        new_bear_bias = bear_bias and not self.prev_bear_bias
        
        fast_bull_ok = True
        fast_bear_ok = True
        
        if self.useEma1 and self.useEma2:
            fast_bull_ok = self.ema1[-1] > self.ema2[-1]
            fast_bear_ok = self.ema1[-1] < self.ema2[-1]
        
        full_bull = bull_bias and fast_bull_ok
        full_bear = bear_bias and fast_bear_ok
        
        long_signal = full_bull and (crossover(self.ema1, self.ema2) or new_bull_bias)
        short_signal = full_bear and (crossover(self.ema2, self.ema1) or new_bear_bias)
        
        exit_long_signal = self.position.is_long and crossover(self.ema2, self.ema1)
        exit_short_signal = self.position.is_short and crossover(self.ema1, self.ema2)
        
        if long_signal and not self.position.is_long:
            if self.position.is_short:
                self.position.close()
            self.buy()
        
        if short_signal and not self.position.is_short:
            if self.position.is_long:
                self.position.close()
            self.sell()
        
        if exit_long_signal and not short_signal:
            self.position.close()
        
        if exit_short_signal and not long_signal:
            self.position.close()
        
        self.prev_bull_bias = bull_bias
        self.prev_bear_bias = bear_bias


if __name__ == "__main__":
    bt = Backtest(
        pd.read_csv("data.csv", index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.001,
        slippage=0.001
    )
    stats = bt.run()
    print(stats)