"""
DS-TV Backtest Results: configurable-averages-vwap-institutional-bands
============================================================

--- SPY ---
  Return                    -0.76%
  Buy & Hold Return         17.90%
  Max Drawdown              -3.46%
  Sharpe Ratio              -0.10
  Sortino Ratio             -0.12
  Calmar Ratio              -0.11
  Profit Factor             0.79
  Expectancy                -0.18%
  SQN                       -0.21
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                2.14%
  Worst Trade               -1.85%
  Avg Trade                 -0.19%
  Exposure Time             15.40%
  Equity Final              99241.88$
  Equity Peak               101375.04$
  Avg Drawdown              -2.11%
  Max Drawdown Duration     350 days 00:00:00
  Max Trade Duration        67 days 00:00:00
  Avg Trade Duration        27 days 00:00:00
  Ann. Return               -0.38%
  Ann. Volatility           4.01%

--- BTC ---
  Return                    9.71%
  Buy & Hold Return         17.39%
  Max Drawdown              -23.06%
  Sharpe Ratio              0.28
  Sortino Ratio             0.46
  Calmar Ratio              0.21
  Profit Factor             2.02
  Expectancy                2.58%
  SQN                       0.27
  # Trades                  11
  Win Rate                  36.36%
  Best Trade                49.58%
  Worst Trade               -9.73%
  Avg Trade                 1.66%
  Exposure Time             24.90%
  Equity Final              109707.82$
  Equity Peak               141774.37$
  Avg Drawdown              -3.72%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        72 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               4.73%
  Ann. Volatility           17.17%

--- QQQ ---
  Return                    -12.97%
  Buy & Hold Return         22.08%
  Max Drawdown              -12.97%
  Sharpe Ratio              -1.27
  Sortino Ratio             -1.36
  Calmar Ratio              -0.52
  Profit Factor             0.00
  Expectancy                -2.29%
  SQN                       -5.69
  # Trades                  6
  Win Rate                  0.00%
  Best Trade                -0.85%
  Worst Trade               -3.89%
  Avg Trade                 -2.30%
  Exposure Time             13.80%
  Equity Final              87027.09$
  Equity Peak               100000.00$
  Avg Drawdown              -12.97%
  Max Drawdown Duration     399 days 00:00:00
  Max Trade Duration        35 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               -6.76%
  Ann. Volatility           5.34%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — configurable-averages-vwap-institutional-bands
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Moving averages periods
    ma1_period = 9
    ma2_period = 20
    ma3_period = 50
    ma4_period = 200
    ma5_period = 200
    
    # Moving averages types
    ma1_type = "EMA"
    ma2_type = "EMA"
    ma3_type = "EMA"
    ma4_type = "EMA"
    ma5_type = "SMA"
    
    # VWAP bands multiplier
    dp_mult = 1.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate moving averages
        if self.ma1_type == "EMA":
            self.ma1 = self.I(pta.ema, close, length=self.ma1_period)
        else:
            self.ma1 = self.I(pta.sma, close, length=self.ma1_period)
            
        if self.ma2_type == "EMA":
            self.ma2 = self.I(pta.ema, close, length=self.ma2_period)
        else:
            self.ma2 = self.I(pta.sma, close, length=self.ma2_period)
            
        if self.ma3_type == "EMA":
            self.ma3 = self.I(pta.ema, close, length=self.ma3_period)
        else:
            self.ma3 = self.I(pta.sma, close, length=self.ma3_period)
            
        if self.ma4_type == "EMA":
            self.ma4 = self.I(pta.ema, close, length=self.ma4_period)
        else:
            self.ma4 = self.I(pta.sma, close, length=self.ma4_period)
            
        if self.ma5_type == "EMA":
            self.ma5 = self.I(pta.ema, close, length=self.ma5_period)
        else:
            self.ma5 = self.I(pta.sma, close, length=self.ma5_period)
        
        # Calculate VWAP with bands for daily timeframe
        self.vwap_d = self.I(self._calc_vwap_daily, close, high, low, volume)
        self.vwap_d_band_up = self.I(self._calc_vwap_band_up_daily, close, high, low, volume)
        self.vwap_d_band_dn = self.I(self._calc_vwap_band_dn_daily, close, high, low, volume)

    def _calc_vwap_daily(self, close, high, low, volume):
        """Calculate daily VWAP"""
        tp = (high + low + close) / 3
        cumv = volume.cumsum()
        cumtp = (tp * volume).cumsum()
        vwap = cumtp / cumv
        return vwap

    def _calc_vwap_band_up_daily(self, close, high, low, volume):
        """Calculate daily VWAP upper band"""
        tp = (high + low + close) / 3
        cumv = volume.cumsum()
        cumtp = (tp * volume).cumsum()
        cumtp2 = (tp * tp * volume).cumsum()
        vwap = cumtp / cumv
        ex2 = cumtp2 / cumv
        varp = np.maximum(ex2 - vwap * vwap, 0)
        sd = np.sqrt(varp)
        return vwap + sd * self.dp_mult

    def _calc_vwap_band_dn_daily(self, close, high, low, volume):
        """Calculate daily VWAP lower band"""
        tp = (high + low + close) / 3
        cumv = volume.cumsum()
        cumtp = (tp * volume).cumsum()
        cumtp2 = (tp * tp * volume).cumsum()
        vwap = cumtp / cumv
        ex2 = cumtp2 / cumv
        varp = np.maximum(ex2 - vwap * vwap, 0)
        sd = np.sqrt(varp)
        return vwap - sd * self.dp_mult

    def next(self):
        # Check if we have valid indicator values
        if pd.isna(self.ma1[-1]) or pd.isna(self.ma2[-1]):
            return
        
        # Trading logic based on moving average crossovers
        # Buy when fast MA (ma1) crosses above slower MA (ma2)
        if crossover(self.ma1, self.ma2):
            if not self.position:
                self.buy()
        
        # Sell when fast MA (ma1) crosses below slower MA (ma2)
        elif crossover(self.ma2, self.ma1):
            if self.position:
                self.position.close()
        
        # Additional exit condition: price touches lower VWAP band
        if self.position and not pd.isna(self.vwap_d_band_dn[-1]):
            if self.data.Close[-1] <= self.vwap_d_band_dn[-1]:
                self.position.close()
        
        # Additional exit condition: price falls below MA4 (longer term support)
        if self.position and pd.notna(self.ma4[-1]):
            if self.data.Close[-1] < self.ma4[-1]:
                if pd.isna(self.ma1[-1]) or self.ma1[-1] < self.ma3[-1]:
                    self.position.close()


if __name__ == "__main__":
    # Load data
    df = pd.read_csv("data.csv", index_col=0, parse_dates=True)
    
    # Run backtest
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()