"""
DS-TV Backtest Results: crossing-moving-averages-with-adx-filter
============================================================

--- SPY ---
  Return                    35.79%
  Buy & Hold Return         32.60%
  Max Drawdown              -18.68%
  Sharpe Ratio              0.94
  Sortino Ratio             1.66
  Calmar Ratio              0.89
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              135788.74$
  Equity Peak               136089.04$
  Avg Drawdown              -1.65%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               16.67%
  Ann. Volatility           17.80%

--- BTC ---
  Return                    0.14%
  Buy & Hold Return         0.79%
  Max Drawdown              -40.02%
  Sharpe Ratio              0.00
  Sortino Ratio             0.00
  Calmar Ratio              0.00
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100136.10$
  Equity Peak               155038.57$
  Avg Drawdown              -7.68%
  Max Drawdown Duration     141 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.07%
  Ann. Volatility           32.37%

--- QQQ ---
  Return                    41.44%
  Buy & Hold Return         38.01%
  Max Drawdown              -22.74%
  Sharpe Ratio              0.84
  Sortino Ratio             1.50
  Calmar Ratio              0.84
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              141439.66$
  Equity Peak               146185.01$
  Avg Drawdown              -2.52%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               19.09%
  Ann. Volatility           22.84%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — crossing-moving-averages-with-adx-filter
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fastLen = 20
    slowLen = 120
    maType = "SMA"
    useADX = True
    adxLen = 14
    adxThreshold = 20.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate moving averages based on type
        if self.maType == "SMA":
            self.fastMA = self.I(pta.sma, close, length=self.fastLen)
            self.slowMA = self.I(pta.sma, close, length=self.slowLen)
        elif self.maType == "EMA":
            self.fastMA = self.I(pta.ema, close, length=self.fastLen)
            self.slowMA = self.I(pta.ema, close, length=self.slowLen)
        elif self.maType == "WMA":
            self.fastMA = self.I(pta.wma, close, length=self.fastLen)
            self.slowMA = self.I(pta.wma, close, length=self.slowLen)
        else:  # LMA/RMA
            self.fastMA = self.I(pta.rma, close, length=self.fastLen)
            self.slowMA = self.I(pta.rma, close, length=self.slowLen)
        
        # Calculate ADX components
        def calc_adx():
            tr = pta.true_range(high, low, close)
            trur = pta.rma(tr, length=self.adxLen)
            
            upMove = high.diff()
            downMove = -low.diff()
            
            plusDM = pd.Series(0.0, index=close.index)
            minusDM = pd.Series(0.0, index=close.index)
            
            for i in range(1, len(close)):
                upM = upMove.iloc[i] if upMove.iloc[i] > downMove.iloc[i] and upMove.iloc[i] > 0 else 0.0
                downM = downMove.iloc[i] if downMove.iloc[i] > upMove.iloc[i] and downMove.iloc[i] > 0 else 0.0
                plusDM.iloc[i] = upM
                minusDM.iloc[i] = downM
            
            plusDI_raw = pta.rma(plusDM, length=self.adxLen)
            minusDI_raw = pta.rma(minusDM, length=self.adxLen)
            
            plusDI = 100 * plusDI_raw / trur
            minusDI = 100 * minusDI_raw / trur
            
            dx = 100 * np.abs(plusDI - minusDI) / (plusDI + minusDI)
            adx = pta.rma(dx, length=self.adxLen)
            
            return adx
        
        self.adx = self.I(calc_adx)

    def next(self):
        longBias = self.fastMA[-1] > self.slowMA[-1]
        shortBias = self.fastMA[-1] < self.slowMA[-1]
        
        adxOK = not self.useADX or (self.adx[-1] is not None and self.adx[-1] >= self.adxThreshold)
        
        enterLong = longBias and adxOK and not self.position
        enterShort = shortBias and adxOK and not self.position
        
        if enterLong:
            self.buy()
        elif enterShort:
            self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()