"""
DS-TV Backtest Results: cyberpunk-ichimoku-oracle
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — cyberpunk-ichimoku-oracle
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    tenkan_len = 9
    kijun_len = 26
    senkou_b = 52
    displacement = 26

    def init(self):
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        close = pd.Series(self.data.Close)
        
        # Donchian calculation: average of highest high and lowest low
        def donchian(src_high, src_low, length):
            highest = src_high.rolling(window=length).max()
            lowest = src_low.rolling(window=length).min()
            return (highest + lowest) / 2
        
        # Calculate Ichimoku components
        self.tenkan = self.I(lambda: donchian(high, low, self.tenkan_len))
        self.kijun = self.I(lambda: donchian(high, low, self.kijun_len))
        self.span_a = self.I(lambda: (self.tenkan + self.kijun) / 2)
        self.span_b = self.I(lambda: donchian(high, low, self.senkou_b))
        
        # For chikou (lagging line), we'll use close
        self.chikou = close
        
        # Calculate signal indicators
        self.tenkan_above_kijun = self.I(lambda: (self.tenkan > self.kijun).astype(int))

    def next(self):
        if len(self) < self.displacement + self.senkou_b:
            return
        
        # Ichimoku analysis
        # Price vs Kumo (displaced forward)
        kumo_top = max(self.span_a[-self.displacement], self.span_b[-self.displacement])
        kumo_btm = min(self.span_a[-self.displacement], self.span_b[-self.displacement])
        
        price_vs_kumo = 1 if self.data.Close[-1] > kumo_top else (-1 if self.data.Close[-1] < kumo_btm else 0)
        
        # Tenkan-Kijun cross status
        tk_positive = 1 if self.tenkan[-1] > self.kijun[-1] else -1
        
        # Chikou span status (displaced backwards)
        chikou_idx = len(self) - self.displacement - 1
        if chikou_idx >= 0:
            chikou_price = self.chikou.iloc[chikou_idx]
            c_stat = 1 if self.data.Close[-1] > chikou_price else (-1 if self.data.Close[-1] < chikou_price else 0)
        else:
            c_stat = 0
        
        # Score system
        score = price_vs_kumo + tk_positive + c_stat
        
        # Entry/Exit logic based on Ichimoku signals
        # Strong bullish: all three signals aligned positively
        if score == 3 and not self.position:
            self.buy()
        # Strong bearish: all three signals aligned negatively
        elif score == -3 and self.position:
            self.sell()
        # Moderate bullish signal
        elif score == 2 and not self.position and price_vs_kumo == 1 and tk_positive == 1:
            self.buy()
        # Moderate bearish signal
        elif score == -2 and self.position and price_vs_kumo == -1 and tk_positive == -1:
            self.sell()
        # Exit on neutral bias after entry
        elif score == 0 and self.position:
            self.sell()