"""
DS-TV Backtest Results: edo-ema-core-cross
============================================================

--- SPY ---
  Return                    17.83%
  Buy & Hold Return         17.90%
  Max Drawdown              -4.90%
  Sharpe Ratio              1.07
  Sortino Ratio             1.73
  Calmar Ratio              1.76
  Profit Factor             6.58
  Expectancy                4.64%
  SQN                       0.83
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                21.39%
  Worst Trade               -1.85%
  Avg Trade                 4.22%
  Exposure Time             43.20%
  Equity Final              117832.80$
  Equity Peak               121843.33$
  Avg Drawdown              -1.16%
  Max Drawdown Duration     137 days 00:00:00
  Max Trade Duration        202 days 00:00:00
  Avg Trade Duration        77 days 00:00:00
  Ann. Return               8.62%
  Ann. Volatility           8.09%

--- BTC ---
  Return                    22.05%
  Buy & Hold Return         17.39%
  Max Drawdown              -18.76%
  Sharpe Ratio              0.50
  Sortino Ratio             0.85
  Calmar Ratio              0.56
  Profit Factor             2.45
  Expectancy                3.81%
  SQN                       0.55
  # Trades                  12
  Win Rate                  33.33%
  Best Trade                49.58%
  Worst Trade               -9.73%
  Avg Trade                 2.83%
  Exposure Time             38.71%
  Equity Final              122045.91$
  Equity Peak               146294.94$
  Avg Drawdown              -4.65%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        72 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               10.46%
  Ann. Volatility           21.08%

--- QQQ ---
  Return                    11.89%
  Buy & Hold Return         22.08%
  Max Drawdown              -12.96%
  Sharpe Ratio              0.56
  Sortino Ratio             0.84
  Calmar Ratio              0.45
  Profit Factor             2.14
  Expectancy                2.45%
  SQN                       0.41
  # Trades                  6
  Win Rate                  16.67%
  Best Trade                27.60%
  Worst Trade               -3.89%
  Avg Trade                 1.90%
  Exposure Time             41.80%
  Equity Final              111891.30$
  Equity Peak               128557.95$
  Avg Drawdown              -1.99%
  Max Drawdown Duration     126 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        49 days 00:00:00
  Ann. Return               5.83%
  Ann. Volatility           10.39%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — edo-ema-core-cross
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate EMAs
        self.ema9 = self.I(pta.ema, close, length=9)
        self.ema20 = self.I(pta.ema, close, length=20)
        self.ema50 = self.I(pta.ema, close, length=50)
        self.ema100 = self.I(pta.ema, close, length=100)
        self.ema200 = self.I(pta.ema, close, length=200)

    def next(self):
        # Trading signals based on EMA crossovers
        
        # EMA 9/20 crossover
        if crossover(self.ema9, self.ema20):
            if not self.position:
                self.buy()
        elif crossover(self.ema20, self.ema9):
            if self.position:
                self.position.close()
        
        # EMA 20/50 crossover for additional confirmation
        if crossover(self.ema20, self.ema50):
            if not self.position:
                self.buy()
        elif crossover(self.ema50, self.ema20):
            if self.position:
                self.position.close()
        
        # EMA 50/200 crossover for strong signals
        if crossover(self.ema50, self.ema200):
            if not self.position:
                self.buy()
        elif crossover(self.ema200, self.ema50):
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()