"""
DS-TV Backtest Results: elite-cloud-breakout
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — elite-cloud-breakout
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    emaLengthInput = 21
    sensitivityInput = 1
    atrPeriodInput = 10

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Dual EMA Cloud
        self.emaHigh = self.I(pta.ema, high, length=self.emaLengthInput)
        self.emaLow = self.I(pta.ema, low, length=self.emaLengthInput)
        self.emaAvg = self.I(lambda: (self.emaHigh + self.emaLow) / 2)
        
        # ATR for trailing stop
        self.atr = self.I(pta.atr, high, low, close, length=self.atrPeriodInput)
        
        # Initialize trailing stop
        self.trailingStop = np.zeros(len(self.data))
        self.lastTrailingStop = 0.0

    def next(self):
        # Calculate nLoss
        nLoss = self.sensitivityInput * (self.atr[-1] if self.atr[-1] is not None else 0)
        
        # Update trailing stop
        if len(self) < 2:
            self.trailingStop[len(self) - 1] = self.data.Close[-1]
            self.lastTrailingStop = self.data.Close[-1]
            return
        
        prevTrailingStop = self.lastTrailingStop
        
        if self.data.Close[-1] > prevTrailingStop and self.data.Close[-2] > prevTrailingStop:
            newStop = max(prevTrailingStop, self.data.Close[-1] - nLoss)
        elif self.data.Close[-1] < prevTrailingStop and self.data.Close[-2] < prevTrailingStop:
            newStop = min(prevTrailingStop, self.data.Close[-1] + nLoss)
        elif self.data.Close[-1] > prevTrailingStop:
            newStop = self.data.Close[-1] - nLoss
        else:
            newStop = self.data.Close[-1] + nLoss
        
        self.trailingStop[len(self) - 1] = newStop
        self.lastTrailingStop = newStop
        
        # Signal Logic: 2-Bar Cloud Breakout
        if len(self) < 3:
            return
        
        isAbove = self.data.Close[-1] > self.emaHigh[-1]
        isAbove_1 = self.data.Close[-2] > self.emaHigh[-2]
        isAbove_2 = self.data.Close[-3] > self.emaHigh[-3]
        
        isBelow = self.data.Close[-1] < self.emaLow[-1]
        isBelow_1 = self.data.Close[-2] < self.emaLow[-2]
        isBelow_2 = self.data.Close[-3] < self.emaLow[-3]
        
        buySignal = isAbove and isAbove_1 and not isAbove_2
        sellSignal = isBelow and isBelow_1 and not isBelow_2
        
        if buySignal and not self.position:
            self.buy()
        elif sellSignal and self.position:
            self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()