"""
DS-TV Backtest Results: ema-2452
============================================================

--- SPY ---
  Return                    27.11%
  Buy & Hold Return         40.80%
  Max Drawdown              -16.47%
  Sharpe Ratio              0.77
  Sortino Ratio             1.23
  Calmar Ratio              0.78
  Profit Factor             3.43
  Expectancy                3.95%
  SQN                       0.51
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                11.14%
  Worst Trade               -3.25%
  Avg Trade                 3.70%
  Exposure Time             51.00%
  Equity Final              127112.38$
  Equity Peak               127394.20$
  Avg Drawdown              -2.24%
  Max Drawdown Duration     259 days 00:00:00
  Max Trade Duration        300 days 00:00:00
  Avg Trade Duration        186 days 00:00:00
  Ann. Return               12.85%
  Ann. Volatility           16.65%

--- BTC ---
  Return                    1.77%
  Buy & Hold Return         0.21%
  Max Drawdown              -34.23%
  Sharpe Ratio              0.03
  Sortino Ratio             0.04
  Calmar Ratio              0.03
  Profit Factor             1.07
  Expectancy                0.47%
  SQN                       0.04
  # Trades                  10
  Win Rate                  30.00%
  Best Trade                52.25%
  Worst Trade               -11.30%
  Avg Trade                 -0.97%
  Exposure Time             68.67%
  Equity Final              101767.25$
  Equity Peak               132404.81$
  Avg Drawdown              -8.86%
  Max Drawdown Duration     195 days 00:00:00
  Max Trade Duration        152 days 00:00:00
  Avg Trade Duration        50 days 00:00:00
  Ann. Return               0.88%
  Ann. Volatility           33.27%

--- QQQ ---
  Return                    -3.76%
  Buy & Hold Return         46.14%
  Max Drawdown              -28.40%
  Sharpe Ratio              -0.10
  Sortino Ratio             -0.14
  Calmar Ratio              -0.07
  Profit Factor             0.18
  Expectancy                -3.43%
  SQN                       -1.99
  # Trades                  6
  Win Rate                  16.67%
  Best Trade                4.44%
  Worst Trade               -7.95%
  Avg Trade                 -3.51%
  Exposure Time             50.00%
  Equity Final              96236.17$
  Equity Peak               111124.47$
  Avg Drawdown              -5.57%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        171 days 00:00:00
  Avg Trade Duration        61 days 00:00:00
  Ann. Return               -1.92%
  Ann. Volatility           18.68%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ema-2452
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        open_price = pd.Series(self.data.Open)
        
        # Calculate EMAs
        self.ema_fast = self.I(pta.ema, close, length=24)
        self.ema_slow = self.I(pta.ema, close, length=52)
        
        # Calculate amplitude (percentage change from open to close)
        self.amplitude = self.I(lambda: (close - open_price) / open_price * 100)

    def next(self):
        # Buy when fast EMA crosses above slow EMA
        if crossover(self.ema_fast, self.ema_slow):
            self.buy()
        
        # Sell when fast EMA crosses below slow EMA
        elif crossover(self.ema_slow, self.ema_fast):
            self.sell()