"""
DS-TV Backtest Results: ema-950-atr-full-terminal
============================================================

--- SPY ---
  Return                    14.01%
  Buy & Hold Return         40.20%
  Max Drawdown              -19.07%
  Sharpe Ratio              0.46
  Sortino Ratio             0.73
  Calmar Ratio              0.36
  Profit Factor             0.00
  Expectancy                -3.40%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -3.40%
  Worst Trade               -3.40%
  Avg Trade                 -3.40%
  Exposure Time             0.80%
  Equity Final              114013.64$
  Equity Peak               114266.20$
  Avg Drawdown              -2.00%
  Max Drawdown Duration     168 days 00:00:00
  Max Trade Duration        3 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               6.83%
  Ann. Volatility           14.99%

--- BTC ---
  Return                    94.58%
  Buy & Hold Return         0.29%
  Max Drawdown              -27.71%
  Sharpe Ratio              0.76
  Sortino Ratio             1.72
  Calmar Ratio              1.42
  Profit Factor             3.65
  Expectancy                8.21%
  SQN                       0.84
  # Trades                  9
  Win Rate                  55.56%
  Best Trade                72.90%
  Worst Trade               -15.49%
  Avg Trade                 6.06%
  Exposure Time             86.46%
  Equity Final              194577.68$
  Equity Peak               215599.61$
  Avg Drawdown              -4.69%
  Max Drawdown Duration     385 days 00:00:00
  Max Trade Duration        228 days 00:00:00
  Avg Trade Duration        71 days 00:00:00
  Ann. Return               39.43%
  Ann. Volatility           51.72%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         45.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ema-950-atr-full-terminal
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema9_len = 9
    ema50_len = 50
    rsi_length = 14
    atr_len = 14
    macd_fast = 12
    macd_slow = 26
    macd_signal = 9
    atr_mult = 1.0
    rr_ratio = 1.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema9 = self.I(pta.ema, close, length=self.ema9_len)
        self.ema50 = self.I(pta.ema, close, length=self.ema50_len)
        self.rsi = self.I(pta.rsi, close, length=self.rsi_length)
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_len)
        
        macd_result = self.I(lambda: pta.macd(close, fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_signal))
        self.macd_line = self.I(lambda: pta.macd(close, fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_signal)['MACD_12_26_9'] if pta.macd(close, fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_signal) is not None else pd.Series(0, index=close.index))
        self.macd_signal = self.I(lambda: pta.macd(close, fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_signal)['MACDh_12_26_9'] if pta.macd(close, fast=self.macd_fast, slow=self.macd_slow, signal=self.macd_signal) is not None else pd.Series(0, index=close.index))
        
        self.in_trade = False
        self.entry_price = None
        self.tp_price = None
        self.sl_price = None
        self.trade_type = None

    def next(self):
        if len(self.data) < max(self.ema50_len, self.atr_len, self.macd_slow) + 5:
            return
        
        close_val = self.data.Close[-1]
        high_val = self.data.High[-1]
        low_val = self.data.Low[-1]
        ema9_val = self.ema9[-1]
        ema50_val = self.ema50[-1]
        rsi_val = self.rsi[-1]
        atr_val = self.atr[-1]
        
        if pd.isna(atr_val) or atr_val == 0:
            return
        
        macd_line_val = self.macd_line[-1] if len(self.macd_line) > 0 and not pd.isna(self.macd_line[-1]) else 0
        macd_signal_val = self.macd_signal[-1] if len(self.macd_signal) > 0 and not pd.isna(self.macd_signal[-1]) else 0
        
        if self.in_trade:
            if self.trade_type == 1:
                if high_val >= self.tp_price:
                    self.sell()
                    self.in_trade = False
                elif low_val <= self.sl_price:
                    self.sell()
                    self.in_trade = False
            elif self.trade_type == -1:
                if low_val <= self.tp_price:
                    self.buy()
                    self.in_trade = False
                elif high_val >= self.sl_price:
                    self.buy()
                    self.in_trade = False
        else:
            buy_signal = crossover(self.ema9, self.ema50) and rsi_val > 50 and macd_line_val > macd_signal_val
            sell_signal = crossover(self.ema50, self.ema9) and rsi_val < 50 and macd_line_val < macd_signal_val
            
            if buy_signal:
                sl_dist = atr_val * self.atr_mult
                self.entry_price = close_val
                self.sl_price = close_val - sl_dist
                self.tp_price = close_val + (sl_dist * self.rr_ratio)
                self.trade_type = 1
                self.in_trade = True
                self.buy()
            
            elif sell_signal:
                sl_dist = atr_val * self.atr_mult
                self.entry_price = close_val
                self.sl_price = close_val + sl_dist
                self.tp_price = close_val - (sl_dist * self.rr_ratio)
                self.trade_type = -1
                self.in_trade = True
                self.sell()


if __name__ == '__main__':
    import yfinance as yf
    
    data = yf.download('SPY', start='2023-01-01', end='2024-01-01', interval='1h')
    
    bt = Backtest(data, TvStrategy, cash=100000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()