"""
DS-TV Backtest Results: ema-20-ema-50-touch-alert
============================================================

--- SPY ---
  Return                    -38.50%
  Buy & Hold Return         40.20%
  Max Drawdown              -38.99%
  Sharpe Ratio              -1.78
  Sortino Ratio             -1.93
  Calmar Ratio              -0.56
  Profit Factor             0.31
  Expectancy                -1.03%
  SQN                       -1.83
  # Trades                  43
  Win Rate                  27.91%
  Best Trade                7.79%
  Worst Trade               -21.77%
  Avg Trade                 -1.11%
  Exposure Time             89.40%
  Equity Final              61498.60$
  Equity Peak               100808.53$
  Avg Drawdown              -19.55%
  Max Drawdown Duration     649 days 00:00:00
  Max Trade Duration        193 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               -21.73%
  Ann. Volatility           12.19%

--- BTC ---
  Return                    -37.93%
  Buy & Hold Return         0.29%
  Max Drawdown              -52.21%
  Sharpe Ratio              -0.98
  Sortino Ratio             -1.04
  Calmar Ratio              -0.41
  Profit Factor             0.39
  Expectancy                -1.45%
  SQN                       -1.11
  # Trades                  43
  Win Rate                  46.51%
  Best Trade                6.98%
  Worst Trade               -51.88%
  Avg Trade                 -1.96%
  Exposure Time             36.39%
  Equity Final              62070.97$
  Equity Peak               106119.24$
  Avg Drawdown              -26.43%
  Max Drawdown Duration     673 days 00:00:00
  Max Trade Duration        73 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               -21.19%
  Ann. Volatility           21.52%

--- QQQ ---
  Return                    -40.85%
  Buy & Hold Return         45.93%
  Max Drawdown              -42.76%
  Sharpe Ratio              -1.45
  Sortino Ratio             -1.60
  Calmar Ratio              -0.54
  Profit Factor             0.38
  Expectancy                -1.28%
  SQN                       -1.48
  # Trades                  36
  Win Rate                  41.67%
  Best Trade                9.12%
  Worst Trade               -28.55%
  Avg Trade                 -1.45%
  Exposure Time             88.80%
  Equity Final              59154.40$
  Equity Peak               100440.45$
  Avg Drawdown              -22.76%
  Max Drawdown Duration     647 days 00:00:00
  Max Trade Duration        193 days 00:00:00
  Avg Trade Duration        18 days 00:00:00
  Ann. Return               -23.25%
  Ann. Volatility           16.01%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ema-20-ema-50-touch-alert
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema20 = self.I(pta.ema, close, length=20)
        self.ema50 = self.I(pta.ema, close, length=50)
        
        self.touch_ema20 = self.I(lambda: (low <= self.ema20) & (high >= self.ema20))
        self.touch_ema50 = self.I(lambda: (low <= self.ema50) & (high >= self.ema50))

    def next(self):
        if len(self.data) < 50:
            return
        
        if self.touch_ema20[-1] and not self.position:
            self.buy()
        elif self.touch_ema50[-1] and self.position:
            self.sell()