"""
DS-TV Backtest Results: ema-clouds-jb-style
============================================================

--- SPY ---
  Return                    5.52%
  Buy & Hold Return         29.25%
  Max Drawdown              -7.98%
  Sharpe Ratio              0.34
  Sortino Ratio             0.49
  Calmar Ratio              0.34
  Profit Factor             1.40
  Expectancy                0.41%
  SQN                       0.35
  # Trades                  16
  Win Rate                  31.25%
  Best Trade                13.06%
  Worst Trade               -4.60%
  Avg Trade                 0.34%
  Exposure Time             50.20%
  Equity Final              105518.26$
  Equity Peak               114666.60$
  Avg Drawdown              -1.72%
  Max Drawdown Duration     209 days 00:00:00
  Max Trade Duration        66 days 00:00:00
  Avg Trade Duration        22 days 00:00:00
  Ann. Return               2.74%
  Ann. Volatility           8.04%

--- BTC ---
  Return                    10.37%
  Buy & Hold Return         14.16%
  Max Drawdown              -19.45%
  Sharpe Ratio              0.26
  Sortino Ratio             0.41
  Calmar Ratio              0.26
  Profit Factor             1.52
  Expectancy                0.94%
  SQN                       0.37
  # Trades                  27
  Win Rate                  44.44%
  Best Trade                13.42%
  Worst Trade               -9.14%
  Avg Trade                 0.78%
  Exposure Time             39.95%
  Equity Final              110365.01$
  Equity Peak               137014.16$
  Avg Drawdown              -4.08%
  Max Drawdown Duration     181 days 00:00:00
  Max Trade Duration        27 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               5.05%
  Ann. Volatility           19.71%

--- QQQ ---
  Return                    2.91%
  Buy & Hold Return         27.84%
  Max Drawdown              -10.87%
  Sharpe Ratio              0.14
  Sortino Ratio             0.19
  Calmar Ratio              0.13
  Profit Factor             1.13
  Expectancy                0.15%
  SQN                       0.17
  # Trades                  28
  Win Rate                  35.71%
  Best Trade                10.40%
  Worst Trade               -4.24%
  Avg Trade                 0.10%
  Exposure Time             49.20%
  Equity Final              102908.27$
  Equity Peak               115460.86$
  Avg Drawdown              -3.27%
  Max Drawdown Duration     147 days 00:00:00
  Max Trade Duration        49 days 00:00:00
  Avg Trade Duration        12 days 00:00:00
  Ann. Return               1.46%
  Ann. Volatility           10.47%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ema-clouds-jb-style
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # EMA Lengths
    fast_ema1 = 5
    fast_ema2 = 12
    med_ema1 = 34
    med_ema2 = 50
    slow_ema1 = 72
    slow_ema2 = 89
    atr_length = 14
    atr_multiplier = 0.1
    rsi_length = 14

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # Current timeframe EMAs
        self.ema_fast1 = self.I(pta.ema, close, length=self.fast_ema1)
        self.ema_fast2 = self.I(pta.ema, close, length=self.fast_ema2)
        self.ema_med1 = self.I(pta.ema, close, length=self.med_ema1)
        self.ema_med2 = self.I(pta.ema, close, length=self.med_ema2)
        self.ema_slow1 = self.I(pta.ema, close, length=self.slow_ema1)
        self.ema_slow2 = self.I(pta.ema, close, length=self.slow_ema2)

        # ATR for sweep detection
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_length)

        # RSI
        self.rsi = self.I(pta.rsi, close, length=self.rsi_length)

    def next(self):
        # Skip if not enough data
        if len(self.data) < self.slow_ema2 + 5:
            return

        # Current values
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        prev_low = self.data.Low[-2] if len(self.data) > 1 else current_low
        prev_high = self.data.High[-2] if len(self.data) > 1 else current_high

        # ATR depth filter value
        atr_val = self.atr[-1] if self.atr[-1] is not None else 0

        # Bull sweep trigger: low < low[1] and (low[1] - low >= 0.1 * atr14) and high > low[1] and close > low[1]
        bull_sweep = (
            current_low < prev_low
            and (prev_low - current_low >= self.atr_multiplier * atr_val)
            and current_high > prev_low
            and current_close > prev_low
        )

        # Bear sweep trigger: high > high[1] and (high - high[1] >= 0.1 * atr14) and low < high[1] and close < high[1]
        bear_sweep = (
            current_high > prev_high
            and (current_high - prev_high >= self.atr_multiplier * atr_val)
            and current_low < prev_high
            and current_close < prev_high
        )

        # EMA trend conditions - all EMAs aligned
        fast_bullish = self.ema_fast1[-1] >= self.ema_fast2[-1]
        med_bullish = self.ema_med1[-1] >= self.ema_med2[-1]
        slow_bullish = self.ema_slow1[-1] >= self.ema_slow2[-1]
        all_bullish = fast_bullish and med_bullish and slow_bullish

        fast_bearish = self.ema_fast1[-1] < self.ema_fast2[-1]
        med_bearish = self.ema_med1[-1] < self.ema_med2[-1]
        slow_bearish = self.ema_slow1[-1] < self.ema_slow2[-1]
        all_bearish = fast_bearish and med_bearish and slow_bearish

        # Trend reference using fast EMA cloud
        trend_bullish = fast_bullish
        trend_bearish = fast_bearish

        # Entry logic
        # Buy on bull sweep with bullish trend alignment
        if bull_sweep and trend_bullish and all_bullish and not self.position:
            self.buy()

        # Sell on bear sweep with bearish trend alignment
        elif bear_sweep and trend_bearish and all_bearish and self.position:
            self.position.close()

        # Exit on trend reversal
        if self.position:
            # Exit long if fast EMA crosses below
            if crossover(self.ema_fast2, self.ema_fast1):
                self.position.close()

            # Exit on RSI overbought
            if self.rsi[-1] > 70:
                self.position.close()

        # Exit short positions on trend reversal (if shorting was implemented)
        if not self.position:
            # Buy on fast EMA bullish crossover with trend confirmation
            if crossover(self.ema_fast1, self.ema_fast2) and trend_bullish:
                self.buy()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()