"""
DS-TV Backtest Results: fiery-river-v20-with-volatility
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         29.25%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.16%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         27.84%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fiery-river-v20-with-volatility
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Moving Average Parameters
    ma_type = 'EMA'
    period = 89
    
    # Fibonacci ratios - Current timeframe
    fib1 = 0.618
    fib2 = 0.5
    fib3 = 0.382
    fib4 = 0.27
    fib5 = 0.18
    fib01 = 1.618
    fib02 = 1.72
    fib03 = 1.89
    
    # ATR Parameters
    atr_period = 13

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate Moving Average
        if self.ma_type == 'EMA':
            self.ma = self.I(pta.ema, close, length=self.period)
        elif self.ma_type == 'SMA':
            self.ma = self.I(pta.sma, close, length=self.period)
        elif self.ma_type == 'WMA':
            self.ma = self.I(pta.wma, close, length=self.period)
        elif self.ma_type == 'RMA':
            self.ma = self.I(pta.rma, close, length=self.period)
        elif self.ma_type == 'HMA':
            self.ma = self.I(pta.hma, close, length=self.period)
        else:
            self.ma = self.I(pta.ema, close, length=self.period)
        
        # Calculate ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_period)
        
        # Calculate Fibonacci support/resistance levels
        self.fib_s1 = self.I(lambda: self.ma * self.fib1 - self.atr)
        self.fib_s2 = self.I(lambda: self.ma * self.fib2 - self.atr)
        self.fib_s3 = self.I(lambda: self.ma * self.fib3 - self.atr)
        self.fib_s4 = self.I(lambda: self.ma * self.fib4 - self.atr)
        self.fib_s5 = self.I(lambda: self.ma * self.fib5 - self.atr)
        
        self.fib_r1 = self.I(lambda: self.ma * self.fib01 + self.atr * 2)
        self.fib_r2 = self.I(lambda: self.ma * self.fib02 + self.atr * 2)
        self.fib_r3 = self.I(lambda: self.ma * self.fib03 + self.atr * 2)

    def next(self):
        close = self.data.Close[-1]
        ma = self.ma[-1]
        atr = self.atr[-1]
        
        # Check if we have valid indicators
        if pd.isna(ma) or pd.isna(atr):
            return
        
        fib_s1 = self.fib_s1[-1]
        fib_s2 = self.fib_s2[-1]
        fib_r1 = self.fib_r1[-1]
        fib_r2 = self.fib_r2[-1]
        
        # Validate all values
        if pd.isna(fib_s1) or pd.isna(fib_s2) or pd.isna(fib_r1) or pd.isna(fib_r2):
            return
        
        # Buy signal: Price touches support levels and is below MA, with upward reversal
        if not self.position:
            if close <= fib_s1 and close > fib_s2:
                self.buy()
            elif close <= fib_s2 and len(self) > 1:
                if self.data.Close[-2] < close:
                    self.buy()
        
        # Sell signal: Price touches resistance levels and is above MA, with downward reversal
        if self.position:
            if close >= fib_r1 or close >= fib_r2:
                self.sell()
            elif close >= ma * 1.05:
                self.sell()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()