"""
DS-TV Backtest Results: fimathe-elite-pro
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "linreg_now" shape: (), returned value: 695.9204305346545)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "linreg_now" shape: (), returned value: 80471.1245922985)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "linreg_now" shape: (), returned value: 623.0669909534558)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fimathe-elite-pro
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # ALMA parameters
    len_alma = 9
    len_alma_slow = 40
    sigma_alma = 6
    offset_alma = 0.85
    
    # Setup parameters
    qtde_bars = 15
    lookback_trend = 60
    limite_pontos = 500
    ignorar_inicio = 1
    
    # Confluence and filters
    minConfluence = 2
    minVolume = 1.1
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # VWAP
        self.vwap = self.I(lambda: pta.vwap(close, high, low, volume) or pd.Series(close.iloc[-1], index=close.index))
        
        # ALMA indicators
        def alma_fast():
            result = pta.alma(close, length=self.len_alma, offset=self.offset_alma, sigma=self.sigma_alma)
            return result if result is not None else pd.Series(close.iloc[-1], index=close.index)
        
        def alma_slow():
            result = pta.alma(close, length=self.len_alma_slow, offset=self.offset_alma, sigma=self.sigma_alma)
            return result if result is not None else pd.Series(close.iloc[-1], index=close.index)
        
        self.alma_fast = self.I(alma_fast)
        self.alma_slow = self.I(alma_slow)
        
        # Volume MA
        self.volMA = self.I(pta.sma, volume, length=20)
        
        # Linear regression for trend
        def linreg_now():
            if len(close) >= self.lookback_trend:
                return pta.linreg(close, length=self.lookback_trend).iloc[-1]
            return close.iloc[-1]
        
        def linreg_prev():
            if len(close) >= self.lookback_trend + 1:
                return pta.linreg(close, length=self.lookback_trend).iloc[-2]
            return close.iloc[-1]
        
        self.linreg_now = self.I(linreg_now)
        self.linreg_prev = self.I(linreg_prev)
        
        # EMA for MTF trends
        self.ema_20 = self.I(pta.ema, close, length=20)
        
        # Track state
        self.estado = 0  # 0: waiting, 1: long, -1: short
        self.nivel = 1
        self.ePrice = None
        self.pStop = None
        self.pAlvo = None
        self.rTopo = None
        self.rFundo = None
        self.amp = None
        self.setupOk = False
        self.tendDir = None
        self.crTop = None
        self.crBot = None
        self.znTop = None
        self.znBot = None
        self.fatiado = False
        self.bIni = None
        self.bars_mapped = 0
        self.is_mapping = False

    def next(self):
        # Skip initial bars
        if len(self.data) <= self.ignorar_inicio:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        open_price = self.data.Open[-1]
        volume = self.data.Volume[-1]
        
        # Calculate current scores
        volMA = self.volMA[-1]
        vwapVal = self.vwap[-1]
        highVol = volume > volMA * self.minVolume
        
        lrNow = self.linreg_now[-1]
        lrPrev = self.linreg_prev[-1]
        
        # Bullish and bearish scores
        bScore = (1 if highVol else 0) + (1 if close > vwapVal else 0) + (1 if close > open_price else 0) + (1 if lrNow > lrPrev else 0)
        sScore = (1 if highVol else 0) + (1 if close < vwapVal else 0) + (1 if close < open_price else 0) + (1 if lrNow < lrPrev else 0)
        
        # Setup mapping logic
        if not self.setupOk:
            if not self.is_mapping:
                self.is_mapping = True
                self.bars_mapped = 1
                self.bIni = len(self.data)
                self.rTopo = high
                self.rFundo = low
            else:
                self.bars_mapped += 1
                self.rTopo = max(self.rTopo, high)
                self.rFundo = min(self.rFundo, low)
                
                if self.bars_mapped >= self.qtde_bars:
                    # Setup complete
                    self.setupOk = True
                    self.is_mapping = False
                    
                    rng = self.rTopo - self.rFundo
                    self.fatiado = rng > self.limite_pontos
                    self.amp = (rng / 2.0) if self.fatiado else rng
                    self.tendDir = "ALTA" if lrNow > lrPrev else "BAIXA"
                    
                    mid = (self.rTopo + self.rFundo) / 2.0
                    
                    if self.tendDir == "ALTA":
                        self.crTop = self.rTopo
                        self.crBot = mid if self.fatiado else self.rFundo
                        self.znTop = mid if self.fatiado else self.rFundo
                        self.znBot = (self.rFundo if self.fatiado else self.rFundo - self.amp)
                    else:
                        self.crTop = mid if self.fatiado else self.rTopo
                        self.crBot = self.rFundo
                        self.znTop = (self.rTopo if self.fatiado else self.rTopo + self.amp)
                        self.znBot = mid if self.fatiado else self.rTopo
        
        if self.setupOk:
            # ESTADO 0: WAITING
            if self.estado == 0:
                if self.tendDir == "ALTA":
                    # Buy signal
                    if close > self.crTop and bScore >= self.minConfluence:
                        self.estado = 1
                        self.nivel = 1
                        self.ePrice = close
                        self.pStop = self.znBot
                        self.pAlvo = self.crTop + self.amp
                        self.buy()
                    # Reversal sell
                    elif close < self.znBot and sScore >= self.minConfluence:
                        self.estado = -1
                        self.nivel = 1
                        self.ePrice = close
                        self.pStop = self.crBot
                        self.pAlvo = self.znBot - self.amp
                        self.sell()
                else:  # BAIXA
                    # Sell signal
                    if close < self.crBot and sScore >= self.minConfluence:
                        self.estado = -1
                        self.nivel = 1
                        self.ePrice = close
                        self.pStop = self.znTop
                        self.pAlvo = self.crBot - self.amp
                        self.sell()
                    # Reversal buy
                    elif close > self.znTop and bScore >= self.minConfluence:
                        self.estado = 1
                        self.nivel = 1
                        self.ePrice = close
                        self.pStop = self.crTop
                        self.pAlvo = self.znTop + self.amp
                        self.buy()
            
            # ESTADO 1: LONG
            elif self.estado == 1:
                # Stop loss
                if close < self.pStop:
                    self.estado = 0
                    self.pStop = None
                    self.pAlvo = None
                    self.nivel = 1
                    self.sell()
                # Take profit
                elif close >= self.pAlvo and self.pAlvo is not None:
                    self.nivel += 1
                    self.pStop = self.pStop + self.amp
                    self.pAlvo = self.pAlvo + self.amp
                    # Don't close, just move levels
            
            # ESTADO -1: SHORT
            elif self.estado == -1:
                # Stop loss
                if close > self.pStop:
                    self.estado = 0
                    self.pStop = None
                    self.pAlvo = None
                    self.nivel = 1
                    self.buy()
                # Take profit
                elif close <= self.pAlvo and self.pAlvo is not None:
                    self.nivel += 1
                    self.pStop = self.pStop - self.amp
                    self.pAlvo = self.pAlvo - self.amp
                    # Don't close, just move levels