"""
DS-TV Backtest Results: fractal-retracement-jamallo
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         38.23%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         9.48%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         41.79%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fractal-retracement-jamallo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    framaLength = 50
    framaFC = 1
    framaSC = 200
    rangeMultiplier = 1.5
    movsrc = 1
    band1Multiplier = 0.5
    band2Multiplier = 1.0
    bandSmoothing = 3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate FRAMA
        self.frama_values = self.I(self._calculate_frama, high, low, close)
        
        # Calculate adaptive range
        self.atr_values = self.I(pta.atr, high, low, close, length=int(self.framaLength / 2))
        self.adaptive_range = self.I(lambda: self.atr_values * self.rangeMultiplier if self.atr_values is not None else pd.Series(0, index=close.index))
        
        # Calculate k (filtered FRAMA with range logic)
        self.k_values = self.I(self._calculate_k, high, low, close)
        
        # Calculate adaptive bands
        self.band1_upper = self.I(self._calculate_band1_upper, close)
        self.band1_lower = self.I(self._calculate_band1_lower, close)
        self.band2_upper = self.I(self._calculate_band2_upper, close)
        self.band2_lower = self.I(self._calculate_band2_lower, close)
        
        # Direction tracking
        self.prev_k = None
        self.upward = True

    def _calculate_frama(self, high, low, close):
        filt = close.iloc[0]
        frama_result = []
        
        for i in range(len(close)):
            if i == 0:
                frama_result.append(close.iloc[i])
                continue
            
            n1 = int(self.framaLength / 2)
            n2 = int(self.framaLength / 2)
            
            start_idx = max(0, i - n1 + 1)
            hh1 = high.iloc[start_idx:i+1].max()
            ll1 = low.iloc[start_idx:i+1].min()
            
            start_idx2 = max(0, i - n1 - n2 + 1)
            end_idx2 = max(0, i - n1 + 1)
            if start_idx2 < end_idx2:
                hh2 = high.iloc[start_idx2:end_idx2].max()
                ll2 = low.iloc[start_idx2:end_idx2].min()
            else:
                hh2 = high.iloc[start_idx2] if start_idx2 < len(high) else hh1
                ll2 = low.iloc[start_idx2] if start_idx2 < len(low) else ll1
            
            start_idx3 = max(0, i - self.framaLength + 1)
            hh3 = high.iloc[start_idx3:i+1].max()
            ll3 = low.iloc[start_idx3:i+1].min()
            
            n1_range = hh1 - ll1
            n2_range = hh2 - ll2
            n3_range = hh3 - ll3
            
            if n3_range > 0:
                D = (np.log(n1_range + n2_range) - np.log(n3_range)) / np.log(2)
            else:
                D = 1.0
            
            D = np.clip(D, 1.0, 2.0)
            
            alpha = np.exp(-4.6 * (D - 1))
            oldAlpha = alpha
            oldN = (2 - oldAlpha) / oldAlpha if oldAlpha != 0 else 1
            newN = ((self.framaSC - self.framaFC) * (oldN - 1) / (self.framaSC - 1)) + self.framaFC
            alpha = 2 / (newN + 1)
            
            filt = alpha * close.iloc[i] + (1 - alpha) * filt
            frama_result.append(filt)
        
        return pd.Series(frama_result, index=close.index)

    def _calculate_k(self, high, low, close):
        frama_vals = self._calculate_frama(high, low, close)
        atr_vals = pta.atr(high, low, close, length=int(self.framaLength / 2))
        if atr_vals is None:
            atr_vals = pd.Series(0, index=close.index)
        
        adapt_range = atr_vals * self.rangeMultiplier
        
        hh = close if self.movsrc == 1 else high
        
        k_vals = []
        k = frama_vals.iloc[0]
        
        for i in range(len(close)):
            if i == 0:
                k_vals.append(k)
                continue
            
            if hh.iloc[i] > k_vals[i-1]:
                candidate = frama_vals.iloc[i] - adapt_range.iloc[i] if i < len(adapt_range) else frama_vals.iloc[i]
                k = candidate if candidate < k_vals[i-1] else k_vals[i-1]
            else:
                candidate = frama_vals.iloc[i] + adapt_range.iloc[i] if i < len(adapt_range) else frama_vals.iloc[i]
                k = candidate if candidate > k_vals[i-1] else k_vals[i-1]
            
            k_vals.append(k)
        
        return pd.Series(k_vals, index=close.index)

    def _calculate_band1_upper(self, close):
        k_vals = self.k_values
        atr_vals = pta.atr(pd.Series(self.data.High), pd.Series(self.data.Low), close, length=int(self.framaLength / 2))
        if atr_vals is None:
            atr_vals = pd.Series(0, index=close.index)
        
        adapt_range = atr_vals * self.rangeMultiplier
        band1_upper_raw = k_vals + (adapt_range * self.band1Multiplier)
        band1_upper_smooth = pta.ema(band1_upper_raw, length=self.bandSmoothing)
        if band1_upper_smooth is None:
            band1_upper_smooth = band1_upper_raw
        return band1_upper_smooth

    def _calculate_band1_lower(self, close):
        k_vals = self.k_values
        atr_vals = pta.atr(pd.Series(self.data.High), pd.Series(self.data.Low), close, length=int(self.framaLength / 2))
        if atr_vals is None:
            atr_vals = pd.Series(0, index=close.index)
        
        adapt_range = atr_vals * self.rangeMultiplier
        band1_lower_raw = k_vals - (adapt_range * self.band1Multiplier)
        band1_lower_smooth = pta.ema(band1_lower_raw, length=self.bandSmoothing)
        if band1_lower_smooth is None:
            band1_lower_smooth = band1_lower_raw
        return band1_lower_smooth

    def _calculate_band2_upper(self, close):
        k_vals = self.k_values
        atr_vals = pta.atr(pd.Series(self.data.High), pd.Series(self.data.Low), close, length=int(self.framaLength / 2))
        if atr_vals is None:
            atr_vals = pd.Series(0, index=close.index)
        
        adapt_range = atr_vals * self.rangeMultiplier
        band2_upper_raw = k_vals + (adapt_range * self.band2Multiplier)
        band2_upper_smooth = pta.ema(band2_upper_raw, length=self.bandSmoothing)
        if band2_upper_smooth is None:
            band2_upper_smooth = band2_upper_raw
        return band2_upper_smooth

    def _calculate_band2_lower(self, close):
        k_vals = self.k_values
        atr_vals = pta.atr(pd.Series(self.data.High), pd.Series(self.data.Low), close, length=int(self.framaLength / 2))
        if atr_vals is None:
            atr_vals = pd.Series(0, index=close.index)
        
        adapt_range = atr_vals * self.rangeMultiplier
        band2_lower_raw = k_vals - (adapt_range * self.band2Multiplier)
        band2_lower_smooth = pta.ema(band2_lower_raw, length=self.bandSmoothing)
        if band2_lower_smooth is None:
            band2_lower_smooth = band2_lower_raw
        return band2_lower_smooth

    def next(self):
        if len(self.data) < self.framaLength + 5:
            return
        
        current_k = self.k_values[-1]
        current_close = self.data.Close[-1]
        
        if self.prev_k is not None:
            if current_k > self.prev_k:
                self.upward = True
            elif current_k < self.prev_k:
                self.upward = False
        
        self.prev_k = current_k
        
        # Buy signal: price touches lower band in uptrend
        if self.upward and not self.position:
            if current_close <= self.band1_lower[-1]:
                self.buy()
        
        # Sell signal: price touches upper band in downtrend
        if not self.upward and self.position:
            if current_close >= self.band1_upper[-1]:
                self.sell()
        
        # Exit long if trend reverses
        if self.position and not self.upward:
            self.sell()
        
        # Exit short if trend reverses (not applicable for long-only, but kept for completeness)
        if not self.position and self.upward:
            pass


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()