"""
DS-TV Backtest Results: future-ema-projection
============================================================

--- SPY ---
  Return                    -21.76%
  Buy & Hold Return         40.20%
  Max Drawdown              -29.06%
  Sharpe Ratio              -0.87
  Sortino Ratio             -1.10
  Calmar Ratio              -0.40
  Profit Factor             0.20
  Expectancy                -2.69%
  SQN                       -1.55
  # Trades                  8
  Win Rate                  12.50%
  Best Trade                5.38%
  Worst Trade               -12.07%
  Avg Trade                 -2.80%
  Exposure Time             87.80%
  Equity Final              78237.84$
  Equity Peak               110083.31$
  Avg Drawdown              -5.47%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        266 days 00:00:00
  Avg Trade Duration        80 days 00:00:00
  Ann. Return               -11.63%
  Ann. Volatility           13.32%

--- BTC ---
  Return                    -28.56%
  Buy & Hold Return         0.29%
  Max Drawdown              -46.58%
  Sharpe Ratio              -0.80
  Sortino Ratio             -0.91
  Calmar Ratio              -0.33
  Profit Factor             0.18
  Expectancy                -9.59%
  SQN                       -0.79
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                7.88%
  Worst Trade               -56.55%
  Avg Trade                 -13.95%
  Exposure Time             30.37%
  Equity Final              71444.62$
  Equity Peak               112472.13$
  Avg Drawdown              -11.38%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        75 days 00:00:00
  Avg Trade Duration        45 days 00:00:00
  Ann. Return               -15.46%
  Ann. Volatility           19.29%

--- QQQ ---
  Return                    -25.34%
  Buy & Hold Return         45.93%
  Max Drawdown              -38.27%
  Sharpe Ratio              -0.79
  Sortino Ratio             -0.98
  Calmar Ratio              -0.36
  Profit Factor             0.29
  Expectancy                -2.70%
  SQN                       -1.14
  # Trades                  9
  Win Rate                  33.33%
  Best Trade                5.91%
  Worst Trade               -16.38%
  Avg Trade                 -2.94%
  Exposure Time             87.60%
  Equity Final              74657.76$
  Equity Peak               114954.70$
  Avg Drawdown              -7.20%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        264 days 00:00:00
  Avg Trade Duration        71 days 00:00:00
  Ann. Return               -13.70%
  Ann. Volatility           17.28%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — future-ema-projection
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len1 = 10
    len2 = 20
    len3 = 50

    def init(self):
        close = pd.Series(self.data.Close)
        
        self.ema1 = self.I(pta.ema, close, length=self.len1)
        self.ema2 = self.I(pta.ema, close, length=self.len2)
        self.ema3 = self.I(pta.ema, close, length=self.len3)

    def next(self):
        if len(self.data) < self.len3 + 1:
            return
        
        ema1_val = self.ema1[-1]
        ema2_val = self.ema2[-1]
        ema3_val = self.ema3[-1]
        
        if ema1_val is None or ema2_val is None or ema3_val is None:
            return
        
        if len(self.ema1) < 2 or len(self.ema2) < 2 or len(self.ema3) < 2:
            return
        
        ema1_prev = self.ema1[-2]
        ema2_prev = self.ema2[-2]
        
        if ema1_prev is None or ema2_prev is None:
            return
        
        if not self.position:
            if crossover(self.ema1, self.ema2):
                self.buy()
        else:
            if crossover(self.ema2, self.ema1):
                self.sell()