"""
DS-TV Backtest Results: globus-capitas-ema-9-ema-14-ribbon
============================================================

--- SPY ---
  Return                    23.79%
  Buy & Hold Return         38.66%
  Max Drawdown              -6.27%
  Sharpe Ratio              1.10
  Sortino Ratio             1.73
  Calmar Ratio              1.81
  Profit Factor             5.55
  Expectancy                2.61%
  SQN                       1.06
  # Trades                  9
  Win Rate                  44.44%
  Best Trade                21.09%
  Worst Trade               -1.85%
  Avg Trade                 2.40%
  Exposure Time             70.20%
  Equity Final              123789.19$
  Equity Peak               129606.94$
  Avg Drawdown              -1.15%
  Max Drawdown Duration     301 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        55 days 00:00:00
  Ann. Return               11.36%
  Ann. Volatility           10.34%

--- BTC ---
  Return                    11.36%
  Buy & Hold Return         37.68%
  Max Drawdown              -20.22%
  Sharpe Ratio              0.24
  Sortino Ratio             0.39
  Calmar Ratio              0.27
  Profit Factor             1.52
  Expectancy                1.64%
  SQN                       0.27
  # Trades                  17
  Win Rate                  29.41%
  Best Trade                51.06%
  Worst Trade               -8.91%
  Avg Trade                 0.82%
  Exposure Time             47.33%
  Equity Final              111362.46$
  Equity Peak               131450.66$
  Avg Drawdown              -6.27%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        70 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               5.52%
  Ann. Volatility           23.41%

--- QQQ ---
  Return                    21.79%
  Buy & Hold Return         39.38%
  Max Drawdown              -13.77%
  Sharpe Ratio              0.75
  Sortino Ratio             1.14
  Calmar Ratio              0.76
  Profit Factor             2.48
  Expectancy                1.87%
  SQN                       0.83
  # Trades                  12
  Win Rate                  58.33%
  Best Trade                20.57%
  Worst Trade               -4.76%
  Avg Trade                 1.66%
  Exposure Time             69.80%
  Equity Final              121786.51$
  Equity Peak               141240.67$
  Avg Drawdown              -2.03%
  Max Drawdown Duration     159 days 00:00:00
  Max Trade Duration        129 days 00:00:00
  Avg Trade Duration        41 days 00:00:00
  Ann. Return               10.44%
  Ann. Volatility           14.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — globus-capitas-ema-9-ema-14-ribbon
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    emaFastLen = 9
    emaSlowLen = 14

    def init(self):
        close = pd.Series(self.data.Close)
        self.emaFast = self.I(pta.ema, close, length=self.emaFastLen)
        self.emaSlow = self.I(pta.ema, close, length=self.emaSlowLen)

    def next(self):
        if crossover(self.emaFast, self.emaSlow):
            if not self.position:
                self.buy()
        elif crossover(self.emaSlow, self.emaFast):
            if self.position:
                self.position.close()