"""
DS-TV Backtest Results: high-volatility-ema-extension-bands
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         35.76%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         -2.17%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         39.41%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — high-volatility-ema-extension-bands
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        
        # EMA 8
        self.ema8 = self.I(pta.ema, close, length=8)
        
        # EMA 34
        self.ema34 = self.I(pta.ema, close, length=34)
        
        # Track state for signal filtering
        self.last_bullish_signal = -10
        self.last_bearish_signal = -10

    def next(self):
        # Check for crossover signals
        ema8_current = self.ema8[-1]
        ema8_prev = self.ema8[-2] if len(self.ema8) > 1 else ema8_current
        ema34_current = self.ema34[-1]
        ema34_prev = self.ema34[-2] if len(self.ema34) > 1 else ema34_current
        
        close_current = self.data.Close[-1]
        close_prev1 = self.data.Close[-2] if len(self.data.Close) > 1 else close_current
        close_prev2 = self.data.Close[-3] if len(self.data.Close) > 2 else close_prev1
        
        current_bar = len(self.data) - 1
        
        # Detect cross up (EMA 8 crosses above EMA 34)
        cross_up = (ema8_prev <= ema34_prev) and (ema8_current > ema34_current)
        
        # Detect cross down (EMA 8 crosses below EMA 34)
        cross_down = (ema8_prev >= ema34_prev) and (ema8_current < ema34_current)
        
        # Bullish condition: crossover happened 1-3 bars ago + 2 consecutive higher closes + close above 34 EMA
        bars_since_cross_up = current_bar - self.last_bullish_signal
        bullish_condition = (
            (1 <= bars_since_cross_up <= 3) and
            (close_current > close_prev1) and
            (close_prev1 > close_prev2) and
            (close_current > ema34_current) and
            (bars_since_cross_up > 3)  # Prevent duplicate signals
        )
        
        # Bearish condition: crossover happened 1-3 bars ago + 2 consecutive lower closes + close below 34 EMA
        bars_since_cross_down = current_bar - self.last_bearish_signal
        bearish_condition = (
            (1 <= bars_since_cross_down <= 3) and
            (close_current < close_prev1) and
            (close_prev1 < close_prev2) and
            (close_current < ema34_current) and
            (bars_since_cross_down > 3)  # Prevent duplicate signals
        )
        
        # Update state
        if cross_up:
            self.last_bullish_signal = current_bar
            self.last_bearish_signal = -10
        
        if cross_down:
            self.last_bearish_signal = current_bar
            self.last_bullish_signal = -10
        
        # Execute trades
        if bullish_condition:
            if not self.position:
                self.buy()
        elif bearish_condition:
            if self.position:
                self.sell()


if __name__ == "__main__":
    # Load your data here
    # df = pd.read_csv("data.csv", parse_dates=True, index_col=0)
    
    # Example: Using yfinance to fetch data
    import yfinance as yf
    df = yf.download("EURUSD=X", start="2022-01-01", end="2024-01-01", interval="1h")
    
    bt = Backtest(df, TvStrategy, commission=.0002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()