"""
DS-TV Backtest Results: hull-suite-session-master-mtf-ny-alertas
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         37.07%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         -1.05%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         40.95%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — hull-suite-session-master-mtf-ny-alertas
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 55
    length_mult = 1.0
    swing_lookback = 3
    line_bars = 10
    mode_switch = "Hma"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.len = int(np.round(self.length * self.length_mult))
        
        # Hull Moving Average calculation
        self.hull = self.I(self._calc_hull, close, self.len, self.mode_switch)
        
        # High/Low swings
        self.lowest_m3 = self.I(lambda: low.rolling(self.swing_lookback).min())
        self.highest_m3 = self.I(lambda: high.rolling(self.swing_lookback).max())
        
        # Session Master trend
        self.sm_trend = self.I(self._calc_session_master, high, low, close)
        
        # State variables
        self.precio_v2 = None
        self.retroceso_confirmado = False
        self.entrada_realizada = False
        self.entry_price = None
        self.sl_price = None
        self.tp_price = None
        self.bars_in_trade = 0

    def _calc_hull(self, close_series, length, mode):
        """Calculate Hull Moving Average"""
        half_len = int(length / 2)
        sqrt_len = int(np.sqrt(length))
        
        if mode == "Hma":
            wma_half = pta.wma(close_series, length=half_len)
            wma_full = pta.wma(close_series, length=length)
            if wma_half is None or wma_full is None:
                return pd.Series(0, index=close_series.index)
            combined = 2.0 * wma_half - wma_full
            result = pta.wma(combined, length=sqrt_len)
            return result if result is not None else pd.Series(0, index=close_series.index)
        
        elif mode == "Ehma":
            ema_half = pta.ema(close_series, length=half_len)
            ema_full = pta.ema(close_series, length=length)
            if ema_half is None or ema_full is None:
                return pd.Series(0, index=close_series.index)
            combined = 2.0 * ema_half - ema_full
            result = pta.ema(combined, length=sqrt_len)
            return result if result is not None else pd.Series(0, index=close_series.index)
        
        else:  # THMA
            third_len = int(length / 3)
            wma_third = pta.wma(close_series, length=third_len)
            wma_half = pta.wma(close_series, length=half_len)
            wma_full = pta.wma(close_series, length=length)
            if wma_third is None or wma_half is None or wma_full is None:
                return pd.Series(0, index=close_series.index)
            combined = 3.0 * wma_third - wma_half - wma_full
            result = pta.wma(combined, length=length)
            return result if result is not None else pd.Series(0, index=close_series.index)

    def _calc_session_master(self, high_series, low_series, close_series):
        """Calculate Session Master trend using DI logic"""
        len_sm = 28
        
        tr = np.maximum(
            np.maximum(high_series - low_series, 
                      np.abs(high_series - close_series.shift(1))),
            np.abs(low_series - close_series.shift(1))
        )
        
        dp = np.where(
            (high_series - high_series.shift(1)) > (low_series.shift(1) - low_series),
            np.maximum(high_series - high_series.shift(1), 0),
            0
        )
        
        dm = np.where(
            (low_series.shift(1) - low_series) > (high_series - high_series.shift(1)),
            np.maximum(low_series.shift(1) - low_series, 0),
            0
        )
        
        str_series = pd.Series(index=high_series.index, dtype=float)
        sdp_series = pd.Series(index=high_series.index, dtype=float)
        sdm_series = pd.Series(index=high_series.index, dtype=float)
        
        str_val = 0.0
        sdp_val = 0.0
        sdm_val = 0.0
        
        for i in range(len(high_series)):
            str_val = str_val - (str_val / len_sm) + tr.iloc[i]
            sdp_val = sdp_val - (sdp_val / len_sm) + dp[i]
            sdm_val = sdm_val - (sdm_val / len_sm) + dm[i]
            
            str_series.iloc[i] = str_val
            sdp_series.iloc[i] = sdp_val
            sdm_series.iloc[i] = sdm_val
        
        di_p = (sdp_series / str_series * 100).fillna(0)
        di_m = (sdm_series / str_series * 100).fillna(0)
        
        trend = np.where(di_p - di_m > 2, 1, -1)
        return pd.Series(trend, index=high_series.index)

    def next(self):
        if len(self.data) < self.len + 10:
            return
        
        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        hull_current = self.hull[-1]
        hull_prev1 = self.hull[-2] if len(self.hull) > 1 else hull_current
        hull_prev3 = self.hull[-4] if len(self.hull) > 3 else hull_current
        hull_prev2 = self.hull[-3] if len(self.hull) > 2 else hull_current
        hull_prev4 = self.hull[-5] if len(self.hull) > 4 else hull_current
        
        es_verde = hull_prev1 > hull_prev3
        es_rojo = hull_prev1 < hull_prev3
        
        # Trend change reset
        if (es_rojo and self.hull[-2] <= self.hull[-4]) or (es_verde and self.hull[-2] >= self.hull[-4]):
            self.precio_v2 = None
            self.retroceso_confirmado = False
            self.entrada_realizada = False
        
        # Multi-timeframe trend (simplified - using local trend as proxy)
        mtf_alcista = es_verde
        mtf_bajista = es_rojo
        
        sm_trend = self.sm_trend[-1] if len(self.sm_trend) > 0 else 0
        
        # V2 detection
        es_v2_alcista = es_verde and not (hull_prev2 > hull_prev4) and mtf_alcista and sm_trend == 1
        es_v2_bajista = es_rojo and not (hull_prev2 < hull_prev4) and mtf_bajista and sm_trend == -1
        
        if es_v2_alcista or es_v2_bajista:
            self.precio_v2 = open_
        
        # Retroceso confirmation
        if es_verde and self.precio_v2 is not None and low < self.precio_v2 and close < open_:
            self.retroceso_confirmado = True
        
        if es_rojo and self.precio_v2 is not None and high > self.precio_v2 and close > open_:
            self.retroceso_confirmado = True
        
        # Entry signals
        low_m3 = self.lowest_m3[-1] if len(self.lowest_m3) > 0 else low
        high_m3 = self.highest_m3[-1] if len(self.highest_m3) > 0 else high
        
        definitiva_long = (es_verde and self.retroceso_confirmado and not self.entrada_realizada 
                          and close > open_ and close > hull_current and mtf_alcista and sm_trend == 1)
        
        definitiva_short = (es_rojo and self.retroceso_confirmado and not self.entrada_realizada 
                           and close < open_ and close < hull_current and mtf_bajista and sm_trend == -1)
        
        # Exit existing position
        if self.position:
            self.bars_in_trade += 1
            
            if self.position.is_long and (definitiva_short or self.bars_in_trade > self.line_bars):
                self.position.close()
                self.entrada_realizada = False
            elif self.position.is_short and (definitiva_long or self.bars_in_trade > self.line_bars):
                self.position.close()
                self.entrada_realizada = False
        
        # Entry logic
        if definitiva_long and not self.position:
            sl = low_m3
            risk = abs(close - sl)
            self.buy()
            self.entry_price = close
            self.sl_price = sl
            self.tp_price = close + risk
            self.entrada_realizada = True
            self.bars_in_trade = 0
        
        elif definitiva_short and not self.position:
            sl = high_m3
            risk = abs(close - sl)
            self.sell()
            self.entry_price = close
            self.sl_price = sl
            self.tp_price = close - risk
            self.entrada_realizada = True
            self.bars_in_trade = 0


if __name__ == "__main__":
    bt = Backtest(
        pd.read_csv("data.csv", index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.001
    )
    stats = bt.run()
    print(stats)
    bt.plot()