"""
DS-TV Backtest Results: improved-mcginley-dynamic
============================================================

--- SPY ---
  Return                    11.15%
  Buy & Hold Return         41.94%
  Max Drawdown              -11.64%
  Sharpe Ratio              0.52
  Sortino Ratio             0.75
  Calmar Ratio              0.47
  Profit Factor             1.50
  Expectancy                0.39%
  SQN                       0.56
  # Trades                  30
  Win Rate                  50.00%
  Best Trade                16.70%
  Worst Trade               -3.24%
  Avg Trade                 0.34%
  Exposure Time             81.80%
  Equity Final              111150.18$
  Equity Peak               116084.91$
  Avg Drawdown              -1.93%
  Max Drawdown Duration     343 days 00:00:00
  Max Trade Duration        102 days 00:00:00
  Avg Trade Duration        19 days 00:00:00
  Ann. Return               5.47%
  Ann. Volatility           10.51%

--- BTC ---
  Return                    8.68%
  Buy & Hold Return         46.22%
  Max Drawdown              -30.11%
  Sharpe Ratio              0.16
  Sortino Ratio             0.25
  Calmar Ratio              0.14
  Profit Factor             1.35
  Expectancy                0.70%
  SQN                       0.20
  # Trades                  44
  Win Rate                  22.73%
  Best Trade                52.04%
  Worst Trade               -8.88%
  Avg Trade                 0.32%
  Exposure Time             63.34%
  Equity Final              108679.53$
  Equity Peak               138437.12$
  Avg Drawdown              -7.17%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        72 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               4.24%
  Ann. Volatility           27.32%

--- QQQ ---
  Return                    17.98%
  Buy & Hold Return         42.67%
  Max Drawdown              -14.65%
  Sharpe Ratio              0.59
  Sortino Ratio             0.87
  Calmar Ratio              0.59
  Profit Factor             1.59
  Expectancy                0.59%
  SQN                       0.64
  # Trades                  34
  Win Rate                  38.24%
  Best Trade                22.38%
  Worst Trade               -3.58%
  Avg Trade                 0.49%
  Exposure Time             79.60%
  Equity Final              117976.26$
  Equity Peak               133443.35$
  Avg Drawdown              -2.66%
  Max Drawdown Duration     176 days 00:00:00
  Max Trade Duration        102 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               8.69%
  Ann. Volatility           14.81%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — improved-mcginley-dynamic
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 10

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate McGinley Dynamic indicator
        def mcginley_dynamic(close_series, length):
            md = np.zeros(len(close_series))
            md[0] = close_series.iloc[0]
            
            for i in range(1, len(close_series)):
                if i < length:
                    md[i] = close_series.iloc[:i+1].mean()
                else:
                    src = close_series.iloc[i]
                    md_prev = md[i-1]
                    ratio = src / md_prev if md_prev != 0 else 1.0
                    ratio = max(min(ratio, 2.0), 0.5)
                    md[i] = md_prev + (src - md_prev) / (length * np.power(ratio, 4))
            
            return pd.Series(md, index=close_series.index)
        
        self.md = self.I(mcginley_dynamic, close, self.length)

    def next(self):
        if len(self.data) < 2:
            return
        
        # Buy when price crosses above McGinley Dynamic
        if crossover(self.data.Close, self.md):
            if not self.position:
                self.buy()
        
        # Sell when price crosses below McGinley Dynamic
        elif crossover(self.md, self.data.Close):
            if self.position:
                self.position.close()