"""
DS-TV Backtest Results: its-just-for-study-basis-pls-do-backtest-on-15min-chart-and-apply-on-your-tradin
============================================================

--- SPY ---
  Return                    4.40%
  Buy & Hold Return         17.90%
  Max Drawdown              -13.94%
  Sharpe Ratio              0.18
  Sortino Ratio             0.25
  Calmar Ratio              0.16
  Profit Factor             1.63
  Expectancy                0.59%
  SQN                       0.36
  # Trades                  10
  Win Rate                  40.00%
  Best Trade                13.70%
  Worst Trade               -2.96%
  Avg Trade                 0.50%
  Exposure Time             47.00%
  Equity Final              104395.69$
  Equity Peak               111257.83$
  Avg Drawdown              -5.80%
  Max Drawdown Duration     181 days 00:00:00
  Max Trade Duration        190 days 00:00:00
  Avg Trade Duration        35 days 00:00:00
  Ann. Return               2.19%
  Ann. Volatility           12.40%

--- BTC ---
  Return                    69.68%
  Buy & Hold Return         17.39%
  Max Drawdown              -18.61%
  Sharpe Ratio              0.88
  Sortino Ratio             1.81
  Calmar Ratio              1.62
  Profit Factor             2.64
  Expectancy                3.08%
  SQN                       0.70
  # Trades                  15
  Win Rate                  26.67%
  Best Trade                54.46%
  Worst Trade               -4.76%
  Avg Trade                 2.29%
  Exposure Time             53.08%
  Equity Final              169675.23$
  Equity Peak               176823.19$
  Avg Drawdown              -4.94%
  Max Drawdown Duration     121 days 00:00:00
  Max Trade Duration        117 days 00:00:00
  Avg Trade Duration        26 days 00:00:00
  Ann. Return               30.21%
  Ann. Volatility           34.17%

--- QQQ ---
  Return                    13.88%
  Buy & Hold Return         22.08%
  Max Drawdown              -15.47%
  Sharpe Ratio              0.43
  Sortino Ratio             0.67
  Calmar Ratio              0.44
  Profit Factor             2.34
  Expectancy                1.22%
  SQN                       0.57
  # Trades                  12
  Win Rate                  33.33%
  Best Trade                21.85%
  Worst Trade               -2.49%
  Avg Trade                 1.04%
  Exposure Time             46.60%
  Equity Final              113882.57$
  Equity Peak               128519.41$
  Avg Drawdown              -3.23%
  Max Drawdown Duration     126 days 00:00:00
  Max Trade Duration        194 days 00:00:00
  Avg Trade Duration        29 days 00:00:00
  Ann. Return               6.77%
  Ann. Volatility           15.70%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — its-just-for-study-basis-pls-do-backtest-on-15min-chart-and-apply-on-your-tradin
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    period_dema = 7
    period_atr = 14
    factor_atr = 1.7
    dema_200_period = 200

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate DEMA ATR with bands
        def dema_atr_bands():
            ema1 = pta.ema(close, length=self.period_dema)
            ema2 = pta.ema(ema1, length=self.period_dema)
            dema = 2 * ema1 - ema2
            
            atr = pta.atr(high, low, close, length=self.period_atr)
            atr_adjusted = atr * self.factor_atr
            
            result = pd.Series(index=close.index, dtype=float)
            result.iloc[0] = dema.iloc[0] if not pd.isna(dema.iloc[0]) else np.nan
            
            for i in range(1, len(close)):
                prev_val = result.iloc[i-1]
                dema_val = dema.iloc[i]
                atr_val = atr_adjusted.iloc[i]
                
                if pd.isna(prev_val):
                    result.iloc[i] = dema_val
                elif dema_val - atr_val > prev_val:
                    result.iloc[i] = dema_val - atr_val
                elif dema_val + atr_val < prev_val:
                    result.iloc[i] = dema_val + atr_val
                else:
                    result.iloc[i] = prev_val
            
            return result
        
        self.dema_atr = self.I(dema_atr_bands)
        
        # Calculate 200 DEMA
        def dema_200():
            ema1 = pta.ema(close, length=200)
            ema2 = pta.ema(ema1, length=200)
            return 2 * ema1 - ema2
        
        self.dema_200 = self.I(dema_200)

    def next(self):
        # Buy signal: close crosses above 200 DEMA
        if crossover(self.data.Close, self.dema_200):
            self.buy()
        
        # Sell signal: close crosses below 200 DEMA
        elif crossover(self.dema_200, self.data.Close):
            self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()