"""
DS-TV Backtest Results: ma-cross-table-elite-qqqspy
============================================================

--- SPY ---
  Return                    2.39%
  Buy & Hold Return         17.90%
  Max Drawdown              -16.38%
  Sharpe Ratio              0.12
  Sortino Ratio             0.16
  Calmar Ratio              0.07
  Profit Factor             1.28
  Expectancy                0.86%
  SQN                       0.08
  # Trades                  6
  Win Rate                  50.00%
  Best Trade                22.90%
  Worst Trade               -12.43%
  Avg Trade                 0.32%
  Exposure Time             41.40%
  Equity Final              102386.22$
  Equity Peak               103756.32$
  Avg Drawdown              -3.13%
  Max Drawdown Duration     204 days 00:00:00
  Max Trade Duration        176 days 00:00:00
  Avg Trade Duration        49 days 00:00:00
  Ann. Return               1.20%
  Ann. Volatility           9.66%

--- BTC ---
  Return                    16.35%
  Buy & Hold Return         17.39%
  Max Drawdown              -28.27%
  Sharpe Ratio              0.39
  Sortino Ratio             0.65
  Calmar Ratio              0.28
  Profit Factor             1.88
  Expectancy                2.89%
  SQN                       0.37
  # Trades                  14
  Win Rate                  35.71%
  Best Trade                46.61%
  Worst Trade               -11.82%
  Avg Trade                 2.00%
  Exposure Time             40.90%
  Equity Final              116350.18$
  Equity Peak               161219.24$
  Avg Drawdown              -3.52%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        70 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               7.85%
  Ann. Volatility           20.17%

--- QQQ ---
  Return                    11.39%
  Buy & Hold Return         22.08%
  Max Drawdown              -9.44%
  Sharpe Ratio              0.49
  Sortino Ratio             0.72
  Calmar Ratio              0.59
  Profit Factor             2.11
  Expectancy                1.58%
  SQN                       0.55
  # Trades                  8
  Win Rate                  37.50%
  Best Trade                18.58%
  Worst Trade               -4.21%
  Avg Trade                 1.36%
  Exposure Time             44.40%
  Equity Final              111392.87$
  Equity Peak               120698.06$
  Avg Drawdown              -2.11%
  Max Drawdown Duration     103 days 00:00:00
  Max Trade Duration        127 days 00:00:00
  Avg Trade Duration        39 days 00:00:00
  Ann. Return               5.59%
  Ann. Volatility           11.45%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ma-cross-table-elite-qqqspy
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    bar1_len = 10
    bar2_len = 20
    day1_len = 10
    day2_len = 20
    day3_len = 50
    day4_len = 100
    day5_len = 200
    vol_ma_len = 50
    rsi_len = 14
    ma_type = "SMA"
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Bar-level MAs
        if self.ma_type == "SMA":
            self.ma1b = self.I(pta.sma, close, length=self.bar1_len)
            self.ma2b = self.I(pta.sma, close, length=self.bar2_len)
        else:
            self.ma1b = self.I(pta.ema, close, length=self.bar1_len)
            self.ma2b = self.I(pta.ema, close, length=self.bar2_len)
        
        # Daily MAs (approximated using longer lookback on current timeframe)
        if self.ma_type == "SMA":
            self.ma1d = self.I(pta.sma, close, length=self.day1_len)
            self.ma2d = self.I(pta.sma, close, length=self.day2_len)
            self.ma3d = self.I(pta.sma, close, length=self.day3_len)
            self.ma4d = self.I(pta.sma, close, length=self.day4_len)
            self.ma5d = self.I(pta.sma, close, length=self.day5_len)
        else:
            self.ma1d = self.I(pta.ema, close, length=self.day1_len)
            self.ma2d = self.I(pta.ema, close, length=self.day2_len)
            self.ma3d = self.I(pta.ema, close, length=self.day3_len)
            self.ma4d = self.I(pta.ema, close, length=self.day4_len)
            self.ma5d = self.I(pta.ema, close, length=self.day5_len)
        
        # RSI indicators
        self.rsi_current = self.I(pta.rsi, close, length=self.rsi_len)
        self.rsi1b = self.I(pta.rsi, close, length=self.bar1_len)
        self.rsi2b = self.I(pta.rsi, close, length=self.bar2_len)
        self.rsi1d = self.I(pta.rsi, close, length=self.day1_len)
        self.rsi2d = self.I(pta.rsi, close, length=self.day2_len)
        self.rsi3d = self.I(pta.rsi, close, length=self.day3_len)
        self.rsi4d = self.I(pta.rsi, close, length=self.day4_len)
        self.rsi5d = self.I(pta.rsi, close, length=self.day5_len)
        
        # Volume indicators
        self.vol_ma = self.I(pta.sma, volume, length=self.vol_ma_len)
        
        # ATR
        self.atr = self.I(pta.atr, high, low, close, length=14)
        
    def next(self):
        # Simple MA crossover strategy: buy when fast MA crosses above slow MA
        # Sell when fast MA crosses below slow MA
        
        # Bar-level trading signals
        if crossover(self.ma1b, self.ma2b):
            if not self.position:
                self.buy()
        elif crossover(self.ma2b, self.ma1b):
            if self.position:
                self.position.close()
        
        # Additional confirmation with RSI
        # If RSI is extremely overbought, consider exiting
        if self.position and self.rsi_current[-1] > 85:
            self.position.close()
        
        # If RSI is extremely oversold and we're not in a position, consider buying
        if not self.position and self.rsi_current[-1] < 15 and self.ma1b[-1] > self.ma2b[-1]:
            self.buy()