"""
DS-TV Backtest Results: moving-average-50-400-by-cb
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         5.75%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         -17.18%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         4.17%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — moving-average-50-400-by-cb
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    Length1 = 50
    Length2 = 100
    Length3 = 200
    Length4 = 300
    Length5 = 400

    def init(self):
        close = pd.Series(self.data.Close)
        
        self.ma50 = self.I(pta.sma, close, length=self.Length1)
        self.ma100 = self.I(pta.sma, close, length=self.Length2)
        self.ma200 = self.I(pta.sma, close, length=self.Length3)
        self.ma300 = self.I(pta.sma, close, length=self.Length4)
        self.ma400 = self.I(pta.sma, close, length=self.Length5)

    def next(self):
        if len(self.data) < self.Length5:
            return
        
        close = self.data.Close[-1]
        
        ma50_val = self.ma50[-1]
        ma100_val = self.ma100[-1]
        ma200_val = self.ma200[-1]
        ma300_val = self.ma300[-1]
        ma400_val = self.ma400[-1]
        
        ma50_prev = self.ma50[-2] if len(self.ma50) > 1 else ma50_val
        ma100_prev = self.ma100[-2] if len(self.ma100) > 1 else ma100_val
        
        if not self.position:
            if (crossover(self.ma50, self.ma100) and 
                ma50_val > ma200_val and 
                ma100_val > ma300_val and
                ma200_val > ma400_val):
                self.buy()
        else:
            if (crossover(self.ma100, self.ma50) or 
                close < ma200_val):
                self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()