"""
DS-TV Backtest Results: msj-ema
============================================================

--- SPY ---
  Return                    5.05%
  Buy & Hold Return         17.90%
  Max Drawdown              -17.25%
  Sharpe Ratio              0.21
  Sortino Ratio             0.27
  Calmar Ratio              0.15
  Profit Factor             0.00
  Expectancy                -12.03%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -12.03%
  Worst Trade               -12.03%
  Avg Trade                 -12.03%
  Exposure Time             5.80%
  Equity Final              105051.19$
  Equity Peak               105283.73$
  Avg Drawdown              -7.44%
  Max Drawdown Duration     279 days 00:00:00
  Max Trade Duration        41 days 00:00:00
  Avg Trade Duration        41 days 00:00:00
  Ann. Return               2.51%
  Ann. Volatility           12.02%

--- BTC ---
  Return                    -7.17%
  Buy & Hold Return         17.39%
  Max Drawdown              -27.35%
  Sharpe Ratio              -0.17
  Sortino Ratio             -0.24
  Calmar Ratio              -0.13
  Profit Factor             0.73
  Expectancy                -2.16%
  SQN                       -0.30
  # Trades                  4
  Win Rate                  25.00%
  Best Trade                22.95%
  Worst Trade               -13.68%
  Avg Trade                 -3.16%
  Exposure Time             28.32%
  Equity Final              92833.11$
  Equity Peak               127777.94$
  Avg Drawdown              -7.14%
  Max Drawdown Duration     385 days 00:00:00
  Max Trade Duration        152 days 00:00:00
  Avg Trade Duration        52 days 00:00:00
  Ann. Return               -3.65%
  Ann. Volatility           21.61%

--- QQQ ---
  Return                    9.83%
  Buy & Hold Return         22.08%
  Max Drawdown              -19.72%
  Sharpe Ratio              0.33
  Sortino Ratio             0.47
  Calmar Ratio              0.25
  Profit Factor             0.00
  Expectancy                -7.86%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -7.86%
  Worst Trade               -7.86%
  Avg Trade                 -7.86%
  Exposure Time             6.80%
  Equity Final              109829.33$
  Equity Peak               113501.82$
  Avg Drawdown              -7.31%
  Max Drawdown Duration     204 days 00:00:00
  Max Trade Duration        48 days 00:00:00
  Avg Trade Duration        48 days 00:00:00
  Ann. Return               4.84%
  Ann. Volatility           14.66%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — msj-ema
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fastLength = 20
    slowLength = 200

    def init(self):
        close = pd.Series(self.data.Close)
        self.emaFast = self.I(pta.ema, close, length=self.fastLength)
        self.emaSlow = self.I(pta.ema, close, length=self.slowLength)

    def next(self):
        if crossover(self.emaFast, self.emaSlow):
            self.buy()
        elif crossover(self.emaSlow, self.emaFast):
            self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()