"""
DS-TV Backtest Results: multi-signal-trading-indicator-fvg-liquidity-jamil
============================================================

--- SPY ---
  Return                    -19.07%
  Buy & Hold Return         17.90%
  Max Drawdown              -28.64%
  Sharpe Ratio              -0.87
  Sortino Ratio             -1.10
  Calmar Ratio              -0.35
  Profit Factor             0.00
  Expectancy                -4.60%
  SQN                       -1.76
  # Trades                  4
  Win Rate                  0.00%
  Best Trade                -1.22%
  Worst Trade               -12.07%
  Avg Trade                 -4.71%
  Exposure Time             55.60%
  Equity Final              80932.06$
  Equity Peak               113208.63$
  Avg Drawdown              -6.67%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        266 days 00:00:00
  Avg Trade Duration        102 days 00:00:00
  Ann. Return               -10.11%
  Ann. Volatility           11.66%

--- BTC ---
  Return                    -31.91%
  Buy & Hold Return         17.39%
  Max Drawdown              -48.32%
  Sharpe Ratio              -0.89
  Sortino Ratio             -1.01
  Calmar Ratio              -0.36
  Profit Factor             0.00
  Expectancy                -26.34%
  SQN                       -0.99
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                0.25%
  Worst Trade               -52.93%
  Avg Trade                 -31.31%
  Exposure Time             15.73%
  Equity Final              68086.40$
  Equity Peak               105518.34$
  Avg Drawdown              -16.58%
  Max Drawdown Duration     500 days 00:00:00
  Max Trade Duration        92 days 00:00:00
  Avg Trade Duration        57 days 00:00:00
  Ann. Return               -17.46%
  Ann. Volatility           19.56%

--- QQQ ---
  Return                    -20.36%
  Buy & Hold Return         22.08%
  Max Drawdown              -35.65%
  Sharpe Ratio              -0.75
  Sortino Ratio             -0.96
  Calmar Ratio              -0.30
  Profit Factor             0.07
  Expectancy                -3.77%
  SQN                       -1.17
  # Trades                  5
  Win Rate                  20.00%
  Best Trade                1.32%
  Worst Trade               -16.38%
  Avg Trade                 -4.00%
  Exposure Time             54.20%
  Equity Final              79636.55$
  Equity Peak               117464.18$
  Avg Drawdown              -6.16%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        264 days 00:00:00
  Avg Trade Duration        79 days 00:00:00
  Ann. Return               -10.84%
  Ann. Volatility           14.45%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — multi-signal-trading-indicator-fvg-liquidity-jamil
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Trend Settings
    emaFastLen = 9
    emaSlowLen = 21
    trendLen = 50
    ema200Len = 200
    
    # Momentum Settings
    rsiLen = 14
    rsiOverbought = 70
    rsiOversold = 30
    
    # Volume Settings
    volLen = 20
    volMultiplier = 1.5
    
    # FVG Settings
    fvgWidth = 3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate EMAs
        self.emaFast = self.I(pta.ema, close, length=self.emaFastLen)
        self.emaSlow = self.I(pta.ema, close, length=self.emaSlowLen)
        self.emaTrend = self.I(pta.ema, close, length=self.trendLen)
        self.ema200 = self.I(pta.ema, close, length=self.ema200Len)
        
        # Calculate RSI
        self.rsi = self.I(pta.rsi, close, length=self.rsiLen)
        
        # Volume Analysis
        self.volMA = self.I(pta.sma, volume, length=self.volLen)
        
        # Pivot Points for liquidity levels
        self.major_high = self.I(self._pivot_high, high, length=20)
        self.major_low = self.I(self._pivot_low, low, length=20)
        self.minor_high = self.I(self._pivot_high, high, length=10)
        self.minor_low = self.I(self._pivot_low, low, length=10)

    def _pivot_high(self, data, length):
        result = pd.Series(np.nan, index=data.index)
        for i in range(length, len(data) - length):
            if data.iloc[i] == data.iloc[i-length:i].max() and data.iloc[i] == data.iloc[i+1:i+length+1].max():
                result.iloc[i] = data.iloc[i]
        return result

    def _pivot_low(self, data, length):
        result = pd.Series(np.nan, index=data.index)
        for i in range(length, len(data) - length):
            if data.iloc[i] == data.iloc[i-length:i].min() and data.iloc[i] == data.iloc[i+1:i+length+1].min():
                result.iloc[i] = data.iloc[i]
        return result

    def next(self):
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        
        if len(self.data) < self.ema200Len + 5:
            return
        
        emaFastVal = self.emaFast[-1]
        emaSlowVal = self.emaSlow[-1]
        emaTrendVal = self.emaTrend[-1]
        ema200Val = self.ema200[-1]
        rsiVal = self.rsi[-1]
        volMAVal = self.volMA[-1]
        
        if pd.isna(emaFastVal) or pd.isna(emaSlowVal) or pd.isna(emaTrendVal) or pd.isna(rsiVal):
            return
        
        # Trend Detection
        bullishTrend = close > emaTrendVal
        bearishTrend = close < emaTrendVal
        
        # Volume Spike
        volSpike = volume > volMAVal * self.volMultiplier
        
        # Buy Signal: Fast EMA crosses above Slow EMA, price above trend, RSI not overbought
        buySignal = crossover(self.emaFast, self.emaSlow) and bullishTrend and rsiVal < self.rsiOverbought
        strongBuy = buySignal and volSpike
        
        # Sell Signal: Fast EMA crosses below Slow EMA, price below trend, RSI not oversold
        sellSignal = crossover(self.emaSlow, self.emaFast) and bearishTrend and rsiVal > self.rsiOversold
        strongSell = sellSignal and volSpike
        
        # FVG Detection (simplified for backtest)
        if len(self.data) >= 3:
            low_curr = self.data.Low[-1]
            high_2bars = self.data.High[-3]
            low_2bars = self.data.Low[-3]
            high_curr = self.data.High[-1]
            close_1bar = self.data.Close[-2]
            open_1bar = self.data.Open[-2]
            
            bullishFVG = (low_curr > high_2bars) and (close_1bar > open_1bar)
            bearishFVG = (high_curr < low_2bars) and (close_1bar < open_1bar)
            
            # FVG can provide additional confirmation
            if bullishFVG and buySignal:
                strongBuy = True
            if bearishFVG and sellSignal:
                strongSell = True
        
        # Trading Logic
        if strongBuy or buySignal:
            if not self.position:
                self.buy()
        elif strongSell or sellSignal:
            if self.position:
                self.sell()


if __name__ == "__main__":
    import yfinance as yf
    
    # Download sample data
    data = yf.download("AAPL", start="2023-01-01", end="2024-01-01", interval="1d")
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()