"""
DS-TV Backtest Results: multi-higher-time-frame-m-htf-ema-ukutalabs
============================================================

--- SPY ---
  Return                    -28.41%
  Buy & Hold Return         18.09%
  Max Drawdown              -28.43%
  Sharpe Ratio              -1.38
  Sortino Ratio             -1.66
  Calmar Ratio              -0.55
  Profit Factor             0.00
  Expectancy                -2.83%
  SQN                       -1.90
  # Trades                  11
  Win Rate                  9.09%
  Best Trade                0.14%
  Worst Trade               -16.13%
  Avg Trade                 -2.94%
  Exposure Time             43.80%
  Equity Final              71594.15$
  Equity Peak               100000.00$
  Avg Drawdown              -28.43%
  Max Drawdown Duration     320 days 00:00:00
  Max Trade Duration        102 days 00:00:00
  Avg Trade Duration        29 days 00:00:00
  Ann. Return               -15.50%
  Ann. Volatility           11.27%

--- BTC ---
  Return                    -28.08%
  Buy & Hold Return         2.83%
  Max Drawdown              -36.38%
  Sharpe Ratio              -1.02
  Sortino Ratio             -1.11
  Calmar Ratio              -0.42
  Profit Factor             0.05
  Expectancy                -20.22%
  SQN                       -0.91
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                2.08%
  Worst Trade               -42.51%
  Avg Trade                 -23.39%
  Exposure Time             6.98%
  Equity Final              71924.71$
  Equity Peak               101480.58$
  Avg Drawdown              -36.38%
  Max Drawdown Duration     462 days 00:00:00
  Max Trade Duration        49 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               -15.17%
  Ann. Volatility           14.91%

--- QQQ ---
  Return                    -36.09%
  Buy & Hold Return         19.99%
  Max Drawdown              -37.85%
  Sharpe Ratio              -1.61
  Sortino Ratio             -1.86
  Calmar Ratio              -0.53
  Profit Factor             0.04
  Expectancy                -3.37%
  SQN                       -1.95
  # Trades                  13
  Win Rate                  23.08%
  Best Trade                1.10%
  Worst Trade               -21.43%
  Avg Trade                 -3.55%
  Exposure Time             43.00%
  Equity Final              63906.12$
  Equity Peak               100000.00$
  Avg Drawdown              -37.85%
  Max Drawdown Duration     320 days 00:00:00
  Max Trade Duration        102 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               -20.20%
  Ann. Volatility           12.59%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — multi-higher-time-frame-m-htf-ema-ukutalabs
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    period = 21
    input_source = "Close"
    display_5 = True
    display_15 = False
    display_30 = False
    display_60 = False
    display_120 = False
    display_240 = False
    display_daily = False

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema_close = self.I(pta.ema, close, length=self.period)
        self.ema_open = self.I(pta.ema, open_, length=self.period)
        self.ema_high = self.I(pta.ema, high, length=self.period)
        self.ema_low = self.I(pta.ema, low, length=self.period)
        
        self.htf_5_close = self.I(self._calculate_htf_ema, close, 5)
        self.htf_15_close = self.I(self._calculate_htf_ema, close, 15)
        self.htf_30_close = self.I(self._calculate_htf_ema, close, 30)
        self.htf_60_close = self.I(self._calculate_htf_ema, close, 60)
        self.htf_120_close = self.I(self._calculate_htf_ema, close, 120)
        self.htf_240_close = self.I(self._calculate_htf_ema, close, 240)
        self.htf_daily_close = self.I(self._calculate_htf_ema, close, 1440)

    def _calculate_htf_ema(self, series, timeframe_minutes):
        result = pd.Series(np.nan, index=series.index)
        
        bars_per_htf = max(1, timeframe_minutes // 1)
        
        for i in range(len(series)):
            if i < self.period + bars_per_htf - 1:
                continue
            
            start_idx = max(0, i - bars_per_htf + 1)
            end_idx = i + 1
            
            segment = series.iloc[start_idx:end_idx]
            
            if len(segment) >= self.period:
                ema_val = pta.ema(segment, length=self.period)
                if ema_val is not None and len(ema_val) > 0:
                    result.iloc[i] = ema_val.iloc[-1]
        
        return result

    def next(self):
        current_close = self.data.Close[-1]
        current_ema = self.ema_close[-1]
        
        htf_signals = []
        
        if self.display_5 and not np.isnan(self.htf_5_close[-1]):
            if current_close > self.htf_5_close[-1]:
                htf_signals.append(1)
            elif current_close < self.htf_5_close[-1]:
                htf_signals.append(-1)
        
        if self.display_15 and not np.isnan(self.htf_15_close[-1]):
            if current_close > self.htf_15_close[-1]:
                htf_signals.append(1)
            elif current_close < self.htf_15_close[-1]:
                htf_signals.append(-1)
        
        if self.display_30 and not np.isnan(self.htf_30_close[-1]):
            if current_close > self.htf_30_close[-1]:
                htf_signals.append(1)
            elif current_close < self.htf_30_close[-1]:
                htf_signals.append(-1)
        
        if self.display_60 and not np.isnan(self.htf_60_close[-1]):
            if current_close > self.htf_60_close[-1]:
                htf_signals.append(1)
            elif current_close < self.htf_60_close[-1]:
                htf_signals.append(-1)
        
        if self.display_120 and not np.isnan(self.htf_120_close[-1]):
            if current_close > self.htf_120_close[-1]:
                htf_signals.append(1)
            elif current_close < self.htf_120_close[-1]:
                htf_signals.append(-1)
        
        if self.display_240 and not np.isnan(self.htf_240_close[-1]):
            if current_close > self.htf_240_close[-1]:
                htf_signals.append(1)
            elif current_close < self.htf_240_close[-1]:
                htf_signals.append(-1)
        
        if self.display_daily and not np.isnan(self.htf_daily_close[-1]):
            if current_close > self.htf_daily_close[-1]:
                htf_signals.append(1)
            elif current_close < self.htf_daily_close[-1]:
                htf_signals.append(-1)
        
        if len(htf_signals) > 0:
            signal_sum = sum(htf_signals)
            
            if signal_sum > 0 and not self.position:
                self.buy()
            elif signal_sum < 0 and self.position:
                self.sell()
        
        if len(self.data) > self.period + 1:
            if crossover(self.ema_close, self.data.Close):
                if not self.position:
                    self.buy()
            elif crossover(self.data.Close, self.ema_close):
                if self.position:
                    self.sell()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("AAPL", start="2020-01-01", end="2023-12-31", interval="1d")
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()