"""
DS-TV Backtest Results: nested-sma-conditional-bands
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(640)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "sma(1280)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(640)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — nested-sma-conditional-bands
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Default parameters from the Pine Script
    mult_preset = "1/2"
    manual_fine = 1.0
    offset_mode = "Points"
    base_length = 20
    shade1 = True
    shade2 = True
    shade3 = True
    shade4 = True
    shade5 = True
    shade6 = True
    shade7 = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # Determine multiplier
        mult_map = {
            "1/1024": 1.0 / 1024,
            "1/512": 1.0 / 512,
            "1/256": 1.0 / 256,
            "1/128": 1.0 / 128,
            "1/64": 1.0 / 64,
            "1/32": 1.0 / 32,
            "1/16": 1.0 / 16,
            "1/8": 1.0 / 8,
            "1/4": 1.0 / 4,
            "1/2": 1.0 / 2,
            "1": 1.0,
            "2": 2.0,
            "4": 4.0,
            "8": 8.0,
            "16": 16.0,
            "32": 32.0,
            "64": 64.0,
            "128": 128.0,
            "256": 256.0,
            "512": 512.0,
            "1024": 1024.0,
        }
        mult_base = mult_map.get(self.mult_preset, 1.0)
        final_mult = mult_base * self.manual_fine

        # Calculate deviation
        if self.offset_mode == "Points":
            deviation = 0.305176 * final_mult
        else:
            deviation = close * (0.00625 / 100) * final_mult

        # Calculate lengths
        len1 = self.base_length
        len2 = self.base_length * 2
        len3 = self.base_length * 4
        len4 = self.base_length * 8
        len5 = self.base_length * 16
        len6 = self.base_length * 32
        len7 = self.base_length * 64
        len8 = self.base_length * 128

        # Calculate moving averages
        self.ma1 = self.I(pta.sma, close, length=len1)
        self.ma2 = self.I(pta.sma, close, length=len2)
        self.ma3 = self.I(pta.sma, close, length=len3)
        self.ma4 = self.I(pta.sma, close, length=len4)
        self.ma5 = self.I(pta.sma, close, length=len5)
        self.ma6 = self.I(pta.sma, close, length=len6)
        self.ma7 = self.I(pta.sma, close, length=len7)
        self.ma8 = self.I(pta.sma, close, length=len8)

        # Store deviation as series for calculations
        self.deviation = self.I(lambda: pd.Series(deviation, index=close.index))

        # Calculate envelopes
        self.u1 = self.I(lambda: self.ma1 + self.deviation * 1)
        self.l1 = self.I(lambda: self.ma1 - self.deviation * 1)
        self.u2 = self.I(lambda: self.ma2 + self.deviation * 2)
        self.l2 = self.I(lambda: self.ma2 - self.deviation * 2)
        self.u3 = self.I(lambda: self.ma3 + self.deviation * 4)
        self.l3 = self.I(lambda: self.ma3 - self.deviation * 4)
        self.u4 = self.I(lambda: self.ma4 + self.deviation * 8)
        self.l4 = self.I(lambda: self.ma4 - self.deviation * 8)
        self.u5 = self.I(lambda: self.ma5 + self.deviation * 16)
        self.l5 = self.I(lambda: self.ma5 - self.deviation * 16)
        self.u6 = self.I(lambda: self.ma6 + self.deviation * 32)
        self.l6 = self.I(lambda: self.ma6 - self.deviation * 32)
        self.u7 = self.I(lambda: self.ma7 + self.deviation * 64)
        self.l7 = self.I(lambda: self.ma7 - self.deviation * 64)
        self.u8 = self.I(lambda: self.ma8 + self.deviation * 128)
        self.l8 = self.I(lambda: self.ma8 - self.deviation * 128)

        # Calculate quartiles
        self.upper_quartile1 = self.I(lambda: self.ma1 + (self.u1 - self.ma1) * 0.75)
        self.lower_quartile1 = self.I(lambda: self.ma1 + (self.l1 - self.ma1) * 0.25)
        self.upper_quartile2 = self.I(lambda: self.ma2 + (self.u2 - self.ma2) * 0.75)
        self.lower_quartile2 = self.I(lambda: self.ma2 + (self.l2 - self.ma2) * 0.25)
        self.upper_quartile3 = self.I(lambda: self.ma3 + (self.u3 - self.ma3) * 0.75)
        self.lower_quartile3 = self.I(lambda: self.ma3 + (self.l3 - self.ma3) * 0.25)
        self.upper_quartile4 = self.I(lambda: self.ma4 + (self.u4 - self.ma4) * 0.75)
        self.lower_quartile4 = self.I(lambda: self.ma4 + (self.l4 - self.ma4) * 0.25)
        self.upper_quartile5 = self.I(lambda: self.ma5 + (self.u5 - self.ma5) * 0.75)
        self.lower_quartile5 = self.I(lambda: self.ma5 + (self.l5 - self.ma5) * 0.25)
        self.upper_quartile6 = self.I(lambda: self.ma6 + (self.u6 - self.ma6) * 0.75)
        self.lower_quartile6 = self.I(lambda: self.ma6 + (self.l6 - self.ma6) * 0.25)
        self.upper_quartile7 = self.I(lambda: self.ma7 + (self.u7 - self.ma7) * 0.75)
        self.lower_quartile7 = self.I(lambda: self.ma7 + (self.l7 - self.ma7) * 0.25)
        self.upper_quartile8 = self.I(lambda: self.ma8 + (self.u8 - self.ma8) * 0.75)
        self.lower_quartile8 = self.I(lambda: self.ma8 + (self.l8 - self.ma8) * 0.25)

        # Store high/low for condition checks
        self.high_series = high
        self.low_series = low

    def next(self):
        # Get current values
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]

        # Check conditions for each level
        up1 = current_high > self.upper_quartile1[-1]
        dn1 = current_low < self.lower_quartile1[-1]
        up2 = current_high > self.upper_quartile2[-1]
        dn2 = current_low < self.lower_quartile2[-1]
        up3 = current_high > self.upper_quartile3[-1]
        dn3 = current_low < self.lower_quartile3[-1]
        up4 = current_high > self.upper_quartile4[-1]
        dn4 = current_low < self.lower_quartile4[-1]
        up5 = current_high > self.upper_quartile5[-1]
        dn5 = current_low < self.lower_quartile5[-1]
        up6 = current_high > self.upper_quartile6[-1]
        dn6 = current_low < self.lower_quartile6[-1]
        up7 = current_high > self.upper_quartile7[-1]
        dn7 = current_low < self.lower_quartile7[-1]
        up8 = current_high > self.upper_quartile8[-1]
        dn8 = current_low < self.lower_quartile8[-1]

        # Count how many levels are triggered
        up_count = sum([up1, up2, up3, up4, up5, up6, up7, up8])
        dn_count = sum([dn1, dn2, dn3, dn4, dn5, dn6, dn7, dn8])

        # Trading logic: buy when multiple upper quartiles are broken, sell when multiple lower quartiles are broken
        if up_count >= 3 and not self.position:
            self.buy()
        elif dn_count >= 3 and self.position:
            self.sell()