"""
DS-TV Backtest Results: orcb-opening-range-candle-break
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — orcb-opening-range-candle-break
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime, timedelta


class TvStrategy(Strategy):
    # Opening Range Settings
    or_start_hour = 7
    or_start_min = 0
    or_end_hour = 8
    or_end_min = 0
    
    # Trade Settings
    sl_buffer = 0.25
    rr_ratio = 2.0
    
    # EMA Settings
    ema_fast_len = 8
    ema_slow_len = 20
    
    # Overnight Settings
    on_start_hour = 0
    on_start_min = 0
    on_end_hour = 7
    on_end_min = 0
    
    # Previous Day Settings
    show_pdhl = False
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate EMAs
        self.ema_fast = self.I(pta.ema, close, length=self.ema_fast_len)
        self.ema_slow = self.I(pta.ema, close, length=self.ema_slow_len)
        
        # Track state variables
        self.or_high = None
        self.or_low = None
        self.or_done = False
        self.trade_fired = False
        self.last_date = None
        self.entry_price = None
        self.sl_price = None
        self.tp_price = None
        
    def next(self):
        # Get current bar time
        current_time = self.data.index[-1]
        current_date = current_time.date()
        current_hour = current_time.hour
        current_min = current_time.minute
        current_mins = current_hour * 60 + current_min
        
        # Reset daily variables
        if self.last_date != current_date:
            self.last_date = current_date
            self.or_high = None
            self.or_low = None
            self.or_done = False
            self.trade_fired = False
            self.entry_price = None
            self.sl_price = None
            self.tp_price = None
        
        # Define OR window
        or_start_mins = self.or_start_hour * 60 + self.or_start_min
        or_end_mins = self.or_end_hour * 60 + self.or_end_min
        in_or_window = current_mins >= or_start_mins and current_mins < or_end_mins
        
        # Track Opening Range
        if in_or_window:
            if self.or_high is None:
                self.or_high = self.data.High[-1]
                self.or_low = self.data.Low[-1]
            else:
                self.or_high = max(self.or_high, self.data.High[-1])
                self.or_low = min(self.or_low, self.data.Low[-1])
        elif not in_or_window and self.or_high is not None and not self.or_done:
            self.or_done = True
        
        # Check for breaks after OR is done
        if self.or_done and not self.trade_fired and len(self) > 1:
            ema_bullish = self.ema_fast[-1] > self.ema_slow[-1]
            ema_bearish = self.ema_fast[-1] < self.ema_slow[-1]
            
            # Long break: close above OR high with bullish EMA
            if self.data.Close[-1] > self.or_high and ema_bullish:
                self.trade_fired = True
                self.entry_price = self.data.Close[-1]
                self.sl_price = self.or_low - self.sl_buffer
                risk = self.entry_price - self.sl_price
                self.tp_price = self.entry_price + risk * self.rr_ratio
                
                self.buy()
            
            # Short break: close below OR low with bearish EMA
            elif self.data.Close[-1] < self.or_low and ema_bearish:
                self.trade_fired = True
                self.entry_price = self.data.Close[-1]
                self.sl_price = self.or_high + self.sl_buffer
                risk = self.sl_price - self.entry_price
                self.tp_price = self.entry_price - risk * self.rr_ratio
                
                self.sell()
        
        # Exit logic
        if self.position:
            if self.position.is_long:
                # Exit long on TP or SL
                if self.data.Close[-1] >= self.tp_price or self.data.Close[-1] <= self.sl_price:
                    self.position.close()
            else:
                # Exit short on TP or SL
                if self.data.Close[-1] <= self.tp_price or self.data.Close[-1] >= self.sl_price:
                    self.position.close()


if __name__ == '__main__':
    # Load data
    df = pd.read_csv('data.csv', parse_dates=True, index_col=0)
    df.columns = ['Open', 'High', 'Low', 'Close', 'Volume']
    
    # Run backtest
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()