"""
DS-TV Backtest Results: pocket-entry-l
============================================================

--- SPY ---
  Return                    -63.01%
  Buy & Hold Return         32.59%
  Max Drawdown              -63.11%
  Sharpe Ratio              -4.22
  Sortino Ratio             -3.15
  Calmar Ratio              -0.62
  Profit Factor             0.48
  Expectancy                -0.27%
  SQN                       -3.96
  # Trades                  356
  Win Rate                  33.43%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.28%
  Exposure Time             74.60%
  Equity Final              36985.88$
  Equity Peak               100264.10$
  Avg Drawdown              -63.11%
  Max Drawdown Duration     543 days 00:00:00
  Max Trade Duration        6 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -39.43%
  Ann. Volatility           9.35%

--- BTC ---
  Return                    -9.94%
  Buy & Hold Return         9.41%
  Max Drawdown              -15.21%
  Sharpe Ratio              -0.66
  Sortino Ratio             -0.75
  Calmar Ratio              -0.33
  Profit Factor             0.46
  Expectancy                -1.41%
  SQN                       -0.85
  # Trades                  8
  Win Rate                  25.00%
  Best Trade                8.84%
  Worst Trade               -10.44%
  Avg Trade                 -1.54%
  Exposure Time             1.23%
  Equity Final              90056.90$
  Equity Peak               106211.22$
  Avg Drawdown              -15.21%
  Max Drawdown Duration     461 days 00:00:00
  Max Trade Duration        1 days 00:00:00
  Avg Trade Duration        1 days 00:00:00
  Ann. Return               -5.09%
  Ann. Volatility           7.72%

--- QQQ ---
  Return                    -64.89%
  Buy & Hold Return         33.82%
  Max Drawdown              -66.01%
  Sharpe Ratio              -3.65
  Sortino Ratio             -2.73
  Calmar Ratio              -0.62
  Profit Factor             0.56
  Expectancy                -0.28%
  SQN                       -3.38
  # Trades                  355
  Win Rate                  35.77%
  Best Trade                6.54%
  Worst Trade               -9.35%
  Avg Trade                 -0.29%
  Exposure Time             74.60%
  Equity Final              35109.09$
  Equity Peak               101992.47$
  Avg Drawdown              -34.49%
  Max Drawdown Duration     521 days 00:00:00
  Max Trade Duration        5 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -40.99%
  Ann. Volatility           11.24%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — pocket-entry-l
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    upper_ma_len = 80
    main_ma_len = 20
    lower_ma_len = 4
    near_threshold = 0.13
    ma_gap_threshold = 0.05

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        self.ma_red = self.I(pta.sma, close, length=self.upper_ma_len)
        self.ma_blue = self.I(pta.sma, close, length=self.main_ma_len)
        self.ma_white = self.I(pta.sma, close, length=self.lower_ma_len)

        self.close_series = close
        self.open_series = open_
        self.high_series = high
        self.low_series = low

    def next(self):
        if len(self.data) < max(self.upper_ma_len, self.main_ma_len, self.lower_ma_len) + 2:
            return

        idx = len(self.data) - 1

        close = self.close_series.iloc[idx]
        open_ = self.open_series.iloc[idx]
        high = self.high_series.iloc[idx]
        low = self.low_series.iloc[idx]

        close_prev = self.close_series.iloc[idx - 1]
        open_prev = self.open_series.iloc[idx - 1]
        low_prev = self.low_series.iloc[idx - 2]

        ma_red = self.ma_red[-1]
        ma_blue = self.ma_blue[-1]
        ma_white = self.ma_white[-1]
        ma_red_prev = self.ma_red[-2]

        if ma_red is None or ma_blue is None or ma_white is None:
            return

        tf_4h_low_current = low_prev
        tf_4h_low_prev = low_prev
        is_4h_low_up = tf_4h_low_current >= (tf_4h_low_prev * 0.999)

        ma_gap = abs(ma_red - ma_blue) / ma_red * 100
        is_perfect_order = ma_red < ma_blue
        is_near_cross = ma_red >= ma_blue and ma_gap <= self.ma_gap_threshold

        is_red_not_down = ma_red >= (ma_red_prev * 0.9999)
        is_trend_up = (is_perfect_order or is_near_cross) and is_red_not_down and is_4h_low_up

        dist_close = abs(close - ma_blue) / ma_blue * 100
        dist_low = abs(low - ma_blue) / ma_blue * 100
        is_break_through = open_ < ma_blue and close > ma_blue
        is_near_blue = (dist_close <= self.near_threshold or
                        dist_low <= (self.near_threshold * 0.7) or
                        is_break_through)

        body_high = max(open_, close)
        body_low = min(open_, close)
        body_size = body_high - body_low

        if body_size < 1e-10:
            body_above_blue = 0
        else:
            body_above_blue = body_high - max(body_low, ma_blue)
            is_min_body_above = (body_above_blue / body_size) >= (0.1 if is_break_through else 0.3)

        is_price_conquer_mas = close > ma_white and close > ma_blue

        prev_body_high = max(open_prev, close_prev)
        is_break_prev_body = close >= prev_body_high

        raw_condition = (is_trend_up and is_near_blue and is_min_body_above and
                         is_price_conquer_mas and is_break_prev_body)

        if raw_condition and not self.position:
            self.buy()
        elif self.position and not raw_condition:
            self.sell()