"""
DS-TV Backtest Results: psy-levels-pivot-ema-v2-nifty-banknifty-by-lazyhacker
============================================================

--- SPY ---
  Return                    22.05%
  Buy & Hold Return         38.81%
  Max Drawdown              -7.20%
  Sharpe Ratio              1.03
  Sortino Ratio             1.60
  Calmar Ratio              1.47
  Profit Factor             4.79
  Expectancy                2.77%
  SQN                       0.99
  # Trades                  8
  Win Rate                  37.50%
  Best Trade                21.09%
  Worst Trade               -1.85%
  Avg Trade                 2.53%
  Exposure Time             70.60%
  Equity Final              122054.55$
  Equity Peak               127840.54$
  Avg Drawdown              -1.19%
  Max Drawdown Duration     304 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        63 days 00:00:00
  Ann. Return               10.57%
  Ann. Volatility           10.24%

--- BTC ---
  Return                    12.23%
  Buy & Hold Return         35.44%
  Max Drawdown              -20.24%
  Sharpe Ratio              0.25
  Sortino Ratio             0.42
  Calmar Ratio              0.29
  Profit Factor             1.52
  Expectancy                1.69%
  SQN                       0.29
  # Trades                  17
  Win Rate                  29.41%
  Best Trade                51.06%
  Worst Trade               -8.91%
  Avg Trade                 0.86%
  Exposure Time             47.33%
  Equity Final              112226.76$
  Equity Peak               131319.21$
  Avg Drawdown              -6.27%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        70 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               5.93%
  Ann. Volatility           23.47%

--- QQQ ---
  Return                    24.80%
  Buy & Hold Return         39.88%
  Max Drawdown              -12.81%
  Sharpe Ratio              0.84
  Sortino Ratio             1.30
  Calmar Ratio              0.92
  Profit Factor             2.73
  Expectancy                2.63%
  SQN                       0.74
  # Trades                  10
  Win Rate                  50.00%
  Best Trade                28.24%
  Worst Trade               -4.76%
  Avg Trade                 2.25%
  Exposure Time             69.60%
  Equity Final              124799.18$
  Equity Peak               143132.02$
  Avg Drawdown              -2.00%
  Max Drawdown Duration     159 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        50 days 00:00:00
  Ann. Return               11.81%
  Ann. Volatility           14.12%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — psy-levels-pivot-ema-v2-nifty-banknifty-by-lazyhacker
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Chart-based EMA parameters
    cEma1Len = 9
    cEma2Len = 15
    
    # HTF EMA parameters (simulated with chart-based since HTF not available in backtest)
    hEma1Len = 9
    hEma2Len = 15
    
    # PSY Levels
    baseLevel = 56600
    levels = 10
    minorStep = 250
    
    # Fibonacci
    fibSession = True
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Chart-based EMAs
        self.cEma1 = self.I(pta.ema, close, length=self.cEma1Len)
        self.cEma2 = self.I(pta.ema, close, length=self.cEma2Len)
        
        # HTF EMAs (simulated with chart EMAs)
        self.hEma1 = self.I(pta.ema, close, length=self.hEma1Len)
        self.hEma2 = self.I(pta.ema, close, length=self.hEma2Len)
        
        # Previous day values
        self.prevClose = self.I(lambda: close.shift(1))
    
    def next(self):
        # Simple trading logic based on EMA crossovers
        # Buy when fast EMA crosses above slow EMA
        if len(self.cEma1) > 1 and len(self.cEma2) > 1:
            if crossover(self.cEma1, self.cEma2):
                if not self.position:
                    self.buy()
            
            # Sell when fast EMA crosses below slow EMA
            elif crossover(self.cEma2, self.cEma1):
                if self.position:
                    self.position.close()
        
        # Alternative: Use HTF EMAs for confirmation
        if len(self.hEma1) > 1 and len(self.hEma2) > 1:
            # If already in position from chart EMA, hold or exit based on HTF
            if self.position:
                # Exit if HTF shows weakness
                if self.hEma1[-1] < self.hEma2[-1]:
                    self.position.close()


if __name__ == "__main__":
    # Load data - replace with your actual data source
    # Example using yfinance for testing
    try:
        import yfinance as yf
        data = yf.download("NIFTYBANK.NS", start="2023-01-01", end="2024-01-01", interval="1h")
    except:
        # Fallback: create sample data
        dates = pd.date_range(start="2023-01-01", end="2024-01-01", freq="1h")
        data = pd.DataFrame({
            "Open": np.random.uniform(56000, 57000, len(dates)),
            "High": np.random.uniform(56000, 57000, len(dates)),
            "Low": np.random.uniform(56000, 57000, len(dates)),
            "Close": np.random.uniform(56000, 57000, len(dates)),
            "Volume": np.random.uniform(1000, 100000, len(dates))
        }, index=dates)
    
    # Ensure proper column names for backtesting.py
    data.columns = ["Open", "High", "Low", "Close", "Volume"]
    
    bt = Backtest(data, TvStrategy, cash=100000, commission=0.001)
    stats = bt.run()
    print(stats)
    bt.plot()