"""
DS-TV Backtest Results: risk-calculation-mean-reversion
============================================================

--- SPY ---
  Return                    0.57%
  Buy & Hold Return         17.90%
  Max Drawdown              -8.13%
  Sharpe Ratio              0.04
  Sortino Ratio             0.06
  Calmar Ratio              0.04
  Profit Factor             1.10
  Expectancy                0.11%
  SQN                       0.05
  # Trades                  10
  Win Rate                  30.00%
  Best Trade                9.43%
  Worst Trade               -2.48%
  Avg Trade                 0.06%
  Exposure Time             32.40%
  Equity Final              100567.85$
  Equity Peak               109247.85$
  Avg Drawdown              -1.74%
  Max Drawdown Duration     249 days 00:00:00
  Max Trade Duration        148 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               0.29%
  Ann. Volatility           6.49%

--- BTC ---
  Return                    6.23%
  Buy & Hold Return         17.39%
  Max Drawdown              -17.90%
  Sharpe Ratio              0.14
  Sortino Ratio             0.21
  Calmar Ratio              0.17
  Profit Factor             8.54
  Expectancy                1.99%
  SQN                       1.95
  # Trades                  12
  Win Rate                  75.00%
  Best Trade                10.22%
  Worst Trade               -1.50%
  Avg Trade                 1.94%
  Exposure Time             29.69%
  Equity Final              106234.93$
  Equity Peak               120689.70$
  Avg Drawdown              -7.01%
  Max Drawdown Duration     236 days 00:00:00
  Max Trade Duration        100 days 00:00:00
  Avg Trade Duration        18 days 00:00:00
  Ann. Return               3.07%
  Ann. Volatility           21.87%

--- QQQ ---
  Return                    -0.22%
  Buy & Hold Return         22.08%
  Max Drawdown              -12.51%
  Sharpe Ratio              -0.01
  Sortino Ratio             -0.01
  Calmar Ratio              -0.01
  Profit Factor             1.03
  Expectancy                0.04%
  SQN                       -0.02
  # Trades                  9
  Win Rate                  33.33%
  Best Trade                9.34%
  Worst Trade               -3.67%
  Avg Trade                 -0.03%
  Exposure Time             35.00%
  Equity Final              99783.09$
  Equity Peak               113906.27$
  Avg Drawdown              -2.83%
  Max Drawdown Duration     273 days 00:00:00
  Max Trade Duration        150 days 00:00:00
  Avg Trade Duration        28 days 00:00:00
  Ann. Return               -0.11%
  Ann. Volatility           9.49%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — risk-calculation-mean-reversion
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    buying_power = 200000.0
    equity_risk = 25000.0
    cooldown_bars = 20

    def init(self):
        close = pd.Series(self.data.Close)
        
        self.ema200 = self.I(pta.ema, close, length=200)
        
        self.cooldown_counter = 0
        self.last_alert_bar = -self.cooldown_bars

    def next(self):
        if len(self.data) < 200:
            return
        
        px = self.data.Close[-1]
        ema200_curr = self.ema200[-1]
        
        if px <= 0:
            return
        
        shares = int(self.buying_power / px)
        
        if shares <= 0:
            return
        
        dist_curr = abs(ema200_curr - px)
        pnl_curr = dist_curr * shares
        pts_eq = self.equity_risk / shares if shares > 0 else 0.0
        
        thresholds = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
        
        for threshold in thresholds:
            if pnl_curr >= threshold and len(self.data) - self.last_alert_bar >= self.cooldown_bars:
                if not self.position:
                    self.buy()
                self.last_alert_bar = len(self.data)
                break
        
        if self.position:
            if dist_curr <= pts_eq * 0.5:
                self.position.close()
            elif dist_curr >= dist_curr * 1.5:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=200000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()