"""
DS-TV Backtest Results: scalping-strategy-3-minutes
============================================================

--- SPY ---
  Return                    -15.83%
  Buy & Hold Return         43.93%
  Max Drawdown              -26.19%
  Sharpe Ratio              -0.63
  Sortino Ratio             -0.71
  Calmar Ratio              -0.32
  Profit Factor             1.28
  Expectancy                0.23%
  SQN                       -0.93
  # Trades                  71
  Win Rate                  59.15%
  Best Trade                5.71%
  Worst Trade               -12.42%
  Avg Trade                 0.20%
  Exposure Time             90.60%
  Equity Final              84171.80$
  Equity Peak               104029.02$
  Avg Drawdown              -5.40%
  Max Drawdown Duration     573 days 00:00:00
  Max Trade Duration        43 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -8.32%
  Ann. Volatility           13.19%

--- BTC ---
  Return                    -29.71%
  Buy & Hold Return         44.64%
  Max Drawdown              -37.20%
  Sharpe Ratio              -0.73
  Sortino Ratio             -0.83
  Calmar Ratio              -0.43
  Profit Factor             0.71
  Expectancy                -0.59%
  SQN                       -1.11
  # Trades                  64
  Win Rate                  37.50%
  Best Trade                13.53%
  Worst Trade               -17.28%
  Avg Trade                 -0.70%
  Exposure Time             44.19%
  Equity Final              70294.35$
  Equity Peak               111146.90$
  Avg Drawdown              -8.60%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        27 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -16.14%
  Ann. Volatility           22.06%

--- QQQ ---
  Return                    -27.95%
  Buy & Hold Return         44.93%
  Max Drawdown              -33.72%
  Sharpe Ratio              -0.99
  Sortino Ratio             -1.05
  Calmar Ratio              -0.45
  Profit Factor             1.37
  Expectancy                0.34%
  SQN                       -1.45
  # Trades                  88
  Win Rate                  53.41%
  Best Trade                5.49%
  Worst Trade               -15.27%
  Avg Trade                 0.30%
  Exposure Time             90.40%
  Equity Final              72054.01$
  Equity Peak               100035.81$
  Avg Drawdown              -33.72%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        31 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               -15.23%
  Ann. Volatility           15.42%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — scalping-strategy-3-minutes
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # MA Type and parameters
    basis_type = 'ALMA'
    basis_len = 2
    offset_sigma = 5
    offset_alma = 0.85
    delay_offset = 0
    use_res = True
    int_res = 8
    
    # Risk Management parameters
    lx_lvl_tp1 = 1.0
    lx_qty_tp1 = 50.0
    lx_lvl_tp2 = 1.5
    lx_qty_tp2 = 30.0
    lx_lvl_tp3 = 2.0
    lx_qty_tp3 = 20.0
    lx_lvl_sl = 0.5

    def init(self):
        close = pd.Series(self.data.Close)
        open_data = pd.Series(self.data.Open)
        
        # MA variant calculation
        self.close_series = self.I(self._variant, self.basis_type, close, self.basis_len, self.offset_sigma, self.offset_alma)
        self.open_series = self.I(self._variant, self.basis_type, open_data, self.basis_len, self.offset_sigma, self.offset_alma)
        
        # Initialize tracking variables
        self.condition = 0.0
        self.entry_price = 0.0
        self.sl_line = 0.0
        self.tp1_line = 0.0
        self.tp2_line = 0.0
        self.tp3_line = 0.0

    def _variant(self, var_type, src, length, off_sig, off_alma):
        """MA variant function"""
        if var_type == 'ALMA':
            result = pta.alma(src, length=length, offset=off_alma, sigma=off_sig)
            return result if result is not None else pd.Series(src.iloc[-1], index=src.index)
        elif var_type == 'HullMA':
            result = pta.hma(src, length=length)
            return result if result is not None else pd.Series(src.iloc[-1], index=src.index)
        else:  # TEMA
            result = pta.tema(src, length=length)
            return result if result is not None else pd.Series(src.iloc[-1], index=src.index)

    def next(self):
        close = self.data.Close[-1]
        close_ma = self.close_series[-1]
        open_ma = self.open_series[-1]
        
        # Entry signals
        le_trigger = crossover(self.close_series, self.open_series)
        se_trigger = crossover(self.open_series, self.close_series)
        
        # Long Entry
        if le_trigger and self.condition <= 0.0:
            self.entry_price = close
            self.condition = 1.0
            self.sl_line = close - (close * (self.lx_lvl_sl / 100))
            self.tp1_line = close + (close * (self.lx_lvl_tp1 / 100))
            self.tp2_line = close + (close * (self.lx_lvl_tp2 / 100))
            self.tp3_line = close + (close * (self.lx_lvl_tp3 / 100))
            if not self.position:
                self.buy()
        
        # Short Entry
        elif se_trigger and self.condition >= 0.0:
            self.entry_price = close
            self.condition = -1.0
            self.sl_line = close + (close * (self.lx_lvl_sl / 100))
            self.tp1_line = close - (close * (self.lx_lvl_tp1 / 100))
            self.tp2_line = close - (close * (self.lx_lvl_tp2 / 100))
            self.tp3_line = close - (close * (self.lx_lvl_tp3 / 100))
            if not self.position:
                self.sell()
        
        # Long position management
        elif self.position.is_long:
            # TP1 exit
            if self.condition == 1.0 and close >= self.tp1_line:
                qty_to_exit = self.position.size * (self.lx_qty_tp1 / 100)
                if qty_to_exit > 0:
                    self.position.close(qty_to_exit / self.position.size)
                self.condition = 1.1
            # TP2 exit
            elif self.condition == 1.1 and close >= self.tp2_line:
                qty_to_exit = self.position.size * (self.lx_qty_tp2 / 100)
                if qty_to_exit > 0:
                    self.position.close(qty_to_exit / self.position.size)
                self.condition = 1.2
            # TP3 exit
            elif self.condition == 1.2 and close >= self.tp3_line:
                qty_to_exit = self.position.size * (self.lx_qty_tp3 / 100)
                if qty_to_exit > 0:
                    self.position.close(qty_to_exit / self.position.size)
                self.condition = 1.3
            # SL exit
            elif close <= self.sl_line:
                self.position.close()
                self.condition = 0.0
        
        # Short position management
        elif self.position.is_short:
            # TP1 exit
            if self.condition == -1.0 and close <= self.tp1_line:
                qty_to_exit = self.position.size * (self.lx_qty_tp1 / 100)
                if qty_to_exit > 0:
                    self.position.close(qty_to_exit / self.position.size)
                self.condition = -1.1
            # TP2 exit
            elif self.condition == -1.1 and close <= self.tp2_line:
                qty_to_exit = self.position.size * (self.lx_qty_tp2 / 100)
                if qty_to_exit > 0:
                    self.position.close(qty_to_exit / self.position.size)
                self.condition = -1.2
            # TP3 exit
            elif self.condition == -1.2 and close <= self.tp3_line:
                qty_to_exit = self.position.size * (self.lx_qty_tp3 / 100)
                if qty_to_exit > 0:
                    self.position.close(qty_to_exit / self.position.size)
                self.condition = -1.3
            # SL exit
            elif close >= self.sl_line:
                self.position.close()
                self.condition = 0.0


if __name__ == '__main__':
    import yfinance as yf
    
    # Download sample data
    data = yf.download('EURUSD=X', start='2023-01-01', end='2023-12-31', interval='15m')
    
    # Run backtest
    bt = Backtest(data, TvStrategy, commission=.0002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()