"""
DS-TV Backtest Results: scalp-options-callput-signals-v3
============================================================

--- SPY ---
  ERROR: Indicator "vwap" error. See traceback above.

--- BTC ---
  ERROR: Indicator "vwap" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "vwap" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — scalp-options-callput-signals-v3
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fastEmaLen = 8
    slowEmaLen = 21
    trendEmaLen = 50
    rsiLen = 14
    rsiBullLevel = 55
    rsiBearLevel = 45
    volLen = 20
    volMultiplier = 1.2
    atrLen = 14
    stopATRMult = 1.0
    targetATRMult = 1.5
    htfEmaLen = 21
    lookbackBreakout = 5
    pullbackLookback = 3
    cooldownBars = 4
    allowContinuation = False
    allowPullbacks = True
    allowBreakouts = True
    useCooldown = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        self.fastEma = self.I(pta.ema, close, length=self.fastEmaLen)
        self.slowEma = self.I(pta.ema, close, length=self.slowEmaLen)
        self.trendEma = self.I(pta.ema, close, length=self.trendEmaLen)
        self.vwapVal = self.I(pta.vwap, close, high=high, low=low)
        self.rsiVal = self.I(pta.rsi, close, length=self.rsiLen)
        self.volAvg = self.I(pta.sma, volume, length=self.volLen)
        self.atrVal = self.I(pta.atr, high, low, close, length=self.atrLen)

        self.highestPrev = self.I(lambda: high.shift(1).rolling(self.lookbackBreakout).max())
        self.lowestPrev = self.I(lambda: low.shift(1).rolling(self.lookbackBreakout).min())

        self.pullbackLongPending = False
        self.pullbackShortPending = False
        self.lastCallBar = -np.inf
        self.lastPutBar = -np.inf

    def next(self):
        if len(self.data) < max(self.fastEmaLen, self.slowEmaLen, self.trendEmaLen, self.atrLen, self.lookbackBreakout + 1):
            return

        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        bar_idx = len(self.data) - 1

        fastEma = self.fastEma[-1]
        slowEma = self.slowEma[-1]
        trendEma = self.trendEma[-1]
        vwapVal = self.vwapVal[-1]
        rsiVal = self.rsiVal[-1]
        volAvg = self.volAvg[-1]
        atrVal = self.atrVal[-1]

        if np.isnan(fastEma) or np.isnan(slowEma) or np.isnan(trendEma) or np.isnan(vwapVal) or np.isnan(rsiVal) or np.isnan(volAvg) or np.isnan(atrVal):
            return

        highestPrev = self.highestPrev[-1]
        lowestPrev = self.lowestPrev[-1]

        volOK = volume >= volAvg * self.volMultiplier

        bullTrend = fastEma > slowEma and close > trendEma and close > vwapVal
        bearTrend = fastEma < slowEma and close < trendEma and close < vwapVal

        bullMomentum = rsiVal >= self.rsiBullLevel
        bearMomentum = rsiVal <= self.rsiBearLevel

        longContext = volOK and bullTrend and bullMomentum
        shortContext = volOK and bearTrend and bearMomentum

        freshLong = crossover(self.fastEma, self.slowEma) and close > vwapVal
        freshShort = crossover(self.slowEma, self.fastEma) and close < vwapVal

        breakoutLong = close > highestPrev and close > open_
        breakoutShort = close < lowestPrev and close < open_

        if self.allowPullbacks and bullTrend and (low <= fastEma or low <= slowEma or low <= vwapVal):
            self.pullbackLongPending = True

        if self.allowPullbacks and bearTrend and (high >= fastEma or high >= slowEma or high >= vwapVal):
            self.pullbackShortPending = True

        if not bullTrend:
            self.pullbackLongPending = False
        if not bearTrend:
            self.pullbackShortPending = False

        reclaimLong = close > fastEma and close > vwapVal and close > open_
        reclaimShort = close < fastEma and close < vwapVal and close < open_

        pullbackLong = self.pullbackLongPending and reclaimLong
        pullbackShort = self.pullbackShortPending and reclaimShort

        if pullbackLong:
            self.pullbackLongPending = False
        if pullbackShort:
            self.pullbackShortPending = False

        continuationLong = self.allowContinuation and bullTrend and close > self.data.High[-2] and close > fastEma and volOK
        continuationShort = self.allowContinuation and bearTrend and close < self.data.Low[-2] and close < fastEma and volOK

        rawCallSignal = longContext and (
            freshLong or
            (self.allowBreakouts and breakoutLong) or
            pullbackLong or
            continuationLong
        )

        rawPutSignal = shortContext and (
            freshShort or
            (self.allowBreakouts and breakoutShort) or
            pullbackShort or
            continuationShort
        )

        callCooldownOK = not self.useCooldown or (bar_idx - self.lastCallBar) > self.cooldownBars
        putCooldownOK = not self.useCooldown or (bar_idx - self.lastPutBar) > self.cooldownBars

        callSignal = rawCallSignal and callCooldownOK and not rawPutSignal
        putSignal = rawPutSignal and putCooldownOK and not rawCallSignal

        if callSignal:
            self.lastCallBar = bar_idx
            if not self.position:
                self.buy()

        if putSignal:
            self.lastPutBar = bar_idx
            if self.position:
                self.position.close()


if __name__ == '__main__':
    from backtesting.test import GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()