"""
DS-TV Backtest Results: sma-distance
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — sma-distance
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    smaLength = 100

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate Daily SMA (using the same close data as a proxy for daily)
        daily_sma = self.I(pta.sma, close, length=self.smaLength)
        
        # Calculate percentage distance
        self.percentage_distance = self.I(
            lambda: ((close - daily_sma) / daily_sma) * 100
        )
        
        # Calculate cumulative positive distances and counts
        def calc_hist_upper():
            pos_dist = np.where(self.percentage_distance > 0, self.percentage_distance, np.nan)
            cum_pos_dist = np.nancumsum(np.nan_to_num(pos_dist))
            cum_pos_count = np.cumsum(~np.isnan(pos_dist))
            hist_upper = np.where(cum_pos_count > 0, cum_pos_dist / cum_pos_count, np.nan)
            return pd.Series(hist_upper, index=close.index)
        
        # Calculate cumulative negative distances and counts
        def calc_hist_lower():
            neg_dist = np.where(self.percentage_distance < 0, self.percentage_distance, np.nan)
            cum_neg_dist = np.nancumsum(np.nan_to_num(neg_dist))
            cum_neg_count = np.cumsum(~np.isnan(neg_dist))
            hist_lower = np.where(cum_neg_count > 0, cum_neg_dist / cum_neg_count, np.nan)
            return pd.Series(hist_lower, index=close.index)
        
        self.historical_upper = self.I(calc_hist_upper)
        self.historical_lower = self.I(calc_hist_lower)

    def next(self):
        # Buy when price crosses above historical upper bound (overbought mean reversion)
        if len(self) > 1:
            if crossover(self.percentage_distance, self.historical_upper):
                if not self.position:
                    self.buy()
            # Sell when price crosses below historical lower bound (oversold mean reversion)
            elif crossover(self.historical_lower, self.percentage_distance):
                if self.position:
                    self.sell()
            # Also sell if distance returns to zero from positive
            elif self.percentage_distance[-1] >= 0 and self.percentage_distance[-2] < 0:
                if self.position:
                    self.sell()
            # Also buy if distance returns to zero from negative
            elif self.percentage_distance[-1] <= 0 and self.percentage_distance[-2] > 0:
                if not self.position:
                    self.buy()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()