"""
DS-TV Backtest Results: spx-scalper-ema-trend-pullback-rsivolume-atr-exits
============================================================

--- SPY ---
  Return                    2.90%
  Buy & Hold Return         17.90%
  Max Drawdown              -0.52%
  Sharpe Ratio              1.31
  Sortino Ratio             3.90
  Calmar Ratio              2.78
  Profit Factor             nan
  Expectancy                1.44%
  SQN                       2.21
  # Trades                  2
  Win Rate                  100.00%
  Best Trade                2.11%
  Worst Trade               0.78%
  Avg Trade                 1.44%
  Exposure Time             2.00%
  Equity Final              102896.26$
  Equity Peak               102960.43$
  Avg Drawdown              -0.29%
  Max Drawdown Duration     47 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               1.45%
  Ann. Volatility           1.11%

--- BTC ---
  Return                    16.68%
  Buy & Hold Return         17.39%
  Max Drawdown              -8.22%
  Sharpe Ratio              0.88
  Sortino Ratio             2.04
  Calmar Ratio              0.97
  Profit Factor             3.58
  Expectancy                3.96%
  SQN                       1.60
  # Trades                  4
  Win Rate                  75.00%
  Best Trade                8.57%
  Worst Trade               -6.15%
  Avg Trade                 3.79%
  Exposure Time             4.10%
  Equity Final              116681.66$
  Equity Peak               116798.62$
  Avg Drawdown              -2.10%
  Max Drawdown Duration     215 days 00:00:00
  Max Trade Duration        9 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               8.01%
  Ann. Volatility           9.05%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — spx-scalper-ema-trend-pullback-rsivolume-atr-exits
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fastLen = 9
    slowLen = 21
    trendLen = 200
    useTrend200 = True
    rsiLen = 14
    rsiLong = 50
    rsiShort = 50
    volLen = 20
    volMult = 1.10
    atrLen = 14
    stopATR = 1.0
    targetATR = 1.3
    trailATR = 0.8
    maxBarsInTrade = 18

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.fastEma = self.I(pta.ema, close, length=self.fastLen)
        self.slowEma = self.I(pta.ema, close, length=self.slowLen)
        self.trendEma = self.I(pta.ema, close, length=self.trendLen)
        
        self.rsi = self.I(pta.rsi, close, length=self.rsiLen)
        self.volMA = self.I(pta.sma, volume, length=self.volLen)
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        self.barsInTrade = 0
        self.entryPrice = None

    def next(self):
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        
        fastEma = self.fastEma[-1]
        slowEma = self.slowEma[-1]
        trendEma = self.trendEma[-1]
        rsi = self.rsi[-1]
        volMA = self.volMA[-1]
        atr = self.atr[-1]
        
        if pd.isna(fastEma) or pd.isna(slowEma) or pd.isna(rsi) or pd.isna(atr) or pd.isna(volMA):
            return
        
        volOK = volume > volMA * self.volMult
        
        trendUp = fastEma > slowEma
        trendDown = fastEma < slowEma
        
        trend200UpOK = not self.useTrend200 or close > trendEma
        trend200DownOK = not self.useTrend200 or close < trendEma
        
        pullbackLong = low <= fastEma and close > fastEma
        pullbackShort = high >= fastEma and close < fastEma
        
        rsiLongCross = crossover(self.rsi, self.rsiLong)
        rsiShortCross = crossover(self.rsiShort, self.rsi)
        
        longSignal = trendUp and trend200UpOK and pullbackLong and rsiLongCross and volOK
        shortSignal = trendDown and trend200DownOK and pullbackShort and rsiShortCross and volOK
        
        if self.position:
            self.barsInTrade += 1
            
            if self.position.is_long:
                longStop = self.entryPrice - (atr * self.stopATR)
                longLimit = self.entryPrice + (atr * self.targetATR)
                
                if close <= longStop or close >= longLimit:
                    self.position.close()
                    self.barsInTrade = 0
                    self.entryPrice = None
                elif self.maxBarsInTrade > 0 and self.barsInTrade >= self.maxBarsInTrade:
                    self.position.close()
                    self.barsInTrade = 0
                    self.entryPrice = None
            
            elif self.position.is_short:
                shortStop = self.entryPrice + (atr * self.stopATR)
                shortLimit = self.entryPrice - (atr * self.targetATR)
                
                if close >= shortStop or close <= shortLimit:
                    self.position.close()
                    self.barsInTrade = 0
                    self.entryPrice = None
                elif self.maxBarsInTrade > 0 and self.barsInTrade >= self.maxBarsInTrade:
                    self.position.close()
                    self.barsInTrade = 0
                    self.entryPrice = None
        else:
            self.barsInTrade = 0
            
            if longSignal:
                self.buy()
                self.entryPrice = close
            elif shortSignal:
                self.sell()
                self.entryPrice = close


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=100000, commission=0.001)
    results = bt.run()
    print(results)
    bt.plot()