"""
DS-TV Backtest Results: strict-1-tradeday-smc-orb
============================================================

--- SPY ---
  ERROR: object of type 'Position' has no len()

--- BTC ---
  ERROR: object of type 'Position' has no len()

--- QQQ ---
  ERROR: object of type 'Position' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — strict-1-tradeday-smc-orb
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime, time


class TvStrategy(Strategy):
    fvg_threshold = 0.0
    atr_length = 15
    atr_multiplier = 3.0
    sma_fast_len = 10
    sma_slow_len = 20
    swing_len = 2
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_length)
        self.sma_fast = self.I(pta.sma, close, length=self.sma_fast_len)
        self.sma_slow = self.I(pta.sma, close, length=self.sma_slow_len)
        
        self.orh = None
        self.orl = None
        self.last_swing_high = None
        self.last_swing_low = None
        self.entry_price = None
        self.partial_taken_1r = False
        self.moved_to_be = False
        self.trade_count = 0
        self.last_day = None
        self.entry_bar = None
        
    def next(self):
        if len(self.data) < max(self.swing_len + 2, self.sma_slow_len, self.atr_length):
            return
        
        current_date = pd.Timestamp(self.data.index[-1]).date()
        if self.last_day != current_date:
            self.last_day = current_date
            self.trade_count = 0
            self.orh = None
            self.orl = None
        
        current_time = pd.Timestamp(self.data.index[-1]).time()
        in_orb = (time(9, 30) <= current_time <= time(9, 45))
        after_orb = (time(9, 45) < current_time <= time(16, 0)) and self.orh is not None
        is_before_cutoff = (time(9, 30) <= current_time < time(12, 0))
        is_exit_time = (time(14, 0) <= current_time <= time(16, 0))
        
        if in_orb:
            if self.orh is None:
                self.orh = self.data.High[-1]
                self.orl = self.data.Low[-1]
            else:
                self.orh = max(self.orh, self.data.High[-1])
                self.orl = min(self.orl, self.data.Low[-1])
        
        if len(self.data) > self.swing_len + 1:
            is_pivot_high = (self.data.High[-self.swing_len-1] < self.data.High[-self.swing_len] > 
                            self.data.High[-self.swing_len+1])
            is_pivot_low = (self.data.Low[-self.swing_len-1] > self.data.Low[-self.swing_len] < 
                           self.data.Low[-self.swing_len+1])
            
            if is_pivot_high:
                self.last_swing_high = self.data.High[-self.swing_len]
            if is_pivot_low:
                self.last_swing_low = self.data.Low[-self.swing_len]
        
        bull_fvg = (self.data.Low[-1] > self.data.High[-3] + (self.fvg_threshold * 0.01) 
                   if len(self.data) > 2 else False)
        bear_fvg = (self.data.High[-1] < self.data.Low[-3] - (self.fvg_threshold * 0.01) 
                   if len(self.data) > 2 else False)
        
        choch_bull = (self.last_swing_high is not None and 
                     crossover(pd.Series(self.data.Close[-5:]), 
                              pd.Series([self.last_swing_high]*5)))
        choch_bear = (self.last_swing_low is not None and 
                     crossover(pd.Series([self.last_swing_low]*5),
                              pd.Series(self.data.Close[-5:])))
        
        can_enter = after_orb and is_before_cutoff and len(self.position) == 0 and self.trade_count == 0
        
        if is_exit_time and len(self.position) > 0:
            self.position.close()
            self.trade_count = 1
        
        if can_enter and self.orh is not None and self.orl is not None:
            orb_range = self.orh - self.orl
            
            if (self.data.Close[-1] > self.orh and self.last_swing_high is not None and 
                self.data.Close[-1] > self.last_swing_high and bull_fvg and 
                self.atr[-1] is not None):
                self.entry_price = self.data.Close[-1]
                self.entry_bar = len(self.data)
                self.buy()
                self.trade_count = 1
                self.partial_taken_1r = False
                self.moved_to_be = False
            
            elif (self.data.Close[-1] < self.orl and self.last_swing_low is not None and 
                  self.data.Close[-1] < self.last_swing_low and bear_fvg and 
                  self.atr[-1] is not None):
                self.entry_price = self.data.Close[-1]
                self.entry_bar = len(self.data)
                self.sell()
                self.trade_count = 1
                self.partial_taken_1r = False
                self.moved_to_be = False
        
        if len(self.position) > 0 and self.entry_price is not None and self.orh is not None:
            orb_range = self.orh - self.orl
            
            if not self.partial_taken_1r:
                if self.position.is_long:
                    hit_1r = self.data.High[-1] >= self.entry_price + orb_range
                    ma_cross = crossover(pd.Series(self.sma_fast[-5:]), 
                                        pd.Series(self.sma_slow[-5:]))
                    if hit_1r or ma_cross:
                        self.position.close(0.5)
                        self.partial_taken_1r = True
                else:
                    hit_1r = self.data.Low[-1] <= self.entry_price - orb_range
                    ma_cross = crossover(pd.Series(self.sma_slow[-5:]), 
                                        pd.Series(self.sma_fast[-5:]))
                    if hit_1r or ma_cross:
                        self.position.close(0.5)
                        self.partial_taken_1r = True
            
            if not self.moved_to_be and self.entry_bar is not None:
                bars_since_entry = len(self.data) - self.entry_bar
                if bars_since_entry >= 180:
                    self.position.close(0.5)
                    self.moved_to_be = True