"""
DS-TV Backtest Results: supply-and-demand-zone-indicator-5m
============================================================

--- SPY ---
  Return                    -42.74%
  Buy & Hold Return         39.08%
  Max Drawdown              -43.52%
  Sharpe Ratio              -2.06
  Sortino Ratio             -2.12
  Calmar Ratio              -0.56
  Profit Factor             0.31
  Expectancy                -0.67%
  SQN                       -3.55
  # Trades                  81
  Win Rate                  33.33%
  Best Trade                4.67%
  Worst Trade               -5.93%
  Avg Trade                 -0.68%
  Exposure Time             95.80%
  Equity Final              57256.24$
  Equity Peak               101378.11$
  Avg Drawdown              -15.12%
  Max Drawdown Duration     684 days 00:00:00
  Max Trade Duration        66 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               -24.50%
  Ann. Volatility           11.92%

--- BTC ---
  Return                    -51.17%
  Buy & Hold Return         14.14%
  Max Drawdown              -54.81%
  Sharpe Ratio              -1.50
  Sortino Ratio             -1.33
  Calmar Ratio              -0.55
  Profit Factor             0.48
  Expectancy                -1.33%
  SQN                       -1.52
  # Trades                  60
  Win Rate                  48.33%
  Best Trade                7.04%
  Worst Trade               -38.33%
  Avg Trade                 -1.58%
  Exposure Time             35.70%
  Equity Final              48830.03$
  Equity Peak               101529.90$
  Avg Drawdown              -54.81%
  Max Drawdown Duration     699 days 00:00:00
  Max Trade Duration        30 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -30.09%
  Ann. Volatility           20.04%

--- QQQ ---
  Return                    -44.98%
  Buy & Hold Return         42.00%
  Max Drawdown              -47.08%
  Sharpe Ratio              -1.69
  Sortino Ratio             -1.76
  Calmar Ratio              -0.55
  Profit Factor             0.37
  Expectancy                -0.88%
  SQN                       -2.55
  # Trades                  66
  Win Rate                  33.33%
  Best Trade                5.06%
  Worst Trade               -15.20%
  Avg Trade                 -0.92%
  Exposure Time             93.40%
  Equity Final              55024.40$
  Equity Peak               100874.43$
  Avg Drawdown              -24.58%
  Max Drawdown Duration     689 days 00:00:00
  Max Trade Duration        90 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -26.00%
  Ann. Volatility           15.41%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — supply-and-demand-zone-indicator-5m
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lookback = 20
    impulseMultiplier = 1.5

    def init(self):
        self.demand_low = np.nan
        self.demand_high = np.nan
        self.supply_low = np.nan
        self.supply_high = np.nan
        
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        
        # Calculate candle body
        self.body = self.I(lambda: np.abs(close - open_))
        
        # Calculate average body
        self.avg_body = self.I(lambda: pta.sma(np.abs(close - open_), length=self.lookback))

    def next(self):
        if len(self.data) < 2:
            return
        
        # Current and previous candle values
        current_body = self.body[-1]
        prev_body = self.body[-2] if len(self.body) > 1 else current_body
        
        current_avg_body = self.avg_body[-1] if not np.isnan(self.avg_body[-1]) else 0
        prev_avg_body = self.avg_body[-2] if len(self.avg_body) > 1 and not np.isnan(self.avg_body[-2]) else current_avg_body
        
        current_close = self.data.Close[-1]
        current_open = self.data.Open[-1]
        prev_close = self.data.Close[-2] if len(self.data) > 1 else current_close
        prev_open = self.data.Open[-2] if len(self.data) > 1 else current_open
        prev_low = self.data.Low[-2] if len(self.data) > 1 else self.data.Low[-1]
        prev_high = self.data.High[-2] if len(self.data) > 1 else self.data.High[-1]
        
        current_low = self.data.Low[-1]
        current_high = self.data.High[-1]
        
        # Impulse detection
        bull_impulse = current_close > current_open and current_body > current_avg_body * self.impulseMultiplier
        bear_impulse = current_open > current_close and current_body > current_avg_body * self.impulseMultiplier
        
        # Base candle detection
        base_candle = prev_body < prev_avg_body
        
        # Zone detection
        demand_zone = base_candle and bull_impulse
        supply_zone = base_candle and bear_impulse
        
        # Update zone levels
        if demand_zone:
            self.demand_low = prev_low
            self.demand_high = prev_high
        
        if supply_zone:
            self.supply_low = prev_low
            self.supply_high = prev_high
        
        # Entry signals
        buy_signal = not np.isnan(self.demand_low) and current_low <= self.demand_high and current_low >= self.demand_low
        sell_signal = not np.isnan(self.supply_high) and current_high >= self.supply_low and current_high <= self.supply_high
        
        # Trading logic
        if buy_signal and not self.position:
            self.buy()
        elif sell_signal and self.position:
            self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)