"""
DS-TV Backtest Results: swift-algo-pro-bos-reteste-miller
============================================================

--- SPY ---
  Return                    -0.88%
  Buy & Hold Return         40.20%
  Max Drawdown              -11.85%
  Sharpe Ratio              -0.04
  Sortino Ratio             -0.05
  Calmar Ratio              -0.04
  Profit Factor             1.01
  Expectancy                0.01%
  SQN                       -0.06
  # Trades                  26
  Win Rate                  34.62%
  Best Trade                9.32%
  Worst Trade               -4.23%
  Avg Trade                 -0.04%
  Exposure Time             45.00%
  Equity Final              99119.52$
  Equity Peak               109671.80$
  Avg Drawdown              -3.76%
  Max Drawdown Duration     262 days 00:00:00
  Max Trade Duration        55 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               -0.44%
  Ann. Volatility           12.02%

--- BTC ---
  Return                    26.77%
  Buy & Hold Return         0.29%
  Max Drawdown              -23.17%
  Sharpe Ratio              0.42
  Sortino Ratio             0.75
  Calmar Ratio              0.54
  Profit Factor             1.15
  Expectancy                0.34%
  SQN                       0.35
  # Trades                  41
  Win Rate                  46.34%
  Best Trade                30.32%
  Worst Trade               -9.23%
  Avg Trade                 0.13%
  Exposure Time             49.52%
  Equity Final              126772.93$
  Equity Peak               133920.89$
  Avg Drawdown              -6.83%
  Max Drawdown Duration     206 days 00:00:00
  Max Trade Duration        29 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               12.58%
  Ann. Volatility           30.07%

--- QQQ ---
  Return                    -11.71%
  Buy & Hold Return         45.93%
  Max Drawdown              -19.52%
  Sharpe Ratio              -0.63
  Sortino Ratio             -0.75
  Calmar Ratio              -0.31
  Profit Factor             0.67
  Expectancy                -0.44%
  SQN                       -0.80
  # Trades                  26
  Win Rate                  38.46%
  Best Trade                6.92%
  Worst Trade               -6.74%
  Avg Trade                 -0.48%
  Exposure Time             35.80%
  Equity Final              88288.59$
  Equity Peak               108172.34$
  Avg Drawdown              -7.35%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               -6.08%
  Ann. Volatility           9.70%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — swift-algo-pro-bos-reteste-miller
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    emaFastLen = 9
    emaSlowLen = 21
    trendLen = 50
    rsiLen = 14
    rr = 2.0
    pivotLen = 3
    maxRetestBars = 6
    boxLength = 25

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.emaFast = self.I(pta.ema, close, length=self.emaFastLen)
        self.emaSlow = self.I(pta.ema, close, length=self.emaSlowLen)
        self.emaTrend = self.I(pta.ema, close, length=self.trendLen)
        
        self.rsiVal = self.I(pta.rsi, close, length=self.rsiLen)
        
        # Pivot highs and lows
        def get_pivot_highs(h, length):
            result = pd.Series(np.nan, index=h.index)
            for i in range(length, len(h) - length):
                if h.iloc[i] == h.iloc[i-length:i+length+1].max():
                    result.iloc[i] = h.iloc[i]
            return result
        
        def get_pivot_lows(l, length):
            result = pd.Series(np.nan, index=l.index)
            for i in range(length, len(l) - length):
                if l.iloc[i] == l.iloc[i-length:i+length+1].min():
                    result.iloc[i] = l.iloc[i]
            return result
        
        self.swingHigh = self.I(get_pivot_highs, high, self.pivotLen)
        self.swingLow = self.I(get_pivot_lows, low, self.pivotLen)
        
        self.lastHigh = None
        self.lastLow = None
        self.waitBullRetest = False
        self.waitBearRetest = False
        self.tradedBull = False
        self.tradedBear = False
        self.bullBars = 0
        self.bearBars = 0
        self.buyStop = None
        self.sellStop = None

    def next(self):
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        # Update last swing high/low
        if not np.isnan(self.swingHigh[-1]):
            self.lastHigh = self.swingHigh[-1]
        
        if not np.isnan(self.swingLow[-1]):
            self.lastLow = self.swingLow[-1]
        
        # BOS conditions
        bosBull = self.lastHigh is not None and close > self.lastHigh
        bosBear = self.lastLow is not None and close < self.lastLow
        
        # Reset on BOS
        if bosBull:
            self.waitBullRetest = True
            self.tradedBull = False
            self.bullBars = 0
        
        if bosBear:
            self.waitBearRetest = True
            self.tradedBear = False
            self.bearBars = 0
        
        # Increment bars while waiting
        if self.waitBullRetest:
            self.bullBars += 1
        
        if self.waitBearRetest:
            self.bearBars += 1
        
        # Timeout
        if self.bullBars > self.maxRetestBars:
            self.waitBullRetest = False
        
        if self.bearBars > self.maxRetestBars:
            self.waitBearRetest = False
        
        # Entry conditions
        bullEntry = (
            self.waitBullRetest and
            not self.tradedBull and
            low <= self.emaFast[-1] and
            close > self.emaFast[-1] and
            self.rsiVal[-1] > 50 and
            close > self.emaTrend[-1]
        )
        
        bearEntry = (
            self.waitBearRetest and
            not self.tradedBear and
            high >= self.emaFast[-1] and
            close < self.emaFast[-1] and
            self.rsiVal[-1] < 50 and
            close < self.emaTrend[-1]
        )
        
        # Execute entries
        if bullEntry:
            self.tradedBull = True
            self.waitBullRetest = False
            self.buyStop = low
            self.buy()
        
        if bearEntry:
            self.tradedBear = True
            self.waitBearRetest = False
            self.sellStop = high
            self.sell()
        
        # Exit logic with risk/reward
        if self.position:
            if self.position.is_long:
                buyTP = close + (close - self.buyStop) * self.rr
                if close >= buyTP or close <= self.buyStop:
                    self.position.close()
            else:
                sellTP = close - (self.sellStop - close) * self.rr
                if close <= sellTP or close >= self.sellStop:
                    self.position.close()