"""
DS-TV Backtest Results: swiss-army-moving-averages-vwap
============================================================

--- SPY ---
  Return                    -0.80%
  Buy & Hold Return         17.90%
  Max Drawdown              -3.46%
  Sharpe Ratio              -0.10
  Sortino Ratio             -0.13
  Calmar Ratio              -0.12
  Profit Factor             0.78
  Expectancy                -0.19%
  SQN                       -0.22
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                2.10%
  Worst Trade               -1.85%
  Avg Trade                 -0.20%
  Exposure Time             16.20%
  Equity Final              99203.32$
  Equity Peak               101336.48$
  Avg Drawdown              -2.11%
  Max Drawdown Duration     350 days 00:00:00
  Max Trade Duration        67 days 00:00:00
  Avg Trade Duration        29 days 00:00:00
  Ann. Return               -0.40%
  Ann. Volatility           4.19%

--- BTC ---
  Return                    23.43%
  Buy & Hold Return         17.39%
  Max Drawdown              -18.72%
  Sharpe Ratio              0.53
  Sortino Ratio             0.91
  Calmar Ratio              0.59
  Profit Factor             2.56
  Expectancy                3.95%
  SQN                       0.59
  # Trades                  12
  Win Rate                  33.33%
  Best Trade                49.58%
  Worst Trade               -9.73%
  Avg Trade                 2.98%
  Exposure Time             37.89%
  Equity Final              123434.45$
  Equity Peak               146549.08$
  Avg Drawdown              -4.36%
  Max Drawdown Duration     203 days 00:00:00
  Max Trade Duration        72 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               11.09%
  Ann. Volatility           21.10%

--- QQQ ---
  Return                    -10.19%
  Buy & Hold Return         22.08%
  Max Drawdown              -10.19%
  Sharpe Ratio              -0.96
  Sortino Ratio             -1.09
  Calmar Ratio              -0.52
  Profit Factor             0.18
  Expectancy                -1.76%
  SQN                       -2.06
  # Trades                  6
  Win Rate                  16.67%
  Best Trade                2.33%
  Worst Trade               -3.89%
  Avg Trade                 -1.78%
  Exposure Time             14.80%
  Equity Final              89813.20$
  Equity Peak               100000.00$
  Avg Drawdown              -10.19%
  Max Drawdown Duration     399 days 00:00:00
  Max Trade Duration        35 days 00:00:00
  Avg Trade Duration        17 days 00:00:00
  Ann. Return               -5.27%
  Ann. Volatility           5.50%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — swiss-army-moving-averages-vwap
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # EMA Settings
    ema1_length = 9
    ema2_length = 20
    ema3_length = 50
    ema4_length = 200
    
    # SMA Settings
    sma1_length = 9
    sma2_length = 20
    sma3_length = 50
    sma4_length = 200
    
    # Master Switches
    show_emas = True
    show_smas = False
    show_vwap = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate EMAs
        if self.show_emas:
            self.ema1 = self.I(pta.ema, close, length=self.ema1_length)
            self.ema2 = self.I(pta.ema, close, length=self.ema2_length)
            self.ema3 = self.I(pta.ema, close, length=self.ema3_length)
            self.ema4 = self.I(pta.ema, close, length=self.ema4_length)
        else:
            self.ema1 = self.I(lambda: pd.Series(np.nan, index=close.index))
            self.ema2 = self.I(lambda: pd.Series(np.nan, index=close.index))
            self.ema3 = self.I(lambda: pd.Series(np.nan, index=close.index))
            self.ema4 = self.I(lambda: pd.Series(np.nan, index=close.index))
        
        # Calculate SMAs
        if self.show_smas:
            self.sma1 = self.I(pta.sma, close, length=self.sma1_length)
            self.sma2 = self.I(pta.sma, close, length=self.sma2_length)
            self.sma3 = self.I(pta.sma, close, length=self.sma3_length)
            self.sma4 = self.I(pta.sma, close, length=self.sma4_length)
        else:
            self.sma1 = self.I(lambda: pd.Series(np.nan, index=close.index))
            self.sma2 = self.I(lambda: pd.Series(np.nan, index=close.index))
            self.sma3 = self.I(lambda: pd.Series(np.nan, index=close.index))
            self.sma4 = self.I(lambda: pd.Series(np.nan, index=close.index))
        
        # Calculate VWAP (simplified daily anchoring)
        if self.show_vwap:
            def calc_vwap():
                df = pd.DataFrame({
                    'High': high,
                    'Low': low,
                    'Close': close,
                    'Volume': volume
                })
                df['HL2'] = (df['High'] + df['Low']) / 2
                df['HLC3'] = (df['High'] + df['Low'] + df['Close']) / 3
                df['CumVolume'] = df['Volume'].cumsum()
                df['CumVolHLC3'] = (df['HLC3'] * df['Volume']).cumsum()
                df['VWAP'] = df['CumVolHLC3'] / df['CumVolume']
                return df['VWAP']
            
            self.vwap = self.I(calc_vwap)
        else:
            self.vwap = self.I(lambda: pd.Series(np.nan, index=close.index))

    def next(self):
        # Trading logic based on EMA crossovers
        if self.show_emas:
            # Buy when fast EMA (9) crosses above medium EMA (20)
            if crossover(self.ema1, self.ema2):
                if not self.position:
                    self.buy()
            
            # Sell when fast EMA (9) crosses below medium EMA (20)
            elif crossover(self.ema2, self.ema1):
                if self.position:
                    self.position.close()
            
            # Additional exit: sell when price crosses below EMA4 (200)
            if self.position and crossover(self.ema4, self.data.Close):
                self.position.close()
        
        # Alternative logic with VWAP if no EMAs
        elif self.show_vwap:
            # Buy when price crosses above VWAP
            if crossover(self.data.Close, self.vwap):
                if not self.position:
                    self.buy()
            
            # Sell when price crosses below VWAP
            elif crossover(self.vwap, self.data.Close):
                if self.position:
                    self.position.close()


if __name__ == '__main__':
    # Load data
    df = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    # Run backtest
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()