"""
DS-TV Backtest Results: the-holy-grail
============================================================

--- SPY ---
  Return                    -1.18%
  Buy & Hold Return         40.20%
  Max Drawdown              -6.16%
  Sharpe Ratio              -0.11
  Sortino Ratio             -0.14
  Calmar Ratio              -0.10
  Profit Factor             0.85
  Expectancy                -0.31%
  SQN                       -0.14
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                5.34%
  Worst Trade               -4.70%
  Avg Trade                 -0.39%
  Exposure Time             15.60%
  Equity Final              98818.92$
  Equity Peak               102674.39$
  Avg Drawdown              -3.31%
  Max Drawdown Duration     440 days 00:00:00
  Max Trade Duration        104 days 00:00:00
  Avg Trade Duration        36 days 00:00:00
  Ann. Return               -0.60%
  Ann. Volatility           5.26%

--- BTC ---
  Return                    -8.02%
  Buy & Hold Return         0.29%
  Max Drawdown              -14.82%
  Sharpe Ratio              -0.32
  Sortino Ratio             -0.43
  Calmar Ratio              -0.28
  Profit Factor             0.00
  Expectancy                -3.47%
  SQN                       -2.20
  # Trades                  3
  Win Rate                  0.00%
  Best Trade                -0.54%
  Worst Trade               -5.23%
  Avg Trade                 -3.49%
  Exposure Time             13.00%
  Equity Final              91978.58$
  Equity Peak               107986.87$
  Avg Drawdown              -9.38%
  Max Drawdown Duration     308 days 00:00:00
  Max Trade Duration        48 days 00:00:00
  Avg Trade Duration        31 days 00:00:00
  Ann. Return               -4.09%
  Ann. Volatility           12.93%

--- QQQ ---
  Return                    2.43%
  Buy & Hold Return         45.93%
  Max Drawdown              -10.90%
  Sharpe Ratio              0.12
  Sortino Ratio             0.17
  Calmar Ratio              0.11
  Profit Factor             nan
  Expectancy                2.45%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                2.45%
  Worst Trade               2.45%
  Avg Trade                 2.45%
  Exposure Time             4.60%
  Equity Final              102431.79$
  Equity Peak               113113.33$
  Avg Drawdown              -4.18%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        33 days 00:00:00
  Avg Trade Duration        33 days 00:00:00
  Ann. Return               1.22%
  Ann. Volatility           10.18%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — the-holy-grail
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    useAdx = True
    adxSmoothing = 14
    diLength = 14
    adxThreshold = 30.0
    emaFastLen = 20
    emaSlowLen = 50
    fractalN = 6

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate EMAs
        self.emaFast = self.I(pta.ema, close, length=self.emaFastLen)
        self.emaSlow = self.I(pta.ema, close, length=self.emaSlowLen)
        
        # Calculate ADX manually (Wilder's method)
        self.adxValue = self.I(self._calculate_adx, high, low, close)
        
        # Calculate Williams Fractals
        self.upFractal = self.I(self._calculate_up_fractal, high)
        self.downFractal = self.I(self._calculate_down_fractal, low)

    def _calculate_adx(self, high, low, close):
        """Calculate ADX using Wilder's smoothing method"""
        result = pd.Series(index=close.index, dtype=float)
        
        if len(close) < self.diLength + self.adxSmoothing:
            return result
        
        # Calculate true range
        tr = np.zeros(len(close))
        tr[0] = high.iloc[0] - low.iloc[0]
        for i in range(1, len(close)):
            tr[i] = max(
                high.iloc[i] - low.iloc[i],
                abs(high.iloc[i] - close.iloc[i-1]),
                abs(low.iloc[i] - close.iloc[i-1])
            )
        
        # Calculate directional movements
        up = np.zeros(len(close))
        down = np.zeros(len(close))
        for i in range(1, len(close)):
            up_move = high.iloc[i] - high.iloc[i-1]
            down_move = low.iloc[i-1] - low.iloc[i]
            
            if up_move > down_move and up_move > 0:
                up[i] = up_move
            if down_move > up_move and down_move > 0:
                down[i] = down_move
        
        # Wilder's smoothing for DM
        plus_dm = np.zeros(len(close))
        minus_dm = np.zeros(len(close))
        atr = np.zeros(len(close))
        
        for i in range(self.diLength, len(close)):
            if i == self.diLength:
                plus_dm[i] = np.sum(up[1:i+1])
                minus_dm[i] = np.sum(down[1:i+1])
                atr[i] = np.sum(tr[1:i+1])
            else:
                plus_dm[i] = plus_dm[i-1] - plus_dm[i-1]/self.diLength + up[i]
                minus_dm[i] = minus_dm[i-1] - minus_dm[i-1]/self.diLength + down[i]
                atr[i] = atr[i-1] - atr[i-1]/self.diLength + tr[i]
        
        # Calculate DI+, DI-
        di_plus = np.zeros(len(close))
        di_minus = np.zeros(len(close))
        for i in range(self.diLength, len(close)):
            if atr[i] != 0:
                di_plus[i] = 100 * plus_dm[i] / atr[i]
                di_minus[i] = 100 * minus_dm[i] / atr[i]
        
        # Calculate DX
        dx = np.zeros(len(close))
        for i in range(self.diLength, len(close)):
            di_sum = di_plus[i] + di_minus[i]
            if di_sum != 0:
                dx[i] = 100 * abs(di_plus[i] - di_minus[i]) / di_sum
        
        # Wilder's smoothing for ADX
        adx_vals = np.zeros(len(close))
        for i in range(self.diLength + self.adxSmoothing, len(close)):
            if i == self.diLength + self.adxSmoothing:
                adx_vals[i] = np.mean(dx[self.diLength:i+1])
            else:
                adx_vals[i] = (adx_vals[i-1] * (self.adxSmoothing - 1) + dx[i]) / self.adxSmoothing
        
        result[:] = adx_vals
        return result

    def _calculate_up_fractal(self, high):
        """Calculate Williams Up Fractal (swing high)"""
        result = pd.Series(False, index=high.index)
        n = self.fractalN
        
        for bar_idx in range(n, len(high) - n):
            pivot_high = high.iloc[bar_idx]
            
            # Check if all previous n bars are lower
            all_before_lower = all(high.iloc[bar_idx - i] < pivot_high for i in range(1, n + 1))
            
            # Check if at least one pattern of future bars is lower
            future_valid = False
            
            # Check n different patterns for future bars
            for pattern in range(n + 1):
                if pattern == 0:
                    # All next n bars lower
                    if all(high.iloc[bar_idx + i] < pivot_high for i in range(1, n + 1)):
                        future_valid = True
                        break
                else:
                    # First 'pattern' bars <= pivot, rest lower
                    if (all(high.iloc[bar_idx + i] <= pivot_high for i in range(1, pattern + 1)) and
                        all(high.iloc[bar_idx + i] < pivot_high for i in range(pattern + 1, n + 1))):
                        future_valid = True
                        break
            
            result.iloc[bar_idx] = all_before_lower and future_valid
        
        return result

    def _calculate_down_fractal(self, low):
        """Calculate Williams Down Fractal (swing low)"""
        result = pd.Series(False, index=low.index)
        n = self.fractalN
        
        for bar_idx in range(n, len(low) - n):
            pivot_low = low.iloc[bar_idx]
            
            # Check if all previous n bars are higher
            all_before_higher = all(low.iloc[bar_idx - i] > pivot_low for i in range(1, n + 1))
            
            # Check if at least one pattern of future bars is higher
            future_valid = False
            
            # Check n different patterns for future bars
            for pattern in range(n + 1):
                if pattern == 0:
                    # All next n bars higher
                    if all(low.iloc[bar_idx + i] > pivot_low for i in range(1, n + 1)):
                        future_valid = True
                        break
                else:
                    # First 'pattern' bars >= pivot, rest higher
                    if (all(low.iloc[bar_idx + i] >= pivot_low for i in range(1, pattern + 1)) and
                        all(low.iloc[bar_idx + i] > pivot_low for i in range(pattern + 1, n + 1))):
                        future_valid = True
                        break
            
            result.iloc[bar_idx] = all_before_higher and future_valid
        
        return result

    def next(self):
        current_idx = len(self.data) - 1
        
        # ADX condition
        adx_ok = self.adxValue[-1] > self.adxThreshold if not np.isnan(self.adxValue[-1]) else False
        adx_cond = adx_ok if self.useAdx else True
        
        # Trend conditions
        trend_bull = self.emaFast[-1] > self.emaSlow[-1]
        trend_bear = self.emaFast[-1] < self.emaSlow[-1]
        
        # Pullback conditions (clean PDF - Pull Down Formation)
        pullback_bull = (self.data.Low[-1] <= self.emaFast[-1] and 
                        self.data.Close[-1] >= self.emaFast[-1] and 
                        self.data.Low[-1] > self.emaSlow[-1])
        pullback_bear = (self.data.High[-1] >= self.emaFast[-1] and 
                        self.data.Close[-1] <= self.emaFast[-1] and 
                        self.data.High[-1] < self.emaSlow[-1])
        
        # Setup (candle A)
        setup_bull = adx_cond and trend_bull and pullback_bull
        setup_bear = adx_cond and trend_bear and pullback_bear
        
        # Check previous bar setup
        if current_idx > 0:
            prev_setup_bull = False
            prev_setup_bear = False
            if current_idx >= 1:
                prev_ema_fast_1 = self.emaFast[-2]
                prev_ema_slow_1 = self.emaSlow[-2]
                prev_trend_bull = prev_ema_fast_1 > prev_ema_slow_1
                prev_trend_bear = prev_ema_fast_1 < prev_ema_slow_1
                
                prev_pullback_bull = (self.data.Low[-2] <= prev_ema_fast_1 and 
                                     self.data.Close[-2] >= prev_ema_fast_1 and 
                                     self.data.Low[-2] > prev_ema_slow_1)
                prev_pullback_bear = (self.data.High[-2] >= prev_ema_fast_1 and 
                                     self.data.Close[-2] <= prev_ema_fast_1 and 
                                     self.data.High[-2] < prev_ema_slow_1)
                
                prev_adx = self.adxValue[-2] if not np.isnan(self.adxValue[-2]) else 0
                prev_adx_ok = prev_adx > self.adxThreshold
                prev_adx_cond = prev_adx_ok if self.useAdx else True
                
                prev_setup_bull = prev_adx_cond and prev_trend_bull and prev_pullback_bull
                prev_setup_bear = prev_adx_cond and prev_trend_bear and prev_pullback_bear
            
            # Trigger (candle B) - high/low breakout
            buy_entry = prev_setup_bull and self.data.High[-1] > self.data.High[-2]
            sell_entry = prev_setup_bear and self.data.Low[-1] < self.data.Low[-2]
            
            if buy_entry and not self.position:
                self.buy()
            elif sell_entry and not self.position:
                self.sell()
        
        # Exit conditions
        if self.position:
            if self.position.is_long:
                # Exit long if price closes below slow EMA
                if self.data.Close[-1] < self.emaSlow[-1]:
                    self.position.close()
            else:
                # Exit short if price closes above slow EMA
                if self.data.Close[-1] > self.emaSlow[-1]:
                    self.position.close()