"""
DS-TV Backtest Results: timeframe-structure-analysis-with-emasma-rsi-confirmation
============================================================

--- SPY ---
  Return                    -33.71%
  Buy & Hold Return         40.20%
  Max Drawdown              -33.73%
  Sharpe Ratio              -1.49
  Sortino Ratio             -1.71
  Calmar Ratio              -0.55
  Profit Factor             0.17
  Expectancy                -3.11%
  SQN                       -2.14
  # Trades                  12
  Win Rate                  16.67%
  Best Trade                5.29%
  Worst Trade               -11.84%
  Avg Trade                 -3.23%
  Exposure Time             89.00%
  Equity Final              66290.16$
  Equity Peak               100000.00$
  Avg Drawdown              -33.73%
  Max Drawdown Duration     651 days 00:00:00
  Max Trade Duration        267 days 00:00:00
  Avg Trade Duration        54 days 00:00:00
  Ann. Return               -18.72%
  Ann. Volatility           12.53%

--- BTC ---
  Return                    -37.77%
  Buy & Hold Return         0.29%
  Max Drawdown              -51.82%
  Sharpe Ratio              -0.92
  Sortino Ratio             -0.98
  Calmar Ratio              -0.41
  Profit Factor             0.17
  Expectancy                -6.77%
  SQN                       -1.13
  # Trades                  9
  Win Rate                  44.44%
  Best Trade                6.76%
  Worst Trade               -53.18%
  Avg Trade                 -9.00%
  Exposure Time             36.53%
  Equity Final              62234.85$
  Equity Peak               101341.14$
  Avg Drawdown              -33.84%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        82 days 00:00:00
  Avg Trade Duration        30 days 00:00:00
  Ann. Return               -21.09%
  Ann. Volatility           23.02%

--- QQQ ---
  Return                    -24.76%
  Buy & Hold Return         45.93%
  Max Drawdown              -38.01%
  Sharpe Ratio              -0.78
  Sortino Ratio             -0.97
  Calmar Ratio              -0.35
  Profit Factor             0.25
  Expectancy                -2.42%
  SQN                       -1.40
  # Trades                  11
  Win Rate                  27.27%
  Best Trade                6.00%
  Worst Trade               -15.64%
  Avg Trade                 -2.57%
  Exposure Time             87.80%
  Equity Final              75240.76$
  Equity Peak               115039.08$
  Avg Drawdown              -6.14%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        267 days 00:00:00
  Avg Trade Duration        59 days 00:00:00
  Ann. Return               -13.36%
  Ann. Volatility           17.16%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — timeframe-structure-analysis-with-emasma-rsi-confirmation
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # MA Filter Settings
    useMA = True
    maType = "EMA"
    maLength = 50
    
    # RSI Settings
    rsiLength = 14
    
    # Structure Settings
    lookback = 3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate MA
        if self.maType == "EMA":
            self.ma = self.I(pta.ema, close, length=self.maLength)
        else:
            self.ma = self.I(pta.sma, close, length=self.maLength)
        
        # Calculate RSI
        self.rsi = self.I(pta.rsi, close, length=self.rsiLength)
        
        # Calculate highest high and lowest low for trend detection
        self.highest_high = self.I(lambda: high.rolling(self.lookback).max())
        self.lowest_low = self.I(lambda: low.rolling(self.lookback).min())
        
        # Store trend state
        self.trend = 0
        self.last_high = None
        self.last_low = None

    def next(self):
        # Get current values
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_ma = self.ma[-1]
        
        # Initialize last_high and last_low on first bar
        if self.last_high is None:
            self.last_high = current_high
            self.last_low = current_low
        
        # Get highest/lowest from lookback period
        if len(self.highest_high) > 0 and not np.isnan(self.highest_high[-1]):
            hi = self.highest_high[-1]
        else:
            hi = current_high
            
        if len(self.lowest_low) > 0 and not np.isnan(self.lowest_low[-1]):
            lo = self.lowest_low[-1]
        else:
            lo = current_low
        
        # Trend detection logic
        new_trend = self.trend
        
        if current_close > self.last_high and (not self.useMA or current_close > current_ma):
            new_trend = 1
        elif current_close < self.last_low and (not self.useMA or current_close < current_ma):
            new_trend = -1
        
        # Update last high/low based on new trend
        if new_trend == 1:
            self.last_high = hi
            self.last_low = lo
        elif new_trend == -1:
            self.last_low = lo
            self.last_high = hi
        
        # Detect trend changes
        trend_changed_bullish = (self.trend != 1 and new_trend == 1)
        trend_changed_bearish = (self.trend != -1 and new_trend == -1)
        
        self.trend = new_trend
        
        # Trading logic: Buy on bullish trend change, Sell on bearish trend change
        if trend_changed_bullish:
            if not self.position:
                self.buy()
        elif trend_changed_bearish:
            if self.position:
                self.sell()