"""
DS-TV Backtest Results: trend-filter-fast-response-replace-sma20-with-sma9-for-quicker-trend-responsiven
============================================================

--- SPY ---
  Return                    -35.39%
  Buy & Hold Return         40.02%
  Max Drawdown              -37.92%
  Sharpe Ratio              -1.28
  Sortino Ratio             -1.47
  Calmar Ratio              -0.52
  Profit Factor             0.24
  Expectancy                -2.50%
  SQN                       -0.63
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                1.61%
  Worst Trade               -6.61%
  Avg Trade                 -2.58%
  Exposure Time             16.60%
  Equity Final              64614.80$
  Equity Peak               103641.09$
  Avg Drawdown              -19.48%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        87 days 00:00:00
  Avg Trade Duration        60 days 00:00:00
  Ann. Return               -19.76%
  Ann. Volatility           15.38%

--- BTC ---
  Return                    -29.48%
  Buy & Hold Return         34.01%
  Max Drawdown              -46.27%
  Sharpe Ratio              -0.70
  Sortino Ratio             -0.80
  Calmar Ratio              -0.35
  Profit Factor             0.00
  Expectancy                -44.12%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -44.12%
  Worst Trade               -44.12%
  Avg Trade                 -44.12%
  Exposure Time             28.45%
  Equity Final              70521.90$
  Equity Peak               112803.48$
  Avg Drawdown              -18.72%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        207 days 00:00:00
  Avg Trade Duration        207 days 00:00:00
  Ann. Return               -16.00%
  Ann. Volatility           22.97%

--- QQQ ---
  Return                    -39.59%
  Buy & Hold Return         42.20%
  Max Drawdown              -46.56%
  Sharpe Ratio              -1.04
  Sortino Ratio             -1.21
  Calmar Ratio              -0.48
  Profit Factor             0.00
  Expectancy                -1.88%
  SQN                       -1.10
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -0.17%
  Worst Trade               -3.60%
  Avg Trade                 -1.90%
  Exposure Time             20.20%
  Equity Final              60410.27$
  Equity Peak               104777.13$
  Avg Drawdown              -12.75%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        119 days 00:00:00
  Avg Trade Duration        72 days 00:00:00
  Ann. Return               -22.43%
  Ann. Volatility           21.53%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trend-filter-fast-response-replace-sma20-with-sma9-for-quicker-trend-responsiven
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy


class TvStrategy(Strategy):
    lookback = 6
    smaLen = 9
    atrLen = 7
    atrMultSL = 1.8
    rrRatio = 1.5
    useVolumeFilter = True
    cooldownBars = 3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        volume = pd.Series(self.data.Volume)
        
        # Trend filter
        self.smaFast = self.I(pta.sma, close, length=self.smaLen)
        
        # Support/Resistance
        self.recentLow = self.I(lambda: low.rolling(self.lookback).min())
        self.recentHigh = self.I(lambda: high.rolling(self.lookback).max())
        
        # Candle patterns
        self.body = self.I(lambda: np.abs(open_ - close))
        self.candleRange = self.I(lambda: high - low)
        self.lowerShadow = self.I(lambda: np.minimum(open_, close) - low)
        self.upperShadow = self.I(lambda: high - np.maximum(open_, close))
        
        # ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        # Volume filter
        self.volAvg = self.I(pta.sma, volume, length=5)
        
        # Previous candle values
        self.prev_open = self.I(lambda: open_.shift(1))
        self.prev_close = self.I(lambda: close.shift(1))
        self.prev_high = self.I(lambda: high.shift(1))
        self.prev_low = self.I(lambda: low.shift(1))
        
        self.last_trade_bar = -999

    def next(self):
        if len(self.data) < self.lookback + 2:
            return
        
        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        
        if (self.smaFast[-1] is None or self.atr[-1] is None or 
            self.recentLow[-1] is None or self.recentHigh[-1] is None):
            return
        
        # Trend filter
        uptrend = close > self.smaFast[-1]
        downtrend = close < self.smaFast[-1]
        
        # Support/Resistance
        nearSupport = low <= self.recentLow[-1] * 1.002
        nearResistance = high >= self.recentHigh[-1] * 0.998
        
        # Pin Bar logic
        isBullPin = (self.lowerShadow[-1] >= 2 * self.body[-1] and 
                     self.upperShadow[-1] <= 0.3 * self.body[-1] and 
                     self.candleRange[-1] > self.atr[-1] * 0.5)
        
        isBearPin = (self.upperShadow[-1] >= 2 * self.body[-1] and 
                     self.lowerShadow[-1] <= 0.3 * self.body[-1] and 
                     self.candleRange[-1] > self.atr[-1] * 0.5)
        
        # Engulfing patterns
        bullEngulf = (self.prev_open[-1] > self.prev_close[-1] and 
                      close > open_ and 
                      close > self.prev_open[-1] and 
                      open_ < self.prev_close[-1])
        
        bearEngulf = (self.prev_open[-1] < self.prev_close[-1] and 
                      close < open_ and 
                      close < self.prev_open[-1] and 
                      open_ > self.prev_close[-1])
        
        # Volume filter
        volOK = (not self.useVolumeFilter or 
                 (self.volAvg[-1] is not None and volume >= self.volAvg[-1] * 1.2))
        
        # Signals
        bullishPattern = isBullPin or bullEngulf
        bearishPattern = isBearPin or bearEngulf
        
        longSignal = (uptrend and nearSupport and bullishPattern and 
                      close > self.prev_high[-1] and volOK)
        
        shortSignal = (downtrend and nearResistance and bearishPattern and 
                       close < self.prev_low[-1] and volOK)
        
        # Cooldown control
        current_bar = len(self.data) - 1
        inCooldown = (current_bar - self.last_trade_bar) <= self.cooldownBars
        
        if longSignal and not inCooldown:
            if self.position:
                self.position.close()
            
            sl = self.prev_low[-1] - self.atrMultSL * self.atr[-1]
            tp = close + self.rrRatio * (close - sl)
            
            self.buy()
            self.last_trade_bar = current_bar
        
        elif shortSignal and not inCooldown:
            if self.position:
                self.position.close()
            
            sl = self.prev_high[-1] + self.atrMultSL * self.atr[-1]
            tp = close - self.rrRatio * (sl - close)
            
            self.sell()
            self.last_trade_bar = current_bar


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)