"""
DS-TV Backtest Results: two-candle-comparison-tmp-v-50
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         17.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         17.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — two-candle-comparison-tmp-v-50
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        volume = pd.Series(self.data.Volume)
        
        # Moving Averages
        self.shortMA = self.I(pta.ema, close, length=21)
        self.middleMA = self.I(pta.ema, close, length=50)
        self.longMA = self.I(pta.ema, close, length=100)
        self.highMA = self.I(pta.ema, close, length=200)
        
        # SMI (Stochastic Momentum Index)
        def calc_smi():
            a = 5
            b = 3
            ll = low.rolling(window=a).min()
            hh = high.rolling(window=a).max()
            diff = hh - ll
            rdiff = close - (hh + ll) / 2
            avgrel = pta.ema(pta.ema(rdiff, length=b), length=b)
            avgdiff = pta.ema(pta.ema(diff, length=b), length=b)
            smi = pd.Series(np.where(avgdiff != 0, (avgrel / (avgdiff / 2) * 100), 0), index=close.index)
            return smi
        
        self.SMI = self.I(calc_smi)
        
        # Volume SMA for volume spike filter
        self.vol_sma = self.I(pta.sma, volume, length=13)
        
        self.signal = None

    def next(self):
        if len(self.data) < 2:
            return
        
        # Current bar data
        curr_open = self.data.Open[-1]
        curr_close = self.data.Close[-1]
        curr_high = self.data.High[-1]
        curr_low = self.data.Low[-1]
        
        # Previous bar data
        prev_open = self.data.Open[-2]
        prev_close = self.data.Close[-2]
        prev_high = self.data.High[-2]
        prev_low = self.data.Low[-2]
        
        # Moving averages current values
        short_ma = self.shortMA[-1]
        middle_ma = self.middleMA[-1]
        long_ma = self.longMA[-1]
        high_ma = self.highMA[-1]
        smi = self.SMI[-1]
        
        # Volume spike check
        curr_vol = self.data.Volume[-1]
        vol_avg = self.vol_sma[-1]
        vol_spike = vol_avg > 0 and (curr_vol / vol_avg) > 1.5
        
        # Close Comparison Logic (Bullish Signal)
        bull_signal = (
            curr_low <= prev_low and
            prev_close < prev_open and
            curr_close > curr_open and
            (curr_open - curr_low) >= (curr_high - curr_close) and
            curr_close > prev_open and
            long_ma < middle_ma and
            middle_ma < short_ma and
            high_ma < long_ma and
            (curr_open - curr_low) < 2 * (curr_close - curr_open) and
            curr_low <= short_ma
        )
        
        # Close Comparison Logic (Bearish Signal)
        bear_signal = (
            curr_high >= prev_high and
            prev_close > prev_open and
            curr_close < curr_open and
            (curr_high - curr_open) >= (curr_close - curr_low) and
            curr_close < prev_open and
            long_ma > middle_ma and
            middle_ma > short_ma and
            high_ma > long_ma and
            (curr_high - curr_open) < 2 * (curr_open - curr_close) and
            curr_high >= short_ma
        )
        
        # Trading Logic
        if bull_signal and vol_spike:
            if self.position:
                self.position.close()
            self.buy()
            self.signal = "Bull"
        elif bear_signal and vol_spike:
            if self.position:
                self.position.close()
            self.signal = "Bear"
        
        # Exit logic - simple trailing based on opposite signal
        if self.position and bear_signal:
            self.position.close()
        elif not self.position and bull_signal:
            pass  # Already entered above


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, commission=.002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()