"""
DS-TV Backtest Results: ultimate-mtf-trend-dashboard-identityka
============================================================

--- SPY ---
  Return                    -45.13%
  Buy & Hold Return         41.68%
  Max Drawdown              -45.48%
  Sharpe Ratio              -2.13
  Sortino Ratio             -1.91
  Calmar Ratio              -0.57
  Profit Factor             0.29
  Expectancy                -1.32%
  SQN                       -2.40
  # Trades                  42
  Win Rate                  26.19%
  Best Trade                11.90%
  Worst Trade               -14.48%
  Avg Trade                 -1.38%
  Exposure Time             84.40%
  Equity Final              54872.55$
  Equity Peak               100645.77$
  Avg Drawdown              -25.71%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        41 days 00:00:00
  Avg Trade Duration        15 days 00:00:00
  Ann. Return               -26.10%
  Ann. Volatility           12.25%

--- BTC ---
  Return                    -24.06%
  Buy & Hold Return         2.97%
  Max Drawdown              -35.79%
  Sharpe Ratio              -0.60
  Sortino Ratio             -0.76
  Calmar Ratio              -0.36
  Profit Factor             0.70
  Expectancy                -1.15%
  SQN                       -0.73
  # Trades                  25
  Win Rate                  24.00%
  Best Trade                26.19%
  Worst Trade               -12.90%
  Avg Trade                 -1.52%
  Exposure Time             37.07%
  Equity Final              75937.07$
  Equity Peak               115645.13$
  Avg Drawdown              -7.77%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        25 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -12.84%
  Ann. Volatility           21.39%

--- QQQ ---
  Return                    -50.65%
  Buy & Hold Return         47.15%
  Max Drawdown              -53.80%
  Sharpe Ratio              -2.08
  Sortino Ratio             -1.79
  Calmar Ratio              -0.56
  Profit Factor             0.36
  Expectancy                -1.68%
  SQN                       -2.19
  # Trades                  38
  Win Rate                  23.68%
  Best Trade                16.07%
  Worst Trade               -16.40%
  Avg Trade                 -1.79%
  Exposure Time             84.00%
  Equity Final              49346.27$
  Equity Peak               106807.41$
  Avg Drawdown              -9.69%
  Max Drawdown Duration     551 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        17 days 00:00:00
  Ann. Return               -29.95%
  Ann. Volatility           14.40%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ultimate-mtf-trend-dashboard-identityka
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    fastLen = 14
    slowLen = 50

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate HMA (Hull Moving Average) using pandas_ta
        # HMA is not directly in pandas_ta, so we'll implement it manually
        def hma(src, length):
            if len(src) < length:
                return pd.Series(np.nan, index=src.index)
            half_length = length // 2
            sqrt_length = int(np.sqrt(length))
            
            wma1 = pta.wma(src, length=half_length)
            wma2 = pta.wma(src, length=length)
            raw_hma = 2 * wma1 - wma2
            hma_result = pta.wma(raw_hma, length=sqrt_length)
            return hma_result
        
        # Fast and Slow HMA
        self.fastMA = self.I(lambda: hma(close, self.fastLen))
        self.slowMA = self.I(lambda: hma(close, self.slowLen))

    def next(self):
        # Get current values
        if len(self.data) < 2:
            return
        
        fast_current = self.fastMA[-1] if len(self.fastMA) > 0 else np.nan
        slow_current = self.slowMA[-1] if len(self.slowMA) > 0 else np.nan
        
        # Handle NaN values
        if pd.isna(fast_current) or pd.isna(slow_current):
            return
        
        fast_prev = self.fastMA[-2] if len(self.fastMA) > 1 else np.nan
        slow_prev = self.slowMA[-2] if len(self.slowMA) > 1 else np.nan
        
        if pd.isna(fast_prev) or pd.isna(slow_prev):
            return
        
        # Long condition: fast MA crosses above slow MA
        long_cond = fast_prev <= slow_prev and fast_current > slow_current
        
        # Short condition: fast MA crosses below slow MA
        short_cond = fast_prev >= slow_prev and fast_current < slow_current
        
        # Trading logic
        if long_cond:
            if self.position.is_short:
                self.position.close()
            self.buy()
        elif short_cond:
            if self.position.is_long:
                self.position.close()
            self.sell()


if __name__ == "__main__":
    # Load your data here
    # Example: data = yf.download("AAPL", start="2020-01-01", end="2024-01-01")
    
    # For demonstration, create sample data
    dates = pd.date_range(start="2020-01-01", end="2024-01-01", freq="D")
    np.random.seed(42)
    close_prices = 100 + np.cumsum(np.random.randn(len(dates)) * 2)
    
    data = pd.DataFrame({
        'Open': close_prices + np.random.randn(len(dates)),
        'High': close_prices + abs(np.random.randn(len(dates))),
        'Low': close_prices - abs(np.random.randn(len(dates))),
        'Close': close_prices,
        'Volume': np.random.randint(1000000, 10000000, len(dates))
    }, index=dates)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()