"""
DS-TV Backtest Results: vwap-lights-2x-gx-vwap-true-hodlod-anchors
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — vwap-lights-2x-gx-vwap-true-hodlod-anchors
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime, timedelta


class TvStrategy(Strategy):
    def init(self):
        self.gx_vwap = None
        self.rth_vwap = None
        self.hod_vwap = None
        self.lod_vwap = None
        
        self.gx_cum_pv = 0
        self.gx_cum_v = 0
        self.gx_key_prev = None
        
        self.rth_cum_pv = 0
        self.rth_cum_v = 0
        self.rth_started = False
        self.rth_active_prev = False
        
        self.hod = None
        self.hod_cum_pv = 0
        self.hod_cum_v = 0
        
        self.lod = None
        self.lod_cum_pv = 0
        self.lod_cum_v = 0
        
        self.in_rth = False

    def _gx_key(self, timestamp):
        dt = pd.Timestamp(timestamp, tz='America/Denver')
        h = dt.hour
        m = dt.minute
        mins = h * 60 + m
        
        if mins < 16 * 60:
            dt = dt - pd.Timedelta(days=1)
        
        return dt.year * 10000 + dt.month * 100 + dt.day

    def _in_session(self, timestamp, start_time="07:30", end_time="14:00"):
        dt = pd.Timestamp(timestamp, tz='America/Denver')
        h = dt.hour
        m = dt.minute
        mins = h * 60 + m
        
        start_mins = int(start_time.split(":")[0]) * 60 + int(start_time.split(":")[1])
        end_mins = int(end_time.split(":")[0]) * 60 + int(end_time.split(":")[1])
        
        return start_mins <= mins < end_mins

    def next(self):
        if len(self.data) < 2:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        hlc3 = (high + low + close) / 3
        
        timestamp = self.data.index[-1]
        
        gx_key = self._gx_key(timestamp)
        if self.gx_key_prev is None:
            self.gx_key_prev = gx_key
        
        if gx_key != self.gx_key_prev:
            self.gx_cum_pv = 0
            self.gx_cum_v = 0
            self.gx_key_prev = gx_key
        
        self.gx_cum_pv += hlc3 * volume
        self.gx_cum_v += volume
        
        if self.gx_cum_v != 0:
            self.gx_vwap = self.gx_cum_pv / self.gx_cum_v
        
        self.in_rth = self._in_session(timestamp)
        
        if self.in_rth and not self.rth_active_prev:
            self.rth_started = True
            self.rth_cum_pv = hlc3 * volume
            self.rth_cum_v = volume
        elif self.in_rth:
            self.rth_cum_pv += hlc3 * volume
            self.rth_cum_v += volume
            self.rth_started = False
        else:
            self.rth_started = False
        
        if self.in_rth and self.rth_cum_v != 0:
            self.rth_vwap = self.rth_cum_pv / self.rth_cum_v
        else:
            self.rth_vwap = None
        
        if self.in_rth:
            if self.hod is None or high > self.hod:
                self.hod = high
                self.hod_cum_pv = high * volume
                self.hod_cum_v = volume
            else:
                self.hod_cum_pv += high * volume
                self.hod_cum_v += volume
            
            if self.hod_cum_v != 0:
                self.hod_vwap = self.hod_cum_pv / self.hod_cum_v
            
            if self.lod is None or low < self.lod:
                self.lod = low
                self.lod_cum_pv = low * volume
                self.lod_cum_v = volume
            else:
                self.lod_cum_pv += low * volume
                self.lod_cum_v += volume
            
            if self.lod_cum_v != 0:
                self.lod_vwap = self.lod_cum_pv / self.lod_cum_v
        elif self.rth_active_prev:
            self.hod = None
            self.hod_cum_pv = 0
            self.hod_cum_v = 0
            self.hod_vwap = None
            
            self.lod = None
            self.lod_cum_pv = 0
            self.lod_cum_v = 0
            self.lod_vwap = None
        
        self.rth_active_prev = self.in_rth
        
        if self.gx_vwap is not None and self.rth_vwap is not None:
            if close > self.gx_vwap and close > self.rth_vwap:
                if not self.position:
                    self.buy()
            elif close < self.gx_vwap and close < self.rth_vwap:
                if self.position:
                    self.position.close()
        
        if self.hod_vwap is not None and self.lod_vwap is not None:
            if close > self.hod_vwap:
                if not self.position:
                    self.buy()
            elif close < self.lod_vwap:
                if self.position:
                    self.position.close()


if __name__ == "__main__":
    df = pd.read_csv("data.csv", index_col=0, parse_dates=True)
    
    bt = Backtest(df, TvStrategy, cash=100000, commission=0.001)
    stats = bt.run()
    print(stats)
    bt.plot()