"""
DS-TV Backtest Results: vwap-archi
============================================================

--- SPY ---
  Return                    -75.40%
  Buy & Hold Return         41.94%
  Max Drawdown              -75.40%
  Sharpe Ratio              -6.20
  Sortino Ratio             -3.68
  Calmar Ratio              -0.67
  Profit Factor             0.45
  Expectancy                -0.28%
  SQN                       -5.64
  # Trades                  494
  Win Rate                  33.00%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.28%
  Exposure Time             99.00%
  Equity Final              24597.51$
  Equity Peak               100000.00$
  Avg Drawdown              -75.40%
  Max Drawdown Duration     724 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -50.68%
  Ann. Volatility           8.18%

--- BTC ---
  Return                    -43.38%
  Buy & Hold Return         46.22%
  Max Drawdown              -43.87%
  Sharpe Ratio              -1.38
  Sortino Ratio             -1.34
  Calmar Ratio              -0.56
  Profit Factor             0.66
  Expectancy                -0.48%
  SQN                       -1.71
  # Trades                  164
  Win Rate                  46.34%
  Best Trade                8.14%
  Worst Trade               -12.38%
  Avg Trade                 -0.53%
  Exposure Time             23.67%
  Equity Final              56620.84$
  Equity Peak               100875.44$
  Avg Drawdown              -22.40%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        1 days 00:00:00
  Avg Trade Duration        1 days 00:00:00
  Ann. Return               -24.72%
  Ann. Volatility           17.92%

--- QQQ ---
  Return                    -76.83%
  Buy & Hold Return         42.67%
  Max Drawdown              -77.11%
  Sharpe Ratio              -5.15
  Sortino Ratio             -3.09
  Calmar Ratio              -0.68
  Profit Factor             0.55
  Expectancy                -0.29%
  SQN                       -4.50
  # Trades                  494
  Win Rate                  35.43%
  Best Trade                6.54%
  Worst Trade               -9.35%
  Avg Trade                 -0.30%
  Exposure Time             99.00%
  Equity Final              23171.22$
  Equity Peak               100000.00$
  Avg Drawdown              -77.11%
  Max Drawdown Duration     724 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -52.14%
  Ann. Volatility           10.13%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — vwap-archi
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate HLC3 (typical price)
        hlc3 = (high + low + close) / 3
        
        # Calculate anchored VWAP with standard deviation bands
        # We'll recalculate VWAP, upper/lower bands for each bar
        def calculate_vwap_bands():
            vwap_values = []
            upper1_values = []
            lower1_values = []
            upper2_values = []
            lower2_values = []
            upper3_values = []
            lower3_values = []
            
            sum_pv = 0.0
            sum_vol = 0.0
            sum_pv2 = 0.0
            prev_day = None
            
            for i in range(len(close)):
                current_day = pd.Timestamp(self.data.index[i]).date()
                
                # Check if new period (daily anchor)
                if prev_day is not None and current_day != prev_day:
                    sum_pv = 0.0
                    sum_vol = 0.0
                    sum_pv2 = 0.0
                
                prev_day = current_day
                
                # Accumulate VWAP values
                sum_pv += hlc3.iloc[i] * volume.iloc[i]
                sum_vol += volume.iloc[i]
                sum_pv2 += (hlc3.iloc[i] ** 2) * volume.iloc[i]
                
                if sum_vol > 0:
                    vwap = sum_pv / sum_vol
                    variance = (sum_pv2 / sum_vol) - (vwap ** 2)
                    stdev = np.sqrt(max(variance, 0))
                    
                    vwap_values.append(vwap)
                    upper1_values.append(vwap + stdev * 1.0)
                    lower1_values.append(vwap - stdev * 1.0)
                    upper2_values.append(vwap + stdev * 2.0)
                    lower2_values.append(vwap - stdev * 2.0)
                    upper3_values.append(vwap + stdev * 3.0)
                    lower3_values.append(vwap - stdev * 3.0)
                else:
                    vwap_values.append(np.nan)
                    upper1_values.append(np.nan)
                    lower1_values.append(np.nan)
                    upper2_values.append(np.nan)
                    lower2_values.append(np.nan)
                    upper3_values.append(np.nan)
                    lower3_values.append(np.nan)
            
            return (pd.Series(vwap_values), 
                    pd.Series(upper1_values), 
                    pd.Series(lower1_values),
                    pd.Series(upper2_values),
                    pd.Series(lower2_values),
                    pd.Series(upper3_values),
                    pd.Series(lower3_values))
        
        vwap_data = calculate_vwap_bands()
        self.vwap = self.I(lambda: vwap_data[0])
        self.upper1 = self.I(lambda: vwap_data[1])
        self.lower1 = self.I(lambda: vwap_data[2])
        self.upper2 = self.I(lambda: vwap_data[3])
        self.lower2 = self.I(lambda: vwap_data[4])
        self.upper3 = self.I(lambda: vwap_data[5])
        self.lower3 = self.I(lambda: vwap_data[6])

    def next(self):
        # Trading logic: Use VWAP bands for mean reversion
        # Buy when price touches lower band and is below VWAP
        # Sell when price touches upper band and is above VWAP
        
        if np.isnan(self.vwap[-1]):
            return
        
        close_price = self.data.Close[-1]
        
        # Buy signal: Price near or below lower 2σ band
        if close_price <= self.lower2[-1] and close_price < self.vwap[-1]:
            if not self.position:
                self.buy()
        
        # Sell signal: Price near or above upper 2σ band
        if close_price >= self.upper2[-1] and close_price > self.vwap[-1]:
            if self.position:
                self.sell()
        
        # Exit on VWAP crossover (mean reversion)
        if self.position:
            if close_price < self.vwap[-1]:
                self.sell()


if __name__ == "__main__":
    # Example backtest setup
    import yfinance as yf
    
    # Download sample data
    data = yf.download("AAPL", start="2022-01-01", end="2023-12-31")
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()