"""
DS-TV Backtest Results: xauusd-ema-stochastic-signal-indicator
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         17.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         17.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — xauusd-ema-stochastic-signal-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    emaFastLen = 50
    emaSlowLen = 200
    stochLen = 14
    smoothK = 3
    smoothD = 3
    swingLeft = 3
    swingRight = 3
    stopBufferTicks = 20
    rrMultiple = 1.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # EMA calculations
        self.ema50 = self.I(pta.ema, close, length=self.emaFastLen)
        self.ema200 = self.I(pta.ema, close, length=self.emaSlowLen)

        # Stochastic calculation
        stoch_result = self.I(lambda: pta.stoch(high, low, close, k=self.stochLen, d=self.smoothD, smooth_k=self.smoothK))
        
        # Extract K and D from stochastic result
        self.stoch_k = self.I(lambda: pta.stoch(high, low, close, k=self.stochLen, d=self.smoothD, smooth_k=self.smoothK))
        
        # Swing pivot calculations using rolling min/max
        self.pivot_low = self.I(lambda: low.rolling(window=2*self.swingRight+1, center=True).min())
        self.pivot_high = self.I(lambda: high.rolling(window=2*self.swingRight+1, center=True).max())

        # Track last swing levels
        self.last_swing_low = np.nan
        self.last_swing_high = np.nan

        # For tracking position state
        self.in_long = False
        self.in_short = False
        self.entry_price = 0
        self.stop_loss = 0
        self.take_profit = 0

    def next(self):
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]

        # Update swing levels
        if len(self.data) > 2 * self.swingRight + 1:
            pivot_low_val = self.pivot_low[-1]
            pivot_high_val = self.pivot_high[-1]

            if not np.isnan(pivot_low_val) and pivot_low_val == low:
                self.last_swing_low = pivot_low_val
            if not np.isnan(pivot_high_val) and pivot_high_val == high:
                self.last_swing_high = pivot_high_val

        # Trend determination
        ema50_val = self.ema50[-1]
        ema200_val = self.ema200[-1]

        bull_trend = close > ema50_val and close > ema200_val
        bear_trend = close < ema50_val and close < ema200_val

        # Stochastic signals
        if len(self.stoch_k) > 1:
            k_current = self.stoch_k[-1]
            k_prev = self.stoch_k[-2]

            buy_trigger = crossover(self.stoch_k, 20)
            sell_trigger = crossover(80, self.stoch_k)

            buy_signal = bull_trend and buy_trigger
            sell_signal = bear_trend and sell_trigger

            # Stop loss and take profit calculations
            buffer = self.stopBufferTicks * 0.01  # Assuming 0.01 as mintick for gold

            if buy_signal and not np.isnan(self.last_swing_low):
                long_sl = self.last_swing_low - buffer
                long_risk = close - long_sl

                if long_risk > 0:
                    long_tp = close + (long_risk * self.rrMultiple)

                    if not self.position:
                        self.buy()
                        self.in_long = True
                        self.entry_price = close
                        self.stop_loss = long_sl
                        self.take_profit = long_tp

            elif sell_signal and not np.isnan(self.last_swing_high):
                short_sl = self.last_swing_high + buffer
                short_risk = short_sl - close

                if short_risk > 0:
                    short_tp = close - (short_risk * self.rrMultiple)

                    if self.position:
                        self.sell()
                    self.in_short = True
                    self.entry_price = close
                    self.stop_loss = short_sl
                    self.take_profit = short_tp

            # Exit logic based on stop loss and take profit
            if self.position:
                if self.in_long:
                    if close <= self.stop_loss or close >= self.take_profit:
                        self.sell()
                        self.in_long = False
                elif self.in_short:
                    if close >= self.stop_loss or close <= self.take_profit:
                        self.buy()
                        self.in_short = False


if __name__ == '__main__':
    from backtesting.test import GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)