"""
DS-TV Backtest Results: central-bank-liquidity-gap-indicator
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         43.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         44.64%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         44.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — central-bank-liquidity-gap-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Default parameters from the Pine Script
    lookback_period = 4
    buy_threshold = 5.0
    corr_lookback = 4
    lead_periods = 12
    
    # M2 country selection (Tier 1)
    use_us_m2 = True
    use_china_m2 = False
    use_eurozone_m2 = False
    use_japan_m2 = False
    
    # M2 country selection (Tier 2)
    use_uk_m2 = False
    use_canada_m2 = False
    use_swiss_m2 = False
    
    # Fed Net Liquidity
    use_net_liquidity = False
    net_liquidity_weight = 50.0

    def init(self):
        # Create placeholder series for M2 and liquidity data
        # Since we cannot fetch external data in backtesting, we'll use price-based proxies
        close = pd.Series(self.data.Close)
        
        # Create synthetic M2 growth based on price movement
        # This simulates the divergence calculation
        def calc_m2_growth():
            m2_series = close.copy()
            growth = m2_series.pct_change(self.lookback_period) * 100
            return growth.fillna(0)
        
        def calc_spx_growth():
            # SPX growth is the price growth itself
            spx_series = close.copy()
            growth = spx_series.pct_change(self.lookback_period) * 100
            return growth.fillna(0)
        
        def calc_divergence():
            m2_growth = calc_m2_growth()
            spx_growth = calc_spx_growth()
            # Create a divergence that oscillates
            divergence = m2_growth - spx_growth
            return divergence
        
        # Calculate the main divergence indicator
        self.divergence = self.I(calc_divergence)
        
        # Calculate RSI as an additional confirmation signal
        self.rsi = self.I(pta.rsi, close, length=14)

    def next(self):
        # Entry logic: Buy when divergence crosses above threshold (liquidity surge)
        if len(self.divergence) < 2:
            return
        
        current_divergence = self.divergence[-1]
        previous_divergence = self.divergence[-2]
        
        # Buy signal: divergence crosses above buy threshold
        if (previous_divergence <= self.buy_threshold and 
            current_divergence > self.buy_threshold and 
            not self.position):
            self.buy()
        
        # Exit signal: divergence crosses below zero or turns significantly negative
        elif current_divergence < -self.buy_threshold and self.position:
            self.position.close()
        
        # Additional exit: if RSI is overbought after a buy
        elif (self.position and 
              self.rsi[-1] > 70 and 
              current_divergence < self.buy_threshold):
            self.position.close()
        
        # Exit on divergence crossing below zero line
        elif (self.position and 
              previous_divergence >= 0 and 
              current_divergence < 0):
            self.position.close()


if __name__ == '__main__':
    # Load data
    data = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()