"""
DS-TV Backtest Results: 52-week-highlow-with-momentum-filter-atr-stop
============================================================

--- SPY ---
  Return                    5.91%
  Buy & Hold Return         16.36%
  Max Drawdown              -10.10%
  Sharpe Ratio              0.39
  Sortino Ratio             0.54
  Calmar Ratio              0.29
  Profit Factor             0.00
  Expectancy                -8.48%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -8.48%
  Worst Trade               -8.48%
  Avg Trade                 -8.48%
  Exposure Time             3.40%
  Equity Final              105912.35$
  Equity Peak               106146.43$
  Avg Drawdown              -2.43%
  Max Drawdown Duration     211 days 00:00:00
  Max Trade Duration        25 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               2.94%
  Ann. Volatility           7.52%

--- BTC ---
  Return                    14.66%
  Buy & Hold Return         2.09%
  Max Drawdown              -21.23%
  Sharpe Ratio              0.29
  Sortino Ratio             0.47
  Calmar Ratio              0.33
  Profit Factor             nan
  Expectancy                10.46%
  SQN                       1.27
  # Trades                  2
  Win Rate                  100.00%
  Best Trade                19.43%
  Worst Trade               1.50%
  Avg Trade                 10.10%
  Exposure Time             41.04%
  Equity Final              114658.29$
  Equity Peak               138716.53$
  Avg Drawdown              -4.67%
  Max Drawdown Duration     385 days 00:00:00
  Max Trade Duration        160 days 00:00:00
  Avg Trade Duration        149 days 00:00:00
  Ann. Return               7.07%
  Ann. Volatility           24.05%

--- QQQ ---
  Return                    6.65%
  Buy & Hold Return         16.87%
  Max Drawdown              -9.78%
  Sharpe Ratio              0.33
  Sortino Ratio             0.46
  Calmar Ratio              0.34
  Profit Factor             0.00
  Expectancy                -9.30%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -9.30%
  Worst Trade               -9.30%
  Avg Trade                 -9.30%
  Exposure Time             3.00%
  Equity Final              106654.66$
  Equity Peak               110223.99$
  Avg Drawdown              -3.11%
  Max Drawdown Duration     202 days 00:00:00
  Max Trade Duration        21 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               3.30%
  Ann. Volatility           9.91%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 52-week-highlow-with-momentum-filter-atr-stop
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLen = 14

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        lookbackPeriod = 252
        
        # 52-Week High/Low
        self.highest_high = self.I(lambda: high.rolling(lookbackPeriod).max())
        self.lowest_low = self.I(lambda: low.rolling(lookbackPeriod).min())
        
        # EMAs and SMA
        self.ema21 = self.I(pta.ema, close, length=21)
        self.ema50 = self.I(pta.ema, close, length=50)
        self.sma200 = self.I(pta.sma, close, length=200)
        
        # ATR Stop
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        self.offset_line = self.I(lambda: close - (self.atr[-1] if self.atr[-1] is not None else 0) * 1.5)

    def next(self):
        # Check if we have valid data
        if len(self.data) < 200:
            return
        
        # Get current values
        close = self.data.Close[-1]
        ema21 = self.ema21[-1]
        ema50 = self.ema50[-1]
        sma200 = self.sma200[-1]
        highest_high = self.highest_high[-1]
        lowest_low = self.lowest_low[-1]
        atr = self.atr[-1]
        
        # Skip if any indicator is NaN
        if pd.isna(ema21) or pd.isna(ema50) or pd.isna(sma200) or pd.isna(highest_high) or pd.isna(lowest_low) or pd.isna(atr):
            return
        
        # Entry logic: Buy when price is near 52-week low and above moving averages
        if close > lowest_low and close > ema21 and ema21 > ema50 and ema50 > sma200:
            if not self.position:
                self.buy()
        
        # Exit logic: Sell when price touches ATR stop or when it falls below key moving averages
        if self.position:
            stop_level = close - atr * 1.5
            if close <= stop_level or close < sma200:
                self.position.close()


if __name__ == '__main__':
    # Example backtest setup (adjust with your own data)
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)