"""
DS-TV Backtest Results: aa-smart-structure-engine
============================================================

--- SPY ---
  Return                    -21.76%
  Buy & Hold Return         40.02%
  Max Drawdown              -29.04%
  Sharpe Ratio              -0.88
  Sortino Ratio             -1.11
  Calmar Ratio              -0.40
  Profit Factor             0.16
  Expectancy                -3.03%
  SQN                       -1.58
  # Trades                  6
  Win Rate                  33.33%
  Best Trade                2.04%
  Worst Trade               -8.45%
  Avg Trade                 -3.12%
  Exposure Time             66.20%
  Equity Final              78238.90$
  Equity Peak               109984.97$
  Avg Drawdown              -8.59%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        160 days 00:00:00
  Avg Trade Duration        81 days 00:00:00
  Ann. Return               -11.63%
  Ann. Volatility           13.19%

--- BTC ---
  Return                    -30.90%
  Buy & Hold Return         37.68%
  Max Drawdown              -41.69%
  Sharpe Ratio              -0.92
  Sortino Ratio             -0.99
  Calmar Ratio              -0.40
  Profit Factor             0.19
  Expectancy                -8.21%
  SQN                       -1.00
  # Trades                  6
  Win Rate                  33.33%
  Best Trade                8.58%
  Worst Trade               -47.22%
  Avg Trade                 -10.52%
  Exposure Time             34.34%
  Equity Final              69099.42$
  Equity Peak               108534.02$
  Avg Drawdown              -10.64%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        70 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               -16.85%
  Ann. Volatility           18.27%

--- QQQ ---
  Return                    -22.05%
  Buy & Hold Return         42.20%
  Max Drawdown              -35.30%
  Sharpe Ratio              -0.70
  Sortino Ratio             -0.89
  Calmar Ratio              -0.33
  Profit Factor             0.05
  Expectancy                -6.96%
  SQN                       -1.48
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                1.09%
  Worst Trade               -14.32%
  Avg Trade                 -7.17%
  Exposure Time             64.20%
  Equity Final              77946.13$
  Equity Peak               116228.07$
  Avg Drawdown              -7.94%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        385 days 00:00:00
  Avg Trade Duration        156 days 00:00:00
  Ann. Return               -11.80%
  Ann. Volatility           16.98%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — aa-smart-structure-engine
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    pivotLen = 4
    atrLen = 7
    impulseFactor = 1.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        
        # Calculate ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        # Calculate pivot highs and lows
        self.ph = self.I(self._pivot_high, high, self.pivotLen)
        self.pl = self.I(self._pivot_low, low, self.pivotLen)
        
        # Calculate candle properties
        self.body = self.I(lambda: np.abs(close - open_))
        self.candleRange = self.I(lambda: high - low)
        
        # Storage for structure tracking
        self.lastHigh = np.nan
        self.prevHigh = np.nan
        self.lastLow = np.nan
        self.prevLow = np.nan
        self.lastSignal = 0

    def _pivot_high(self, high, length):
        """Calculate pivot highs"""
        result = pd.Series(np.nan, index=high.index)
        for i in range(length, len(high) - length):
            if high.iloc[i] == high.iloc[i-length:i+length+1].max():
                result.iloc[i] = high.iloc[i]
        return result

    def _pivot_low(self, low, length):
        """Calculate pivot lows"""
        result = pd.Series(np.nan, index=low.index)
        for i in range(length, len(low) - length):
            if low.iloc[i] == low.iloc[i-length:i+length+1].min():
                result.iloc[i] = low.iloc[i]
        return result

    def next(self):
        # Get current values
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_close = self.data.Close[-1]
        current_open = self.data.Open[-1]
        
        atr_val = self.atr[-1] if len(self.atr) > 0 and not np.isnan(self.atr[-1]) else 0
        body_val = self.body[-1] if len(self.body) > 0 else 0
        range_val = self.candleRange[-1] if len(self.candleRange) > 0 else 0
        
        # Update structure
        if len(self.ph) > 0 and not np.isnan(self.ph[-1]):
            self.prevHigh = self.lastHigh
            self.lastHigh = self.ph[-1]
        
        if len(self.pl) > 0 and not np.isnan(self.pl[-1]):
            self.prevLow = self.lastLow
            self.lastLow = self.pl[-1]
        
        # Calculate impulses
        bullImpulse = (current_close > current_open and 
                      body_val > range_val * 0.5 and 
                      body_val > atr_val * self.impulseFactor)
        
        bearImpulse = (current_close < current_open and 
                      body_val > range_val * 0.5 and 
                      body_val > atr_val * self.impulseFactor)
        
        # Structure types
        isHH = not np.isnan(self.prevHigh) and self.lastHigh > self.prevHigh
        isLH = not np.isnan(self.prevHigh) and self.lastHigh < self.prevHigh
        isLL = not np.isnan(self.prevLow) and self.lastLow < self.prevLow
        isHL = not np.isnan(self.prevLow) and self.lastLow > self.prevLow
        
        # Entry logic
        sellHH = isHH and current_close < current_open and bearImpulse
        sellLH = isLH and current_close < current_open and bearImpulse
        buyLL = isLL and current_close > current_open and bullImpulse
        buyHL = isHL and current_close > current_open and bullImpulse
        
        # Generate signals (no duplicate signals)
        buySignal = (buyLL or buyHL) and self.lastSignal != 1
        sellSignal = (sellHH or sellLH) and self.lastSignal != -1
        
        # Execute trades
        if buySignal:
            if not self.position:
                self.buy()
            self.lastSignal = 1
        
        if sellSignal:
            if self.position:
                self.sell()
            self.lastSignal = -1


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()