"""
DS-TV Backtest Results: ag-pro-market-regime-meter
============================================================

--- SPY ---
  ERROR: Indicator "calc_summ…" error. See traceback above.

--- BTC ---
  ERROR: Indicator "calc_summ…" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "calc_summ…" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ag-pro-market-regime-meter
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lenER = 20
    lenADX = 14
    lenCHOP = 14
    lenATR = 14
    volLook = 100

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Trend Score Calculation
        def calc_trend_score():
            net_move = (close - close.shift(self.lenER)).abs()
            denom_move = (close - close.shift(1)).abs().rolling(self.lenER).sum()
            denom_move = denom_move.replace(0, 1e-10)
            er_raw = net_move / denom_move
            er_raw = er_raw.clip(0, 1)
            
            adx_result = pta.adx(high, low, close, length=self.lenADX)
            if adx_result is not None and 'ADX_14' in adx_result.columns:
                adx_raw = adx_result['ADX_14']
            else:
                adx_raw = pd.Series(25, index=close.index)
            
            adx_norm = (adx_raw / 40.0).clip(0, 1)
            trend_score = (0.65 * er_raw + 0.35 * adx_norm).clip(0, 1)
            return trend_score
        
        self.trend_score = self.I(calc_trend_score)
        
        # Chop Score Calculation
        def calc_chop_score():
            tr = high - low
            sum_tr = tr.rolling(self.lenCHOP).sum()
            hh = high.rolling(self.lenCHOP).max()
            ll = low.rolling(self.lenCHOP).min()
            range_hl = (hh - ll).clip(lower=1e-10)
            
            chop = 100.0 * np.log10(sum_tr / range_hl) / np.log10(self.lenCHOP)
            chop = chop.fillna(50)
            
            chop_norm = ((chop - 38.0) / (62.0 - 38.0)).clip(0, 1)
            trend_s = self.trend_score
            chop_score = (0.70 * chop_norm + 0.30 * (1.0 - trend_s)).clip(0, 1)
            return chop_score
        
        self.chop_score = self.I(calc_chop_score)
        
        # Volatility Score Calculation
        def calc_vol_score():
            atr_result = pta.atr(high, low, close, length=self.lenATR)
            if atr_result is not None:
                atr_val = atr_result
            else:
                atr_val = pd.Series(0, index=close.index)
            
            atr_pct = (100.0 * atr_val / close.replace(0, 1)).fillna(0)
            
            atr_min = atr_pct.rolling(self.volLook).min()
            atr_max = atr_pct.rolling(self.volLook).max()
            atr_span = (atr_max - atr_min).clip(lower=1e-10)
            
            vol_score = ((atr_pct - atr_min) / atr_span).clip(0, 1)
            return vol_score
        
        self.vol_score = self.I(calc_vol_score)
        
        # Summary calculation
        def calc_summary():
            trend_s = self.trend_score
            chop_s = self.chop_score
            
            summary_val = pd.Series(index=close.index, dtype=object)
            for i in range(len(close)):
                if i < len(chop_s) and i < len(trend_s):
                    if chop_s.iloc[i] >= 0.66:
                        summary_val.iloc[i] = "RANGE"
                    elif trend_s.iloc[i] >= 0.66 and chop_s.iloc[i] <= 0.33:
                        summary_val.iloc[i] = "TREND"
                    else:
                        summary_val.iloc[i] = "MIXED"
                else:
                    summary_val.iloc[i] = "MIXED"
            
            return summary_val
        
        self.summary = self.I(calc_summary)

    def next(self):
        if len(self.data) < 2:
            return
        
        current_trend = self.trend_score[-1] if len(self.trend_score) > 0 else 0.5
        current_chop = self.chop_score[-1] if len(self.chop_score) > 0 else 0.5
        current_vol = self.vol_score[-1] if len(self.vol_score) > 0 else 0.5
        
        # Trading logic: Buy in TREND regime with strong trend and low chop
        if current_trend >= 0.66 and current_chop <= 0.33:
            if not self.position:
                self.buy()
        # Sell when regime breaks down (enters RANGE or MIXED)
        elif current_trend < 0.66 or current_chop > 0.33:
            if self.position:
                self.position.close()