"""
DS-TV Backtest Results: ag-pro-swap-engine-pair-rotation-z-score
============================================================

--- SPY ---
  Return                    -24.02%
  Buy & Hold Return         40.21%
  Max Drawdown              -29.18%
  Sharpe Ratio              -1.05
  Sortino Ratio             -1.29
  Calmar Ratio              -0.44
  Profit Factor             0.18
  Expectancy                -0.89%
  SQN                       -1.84
  # Trades                  26
  Win Rate                  30.77%
  Best Trade                1.03%
  Worst Trade               -10.43%
  Avg Trade                 -0.91%
  Exposure Time             66.60%
  Equity Final              75980.56$
  Equity Peak               107032.57$
  Avg Drawdown              -5.31%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        19 days 00:00:00
  Ann. Return               -12.93%
  Ann. Volatility           12.29%

--- BTC ---
  Return                    0.13%
  Buy & Hold Return         35.02%
  Max Drawdown              -24.57%
  Sharpe Ratio              0.00
  Sortino Ratio             0.00
  Calmar Ratio              0.00
  Profit Factor             1.18
  Expectancy                0.47%
  SQN                       0.01
  # Trades                  15
  Win Rate                  40.00%
  Best Trade                14.42%
  Worst Trade               -9.67%
  Avg Trade                 0.23%
  Exposure Time             59.92%
  Equity Final              100126.93$
  Equity Peak               132749.93$
  Avg Drawdown              -7.28%
  Max Drawdown Duration     308 days 00:00:00
  Max Trade Duration        219 days 00:00:00
  Avg Trade Duration        30 days 00:00:00
  Ann. Return               0.06%
  Ann. Volatility           27.62%

--- QQQ ---
  Return                    -34.46%
  Buy & Hold Return         42.44%
  Max Drawdown              -43.70%
  Sharpe Ratio              -1.35
  Sortino Ratio             -1.51
  Calmar Ratio              -0.44
  Profit Factor             0.18
  Expectancy                -1.37%
  SQN                       -2.86
  # Trades                  32
  Win Rate                  25.00%
  Best Trade                1.92%
  Worst Trade               -7.99%
  Avg Trade                 -1.41%
  Exposure Time             69.80%
  Equity Final              65537.42$
  Equity Peak               111808.86$
  Avg Drawdown              -9.01%
  Max Drawdown Duration     551 days 00:00:00
  Max Trade Duration        145 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               -19.18%
  Ann. Volatility           14.26%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ag-pro-swap-engine-pair-rotation-z-score
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Z-Score based pair rotation parameters
    lookback = 180
    zE1 = 1.7
    zE2 = 2.3
    zE3 = 2.9
    zX1 = 0.9
    zX2 = 0.6
    zX3 = 0.3
    
    # Tier sizing
    t1pct = 12.5
    t2pct = 17.5
    t3pct = 22.5
    
    # Filters
    trendBars = 10
    roundtripCost = 0.006
    costMultiple = 4.0
    cooldownBars = 1
    
    def init(self):
        # Since this is a pair rotation indicator without direct price data for Pair A/B,
        # we'll create a synthetic z-score signal based on price momentum
        close = pd.Series(self.data.Close)
        
        # Calculate a simple mean reversion signal using RSI as proxy for z-score
        self.rsi = self.I(pta.rsi, close, length=14)
        
        # Trend filter: use ADX to detect trending conditions
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        self.adx = self.I(pta.adx, high, low, close, length=14)
        
        # Track position state
        self.pos_tier = 0
        self.pos_dir = 0
        self.last_action_bar = -999
        self.actions_today = 0
        self.last_date = None
        
    def next(self):
        # Reset daily action counter
        current_date = pd.Timestamp(self.data.index[-1]).date()
        if self.last_date != current_date:
            self.actions_today = 0
            self.last_date = current_date
        
        # Check cooldown
        bars_since_action = len(self.data) - self.last_action_bar
        cooldown_ok = bars_since_action > self.cooldownBars
        
        # Check daily limit (max 6 actions per day)
        day_ok = self.actions_today < 6
        
        # Get current RSI (proxy for z-score extremeness)
        rsi = self.rsi[-1]
        adx = self.adx[-1] if not np.isnan(self.adx[-1]) else 20
        
        # Detect trend regime (ADX > 25 typically indicates strong trend)
        trend_regime = adx > 25
        
        # Signal direction based on RSI extremes
        # RSI < 30 = oversold (bullish, "want to buy")
        # RSI > 70 = overbought (bearish, "want to sell")
        sig_dir = 0
        if rsi < 30:
            sig_dir = 1  # Bullish signal
        elif rsi > 70:
            sig_dir = -1  # Bearish signal
        
        action_type = 0
        swap_dir = 0
        from_tier = self.pos_tier
        to_tier = self.pos_tier
        
        # EXIT LOGIC first
        if self.pos_tier > 0 and self.pos_dir != 0:
            # Exit when RSI returns toward center
            exit_triggered = False
            
            if self.pos_tier >= 3 and 40 < rsi < 60:
                exit_triggered = True
                to_tier = 2
            elif self.pos_tier >= 2 and 35 < rsi < 65:
                exit_triggered = True
                to_tier = 1
            elif self.pos_tier >= 1 and 30 < rsi < 70:
                exit_triggered = True
                to_tier = 0
            
            if exit_triggered and to_tier < from_tier:
                action_type = -1
                swap_dir = -self.pos_dir
        
        # ENTRY LOGIC (only if no exit)
        if action_type == 0 and sig_dir != 0 and not trend_regime:
            dir_ok = (self.pos_dir == 0) or (self.pos_dir == sig_dir)
            
            if dir_ok and cooldown_ok and day_ok:
                # Tier selection based on RSI extremeness
                if abs(rsi - 50) >= 20:  # RSI < 30 or > 70
                    to_tier = 1
                    if abs(rsi - 50) >= 25:  # Very extreme
                        to_tier = 2
                    if abs(rsi - 50) >= 30:  # Maximum extreme
                        to_tier = 3
                
                # Prevent tier jumps - scale step by step
                to_tier = min(to_tier, self.pos_tier + 1)
                
                if to_tier > from_tier:
                    action_type = 1
                    swap_dir = sig_dir
        
        # Apply action if conditions pass
        if action_type != 0 and cooldown_ok and day_ok and not trend_regime:
            if action_type == 1:  # Entry
                if self.pos_tier == 0:
                    self.pos_dir = swap_dir
                self.pos_tier = to_tier
                self.buy()
                
            elif action_type == -1:  # Exit
                self.pos_tier = to_tier
                if self.pos_tier == 0:
                    self.pos_dir = 0
                    self.sell()
                else:
                    # Partial exit - use sell for long reduction
                    self.sell()
            
            self.last_action_bar = len(self.data)
            self.actions_today += 1