"""
DS-TV Backtest Results: algov2
============================================================

--- SPY ---
  Return                    -46.81%
  Buy & Hold Return         40.20%
  Max Drawdown              -46.81%
  Sharpe Ratio              -2.27
  Sortino Ratio             -2.07
  Calmar Ratio              -0.58
  Profit Factor             0.59
  Expectancy                -0.20%
  SQN                       -2.60
  # Trades                  295
  Win Rate                  45.76%
  Best Trade                6.39%
  Worst Trade               -8.63%
  Avg Trade                 -0.22%
  Exposure Time             89.20%
  Equity Final              53194.82$
  Equity Peak               100000.00$
  Avg Drawdown              -46.81%
  Max Drawdown Duration     656 days 00:00:00
  Max Trade Duration        22 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -27.25%
  Ann. Volatility           12.02%

--- BTC ---
  Return                    -38.86%
  Buy & Hold Return         0.29%
  Max Drawdown              -38.86%
  Sharpe Ratio              -1.56
  Sortino Ratio             -1.58
  Calmar Ratio              -0.56
  Profit Factor             0.62
  Expectancy                -0.48%
  SQN                       -2.03
  # Trades                  129
  Win Rate                  41.86%
  Best Trade                7.58%
  Worst Trade               -12.38%
  Avg Trade                 -0.52%
  Exposure Time             19.56%
  Equity Final              61141.25$
  Equity Peak               100000.00$
  Avg Drawdown              -38.86%
  Max Drawdown Duration     681 days 00:00:00
  Max Trade Duration        1 days 00:00:00
  Avg Trade Duration        1 days 00:00:00
  Ann. Return               -21.78%
  Ann. Volatility           13.94%

--- QQQ ---
  Return                    -39.75%
  Buy & Hold Return         45.93%
  Max Drawdown              -39.75%
  Sharpe Ratio              -1.41
  Sortino Ratio             -1.42
  Calmar Ratio              -0.57
  Profit Factor             0.76
  Expectancy                -0.15%
  SQN                       -1.53
  # Trades                  285
  Win Rate                  52.28%
  Best Trade                6.54%
  Worst Trade               -11.09%
  Avg Trade                 -0.17%
  Exposure Time             89.40%
  Equity Final              60249.52$
  Equity Peak               100000.00$
  Avg Drawdown              -39.75%
  Max Drawdown Duration     656 days 00:00:00
  Max Trade Duration        28 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -22.54%
  Ann. Volatility           15.99%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — algov2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema50_length = 50
    ema2_length = 2
    tp_fixed_points = 350

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ema50_high = self.I(pta.ema, high, length=self.ema50_length)
        self.ema50_low = self.I(pta.ema, low, length=self.ema50_length)
        self.ema2 = self.I(pta.ema, close, length=self.ema2_length)
        
        self.market_state = 0
        self.tp_price = None
        self.entry_price = None

    def next(self):
        if len(self.data) < max(self.ema50_length, self.ema2_length) + 1:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        ema50_high_val = self.ema50_high[-1]
        ema50_low_val = self.ema50_low[-1]
        ema2_val = self.ema2[-1]
        
        pip_value = 0.0001
        tp_distance = self.tp_fixed_points * pip_value
        
        above_zone = ema2_val > ema50_high_val and close > ema50_high_val
        below_zone = ema2_val < ema50_low_val and close < ema50_low_val
        
        tp_hit_long = self.market_state == 1 and self.tp_price is not None and high >= self.tp_price
        tp_hit_short = self.market_state == -1 and self.tp_price is not None and low <= self.tp_price
        
        if tp_hit_long or tp_hit_short:
            self.tp_price = None
            if self.position:
                self.position.close()
            self.market_state = 0
        
        if above_zone and self.market_state != 1:
            if self.position:
                self.position.close()
            self.buy()
            self.market_state = 1
            self.tp_price = close + tp_distance
            self.entry_price = close
        
        elif below_zone and self.market_state != -1:
            if self.position:
                self.position.close()
            self.sell()
            self.market_state = -1
            self.tp_price = close - tp_distance
            self.entry_price = close