"""
DS-TV Backtest Results: auto-sr-channels-willyalgotrader
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         38.66%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         37.68%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         39.38%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — auto-sr-channels-willyalgotrader
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    pivot_len = 21
    atr_len = 14
    min_channel_bars = 10
    max_channel_bars = 400
    channel_quality = 0.55

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_len)
        
        self.pivot_highs = []
        self.pivot_lows = []
        self.pivot_high_indices = []
        self.pivot_low_indices = []
        
        self.up_channel_active = False
        self.down_channel_active = False
        self.up_channel_params = {}
        self.down_channel_params = {}
        
        self.up_bull_fired = False
        self.up_bear_fired = False
        self.down_bull_fired = False
        self.down_bear_fired = False
        
        self.last_signal = None

    def detect_pivots(self, idx):
        if idx < self.pivot_len * 2:
            return
        
        high = self.data.High
        low = self.data.Low
        
        lookback = self.pivot_len
        lookahead = self.pivot_len
        
        if idx - lookback < 0 or idx + lookahead >= len(high):
            return
        
        is_pivot_high = True
        is_pivot_low = True
        
        for i in range(max(0, idx - lookback), min(len(high), idx + lookahead + 1)):
            if i == idx:
                continue
            if high[i] > high[idx]:
                is_pivot_high = False
            if low[i] < low[idx]:
                is_pivot_low = False
        
        if is_pivot_high and len(self.pivot_highs) < 40:
            self.pivot_highs.append(high[idx])
            self.pivot_high_indices.append(idx)
            if len(self.pivot_highs) > 40:
                self.pivot_highs.pop(0)
                self.pivot_high_indices.pop(0)
        
        if is_pivot_low and len(self.pivot_lows) < 40:
            self.pivot_lows.append(low[idx])
            self.pivot_low_indices.append(idx)
            if len(self.pivot_lows) > 40:
                self.pivot_lows.pop(0)
                self.pivot_low_indices.pop(0)

    def line_price(self, x1, y1, x2, y2, bx):
        if x2 == x1:
            return y1
        return y1 + (y2 - y1) / (x2 - x1) * (bx - x1)

    def find_up_channel(self):
        if len(self.pivot_lows) < 2:
            return None
        
        best_params = None
        best_qual = 0.0
        
        sz = len(self.pivot_lows)
        pairs_to_check = min(sz, 8)
        
        for i in range(sz - 1, max(-1, sz - pairs_to_check - 1), -1):
            for j in range(i - 1, max(-1, i - 6), -1):
                ix1 = self.pivot_low_indices[j]
                iy1 = self.pivot_lows[j]
                ix2 = self.pivot_low_indices[i]
                iy2 = self.pivot_lows[i]
                
                span = ix2 - ix1
                if span < self.min_channel_bars or span > self.max_channel_bars:
                    continue
                if iy2 <= iy1:
                    continue
                
                max_off = 0.0
                if len(self.pivot_highs) > 0:
                    for k in range(len(self.pivot_highs)):
                        opp_bar = self.pivot_high_indices[k]
                        if opp_bar >= ix1 and opp_bar <= len(self.data) - 1:
                            opp_val = self.pivot_highs[k]
                            base_at_opp = self.line_price(ix1, iy1, ix2, iy2, opp_bar)
                            diff = opp_val - base_at_opp
                            if diff > max_off:
                                max_off = diff
                
                if max_off <= 0:
                    continue
                
                total_bars = len(self.data) - 1 - ix1
                if total_bars <= 0:
                    continue
                
                check_len = min(total_bars, 300)
                contained = 0
                tol = self.atr[-1] * 0.05 if self.atr[-1] is not None else 0.0
                
                for k in range(check_len):
                    bx = len(self.data) - 1 - k
                    if bx < ix1:
                        break
                    b_line = self.line_price(ix1, iy1, ix2, iy2, bx)
                    p_line = b_line + max_off
                    if self.data.Low[bx] >= b_line - tol and self.data.High[bx] <= p_line + tol:
                        contained += 1
                
                qual = contained / check_len if check_len > 0 else 0.0
                
                if qual >= self.channel_quality and qual > best_qual:
                    best_qual = qual
                    best_params = {
                        'x1': ix1, 'y1': iy1, 'x2': ix2, 'y2': iy2,
                        'offset': max_off, 'quality': qual
                    }
        
        return best_params

    def find_down_channel(self):
        if len(self.pivot_highs) < 2:
            return None
        
        best_params = None
        best_qual = 0.0
        
        sz = len(self.pivot_highs)
        pairs_to_check = min(sz, 8)
        
        for i in range(sz - 1, max(-1, sz - pairs_to_check - 1), -1):
            for j in range(i - 1, max(-1, i - 6), -1):
                ix1 = self.pivot_high_indices[j]
                iy1 = self.pivot_highs[j]
                ix2 = self.pivot_high_indices[i]
                iy2 = self.pivot_highs[i]
                
                span = ix2 - ix1
                if span < self.min_channel_bars or span > self.max_channel_bars:
                    continue
                if iy2 >= iy1:
                    continue
                
                min_off = 0.0
                if len(self.pivot_lows) > 0:
                    for k in range(len(self.pivot_lows)):
                        opp_bar = self.pivot_low_indices[k]
                        if opp_bar >= ix1 and opp_bar <= len(self.data) - 1:
                            opp_val = self.pivot_lows[k]
                            base_at_opp = self.line_price(ix1, iy1, ix2, iy2, opp_bar)
                            diff = opp_val - base_at_opp
                            if diff < min_off:
                                min_off = diff
                
                if min_off >= 0:
                    continue
                
                total_bars = len(self.data) - 1 - ix1
                if total_bars <= 0:
                    continue
                
                check_len = min(total_bars, 300)
                contained = 0
                tol = self.atr[-1] * 0.05 if self.atr[-1] is not None else 0.0
                
                for k in range(check_len):
                    bx = len(self.data) - 1 - k
                    if bx < ix1:
                        break
                    b_line = self.line_price(ix1, iy1, ix2, iy2, bx)
                    p_line = b_line + min_off
                    if self.data.High[bx] <= b_line + tol and self.data.Low[bx] >= p_line - tol:
                        contained += 1
                
                qual = contained / check_len if check_len > 0 else 0.0
                
                if qual >= self.channel_quality and qual > best_qual:
                    best_qual = qual
                    best_params = {
                        'x1': ix1, 'y1': iy1, 'x2': ix2, 'y2': iy2,
                        'offset': min_off, 'quality': qual
                    }
        
        return best_params

    def next(self):
        idx = len(self.data) - 1
        
        if idx < self.pivot_len * 4:
            return
        
        self.detect_pivots(idx)
        
        up_params = self.find_up_channel()
        down_params = self.find_down_channel()
        
        if up_params:
            prev_up = self.up_channel_params
            self.up_channel_active = True
            self.up_channel_params = up_params
            
            if not prev_up or prev_up.get('x1') != up_params['x1'] or prev_up.get('x2') != up_params['x2']:
                self.up_bull_fired = False
                self.up_bear_fired = False
        
        if down_params:
            prev_down = self.down_channel_params
            self.down_channel_active = True
            self.down_channel_params = down_params
            
            if not prev_down or prev_down.get('x1') != down_params['x1'] or prev_down.get('x2') != down_params['x2']:
                self.down_bull_fired = False
                self.down_bear_fired = False
        
        atr_val = self.atr[-1] if self.atr[-1] is not None else (self.data.High[-1] - self.data.Low[-1])
        
        bull_sig = False
        bear_sig = False
        
        if self.up_channel_active and self.up_channel_params:
            params = self.up_channel_params
            if (idx - params['x2']) <= self.max_channel_bars:
                b_now = self.line_price(params['x1'], params['y1'], params['x2'], params['y2'], idx)
                p_now = b_now + params['offset']
                
                tol = atr_val * 0.12
                
                if self.data.Close[-1] > p_now and not self.up_bull_fired:
                    self.up_bull_fired = True
                    bear_sig = False
                    bull_sig = True
                
                if self.data.Close[-1] < b_now and not self.up_bear_fired:
                    self.up_bear_fired = True
                    bull_sig = False
                    bear_sig = True
                
                if b_now - tol <= self.data.Low[-1] <= b_now + tol and self.data.Close[-1] > b_now:
                    if not self.up_bear_fired:
                        bull_sig = True
        
        if self.down_channel_active and self.down_channel_params:
            params = self.down_channel_params
            if (idx - params['x2']) <= self.max_channel_bars:
                b_now = self.line_price(params['x1'], params['y1'], params['x2'], params['y2'], idx)
                p_now = b_now + params['offset']
                
                tol = atr_val * 0.12
                
                if self.data.Close[-1] > b_now and not self.down_bull_fired:
                    self.down_bull_fired = True
                    bear_sig = False
                    bull_sig = True
                
                if self.data.Close[-1] < p_now and not self.down_bear_fired:
                    self.down_bear_fired = True
                    bull_sig = False
                    bear_sig = True
                
                if p_now - tol <= self.data.Low[-1] <= p_now + tol and self.data.Close[-1] > p_now:
                    if not self.down_bear_fired:
                        bull_sig = True
        
        if bull_sig and not self.position:
            self.buy()
            self.last_signal = 'buy'
        elif bear_sig and self.position:
            self.sell()
            self.last_signal = 'sell'