"""
DS-TV Backtest Results: bb-machine-learning-pattern-recognition
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — bb-machine-learning-pattern-recognition
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # BB Settings
    bbLength = 20
    bbMult = 2.0
    
    # ML Settings
    mlLookback = 300
    patternLookback = 5
    minConfidence = 60.0
    minSamples = 5
    futureCandles = 10
    successThreshold = 1.5
    
    # BB State Detection
    squeezeThreshold = 2.0
    expansionRate = 1.5
    bandWalkBars = 3
    
    # Risk Management
    stopLossPct = 2.0
    takeProfitPct = 4.0
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate Bollinger Bands
        self.basis = self.I(pta.sma, close, length=self.bbLength)
        stdev = self.I(lambda c: pta.stdev(c, self.bbLength), close)
        self.dev = self.bbMult * stdev
        self.upperBand = self.basis + self.dev
        self.lowerBand = self.basis - self.dev
        
        # BB Metrics
        self.bbWidth = self.I(lambda: (self.upperBand - self.lowerBand) / self.basis * 100)
        self.bbPercentB = self.I(lambda: (close - self.lowerBand) / (self.upperBand - self.lowerBand))
        
        # BB State Indicators
        self.isSqueeze = self.I(lambda: pd.Series(
            [self.bbWidth.iloc[i] < self.squeezeThreshold if i < len(self.bbWidth) else False 
             for i in range(len(self.bbWidth))], 
            index=close.index
        ))
        
        # RSI for features
        self.rsi = self.I(pta.rsi, close, length=14)
        
        # EMA for trend
        self.ema50 = self.I(pta.ema, close, length=50)
        
        # Candle metrics
        self.candleBody = self.I(lambda: np.abs(self.data.Close - self.data.Open))
        self.candleRange = self.I(lambda: self.data.High - self.data.Low)
        self.avgBody = self.I(lambda: pta.sma(self.candleBody, length=20), )
        
        # Volume SMA
        self.volumeSMA = self.I(pta.sma, volume, length=20)
        
        # Momentum
        self.momentum = self.I(pta.mom, close, length=10)
        
        # Position tracking
        self.inLong = False
        self.inShort = False
        self.entryPrice = None
        self.stopLoss = None
        self.takeProfit = None
        self.lastLongBar = -100
        self.lastShortBar = -100
        self.minBarsBetweenSignals = 5
        
    def next(self):
        if len(self) < self.mlLookback + self.futureCandles + 5:
            return
        
        # Current values
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        basis = self.basis[-1]
        upperBand = self.upperBand[-1]
        lowerBand = self.lowerBand[-1]
        bbPercentB = self.bbPercentB[-1]
        candleBody = self.candleBody[-1]
        candleRange = self.candleRange[-1]
        avgBody = self.avgBody[-1]
        
        # Pattern detection at lower band
        touchedLowerBand = low <= lowerBand
        closedBelowLower = close < lowerBand
        
        # Pattern detection at upper band
        touchedUpperBand = high >= upperBand
        closedAboveUpper = close > upperBand
        
        # Candle patterns
        isBullish = close > self.data.Open[-1]
        isBearish = close < self.data.Open[-1]
        
        pinBarThreshold = 60.0
        upperWick = high - max(close, self.data.Open[-1])
        lowerWick = min(close, self.data.Open[-1]) - low
        
        isPinBarAtLower = touchedLowerBand and candleRange > 0 and (lowerWick / candleRange * 100 > pinBarThreshold) and lowerWick > candleBody * 2
        isPinBarAtUpper = touchedUpperBand and candleRange > 0 and (upperWick / candleRange * 100 > pinBarThreshold) and upperWick > candleBody * 2
        
        # Engulfing patterns
        isBullishEngulfing = isBearish and self.data.Close[-2] < self.data.Open[-2] and isBullish and close > self.data.Open[-2] and self.data.Open[-1] < self.data.Close[-2]
        isBearishEngulfing = isBullish and self.data.Close[-2] > self.data.Open[-2] and isBearish and close < self.data.Open[-2] and self.data.Open[-1] > self.data.Close[-2]
        
        bullishEngulfingAtLower = isBullishEngulfing and (self.data.Low[-2] <= lowerBand)
        bearishEngulfingAtUpper = isBearishEngulfing and (self.data.High[-2] >= upperBand)
        
        # Rejection candles
        rejectionFromLower = touchedLowerBand and isBullish and close > basis + (basis - lowerBand) * 0.5
        rejectionFromUpper = touchedUpperBand and isBearish and close < basis - (upperBand - basis) * 0.5
        
        # Simple ML Confidence (simplified from complex Pine logic)
        longConfidence = 0.0
        shortConfidence = 0.0
        
        # Calculate confidence based on current price position and patterns
        if bbPercentB < 0.2:
            longConfidence = 50.0
            if isPinBarAtLower:
                longConfidence += 20
            if bullishEngulfingAtLower:
                longConfidence += 25
            if rejectionFromLower:
                longConfidence += 20
        
        if bbPercentB > 0.8:
            shortConfidence = 50.0
            if isPinBarAtUpper:
                shortConfidence += 20
            if bearishEngulfingAtUpper:
                shortConfidence += 25
            if rejectionFromUpper:
                shortConfidence += 20
        
        # Signal conditions
        longSignalCondition = (bbPercentB < 0.1 or touchedLowerBand or 
                               isPinBarAtLower or bullishEngulfingAtLower or rejectionFromLower)
        shortSignalCondition = (bbPercentB > 0.9 or touchedUpperBand or 
                                isPinBarAtUpper or bearishEngulfingAtUpper or rejectionFromUpper)
        
        # ML Filtered Signals
        mlLongSignal = longSignalCondition and longConfidence >= self.minConfidence
        mlShortSignal = shortSignalCondition and shortConfidence >= self.minConfidence
        
        # Prevent consecutive signals
        validLongSignal = mlLongSignal and (len(self) - self.lastLongBar) > self.minBarsBetweenSignals
        validShortSignal = mlShortSignal and (len(self) - self.lastShortBar) > self.minBarsBetweenSignals
        
        # Entry Logic
        if validLongSignal and not self.inLong and not self.inShort:
            self.buy()
            self.inLong = True
            self.inShort = False
            self.entryPrice = close
            self.stopLoss = close * (1 - self.stopLossPct / 100)
            self.takeProfit = close * (1 + self.takeProfitPct / 100)
            self.lastLongBar = len(self)
        
        if validShortSignal and not self.inShort and not self.inLong:
            self.sell()
            self.inShort = True
            self.inLong = False
            self.entryPrice = close
            self.stopLoss = close * (1 + self.stopLossPct / 100)
            self.takeProfit = close * (1 - self.takeProfitPct / 100)
            self.lastShortBar = len(self)
        
        # Exit Logic for Long
        if self.inLong:
            longExitMR = crossover(self.data.Close, self.basis)
            longExitSL = low <= self.stopLoss
            longExitTP = high >= self.takeProfit
            
            if longExitMR or longExitSL or longExitTP:
                self.position.close()
                self.inLong = False
                self.entryPrice = None
                self.stopLoss = None
                self.takeProfit = None
        
        # Exit Logic for Short
        if self.inShort:
            shortExitMR = crossover(self.basis, self.data.Close)
            shortExitSL = high >= self.stopLoss
            shortExitTP = low <= self.takeProfit
            
            if shortExitMR or shortExitSL or shortExitTP:
                self.position.close()
                self.inShort = False
                self.entryPrice = None
                self.stopLoss = None
                self.takeProfit = None


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()