"""
DS-TV Backtest Results: bitcoin-cme-gap-sakane
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — bitcoin-cme-gap-sakane
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    maxBars = 100
    minGapPct = 0.5
    adjustPremium = True

    def init(self):
        self.gaps = []
        self.last_cme_close = None
        self.last_chart_close = None
        self.cme_was_closed = False
        self.last_bar_index = -1
        self.in_gap = False
        self.gap_direction = None

    def next(self):
        current_bar = len(self.data) - 1
        
        if current_bar == 0:
            self.last_bar_index = current_bar
            self.last_cme_close = self.data.Close[-1]
            self.last_chart_close = self.data.Close[-1]
            return
        
        time_diff = current_bar - self.last_bar_index
        
        if time_diff > 1:
            if not self.in_gap and self.last_cme_close is not None:
                g_prev = self.last_cme_close
                g_open = self.data.Open[-1]
                g_diff = g_open - g_prev
                gap_pct = abs(g_diff) / g_prev * 100
                
                if gap_pct >= self.minGapPct:
                    g_up = g_open > g_prev
                    self.gap_direction = g_up
                    self.in_gap = True
                    
                    if g_up:
                        self.buy()
                    else:
                        self.sell()
        
        if self.in_gap and self.gap_direction is not None:
            gap_bar_index = current_bar - 1
            bars_since_gap = current_bar - gap_bar_index
            
            if bars_since_gap >= self.maxBars:
                if self.position:
                    self.position.close()
                self.in_gap = False
                self.gap_direction = None
            else:
                if self.gap_direction:
                    if self.data.Low[-1] <= self.last_cme_close:
                        if self.position:
                            self.position.close()
                        self.in_gap = False
                        self.gap_direction = None
                else:
                    if self.data.High[-1] >= self.last_cme_close:
                        if self.position:
                            self.position.close()
                        self.in_gap = False
                        self.gap_direction = None
        
        self.last_bar_index = current_bar
        self.last_cme_close = self.data.Close[-1]
        self.last_chart_close = self.data.Close[-1]


if __name__ == "__main__":
    from datetime import datetime
    import yfinance as yf
    
    data = yf.download("BTC-USD", start="2023-01-01", end="2024-01-01", progress=False)
    data.columns = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']
    data = data[['Open', 'High', 'Low', 'Close', 'Volume']]
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.001)
    results = bt.run()
    print(results)