"""
DS-TV Backtest Results: blackcat-l2-napoleon-mille-feuille
============================================================

--- SPY ---
  Return                    -0.24%
  Buy & Hold Return         38.23%
  Max Drawdown              -13.69%
  Sharpe Ratio              -0.01
  Sortino Ratio             -0.02
  Calmar Ratio              -0.01
  Profit Factor             1.03
  Expectancy                0.08%
  SQN                       -0.02
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                6.58%
  Worst Trade               -6.42%
  Avg Trade                 -0.13%
  Exposure Time             7.60%
  Equity Final              99759.39$
  Equity Peak               109842.41$
  Avg Drawdown              -3.56%
  Max Drawdown Duration     321 days 00:00:00
  Max Trade Duration        31 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               -0.12%
  Ann. Volatility           10.55%

--- BTC ---
  Return                    10.42%
  Buy & Hold Return         9.48%
  Max Drawdown              -19.48%
  Sharpe Ratio              0.29
  Sortino Ratio             0.44
  Calmar Ratio              0.26
  Profit Factor             1.56
  Expectancy                2.09%
  SQN                       0.33
  # Trades                  11
  Win Rate                  63.64%
  Best Trade                22.27%
  Worst Trade               -12.78%
  Avg Trade                 1.51%
  Exposure Time             26.54%
  Equity Final              110415.10$
  Equity Peak               135087.80$
  Avg Drawdown              -4.49%
  Max Drawdown Duration     141 days 00:00:00
  Max Trade Duration        32 days 00:00:00
  Avg Trade Duration        17 days 00:00:00
  Ann. Return               5.07%
  Ann. Volatility           17.41%

--- QQQ ---
  Return                    -8.91%
  Buy & Hold Return         41.79%
  Max Drawdown              -21.33%
  Sharpe Ratio              -0.48
  Sortino Ratio             -0.55
  Calmar Ratio              -0.22
  Profit Factor             0.64
  Expectancy                -1.84%
  SQN                       -0.41
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                7.24%
  Worst Trade               -16.31%
  Avg Trade                 -2.32%
  Exposure Time             12.40%
  Equity Final              91094.70$
  Equity Peak               108300.99$
  Avg Drawdown              -5.32%
  Max Drawdown Duration     558 days 00:00:00
  Max Trade Duration        35 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               -4.59%
  Ann. Volatility           9.65%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — blackcat-l2-napoleon-mille-feuille
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    sell_label_threshold = 4
    buy_label_threshold = 2

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)

        # 25-period mid-price channels
        mid_price_25 = self.I(lambda: pta.sma((low + high) / 2, length=25))
        upper_channel_25 = self.I(lambda: mid_price_25 * 1.15 if mid_price_25 is not None else pd.Series(0, index=close.index))
        lower_channel_25 = self.I(lambda: mid_price_25 * 0.95 if mid_price_25 is not None else pd.Series(0, index=close.index))
        mid_channel_25 = self.I(lambda: (upper_channel_25 + lower_channel_25) / 2 if upper_channel_25 is not None else pd.Series(0, index=close.index))

        # 5-period MA bands
        ma_close_5 = self.I(lambda: pta.sma(close, length=5))
        ma_open_5 = self.I(lambda: pta.sma(open_, length=5))
        mid_price_5 = self.I(lambda: (ma_close_5 + ma_open_5) / 2 if ma_close_5 is not None else pd.Series(0, index=close.index))
        upper_band_5 = self.I(lambda: mid_price_5 * 1.06 if mid_price_5 is not None else pd.Series(0, index=close.index))
        lower_band_5 = self.I(lambda: mid_price_5 * 0.98 if mid_price_5 is not None else pd.Series(0, index=close.index))
        mid_band_5 = self.I(lambda: (upper_band_5 + lower_band_5) / 2 if upper_band_5 is not None else pd.Series(0, index=close.index))

        # Store references for next()
        self.mid_price_25 = mid_price_25
        self.upper_channel_25 = upper_channel_25
        self.lower_channel_25 = lower_channel_25
        self.mid_channel_25 = mid_channel_25
        self.upper_band_5 = upper_band_5
        self.lower_band_5 = lower_band_5
        self.mid_band_5 = mid_band_5

        # Calculate strength score as a custom indicator
        self.strength_score = self.I(self._calculate_strength_score)

    def _calculate_strength_score(self):
        scores = []
        for i in range(len(self.data)):
            if i < max(25, 5):
                scores.append(0)
            else:
                upper_band_5 = self.upper_band_5[i]
                lower_band_5 = self.lower_band_5[i]
                mid_band_5 = self.mid_band_5[i]
                lower_channel_25 = self.lower_channel_25[i]
                mid_channel_25 = self.mid_channel_25[i]
                upper_channel_25 = self.upper_channel_25[i]

                cond1 = upper_band_5 > lower_channel_25
                cond2 = upper_band_5 > mid_channel_25
                cond3 = upper_band_5 > upper_channel_25
                cond4 = mid_band_5 > lower_channel_25
                cond5 = mid_band_5 > mid_channel_25
                cond6 = mid_band_5 > upper_channel_25
                cond7 = lower_band_5 > lower_channel_25
                cond8 = lower_band_5 > mid_channel_25
                cond9 = lower_band_5 > upper_channel_25

                score = sum([cond1, cond2, cond3, cond4, cond5, cond6, cond7, cond8, cond9])
                scores.append(score)

        return pd.Series(scores, index=self.data.index)

    def next(self):
        if len(self.data) < 26:
            return

        current_score = self.strength_score[-1]
        prev_score = self.strength_score[-2] if len(self.strength_score) > 1 else current_score

        # Buy signal: strength crosses below buy threshold
        if prev_score > self.buy_label_threshold and current_score <= self.buy_label_threshold:
            if not self.position:
                self.buy()

        # Sell signal: strength crosses above sell threshold
        if prev_score <= self.sell_label_threshold and current_score > self.sell_label_threshold:
            if self.position:
                self.position.close()

        # Alternative: Exit longs when strength drops significantly
        if self.position and current_score < self.buy_label_threshold:
            self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()