"""
DS-TV Backtest Results: classic-dow-theory-market-structure
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         40.54%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         34.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.28%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — classic-dow-theory-market-structure
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # ZigZag Settings
    dev_thresh_inp = 3.0
    depth = 11
    
    # Market Structure Settings
    show_labels = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ATR for deviation threshold
        self.atr = self.I(pta.atr, high, low, close, length=10)
        
        # Track market structure states
        self.locked_H = None
        self.prev_locked_H = None
        self.locked_L = None
        self.prev_locked_L = None
        
        self.line_HL = None  # Support line from Higher Low
        self.line_LH = None  # Resistance line from Lower High
        
        self.last_pivot_high = None
        self.last_pivot_low = None
        self.last_pivot_price = None
        self.last_pivot_bar = None
        self.is_high_last = None
        
        # Signals for trading
        self.uptrend_confirmed = False
        self.downtrend_confirmed = False
        self.break_of_lh = False
        self.break_of_hl = False

    def find_pivot_high(self, bar_idx):
        """Find pivot high at depth/2 bars back"""
        if bar_idx < self.depth:
            return None, None
        
        length = self.depth // 2
        look_back = length * 2
        
        if bar_idx - look_back < 0:
            return None, None
        
        pivot_idx = bar_idx - length
        if pivot_idx < 0:
            return None, None
        
        pivot_price = self.data.High[pivot_idx]
        
        # Check if this is a valid pivot high
        is_valid = True
        for i in range(max(0, pivot_idx - look_back), min(len(self.data), pivot_idx + look_back + 1)):
            if self.data.High[i] > pivot_price:
                is_valid = False
                break
        
        return (pivot_idx, pivot_price) if is_valid else (None, None)

    def find_pivot_low(self, bar_idx):
        """Find pivot low at depth/2 bars back"""
        if bar_idx < self.depth:
            return None, None
        
        length = self.depth // 2
        look_back = length * 2
        
        if bar_idx - look_back < 0:
            return None, None
        
        pivot_idx = bar_idx - length
        if pivot_idx < 0:
            return None, None
        
        pivot_price = self.data.Low[pivot_idx]
        
        # Check if this is a valid pivot low
        is_valid = True
        for i in range(max(0, pivot_idx - look_back), min(len(self.data), pivot_idx + look_back + 1)):
            if self.data.Low[i] < pivot_price:
                is_valid = False
                break
        
        return (pivot_idx, pivot_price) if is_valid else (None, None)

    def calc_dev(self, base_price, price):
        """Calculate deviation percentage"""
        if base_price == 0:
            return 0
        return 100 * (price - base_price) / price

    def next(self):
        current_bar = len(self.data) - 1
        
        if self.atr[-1] is None:
            return
        
        # Calculate deviation threshold
        dev_thresh = (self.atr[-1] / self.data.Close[-1]) * 100 * self.dev_thresh_inp
        
        current_close = self.data.Close[-1]
        
        # Check for pivot high
        pivot_h_idx, pivot_h_price = self.find_pivot_high(current_bar)
        
        if pivot_h_idx is not None:
            dev = self.calc_dev(self.last_pivot_price if self.last_pivot_price else pivot_h_price, pivot_h_price)
            
            if self.is_high_last == True and self.last_pivot_price is not None:
                # Continue uptrend
                if pivot_h_price > self.last_pivot_price:
                    # Higher High - potential continuation
                    self.last_pivot_high = pivot_h_idx
                    self.last_pivot_price = pivot_h_price
                    self.last_pivot_bar = pivot_h_idx
            else:
                # Direction changed from down to up
                if abs(dev) > dev_thresh:
                    if self.last_pivot_price is not None:
                        # Lock the previous low
                        self.prev_locked_L = self.locked_L
                        self.locked_L = self.last_pivot_price
                        
                        # Set support line from higher low
                        if self.locked_L is not None and self.prev_locked_L is not None:
                            if self.locked_L > self.prev_locked_L:
                                self.line_HL = self.locked_L
                    
                    self.is_high_last = True
                    self.last_pivot_high = pivot_h_idx
                    self.last_pivot_price = pivot_h_price
                    self.last_pivot_bar = pivot_h_idx
        
        # Check for pivot low
        pivot_l_idx, pivot_l_price = self.find_pivot_low(current_bar)
        
        if pivot_l_idx is not None:
            dev = self.calc_dev(self.last_pivot_price if self.last_pivot_price else pivot_l_price, pivot_l_price)
            
            if self.is_high_last == False and self.last_pivot_price is not None:
                # Continue downtrend
                if pivot_l_price < self.last_pivot_price:
                    # Lower Low - potential continuation
                    self.last_pivot_low = pivot_l_idx
                    self.last_pivot_price = pivot_l_price
                    self.last_pivot_bar = pivot_l_idx
            else:
                # Direction changed from up to down
                if abs(dev) > dev_thresh:
                    if self.last_pivot_price is not None:
                        # Lock the previous high
                        self.prev_locked_H = self.locked_H
                        self.locked_H = self.last_pivot_price
                        
                        # Set resistance line from lower high
                        if self.locked_H is not None and self.prev_locked_H is not None:
                            if self.locked_H < self.prev_locked_H:
                                self.line_LH = self.locked_H
                    
                    self.is_high_last = False
                    self.last_pivot_low = pivot_l_idx
                    self.last_pivot_price = pivot_l_price
                    self.last_pivot_bar = pivot_l_idx
        
        # Reversal Detection: Break of Lower High ends Downtrend
        if self.line_LH is not None and current_close > self.line_LH:
            self.break_of_lh = True
            self.uptrend_confirmed = True
            self.line_LH = None
        
        # Reversal Detection: Break of Higher Low ends Uptrend
        if self.line_HL is not None and current_close < self.line_HL:
            self.break_of_hl = True
            self.downtrend_confirmed = True
            self.line_HL = None
        
        # Trading Logic
        if self.break_of_lh and not self.position:
            self.buy()
            self.break_of_lh = False
        
        if self.break_of_hl and self.position:
            self.sell()
            self.break_of_hl = False


if __name__ == '__main__':
    bt = Backtest(
        pd.read_csv('data.csv', index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=.002
    )
    stats = bt.run()
    print(stats)