"""
DS-TV Backtest Results: clean-institutional-levels
============================================================

--- SPY ---
  Return                    -8.78%
  Buy & Hold Return         41.94%
  Max Drawdown              -14.69%
  Sharpe Ratio              -0.45
  Sortino Ratio             -0.67
  Calmar Ratio              -0.31
  Profit Factor             0.58
  Expectancy                -1.22%
  SQN                       -0.57
  # Trades                  6
  Win Rate                  50.00%
  Best Trade                6.47%
  Worst Trade               -8.36%
  Avg Trade                 -1.36%
  Exposure Time             52.00%
  Equity Final              91219.31$
  Equity Peak               101936.07$
  Avg Drawdown              -6.02%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        147 days 00:00:00
  Avg Trade Duration        62 days 00:00:00
  Ann. Return               -4.53%
  Ann. Volatility           10.11%

--- BTC ---
  Return                    16.14%
  Buy & Hold Return         46.22%
  Max Drawdown              -23.68%
  Sharpe Ratio              0.32
  Sortino Ratio             0.54
  Calmar Ratio              0.33
  Profit Factor             1.70
  Expectancy                2.17%
  SQN                       0.60
  # Trades                  11
  Win Rate                  36.36%
  Best Trade                20.50%
  Worst Trade               -11.60%
  Avg Trade                 1.69%
  Exposure Time             29.14%
  Equity Final              116142.90$
  Equity Peak               119368.90$
  Avg Drawdown              -5.24%
  Max Drawdown Duration     247 days 00:00:00
  Max Trade Duration        52 days 00:00:00
  Avg Trade Duration        19 days 00:00:00
  Ann. Return               7.76%
  Ann. Volatility           24.07%

--- QQQ ---
  Return                    -33.74%
  Buy & Hold Return         42.67%
  Max Drawdown              -34.82%
  Sharpe Ratio              -1.43
  Sortino Ratio             -1.58
  Calmar Ratio              -0.54
  Profit Factor             0.11
  Expectancy                -4.89%
  SQN                       -2.40
  # Trades                  8
  Win Rate                  12.50%
  Best Trade                5.03%
  Worst Trade               -12.85%
  Avg Trade                 -5.03%
  Exposure Time             60.00%
  Equity Final              66262.69$
  Equity Peak               101653.30$
  Avg Drawdown              -16.56%
  Max Drawdown Duration     551 days 00:00:00
  Max Trade Duration        175 days 00:00:00
  Avg Trade Duration        53 days 00:00:00
  Ann. Return               -18.73%
  Ann. Volatility           13.12%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — clean-institutional-levels
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    leftBars = 3
    rightBars = 3

    def init(self):
        # Pre-calculate pivot highs and lows for the entire dataset
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate pivot highs and lows
        self.pivot_highs = self._calculate_pivot_highs(high, self.leftBars, self.rightBars)
        self.pivot_lows = self._calculate_pivot_lows(low, self.leftBars, self.rightBars)
        
        # Store detected levels
        self.ith_levels = []  # ITH (Intermediate Swing High)
        self.itl_levels = []  # ITL (Intermediate Swing Low)
        self.h_vals = []
        self.h_idxs = []
        self.l_vals = []
        self.l_idxs = []

    def _calculate_pivot_highs(self, high, left_bars, right_bars):
        """Calculate pivot highs"""
        pivots = pd.Series(np.nan, index=high.index)
        for i in range(left_bars, len(high) - right_bars):
            left_section = high.iloc[i - left_bars:i]
            right_section = high.iloc[i + 1:i + 1 + right_bars]
            if high.iloc[i] > left_section.max() and high.iloc[i] > right_section.max():
                pivots.iloc[i] = high.iloc[i]
        return pivots

    def _calculate_pivot_lows(self, low, left_bars, right_bars):
        """Calculate pivot lows"""
        pivots = pd.Series(np.nan, index=low.index)
        for i in range(left_bars, len(low) - right_bars):
            left_section = low.iloc[i - left_bars:i]
            right_section = low.iloc[i + 1:i + 1 + right_bars]
            if low.iloc[i] < left_section.min() and low.iloc[i] < right_section.min():
                pivots.iloc[i] = low.iloc[i]
        return pivots

    def next(self):
        idx = len(self.data) - 1
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        # Check for new pivot high
        if not np.isnan(self.pivot_highs.iloc[idx]):
            ph_value = self.pivot_highs.iloc[idx]
            self.h_vals.append(ph_value)
            self.h_idxs.append(idx)
            
            # Check for ITH pattern (3 consecutive pivots where middle > sides)
            if len(self.h_vals) >= 3:
                v1 = self.h_vals[-3]
                v2 = self.h_vals[-2]
                v3 = self.h_vals[-1]
                if v2 > v1 and v2 > v3:
                    level_idx = self.h_idxs[-2]
                    self.ith_levels.append({'price': v2, 'idx': level_idx, 'hit': False})
        
        # Check for new pivot low
        if not np.isnan(self.pivot_lows.iloc[idx]):
            pl_value = self.pivot_lows.iloc[idx]
            self.l_vals.append(pl_value)
            self.l_idxs.append(idx)
            
            # Check for ITL pattern (3 consecutive pivots where middle < sides)
            if len(self.l_vals) >= 3:
                v1 = self.l_vals[-3]
                v2 = self.l_vals[-2]
                v3 = self.l_vals[-1]
                if v2 < v1 and v2 < v3:
                    level_idx = self.l_idxs[-2]
                    self.itl_levels.append({'price': v2, 'idx': level_idx, 'hit': False})
        
        # Check if ITH levels are hit (resistance)
        for level in self.ith_levels:
            if not level['hit'] and current_high >= level['price']:
                level['hit'] = True
                # Signal: Price hit resistance, consider selling/shorting
                if self.position:
                    self.position.close()
                else:
                    self.sell()
        
        # Check if ITL levels are hit (support)
        for level in self.itl_levels:
            if not level['hit'] and current_low <= level['price']:
                level['hit'] = True
                # Signal: Price hit support, consider buying
                if self.position:
                    self.position.close()
                else:
                    self.buy()