"""
DS-TV Backtest Results: donchian-channels-trend
============================================================

--- SPY ---
  Return                    -43.77%
  Buy & Hold Return         40.20%
  Max Drawdown              -47.48%
  Sharpe Ratio              -1.97
  Sortino Ratio             -1.94
  Calmar Ratio              -0.53
  Profit Factor             0.40
  Expectancy                -0.53%
  SQN                       -2.41
  # Trades                  101
  Win Rate                  35.64%
  Best Trade                6.39%
  Worst Trade               -13.14%
  Avg Trade                 -0.56%
  Exposure Time             80.60%
  Equity Final              56226.32$
  Equity Peak               106817.40$
  Avg Drawdown              -8.53%
  Max Drawdown Duration     573 days 00:00:00
  Max Trade Duration        192 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               -25.19%
  Ann. Volatility           12.77%

--- BTC ---
  Return                    6.63%
  Buy & Hold Return         0.29%
  Max Drawdown              -36.73%
  Sharpe Ratio              0.12
  Sortino Ratio             0.18
  Calmar Ratio              0.09
  Profit Factor             1.11
  Expectancy                0.20%
  SQN                       0.13
  # Trades                  75
  Win Rate                  48.00%
  Best Trade                44.77%
  Worst Trade               -24.09%
  Avg Trade                 -0.04%
  Exposure Time             49.93%
  Equity Final              106630.69$
  Equity Peak               141598.87$
  Avg Drawdown              -6.15%
  Max Drawdown Duration     337 days 00:00:00
  Max Trade Duration        130 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               3.26%
  Ann. Volatility           27.89%

--- QQQ ---
  Return                    -50.49%
  Buy & Hold Return         45.93%
  Max Drawdown              -56.75%
  Sharpe Ratio              -1.93
  Sortino Ratio             -1.82
  Calmar Ratio              -0.53
  Profit Factor             0.44
  Expectancy                -0.55%
  SQN                       -2.46
  # Trades                  124
  Win Rate                  36.29%
  Best Trade                6.54%
  Worst Trade               -17.40%
  Avg Trade                 -0.58%
  Exposure Time             83.60%
  Equity Final              49512.99$
  Equity Peak               111124.47$
  Avg Drawdown              -10.29%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        195 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -29.83%
  Ann. Volatility           15.45%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — donchian-channels-trend
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 50
    offset = 0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate Donchian Channels
        self.upper = self.I(lambda: high.rolling(self.length).max())
        self.lower = self.I(lambda: low.rolling(self.length).min())
        self.basis = self.I(lambda: (high.rolling(self.length).max() + low.rolling(self.length).min()) / 2)
        
        # Trend state tracker
        self.trend = 0

    def next(self):
        # Check if we have enough data
        if len(self.data) < self.length:
            return
        
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_upper = self.upper[-1]
        current_lower = self.lower[-1]
        
        # Trend detection logic
        if current_high == current_upper:
            self.trend = 1
        elif current_low == current_lower:
            self.trend = -1
        
        # Trading logic based on trend
        if self.trend == 1 and not self.position:
            self.buy()
        elif self.trend == -1 and self.position:
            self.sell()