"""
DS-TV Backtest Results: double-ma-customizable-all-types
============================================================

--- SPY ---
  Return                    5.72%
  Buy & Hold Return         17.90%
  Max Drawdown              -10.35%
  Sharpe Ratio              0.36
  Sortino Ratio             0.50
  Calmar Ratio              0.27
  Profit Factor             0.00
  Expectancy                -9.50%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -9.50%
  Worst Trade               -9.50%
  Avg Trade                 -9.50%
  Exposure Time             7.00%
  Equity Final              105724.37$
  Equity Peak               105958.45$
  Avg Drawdown              -2.46%
  Max Drawdown Duration     139 days 00:00:00
  Max Trade Duration        49 days 00:00:00
  Avg Trade Duration        49 days 00:00:00
  Ann. Return               2.85%
  Ann. Volatility           7.92%

--- BTC ---
  Return                    5.85%
  Buy & Hold Return         17.39%
  Max Drawdown              -42.99%
  Sharpe Ratio              0.09
  Sortino Ratio             0.14
  Calmar Ratio              0.07
  Profit Factor             0.63
  Expectancy                -3.28%
  SQN                       -0.47
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                17.01%
  Worst Trade               -18.67%
  Avg Trade                 -4.39%
  Exposure Time             53.76%
  Equity Final              105846.38$
  Equity Peak               138155.67$
  Avg Drawdown              -7.86%
  Max Drawdown Duration     385 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        131 days 00:00:00
  Ann. Return               2.88%
  Ann. Volatility           32.94%

--- QQQ ---
  Return                    -3.45%
  Buy & Hold Return         22.08%
  Max Drawdown              -17.48%
  Sharpe Ratio              -0.17
  Sortino Ratio             -0.22
  Calmar Ratio              -0.10
  Profit Factor             0.00
  Expectancy                -16.70%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -16.70%
  Worst Trade               -16.70%
  Avg Trade                 -16.70%
  Exposure Time             7.60%
  Equity Final              96551.65$
  Equity Peak               100000.00$
  Avg Drawdown              -17.48%
  Max Drawdown Duration     292 days 00:00:00
  Max Trade Duration        54 days 00:00:00
  Avg Trade Duration        54 days 00:00:00
  Ann. Return               -1.75%
  Ann. Volatility           10.21%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — double-ma-customizable-all-types
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ma_type_1 = "SMA"
    length_1 = 50
    ma_type_2 = "EMA"
    length_2 = 200

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate MA 1
        if self.ma_type_1 == "SMA":
            self.ma1 = self.I(pta.sma, close, length=self.length_1)
        elif self.ma_type_1 == "EMA":
            self.ma1 = self.I(pta.ema, close, length=self.length_1)
        elif self.ma_type_1 == "WMA":
            self.ma1 = self.I(pta.wma, close, length=self.length_1)
        elif self.ma_type_1 == "RMA":
            self.ma1 = self.I(pta.rma, close, length=self.length_1)
        elif self.ma_type_1 == "HMA":
            self.ma1 = self.I(pta.hma, close, length=self.length_1)
        
        # Calculate MA 2
        if self.ma_type_2 == "SMA":
            self.ma2 = self.I(pta.sma, close, length=self.length_2)
        elif self.ma_type_2 == "EMA":
            self.ma2 = self.I(pta.ema, close, length=self.length_2)
        elif self.ma_type_2 == "WMA":
            self.ma2 = self.I(pta.wma, close, length=self.length_2)
        elif self.ma_type_2 == "RMA":
            self.ma2 = self.I(pta.rma, close, length=self.length_2)
        elif self.ma_type_2 == "HMA":
            self.ma2 = self.I(pta.hma, close, length=self.length_2)

    def next(self):
        # Buy when MA1 crosses above MA2
        if crossover(self.ma1, self.ma2):
            self.buy()
        
        # Sell when MA1 crosses below MA2
        elif crossover(self.ma2, self.ma1):
            self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()