"""
DS-TV Backtest Results: floop-pro
============================================================

--- SPY ---
  Return                    13.97%
  Buy & Hold Return         17.90%
  Max Drawdown              -12.27%
  Sharpe Ratio              0.64
  Sortino Ratio             0.98
  Calmar Ratio              0.55
  Profit Factor             1.63
  Expectancy                1.07%
  SQN                       0.49
  # Trades                  10
  Win Rate                  50.00%
  Best Trade                14.36%
  Worst Trade               -6.86%
  Avg Trade                 0.92%
  Exposure Time             35.60%
  Equity Final              113965.15$
  Equity Peak               117338.31$
  Avg Drawdown              -2.34%
  Max Drawdown Duration     192 days 00:00:00
  Max Trade Duration        76 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               6.81%
  Ann. Volatility           10.71%

--- BTC ---
  Return                    -20.33%
  Buy & Hold Return         17.39%
  Max Drawdown              -28.76%
  Sharpe Ratio              -0.77
  Sortino Ratio             -0.89
  Calmar Ratio              -0.37
  Profit Factor             0.37
  Expectancy                -4.74%
  SQN                       -1.25
  # Trades                  5
  Win Rate                  20.00%
  Best Trade                14.10%
  Worst Trade               -12.33%
  Avg Trade                 -5.18%
  Exposure Time             15.18%
  Equity Final              79668.41$
  Equity Peak               111036.14$
  Avg Drawdown              -4.97%
  Max Drawdown Duration     488 days 00:00:00
  Max Trade Duration        59 days 00:00:00
  Avg Trade Duration        22 days 00:00:00
  Ann. Return               -10.73%
  Ann. Volatility           13.93%

--- QQQ ---
  Return                    -0.86%
  Buy & Hold Return         22.08%
  Max Drawdown              -16.94%
  Sharpe Ratio              -0.04
  Sortino Ratio             -0.05
  Calmar Ratio              -0.03
  Profit Factor             0.98
  Expectancy                -0.06%
  SQN                       -0.13
  # Trades                  10
  Win Rate                  30.00%
  Best Trade                15.22%
  Worst Trade               -8.66%
  Avg Trade                 -0.27%
  Exposure Time             29.40%
  Equity Final              99143.27$
  Equity Peak               103088.81$
  Avg Drawdown              -7.16%
  Max Drawdown Duration     252 days 00:00:00
  Max Trade Duration        54 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               -0.43%
  Ann. Volatility           11.55%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — floop-pro
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Core parameters
    sensitivity = 5
    atr_len = 14
    atr_mult = 0.8
    tp1_r = 3.0
    tp2_r = 4.0
    sl_r = 2.2
    ema_fast = 60
    ema_slow = 200
    ema_filter = False

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_len)

        # EMA
        self.ema_f = self.I(pta.ema, close, length=self.ema_fast)
        self.ema_s = self.I(pta.ema, close, length=self.ema_slow)

        # Range Filter calculation
        self.rf_filt = self.I(self._range_filter, close, high, low)
        self.rf_trend = self.I(self._range_filter_trend, close, high, low)

        # ROC for momentum
        self.roc5 = self.I(self._roc, close, 5)
        self.roc10 = self.I(self._roc, close, 10)
        self.roc20 = self.I(self._roc, close, 20)

        # Signal tracking
        self.entry_price = np.nan
        self.entry_dir = 0
        self.tp1_price = np.nan
        self.sl_price = np.nan

    def _range_filter(self, close, high, low):
        atr = pta.atr(high, low, close, length=self.atr_len)
        if atr is None:
            return pd.Series(close.values)
        rng = atr * self.atr_mult * (self.sensitivity / 8.0)
        filt = close.copy()
        for i in range(1, len(close)):
            if close.iloc[i] > filt.iloc[i - 1] + rng.iloc[i]:
                filt.iloc[i] = close.iloc[i] - rng.iloc[i]
            elif close.iloc[i] < filt.iloc[i - 1] - rng.iloc[i]:
                filt.iloc[i] = close.iloc[i] + rng.iloc[i]
            else:
                filt.iloc[i] = filt.iloc[i - 1]
        return filt

    def _range_filter_trend(self, close, high, low):
        atr = pta.atr(high, low, close, length=self.atr_len)
        if atr is None:
            return pd.Series(np.zeros(len(close)))
        rng = atr * self.atr_mult * (self.sensitivity / 8.0)
        filt = close.copy()
        for i in range(1, len(close)):
            if close.iloc[i] > filt.iloc[i - 1] + rng.iloc[i]:
                filt.iloc[i] = close.iloc[i] - rng.iloc[i]
            elif close.iloc[i] < filt.iloc[i - 1] - rng.iloc[i]:
                filt.iloc[i] = close.iloc[i] + rng.iloc[i]
            else:
                filt.iloc[i] = filt.iloc[i - 1]

        trend = pd.Series(np.zeros(len(close)))
        for i in range(1, len(close)):
            if filt.iloc[i] > filt.iloc[i - 1]:
                trend.iloc[i] = 1
            elif filt.iloc[i] < filt.iloc[i - 1]:
                trend.iloc[i] = -1
            else:
                trend.iloc[i] = trend.iloc[i - 1]
        return trend

    def _roc(self, close, period):
        roc = ((close - close.shift(period)) / close.shift(period) * 100)
        return roc

    def next(self):
        if len(self.data) < max(self.ema_slow, 20):
            return

        atr_val = self.atr[-1] if not np.isnan(self.atr[-1]) else 0
        if atr_val == 0:
            return

        close_val = self.data.Close[-1]
        rf_trend_val = self.rf_trend[-1]
        ema_f_val = self.ema_f[-1]
        ema_s_val = self.ema_s[-1]
        roc5_val = self.roc5[-1]
        roc20_val = self.roc20[-1]

        # EMA alignment check
        ema_cross_bull = ema_f_val > ema_s_val
        ema_price_above = close_val > ema_f_val
        ema_slope_up = len(self.data) >= 6 and self.ema_f[-1] > self.ema_f[-6]
        ema_all_bull = ema_cross_bull and ema_price_above and ema_slope_up

        ema_cross_bear = ema_f_val < ema_s_val
        ema_price_below = close_val < ema_f_val
        ema_slope_down = len(self.data) >= 6 and self.ema_f[-1] < self.ema_f[-6]
        ema_all_bear = ema_cross_bear and ema_price_below and ema_slope_down

        # Momentum check
        mom_bull = roc5_val > 0 and self.roc10[-1] > 0 and roc20_val > 0
        mom_bear = roc5_val < 0 and self.roc10[-1] < 0 and roc20_val < 0

        # Trend change detection
        trend_changed = False
        if len(self.data) >= 2:
            if self.rf_trend[-1] != self.rf_trend[-2]:
                trend_changed = True

        long_sig_raw = trend_changed and rf_trend_val == 1
        short_sig_raw = trend_changed and rf_trend_val == -1

        ema_gate = self.ema_filter and (
            (rf_trend_val == 1 and not ema_all_bull) or (rf_trend_val == -1 and not ema_all_bear)
        )

        long_sig = long_sig_raw and not ema_gate
        short_sig = short_sig_raw and not ema_gate

        # Entry logic
        if long_sig and not self.position:
            self.entry_price = close_val
            self.entry_dir = 1
            self.tp1_price = close_val + atr_val * self.tp1_r
            self.tp2_price = close_val + atr_val * self.tp2_r
            self.sl_price = close_val - atr_val * self.sl_r
            self.buy()

        elif short_sig and not self.position:
            self.entry_price = close_val
            self.entry_dir = -1
            self.tp1_price = close_val - atr_val * self.tp1_r
            self.tp2_price = close_val - atr_val * self.tp2_r
            self.sl_price = close_val + atr_val * self.sl_r
            self.sell()

        # Exit logic
        if self.position:
            if self.entry_dir == 1:
                if close_val >= self.tp1_price or close_val <= self.sl_price:
                    self.position.close()
            elif self.entry_dir == -1:
                if close_val <= self.tp1_price or close_val >= self.sl_price:
                    self.position.close()