"""
DS-TV Backtest Results: fvg-mitigation-intraday-pro-clean-darshakssc
============================================================

--- SPY ---
  Return                    39.49%
  Buy & Hold Return         41.94%
  Max Drawdown              -18.75%
  Sharpe Ratio              0.94
  Sortino Ratio             1.66
  Calmar Ratio              0.97
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              139490.28$
  Equity Peak               139799.82$
  Avg Drawdown              -1.73%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               18.26%
  Ann. Volatility           19.41%

--- BTC ---
  Return                    18.23%
  Buy & Hold Return         46.22%
  Max Drawdown              -35.84%
  Sharpe Ratio              0.26
  Sortino Ratio             0.42
  Calmar Ratio              0.24
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              118233.27$
  Equity Peak               173135.75$
  Avg Drawdown              -6.27%
  Max Drawdown Duration     238 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               8.72%
  Ann. Volatility           33.76%

--- QQQ ---
  Return                    39.13%
  Buy & Hold Return         42.67%
  Max Drawdown              -22.71%
  Sharpe Ratio              0.73
  Sortino Ratio             1.27
  Calmar Ratio              0.80
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              139128.96$
  Equity Peak               143791.78$
  Avg Drawdown              -2.96%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               18.11%
  Ann. Volatility           24.77%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fvg-mitigation-intraday-pro-clean-darshakssc
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # FVG Detection parameters
    extend_bars = 220
    max_boxes_drawn = 8
    max_stored_zones = 120
    min_gap_ticks = 6
    min_gap_pct = 0.05
    use_wick_touch = True
    hide_mitigated = True
    show_only_nearest = True
    
    # A+ Signal Filter parameters
    require_rejection = True
    min_body_to_range = 0.55
    close_through_mid = True
    cooldown_bars = 12
    
    def init(self):
        self.fvg_boxes = []
        self.cooldown = 0
        self.min_tick = 0.01
        
    def next(self):
        if len(self.data) < 3:
            return
            
        current_idx = len(self.data) - 1
        current_open = self.data.Open[-1]
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        prev_open = self.data.Open[-2]
        prev_close = self.data.Close[-2]
        prev_high = self.data.High[-2]
        prev_low = self.data.Low[-2]
        
        prev2_open = self.data.Open[-3]
        prev2_close = self.data.Close[-3]
        prev2_high = self.data.High[-3]
        prev2_low = self.data.Low[-3]
        
        # Decrement cooldown
        if self.cooldown > 0:
            self.cooldown -= 1
        
        # FVG Detection
        bull_fvg = current_low > prev2_high
        bear_fvg = current_high < prev2_low
        
        gap_bull = (current_low - prev2_high) if bull_fvg else 0.0
        gap_bear = (prev2_low - current_high) if bear_fvg else 0.0
        
        min_gap_abs = self.min_gap_ticks * self.min_tick
        min_gap_pct_abs = current_close * (self.min_gap_pct / 100.0) if self.min_gap_pct > 0 else 0.0
        min_need = max(min_gap_abs, min_gap_pct_abs)
        
        bull_ok = bull_fvg and (gap_bull >= min_need)
        bear_ok = bear_fvg and (gap_bear >= min_need)
        
        # Create zones
        if bull_ok:
            z_top = current_low
            z_bot = prev2_high
            self.fvg_boxes.append({
                'top': z_top,
                'bot': z_bot,
                'direction': 1,
                'born': current_idx,
                'mitigated': False
            })
        
        if bear_ok:
            z_top = prev2_low
            z_bot = current_high
            self.fvg_boxes.append({
                'top': z_top,
                'bot': z_bot,
                'direction': -1,
                'born': current_idx,
                'mitigated': False
            })
        
        # Cap stored zones
        while len(self.fvg_boxes) > self.max_stored_zones:
            self.fvg_boxes.pop()
        
        # Expire old zones
        self.fvg_boxes = [
            box for box in self.fvg_boxes 
            if (current_idx - box['born']) <= self.extend_bars
        ]
        
        # Find nearest unhidden zone
        nearest_idx = None
        best_dist = float('inf')
        
        for i, box in enumerate(self.fvg_boxes):
            if self.hide_mitigated and box['mitigated']:
                continue
            
            mid = (box['top'] + box['bot']) * 0.5
            dist = abs(current_close - mid)
            
            if dist < best_dist:
                best_dist = dist
                nearest_idx = i
        
        # Mitigation signals (evaluate only nearest zone)
        bull_sig = False
        bear_sig = False
        
        if nearest_idx is not None and self.cooldown == 0:
            box = self.fvg_boxes[nearest_idx]
            t = box['top']
            b = box['bot']
            d = box['direction']
            
            if not box['mitigated']:
                in_wick = (current_low <= t) and (current_high >= b)
                in_close = (current_close <= t) and (current_close >= b)
                touched = in_wick if self.use_wick_touch else in_close
                mid = (t + b) * 0.5
                
                # Rejection candle check
                rng = max(current_high - current_low, self.min_tick)
                body = abs(current_close - current_open)
                body_ratio = body / rng if rng > 0 else 0
                
                rej_bull = current_close > current_open and body_ratio >= self.min_body_to_range
                rej_bear = current_close < current_open and body_ratio >= self.min_body_to_range
                
                if touched and self.cooldown == 0:
                    bull_pass = (d == 1) and (rej_bull if self.require_rejection else True) and (current_close > mid if self.close_through_mid else current_close > t)
                    bear_pass = (d == -1) and (rej_bear if self.require_rejection else True) and (current_close < mid if self.close_through_mid else current_close < b)
                    
                    if bull_pass:
                        bull_sig = True
                        box['mitigated'] = True
                        self.cooldown = self.cooldown_bars
                    
                    if bear_sig:
                        bear_sig = True
                        box['mitigated'] = True
                        self.cooldown = self.cooldown_bars
        
        # Trading signals
        if bull_sig:
            if not self.position:
                self.buy()
        elif bear_sig:
            if self.position:
                self.position.close()


if __name__ == '__main__':
    from datetime import datetime
    
    # Load data
    data = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()