"""
DS-TV Backtest Results: fxshare-cc-reversal
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         43.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         44.64%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         44.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fxshare-cc-reversal
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    minCount = 4
    minBody = 20
    emaLen = 2

    def init(self):
        close = pd.Series(self.data.Close)
        self.ema = self.I(pta.ema, close, length=self.emaLen)

    def next(self):
        if len(self.data) < 2:
            return

        # Current bar values
        curr_open = self.data.Open[-1]
        curr_close = self.data.Close[-1]
        curr_high = self.data.High[-1]
        curr_low = self.data.Low[-1]

        # Previous bar values
        prev_open = self.data.Open[-2]
        prev_close = self.data.Close[-2]

        # Calculate body
        curr_body = abs(curr_close - curr_open)
        prev_body = abs(prev_close - prev_open)

        # Determine validity and direction
        curr_valid = curr_body >= self.minBody
        prev_valid = prev_body >= self.minBody

        curr_is_bull = curr_close > curr_open
        curr_is_bear = curr_close < curr_open

        prev_is_bull = prev_close > prev_open
        prev_is_bear = prev_close < prev_open

        # Count consecutive valid candles
        if not hasattr(self, 'bull_count'):
            self.bull_count = 0
            self.bear_count = 0

        if curr_valid and curr_is_bull:
            self.bull_count += 1
        else:
            self.bull_count = 0

        if curr_valid and curr_is_bear:
            self.bear_count += 1
        else:
            self.bear_count = 0

        # Get EMA value
        ema_val = self.ema[-1]

        # Reversal conditions
        sell_cond = self.bull_count >= self.minCount and curr_is_bear and curr_close < ema_val
        buy_cond = self.bear_count >= self.minCount and curr_is_bull and curr_close > ema_val

        # Trading logic
        if sell_cond and self.position:
            self.sell()
        elif buy_cond and not self.position:
            self.buy()