"""
DS-TV Backtest Results: gann-n-bar-swing-chart
============================================================

--- SPY ---
  Return                    3.92%
  Buy & Hold Return         41.94%
  Max Drawdown              -15.71%
  Sharpe Ratio              0.14
  Sortino Ratio             0.21
  Calmar Ratio              0.12
  Profit Factor             1.11
  Expectancy                0.08%
  SQN                       0.18
  # Trades                  70
  Win Rate                  47.14%
  Best Trade                12.86%
  Worst Trade               -7.60%
  Avg Trade                 0.05%
  Exposure Time             75.00%
  Equity Final              103915.86$
  Equity Peak               106972.42$
  Avg Drawdown              -3.20%
  Max Drawdown Duration     352 days 00:00:00
  Max Trade Duration        32 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               1.95%
  Ann. Volatility           14.44%

--- BTC ---
  Return                    52.05%
  Buy & Hold Return         46.22%
  Max Drawdown              -17.82%
  Sharpe Ratio              0.87
  Sortino Ratio             1.76
  Calmar Ratio              1.31
  Profit Factor             1.80
  Expectancy                0.94%
  SQN                       1.25
  # Trades                  84
  Win Rate                  44.05%
  Best Trade                41.10%
  Worst Trade               -8.52%
  Avg Trade                 0.76%
  Exposure Time             63.06%
  Equity Final              152046.50$
  Equity Peak               162035.84$
  Avg Drawdown              -3.80%
  Max Drawdown Duration     242 days 00:00:00
  Max Trade Duration        20 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               23.27%
  Ann. Volatility           26.78%

--- QQQ ---
  Return                    -18.24%
  Buy & Hold Return         42.67%
  Max Drawdown              -29.92%
  Sharpe Ratio              -0.68
  Sortino Ratio             -0.78
  Calmar Ratio              -0.32
  Profit Factor             0.75
  Expectancy                -0.26%
  SQN                       -1.04
  # Trades                  73
  Win Rate                  42.47%
  Best Trade                5.89%
  Worst Trade               -10.16%
  Avg Trade                 -0.29%
  Exposure Time             75.60%
  Equity Final              81759.88$
  Equity Peak               100024.00$
  Avg Drawdown              -15.54%
  Max Drawdown Duration     710 days 00:00:00
  Max Trade Duration        29 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               -9.65%
  Ann. Volatility           14.13%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gann-n-bar-swing-chart
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    swing_n = 1
    
    def init(self):
        self.pH = None
        self.pL = None
        self.dir = 0
        self.revCnt = 0
        self.extBar = 0
        self.extVal = 0.0
        self.tBar = None
        self.tVal = None
        self.swing_turns = []
        
    def next(self):
        idx = len(self.data) - 1
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        if self.pH is None:
            self.pH = high
            self.pL = low
        else:
            hh = high > self.pH
            lh = high < self.pH
            hl = low > self.pL
            ll = low < self.pL
            
            bc = 0
            if hh and hl:
                bc = 1
            elif lh and ll:
                bc = -1
            elif lh and hl:
                bc = 0
            elif hh and ll:
                bc = 2
            elif hh or (high == self.pH and hl):
                bc = 1
            elif ll or (high == self.pH and ll) or lh:
                bc = -1
            
            is_inside = bc == 0
            eff = self.dir if bc == 2 else bc
            
            if not is_inside and eff != 0:
                if self.dir == 0:
                    self.dir = eff
                    self.extBar = idx
                    self.extVal = high if eff == 1 else low
                else:
                    if eff == self.dir:
                        self.revCnt = 0
                        if self.dir == 1 and high > self.extVal:
                            self.extVal = high
                            self.extBar = idx
                        if self.dir == -1 and low < self.extVal:
                            self.extVal = low
                            self.extBar = idx
                    else:
                        self.revCnt += 1
                        if self.revCnt >= self.swing_n:
                            if self.tBar is not None:
                                self.swing_turns.append({
                                    'turn_type': 'H' if self.dir == 1 else 'L',
                                    'bar': self.extBar,
                                    'price': self.extVal,
                                    'prev_bar': self.tBar,
                                    'prev_price': self.tVal
                                })
                            
                            self.tBar = self.extBar
                            self.tVal = self.extVal
                            self.dir = -self.dir
                            self.revCnt = 0
                            self.extBar = idx
                            self.extVal = high if self.dir == 1 else low
                
                self.pH = high
                self.pL = low
            
            if self.swing_turns:
                last_turn = self.swing_turns[-1]
                if last_turn['turn_type'] == 'L' and self.dir == 1:
                    if not self.position:
                        self.buy()
                elif last_turn['turn_type'] == 'H' and self.dir == -1:
                    if self.position:
                        self.position.close()


if __name__ == '__main__':
    import yfinance as yf
    
    data = yf.download('AAPL', start='2023-01-01', end='2024-01-01', progress=False)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    results = bt.run()
    print(results)
    bt.plot()