"""
DS-TV Backtest Results: gold-priceaction-v1
============================================================

--- SPY ---
  Return                    18.22%
  Buy & Hold Return         41.94%
  Max Drawdown              -7.34%
  Sharpe Ratio              0.85
  Sortino Ratio             1.28
  Calmar Ratio              1.20
  Profit Factor             2.09
  Expectancy                1.00%
  SQN                       0.87
  # Trades                  18
  Win Rate                  44.44%
  Best Trade                14.58%
  Worst Trade               -3.24%
  Avg Trade                 0.90%
  Exposure Time             72.40%
  Equity Final              118217.76$
  Equity Peak               126862.88$
  Avg Drawdown              -1.34%
  Max Drawdown Duration     303 days 00:00:00
  Max Trade Duration        101 days 00:00:00
  Avg Trade Duration        28 days 00:00:00
  Ann. Return               8.80%
  Ann. Volatility           10.30%

--- BTC ---
  Return                    8.44%
  Buy & Hold Return         46.22%
  Max Drawdown              -22.10%
  Sharpe Ratio              0.16
  Sortino Ratio             0.26
  Calmar Ratio              0.19
  Profit Factor             1.23
  Expectancy                0.53%
  SQN                       0.23
  # Trades                  31
  Win Rate                  29.03%
  Best Trade                41.81%
  Worst Trade               -8.88%
  Avg Trade                 0.17%
  Exposure Time             47.47%
  Equity Final              108435.41$
  Equity Peak               124946.68$
  Avg Drawdown              -6.88%
  Max Drawdown Duration     225 days 00:00:00
  Max Trade Duration        55 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               4.13%
  Ann. Volatility           25.64%

--- QQQ ---
  Return                    37.46%
  Buy & Hold Return         42.67%
  Max Drawdown              -10.01%
  Sharpe Ratio              1.20
  Sortino Ratio             1.98
  Calmar Ratio              1.74
  Profit Factor             2.90
  Expectancy                1.45%
  SQN                       1.33
  # Trades                  24
  Win Rate                  41.67%
  Best Trade                19.63%
  Worst Trade               -3.58%
  Avg Trade                 1.34%
  Exposure Time             69.80%
  Equity Final              137459.93$
  Equity Peak               152745.93$
  Avg Drawdown              -1.72%
  Max Drawdown Duration     147 days 00:00:00
  Max Trade Duration        101 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               17.39%
  Ann. Volatility           14.51%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gold-priceaction-v1
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        major_len = 50
        minor_len = 15
        
        if len(self.data) < major_len + 1:
            return
        
        recent_high = high.iloc[-major_len:].max()
        recent_low = low.iloc[-major_len:].min()
        
        current_close = close.iloc[-1]
        
        bullish_structure = current_close > recent_low
        bearish_structure = current_close < recent_high
        
        rsi = pta.rsi(close, length=14)
        if rsi is None or len(rsi) < 1:
            return
        
        current_rsi = rsi.iloc[-1]
        
        if bullish_structure and current_rsi > 50 and current_rsi < 70:
            if not self.position:
                self.buy()
        elif bearish_structure and current_rsi < 50 and current_rsi > 30:
            if self.position:
                self.position.close()
        
        if self.position:
            if current_rsi > 80:
                self.position.close()
            elif current_rsi < 20:
                self.position.close()


if __name__ == '__main__':
    from datetime import datetime
    
    bt = Backtest(
        pd.read_csv('data.csv', index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=.002
    )
    
    results = bt.run()
    print(results)
    bt.plot()