"""
DS-TV Backtest Results: hidden-markov-model-market-regimes-luxalgo
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         27.40%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         5.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         24.82%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — hidden-markov-model-market-regimes-luxalgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lookback_period = 50
    smoothing_rate = 0.1

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate log returns
        self.log_returns = self.I(lambda: np.log(close / close.shift(1)))
        
        # Calculate mean return and volatility
        self.mean_return = self.I(lambda: pd.Series(self.log_returns).rolling(self.lookback_period).mean())
        self.volatility = self.I(lambda: pd.Series(self.log_returns).rolling(self.lookback_period).std())
        
        # Normalized observations
        self.norm_return = self.I(lambda: (self.log_returns - self.mean_return) / (self.volatility + 1e-9))
        self.norm_vol = self.I(lambda: self.volatility / (pd.Series(self.volatility).rolling(self.lookback_period).mean() + 1e-9))
        
        # State probabilities
        self.prob0 = 0.25
        self.prob1 = 0.25
        self.prob2 = 0.25
        self.prob3 = 0.25
        
        # Transition matrix
        self.p00, self.p01, self.p02, self.p03 = 0.9, 0.05, 0.02, 0.03
        self.p10, self.p11, self.p12, self.p13 = 0.1, 0.80, 0.05, 0.05
        self.p20, self.p21, self.p22, self.p23 = 0.0, 0.10, 0.85, 0.05
        self.p30, self.p31, self.p32, self.p33 = 0.1, 0.05, 0.00, 0.85
        
        # Store regime probabilities for trading decisions
        self.regime_probs = self.I(self._calculate_regimes)

    def _calculate_regimes(self):
        regimes = np.zeros((len(self.data), 4))
        
        for i in range(len(self.data)):
            if i == 0 or pd.isna(self.norm_vol[-1]):
                regimes[i] = [0.25, 0.25, 0.25, 0.25]
                continue
            
            norm_vol = self.norm_vol[-1]
            norm_ret = self.norm_return[-1]
            
            # Emission likelihoods
            emission_low_vol = np.exp(-((norm_vol - 0.7) ** 2) / 0.5) * np.exp(-((norm_ret - 0.5) ** 2) / 2.0)
            emission_high_vol = np.exp(-((norm_vol - 1.5) ** 2) / 1.0) * np.exp(-(norm_ret ** 2) / 0.5)
            emission_crash = np.exp(-((norm_vol - 2.0) ** 2) / 1.0) * (1.0 if norm_ret < -1.5 else np.exp(-((norm_ret + 2.0) ** 2) / 1.0))
            emission_accum = np.exp(-((norm_vol - 0.6) ** 2) / 0.5) * np.exp(-((norm_ret + 0.2) ** 2) / 1.0)
            
            # Prior step
            prior0 = self.prob0 * self.p00 + self.prob1 * self.p10 + self.prob2 * self.p20 + self.prob3 * self.p30
            prior1 = self.prob0 * self.p01 + self.prob1 * self.p11 + self.prob2 * self.p21 + self.prob3 * self.p31
            prior2 = self.prob0 * self.p02 + self.prob1 * self.p12 + self.prob2 * self.p22 + self.prob3 * self.p32
            prior3 = self.prob0 * self.p03 + self.prob1 * self.p13 + self.prob2 * self.p23 + self.prob3 * self.p33
            
            # Update step
            unnorm0 = emission_low_vol * prior0
            unnorm1 = emission_high_vol * prior1
            unnorm2 = emission_crash * prior2
            unnorm3 = emission_accum * prior3
            
            # Normalization
            sum_probs = unnorm0 + unnorm1 + unnorm2 + unnorm3
            if sum_probs > 0:
                new_prob0 = (1.0 - self.smoothing_rate) * self.prob0 + self.smoothing_rate * (unnorm0 / sum_probs)
                new_prob1 = (1.0 - self.smoothing_rate) * self.prob1 + self.smoothing_rate * (unnorm1 / sum_probs)
                new_prob2 = (1.0 - self.smoothing_rate) * self.prob2 + self.smoothing_rate * (unnorm2 / sum_probs)
                new_prob3 = (1.0 - self.smoothing_rate) * self.prob3 + self.smoothing_rate * (unnorm3 / sum_probs)
            else:
                new_prob0, new_prob1, new_prob2, new_prob3 = self.prob0, self.prob1, self.prob2, self.prob3
            
            # Normalization to sum to 1
            current_sum = new_prob0 + new_prob1 + new_prob2 + new_prob3
            if current_sum > 0:
                new_prob0 /= current_sum
                new_prob1 /= current_sum
                new_prob2 /= current_sum
                new_prob3 /= current_sum
            
            self.prob0, self.prob1, self.prob2, self.prob3 = new_prob0, new_prob1, new_prob2, new_prob3
            regimes[i] = [new_prob0, new_prob1, new_prob2, new_prob3]
        
        return regimes

    def next(self):
        if len(self.data) < self.lookback_period + 1:
            return
        
        current_regimes = self.regime_probs[-1]
        prob0, prob1, prob2, prob3 = current_regimes[0], current_regimes[1], current_regimes[2], current_regimes[3]
        
        # Determine dominant state
        max_prob = max(prob0, prob1, prob2, prob3)
        dominant_state = list(current_regimes).index(max_prob)
        
        # Trading logic based on regime
        # Buy in Low Vol Trend (state 0) or Accumulation (state 3) with high confidence
        # Sell in High Vol Chop (state 1) or Crash (state 2) with high confidence
        
        if dominant_state == 0 and max_prob > 0.60:
            if not self.position:
                self.buy()
        elif dominant_state == 3 and max_prob > 0.60:
            if not self.position:
                self.buy()
        elif dominant_state == 1 and max_prob > 0.65:
            if self.position:
                self.sell()
        elif dominant_state == 2 and max_prob > 0.65:
            if self.position:
                self.sell()


if __name__ == '__main__':
    import yfinance as yf
    
    df = yf.download('BTC-USD', start='2022-01-01', end='2023-12-31', progress=False)
    
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)