"""
DS-TV Backtest Results: hour-pivots
============================================================

--- SPY ---
  Return                    -60.43%
  Buy & Hold Return         41.94%
  Max Drawdown              -60.62%
  Sharpe Ratio              -3.95
  Sortino Ratio             -3.22
  Calmar Ratio              -0.62
  Profit Factor             0.36
  Expectancy                -0.33%
  SQN                       -5.93
  # Trades                  279
  Win Rate                  25.81%
  Best Trade                5.41%
  Worst Trade               -3.19%
  Avg Trade                 -0.33%
  Exposure Time             99.60%
  Equity Final              39574.79$
  Equity Peak               100499.19$
  Avg Drawdown              -30.61%
  Max Drawdown Duration     720 days 00:00:00
  Max Trade Duration        35 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -37.32%
  Ann. Volatility           9.46%

--- BTC ---
  Return                    -33.80%
  Buy & Hold Return         46.22%
  Max Drawdown              -36.19%
  Sharpe Ratio              -0.95
  Sortino Ratio             -0.99
  Calmar Ratio              -0.51
  Profit Factor             0.52
  Expectancy                -2.18%
  SQN                       -1.13
  # Trades                  26
  Win Rate                  42.31%
  Best Trade                11.63%
  Worst Trade               -32.52%
  Avg Trade                 -2.66%
  Exposure Time             35.98%
  Equity Final              66196.69$
  Equity Peak               103735.29$
  Avg Drawdown              -36.19%
  Max Drawdown Duration     715 days 00:00:00
  Max Trade Duration        43 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -18.62%
  Ann. Volatility           19.62%

--- QQQ ---
  Return                    -53.69%
  Buy & Hold Return         42.67%
  Max Drawdown              -55.84%
  Sharpe Ratio              -2.45
  Sortino Ratio             -2.28
  Calmar Ratio              -0.58
  Profit Factor             0.42
  Expectancy                -0.41%
  SQN                       -3.84
  # Trades                  189
  Win Rate                  26.98%
  Best Trade                10.76%
  Worst Trade               -4.07%
  Avg Trade                 -0.42%
  Exposure Time             98.20%
  Equity Final              46307.44$
  Equity Peak               102021.30$
  Avg Drawdown              -28.01%
  Max Drawdown Duration     719 days 00:00:00
  Max Trade Duration        45 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -32.16%
  Ann. Volatility           13.13%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — hour-pivots
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        # This is a pivot point indicator that draws support/resistance levels
        # Since it's purely a visual indicator with no trading signals defined,
        # we'll create a simple trading rule based on price interaction with pivots
        
        # Calculate weekly pivots manually
        if len(self.data) < 2:
            return
        
        # Get previous weekly OHLC (simplified: use last 5 bars as proxy for week)
        lookback = min(5, len(self.data) - 1)
        prev_high = max(self.data.High[-lookback:])
        prev_low = min(self.data.Low[-lookback:])
        prev_close = self.data.Close[-2]
        
        # Calculate pivot levels
        p = (prev_high + prev_low + prev_close) / 3
        rng = prev_high - prev_low
        
        r1 = (2 * p) - prev_low
        r5 = p + 4 * rng
        s1 = (2 * p) - prev_high
        s5 = p - 4 * rng
        
        current_price = self.data.Close[-1]
        
        # Trading logic: Buy near support, sell near resistance
        if not self.position:
            # Buy near S5 (extreme support)
            if current_price <= s5 * 1.01 and current_price >= s5 * 0.99:
                self.buy()
            # Buy near S1 (minor support)
            elif current_price <= s1 * 1.01 and current_price >= s1 * 0.99:
                self.buy()
        else:
            # Sell near R5 (extreme resistance)
            if current_price >= r5 * 0.99 and current_price <= r5 * 1.01:
                self.sell()
            # Sell near R1 (minor resistance)
            elif current_price >= r1 * 0.99 and current_price <= r1 * 1.01:
                self.sell()
            # Stop loss if price falls below S5
            elif current_price < s5 * 0.95:
                self.sell()