"""
DS-TV Backtest Results: inducement-ualgo
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — inducement-ualgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        if len(self.data) < 2:
            return
        
        high = self.data.High
        low = self.data.Low
        close = self.data.Close
        
        current_high = high[-1]
        current_low = low[-1]
        prev_high = high[-2]
        prev_low = low[-2]
        
        if not hasattr(self, 'trend'):
            self.trend = 1
            self.leg_high = current_high
            self.leg_low = current_low
            self.m_high = current_high
            self.m_low = current_low
            self.pullback_low = None
            self.pullback_high = None
            self.active_idms = []
            self.last_buy_price = None
            self.last_sell_price = None
            return
        
        is_inside = current_high <= self.m_high and current_low >= self.m_low
        
        if not is_inside:
            broke_low = current_low < self.m_low
            broke_high = current_high > self.m_high
            
            self.m_high = max(self.m_high, current_high)
            self.m_low = min(self.m_low, current_low)
            
            if self.trend == 1:
                if current_high > self.leg_high:
                    if self.pullback_low is not None:
                        self.active_idms.append({
                            'price': self.pullback_low,
                            'direction': 1,
                            'swept': False
                        })
                        self.leg_low = self.pullback_low
                        self.pullback_low = None
                    self.leg_high = current_high
                elif broke_low:
                    if self.pullback_low is None or current_low < self.pullback_low:
                        self.pullback_low = current_low
                
                if current_low < self.leg_low:
                    self.trend = -1
                    self.leg_low = current_low
                    self.pullback_low = None
                    self.pullback_high = None
            
            elif self.trend == -1:
                if current_low < self.leg_low:
                    if self.pullback_high is not None:
                        self.active_idms.append({
                            'price': self.pullback_high,
                            'direction': -1,
                            'swept': False
                        })
                        self.leg_high = self.pullback_high
                        self.pullback_high = None
                    self.leg_low = current_low
                elif broke_high:
                    if self.pullback_high is None or current_high > self.pullback_high:
                        self.pullback_high = current_high
                
                if current_high > self.leg_high:
                    self.trend = 1
                    self.leg_high = current_high
                    self.pullback_high = None
                    self.pullback_low = None
        
        for idm in self.active_idms:
            if not idm['swept']:
                if idm['direction'] == 1 and current_low <= idm['price']:
                    idm['swept'] = True
                elif idm['direction'] == -1 and current_high >= idm['price']:
                    idm['swept'] = True
        
        if len(self.active_idms) > 0:
            for idm in self.active_idms:
                if idm['direction'] == 1 and idm['swept']:
                    if not self.position:
                        self.buy()
                        self.last_buy_price = current_high
                elif idm['direction'] == -1 and idm['swept']:
                    if self.position:
                        self.position.close()
                        self.last_sell_price = current_low
        
        if len(self.active_idms) > 50:
            self.active_idms.pop(0)


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()