"""
DS-TV Backtest Results: kj-pullback-regime-with-filter-with-1hour-filter
============================================================

--- SPY ---
  Return                    26.14%
  Buy & Hold Return         27.40%
  Max Drawdown              -18.70%
  Sharpe Ratio              0.71
  Sortino Ratio             1.19
  Calmar Ratio              0.66
  Profit Factor             4766.83
  Expectancy                4.00%
  SQN                       1.65
  # Trades                  6
  Win Rate                  83.33%
  Best Trade                14.98%
  Worst Trade               -0.01%
  Avg Trade                 3.87%
  Exposure Time             76.40%
  Equity Final              126138.64$
  Equity Peak               126673.70$
  Avg Drawdown              -1.80%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        335 days 00:00:00
  Avg Trade Duration        93 days 00:00:00
  Ann. Return               12.42%
  Ann. Volatility           17.45%

--- BTC ---
  Return                    -36.79%
  Buy & Hold Return         5.39%
  Max Drawdown              -46.07%
  Sharpe Ratio              -0.97
  Sortino Ratio             -1.03
  Calmar Ratio              -0.44
  Profit Factor             0.05
  Expectancy                -10.18%
  SQN                       -1.57
  # Trades                  4
  Win Rate                  25.00%
  Best Trade                2.24%
  Worst Trade               -25.95%
  Avg Trade                 -10.94%
  Exposure Time             25.03%
  Equity Final              63210.17$
  Equity Peak               106974.45$
  Avg Drawdown              -16.30%
  Max Drawdown Duration     385 days 00:00:00
  Max Trade Duration        88 days 00:00:00
  Avg Trade Duration        46 days 00:00:00
  Ann. Return               -20.47%
  Ann. Volatility           21.06%

--- QQQ ---
  Return                    21.14%
  Buy & Hold Return         24.82%
  Max Drawdown              -22.84%
  Sharpe Ratio              0.52
  Sortino Ratio             0.85
  Calmar Ratio              0.44
  Profit Factor             17.66
  Expectancy                2.39%
  SQN                       2.17
  # Trades                  9
  Win Rate                  66.67%
  Best Trade                9.45%
  Worst Trade               -0.79%
  Avg Trade                 2.34%
  Exposure Time             60.80%
  Equity Final              121141.28$
  Equity Peak               126201.40$
  Avg Drawdown              -2.67%
  Max Drawdown Duration     190 days 00:00:00
  Max Trade Duration        211 days 00:00:00
  Avg Trade Duration        50 days 00:00:00
  Ann. Return               10.15%
  Ann. Volatility           19.62%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — kj-pullback-regime-with-filter-with-1hour-filter
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Parameters from the Pine Script
    pacLen = 34
    emaLen = 100
    atrLen = 14
    slopeLookback = 12
    flatAtrFrac = 0.10
    minSpaceFrac = 0.15
    minBarsAway = 6
    useHTF = False

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Core indicators
        self.ema100 = self.I(pta.ema, close, length=self.emaLen)
        self.pacUpper = self.I(pta.ema, high, length=self.pacLen)
        self.pacLower = self.I(pta.ema, low, length=self.pacLen)
        self.pacMid = self.I(pta.ema, close, length=self.pacLen)
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        # State variables for long
        self.wasOutLong = False
        self.validPullbackLong = False
        
        # State variables for short
        self.wasOutShort = False
        self.validPullbackShort = False
        
        # Track bars since last cross
        self.barsSinceCross = 0

    def next(self):
        if len(self.data) < max(self.pacLen, self.emaLen, self.atrLen, self.slopeLookback) + 1:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        ema100 = self.ema100[-1]
        pacUpper = self.pacUpper[-1]
        pacLower = self.pacLower[-1]
        pacMid = self.pacMid[-1]
        atr = self.atr[-1]
        
        # Regime Filter calculations
        pacSlope = abs(self.pacMid[-1] - self.pacMid[-self.slopeLookback - 1])
        pacFlatRaw = pacSlope < atr * self.flatAtrFrac
        
        emaPacDist = abs(ema100 - pacMid)
        noSpace = emaPacDist < atr * self.minSpaceFrac
        
        # Track bars since cross
        if len(self.data) > 1:
            prev_close = self.data.Close[-2]
            if (prev_close <= ema100 and close > ema100) or (prev_close >= ema100 and close < ema100):
                self.barsSinceCross = 0
            else:
                self.barsSinceCross += 1
        
        tooMuchChop = self.barsSinceCross < self.minBarsAway
        
        flatBad = pacFlatRaw and tooMuchChop
        noTrade = flatBad or noSpace or tooMuchChop
        
        # Trend determination
        longTrend = pacMid > ema100
        shortTrend = pacMid < ema100
        
        # LONG logic
        if longTrend and close > pacUpper:
            self.wasOutLong = True
        
        if self.wasOutLong and close < pacUpper and close > pacLower and close <= pacMid:
            self.validPullbackLong = True
        
        longSignal = longTrend and self.wasOutLong and self.validPullbackLong and close > pacUpper
        
        if longSignal:
            self.wasOutLong = False
            self.validPullbackLong = False
        
        if not longTrend:
            self.wasOutLong = False
            self.validPullbackLong = False
        
        # SHORT logic
        if shortTrend and close < pacLower:
            self.wasOutShort = True
        
        if self.wasOutShort and close > pacLower and close < pacUpper and close >= pacMid:
            self.validPullbackShort = True
        
        shortSignal = shortTrend and self.wasOutShort and self.validPullbackShort and close < pacLower
        
        if shortSignal:
            self.wasOutShort = False
            self.validPullbackShort = False
        
        if not shortTrend:
            self.wasOutShort = False
            self.validPullbackShort = False
        
        # Final gating
        finalLong = longSignal and not noTrade
        finalShort = shortSignal and not noTrade
        
        # Execute trades
        if finalLong:
            if self.position:
                self.position.close()
            self.buy()
        elif finalShort:
            if self.position:
                self.position.close()
            self.sell()


if __name__ == "__main__":
    from datetime import datetime
    
    # Load your data here
    # Example with sample data
    bt = Backtest(
        pd.read_csv('data.csv', index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=.002,
        exclusive_orders=True
    )
    
    stats = bt.run()
    print(stats)
    bt.plot()