"""
DS-TV Backtest Results: liquidity-sweep-rider-institutional-hft-grabber
============================================================

--- SPY ---
  ERROR: 'Position' object has no attribute 'open_price'

--- BTC ---
  ERROR: 'Position' object has no attribute 'open_price'

--- QQQ ---
  ERROR: 'Position' object has no attribute 'open_price'

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — liquidity-sweep-rider-institutional-hft-grabber
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    leftBars = 5
    rightBars = 5
    volLen = 20
    volMult = 2.0
    eatSellStopsLongSL = True
    eatBuyStopsShortSL = True
    eatStopLossOnly = True
    useATR = True
    atrLen = 14
    slAtrMult = 1.2
    tpRR = 2.5

    def init(self):
        # Prepare data series
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        # Calculate ATR
        self.atr_val = self.I(pta.atr, high, low, close, length=self.atrLen)

        # Calculate average volume
        self.avg_vol = self.I(pta.sma, volume, length=self.volLen)

        # Pivot high/low detection using rolling max/min
        self.pivot_high = self.I(
            lambda: high.rolling(window=self.leftBars + self.rightBars + 1, center=True).max()
        )
        self.pivot_low = self.I(
            lambda: low.rolling(window=self.leftBars + self.rightBars + 1, center=True).min()
        )

        # Track liquidity levels
        self.sell_side_liquidity = np.nan
        self.buy_side_liquidity = np.nan

        # Track last sweep bars for cooldown
        self.last_bull_sweep_bar = -999
        self.last_bear_sweep_bar = -999
        self.cooldown = max(self.leftBars + self.rightBars, 5) * 2

    def next(self):
        # Update liquidity levels based on pivot highs/lows
        idx = len(self.data) - 1

        # Check for new pivot high at correct offset
        if idx >= self.leftBars + self.rightBars:
            center_idx = idx - self.rightBars
            if (
                center_idx >= self.leftBars
                and center_idx < len(self.data) - self.rightBars
            ):
                is_pivot_high = True
                pivot_h_val = self.data.High[center_idx]
                for i in range(
                    max(0, center_idx - self.leftBars),
                    min(len(self.data), center_idx + self.rightBars + 1),
                ):
                    if i != center_idx and self.data.High[i] >= pivot_h_val:
                        is_pivot_high = False
                        break
                if is_pivot_high:
                    self.sell_side_liquidity = pivot_h_val

                is_pivot_low = True
                pivot_l_val = self.data.Low[center_idx]
                for i in range(
                    max(0, center_idx - self.leftBars),
                    min(len(self.data), center_idx + self.rightBars + 1),
                ):
                    if i != center_idx and self.data.Low[i] <= pivot_l_val:
                        is_pivot_low = False
                        break
                if is_pivot_low:
                    self.buy_side_liquidity = pivot_l_val

        # Current bar data
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_close = self.data.Close[-1]
        current_vol = self.data.Volume[-1]

        # Get average volume (handle None)
        avg_vol = self.avg_vol[-1] if self.avg_vol[-1] is not None else 0

        # Sweep detection
        bull_sweep = (
            not np.isnan(self.buy_side_liquidity)
            and current_low < self.buy_side_liquidity
            and current_close > self.buy_side_liquidity
            and current_vol >= avg_vol * self.volMult
        )

        bear_sweep = (
            not np.isnan(self.sell_side_liquidity)
            and current_high > self.sell_side_liquidity
            and current_close < self.sell_side_liquidity
            and current_vol >= avg_vol * self.volMult
        )

        # Entry conditions with cooldown
        bull_entry = (
            bull_sweep
            and self.eatSellStopsLongSL
            and (len(self.data) - self.last_bull_sweep_bar > self.cooldown)
        )

        bear_entry = (
            bear_sweep
            and self.eatBuyStopsShortSL
            and (len(self.data) - self.last_bear_sweep_bar > self.cooldown)
        )

        # Execute entries
        if bull_entry and not self.position:
            self.buy()
            self.last_bull_sweep_bar = len(self.data)

        if bear_entry and not self.position:
            self.sell()
            self.last_bear_sweep_bar = len(self.data)

        # ATR-based risk management
        if self.useATR and self.position:
            atr_val = self.atr_val[-1]
            if atr_val is not None and atr_val > 0:
                if self.position.is_long:
                    entry_price = self.position.open_price
                    sl = entry_price - atr_val * self.slAtrMult
                    tp = entry_price + atr_val * self.slAtrMult * self.tpRR

                    # Close if SL or TP is hit
                    if current_low <= sl:
                        self.position.close()
                    elif current_high >= tp:
                        self.position.close()

                elif self.position.is_short:
                    entry_price = self.position.open_price
                    sl = entry_price + atr_val * self.slAtrMult
                    tp = entry_price - atr_val * self.slAtrMult * self.tpRR

                    # Close if SL or TP is hit
                    if current_high >= sl:
                        self.position.close()
                    elif current_low <= tp:
                        self.position.close()


if __name__ == "__main__":
    from datetime import datetime

    # Example: Run backtest on sample data
    bt = Backtest(
        pd.read_csv("data.csv", index_col=0, parse_dates=True),
        TvStrategy,
        cash=100000,
        commission=0.0004,
    )
    results = bt.run()
    print(results)