"""
DS-TV Backtest Results: liquidity-trail-signals-boswaves
============================================================

--- SPY ---
  Return                    -2.12%
  Buy & Hold Return         35.75%
  Max Drawdown              -17.38%
  Sharpe Ratio              -0.08
  Sortino Ratio             -0.10
  Calmar Ratio              -0.06
  Profit Factor             1.07
  Expectancy                0.11%
  SQN                       -0.01
  # Trades                  17
  Win Rate                  29.41%
  Best Trade                17.89%
  Worst Trade               -4.01%
  Avg Trade                 -0.01%
  Exposure Time             88.00%
  Equity Final              97881.11$
  Equity Peak               114332.14$
  Avg Drawdown              -2.61%
  Max Drawdown Duration     407 days 00:00:00
  Max Trade Duration        161 days 00:00:00
  Avg Trade Duration        38 days 00:00:00
  Ann. Return               -1.07%
  Ann. Volatility           14.20%

--- BTC ---
  Return                    13.74%
  Buy & Hold Return         2.27%
  Max Drawdown              -28.23%
  Sharpe Ratio              0.20
  Sortino Ratio             0.33
  Calmar Ratio              0.24
  Profit Factor             1.01
  Expectancy                0.04%
  SQN                       -0.13
  # Trades                  13
  Win Rate                  30.77%
  Best Trade                49.78%
  Worst Trade               -10.76%
  Avg Trade                 -0.89%
  Exposure Time             59.64%
  Equity Final              113735.69$
  Equity Peak               121595.57$
  Avg Drawdown              -7.30%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        113 days 00:00:00
  Avg Trade Duration        34 days 00:00:00
  Ann. Return               6.64%
  Ann. Volatility           33.65%

--- QQQ ---
  Return                    -14.25%
  Buy & Hold Return         39.12%
  Max Drawdown              -27.06%
  Sharpe Ratio              -0.43
  Sortino Ratio             -0.54
  Calmar Ratio              -0.28
  Profit Factor             0.81
  Expectancy                -0.61%
  SQN                       -0.44
  # Trades                  15
  Win Rate                  26.67%
  Best Trade                23.27%
  Worst Trade               -6.70%
  Avg Trade                 -0.86%
  Exposure Time             87.80%
  Equity Final              85745.15$
  Equity Peak               117561.62$
  Avg Drawdown              -7.28%
  Max Drawdown Duration     474 days 00:00:00
  Max Trade Duration        198 days 00:00:00
  Avg Trade Duration        43 days 00:00:00
  Ann. Return               -7.46%
  Ann. Volatility           17.22%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — liquidity-trail-signals-boswaves
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ma_len = 28
    atr_len = 15
    atr_mult = 1.25
    swing_len = 12
    entry_mode = "Signal Change"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        self.ma = self.I(pta.ema, close, length=self.ma_len)
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_len)

        self.trend = 1
        self.trail = None
        self.pending_dir = 0
        self.pending_trail = None

        self.raw_up = self.I(lambda: self.ma - self.atr * self.atr_mult)
        self.raw_dn = self.I(lambda: self.ma + self.atr * self.atr_mult)

    def next(self):
        if len(self.data) < self.ma_len + self.atr_len:
            return

        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]

        ma_val = self.ma[-1]
        atr_val = self.atr[-1]

        raw_up = ma_val - atr_val * self.atr_mult
        raw_dn = ma_val + atr_val * self.atr_mult

        if self.trail is None:
            self.trail = raw_up if close > ma_val else raw_dn
            self.trend = 1 if close > ma_val else -1
        else:
            prev_trend = self.trend

            if self.trend == 1:
                self.trail = max(raw_up, self.trail)
                if close < self.trail:
                    self.trend = -1
                    self.trail = raw_dn
            else:
                self.trail = min(raw_dn, self.trail)
                if close > self.trail:
                    self.trend = 1
                    self.trail = raw_up

            flip_bull = self.trend == 1 and prev_trend == -1
            flip_bear = self.trend == -1 and prev_trend == 1

            if flip_bull:
                self.pending_dir = 1
                self.pending_trail = self.trail

            if flip_bear:
                self.pending_dir = -1
                self.pending_trail = self.trail

            retest_bull_entry = (
                self.entry_mode == "Trail Retest"
                and self.pending_dir == 1
                and low <= self.pending_trail
                and close >= self.pending_trail
            )
            retest_bear_entry = (
                self.entry_mode == "Trail Retest"
                and self.pending_dir == -1
                and high >= self.pending_trail
                and close <= self.pending_trail
            )

            sig_bull_entry = self.entry_mode == "Signal Change" and flip_bull
            sig_bear_entry = self.entry_mode == "Signal Change" and flip_bear

            do_bull_entry = sig_bull_entry or retest_bull_entry
            do_bear_entry = sig_bear_entry or retest_bear_entry

            if retest_bull_entry or retest_bear_entry:
                self.pending_dir = 0

            if do_bull_entry:
                if self.position:
                    self.position.close()
                self.buy()
            elif do_bear_entry:
                if self.position:
                    self.position.close()
                self.sell()