"""
DS-TV Backtest Results: liquidity-stop-hunt-pro-optimized
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    -14.61%
  Buy & Hold Return         14.14%
  Max Drawdown              -44.23%
  Sharpe Ratio              -0.30
  Sortino Ratio             -0.39
  Calmar Ratio              -0.17
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              85391.81$
  Equity Peak               140294.29$
  Avg Drawdown              -7.21%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               -7.58%
  Ann. Volatility           25.48%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — liquidity-stop-hunt-pro-optimized
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Equal Highs / Lows
    eq_lookback = 50
    eq_thresh = 0.02
    
    # Stop Hunt Detection
    swing_len = 10
    hunt_vol_mult = 2.0
    wick_body_min = 3.0
    
    # Leverage levels
    show_lev_10 = True
    show_lev_25 = True
    show_lev_50 = True
    show_lev_100 = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # ATR and Volume SMA
        self.atr14 = self.I(pta.atr, high, low, close, length=14)
        self.vol_sma20 = self.I(pta.sma, volume, length=20)
        
        # Pivot tracking
        self.ph_list = []
        self.pl_list = []
        self.ph_bars = []
        self.pl_bars = []
        
        # State for equal levels
        self.last_ph = None
        self.last_pl = None
        self.prev_ph = None
        self.prev_pl = None
        self.last_ph_bar = None
        self.last_pl_bar = None

    def detect_pivots(self):
        """Detect swing highs and lows"""
        if len(self.data) < self.swing_len * 2:
            return None, None
        
        idx = len(self.data) - 1
        
        # Swing high
        if idx >= self.swing_len:
            is_ph = True
            for i in range(1, self.swing_len + 1):
                if self.data.High[idx - i] >= self.data.High[idx]:
                    is_ph = False
                    break
                if self.data.High[idx + i if idx + i < len(self.data) else idx] >= self.data.High[idx]:
                    is_ph = False
                    break
            if is_ph:
                ph = self.data.High[idx]
            else:
                ph = None
        else:
            ph = None
        
        # Swing low
        if idx >= self.swing_len:
            is_pl = True
            for i in range(1, self.swing_len + 1):
                if self.data.Low[idx - i] <= self.data.Low[idx]:
                    is_pl = False
                    break
                if self.data.Low[idx + i if idx + i < len(self.data) else idx] <= self.data.Low[idx]:
                    is_pl = False
                    break
            if is_pl:
                pl = self.data.Low[idx]
            else:
                pl = None
        else:
            pl = None
        
        return ph, pl

    def check_equal_levels(self):
        """Check for equal highs and lows"""
        ph, pl = self.detect_pivots()
        idx = len(self.data) - 1
        
        is_eqh = False
        is_eql = False
        eqh_price = None
        eql_price = None
        
        if ph is not None:
            if self.last_ph is not None:
                diff_ph = abs(ph - self.last_ph) / self.last_ph * 100
                bar_sep_ph = idx - (self.last_ph_bar if self.last_ph_bar is not None else 0)
                if diff_ph <= self.eq_thresh and bar_sep_ph >= self.swing_len * 2:
                    is_eqh = True
                    eqh_price = max(ph, self.last_ph)
            
            self.prev_ph = self.last_ph
            self.last_ph = ph
            self.last_ph_bar = idx
        
        if pl is not None:
            if self.last_pl is not None:
                diff_pl = abs(pl - self.last_pl) / self.last_pl * 100
                bar_sep_pl = idx - (self.last_pl_bar if self.last_pl_bar is not None else 0)
                if diff_pl <= self.eq_thresh and bar_sep_pl >= self.swing_len * 2:
                    is_eql = True
                    eql_price = min(pl, self.last_pl)
            
            self.prev_pl = self.last_pl
            self.last_pl = pl
            self.last_pl_bar = idx
        
        return is_eqh, is_eql, eqh_price, eql_price, ph, pl

    def check_stop_hunt(self, ph, pl):
        """Detect stop hunts based on wicks and volume"""
        idx = len(self.data) - 1
        
        if idx < self.eq_lookback + 1:
            return False, False
        
        open_price = self.data.Open[-1]
        close_price = self.data.Close[-1]
        high_price = self.data.High[-1]
        low_price = self.data.Low[-1]
        vol = self.data.Volume[-1]
        
        body_size = abs(close_price - open_price)
        upper_wick = high_price - max(open_price, close_price)
        lower_wick = min(open_price, close_price) - low_price
        
        atr_val = self.atr14[-1] if len(self.atr14) > 0 else 0
        vol_thresh = (self.vol_sma20[-1] if len(self.vol_sma20) > 0 else vol) * self.hunt_vol_mult
        atr_half = atr_val * 0.5
        
        # Get swing levels from lookback
        swing_high = max(self.data.High[-self.eq_lookback:-1]) if len(self.data) > self.eq_lookback else high_price
        swing_low = min(self.data.Low[-self.eq_lookback:-1]) if len(self.data) > self.eq_lookback else low_price
        
        bear_hunt = (high_price > swing_high and 
                     close_price < swing_high and 
                     swing_high - close_price > atr_half and 
                     upper_wick > body_size * self.wick_body_min and 
                     vol > vol_thresh)
        
        bull_hunt = (low_price < swing_low and 
                     close_price > swing_low and 
                     close_price - swing_low > atr_half and 
                     lower_wick > body_size * self.wick_body_min and 
                     vol > vol_thresh)
        
        return bear_hunt, bull_hunt

    def next(self):
        idx = len(self.data) - 1
        
        if idx < max(self.swing_len * 2, self.eq_lookback):
            return
        
        # Check for signals
        is_eqh, is_eql, eqh_price, eql_price, ph, pl = self.check_equal_levels()
        bear_hunt, bull_hunt = self.check_stop_hunt(ph, pl)
        
        # Trading logic: Buy on bullish signals, Sell on bearish signals
        if bull_hunt or is_eql:
            if not self.position:
                self.buy()
        
        if bear_hunt or is_eqh:
            if self.position:
                self.sell()


if __name__ == '__main__':
    import yfinance as yf
    
    # Download sample data
    data = yf.download('BTCUSD', start='2023-01-01', end='2024-01-01', interval='1h')
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.001)
    stats = bt.run()
    print(stats)
    bt.plot()