"""
DS-TV Backtest Results: liquidity-sweep-detector
============================================================

--- SPY ---
  Return                    -16.49%
  Buy & Hold Return         40.20%
  Max Drawdown              -28.34%
  Sharpe Ratio              -0.68
  Sortino Ratio             -0.88
  Calmar Ratio              -0.31
  Profit Factor             0.51
  Expectancy                -1.58%
  SQN                       -0.14
  # Trades                  5
  Win Rate                  20.00%
  Best Trade                8.37%
  Worst Trade               -6.75%
  Avg Trade                 -1.73%
  Exposure Time             26.80%
  Equity Final              83508.29$
  Equity Peak               116192.82$
  Avg Drawdown              -6.39%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        69 days 00:00:00
  Avg Trade Duration        53 days 00:00:00
  Ann. Return               -8.68%
  Ann. Volatility           12.86%

--- BTC ---
  Return                    -33.20%
  Buy & Hold Return         0.29%
  Max Drawdown              -41.17%
  Sharpe Ratio              -1.04
  Sortino Ratio             -1.09
  Calmar Ratio              -0.44
  Profit Factor             0.03
  Expectancy                -7.80%
  SQN                       -1.41
  # Trades                  6
  Win Rate                  16.67%
  Best Trade                1.32%
  Worst Trade               -34.44%
  Avg Trade                 -8.75%
  Exposure Time             32.28%
  Equity Final              66804.72$
  Equity Peak               110443.86$
  Avg Drawdown              -11.28%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        150 days 00:00:00
  Avg Trade Duration        40 days 00:00:00
  Ann. Return               -18.24%
  Ann. Volatility           17.51%

--- QQQ ---
  Return                    6.78%
  Buy & Hold Return         45.93%
  Max Drawdown              -18.59%
  Sharpe Ratio              0.20
  Sortino Ratio             0.32
  Calmar Ratio              0.18
  Profit Factor             1.55
  Expectancy                1.68%
  SQN                       0.19
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                14.10%
  Worst Trade               -8.02%
  Avg Trade                 1.26%
  Exposure Time             46.00%
  Equity Final              106781.65$
  Equity Peak               113793.09$
  Avg Drawdown              -2.99%
  Max Drawdown Duration     151 days 00:00:00
  Max Trade Duration        192 days 00:00:00
  Avg Trade Duration        111 days 00:00:00
  Ann. Return               3.36%
  Ann. Volatility           17.18%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — liquidity-sweep-detector
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Zone detection parameters
    length = 8
    maxZones = 8
    zoneRange = "Wick Rejection"
    
    # Sweep detection
    showSweeps = True
    showSweepBG = True
    
    # Quality filters
    useTrendFilter = False
    trendEmaLen = 50
    useVolFilter = False
    volMultiplier = 1.2
    volAvgLen = 20
    useWickFilter = False
    wickMinPct = 40
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        open_price = pd.Series(self.data.Open)
        
        # Calculate trend EMA
        self.trend_ema = self.I(pta.ema, close, length=self.trendEmaLen)
        
        # Calculate volume average
        self.vol_avg = self.I(pta.sma, volume, length=self.volAvgLen)
        
        # Track zones
        self.resistance_zones = []  # List of (top, bottom, bar_index, swept, broken)
        self.support_zones = []     # List of (top, bottom, bar_index, swept, broken)
        
        self.bull_sweep_count = 0
        self.bear_sweep_count = 0
        self.last_bull_sweep_bar = -999
        self.last_bear_sweep_bar = -999
        
        # Store for pivot detection
        self.high_series = high
        self.low_series = low
        self.close_series = close
        self.open_series = open_price
        self.volume_series = volume

    def next(self):
        if len(self.data) < self.length + 1:
            return
        
        idx = len(self.data) - 1
        current_idx = idx
        
        # Get current values
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_close = self.data.Close[-1]
        current_open = self.data.Open[-1]
        current_volume = self.data.Volume[-1]
        
        # Detect pivot high (resistance zone)
        if idx >= 2 * self.length:
            ph_idx = idx - self.length
            if ph_idx > 0 and ph_idx < len(self.data) - self.length:
                is_ph = True
                ph_high = self.data.High[ph_idx]
                
                for i in range(ph_idx - self.length, ph_idx):
                    if i >= 0 and self.data.High[i] >= ph_high:
                        is_ph = False
                        break
                for i in range(ph_idx + 1, ph_idx + self.length + 1):
                    if i < len(self.data) and self.data.High[i] >= ph_high:
                        is_ph = False
                        break
                
                if is_ph:
                    zone_top = ph_high
                    if self.zoneRange == "Wick Rejection":
                        zone_btm = max(self.data.Open[ph_idx], self.data.Close[ph_idx])
                    else:
                        zone_btm = self.data.Low[ph_idx]
                    
                    # Add resistance zone
                    self.resistance_zones.append({
                        'top': zone_top,
                        'btm': zone_btm,
                        'x1': ph_idx,
                        'swept': False,
                        'broken': False,
                        'tests': 0
                    })
                    
                    if len(self.resistance_zones) > self.maxZones:
                        self.resistance_zones.pop(0)
        
        # Detect pivot low (support zone)
        if idx >= 2 * self.length:
            pl_idx = idx - self.length
            if pl_idx > 0 and pl_idx < len(self.data) - self.length:
                is_pl = True
                pl_low = self.data.Low[pl_idx]
                
                for i in range(pl_idx - self.length, pl_idx):
                    if i >= 0 and self.data.Low[i] <= pl_low:
                        is_pl = False
                        break
                for i in range(pl_idx + 1, pl_idx + self.length + 1):
                    if i < len(self.data) and self.data.Low[i] <= pl_low:
                        is_pl = False
                        break
                
                if is_pl:
                    if self.zoneRange == "Wick Rejection":
                        zone_top = min(self.data.Open[pl_idx], self.data.Close[pl_idx])
                    else:
                        zone_top = self.data.High[pl_idx]
                    zone_btm = pl_low
                    
                    # Add support zone
                    self.support_zones.append({
                        'top': zone_top,
                        'btm': zone_btm,
                        'x1': pl_idx,
                        'swept': False,
                        'broken': False,
                        'tests': 0
                    })
                    
                    if len(self.support_zones) > self.maxZones:
                        self.support_zones.pop(0)
        
        # Calculate quality filters
        bar_range = current_high - current_low
        body_size = abs(current_close - current_open)
        wick_pct = (bar_range - body_size) / bar_range * 100 if bar_range > 0 else 0
        
        is_above_ema = current_close > self.trend_ema[-1] if not np.isnan(self.trend_ema[-1]) else True
        is_below_ema = current_close < self.trend_ema[-1] if not np.isnan(self.trend_ema[-1]) else True
        is_vol_spike = current_volume > self.vol_avg[-1] * self.volMultiplier if not np.isnan(self.vol_avg[-1]) else True
        is_strong_wick = wick_pct >= self.wickMinPct
        
        bull_filter_ok = (not self.useTrendFilter or is_above_ema) and \
                         (not self.useVolFilter or is_vol_spike) and \
                         (not self.useWickFilter or is_strong_wick)
        
        bear_filter_ok = (not self.useTrendFilter or is_below_ema) and \
                         (not self.useVolFilter or is_vol_spike) and \
                         (not self.useWickFilter or is_strong_wick)
        
        bull_sweep_now = False
        bear_sweep_now = False
        
        # Update resistance zones
        for zone in self.resistance_zones:
            if not zone['broken']:
                # Test: high touches zone but close stays below top
                if zone['btm'] < current_high <= zone['top'] and current_close < zone['btm']:
                    zone['tests'] += 1
                
                # Sweep: wick above top but close back below top
                if current_high > zone['top'] and current_close <= zone['top'] and not zone['swept'] and bear_filter_ok:
                    zone['swept'] = True
                    bear_sweep_now = True
                    self.bear_sweep_count += 1
                    self.last_bear_sweep_bar = current_idx
                
                # Broken: close firmly above top
                if current_close > zone['top'] and (idx > 0 and self.data.Close[idx - 1] > zone['top']):
                    zone['broken'] = True
        
        # Update support zones
        for zone in self.support_zones:
            if not zone['broken']:
                # Test: low dips into zone but close stays above btm
                if zone['btm'] <= current_low < zone['top'] and current_close > zone['top']:
                    zone['tests'] += 1
                
                # Sweep: wick below btm but close back above btm
                if current_low < zone['btm'] and current_close >= zone['btm'] and not zone['swept'] and bull_filter_ok:
                    zone['swept'] = True
                    bull_sweep_now = True
                    self.bull_sweep_count += 1
                    self.last_bull_sweep_bar = current_idx
                
                # Broken: close firmly below btm
                if current_close < zone['btm'] and (idx > 0 and self.data.Close[idx - 1] < zone['btm']):
                    zone['broken'] = True
        
        # Trading logic based on sweeps
        if bull_sweep_now and not self.position:
            self.buy()
        elif bear_sweep_now and self.position:
            self.sell()
        
        # Exit logic: if we entered on bull sweep, exit on bear sweep (or vice versa)
        if self.position:
            if bear_sweep_now and self.last_bull_sweep_bar >= 0 and current_idx - self.last_bull_sweep_bar > 1:
                self.sell()


if __name__ == '__main__':
    from datetime import datetime
    
    # Example: run backtest on sample data
    # Note: You'll need to load your own OHLCV data
    # This is a template showing how to run the backtest
    
    # bt = Backtest(data, TvStrategy, cash=10000, commission=0.001)
    # stats = bt.run()
    # print(stats)
    # bt.plot()