"""
DS-TV Backtest Results: liquidation-heatmap-by-rumiancev
============================================================

--- SPY ---
  Return                    35.79%
  Buy & Hold Return         41.94%
  Max Drawdown              -18.68%
  Sharpe Ratio              0.94
  Sortino Ratio             1.66
  Calmar Ratio              0.89
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              135788.74$
  Equity Peak               136089.04$
  Avg Drawdown              -1.65%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               16.67%
  Ann. Volatility           17.80%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    18.70%
  Buy & Hold Return         42.67%
  Max Drawdown              -22.74%
  Sharpe Ratio              0.48
  Sortino Ratio             0.78
  Calmar Ratio              0.40
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              118696.83$
  Equity Peak               122678.80$
  Avg Drawdown              -3.02%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               9.02%
  Ann. Volatility           18.86%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — liquidation-heatmap-by-rumiancev
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    lookback = 100
    sens = 10
    minBarGap = 0
    lev1 = 100
    lev2 = 50
    lev3 = 25
    scaleTicks = 600
    dispPct = 0.20
    refPL = "close"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        def calculate_stream():
            volume_data = volume if volume is not None else pd.Series(0, index=close.index)
            return volume_data
        
        def calculate_spike_detection():
            stream = calculate_stream()
            stream_abs = stream.abs()
            
            mu = pta.sma(stream_abs, length=self.lookback)
            sd = pta.stdev(stream_abs, length=self.lookback)
            
            if mu is None or sd is None:
                return pd.Series(0, index=close.index)
            
            z = pd.Series(index=close.index, dtype=float)
            for i in range(len(close)):
                if sd.iloc[i] > 0:
                    z.iloc[i] = (stream_abs.iloc[i] - mu.iloc[i]) / sd.iloc[i]
                else:
                    z.iloc[i] = 0.0
            
            thr = 1.0 + (self.sens - 1) * (2.0 / 19.0)
            return z > thr
        
        def calculate_ref_price():
            if self.refPL == "open":
                return pd.Series(self.data.Open)
            elif self.refPL == "close":
                return close
            elif self.refPL == "hl2":
                return (high + low) / 2
            elif self.refPL == "hlc3":
                return (high + low + close) / 3
            else:
                return close
        
        self.spike_signal = self.I(calculate_spike_detection)
        self.ref_price = self.I(calculate_ref_price)
        
    def next(self):
        if len(self.data) < self.lookback + 5:
            return
        
        current_spike = self.spike_signal[-1]
        
        if current_spike and not self.position:
            ref_p = self.ref_price[-1]
            
            liq_prices = []
            if self.lev1 > 0:
                lp = ref_p * (1.0 - 1.0 / self.lev1)
                sp = ref_p * (1.0 + 1.0 / self.lev1)
                liq_prices.append((lp, sp))
            
            if self.lev2 > 0:
                lp = ref_p * (1.0 - 1.0 / self.lev2)
                sp = ref_p * (1.0 + 1.0 / self.lev2)
                liq_prices.append((lp, sp))
            
            if self.lev3 > 0:
                lp = ref_p * (1.0 - 1.0 / self.lev3)
                sp = ref_p * (1.0 + 1.0 / self.lev3)
                liq_prices.append((lp, sp))
            
            if liq_prices:
                avg_long_liq = np.mean([lp for lp, sp in liq_prices])
                avg_short_liq = np.mean([sp for lp, sp in liq_prices])
                
                current_price = self.data.Close[-1]
                
                dist_to_long = abs(current_price - avg_long_liq)
                dist_to_short = abs(current_price - avg_short_liq)
                
                if dist_to_long < dist_to_short and current_price > avg_long_liq:
                    self.buy()
                elif dist_to_short < dist_to_long and current_price < avg_short_liq:
                    self.buy()
        
        elif self.position:
            ref_p = self.ref_price[-1]
            current_price = self.data.Close[-1]
            
            if self.position.is_long:
                avg_liq = ref_p * (1.0 - 1.0 / max(self.lev1, self.lev2, self.lev3))
                if current_price <= avg_liq * 0.98:
                    self.position.close()
            else:
                avg_liq = ref_p * (1.0 + 1.0 / max(self.lev1, self.lev2, self.lev3))
                if current_price >= avg_liq * 1.02:
                    self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()