"""
DS-TV Backtest Results: ma-matrix-pro-multi-timeframe-trend-analyzer
============================================================

--- SPY ---
  Return                    -12.19%
  Buy & Hold Return         17.90%
  Max Drawdown              -17.30%
  Sharpe Ratio              -0.52
  Sortino Ratio             -0.61
  Calmar Ratio              -0.37
  Profit Factor             0.70
  Expectancy                -0.26%
  SQN                       -0.72
  # Trades                  43
  Win Rate                  23.26%
  Best Trade                10.24%
  Worst Trade               -6.86%
  Avg Trade                 -0.29%
  Exposure Time             59.00%
  Equity Final              87809.83$
  Equity Peak               106176.66$
  Avg Drawdown              -4.51%
  Max Drawdown Duration     321 days 00:00:00
  Max Trade Duration        38 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -6.34%
  Ann. Volatility           12.11%

--- BTC ---
  Return                    -20.58%
  Buy & Hold Return         17.39%
  Max Drawdown              -23.61%
  Sharpe Ratio              -0.70
  Sortino Ratio             -0.88
  Calmar Ratio              -0.46
  Profit Factor             0.57
  Expectancy                -1.31%
  SQN                       -0.98
  # Trades                  20
  Win Rate                  25.00%
  Best Trade                18.15%
  Worst Trade               -8.31%
  Avg Trade                 -1.49%
  Exposure Time             14.50%
  Equity Final              79420.21$
  Equity Peak               103971.31$
  Avg Drawdown              -10.18%
  Max Drawdown Duration     445 days 00:00:00
  Max Trade Duration        14 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               -10.87%
  Ann. Volatility           15.46%

--- QQQ ---
  Return                    -16.72%
  Buy & Hold Return         22.08%
  Max Drawdown              -23.31%
  Sharpe Ratio              -0.60
  Sortino Ratio             -0.69
  Calmar Ratio              -0.38
  Profit Factor             0.69
  Expectancy                -0.43%
  SQN                       -0.85
  # Trades                  39
  Win Rate                  30.77%
  Best Trade                12.05%
  Worst Trade               -10.36%
  Avg Trade                 -0.49%
  Exposure Time             58.20%
  Equity Final              83281.92$
  Equity Peak               106077.79$
  Avg Drawdown              -7.55%
  Max Drawdown Duration     333 days 00:00:00
  Max Trade Duration        36 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -8.81%
  Ann. Volatility           14.71%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ma-matrix-pro-multi-timeframe-trend-analyzer
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.m5 = self.I(pta.sma, close, length=5)
        self.m8 = self.I(pta.sma, close, length=8)
        self.m13 = self.I(pta.sma, close, length=13)
        self.m21 = self.I(pta.ema, close, length=21)
        self.m34 = self.I(pta.ema, close, length=34)
        self.m200 = self.I(pta.ema, close, length=200)
        self.atr_val = self.I(pta.atr, high, low, close, length=14)
        
        self.in_long = False
        self.in_short = False

    def next(self):
        if len(self.data) < 2:
            return
        
        close_price = self.data.Close[-1]
        m5_val = self.m5[-1]
        m8_val = self.m8[-1]
        m13_val = self.m13[-1]
        m21_val = self.m21[-1]
        m34_val = self.m34[-1]
        m200_val = self.m200[-1]
        atr_val = self.atr_val[-1]
        
        if pd.isna(m5_val) or pd.isna(m8_val) or pd.isna(m13_val) or pd.isna(m21_val) or pd.isna(m34_val) or pd.isna(m200_val) or pd.isna(atr_val):
            return
        
        tol = atr_val * 0.1
        
        k_up = m5_val > m8_val and m8_val > m13_val
        k_dn = m5_val < m8_val and m8_val < m13_val
        
        o_up = m21_val > (m34_val + tol)
        o_dn = m21_val < (m34_val - tol)
        
        price_above_200 = close_price > m200_val
        price_above_m5 = close_price > m5_val
        price_above_m13 = close_price > m13_val
        price_below_m5 = close_price < m5_val
        price_below_m13 = close_price < m13_val
        
        if k_up and o_up:
            if price_above_m5 and not self.in_long and price_above_200:
                self.buy()
                self.in_long = True
                self.in_short = False
            elif price_below_m5 and self.in_long:
                self.sell()
                self.in_long = False
        
        elif k_dn and o_dn:
            if price_below_m5 and not self.in_short and not price_above_200:
                self.sell()
                self.in_short = True
                self.in_long = False
            elif price_above_m5 and self.in_short:
                self.buy()
                self.in_short = False
        
        else:
            if self.in_long and (price_below_m13 or k_dn):
                self.sell()
                self.in_long = False
            elif self.in_short and (price_above_m13 or k_up):
                self.buy()
                self.in_short = False


if __name__ == "__main__":
    bt = Backtest(
        pd.read_csv("data.csv", index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.002,
        exclusive_orders=True
    )
    stats = bt.run()
    print(stats)
    bt.plot()