"""
DS-TV Backtest Results: matrix-supply-demand-zones-matrix-trading-lab
============================================================

--- SPY ---
  Return                    -50.21%
  Buy & Hold Return         38.66%
  Max Drawdown              -54.23%
  Sharpe Ratio              -3.03
  Sortino Ratio             -2.63
  Calmar Ratio              -0.55
  Profit Factor             0.47
  Expectancy                -0.29%
  SQN                       -2.66
  # Trades                  230
  Win Rate                  35.22%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.30%
  Exposure Time             47.00%
  Equity Final              49793.51$
  Equity Peak               108781.86$
  Avg Drawdown              -12.60%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        5 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -29.63%
  Ann. Volatility           9.78%

--- BTC ---
  Return                    -26.68%
  Buy & Hold Return         37.68%
  Max Drawdown              -31.18%
  Sharpe Ratio              -1.15
  Sortino Ratio             -1.21
  Calmar Ratio              -0.46
  Profit Factor             0.66
  Expectancy                -0.39%
  SQN                       -1.48
  # Trades                  113
  Win Rate                  46.90%
  Best Trade                9.78%
  Worst Trade               -9.26%
  Avg Trade                 -0.43%
  Exposure Time             18.60%
  Equity Final              73323.25$
  Equity Peak               106538.39$
  Avg Drawdown              -9.08%
  Max Drawdown Duration     583 days 00:00:00
  Max Trade Duration        7 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -14.35%
  Ann. Volatility           12.53%

--- QQQ ---
  Return                    -49.95%
  Buy & Hold Return         39.38%
  Max Drawdown              -57.66%
  Sharpe Ratio              -2.49
  Sortino Ratio             -2.23
  Calmar Ratio              -0.51
  Profit Factor             0.58
  Expectancy                -0.28%
  SQN                       -2.12
  # Trades                  236
  Win Rate                  36.86%
  Best Trade                6.54%
  Worst Trade               -9.35%
  Avg Trade                 -0.29%
  Exposure Time             47.60%
  Equity Final              50049.30$
  Equity Peak               116752.77$
  Avg Drawdown              -11.52%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -29.45%
  Ann. Volatility           11.85%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — matrix-supply-demand-zones-matrix-trading-lab
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    swingLen = 20
    zoneSourceMode = "Full Candle"
    maxZones = 4
    extendBars = 80
    minZoneATR = 0.10
    maxZoneATR = 2.50
    autoRemove = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        
        self.atr = self.I(pta.atr, high, low, close, length=14)
        
        self.demand_zones = []
        self.supply_zones = []
        self.last_demand_top = None
        self.last_demand_bottom = None
        self.last_supply_top = None
        self.last_supply_bottom = None
        
    def _get_source_top(self, idx):
        if self.zoneSourceMode == "Body Only":
            return max(self.data.Open[idx], self.data.Close[idx])
        else:
            return self.data.High[idx]
    
    def _get_source_bottom(self, idx):
        if self.zoneSourceMode == "Body Only":
            return min(self.data.Open[idx], self.data.Close[idx])
        else:
            return self.data.Low[idx]
    
    def _get_pivot_high(self):
        if len(self.data) < self.swingLen * 2 + 1:
            return None
        
        idx = len(self.data) - 1 - self.swingLen
        if idx < self.swingLen:
            return None
        
        pivot_high = self.data.High[idx]
        for i in range(idx - self.swingLen, idx):
            if self.data.High[i] > pivot_high:
                return None
        for i in range(idx + 1, idx + self.swingLen + 1):
            if i >= len(self.data):
                return None
            if self.data.High[i] > pivot_high:
                return None
        
        return pivot_high, idx
    
    def _get_pivot_low(self):
        if len(self.data) < self.swingLen * 2 + 1:
            return None
        
        idx = len(self.data) - 1 - self.swingLen
        if idx < self.swingLen:
            return None
        
        pivot_low = self.data.Low[idx]
        for i in range(idx - self.swingLen, idx):
            if self.data.Low[i] < pivot_low:
                return None
        for i in range(idx + 1, idx + self.swingLen + 1):
            if i >= len(self.data):
                return None
            if self.data.Low[i] < pivot_low:
                return None
        
        return pivot_low, idx
    
    def next(self):
        if len(self.data) < self.swingLen * 2 + 1:
            return
        
        current_atr = self.atr[-1]
        if current_atr is None or np.isnan(current_atr):
            return
        
        pivot_low_result = self._get_pivot_low()
        if pivot_low_result is not None:
            pivot_low, pivot_idx = pivot_low_result
            src = self.swingLen
            top_val = self._get_source_top(pivot_idx)
            bot_val = self._get_source_bottom(pivot_idx)
            zone_size = top_val - bot_val
            
            valid_size = (zone_size >= current_atr * self.minZoneATR and 
                         zone_size <= current_atr * self.maxZoneATR)
            
            if valid_size:
                self.demand_zones.insert(0, {
                    'top': top_val,
                    'bottom': bot_val,
                    'invalidated': False
                })
                self.last_demand_top = top_val
                self.last_demand_bottom = bot_val
                
                if len(self.demand_zones) > self.maxZones:
                    self.demand_zones.pop()
        
        pivot_high_result = self._get_pivot_high()
        if pivot_high_result is not None:
            pivot_high, pivot_idx = pivot_high_result
            src = self.swingLen
            top_val = self._get_source_top(pivot_idx)
            bot_val = self._get_source_bottom(pivot_idx)
            zone_size = top_val - bot_val
            
            valid_size = (zone_size >= current_atr * self.minZoneATR and 
                         zone_size <= current_atr * self.maxZoneATR)
            
            if valid_size:
                self.supply_zones.insert(0, {
                    'top': top_val,
                    'bottom': bot_val,
                    'invalidated': False
                })
                self.last_supply_top = top_val
                self.last_supply_bottom = bot_val
                
                if len(self.supply_zones) > self.maxZones:
                    self.supply_zones.pop()
        
        for demand_zone in self.demand_zones:
            if self.data.Close[-1] < demand_zone['bottom']:
                if self.autoRemove:
                    demand_zone['invalidated'] = True
                else:
                    demand_zone['invalidated'] = True
        
        if self.autoRemove:
            self.demand_zones = [z for z in self.demand_zones if not z['invalidated']]
        
        for supply_zone in self.supply_zones:
            if self.data.Close[-1] > supply_zone['top']:
                if self.autoRemove:
                    supply_zone['invalidated'] = True
                else:
                    supply_zone['invalidated'] = True
        
        if self.autoRemove:
            self.supply_zones = [z for z in self.supply_zones if not z['invalidated']]
        
        inside_demand = False
        inside_supply = False
        
        if self.last_demand_top and self.last_demand_bottom:
            if self.data.Close[-1] >= self.last_demand_bottom and self.data.Close[-1] <= self.last_demand_top:
                inside_demand = True
        
        if self.last_supply_top and self.last_supply_bottom:
            if self.data.Close[-1] >= self.last_supply_bottom and self.data.Close[-1] <= self.last_supply_top:
                inside_supply = True
        
        if inside_demand and not self.position:
            self.buy()
        elif inside_supply and self.position:
            self.sell()
        elif not inside_demand and not inside_supply and self.position:
            self.sell()