"""
DS-TV Backtest Results: moving-average-ribbon-ma-ribbon-tr
============================================================

--- SPY ---
  Return                    28.90%
  Buy & Hold Return         40.20%
  Max Drawdown              -8.38%
  Sharpe Ratio              1.12
  Sortino Ratio             1.79
  Calmar Ratio              1.63
  Profit Factor             nan
  Expectancy                3.96%
  SQN                       2.64
  # Trades                  2
  Win Rate                  100.00%
  Best Trade                5.42%
  Worst Trade               2.50%
  Avg Trade                 3.95%
  Exposure Time             40.40%
  Equity Final              128900.80$
  Equity Peak               129185.70$
  Avg Drawdown              -1.62%
  Max Drawdown Duration     134 days 00:00:00
  Max Trade Duration        202 days 00:00:00
  Avg Trade Duration        148 days 00:00:00
  Ann. Return               13.65%
  Ann. Volatility           12.18%

--- BTC ---
  Return                    4.31%
  Buy & Hold Return         0.29%
  Max Drawdown              -28.22%
  Sharpe Ratio              0.09
  Sortino Ratio             0.14
  Calmar Ratio              0.08
  Profit Factor             1.37
  Expectancy                2.54%
  SQN                       0.10
  # Trades                  7
  Win Rate                  28.57%
  Best Trade                50.24%
  Worst Trade               -18.29%
  Avg Trade                 0.59%
  Exposure Time             49.25%
  Equity Final              104314.16$
  Equity Peak               145316.03$
  Avg Drawdown              -6.05%
  Max Drawdown Duration     181 days 00:00:00
  Max Trade Duration        148 days 00:00:00
  Avg Trade Duration        51 days 00:00:00
  Ann. Return               2.13%
  Ann. Volatility           23.93%

--- QQQ ---
  Return                    11.91%
  Buy & Hold Return         45.93%
  Max Drawdown              -19.86%
  Sharpe Ratio              0.38
  Sortino Ratio             0.54
  Calmar Ratio              0.29
  Profit Factor             0.42
  Expectancy                -1.97%
  SQN                       -0.66
  # Trades                  3
  Win Rate                  33.33%
  Best Trade                4.29%
  Worst Trade               -6.75%
  Avg Trade                 -2.08%
  Exposure Time             36.80%
  Equity Final              111909.27$
  Equity Peak               115664.28$
  Avg Drawdown              -4.14%
  Max Drawdown Duration     455 days 00:00:00
  Max Trade Duration        169 days 00:00:00
  Avg Trade Duration        90 days 00:00:00
  Ann. Return               5.83%
  Ann. Volatility           15.40%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — moving-average-ribbon-ma-ribbon-tr
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    Length_1 = 21
    Length_2 = 50
    MA_Type = 'EMA'
    lookback_momentum = 5
    lookback_spread = 70
    lookback_max_momentum = 50

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)

        # Calculate moving averages based on type
        if self.MA_Type == 'EMA':
            self.value_1 = self.I(pta.ema, close, length=self.Length_1)
            self.value_2 = self.I(pta.ema, close, length=self.Length_2)
        elif self.MA_Type == 'SMA':
            self.value_1 = self.I(pta.sma, close, length=self.Length_1)
            self.value_2 = self.I(pta.sma, close, length=self.Length_2)
        elif self.MA_Type == 'RMA':
            self.value_1 = self.I(pta.rma, close, length=self.Length_1)
            self.value_2 = self.I(pta.rma, close, length=self.Length_2)
        elif self.MA_Type == 'WMA':
            self.value_1 = self.I(pta.wma, close, length=self.Length_1)
            self.value_2 = self.I(pta.wma, close, length=self.Length_2)
        elif self.MA_Type == 'VWMA':
            self.value_1 = self.I(pta.vwma, close, volume, length=self.Length_1)
            self.value_2 = self.I(pta.vwma, close, volume, length=self.Length_2)
        elif self.MA_Type == 'HMA':
            self.value_1 = self.I(pta.hma, close, length=self.Length_1)
            self.value_2 = self.I(pta.hma, close, length=self.Length_2)
        elif self.MA_Type == 'DEMA':
            self.value_1 = self.I(pta.dema, close, length=self.Length_1)
            self.value_2 = self.I(pta.dema, close, length=self.Length_2)
        elif self.MA_Type == 'TEMA':
            self.value_1 = self.I(pta.tema, close, length=self.Length_1)
            self.value_2 = self.I(pta.tema, close, length=self.Length_2)
        else:  # Default to EMA
            self.value_1 = self.I(pta.ema, close, length=self.Length_1)
            self.value_2 = self.I(pta.ema, close, length=self.Length_2)

        # Calculate spread
        def calc_spread(idx):
            if idx < len(close):
                return self.value_1[idx] - self.value_2[idx]
            return 0

        self.spread = self.I(lambda: pd.Series([self.value_1[i] - self.value_2[i] if i < len(self.value_1) and i < len(self.value_2) else 0 for i in range(len(self.value_1))]))

        # Calculate momentum
        def calc_momentum(idx):
            if idx >= self.lookback_momentum and self.value_1[idx] is not None and self.value_1[idx - self.lookback_momentum] is not None:
                return abs(self.value_1[idx] - self.value_1[idx - self.lookback_momentum])
            return 0

        self.momentum = self.I(lambda: pd.Series([abs(self.value_1[i] - self.value_1[max(0, i - self.lookback_momentum)]) if i < len(self.value_1) else 0 for i in range(len(self.value_1))]))

        # Track crossovers for entry/exit signals
        self.bull_crossover = self.I(lambda: pd.Series([1 if i > 0 and self.value_1[i] > self.value_2[i] and self.value_1[i-1] <= self.value_2[i-1] else 0 for i in range(len(self.value_1))]))
        self.bear_crossover = self.I(lambda: pd.Series([1 if i > 0 and self.value_1[i] < self.value_2[i] and self.value_1[i-1] >= self.value_2[i-1] else 0 for i in range(len(self.value_1))]))

    def next(self):
        # Entry signal: Fast MA crosses above Slow MA (bullish)
        if self.bull_crossover[-1] > 0:
            if not self.position:
                self.buy()

        # Exit signal: Fast MA crosses below Slow MA (bearish)
        if self.bear_crossover[-1] > 0:
            if self.position:
                self.position.close()