"""
DS-TV Backtest Results: nifty-bank-nifty-options-target-levels
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — nifty-bank-nifty-options-target-levels
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Zone definitions
    zones = [
        (11, 9),    # Zone 1
        (19, 17),   # Zone 2
        (37, 35),   # Zone 3
        (66, 64),   # Zone 4
        (82, 80),   # Zone 5
        (107, 105), # Zone 6
        (126, 125), # Zone 7
        (145, 143), # Zone 8
        (166, 164), # Zone 9
        (187, 185), # Zone 10
        (214, 212), # Zone 11
        (226, 225), # Zone 12
        (287, 286), # Zone 13
        (257, 256), # Zone 14
        (288, 286), # Zone 15
        (324, 322), # Zone 16
        (354, 352), # Zone 17
        (432, 431), # Zone 18
        (389, 388), # Zone 19
        (408, 407), # Zone 20
        (458, 456), # Zone 21
        (484, 482), # Zone 22
        (529, 528), # Zone 23
        (576, 575), # Zone 24
        (626, 624), # Zone 25
        (676, 675), # Zone 26
        (729, 728), # Zone 27
        (784, 782), # Zone 28
        (512, 511), # Zone 29
        (306, 304), # Zone 30
    ]

    def init(self):
        # This is a zone-based indicator, not a traditional moving average or oscillator
        # We'll create a simple trading logic based on price proximity to zones
        pass

    def next(self):
        current_price = self.data.Close[-1]
        
        # Find which zone the price is in or near
        in_zone = False
        for i, (high, low) in enumerate(self.zones):
            zone_top = max(high, low)
            zone_bot = min(high, low)
            
            # If price is in the zone
            if zone_bot <= current_price <= zone_top:
                in_zone = True
                # Buy at lower part of zone, sell at upper part
                if current_price <= zone_bot + (zone_top - zone_bot) * 0.3:
                    if not self.position:
                        self.buy()
                elif current_price >= zone_top - (zone_top - zone_bot) * 0.3:
                    if self.position:
                        self.sell()
                break
        
        # If not in any zone, use simple mean reversion logic
        if not in_zone:
            # Find nearest zone above and below
            zones_above = [z for z in self.zones if min(z) > current_price]
            zones_below = [z for z in self.zones if max(z) < current_price]
            
            if zones_below:
                nearest_above = min(zones_above, key=lambda z: min(z)) if zones_above else None
                # Price between zones, buy on pullback toward support
                if self.position and len(self) % 5 == 0:
                    self.sell()
            elif zones_above:
                # Price above all zones, sell on bounces
                if self.position:
                    self.sell()


if __name__ == '__main__':
    # Example backtesting with sample data
    df = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()