"""
DS-TV Backtest Results: order-block-finder-definededge
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — order-block-finder-definededge
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    swing_len = 5
    max_ob = 8
    min_impulse = 1.0
    require_vol = False
    prox_pct = 1.0
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.atr14 = self.I(pta.atr, high, low, close, length=14)
        self.vol_sma = self.I(pta.sma, volume, length=20)
        
        self.bull_obs = []
        self.bear_obs = []
        self.bull_brk = []
        self.bear_brk = []
        
        self.last_swing_high = np.nan
        self.last_swing_low = np.nan
        
        self.bull_ob_found = False
        self.bear_ob_found = False
        
    def detect_structure(self):
        if len(self.data) < self.swing_len * 2 + 1:
            return
        
        idx = len(self.data) - 1
        close = self.data.Close
        high = self.data.High
        low = self.data.Low
        
        pivot_high = True
        pivot_low = True
        
        for i in range(1, self.swing_len + 1):
            if idx - i < 0 or idx + i >= len(close):
                pivot_high = False
                pivot_low = False
                break
            if high[idx - i] >= high[idx] or high[idx + i] >= high[idx]:
                pivot_high = False
            if low[idx - i] <= low[idx] or low[idx + i] <= low[idx]:
                pivot_low = False
        
        if pivot_high:
            self.last_swing_high = high[idx]
        
        if pivot_low:
            self.last_swing_low = low[idx]
    
    def detect_order_blocks(self):
        if len(self.data) < self.swing_len * 2 + 2:
            return
        
        close = self.data.Close
        open_ = self.data.Open
        high = self.data.High
        low = self.data.Low
        volume = self.data.Volume
        
        idx = len(self.data) - 1
        atr_val = self.atr14[-1] if not np.isnan(self.atr14[-1]) else 0
        vol_avg = self.vol_sma[-1] if not np.isnan(self.vol_sma[-1]) else 1
        
        strong_bull = (close[idx] > open_[idx] and 
                       (close[idx] - open_[idx]) > self.min_impulse * atr_val)
        strong_bear = (open_[idx] > close[idx] and 
                       (open_[idx] - close[idx]) > self.min_impulse * atr_val)
        
        vol_ok = (volume[idx] > vol_avg) if self.require_vol else True
        
        self.bull_ob_found = False
        self.bear_ob_found = False
        
        if strong_bull and vol_ok:
            for lookback in range(1, min(self.swing_len * 2, 10) + 1):
                if idx - lookback < 0:
                    break
                if close[idx - lookback] < open_[idx - lookback]:
                    ob_top = high[idx - lookback]
                    ob_btm = low[idx - lookback]
                    self.bull_obs.append({
                        'top': ob_top,
                        'btm': ob_btm,
                        'idx': idx - lookback,
                        'vol_ratio': volume[idx - lookback] / vol_avg if vol_avg > 0 else 1.0,
                        'impulse': (close[idx] - open_[idx]) / atr_val if atr_val > 0 else 1.0,
                        'tests': 0
                    })
                    self.bull_ob_found = True
                    break
        
        if strong_bear and vol_ok:
            for lookback in range(1, min(self.swing_len * 2, 10) + 1):
                if idx - lookback < 0:
                    break
                if close[idx - lookback] > open_[idx - lookback]:
                    ob_top = high[idx - lookback]
                    ob_btm = low[idx - lookback]
                    self.bear_obs.append({
                        'top': ob_top,
                        'btm': ob_btm,
                        'idx': idx - lookback,
                        'vol_ratio': volume[idx - lookback] / vol_avg if vol_avg > 0 else 1.0,
                        'impulse': (open_[idx] - close[idx]) / atr_val if atr_val > 0 else 1.0,
                        'tests': 0
                    })
                    self.bear_ob_found = True
                    break
        
        while len(self.bull_obs) > self.max_ob:
            self.bull_obs.pop()
        
        while len(self.bear_obs) > self.max_ob:
            self.bear_obs.pop()
    
    def process_order_blocks(self):
        close = self.data.Close[-1]
        low = self.data.Low[-1]
        high = self.data.High[-1]
        
        bull_obs_to_remove = []
        for i, ob in enumerate(self.bull_obs):
            if close < ob['btm']:
                self.bear_brk.append(ob)
                bull_obs_to_remove.append(i)
            elif low < ob['top'] and low >= ob['btm'] and close >= ob['btm']:
                ob['tests'] += 1
        
        for i in sorted(bull_obs_to_remove, reverse=True):
            self.bull_obs.pop(i)
        
        bear_obs_to_remove = []
        for i, ob in enumerate(self.bear_obs):
            if close > ob['top']:
                self.bull_brk.append(ob)
                bear_obs_to_remove.append(i)
            elif high > ob['btm'] and high <= ob['top'] and close <= ob['top']:
                ob['tests'] += 1
        
        for i in sorted(bear_obs_to_remove, reverse=True):
            self.bear_obs.pop(i)
        
        bull_brk_to_remove = []
        for i, brk in enumerate(self.bull_brk):
            if close < brk['btm']:
                bull_brk_to_remove.append(i)
        
        for i in sorted(bull_brk_to_remove, reverse=True):
            self.bull_brk.pop(i)
        
        bear_brk_to_remove = []
        for i, brk in enumerate(self.bear_brk):
            if close > brk['top']:
                bear_brk_to_remove.append(i)
        
        for i in sorted(bear_brk_to_remove, reverse=True):
            self.bear_brk.pop(i)
    
    def next(self):
        self.detect_structure()
        self.detect_order_blocks()
        self.process_order_blocks()
        
        close = self.data.Close[-1]
        
        if len(self.bull_obs) > 0:
            strongest_bull_ob = max(self.bull_obs, key=lambda x: x['vol_ratio'] * x['impulse'])
            if close < strongest_bull_ob['btm'] and not self.position:
                self.buy()
        
        if len(self.bear_obs) > 0:
            strongest_bear_ob = max(self.bear_obs, key=lambda x: x['vol_ratio'] * x['impulse'])
            if close > strongest_bear_ob['top'] and self.position:
                self.position.close()
        
        if len(self.bear_obs) > 0:
            strongest_bear_ob = max(self.bear_obs, key=lambda x: x['vol_ratio'] * x['impulse'])
            if close > strongest_bear_ob['top'] and not self.position:
                self.sell()
        
        if len(self.bull_obs) > 0:
            strongest_bull_ob = max(self.bull_obs, key=lambda x: x['vol_ratio'] * x['impulse'])
            if close < strongest_bull_ob['btm'] and self.position:
                self.position.close()


if __name__ == '__main__':
    import yfinance as yf
    
    data = yf.download('SPY', start='2020-01-01', end='2024-01-01', progress=False)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()