"""
DS-TV Backtest Results: orderflow-synthesis-pro-joat
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(atr(14),50)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "sma(atr(14),50)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(atr(14),50)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — orderflow-synthesis-pro-joat
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Order Block Detection parameters
    ob_lookback = 20
    ob_vol_mult = 1.3
    ob_atr_mult = 1.5
    
    # Fair Value Gap parameters
    fvg_min_size = 0.3
    
    # Liquidity Analysis parameters
    liq_swing_len = 5
    liq_tolerance = 0.15
    
    # Premium/Discount Array parameters
    pd_array_len = 50

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate ATR and volume indicators
        self.atr = self.I(pta.atr, high, low, close, length=14)
        self.avg_vol = self.I(pta.sma, volume, length=20)
        self.atr_sma50 = self.I(pta.sma, self.atr, length=50)
        
        # Calculate pivot points for liquidity
        self.pivot_high = self.I(lambda: pta.pivothigh(high, self.liq_swing_len, self.liq_swing_len) or pd.Series(np.nan, index=high.index))
        self.pivot_low = self.I(lambda: pta.pivotlow(low, self.liq_swing_len, self.liq_swing_len) or pd.Series(np.nan, index=low.index))
        
        # Range highs and lows for premium/discount zones
        self.range_high = self.I(lambda: high.rolling(self.pd_array_len).max())
        self.range_low = self.I(lambda: low.rolling(self.pd_array_len).min())
        self.range_eq = self.I(lambda: (high.rolling(self.pd_array_len).max() + low.rolling(self.pd_array_len).min()) / 2)
        
        # Volume calculations
        self.buy_volume = self.I(lambda: pd.Series(np.where(close > pd.Series(self.data.Open), volume, 0), index=close.index))
        self.sell_volume = self.I(lambda: pd.Series(np.where(close < pd.Series(self.data.Open), volume, 0), index=close.index))
        
        # Track order blocks
        self.bullish_obs = []
        self.bearish_obs = []
        self.last_bullish_ob_bar = -100
        self.last_bearish_ob_bar = -100
        
        # Track FVGs
        self.bullish_fvgs = []
        self.bearish_fvgs = []
        
        # Confluence score tracking
        self.in_position = False

    def next(self):
        if len(self.data) < self.ob_lookback + 5:
            return
        
        current_bar = len(self.data) - 1
        current_close = self.data.Close[-1]
        current_open = self.data.Open[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_volume = self.data.Volume[-1]
        
        prev_close = self.data.Close[-2] if len(self.data) > 1 else current_close
        prev_open = self.data.Open[-2] if len(self.data) > 1 else current_open
        prev_high = self.data.High[-2] if len(self.data) > 1 else current_high
        prev_low = self.data.Low[-2] if len(self.data) > 1 else current_low
        prev_volume = self.data.Volume[-2] if len(self.data) > 1 else current_volume
        
        if self.atr[-1] is None or self.avg_vol[-1] is None:
            return
        
        atr_val = self.atr[-1]
        avg_vol_val = self.avg_vol[-1]
        atr_sma_val = self.atr_sma50[-1]
        
        # Detect volume imbalance
        vol_imbalance = (current_volume > avg_vol_val * 1.5 and 
                        abs(current_close - current_open) > atr_val * 0.5)
        
        # Detect Bullish Order Block
        bullish_ob = (prev_close < prev_open and 
                     current_close > current_open and 
                     (current_high - current_low) > atr_val * self.ob_atr_mult and 
                     current_volume > avg_vol_val * self.ob_vol_mult)
        
        if bullish_ob:
            ob_top = prev_high
            ob_bottom = prev_low
            self.bullish_obs.append({
                'bar': current_bar,
                'top': ob_top,
                'bottom': ob_bottom,
                'mitigated': False
            })
            self.last_bullish_ob_bar = current_bar
        
        # Detect Bearish Order Block
        bearish_ob = (prev_close > prev_open and 
                     current_close < current_open and 
                     (current_high - current_low) > atr_val * self.ob_atr_mult and 
                     current_volume > avg_vol_val * self.ob_vol_mult)
        
        if bearish_ob:
            ob_top = prev_high
            ob_bottom = prev_low
            self.bearish_obs.append({
                'bar': current_bar,
                'top': ob_top,
                'bottom': ob_bottom,
                'mitigated': False
            })
            self.last_bearish_ob_bar = current_bar
        
        # Mitigate bullish order blocks (price breaks below)
        for ob in self.bullish_obs:
            if not ob['mitigated'] and current_close < ob['bottom']:
                ob['mitigated'] = True
        
        # Mitigate bearish order blocks (price breaks above)
        for ob in self.bearish_obs:
            if not ob['mitigated'] and current_close > ob['top']:
                ob['mitigated'] = True
        
        # Detect Bullish Fair Value Gap (gap between candle[2] high and current low)
        if len(self.data) > 2:
            high_2 = self.data.High[-3]
            if current_low > high_2:
                fvg_bull_size = (current_low - high_2) / high_2 * 100
                if fvg_bull_size >= self.fvg_min_size:
                    self.bullish_fvgs.append({
                        'bar': current_bar,
                        'top': current_low,
                        'bottom': high_2,
                        'filled': False
                    })
        
        # Detect Bearish Fair Value Gap (gap between candle[2] low and current high)
        if len(self.data) > 2:
            low_2 = self.data.Low[-3]
            if current_high < low_2:
                fvg_bear_size = (low_2 - current_high) / low_2 * 100
                if fvg_bear_size >= self.fvg_min_size:
                    self.bearish_fvgs.append({
                        'bar': current_bar,
                        'top': low_2,
                        'bottom': current_high,
                        'filled': False
                    })
        
        # Fill bullish FVGs
        for fvg in self.bullish_fvgs:
            if not fvg['filled'] and current_low <= fvg['bottom']:
                fvg['filled'] = True
        
        # Fill bearish FVGs
        for fvg in self.bearish_fvgs:
            if not fvg['filled'] and current_high >= fvg['top']:
                fvg['filled'] = True
        
        # Calculate confluence score
        confluence_score = 0
        
        # Order blocks scoring
        active_bullish_obs = sum(1 for ob in self.bullish_obs if not ob['mitigated'])
        active_bearish_obs = sum(1 for ob in self.bearish_obs if not ob['mitigated'])
        total_active_obs = active_bullish_obs + active_bearish_obs
        
        if total_active_obs > 3:
            confluence_score += 25
        elif total_active_obs > 1:
            confluence_score += 15
        else:
            confluence_score += 5
        
        # FVG scoring
        active_fvgs = sum(1 for fvg in self.bullish_fvgs + self.bearish_fvgs if not fvg['filled'])
        if active_fvgs > 5:
            confluence_score += 25
        elif active_fvgs > 2:
            confluence_score += 15
        else:
            confluence_score += 5
        
        # Premium/Discount zone scoring
        if self.range_eq[-1] is not None:
            in_premium = current_close > self.range_eq[-1] and current_close > (self.range_eq[-1] + (self.range_high[-1] - self.range_eq[-1]) * 0.5)
            in_discount = current_close < self.range_eq[-1] and current_close < (self.range_eq[-1] - (self.range_eq[-1] - self.range_low[-1]) * 0.5)
            if in_premium or in_discount:
                confluence_score += 15
            else:
                confluence_score += 5
        else:
            confluence_score += 5
        
        # Volatility scoring
        if atr_sma_val is not None and atr_sma_val > 0:
            vol_ratio = atr_val / atr_sma_val
            if vol_ratio > 1.3:
                confluence_score += 15
            elif vol_ratio < 0.8:
                confluence_score += 10
            else:
                confluence_score += 5
        else:
            confluence_score += 5
        
        # Entry logic based on confluence and order blocks
        if not self.position:
            # Bullish signal: recent bullish OB, price in discount, confluence strong
            bullish_signal = (
                active_bullish_obs > 0 and 
                current_bar - self.last_bullish_ob_bar < 20 and
                confluence_score >= 50 and
                vol_imbalance
            )
            
            if bullish_signal:
                self.buy()
                self.in_position = True
            
            # Bearish signal: recent bearish OB, price in premium, confluence strong
            bearish_signal = (
                active_bearish_obs > 0 and 
                current_bar - self.last_bearish_ob_bar < 20 and
                confluence_score >= 50 and
                vol_imbalance
            )
            
            if bearish_signal:
                self.sell()
                self.in_position = True
        
        else:
            # Exit logic
            # Exit if order blocks are mitigated
            if self.position.is_long:
                # Check if any active bullish OB was mitigated
                if all(ob['mitigated'] for ob in self.bullish_obs if ob['bar'] > current_bar - 30):
                    self.position.close()
                    self.in_position = False
            
            elif self.position.is_short:
                # Check if any active bearish OB was mitigated
                if all(ob['mitigated'] for ob in self.bearish_obs if ob['bar'] > current_bar - 30):
                    self.position.close()
                    self.in_position = False
            
            # Stop loss based on recent order block range
            if self.position.is_long and self.bullish_obs:
                recent_obs = [ob for ob in self.bullish_obs if ob['bar'] > current_bar - 50 and not ob['mitigated']]
                if recent_obs:
                    stop_price = min(ob['bottom'] for ob in recent_obs)
                    if current_close < stop_price:
                        self.position.close()
                        self.in_position = False
            
            elif self.position.is_short and self.bearish_obs:
                recent_obs = [ob for ob in self.bearish_obs if ob['bar'] > current_bar - 50 and not ob['mitigated']]
                if recent_obs:
                    stop_price = max(ob['top'] for ob in recent_obs)
                    if current_close > stop_price:
                        self.position.close()
                        self.in_position = False
        
        # Cleanup old order blocks
        self.bullish_obs = [ob for ob in self.bullish_obs if current_bar - ob['bar'] < 100]
        self.bearish_obs = [ob for ob in self.bearish_obs if current_bar - ob['bar'] < 100]
        self.bullish_fvgs = [fvg for fvg in self.bullish_fvgs if current_bar - fvg['bar'] < 100]
        self.bearish_fvgs = [fvg for fvg in self.bearish_fvgs if current_bar - fvg['bar'] < 100]


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()