"""
DS-TV Backtest Results: perky-smc-ultimate-v3
============================================================

--- SPY ---
  Return                    16.13%
  Buy & Hold Return         17.90%
  Max Drawdown              -18.71%
  Sharpe Ratio              0.51
  Sortino Ratio             0.82
  Calmar Ratio              0.42
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              116134.35$
  Equity Peak               116391.53$
  Avg Drawdown              -2.06%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               7.83%
  Ann. Volatility           15.48%

--- BTC ---
  Return                    10.67%
  Buy & Hold Return         17.39%
  Max Drawdown              -37.48%
  Sharpe Ratio              0.18
  Sortino Ratio             0.28
  Calmar Ratio              0.14
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              110673.46$
  Equity Peak               165575.93$
  Avg Drawdown              -5.15%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               5.19%
  Ann. Volatility           28.63%

--- QQQ ---
  Return                    -22.23%
  Buy & Hold Return         22.08%
  Max Drawdown              -37.19%
  Sharpe Ratio              -0.73
  Sortino Ratio             -0.94
  Calmar Ratio              -0.32
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              77773.33$
  Equity Peak               117322.28$
  Avg Drawdown              -6.68%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               -11.90%
  Ann. Volatility           16.38%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — perky-smc-ultimate-v3
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # SMC Parameters
    swings_length = 50
    internal_swings_length = 5
    equal_highs_lows_length = 3
    equal_threshold = 0.1
    
    # Sweep Parameters
    sweep_len = 5
    
    # Entry/Exit Parameters
    tp1_mult = 0.5
    tp2_mult = 1.0
    tp3_mult = 2.0
    sl_mult = 0.5
    
    # Filters
    require_fvg = False
    require_ob = False
    require_choch = False
    require_smc_bias = False
    show_sweep_entries = True
    
    def init(self):
        # Calculate ATR for position sizing and sweeps
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        close = pd.Series(self.data.Close)
        
        self.atr = self.I(pta.atr, high, low, close, length=200)
        
        # Track swing pivots manually
        self.swing_high_pivot = None
        self.swing_low_pivot = None
        self.internal_high_pivot = None
        self.internal_low_pivot = None
        
        # Track structure trend
        self.swing_trend_bias = 0  # 1 = bullish, -1 = bearish
        self.internal_trend_bias = 0
        
        # Track last CHoCH for entries
        self.last_bull_choch = False
        self.last_bear_choch = False
        
        # Sweep tracking
        self.last_green_sweep = False
        self.last_red_sweep = False
        self.sweep_prices = {'green': [], 'red': []}
        
        # Position tracking
        self.in_long = False
        self.in_short = False
        self.entry_price = None
        self.entry_atr = None
        
    def next(self):
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        if len(self.data) < self.swings_length + 5:
            return
        
        atr_val = self.atr[-1]
        if atr_val is None or np.isnan(atr_val):
            return
        
        # Update swing structure
        self._update_swing_structure()
        self._update_internal_structure()
        self._detect_sweeps()
        
        # Generate entry signals
        bull_choch = self.last_bull_choch and self.swing_trend_bias == 1
        bear_choch = self.last_bear_choch and self.swing_trend_bias == -1
        
        # Sweep-based entries
        sweep_long = self.show_sweep_entries and self.last_green_sweep
        sweep_short = self.show_sweep_entries and self.last_red_sweep
        
        # Entry logic
        if sweep_long and not self.in_long and not self.in_short:
            self.entry_price = close
            self.entry_atr = atr_val
            self.in_long = True
            self.buy()
        
        elif sweep_short and not self.in_short and not self.in_long:
            self.entry_price = close
            self.entry_atr = atr_val
            self.in_short = True
            self.sell()
        
        # Exit logic based on structure breaks
        if self.in_long and self.swing_trend_bias == -1:
            self.in_long = False
            self.sell()
        
        elif self.in_short and self.swing_trend_bias == 1:
            self.in_short = False
            self.buy()
        
        # Reset sweep signals
        self.last_green_sweep = False
        self.last_red_sweep = False
    
    def _update_swing_structure(self):
        """Track swing highs and lows using pivot detection"""
        length = self.swings_length
        
        if len(self.data) < length + 1:
            return
        
        # Get highest high and lowest low
        highest = max(self.data.High[-length:])
        lowest = min(self.data.Low[-length:])
        
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        close = self.data.Close[-1]
        
        # Detect new swing high
        if current_high > highest:
            old_bias = self.swing_trend_bias
            self.swing_trend_bias = -1  # Bearish after high
            
            if old_bias == 1:
                self.last_bull_choch = True
            self.swing_high_pivot = current_high
        
        # Detect new swing low
        if current_low < lowest:
            old_bias = self.swing_trend_bias
            self.swing_trend_bias = 1  # Bullish after low
            
            if old_bias == -1:
                self.last_bear_choch = True
            self.swing_low_pivot = current_low
    
    def _update_internal_structure(self):
        """Track internal structure (5-bar swings)"""
        length = self.internal_swings_length
        
        if len(self.data) < length + 1:
            return
        
        highest = max(self.data.High[-length:])
        lowest = min(self.data.Low[-length:])
        
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        if current_high > highest:
            self.internal_trend_bias = -1
            self.internal_high_pivot = current_high
        
        if current_low < lowest:
            self.internal_trend_bias = 1
            self.internal_low_pivot = current_low
    
    def _detect_sweeps(self):
        """Detect liquidity sweeps based on pivot wicks and closes"""
        length = self.sweep_len
        
        if len(self.data) < length + 2:
            return
        
        # Get pivot high and low
        high_vals = list(self.data.High[-length*2:])
        low_vals = list(self.data.Low[-length*2:])
        close_vals = list(self.data.Close[-length*2:])
        
        if len(high_vals) < length:
            return
        
        # Simplified pivot detection
        mid = len(high_vals) // 2
        pivot_high = max(high_vals[mid-length//2:mid+length//2])
        pivot_low = min(low_vals[mid-length//2:mid+length//2])
        
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_close = self.data.Close[-1]
        
        # Green sweep: wick below pivot low, close above
        if current_low < pivot_low and current_close > pivot_low:
            self.last_green_sweep = True
            self.sweep_prices['green'].append(current_low)
        
        # Red sweep: wick above pivot high, close below
        if current_high > pivot_high and current_close < pivot_high:
            self.last_red_sweep = True
            self.sweep_prices['red'].append(current_high)