"""
DS-TV Backtest Results: pressure-zone-analyzer-joat
============================================================

--- SPY ---
  Return                    -59.62%
  Buy & Hold Return         40.20%
  Max Drawdown              -62.69%
  Sharpe Ratio              -3.84
  Sortino Ratio             -3.14
  Calmar Ratio              -0.59
  Profit Factor             0.41
  Expectancy                -0.27%
  SQN                       -5.53
  # Trades                  331
  Win Rate                  31.12%
  Best Trade                3.48%
  Worst Trade               -3.44%
  Avg Trade                 -0.27%
  Exposure Time             77.40%
  Equity Final              40380.28$
  Equity Peak               108220.67$
  Avg Drawdown              -21.28%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        27 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -36.68%
  Ann. Volatility           9.56%

--- BTC ---
  Return                    -26.27%
  Buy & Hold Return         0.29%
  Max Drawdown              -32.48%
  Sharpe Ratio              -0.96
  Sortino Ratio             -1.04
  Calmar Ratio              -0.43
  Profit Factor             0.59
  Expectancy                -0.39%
  SQN                       -1.87
  # Trades                  100
  Win Rate                  41.00%
  Best Trade                3.89%
  Worst Trade               -9.26%
  Avg Trade                 -0.41%
  Exposure Time             29.00%
  Equity Final              73732.45$
  Equity Peak               109193.74$
  Avg Drawdown              -12.69%
  Max Drawdown Duration     650 days 00:00:00
  Max Trade Duration        33 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -14.11%
  Ann. Volatility           14.69%

--- QQQ ---
  Return                    -59.20%
  Buy & Hold Return         45.93%
  Max Drawdown              -63.43%
  Sharpe Ratio              -3.08
  Sortino Ratio             -2.61
  Calmar Ratio              -0.57
  Profit Factor             0.49
  Expectancy                -0.29%
  SQN                       -4.72
  # Trades                  306
  Win Rate                  33.33%
  Best Trade                4.67%
  Worst Trade               -4.66%
  Avg Trade                 -0.29%
  Exposure Time             77.40%
  Equity Final              40801.90$
  Equity Peak               109448.38$
  Avg Drawdown              -13.68%
  Max Drawdown Duration     551 days 00:00:00
  Max Trade Duration        35 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -36.35%
  Ann. Volatility           11.81%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — pressure-zone-analyzer-joat
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    zone_length = 50
    pivot_length = 10
    max_zones = 8
    zone_thickness_percent = 0.5
    volume_weight = 0.4
    touch_weight = 0.3
    age_weight = 0.3

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate highest and lowest for fibonacci
        self.swing_high = self.I(lambda: high.rolling(self.zone_length).max())
        self.swing_low = self.I(lambda: low.rolling(self.zone_length).min())
        
        # Calculate SMA for volume scoring
        self.avg_volume = self.I(pta.sma, volume, length=50)
        
        # Track pivot highs and lows
        self.pivot_high_vals = self.I(lambda: self._calc_pivot_high(high))
        self.pivot_low_vals = self.I(lambda: self._calc_pivot_low(low))
        
        # Pressure zones tracking
        self.resistance_zones = []
        self.support_zones = []
        
    def _calc_pivot_high(self, high_series):
        result = pd.Series(np.nan, index=high_series.index)
        for i in range(self.pivot_length, len(high_series) - self.pivot_length):
            if high_series.iloc[i] == high_series.iloc[i-self.pivot_length:i+self.pivot_length+1].max():
                result.iloc[i] = high_series.iloc[i]
        return result
    
    def _calc_pivot_low(self, low_series):
        result = pd.Series(np.nan, index=low_series.index)
        for i in range(self.pivot_length, len(low_series) - self.pivot_length):
            if low_series.iloc[i] == low_series.iloc[i-self.pivot_length:i+self.pivot_length+1].min():
                result.iloc[i] = low_series.iloc[i]
        return result
    
    def _calc_zone_thickness(self, price):
        return price * (self.zone_thickness_percent / 100.0)
    
    def _in_zone(self, price, zone_price, thickness):
        return abs(price - zone_price) <= thickness
    
    def _calc_zone_strength(self, touches, vol_at_zone, age, avg_vol):
        if avg_vol > 0:
            vol_score = min(vol_at_zone / avg_vol, 3.0) / 3.0
        else:
            vol_score = 0.5
        
        touch_score = min(touches / 5.0, 1.0)
        age_score = max(1.0 - (age / 500.0), 0.0)
        
        strength = (vol_score * self.volume_weight) + (touch_score * self.touch_weight) + (age_score * self.age_weight)
        return strength
    
    def _calc_fib_levels(self, high_val, low_val):
        price_range = high_val - low_val
        fib236 = low_val + (price_range * 0.236)
        fib382 = low_val + (price_range * 0.382)
        fib500 = low_val + (price_range * 0.500)
        fib618 = low_val + (price_range * 0.618)
        fib786 = low_val + (price_range * 0.786)
        return fib236, fib382, fib500, fib618, fib786
    
    def _calc_golden_zone(self, high_val, low_val):
        price_range = high_val - low_val
        golden_top = low_val + (price_range * 0.618)
        golden_bottom = low_val + (price_range * 0.500)
        return golden_top, golden_bottom

    def next(self):
        if len(self.data) < self.zone_length + self.pivot_length:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        
        swing_high = self.swing_high[-1]
        swing_low = self.swing_low[-1]
        avg_vol = self.avg_volume[-1]
        
        if pd.isna(swing_high) or pd.isna(swing_low) or pd.isna(avg_vol):
            return
        
        # Calculate fibonacci levels
        fib236, fib382, fib500, fib618, fib786 = self._calc_fib_levels(swing_high, swing_low)
        
        # Calculate golden zone
        golden_top, golden_bottom = self._calc_golden_zone(swing_high, swing_low)
        
        # Zone thickness
        thickness = self._calc_zone_thickness(close)
        
        # Check for new pivot high
        if not pd.isna(self.pivot_high_vals[-1]):
            pivot_price = self.pivot_high_vals[-1]
            self.resistance_zones.append({
                'price': pivot_price,
                'start_bar': len(self.data) - self.pivot_length,
                'touches': 1,
                'volume_at_zone': volume,
                'type': 'resistance'
            })
            if len(self.resistance_zones) > self.max_zones:
                self.resistance_zones.pop(0)
        
        # Check for new pivot low
        if not pd.isna(self.pivot_low_vals[-1]):
            pivot_price = self.pivot_low_vals[-1]
            self.support_zones.append({
                'price': pivot_price,
                'start_bar': len(self.data) - self.pivot_length,
                'touches': 1,
                'volume_at_zone': volume,
                'type': 'support'
            })
            if len(self.support_zones) > self.max_zones:
                self.support_zones.pop(0)
        
        # Update resistance zone touches and strength
        for zone in self.resistance_zones:
            if self._in_zone(high, zone['price'], thickness):
                zone['touches'] += 1
                zone['volume_at_zone'] = max(zone['volume_at_zone'], volume)
            
            age = len(self.data) - zone['start_bar']
            zone['strength'] = self._calc_zone_strength(zone['touches'], zone['volume_at_zone'], age, avg_vol)
        
        # Update support zone touches and strength
        for zone in self.support_zones:
            if self._in_zone(low, zone['price'], thickness):
                zone['touches'] += 1
                zone['volume_at_zone'] = max(zone['volume_at_zone'], volume)
            
            age = len(self.data) - zone['start_bar']
            zone['strength'] = self._calc_zone_strength(zone['touches'], zone['volume_at_zone'], age, avg_vol)
        
        # Trading logic based on pressure zones and golden zone
        in_golden_zone = close >= golden_bottom and close <= golden_top
        
        # Check proximity to resistance
        near_resistance = False
        for zone in self.resistance_zones:
            if zone['strength'] > 0.6 and self._in_zone(close, zone['price'], thickness * 2):
                near_resistance = True
                break
        
        # Check proximity to support
        near_support = False
        for zone in self.support_zones:
            if zone['strength'] > 0.6 and self._in_zone(close, zone['price'], thickness * 2):
                near_support = True
                break
        
        # Entry logic: Buy when price is in golden zone or near support with strength
        if in_golden_zone and not self.position:
            self.buy()
        elif near_support and not self.position:
            strongest_support = max(self.support_zones, key=lambda z: z['strength']) if self.support_zones else None
            if strongest_support and strongest_support['strength'] > 0.6:
                self.buy()
        
        # Exit logic: Sell when near resistance or leaving golden zone
        if self.position:
            if near_resistance:
                strongest_resistance = max(self.resistance_zones, key=lambda z: z['strength']) if self.resistance_zones else None
                if strongest_resistance and strongest_resistance['strength'] > 0.6:
                    self.sell()
            elif not in_golden_zone and close > golden_top:
                self.sell()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()