"""
DS-TV Backtest Results: renko-flip-alert-traditional-only
============================================================

--- SPY ---
  Return                    -48.19%
  Buy & Hold Return         41.94%
  Max Drawdown              -48.42%
  Sharpe Ratio              -2.37
  Sortino Ratio             -2.24
  Calmar Ratio              -0.58
  Profit Factor             0.46
  Expectancy                -0.49%
  SQN                       -3.09
  # Trades                  128
  Win Rate                  29.69%
  Best Trade                7.48%
  Worst Trade               -6.20%
  Avg Trade                 -0.51%
  Exposure Time             98.80%
  Equity Final              51809.17$
  Equity Peak               100444.26$
  Avg Drawdown              -48.42%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        14 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               -28.21%
  Ann. Volatility           11.93%

--- BTC ---
  Return                    -28.95%
  Buy & Hold Return         46.22%
  Max Drawdown              -30.33%
  Sharpe Ratio              -0.62
  Sortino Ratio             -0.74
  Calmar Ratio              -0.52
  Profit Factor             0.72
  Expectancy                -0.64%
  SQN                       -0.86
  # Trades                  80
  Win Rate                  41.25%
  Best Trade                26.55%
  Worst Trade               -18.18%
  Avg Trade                 -0.80%
  Exposure Time             39.53%
  Equity Final              71047.05$
  Equity Peak               100392.78$
  Avg Drawdown              -15.83%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        9 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -15.69%
  Ann. Volatility           25.49%

--- QQQ ---
  Return                    -50.69%
  Buy & Hold Return         42.67%
  Max Drawdown              -52.23%
  Sharpe Ratio              -2.02
  Sortino Ratio             -1.91
  Calmar Ratio              -0.57
  Profit Factor             0.55
  Expectancy                -0.53%
  SQN                       -2.52
  # Trades                  128
  Win Rate                  33.59%
  Best Trade                8.99%
  Worst Trade               -7.20%
  Avg Trade                 -0.55%
  Exposure Time             99.00%
  Equity Final              49313.82$
  Equity Peak               100652.38$
  Avg Drawdown              -52.23%
  Max Drawdown Duration     725 days 00:00:00
  Max Trade Duration        14 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               -29.97%
  Ann. Volatility           14.87%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — renko-flip-alert-traditional-only
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        # Current bar direction
        is_bull = self.data.Close[-1] > self.data.Open[-1]
        is_bear = self.data.Close[-1] < self.data.Open[-1]
        
        # Previous bar direction
        if len(self.data) >= 2:
            was_bull = self.data.Close[-2] > self.data.Open[-2]
            was_bear = self.data.Close[-2] < self.data.Open[-2]
            
            # Flip conditions
            bull_flip = is_bull and was_bear
            bear_flip = is_bear and was_bull
            
            # Trading logic
            if bull_flip and not self.position:
                self.buy()
            elif bear_flip and self.position:
                self.sell()