"""
DS-TV Backtest Results: signal-goat-hh-hl-lh-ll-extension-lines
============================================================

--- SPY ---
  Return                    -44.67%
  Buy & Hold Return         43.17%
  Max Drawdown              -46.23%
  Sharpe Ratio              -2.07
  Sortino Ratio             -2.02
  Calmar Ratio              -0.56
  Profit Factor             0.55
  Expectancy                -0.42%
  SQN                       -1.96
  # Trades                  114
  Win Rate                  42.11%
  Best Trade                6.39%
  Worst Trade               -17.92%
  Avg Trade                 -0.46%
  Exposure Time             80.20%
  Equity Final              55326.70$
  Equity Peak               102838.09$
  Avg Drawdown              -23.54%
  Max Drawdown Duration     573 days 00:00:00
  Max Trade Duration        185 days 00:00:00
  Avg Trade Duration        6 days 00:00:00
  Ann. Return               -25.79%
  Ann. Volatility           12.48%

--- BTC ---
  Return                    -42.79%
  Buy & Hold Return         37.68%
  Max Drawdown              -56.61%
  Sharpe Ratio              -1.08
  Sortino Ratio             -1.11
  Calmar Ratio              -0.43
  Profit Factor             0.64
  Expectancy                -0.51%
  SQN                       -1.11
  # Trades                  145
  Win Rate                  48.28%
  Best Trade                6.90%
  Worst Trade               -52.53%
  Avg Trade                 -0.70%
  Exposure Time             38.58%
  Equity Final              57211.78$
  Equity Peak               108016.95$
  Avg Drawdown              -11.24%
  Max Drawdown Duration     650 days 00:00:00
  Max Trade Duration        74 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -24.33%
  Ann. Volatility           22.52%

--- QQQ ---
  Return                    -53.78%
  Buy & Hold Return         41.48%
  Max Drawdown              -56.89%
  Sharpe Ratio              -2.08
  Sortino Ratio             -1.93
  Calmar Ratio              -0.57
  Profit Factor             0.61
  Expectancy                -0.37%
  SQN                       -2.09
  # Trades                  166
  Win Rate                  40.36%
  Best Trade                6.54%
  Worst Trade               -23.55%
  Avg Trade                 -0.41%
  Exposure Time             92.60%
  Equity Final              46217.16$
  Equity Peak               105177.44$
  Avg Drawdown              -14.86%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        213 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -32.23%
  Ann. Volatility           15.49%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — signal-goat-hh-hl-lh-ll-extension-lines
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    pivot_len = 5
    extend_bars = 50

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate pivot highs and lows
        self.pivot_high = self.I(self._calculate_pivot_high, high, self.pivot_len)
        self.pivot_low = self.I(self._calculate_pivot_low, low, self.pivot_len)
        
        # Track previous pivots for structure detection
        self.prev_high = None
        self.prev_low = None
        self.last_hh_price = None
        self.last_lh_price = None
        self.last_hl_price = None
        self.last_ll_price = None

    def _calculate_pivot_high(self, high, pivot_len):
        result = pd.Series(np.nan, index=high.index)
        for i in range(pivot_len, len(high) - pivot_len):
            window = high.iloc[i - pivot_len:i + pivot_len + 1]
            if high.iloc[i] == window.max() and i >= pivot_len * 2:
                result.iloc[i] = high.iloc[i]
        return result

    def _calculate_pivot_low(self, low, pivot_len):
        result = pd.Series(np.nan, index=low.index)
        for i in range(pivot_len, len(low) - pivot_len):
            window = low.iloc[i - pivot_len:i + pivot_len + 1]
            if low.iloc[i] == window.min() and i >= pivot_len * 2:
                result.iloc[i] = low.iloc[i]
        return result

    def next(self):
        current_ph = self.pivot_high[-1]
        current_pl = self.pivot_low[-1]
        
        # High structure: HH / LH detection
        if not np.isnan(current_ph):
            if self.prev_high is not None:
                is_hh = current_ph > self.prev_high
                is_lh = current_ph < self.prev_high
                
                if is_hh:
                    self.last_hh_price = current_ph
                elif is_lh:
                    self.last_lh_price = current_ph
            
            self.prev_high = current_ph
        
        # Low structure: HL / LL detection
        if not np.isnan(current_pl):
            if self.prev_low is not None:
                is_hl = current_pl > self.prev_low
                is_ll = current_pl < self.prev_low
                
                if is_hl:
                    self.last_hl_price = current_pl
                elif is_ll:
                    self.last_ll_price = current_pl
            
            self.prev_low = current_pl
        
        # Trading logic based on structure
        if self.last_hh_price is not None and self.data.Close[-1] > self.last_hh_price:
            if not self.position:
                self.buy()
        
        if self.last_ll_price is not None and self.data.Close[-1] < self.last_ll_price:
            if self.position:
                self.sell()
        
        if self.last_lh_price is not None and self.data.Close[-1] < self.last_lh_price:
            if self.position:
                self.sell()
        
        if self.last_hl_price is not None and self.data.Close[-1] > self.last_hl_price:
            if not self.position:
                self.buy()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()