"""
DS-TV Backtest Results: smart-money-auto-order-blocks-identityka
============================================================

--- SPY ---
  Return                    114.85%
  Buy & Hold Return         43.17%
  Max Drawdown              -7.59%
  Sharpe Ratio              2.01
  Sortino Ratio             5.01
  Calmar Ratio              6.20
  Profit Factor             17.26
  Expectancy                2.54%
  SQN                       4.37
  # Trades                  31
  Win Rate                  93.55%
  Best Trade                13.44%
  Worst Trade               -4.79%
  Avg Trade                 2.50%
  Exposure Time             75.00%
  Equity Final              214851.99$
  Equity Peak               219865.31$
  Avg Drawdown              -1.30%
  Max Drawdown Duration     92 days 00:00:00
  Max Trade Duration        53 days 00:00:00
  Avg Trade Duration        18 days 00:00:00
  Ann. Return               47.03%
  Ann. Volatility           23.39%

--- BTC ---
  Return                    1952.97%
  Buy & Hold Return         37.68%
  Max Drawdown              -32.93%
  Sharpe Ratio              1.86
  Sortino Ratio             15.71
  Calmar Ratio              10.69
  Profit Factor             9.11
  Expectancy                7.30%
  SQN                       3.65
  # Trades                  47
  Win Rate                  87.23%
  Best Trade                33.34%
  Worst Trade               -21.61%
  Avg Trade                 6.96%
  Exposure Time             89.60%
  Equity Final              2052974.67$
  Equity Peak               2181637.90$
  Avg Drawdown              -3.17%
  Max Drawdown Duration     152 days 00:00:00
  Max Trade Duration        51 days 00:00:00
  Avg Trade Duration        14 days 00:00:00
  Ann. Return               352.16%
  Ann. Volatility           189.26%

--- QQQ ---
  Return                    328.92%
  Buy & Hold Return         41.48%
  Max Drawdown              -7.83%
  Sharpe Ratio              2.59
  Sortino Ratio             10.42
  Calmar Ratio              13.83
  Profit Factor             27.44
  Expectancy                4.83%
  SQN                       4.82
  # Trades                  31
  Win Rate                  93.55%
  Best Trade                20.99%
  Worst Trade               -5.59%
  Avg Trade                 4.73%
  Exposure Time             90.60%
  Equity Final              428916.30$
  Equity Peak               440293.10$
  Avg Drawdown              -1.40%
  Max Drawdown Duration     63 days 00:00:00
  Max Trade Duration        65 days 00:00:00
  Avg Trade Duration        22 days 00:00:00
  Ann. Return               108.31%
  Ann. Volatility           41.81%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — smart-money-auto-order-blocks-identityka
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    prd = 5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        
        # Detect pivot highs and lows
        self.pivot_high = self.I(self._detect_pivot_high, high, self.prd)
        self.pivot_low = self.I(self._detect_pivot_low, low, self.prd)
        
        # Track order block levels
        self.bearish_ob_top = None
        self.bearish_ob_bot = None
        self.bullish_ob_top = None
        self.bullish_ob_bot = None
        
        self.last_pivot_high_bar = -100
        self.last_pivot_low_bar = -100
        self.in_bearish_ob = False
        self.in_bullish_ob = False

    def _detect_pivot_high(self, high_series, period):
        result = pd.Series(index=high_series.index, dtype=float)
        for i in range(len(high_series)):
            if i < period or i >= len(high_series) - period:
                result.iloc[i] = np.nan
            else:
                is_pivot = True
                for j in range(1, period + 1):
                    if high_series.iloc[i] <= high_series.iloc[i - j] or high_series.iloc[i] <= high_series.iloc[i + j]:
                        is_pivot = False
                        break
                result.iloc[i] = high_series.iloc[i] if is_pivot else np.nan
        return result

    def _detect_pivot_low(self, low_series, period):
        result = pd.Series(index=low_series.index, dtype=float)
        for i in range(len(low_series)):
            if i < period or i >= len(low_series) - period:
                result.iloc[i] = np.nan
            else:
                is_pivot = True
                for j in range(1, period + 1):
                    if low_series.iloc[i] >= low_series.iloc[i - j] or low_series.iloc[i] >= low_series.iloc[i + j]:
                        is_pivot = False
                        break
                result.iloc[i] = low_series.iloc[i] if is_pivot else np.nan
        return result

    def next(self):
        current_idx = len(self.data) - 1
        
        # Check for new pivot high (Bearish OB)
        if not np.isnan(self.pivot_high[-1]):
            lookback_idx = current_idx - self.prd
            if 0 <= lookback_idx < len(self.data):
                top = self.data.High[lookback_idx]
                bot = max(self.data.Open[lookback_idx], self.data.Close[lookback_idx])
                self.bearish_ob_top = top
                self.bearish_ob_bot = bot
                self.last_pivot_high_bar = current_idx
                self.in_bearish_ob = True
                self.in_bullish_ob = False
        
        # Check for new pivot low (Bullish OB)
        if not np.isnan(self.pivot_low[-1]):
            lookback_idx = current_idx - self.prd
            if 0 <= lookback_idx < len(self.data):
                top = min(self.data.Open[lookback_idx], self.data.Close[lookback_idx])
                bot = self.data.Low[lookback_idx]
                self.bullish_ob_top = top
                self.bullish_ob_bot = bot
                self.last_pivot_low_bar = current_idx
                self.in_bullish_ob = True
                self.in_bearish_ob = False
        
        current_price = self.data.Close[-1]
        
        # Trading Logic: Enter long when price touches bullish OB (support)
        if self.in_bullish_ob and self.bullish_ob_bot is not None and self.bullish_ob_top is not None:
            if current_price <= self.bullish_ob_top and current_price >= self.bullish_ob_bot:
                if not self.position:
                    self.buy()
        
        # Trading Logic: Enter short when price touches bearish OB (resistance)
        if self.in_bearish_ob and self.bearish_ob_top is not None and self.bearish_ob_bot is not None:
            if current_price >= self.bearish_ob_bot and current_price <= self.bearish_ob_top:
                if not self.position:
                    self.position.close() if self.position else None
        
        # Exit long if price breaks above bearish OB
        if self.position and self.position.is_long:
            if self.in_bearish_ob and self.bearish_ob_top is not None:
                if current_price > self.bearish_ob_top:
                    self.sell()
        
        # Exit short if price breaks below bullish OB
        if self.position and not self.position.is_long:
            if self.in_bullish_ob and self.bullish_ob_bot is not None:
                if current_price < self.bullish_ob_bot:
                    self.buy()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("EURUSD=X", start="2023-01-01", end="2024-01-01", progress=False)
    
    bt = Backtest(data, TvStrategy, commission=.0002, exclusive_orders=True)
    stats = bt.run()
    print(stats)
    bt.plot()