"""
DS-TV Backtest Results: structural-flow-decoder-joat
============================================================

--- SPY ---
  Return                    0.66%
  Buy & Hold Return         43.17%
  Max Drawdown              -9.45%
  Sharpe Ratio              0.03
  Sortino Ratio             0.04
  Calmar Ratio              0.04
  Profit Factor             1.10
  Expectancy                0.13%
  SQN                       0.07
  # Trades                  9
  Win Rate                  55.56%
  Best Trade                6.87%
  Worst Trade               -4.59%
  Avg Trade                 0.08%
  Exposure Time             42.00%
  Equity Final              100657.67$
  Equity Peak               104116.18$
  Avg Drawdown              -2.68%
  Max Drawdown Duration     164 days 00:00:00
  Max Trade Duration        69 days 00:00:00
  Avg Trade Duration        33 days 00:00:00
  Ann. Return               0.33%
  Ann. Volatility           11.19%

--- BTC ---
  Return                    13.47%
  Buy & Hold Return         -2.17%
  Max Drawdown              -22.90%
  Sharpe Ratio              0.29
  Sortino Ratio             0.47
  Calmar Ratio              0.28
  Profit Factor             1.63
  Expectancy                1.62%
  SQN                       0.38
  # Trades                  15
  Win Rate                  40.00%
  Best Trade                46.01%
  Worst Trade               -9.19%
  Avg Trade                 0.97%
  Exposure Time             34.88%
  Equity Final              113472.21$
  Equity Peak               132381.40$
  Avg Drawdown              -5.22%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        57 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               6.51%
  Ann. Volatility           22.77%

--- QQQ ---
  Return                    -11.72%
  Buy & Hold Return         39.41%
  Max Drawdown              -19.13%
  Sharpe Ratio              -0.49
  Sortino Ratio             -0.56
  Calmar Ratio              -0.32
  Profit Factor             0.41
  Expectancy                -1.00%
  SQN                       -1.24
  # Trades                  12
  Win Rate                  33.33%
  Best Trade                2.65%
  Worst Trade               -6.79%
  Avg Trade                 -1.04%
  Exposure Time             35.40%
  Equity Final              88278.73$
  Equity Peak               109160.81$
  Avg Drawdown              -4.84%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        46 days 00:00:00
  Avg Trade Duration        20 days 00:00:00
  Ann. Return               -6.09%
  Ann. Volatility           12.37%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — structural-flow-decoder-joat
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    swingLength = 5
    internalSwingLen = 3
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate RSI for momentum detection
        self.rsi = self.I(pta.rsi, close, length=14)
        
        # Calculate MACD for momentum confirmation
        macd_result = self.I(lambda: pta.macd(close, fast=12, slow=26, signal=9))
        self.macd_hist = self.I(lambda: self._extract_macd_hist(close))
        
        # Calculate ATR for volatility
        self.atr = self.I(pta.atr, high, low, close, length=14)
        
        # Calculate pivot highs and lows using rolling windows
        self.pivot_high = self.I(lambda: self._calc_pivot_high(high, self.swingLength))
        self.pivot_low = self.I(lambda: self._calc_pivot_low(low, self.swingLength))
        
        # Track structure state
        self.bullish_structure = True
        self.last_swing_high = None
        self.last_swing_low = None
        self.structure_strength = 0
        
    def _extract_macd_hist(self, close):
        result = pta.macd(close, fast=12, slow=26, signal=9)
        if result is not None and len(result) > 0:
            # MACD returns a dataframe with MACD_12_26_9, MACDh_12_26_9, MACDs_12_26_9
            if 'MACDh_12_26_9' in result.columns:
                return result['MACDh_12_26_9']
            elif len(result.columns) > 2:
                return result.iloc[:, 2]
        return pd.Series(0, index=close.index)
    
    def _calc_pivot_high(self, high, period):
        result = pd.Series(index=high.index, dtype=float)
        for i in range(len(high)):
            if i < period or i >= len(high) - period:
                result.iloc[i] = np.nan
            else:
                window = high.iloc[i-period:i+period+1]
                mid_val = high.iloc[i]
                if mid_val == window.max():
                    result.iloc[i] = mid_val
                else:
                    result.iloc[i] = np.nan
        return result
    
    def _calc_pivot_low(self, low, period):
        result = pd.Series(index=low.index, dtype=float)
        for i in range(len(low)):
            if i < period or i >= len(low) - period:
                result.iloc[i] = np.nan
            else:
                window = low.iloc[i-period:i+period+1]
                mid_val = low.iloc[i]
                if mid_val == window.min():
                    result.iloc[i] = mid_val
                else:
                    result.iloc[i] = np.nan
        return result
    
    def next(self):
        # Get current values
        rsi_val = self.rsi[-1] if len(self.rsi) > 0 and not np.isnan(self.rsi[-1]) else 50
        macd_hist_val = self.macd_hist[-1] if len(self.macd_hist) > 0 and not np.isnan(self.macd_hist[-1]) else 0
        pivot_high_val = self.pivot_high[-1] if len(self.pivot_high) > 0 else np.nan
        pivot_low_val = self.pivot_low[-1] if len(self.pivot_low) > 0 else np.nan
        
        # Update swing highs
        if not np.isnan(pivot_high_val):
            if self.last_swing_high is not None:
                if pivot_high_val > self.last_swing_high:
                    # Higher high - bullish structure
                    if self.bullish_structure:
                        # BOS Bullish
                        self.structure_strength += 1
                    else:
                        # CHoCH to bullish
                        self.bullish_structure = True
                        self.structure_strength = 1
                else:
                    # Lower high - bearish structure
                    if not self.bullish_structure:
                        self.structure_strength += 1
            
            self.last_swing_high = pivot_high_val
        
        # Update swing lows
        if not np.isnan(pivot_low_val):
            if self.last_swing_low is not None:
                if pivot_low_val > self.last_swing_low:
                    # Higher low - bullish structure
                    if self.bullish_structure:
                        self.structure_strength += 1
                else:
                    # Lower low - bearish structure
                    if not self.bullish_structure:
                        # BOS Bearish
                        self.structure_strength += 1
                    else:
                        # CHoCH to bearish
                        self.bullish_structure = False
                        self.structure_strength = 1
            
            self.last_swing_low = pivot_low_val
        
        # Momentum detection
        momentum_bull = (rsi_val > 50 and macd_hist_val > 0)
        momentum_bear = (rsi_val < 50 and macd_hist_val < 0)
        
        # Entry signals: Buy on bullish structure + momentum confirmation
        if not self.position:
            if self.bullish_structure and momentum_bull and self.structure_strength > 1:
                self.buy()
            elif not self.bullish_structure and momentum_bear and self.structure_strength > 1:
                self.sell()
        else:
            # Exit signals: Structure change or momentum reversal
            if self.position.is_long:
                if not self.bullish_structure or momentum_bear:
                    self.position.close()
            elif self.position.is_short:
                if self.bullish_structure or momentum_bull:
                    self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()