"""
DS-TV Backtest Results: structure-stats-trend-long-short-for-tfex-s50-go
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — structure-stats-trend-long-short-for-tfex-s50-go
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    anchor_tf = "W"
    entry_sd = 1.5
    exit_sd = 3.0
    swing_len = 3
    memory_len = 15
    warmup_bars = 1
    htf_swing = 3

    def init(self):
        self.state = 0
        self.mem_up_entry = 999
        self.mem_dn_entry = 999
        self.mem_up_exit = 999
        self.mem_dn_exit = 999
        self.bars_in_period = 0
        self.last_ph = np.nan
        self.last_pl = np.nan
        self.ht_ph = np.nan
        self.ht_pl = np.nan
        self.sum_src_vol = 0.0
        self.sum_vol = 0.0
        self.sum_src_src_vol = 0.0
        self.last_period = None
        self.last_htf_period = None
        self.htf_trend = 1

    def next(self):
        if len(self.data) < self.swing_len + 2:
            return

        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        hlc3_val = (high + low + close) / 3.0
        volume = self.data.Volume[-1]

        # Detect new anchor period
        df = self.data.df
        current_idx = len(df) - 1
        current_time = df.index[current_idx]
        
        is_new_period = False
        if self.last_period is None:
            is_new_period = True
            self.last_period = current_time
        else:
            if self.anchor_tf == "W":
                curr_week = (current_time.year, current_time.isocalendar()[1])
                last_week = (self.last_period.year, self.last_period.isocalendar()[1])
                is_new_period = curr_week != last_week
            elif self.anchor_tf == "D":
                is_new_period = current_time.date() != self.last_period.date()
            elif self.anchor_tf == "M":
                is_new_period = (current_time.year, current_time.month) != (self.last_period.year, self.last_period.month)
            
            if is_new_period:
                self.last_period = current_time

        # Warm-up bar counting
        if is_new_period:
            self.bars_in_period = 0
            self.sum_src_vol = 0.0
            self.sum_vol = 0.0
            self.sum_src_src_vol = 0.0
        else:
            self.bars_in_period += 1

        is_warmed_up = self.bars_in_period >= self.warmup_bars

        # AVWAP calculation
        self.sum_src_vol += hlc3_val * volume
        self.sum_vol += volume
        self.sum_src_src_vol += hlc3_val * hlc3_val * volume

        if self.sum_vol > 0:
            vwap_val = self.sum_src_vol / self.sum_vol
            variance = (self.sum_src_src_vol / self.sum_vol) - (vwap_val * vwap_val)
            stdev = np.sqrt(max(0, variance))
        else:
            vwap_val = close
            stdev = 0

        up_entry = vwap_val + (self.entry_sd * stdev)
        dn_entry = vwap_val - (self.entry_sd * stdev)
        up_exit = vwap_val + (self.exit_sd * stdev)
        dn_exit = vwap_val - (self.exit_sd * stdev)

        # HTF Bias using pivots
        if len(df) >= self.htf_swing * 2 + 1:
            highs = df['High'].values
            lows = df['Low'].values
            closes = df['Close'].values
            
            idx = current_idx
            if idx >= self.htf_swing * 2:
                is_ph = True
                is_pl = True
                for j in range(1, self.htf_swing + 1):
                    if idx - j < 0 or idx + j >= len(highs):
                        is_ph = False
                        is_pl = False
                        break
                    if highs[idx] <= highs[idx - j] or highs[idx] <= highs[idx + j]:
                        is_ph = False
                    if lows[idx] >= lows[idx - j] or lows[idx] >= lows[idx + j]:
                        is_pl = False
                
                if is_ph:
                    self.ht_ph = highs[idx]
                if is_pl:
                    self.ht_pl = lows[idx]
        
        if not np.isnan(self.ht_ph) and close > self.ht_ph:
            self.htf_trend = 1
        if not np.isnan(self.ht_pl) and close < self.ht_pl:
            self.htf_trend = -1

        bias_long = (self.htf_trend == 1)
        bias_short = (self.htf_trend == -1)

        # SMC Structure - Current TF Pivot
        if len(df) >= self.swing_len * 2 + 1:
            highs = df['High'].values
            lows = df['Low'].values
            
            idx = current_idx
            if idx >= self.swing_len * 2:
                is_ph = True
                is_pl = True
                for j in range(1, self.swing_len + 1):
                    if idx - j < 0 or idx + j >= len(highs):
                        is_ph = False
                        is_pl = False
                        break
                    if highs[idx] <= highs[idx - j] or highs[idx] <= highs[idx + j]:
                        is_ph = False
                    if lows[idx] >= lows[idx - j] or lows[idx] >= lows[idx + j]:
                        is_pl = False
                
                if is_ph:
                    self.last_ph = highs[idx]
                if is_pl:
                    self.last_pl = lows[idx]

        bull_choch = False
        bear_choch = False
        
        if not np.isnan(self.last_ph) and len(df) >= 2:
            if df['Close'].iloc[-2] <= self.last_ph and close > self.last_ph:
                bull_choch = True
        
        if not np.isnan(self.last_pl) and len(df) >= 2:
            if df['Close'].iloc[-2] >= self.last_pl and close < self.last_pl:
                bear_choch = True

        # Memory Logic
        self.mem_up_entry += 1
        self.mem_dn_entry += 1
        self.mem_up_exit += 1
        self.mem_dn_exit += 1

        if low <= dn_entry and is_warmed_up:
            self.mem_dn_entry = 0
        if high >= up_entry and is_warmed_up:
            self.mem_up_entry = 0
        if low <= dn_exit and is_warmed_up:
            self.mem_dn_exit = 0
        if high >= up_exit and is_warmed_up:
            self.mem_up_exit = 0

        # State Machine
        open_l = False
        open_s = False
        close_l = False
        close_s = False

        if self.state == 0:
            if self.mem_dn_entry <= self.memory_len and bull_choch and bias_long:
                open_l = True
                self.state = 1
                self.mem_dn_entry = 999
            elif self.mem_up_entry <= self.memory_len and bear_choch and bias_short:
                open_s = True
                self.state = -1
                self.mem_up_entry = 999

        if self.state == 1 and self.mem_up_exit <= self.memory_len and bear_choch:
            close_l = True
            self.state = 0
            self.mem_up_exit = 999

        if self.state == -1 and self.mem_dn_exit <= self.memory_len and bull_choch:
            close_s = True
            self.state = 0
            self.mem_dn_exit = 999

        # Execution
        if open_l and not self.position:
            self.buy()
        elif close_l and self.position:
            self.position.close()

        if open_s and not self.position:
            self.sell()
        elif close_s and self.position:
            self.position.close()


if __name__ == "__main__":
    from backtesting.test import GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()