"""
DS-TV Backtest Results: structural-svm-ranker-luxalgo
============================================================

--- SPY ---
  Return                    -37.44%
  Buy & Hold Return         39.08%
  Max Drawdown              -42.27%
  Sharpe Ratio              -1.52
  Sortino Ratio             -1.61
  Calmar Ratio              -0.50
  Profit Factor             0.27
  Expectancy                -4.30%
  SQN                       -1.26
  # Trades                  9
  Win Rate                  22.22%
  Best Trade                11.85%
  Worst Trade               -27.11%
  Avg Trade                 -4.87%
  Exposure Time             92.00%
  Equity Final              62563.24$
  Equity Peak               108122.16$
  Avg Drawdown              -7.33%
  Max Drawdown Duration     573 days 00:00:00
  Max Trade Duration        192 days 00:00:00
  Avg Trade Duration        75 days 00:00:00
  Ann. Return               -21.05%
  Ann. Volatility           13.86%

--- BTC ---
  Return                    -50.17%
  Buy & Hold Return         14.14%
  Max Drawdown              -60.56%
  Sharpe Ratio              -1.11
  Sortino Ratio             -1.10
  Calmar Ratio              -0.49
  Profit Factor             0.00
  Expectancy                -42.85%
  SQN                       -1.59
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -14.12%
  Worst Trade               -71.57%
  Avg Trade                 -50.59%
  Exposure Time             36.11%
  Equity Final              49830.42$
  Equity Peak               105125.83$
  Avg Drawdown              -20.81%
  Max Drawdown Duration     631 days 00:00:00
  Max Trade Duration        213 days 00:00:00
  Avg Trade Duration        132 days 00:00:00
  Ann. Return               -29.38%
  Ann. Volatility           26.42%

--- QQQ ---
  Return                    -34.80%
  Buy & Hold Return         42.00%
  Max Drawdown              -48.41%
  Sharpe Ratio              -0.97
  Sortino Ratio             -1.12
  Calmar Ratio              -0.40
  Profit Factor             0.33
  Expectancy                -3.94%
  SQN                       -0.84
  # Trades                  8
  Win Rate                  50.00%
  Best Trade                12.08%
  Worst Trade               -34.62%
  Avg Trade                 -4.93%
  Exposure Time             86.40%
  Equity Final              65198.67$
  Equity Peak               111124.47$
  Avg Drawdown              -8.90%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        231 days 00:00:00
  Avg Trade Duration        79 days 00:00:00
  Ann. Return               -19.39%
  Ann. Volatility           19.99%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — structural-svm-ranker-luxalgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    pivotLen = 5
    volWeight = 0.4
    rsiWeight = 0.3
    distWeight = 0.3
    atrLen = 14

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.rsi = self.I(pta.rsi, close, length=14)
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        self.vol_sma = self.I(pta.sma, volume, length=20)
        
        self.last_pivot_hi = None
        self.last_pivot_hi_idx = None
        self.last_pivot_lo = None
        self.last_pivot_lo_idx = None
        self.trend = 0
        
        self.pivot_hi_values = []
        self.pivot_lo_values = []
        
    def sigmoid(self, x):
        return 100 / (1 + np.exp(-x))
    
    def detect_pivot_high(self, idx):
        if idx < self.pivotLen or idx >= len(self.data) - self.pivotLen:
            return None
        
        current_high = self.data.High[idx]
        is_pivot = True
        
        for i in range(1, self.pivotLen + 1):
            if self.data.High[idx - i] >= current_high or self.data.High[idx + i] >= current_high:
                is_pivot = False
                break
        
        return current_high if is_pivot else None
    
    def detect_pivot_low(self, idx):
        if idx < self.pivotLen or idx >= len(self.data) - self.pivotLen:
            return None
        
        current_low = self.data.Low[idx]
        is_pivot = True
        
        for i in range(1, self.pivotLen + 1):
            if self.data.Low[idx - i] <= current_low or self.data.Low[idx + i] <= current_low:
                is_pivot = False
                break
        
        return current_low if is_pivot else None
    
    def next(self):
        idx = len(self.data) - 1
        
        if idx < self.pivotLen + 1:
            return
        
        ph = self.detect_pivot_high(idx - self.pivotLen)
        pl = self.detect_pivot_low(idx - self.pivotLen)
        
        if ph is not None:
            self.last_pivot_hi = ph
            self.last_pivot_hi_idx = idx - self.pivotLen
        
        if pl is not None:
            self.last_pivot_lo = pl
            self.last_pivot_lo_idx = idx - self.pivotLen
        
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        prev_high = self.data.High[-2] if len(self.data) > 1 else current_high
        prev_low = self.data.Low[-2] if len(self.data) > 1 else current_low
        
        rel_vol = self.data.Volume[-1] / max(self.vol_sma[-1], 1)
        rsi_val = self.rsi[-1] if self.rsi[-1] is not None else 50
        rsi_feature = abs(rsi_val - 50) / 50
        atr_val = self.atr[-1] if self.atr[-1] is not None else 1
        atr_val = max(atr_val, 0.001)
        
        if self.last_pivot_hi is not None and current_close > self.last_pivot_hi and prev_high <= self.last_pivot_hi:
            dist_feature = (current_close - self.last_pivot_hi) / atr_val
            raw_score = (rel_vol * self.volWeight) + (rsi_feature * self.rsiWeight) + (dist_feature * self.distWeight)
            current_score = self.sigmoid(raw_score * 2 - 1)
            
            if self.trend == -1:
                self.trend = 1
            else:
                self.trend = 1
            
            if not self.position:
                self.buy()
            
            self.last_pivot_hi = None
        
        elif self.last_pivot_lo is not None and current_close < self.last_pivot_lo and prev_low >= self.last_pivot_lo:
            dist_feature = (self.last_pivot_lo - current_close) / atr_val
            raw_score = (rel_vol * self.volWeight) + (rsi_feature * self.rsiWeight) + (dist_feature * self.distWeight)
            current_score = self.sigmoid(raw_score * 2 - 1)
            
            if self.trend == 1:
                self.trend = -1
            else:
                self.trend = -1
            
            if self.position:
                self.sell()
            
            self.last_pivot_lo = None


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()