"""
DS-TV Backtest Results: swiftedge-ivb-model
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         38.66%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         37.68%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         39.38%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — swiftedge-ivb-model
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atr_period = 14
    atr_mult_1 = 0.1
    atr_mult_2 = 0.2
    atr_mult_3 = 0.3
    atr_mult_4 = 0.4
    atr_mult_5 = 0.5
    atr_mult_6 = 0.0
    or_start_hour = 9
    or_start_minute = 0
    or_end_hour = 9
    or_end_minute = 30

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_period)
        
        self.or_high_val = np.nan
        self.or_low_val = np.nan
        self.or_start_bar = -1
        self.break_level = np.nan
        self.is_long = False
        self.breakout_detected = False
        self.last_day = -1

    def next(self):
        current_time = pd.Timestamp(self.data.index[-1])
        current_day = current_time.day
        
        if current_day != self.last_day:
            self.or_high_val = np.nan
            self.or_low_val = np.nan
            self.or_start_bar = -1
            self.last_day = current_day
        
        in_or = (current_time.hour == self.or_start_hour and 
                 self.or_start_minute <= current_time.minute < self.or_end_minute)
        
        if in_or:
            if self.or_start_bar == -1:
                self.or_start_bar = len(self.data) - 1
                self.or_high_val = self.data.High[-1]
                self.or_low_val = self.data.Low[-1]
            
            self.or_high_val = max(self.or_high_val, self.data.High[-1])
            self.or_low_val = min(self.or_low_val, self.data.Low[-1])
        
        after_or = not in_or and not np.isnan(self.or_high_val)
        
        up_break = False
        dn_break = False
        
        if after_or and len(self.data) > 1:
            if self.data.Close[-1] > self.or_high_val and self.data.Close[-2] <= self.or_high_val:
                up_break = True
            if self.data.Close[-1] < self.or_low_val and self.data.Close[-2] >= self.or_low_val:
                dn_break = True
        
        if up_break:
            self.break_level = self.or_high_val
            self.is_long = True
            self.breakout_detected = True
            if not self.position:
                self.buy()
        
        if dn_break:
            self.break_level = self.or_low_val
            self.is_long = False
            self.breakout_detected = True
            if self.position:
                self.position.close()
            else:
                self.sell()
        
        if self.breakout_detected and self.position:
            atr_val = self.atr[-1] if not np.isnan(self.atr[-1]) else 0
            
            if self.is_long:
                target_6 = self.break_level + atr_val * self.atr_mult_6
                if self.atr_mult_6 > 0 and self.data.High[-1] >= target_6:
                    self.position.close()
                    self.breakout_detected = False
                else:
                    target_5 = self.break_level + atr_val * self.atr_mult_5
                    if self.atr_mult_5 > 0 and self.data.High[-1] >= target_5:
                        self.position.close()
                        self.breakout_detected = False
            else:
                target_6 = self.break_level - atr_val * self.atr_mult_6
                if self.atr_mult_6 > 0 and self.data.Low[-1] <= target_6:
                    self.position.close()
                    self.breakout_detected = False
                else:
                    target_5 = self.break_level - atr_val * self.atr_mult_5
                    if self.atr_mult_5 > 0 and self.data.Low[-1] <= target_5:
                        self.position.close()
                        self.breakout_detected = False


if __name__ == '__main__':
    bt = Backtest(
        pd.read_csv('data.csv', index_col=0, parse_dates=True),
        TvStrategy,
        cash=100000,
        commission=.002
    )
    stats = bt.run()
    print(stats)
    bt.plot()