"""
DS-TV Backtest Results: tikole-spadx-di-trend-indication-9503888883
============================================================

--- SPY ---
  ERROR: Indicator "calc_smoo…(calc_true…,calc_dire…,calc_dire…)" error. See traceback above.

--- BTC ---
  ERROR: Indicator "calc_smoo…(calc_true…,calc_dire…,calc_dire…)" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "calc_smoo…(calc_true…,calc_dire…,calc_dire…)" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — tikole-spadx-di-trend-indication-9503888883
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len = 14
    th1 = 10
    th2 = 20
    th3 = 40
    priority = 1

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate True Range manually
        def calc_true_range():
            tr = pd.Series(index=close.index, dtype=float)
            for i in range(len(close)):
                if i == 0:
                    tr.iloc[i] = high.iloc[i] - low.iloc[i]
                else:
                    tr.iloc[i] = max(
                        high.iloc[i] - low.iloc[i],
                        abs(high.iloc[i] - close.iloc[i-1]),
                        abs(low.iloc[i] - close.iloc[i-1])
                    )
            return tr
        
        # Calculate Directional Movements manually
        def calc_directional_movements():
            dm_plus = pd.Series(index=close.index, dtype=float)
            dm_minus = pd.Series(index=close.index, dtype=float)
            for i in range(len(close)):
                if i == 0:
                    dm_plus.iloc[i] = 0
                    dm_minus.iloc[i] = 0
                else:
                    up_move = high.iloc[i] - high.iloc[i-1]
                    down_move = low.iloc[i-1] - low.iloc[i]
                    
                    if up_move > down_move and up_move > 0:
                        dm_plus.iloc[i] = up_move
                    else:
                        dm_plus.iloc[i] = 0
                    
                    if down_move > up_move and down_move > 0:
                        dm_minus.iloc[i] = down_move
                    else:
                        dm_minus.iloc[i] = 0
            return dm_plus, dm_minus
        
        # Calculate Smoothed values manually
        def calc_smoothed_values(tr, dm_plus, dm_minus):
            smoothed_tr = pd.Series(index=close.index, dtype=float)
            smoothed_dm_plus = pd.Series(index=close.index, dtype=float)
            smoothed_dm_minus = pd.Series(index=close.index, dtype=float)
            
            for i in range(len(close)):
                if i < self.len:
                    if i == 0:
                        smoothed_tr.iloc[i] = tr.iloc[i]
                        smoothed_dm_plus.iloc[i] = dm_plus.iloc[i]
                        smoothed_dm_minus.iloc[i] = dm_minus.iloc[i]
                    else:
                        smoothed_tr.iloc[i] = smoothed_tr.iloc[i-1] - (smoothed_tr.iloc[i-1] / self.len) + tr.iloc[i]
                        smoothed_dm_plus.iloc[i] = smoothed_dm_plus.iloc[i-1] - (smoothed_dm_plus.iloc[i-1] / self.len) + dm_plus.iloc[i]
                        smoothed_dm_minus.iloc[i] = smoothed_dm_minus.iloc[i-1] - (smoothed_dm_minus.iloc[i-1] / self.len) + dm_minus.iloc[i]
                else:
                    smoothed_tr.iloc[i] = smoothed_tr.iloc[i-1] - (smoothed_tr.iloc[i-1] / self.len) + tr.iloc[i]
                    smoothed_dm_plus.iloc[i] = smoothed_dm_plus.iloc[i-1] - (smoothed_dm_plus.iloc[i-1] / self.len) + dm_plus.iloc[i]
                    smoothed_dm_minus.iloc[i] = smoothed_dm_minus.iloc[i-1] - (smoothed_dm_minus.iloc[i-1] / self.len) + dm_minus.iloc[i]
            
            return smoothed_tr, smoothed_dm_plus, smoothed_dm_minus
        
        # Calculate DI+ and DI-
        def calc_di_values(smoothed_tr, smoothed_dm_plus, smoothed_dm_minus):
            di_plus = pd.Series(index=close.index, dtype=float)
            di_minus = pd.Series(index=close.index, dtype=float)
            
            for i in range(len(close)):
                if smoothed_tr.iloc[i] != 0:
                    di_plus.iloc[i] = (smoothed_dm_plus.iloc[i] / smoothed_tr.iloc[i]) * 100
                    di_minus.iloc[i] = (smoothed_dm_minus.iloc[i] / smoothed_tr.iloc[i]) * 100
                else:
                    di_plus.iloc[i] = 0
                    di_minus.iloc[i] = 0
            
            return di_plus, di_minus
        
        # Calculate DX and ADX
        def calc_adx(di_plus, di_minus):
            dx = pd.Series(index=close.index, dtype=float)
            
            for i in range(len(close)):
                di_sum = di_plus.iloc[i] + di_minus.iloc[i]
                if di_sum != 0:
                    dx.iloc[i] = (abs(di_plus.iloc[i] - di_minus.iloc[i]) / di_sum) * 100
                else:
                    dx.iloc[i] = 0
            
            adx = pta.sma(dx, length=self.len)
            if adx is None:
                adx = pd.Series(0, index=close.index)
            return adx
        
        tr = self.I(calc_true_range)
        dm_plus, dm_minus = self.I(calc_directional_movements)
        smoothed_tr, smoothed_dm_plus, smoothed_dm_minus = self.I(calc_smoothed_values, tr, dm_plus, dm_minus)
        di_plus, di_minus = self.I(calc_di_values, smoothed_tr, smoothed_dm_plus, smoothed_dm_minus)
        
        self.di_plus = di_plus
        self.di_minus = di_minus
        
        di_diff = di_plus - di_minus
        self.di_diff = di_diff
        
        adx = self.I(calc_adx, di_plus, di_minus)
        self.adx = adx
        
        momentprod = di_diff * adx
        self.momentprod = momentprod
        
        smooth = self.I(pta.ema, momentprod, length=self.len)
        if smooth is None:
            smooth = pd.Series(0, index=close.index)
        self.smooth = smooth

    def next(self):
        if len(self.data) < self.len + 5:
            return
        
        buy_signal = crossover(self.smooth, 1)
        sell_signal = crossover(1, self.smooth)
        
        if buy_signal and not self.position:
            self.buy()
        elif sell_signal and self.position:
            self.position.close()