"""
DS-TV Backtest Results: timeframe-clock-21-pro-plan-and-under
============================================================

--- SPY ---
  Return                    -74.17%
  Buy & Hold Return         41.94%
  Max Drawdown              -74.71%
  Sharpe Ratio              -5.88
  Sortino Ratio             -3.61
  Calmar Ratio              -0.66
  Profit Factor             0.47
  Expectancy                -0.27%
  SQN                       -5.30
  # Trades                  489
  Win Rate                  33.13%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.28%
  Exposure Time             99.60%
  Equity Final              25827.93$
  Equity Peak               102123.52$
  Avg Drawdown              -37.88%
  Max Drawdown Duration     717 days 00:00:00
  Max Trade Duration        14 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -49.45%
  Ann. Volatility           8.41%

--- BTC ---
  Return                    -41.35%
  Buy & Hold Return         46.22%
  Max Drawdown              -46.84%
  Sharpe Ratio              -1.22
  Sortino Ratio             -1.23
  Calmar Ratio              -0.50
  Profit Factor             0.73
  Expectancy                -0.34%
  SQN                       -1.42
  # Trades                  223
  Win Rate                  45.29%
  Best Trade                8.14%
  Worst Trade               -12.38%
  Avg Trade                 -0.39%
  Exposure Time             32.28%
  Equity Final              58645.25$
  Equity Peak               110319.23$
  Avg Drawdown              -16.06%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        9 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -23.39%
  Ann. Volatility           19.21%

--- QQQ ---
  Return                    -75.60%
  Buy & Hold Return         42.67%
  Max Drawdown              -76.25%
  Sharpe Ratio              -4.88
  Sortino Ratio             -3.03
  Calmar Ratio              -0.67
  Profit Factor             0.56
  Expectancy                -0.28%
  SQN                       -4.24
  # Trades                  489
  Win Rate                  35.58%
  Best Trade                6.54%
  Worst Trade               -9.35%
  Avg Trade                 -0.29%
  Exposure Time             99.60%
  Equity Final              24403.53$
  Equity Peak               101476.32$
  Avg Drawdown              -39.15%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        14 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -50.88%
  Ann. Volatility           10.42%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — timeframe-clock-21-pro-plan-and-under
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy


class TvStrategy(Strategy):
    def init(self):
        pass

    def next(self):
        if len(self.data) < 2:
            return
        
        if not self.position:
            self.buy()
        elif len(self.data) > 10:
            self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()