"""
DS-TV Backtest Results: trading-levels-poc-daily-hl-psychological-levels
============================================================

--- SPY ---
  Return                    -49.42%
  Buy & Hold Return         41.94%
  Max Drawdown              -50.36%
  Sharpe Ratio              -2.46
  Sortino Ratio             -2.30
  Calmar Ratio              -0.58
  Profit Factor             0.44
  Expectancy                -0.44%
  SQN                       -3.01
  # Trades                  149
  Win Rate                  36.91%
  Best Trade                10.84%
  Worst Trade               -8.99%
  Avg Trade                 -0.45%
  Exposure Time             98.60%
  Equity Final              50575.87$
  Equity Peak               101674.25$
  Avg Drawdown              -50.36%
  Max Drawdown Duration     720 days 00:00:00
  Max Trade Duration        22 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -29.08%
  Ann. Volatility           11.82%

--- BTC ---
  Return                    -43.47%
  Buy & Hold Return         46.22%
  Max Drawdown              -45.50%
  Sharpe Ratio              -1.21
  Sortino Ratio             -1.18
  Calmar Ratio              -0.54
  Profit Factor             0.51
  Expectancy                -1.30%
  SQN                       -1.50
  # Trades                  44
  Win Rate                  43.18%
  Best Trade                6.86%
  Worst Trade               -22.48%
  Avg Trade                 -1.46%
  Exposure Time             25.58%
  Equity Final              56527.93$
  Equity Peak               101778.50$
  Avg Drawdown              -45.50%
  Max Drawdown Duration     718 days 00:00:00
  Max Trade Duration        15 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -24.79%
  Ann. Volatility           20.44%

--- QQQ ---
  Return                    -50.78%
  Buy & Hold Return         42.67%
  Max Drawdown              -53.01%
  Sharpe Ratio              -2.13
  Sortino Ratio             -2.06
  Calmar Ratio              -0.57
  Profit Factor             0.52
  Expectancy                -0.47%
  SQN                       -2.83
  # Trades                  145
  Win Rate                  37.24%
  Best Trade                5.08%
  Worst Trade               -6.37%
  Avg Trade                 -0.49%
  Exposure Time             97.20%
  Equity Final              49218.10$
  Equity Peak               101868.84$
  Avg Drawdown              -28.80%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        24 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -30.04%
  Ann. Volatility           14.09%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trading-levels-poc-daily-hl-psychological-levels
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # POC Settings
    vol_days = 5
    num_rows = 24
    vol_zone_size = 0.10
    
    # Daily High/Low Settings
    daily_days = 1
    
    # Psychological Levels Settings
    psych_interval = 1.0
    psych_zone_size = 0.10
    max_psych_levels = 10

    def init(self):
        self.daily_pocs = []
        self.daily_highs = []
        self.daily_lows = []
        self.current_day_time = None
        self.current_day_high = None
        self.current_day_low = None
        self.day_bar_highs = []
        self.day_bar_lows = []
        self.day_bar_volumes = []
        self.current_day_poc = None
        self.last_date = None

    def calc_poc(self, day_high, day_low, rows):
        """Calculate Point of Control from volume profile"""
        poc = (day_high + day_low) / 2
        
        if day_high > day_low and len(self.day_bar_highs) > 0:
            row_height = (day_high - day_low) / rows
            bin_volumes = [0.0] * rows
            
            for i in range(len(self.day_bar_highs)):
                bar_h = self.day_bar_highs[i]
                bar_l = self.day_bar_lows[i]
                bar_vol = self.day_bar_volumes[i]
                
                low_bin = max(0, int((bar_l - day_low) / row_height))
                high_bin = min(rows - 1, int((bar_h - day_low) / row_height))
                
                num_bins = high_bin - low_bin + 1
                vol_per_bin = bar_vol / max(num_bins, 1)
                
                for bin_idx in range(low_bin, high_bin + 1):
                    if 0 <= bin_idx < rows:
                        bin_volumes[bin_idx] += vol_per_bin
            
            max_vol = max(bin_volumes) if bin_volumes else 0
            poc_bin_idx = bin_volumes.index(max_vol) if max_vol > 0 else 0
            poc = day_low + (poc_bin_idx + 0.5) * row_height
        
        return poc

    def get_nearest_lower_level(self, price, interval):
        """Calculate the nearest lower psychological level"""
        return int(price / interval) * interval

    def next(self):
        """Trading logic based on support/resistance levels"""
        current_date = pd.Timestamp(self.data.index[-1]).date()
        
        if self.last_date is None or current_date != self.last_date:
            if self.current_day_high is not None and self.current_day_low is not None and len(self.day_bar_highs) > 0:
                poc = self.calc_poc(self.current_day_high, self.current_day_low, self.num_rows)
                self.daily_pocs.append(poc)
                self.daily_highs.append(self.current_day_high)
                self.daily_lows.append(self.current_day_low)
                
                if len(self.daily_pocs) > self.vol_days:
                    self.daily_pocs.pop(0)
                    self.daily_highs.pop(0)
                    self.daily_lows.pop(0)
            
            self.current_day_high = self.data.High[-1]
            self.current_day_low = self.data.Low[-1]
            self.day_bar_highs = [self.data.High[-1]]
            self.day_bar_lows = [self.data.Low[-1]]
            self.day_bar_volumes = [self.data.Volume[-1]]
            self.last_date = current_date
        else:
            self.current_day_high = max(self.current_day_high, self.data.High[-1])
            self.current_day_low = min(self.current_day_low, self.data.Low[-1])
            self.day_bar_highs.append(self.data.High[-1])
            self.day_bar_lows.append(self.data.Low[-1])
            self.day_bar_volumes.append(self.data.Volume[-1])
        
        if len(self.day_bar_highs) > 0:
            self.current_day_poc = self.calc_poc(self.current_day_high, self.current_day_low, self.num_rows)
        
        close_price = self.data.Close[-1]
        
        # Trading logic: Buy near support levels, Sell near resistance levels
        support_levels = []
        resistance_levels = []
        
        # Add POC levels as support/resistance
        if self.daily_lows:
            support_levels.extend(self.daily_lows)
        if self.daily_highs:
            resistance_levels.extend(self.daily_highs)
        if self.current_day_poc is not None:
            support_levels.append(self.current_day_poc)
            resistance_levels.append(self.current_day_poc)
        
        # Add psychological levels
        base_level = self.get_nearest_lower_level(close_price, self.psych_interval)
        for i in range(-self.max_psych_levels, self.max_psych_levels + 1):
            level = base_level + (i * self.psych_interval)
            if level > 0:
                if level < close_price:
                    support_levels.append(level)
                else:
                    resistance_levels.append(level)
        
        # Find closest support and resistance
        closest_support = max([s for s in support_levels if s < close_price], default=None)
        closest_resistance = min([r for r in resistance_levels if r > close_price], default=None)
        
        # Trading signals
        if not self.position:
            # Buy near support with some margin
            if closest_support is not None and (close_price - closest_support) < (self.vol_zone_size * 2):
                self.buy()
            # Buy on psychological level touch
            elif any(abs(close_price - level) < self.psych_zone_size for level in support_levels):
                self.buy()
        else:
            # Sell near resistance with some margin
            if closest_resistance is not None and (closest_resistance - close_price) < (self.vol_zone_size * 2):
                self.sell()
            # Sell on psychological level touch
            elif any(abs(close_price - level) < self.psych_zone_size for level in resistance_levels):
                self.sell()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()