"""
DS-TV Backtest Results: trend-forge
============================================================

--- SPY ---
  Return                    4.26%
  Buy & Hold Return         29.25%
  Max Drawdown              -18.25%
  Sharpe Ratio              0.14
  Sortino Ratio             0.20
  Calmar Ratio              0.12
  Profit Factor             1.11
  Expectancy                0.08%
  SQN                       0.15
  # Trades                  44
  Win Rate                  43.18%
  Best Trade                5.60%
  Worst Trade               -7.77%
  Avg Trade                 0.05%
  Exposure Time             77.40%
  Equity Final              104263.09$
  Equity Peak               123715.39$
  Avg Drawdown              -3.53%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        76 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               2.13%
  Ann. Volatility           14.81%

--- BTC ---
  Return                    28.99%
  Buy & Hold Return         14.16%
  Max Drawdown              -30.16%
  Sharpe Ratio              0.41
  Sortino Ratio             0.73
  Calmar Ratio              0.45
  Profit Factor             1.14
  Expectancy                0.28%
  SQN                       0.13
  # Trades                  49
  Win Rate                  44.90%
  Best Trade                40.31%
  Worst Trade               -15.16%
  Avg Trade                 0.03%
  Exposure Time             57.32%
  Equity Final              128988.58$
  Equity Peak               140023.34$
  Avg Drawdown              -6.11%
  Max Drawdown Duration     372 days 00:00:00
  Max Trade Duration        44 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               13.55%
  Ann. Volatility           32.78%

--- QQQ ---
  Return                    -1.28%
  Buy & Hold Return         27.84%
  Max Drawdown              -19.39%
  Sharpe Ratio              -0.04
  Sortino Ratio             -0.05
  Calmar Ratio              -0.03
  Profit Factor             1.01
  Expectancy                0.01%
  SQN                       -0.09
  # Trades                  51
  Win Rate                  45.10%
  Best Trade                9.71%
  Worst Trade               -7.85%
  Avg Trade                 -0.04%
  Exposure Time             73.20%
  Equity Final              98716.80$
  Equity Peak               114912.07$
  Avg Drawdown              -4.31%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        83 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               -0.65%
  Ann. Volatility           17.73%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trend-forge
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    Trend_1 = "EMA"
    Trend1_Length = 21
    Trend_2 = "EMA"
    Trend2_Length = 55
    Trend_3 = "SMA"
    Trend3_Length = 89
    Multiplier = 2.5
    LongTrades = True
    ShortTrades = False

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        hlc3 = (high + low + close) / 3
        
        # Trend 1 indicators
        ema1 = self.I(pta.ema, close, length=self.Trend1_Length)
        sma1 = self.I(pta.sma, close, length=self.Trend1_Length)
        rsi1 = self.I(pta.rsi, close, length=self.Trend1_Length)
        cci1 = self.I(pta.cci, high, low, close, length=self.Trend1_Length)
        
        esa1 = self.I(pta.ema, hlc3, length=self.Trend1_Length)
        d1 = self.I(pta.ema, np.abs(hlc3 - esa1), length=self.Trend1_Length)
        ci1 = (hlc3 - esa1) / (0.015 * d1 + 1e-10)
        wt1 = self.I(pta.ema, ci1, length=self.Trend1_Length)
        
        # Trend 2 indicators
        ema2 = self.I(pta.ema, close, length=self.Trend2_Length)
        sma2 = self.I(pta.sma, close, length=self.Trend2_Length)
        rsi2 = self.I(pta.rsi, close, length=self.Trend2_Length)
        cci2 = self.I(pta.cci, high, low, close, length=self.Trend2_Length)
        
        esa2 = self.I(pta.ema, hlc3, length=self.Trend2_Length)
        d2 = self.I(pta.ema, np.abs(hlc3 - esa2), length=self.Trend2_Length)
        ci2 = (hlc3 - esa2) / (0.015 * d2 + 1e-10)
        wt2 = self.I(pta.ema, ci2, length=self.Trend2_Length)
        
        # Trend 3 indicators
        ema3 = self.I(pta.ema, close, length=self.Trend3_Length)
        sma3 = self.I(pta.sma, close, length=self.Trend3_Length)
        rsi3 = self.I(pta.rsi, close, length=self.Trend3_Length)
        cci3 = self.I(pta.cci, high, low, close, length=self.Trend3_Length)
        
        esa3 = self.I(pta.ema, hlc3, length=self.Trend3_Length)
        d3 = self.I(pta.ema, np.abs(hlc3 - esa3), length=self.Trend3_Length)
        ci3 = (hlc3 - esa3) / (0.015 * d3 + 1e-10)
        wt3 = self.I(pta.ema, ci3, length=self.Trend3_Length)
        
        # Select which indicator to use based on trend type
        def select_trend_1():
            if self.Trend_1 == "EMA":
                return ema1
            elif self.Trend_1 == "SMA":
                return sma1
            elif self.Trend_1 == "RSI":
                return rsi1
            elif self.Trend_1 == "CCI":
                return cci1
            else:
                return wt1
        
        def select_trend_2():
            if self.Trend_2 == "EMA":
                return ema2
            elif self.Trend_2 == "SMA":
                return sma2
            elif self.Trend_2 == "RSI":
                return rsi2
            elif self.Trend_2 == "CCI":
                return cci2
            else:
                return wt2
        
        def select_trend_3():
            if self.Trend_3 == "EMA":
                return ema3
            elif self.Trend_3 == "SMA":
                return sma3
            elif self.Trend_3 == "RSI":
                return rsi3
            elif self.Trend_3 == "CCI":
                return cci3
            else:
                return wt3
        
        self.ma21 = self.I(select_trend_1)
        self.ma55 = self.I(select_trend_2)
        self.ma89 = self.I(select_trend_3)
        
        self.ama = self.I(lambda: (self.ma21 + self.ma55 + self.ma89) / 3)
        
        # ATR for stop loss
        self.atr = self.I(pta.atr, high, low, close, length=20)
        self.sl_distance = self.I(lambda: self.atr * self.Multiplier)
        
        # State tracking
        self.bull_state = self.I(lambda: (self.ma21 < close) & (self.ma55 <= close) & (self.ma89 <= close))
        self.bear_state = self.I(lambda: (self.ma21 > close) & (self.ma55 > close) & (self.ma89 > close))
        
        # Store previous state for transition detection
        self.prev_bull = None
        self.prev_bear = None
        self.long_stop_loss = None
        self.short_stop_loss = None
        self.long_entry_price = None
        self.short_entry_price = None

    def next(self):
        close_val = self.data.Close[-1]
        
        # Get current indicator values
        ma21_val = self.ma21[-1] if len(self.ma21) > 0 else close_val
        ma55_val = self.ma55[-1] if len(self.ma55) > 0 else close_val
        ma89_val = self.ma89[-1] if len(self.ma89) > 0 else close_val
        atr_val = self.atr[-1] if len(self.atr) > 0 else 0
        sl_dist = atr_val * self.Multiplier
        
        # Determine states
        bull = (ma21_val < close_val) and (ma55_val <= close_val) and (ma89_val <= close_val)
        bear = (ma21_val > close_val) and (ma55_val > close_val) and (ma89_val > close_val)
        
        # Detect state transitions
        bull_entry = False
        bear_entry = False
        bull_exit = False
        bear_exit = False
        
        if self.prev_bull is not None:
            if bull and not self.prev_bull:
                bull_entry = True
                highest_ma = max(ma21_val, ma55_val, ma89_val)
                self.long_entry_price = highest_ma
                self.long_stop_loss = highest_ma - sl_dist
            
            if bear and not self.prev_bear:
                bear_entry = True
                lowest_ma = min(ma21_val, ma55_val, ma89_val)
                self.short_entry_price = lowest_ma
                self.short_stop_loss = lowest_ma + sl_dist
            
            if not bull and self.prev_bull:
                bull_exit = True
            
            if not bear and self.prev_bear:
                bear_exit = True
        
        self.prev_bull = bull
        self.prev_bear = bear
        
        # Entry and exit logic
        if bull_entry and self.LongTrades and not self.position:
            self.buy()
        
        if bear_entry and self.ShortTrades and not self.position:
            self.sell()
        
        if bull_exit and self.position.is_long:
            self.sell()
        
        if bear_exit and self.position.is_short:
            self.buy()
        
        # Stop loss logic
        if self.position.is_long and self.long_stop_loss is not None:
            if close_val <= self.long_stop_loss:
                self.sell()
        
        if self.position.is_short and self.short_stop_loss is not None:
            if close_val >= self.short_stop_loss:
                self.buy()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()