"""
DS-TV Backtest Results: trendline-breakout-indicator-dots3red
============================================================

--- SPY ---
  Return                    -20.74%
  Buy & Hold Return         39.08%
  Max Drawdown              -30.09%
  Sharpe Ratio              -0.72
  Sortino Ratio             -0.92
  Calmar Ratio              -0.37
  Profit Factor             nan
  Expectancy                4.33%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                4.33%
  Worst Trade               4.33%
  Avg Trade                 4.33%
  Exposure Time             42.60%
  Equity Final              79263.66$
  Equity Peak               112962.55$
  Avg Drawdown              -3.36%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        309 days 00:00:00
  Avg Trade Duration        309 days 00:00:00
  Ann. Return               -11.05%
  Ann. Volatility           15.31%

--- BTC ---
  Return                    -32.29%
  Buy & Hold Return         14.14%
  Max Drawdown              -48.29%
  Sharpe Ratio              -0.67
  Sortino Ratio             -0.76
  Calmar Ratio              -0.37
  Profit Factor             0.00
  Expectancy                -24.85%
  SQN                       -1.20
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -3.96%
  Worst Trade               -45.73%
  Avg Trade                 -27.80%
  Exposure Time             36.25%
  Equity Final              67707.90$
  Equity Peak               108101.82$
  Avg Drawdown              -23.38%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        230 days 00:00:00
  Avg Trade Duration        132 days 00:00:00
  Ann. Return               -17.69%
  Ann. Volatility           26.54%

--- QQQ ---
  Return                    33.39%
  Buy & Hold Return         42.00%
  Max Drawdown              -22.75%
  Sharpe Ratio              0.69
  Sortino Ratio             1.18
  Calmar Ratio              0.69
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              133389.60$
  Equity Peak               137866.73$
  Avg Drawdown              -2.70%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               15.63%
  Ann. Volatility           22.74%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trendline-breakout-indicator-dots3red
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    breakout_percentage = 1.03
    slope_threshold = 1.05
    pivot_len = 3
    min_channel_length = 30
    volume_breakout = 50

    def init(self):
        self.pivot_highs = []
        self.pivot_lows = []
        self.trendlines_bullish = []
        self.trendlines_bearish = []
        self.last_pivot_idx_bull = None
        self.last_pivot_val_bull = None
        self.last_pivot_idx_bear = None
        self.last_pivot_val_bear = None
        self.active_breakouts = []
        
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.vol_ma = self.I(pta.sma, volume, length=20)
        
    def get_pivot_high(self, idx):
        if idx < self.pivot_len or idx >= len(self.data) - self.pivot_len:
            return None
        high_vals = self.data.High[idx - self.pivot_len:idx + self.pivot_len + 1]
        pivot = self.data.High[idx]
        if pivot == high_vals.max() and high_vals.tolist().count(pivot) == 1:
            return pivot
        return None
    
    def get_pivot_low(self, idx):
        if idx < self.pivot_len or idx >= len(self.data) - self.pivot_len:
            return None
        low_vals = self.data.Low[idx - self.pivot_len:idx + self.pivot_len + 1]
        pivot = self.data.Low[idx]
        if pivot == low_vals.min() and low_vals.tolist().count(pivot) == 1:
            return pivot
        return None
    
    def get_extreme_in_range(self, left_idx, right_idx, is_bullish):
        if is_bullish:
            extreme = 0.0
            extreme_idx = left_idx
            for i in range(left_idx, right_idx + 1):
                if self.data.High[i] > extreme:
                    extreme = self.data.High[i]
                    extreme_idx = i
        else:
            extreme = float('inf')
            extreme_idx = left_idx
            for i in range(left_idx, right_idx + 1):
                if self.data.Low[i] < extreme:
                    extreme = self.data.Low[i]
                    extreme_idx = i
        return extreme, extreme_idx
    
    def find_max_deviation(self, slope, l_idx, l_val, r_idx, r_val, is_bullish):
        max_deviation = 0.0
        for x in range(l_idx, r_idx + 1):
            line_val = l_val + slope * (x - l_idx)
            if is_bullish:
                gap = self.data.High[x] - line_val
            else:
                gap = line_val - self.data.Low[x]
            if gap > max_deviation:
                max_deviation = gap
        return max_deviation
    
    def is_duplicate_trend(self, l_val, r_val, l_idx, r_idx, arr_of_trendlines):
        if len(arr_of_trendlines) == 0:
            return False
        new_slope = (r_val - l_val) / (r_idx - l_idx) if r_idx != l_idx else 0
        for existing in arr_of_trendlines:
            if existing['active']:
                old_slope = (existing['rVal'] - existing['lVal']) / (existing['rIdx'] - existing['lIdx']) if existing['rIdx'] != existing['lIdx'] else 0
                overlapping = l_idx > existing['lIdx'] and r_idx <= existing['r_extIdx']
                if overlapping:
                    return True
        return False
    
    def collect_trendlines(self, is_bullish, arr_of_trendlines):
        current_idx = len(self.data) - 1
        pivot_idx = current_idx - self.pivot_len
        
        if is_bullish:
            pivot_val = self.get_pivot_low(pivot_idx)
            last_pivot_idx = self.last_pivot_idx_bull
            last_pivot_val = self.last_pivot_val_bull
        else:
            pivot_val = self.get_pivot_high(pivot_idx)
            last_pivot_idx = self.last_pivot_idx_bear
            last_pivot_val = self.last_pivot_val_bear
        
        if pivot_val is None:
            return last_pivot_idx, last_pivot_val
        
        if last_pivot_idx is None:
            if is_bullish:
                self.last_pivot_idx_bull = pivot_idx
                self.last_pivot_val_bull = pivot_val
            else:
                self.last_pivot_idx_bear = pivot_idx
                self.last_pivot_val_bear = pivot_val
            return pivot_idx, pivot_val
        
        l_idx = last_pivot_idx
        l_val = last_pivot_val
        r_idx = pivot_idx
        r_val = pivot_val
        
        if l_val == 0 or r_val == 0:
            if is_bullish:
                self.last_pivot_idx_bull = pivot_idx
                self.last_pivot_val_bull = pivot_val
            else:
                self.last_pivot_idx_bear = pivot_idx
                self.last_pivot_val_bear = pivot_val
            return pivot_idx, pivot_val
        
        is_valid_slope = False
        if is_bullish:
            is_valid_slope = (r_val / l_val > self.slope_threshold)
        else:
            is_valid_slope = (l_val / r_val > self.slope_threshold)
        
        init_min_max = max(l_val, r_val) if is_bullish else min(l_val, r_val)
        
        if is_valid_slope:
            if not self.is_duplicate_trend(l_val, r_val, l_idx, r_idx, arr_of_trendlines):
                new_data = {
                    'lIdx': l_idx,
                    'rIdx': r_idx,
                    'lVal': l_val,
                    'rVal': r_val,
                    'min_max': init_min_max,
                    'min_max_idx': l_idx,
                    'r_extIdx': r_idx,
                    'r_ext': r_val,
                    'active': True
                }
                arr_of_trendlines.append(new_data)
        
        if is_bullish:
            self.last_pivot_idx_bull = pivot_idx
            self.last_pivot_val_bull = pivot_val
        else:
            self.last_pivot_idx_bear = pivot_idx
            self.last_pivot_val_bear = pivot_val
        
        return pivot_idx, pivot_val
    
    def map_trendlines(self, arr_of_trendlines, is_bullish):
        current_idx = len(self.data) - 1
        for data in arr_of_trendlines:
            if data['active']:
                slope = (data['rVal'] - data['lVal']) / (data['rIdx'] - data['lIdx']) if data['rIdx'] != data['lIdx'] else 0
                expected = data['lVal'] + slope * (current_idx - data['lIdx'])
                
                if is_bullish:
                    if self.data.High[current_idx] > data['min_max']:
                        data['min_max'] = self.data.High[current_idx]
                        data['min_max_idx'] = current_idx
                else:
                    if self.data.Low[current_idx] < data['min_max']:
                        data['min_max'] = self.data.Low[current_idx]
                        data['min_max_idx'] = current_idx
                
                if is_bullish:
                    breakout = self.data.Low[current_idx] < expected / self.breakout_percentage
                else:
                    breakout = self.data.Close[current_idx] > expected * self.breakout_percentage
                
                is_long_enough = data['r_extIdx'] - data['lIdx'] >= self.min_channel_length
                
                if breakout:
                    data['active'] = False
                    data['r_extIdx'] = current_idx
                    data['r_ext'] = expected
                    if is_long_enough:
                        self.active_breakouts.append({
                            'idx': current_idx,
                            'is_bullish': is_bullish,
                            'price': expected
                        })
                else:
                    data['r_extIdx'] = current_idx
                    data['r_ext'] = expected
    
    def next(self):
        current_idx = len(self.data) - 1
        
        self.collect_trendlines(False, self.trendlines_bearish)
        self.collect_trendlines(True, self.trendlines_bullish)
        
        if len(self.trendlines_bullish) > 0:
            self.map_trendlines(self.trendlines_bullish, True)
        
        if len(self.trendlines_bearish) > 0:
            self.map_trendlines(self.trendlines_bearish, False)
        
        for breakout in self.active_breakouts:
            if breakout['is_bullish']:
                if not self.position:
                    self.buy()
            else:
                if self.position:
                    self.sell()
        
        self.active_breakouts = []


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)