"""
DS-TV Backtest Results: trend-fusion-indicator
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         40.54%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         34.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.28%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trend-fusion-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    emaLen = 9
    stAtrLen = 10
    stFactor = 4.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # EMA calculation
        self.ema = self.I(pta.ema, close, length=self.emaLen)
        
        # Supertrend calculation
        self.atr = self.I(pta.atr, high, low, close, length=self.stAtrLen)
        
        # Calculate supertrend manually
        self.supertrend = self.I(self._calc_supertrend, high, low, close)
        
        self.trend = 0

    def _calc_supertrend(self, high, low, close):
        h = pd.Series(high)
        l = pd.Series(low)
        c = pd.Series(close)
        
        hl2 = (h + l) / 2
        atr = pta.atr(h, l, c, length=self.stAtrLen)
        
        if atr is None or len(atr) < 1:
            return pd.Series(c)
        
        basic_ub = hl2 + self.stFactor * atr
        basic_lb = hl2 - self.stFactor * atr
        
        final_ub = pd.Series(index=c.index, dtype=float)
        final_lb = pd.Series(index=c.index, dtype=float)
        
        final_ub.iloc[0] = basic_ub.iloc[0]
        final_lb.iloc[0] = basic_lb.iloc[0]
        
        for i in range(1, len(c)):
            final_ub.iloc[i] = basic_ub.iloc[i] if basic_ub.iloc[i] < final_ub.iloc[i-1] or c.iloc[i-1] > final_ub.iloc[i-1] else final_ub.iloc[i-1]
            final_lb.iloc[i] = basic_lb.iloc[i] if basic_lb.iloc[i] > final_lb.iloc[i-1] or c.iloc[i-1] < final_lb.iloc[i-1] else final_lb.iloc[i-1]
        
        supertrend = pd.Series(index=c.index, dtype=float)
        supertrend.iloc[0] = final_lb.iloc[0]
        
        for i in range(1, len(c)):
            if c.iloc[i] <= final_ub.iloc[i]:
                supertrend.iloc[i] = final_ub.iloc[i]
            else:
                supertrend.iloc[i] = final_lb.iloc[i]
        
        return supertrend

    def next(self):
        if len(self.data) < 2:
            return
        
        # Check for crossover
        if self.ema[-2] <= self.supertrend[-2] and self.ema[-1] > self.supertrend[-1]:
            # Buy signal: EMA crossed above Supertrend
            if not self.position:
                self.buy()
            self.trend = 1
        
        elif self.ema[-2] >= self.supertrend[-2] and self.ema[-1] < self.supertrend[-1]:
            # Sell signal: EMA crossed below Supertrend
            if self.position:
                self.position.close()
            self.trend = -1