"""
DS-TV Backtest Results: trend-line-odnac
============================================================

--- SPY ---
  Return                    -24.75%
  Buy & Hold Return         41.94%
  Max Drawdown              -29.74%
  Sharpe Ratio              -1.04
  Sortino Ratio             -1.27
  Calmar Ratio              -0.45
  Profit Factor             0.20
  Expectancy                -3.69%
  SQN                       -1.63
  # Trades                  7
  Win Rate                  28.57%
  Best Trade                5.18%
  Worst Trade               -13.26%
  Avg Trade                 -3.86%
  Exposure Time             71.20%
  Equity Final              75252.88$
  Equity Peak               106871.44$
  Avg Drawdown              -12.41%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        162 days 00:00:00
  Avg Trade Duration        74 days 00:00:00
  Ann. Return               -13.35%
  Ann. Volatility           12.82%

--- BTC ---
  Return                    -46.29%
  Buy & Hold Return         46.22%
  Max Drawdown              -52.94%
  Sharpe Ratio              -1.22
  Sortino Ratio             -1.20
  Calmar Ratio              -0.50
  Profit Factor             0.18
  Expectancy                -10.27%
  SQN                       -1.26
  # Trades                  7
  Win Rate                  28.57%
  Best Trade                11.85%
  Worst Trade               -51.91%
  Avg Trade                 -12.85%
  Exposure Time             39.95%
  Equity Final              53705.64$
  Equity Peak               106075.94$
  Avg Drawdown              -12.37%
  Max Drawdown Duration     673 days 00:00:00
  Max Trade Duration        81 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               -26.68%
  Ann. Volatility           21.84%

--- QQQ ---
  Return                    -39.74%
  Buy & Hold Return         42.67%
  Max Drawdown              -42.60%
  Sharpe Ratio              -1.37
  Sortino Ratio             -1.52
  Calmar Ratio              -0.53
  Profit Factor             0.13
  Expectancy                -6.87%
  SQN                       -2.32
  # Trades                  7
  Win Rate                  14.29%
  Best Trade                7.48%
  Worst Trade               -15.64%
  Avg Trade                 -7.18%
  Exposure Time             88.80%
  Equity Final              60259.79$
  Equity Peak               101354.22$
  Avg Drawdown              -15.00%
  Max Drawdown Duration     669 days 00:00:00
  Max Trade Duration        162 days 00:00:00
  Avg Trade Duration        93 days 00:00:00
  Ann. Return               -22.53%
  Ann. Volatility           16.51%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — trend-line-odnac
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Mode selection
    mode = 'Swing Confirm'
    
    # Swing Confirm Settings
    left_bars = 20
    right_bars = 7
    
    # Pivot High/Low Settings
    pivot_left = 20
    pivot_right = 3
    
    # Williams Fractal Settings
    fractal_bars = 2
    
    # Donchian Settings
    donchian_len = 20

    def init(self):
        self.high_pivots = []
        self.low_pivots = []
        self.high_lines = []
        self.low_lines = []
        self.prev_high_bar = None
        self.prev_high_price = None
        self.prev_low_bar = None
        self.prev_low_price = None
        self.active_high_line = None
        self.active_low_line = None

    def confirm_bearish(self, idx):
        right_bars = self.right_bars
        if idx < right_bars:
            return False
        
        last_bear_close = None
        renew_count = 0
        
        for i in range(right_bars):
            j = right_bars - 1 - i
            bar_idx = idx - j
            if bar_idx >= 0:
                if self.data.Close[bar_idx] < self.data.Open[bar_idx]:
                    if last_bear_close is None:
                        renew_count = 1
                        last_bear_close = self.data.Close[bar_idx]
                    elif self.data.Close[bar_idx] < last_bear_close:
                        renew_count += 1
                        last_bear_close = self.data.Close[bar_idx]
        
        consecutive_bears = 0
        max_consecutive = 0
        for i in range(1, right_bars + 1):
            bar_idx = idx - i
            if bar_idx >= 0:
                if self.data.Close[bar_idx] < self.data.Open[bar_idx]:
                    consecutive_bears += 1
                    max_consecutive = max(max_consecutive, consecutive_bears)
                else:
                    consecutive_bears = 0
        
        return renew_count >= 3 or max_consecutive >= 3

    def confirm_bullish(self, idx):
        right_bars = self.right_bars
        if idx < right_bars:
            return False
        
        last_bull_close = None
        renew_count = 0
        
        for i in range(right_bars):
            j = right_bars - 1 - i
            bar_idx = idx - j
            if bar_idx >= 0:
                if self.data.Close[bar_idx] > self.data.Open[bar_idx]:
                    if last_bull_close is None:
                        renew_count = 1
                        last_bull_close = self.data.Close[bar_idx]
                    elif self.data.Close[bar_idx] > last_bull_close:
                        renew_count += 1
                        last_bull_close = self.data.Close[bar_idx]
        
        consecutive_bulls = 0
        max_consecutive = 0
        for i in range(1, right_bars + 1):
            bar_idx = idx - i
            if bar_idx >= 0:
                if self.data.Close[bar_idx] > self.data.Open[bar_idx]:
                    consecutive_bulls += 1
                    max_consecutive = max(max_consecutive, consecutive_bulls)
                else:
                    consecutive_bulls = 0
        
        return renew_count >= 3 or max_consecutive >= 3

    def find_pivot_high_swing(self, idx):
        if idx < self.left_bars + self.right_bars:
            return None
        
        center_idx = idx - self.right_bars
        center_high = self.data.High[center_idx]
        
        for i in range(1, self.left_bars + 1):
            if center_idx - i >= 0 and self.data.High[center_idx - i] > center_high:
                return None
        
        for i in range(1, self.right_bars + 1):
            if center_idx + i < len(self.data) and self.data.High[center_idx + i] >= center_high:
                return None
        
        return center_high

    def find_pivot_low_swing(self, idx):
        if idx < self.left_bars + self.right_bars:
            return None
        
        center_idx = idx - self.right_bars
        center_low = self.data.Low[center_idx]
        
        for i in range(1, self.left_bars + 1):
            if center_idx - i >= 0 and self.data.Low[center_idx - i] < center_low:
                return None
        
        for i in range(1, self.right_bars + 1):
            if center_idx + i < len(self.data) and self.data.Low[center_idx + i] <= center_low:
                return None
        
        return center_low

    def find_pivot_high_pivot(self, idx):
        if idx < self.pivot_left + self.pivot_right:
            return None
        
        center_idx = idx - self.pivot_right
        center_high = self.data.High[center_idx]
        
        for i in range(1, self.pivot_left + 1):
            if center_idx - i >= 0 and self.data.High[center_idx - i] > center_high:
                return None
        
        for i in range(1, self.pivot_right + 1):
            if center_idx + i < len(self.data) and self.data.High[center_idx + i] >= center_high:
                return None
        
        return center_high

    def find_pivot_low_pivot(self, idx):
        if idx < self.pivot_left + self.pivot_right:
            return None
        
        center_idx = idx - self.pivot_right
        center_low = self.data.Low[center_idx]
        
        for i in range(1, self.pivot_left + 1):
            if center_idx - i >= 0 and self.data.Low[center_idx - i] < center_low:
                return None
        
        for i in range(1, self.pivot_right + 1):
            if center_idx + i < len(self.data) and self.data.Low[center_idx + i] <= center_low:
                return None
        
        return center_low

    def find_fractal_high(self, idx):
        center_idx = idx - self.fractal_bars
        if center_idx < self.fractal_bars or center_idx + self.fractal_bars >= len(self.data):
            return None
        
        center_high = self.data.High[center_idx]
        
        for i in range(1, self.fractal_bars + 1):
            if self.data.High[center_idx - i] >= center_high or self.data.High[center_idx + i] >= center_high:
                return None
        
        return center_high

    def find_fractal_low(self, idx):
        center_idx = idx - self.fractal_bars
        if center_idx < self.fractal_bars or center_idx + self.fractal_bars >= len(self.data):
            return None
        
        center_low = self.data.Low[center_idx]
        
        for i in range(1, self.fractal_bars + 1):
            if self.data.Low[center_idx - i] <= center_low or self.data.Low[center_idx + i] <= center_low:
                return None
        
        return center_low

    def find_donchian_high(self, idx):
        if idx < self.donchian_len + 1:
            return None
        
        if idx >= 1:
            max_high = max(self.data.High[idx - self.donchian_len:idx])
            if self.data.High[idx - 1] == max_high:
                return self.data.High[idx - 1]
        
        return None

    def find_donchian_low(self, idx):
        if idx < self.donchian_len + 1:
            return None
        
        if idx >= 1:
            min_low = min(self.data.Low[idx - self.donchian_len:idx])
            if self.data.Low[idx - 1] == min_low:
                return self.data.Low[idx - 1]
        
        return None

    def get_confirm_offset(self):
        if self.mode == 'Swing Confirm':
            return self.right_bars
        elif self.mode == 'Pivot High/Low':
            return self.pivot_right
        elif self.mode == 'Williams Fractal':
            return self.fractal_bars
        elif self.mode == 'Donchian':
            return 1
        return 0

    def trendline_price(self, x1, y1, x2, y2, x):
        if x2 == x1:
            return None
        return y1 + (y2 - y1) * (x - x1) / (x2 - x1)

    def is_clear_high(self, x1, y1, x2, y2, current_idx):
        span = x2 - x1 - 1
        if span <= 0:
            return True
        
        for i in range(1, span + 1):
            bar_idx = x2 - i
            line_at = self.trendline_price(x1, y1, x2, y2, bar_idx)
            if line_at is not None and bar_idx >= 0 and bar_idx < len(self.data):
                bar_high = self.data.High[bar_idx]
                if bar_high >= line_at:
                    return False
        
        return True

    def is_clear_low(self, x1, y1, x2, y2, current_idx):
        span = x2 - x1 - 1
        if span <= 0:
            return True
        
        for i in range(1, span + 1):
            bar_idx = x2 - i
            line_at = self.trendline_price(x1, y1, x2, y2, bar_idx)
            if line_at is not None and bar_idx >= 0 and bar_idx < len(self.data):
                bar_low = self.data.Low[bar_idx]
                if bar_low <= line_at:
                    return False
        
        return True

    def next(self):
        idx = len(self.data) - 1
        current_bar = idx - self.get_confirm_offset()
        
        ph_raw = None
        pl_raw = None
        is_valid_high = False
        is_valid_low = False
        
        if self.mode == 'Swing Confirm':
            ph_raw = self.find_pivot_high_swing(idx)
            pl_raw = self.find_pivot_low_swing(idx)
            if ph_raw is not None:
                is_valid_high = self.confirm_bearish(idx)
            if pl_raw is not None:
                is_valid_low = self.confirm_bullish(idx)
        
        elif self.mode == 'Pivot High/Low':
            ph_raw = self.find_pivot_high_pivot(idx)
            pl_raw = self.find_pivot_low_pivot(idx)
            is_valid_high = ph_raw is not None
            is_valid_low = pl_raw is not None
        
        elif self.mode == 'Williams Fractal':
            ph_raw = self.find_fractal_high(idx)
            pl_raw = self.find_fractal_low(idx)
            is_valid_high = ph_raw is not None
            is_valid_low = pl_raw is not None
        
        elif self.mode == 'Donchian':
            ph_raw = self.find_donchian_high(idx)
            pl_raw = self.find_donchian_low(idx)
            is_valid_high = ph_raw is not None
            is_valid_low = pl_raw is not None
        
        if is_valid_high and ph_raw is not None:
            if self.prev_high_bar is not None:
                if self.prev_high_price > ph_raw and self.is_clear_high(self.prev_high_bar, self.prev_high_price, current_bar, ph_raw, idx):
                    self.active_high_line = (self.prev_high_bar, self.prev_high_price, current_bar, ph_raw)
            
            self.prev_high_bar = current_bar
            self.prev_high_price = ph_raw
            
            if not self.position:
                self.buy()
        
        if is_valid_low and pl_raw is not None:
            if self.prev_low_bar is not None:
                if self.prev_low_price < pl_raw and self.is_clear_low(self.prev_low_bar, self.prev_low_price, current_bar, pl_raw, idx):
                    self.active_low_line = (self.prev_low_bar, self.prev_low_price, current_bar, pl_raw)
            
            self.prev_low_bar = current_bar
            self.prev_low_price = pl_raw
            
            if self.position:
                self.sell()
        
        if self.active_high_line is not None:
            x1, y1, x2, y2 = self.active_high_line
            line_now = self.trendline_price(x1, y1, x2, y2, idx)
            if line_now is not None:
                if self.data.Close[-1] > line_now:
                    self.active_high_line = None
                    if self.position:
                        self.sell()
        
        if self.active_low_line is not None:
            x1, y1, x2, y2 = self.active_low_line
            line_now = self.trendline_price(x1, y1, x2, y2, idx)
            if line_now is not None:
                if self.data.Close[-1] < line_now:
                    self.active_low_line = None
                    if not self.position:
                        self.buy()