"""
DS-TV Backtest Results: volatility-regime-supertrend-seerquant
============================================================

--- SPY ---
  Return                    -12.73%
  Buy & Hold Return         25.73%
  Max Drawdown              -21.18%
  Sharpe Ratio              -0.58
  Sortino Ratio             -0.74
  Calmar Ratio              -0.31
  Profit Factor             0.51
  Expectancy                -0.93%
  SQN                       -0.99
  # Trades                  12
  Win Rate                  33.33%
  Best Trade                7.35%
  Worst Trade               -3.55%
  Avg Trade                 -0.98%
  Exposure Time             56.60%
  Equity Final              87269.79$
  Equity Peak               110713.95$
  Avg Drawdown              -6.96%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        83 days 00:00:00
  Avg Trade Duration        35 days 00:00:00
  Ann. Return               -6.63%
  Ann. Volatility           11.42%

--- BTC ---
  Return                    39.51%
  Buy & Hold Return         25.07%
  Max Drawdown              -23.80%
  Sharpe Ratio              0.52
  Sortino Ratio             0.95
  Calmar Ratio              0.76
  Profit Factor             1.72
  Expectancy                3.48%
  SQN                       0.50
  # Trades                  9
  Win Rate                  33.33%
  Best Trade                40.04%
  Worst Trade               -12.38%
  Avg Trade                 2.26%
  Exposure Time             72.09%
  Equity Final              139512.06$
  Equity Peak               146660.02$
  Avg Drawdown              -7.04%
  Max Drawdown Duration     176 days 00:00:00
  Max Trade Duration        151 days 00:00:00
  Avg Trade Duration        59 days 00:00:00
  Ann. Return               18.09%
  Ann. Volatility           34.86%

--- QQQ ---
  Return                    -13.27%
  Buy & Hold Return         30.29%
  Max Drawdown              -23.38%
  Sharpe Ratio              -0.49
  Sortino Ratio             -0.61
  Calmar Ratio              -0.30
  Profit Factor             0.66
  Expectancy                -0.98%
  SQN                       -0.54
  # Trades                  10
  Win Rate                  20.00%
  Best Trade                17.83%
  Worst Trade               -5.74%
  Avg Trade                 -1.17%
  Exposure Time             56.20%
  Equity Final              86730.82$
  Equity Peak               113197.81$
  Avg Drawdown              -5.85%
  Max Drawdown Duration     167 days 00:00:00
  Max Trade Duration        153 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               -6.92%
  Ann. Volatility           14.20%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volatility-regime-supertrend-seerquant
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLen = 14
    compMult = 2.0
    expMult = 3.5
    speed = 2
    bbLen = 50
    rankLen = 100
    compLevel = 30.0
    expLevel = 70.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate Bollinger Bands basis and deviation for regime detection
        self.bb_basis = self.I(pta.sma, close, length=self.bbLen)
        self.bb_dev = self.I(lambda: close.rolling(self.bbLen).std())
        
        # Bandwidth calculation
        self.bandwidth = self.I(lambda: np.where(
            self.bb_basis != 0,
            (self.bb_dev * 2.0) / self.bb_basis,
            0.0
        ))
        
        # Highest and lowest bandwidth over rankLen period
        self.bw_high = self.I(lambda: pd.Series(self.bandwidth).rolling(self.rankLen).max())
        self.bw_low = self.I(lambda: pd.Series(self.bandwidth).rolling(self.rankLen).min())
        
        # ATR calculation
        self.atr = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        # HL2 (midpoint)
        self.hl2 = self.I(lambda: (high + low) / 2.0)
        
        # Store bands and direction
        self.upper_band = None
        self.lower_band = None
        self.dir = 1
        self.prev_dir = 1
        
    def next(self):
        # Current index
        idx = len(self.data) - 1
        
        # Get current values safely
        if idx < self.rankLen or self.atr[-1] is None:
            return
            
        bw_high = self.bw_high[-1] if self.bw_high[-1] is not None else 0
        bw_low = self.bw_low[-1] if self.bw_low[-1] is not None else 0
        bw_range = bw_high - bw_low
        
        bandwidth_val = self.bandwidth[-1] if self.bandwidth[-1] is not None else 50.0
        
        if bw_range != 0:
            bw_rank = (bandwidth_val - bw_low) / bw_range * 100.0
        else:
            bw_rank = 50.0
        
        # Regime classification
        is_compression = bw_rank < self.compLevel
        is_expansion = bw_rank > self.expLevel
        
        # Regime-dependent multiplier
        if is_compression:
            regime_mult = self.compMult
        elif is_expansion:
            regime_mult = self.expMult
        else:
            regime_mult = self.compMult + (self.expMult - self.compMult) * ((bw_rank - self.compLevel) / (self.expLevel - self.compLevel))
        
        # Smooth multiplier using EMA (approximated)
        if idx == 0 or self.upper_band is None:
            smooth_mult = regime_mult
        else:
            smooth_mult = 0.8 * self.upper_band_mult_prev + 0.2 * regime_mult if hasattr(self, 'upper_band_mult_prev') else regime_mult
        
        self.upper_band_mult_prev = smooth_mult
        
        # Calculate raw bands
        src = self.hl2[-1]
        atr_val = self.atr[-1] if self.atr[-1] is not None else 0
        upper_raw = src + smooth_mult * atr_val
        lower_raw = src - smooth_mult * atr_val
        
        # Speed control
        speed_alpha = self.speed / 10.0
        
        # Initialize or update bands
        if self.upper_band is None:
            self.upper_band = upper_raw
            self.lower_band = lower_raw
        else:
            # Standard supertrend trailing logic
            upper_trail = upper_raw if (upper_raw < self.upper_band or self.data.Close[-2] > self.upper_band) else self.upper_band
            lower_trail = lower_raw if (lower_raw > self.lower_band or self.data.Close[-2] < self.lower_band) else self.lower_band
            
            # Apply speed blending
            self.upper_band = self.upper_band + speed_alpha * (upper_trail - self.upper_band)
            self.lower_band = self.lower_band + speed_alpha * (lower_trail - self.lower_band)
        
        # Determine direction
        close_val = self.data.Close[-1]
        if close_val > self.upper_band:
            self.dir = 1
        elif close_val < self.lower_band:
            self.dir = -1
        
        # Supertrend line
        st = self.lower_band if self.dir == 1 else self.upper_band
        
        # Signals
        is_bull = self.dir == 1
        is_bear = self.dir == -1
        long_sig = is_bull and self.prev_dir == -1
        short_sig = is_bear and self.prev_dir == 1
        
        # Trading logic
        if long_sig:
            if self.position.is_short:
                self.position.close()
            self.buy()
        elif short_sig:
            if self.position.is_long:
                self.position.close()
            self.sell()
        
        self.prev_dir = self.dir