"""
DS-TV Backtest Results: volume-bubbles-pro-v73-r2d2
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         40.20%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         0.29%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         45.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volume-bubbles-pro-v73-r2d2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Z-Score Detection Parameters
    volume_ma_length = 50
    z_score_threshold = 2.0
    
    # VSA Parameters
    atr_length = 14
    enable_absorption = True
    
    # Offset Multiplier
    atr_offset_mult = 0.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate Volume SMA and StDev
        self.vol_sma = self.I(pta.sma, volume, length=self.volume_ma_length)
        self.vol_stdev = self.I(
            lambda v=volume: v.rolling(window=self.volume_ma_length).std()
        )
        
        # Calculate Z-Score
        def calc_zscore(v=volume, sma=None, stdev=None):
            if sma is None or stdev is None:
                return pd.Series(0, index=v.index)
            result = pd.Series(0.0, index=v.index)
            for i in range(len(v)):
                if stdev.iloc[i] > 0:
                    result.iloc[i] = (v.iloc[i] - sma.iloc[i]) / stdev.iloc[i]
            return result
        
        self.z_score = self.I(calc_zscore)
        
        # Calculate ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_length)
        
        # Calculate Spread
        def calc_spread(h=high, l=low):
            return h - l
        
        self.spread = self.I(calc_spread)
        
        # Calculate Close Position (0.0 to 1.0)
        def calc_close_pos(h=high, l=low, c=close):
            result = pd.Series(0.5, index=c.index)
            for i in range(len(c)):
                if h.iloc[i] - l.iloc[i] > 0:
                    result.iloc[i] = (c.iloc[i] - l.iloc[i]) / (h.iloc[i] - l.iloc[i])
                else:
                    result.iloc[i] = 0.5
            return result
        
        self.close_pos = self.I(calc_close_pos)
        
        # Calculate Delta Volume Approximation
        def calc_delta_vol(v=volume, cp=None):
            if cp is None:
                return pd.Series(0, index=v.index)
            estimated_buy = v * cp
            estimated_sell = v * (1.0 - cp)
            return estimated_buy - estimated_sell
        
        self.delta_vol = self.I(calc_delta_vol)

    def next(self):
        # Safety check for sufficient data
        if len(self.data) < max(self.volume_ma_length, self.atr_length):
            return
        
        # Get current values
        z_score = self.z_score[-1]
        atr_val = self.atr[-1]
        spread = self.spread[-1]
        close_pos = self.close_pos[-1]
        delta_vol = self.delta_vol[-1]
        volume = self.data.Volume[-1]
        
        # Validate indicator values
        if z_score is None or pd.isna(z_score) or atr_val is None or pd.isna(atr_val):
            return
        
        if pd.isna(spread) or pd.isna(close_pos) or pd.isna(delta_vol):
            return
        
        # VSA Classifications
        is_high_volume = z_score >= self.z_score_threshold
        is_tight_spread = spread < (atr_val * 0.5)
        is_neutral_churn = close_pos >= 0.33 and close_pos <= 0.66
        is_absorption = self.enable_absorption and is_high_volume and (is_tight_spread or is_neutral_churn)
        
        # Trade Signals
        is_buy = (delta_vol > 0) and (close_pos > 0.5) and not is_absorption
        is_sell = (delta_vol < 0) and (close_pos < 0.5) and not is_absorption
        
        # Simple buy/sell logic
        # Buy on whale buy activity with positive delta
        if is_high_volume and is_buy:
            if not self.position:
                self.buy()
        
        # Sell on whale sell activity with negative delta
        elif is_high_volume and is_sell:
            if self.position:
                self.position.close()
        
        # Exit on absorption signals (potential reversals)
        elif is_absorption:
            if self.position:
                self.position.close()