"""
DS-TV Backtest Results: yaduvansi-v1-price-action-yaduvansi-122-guardeer
============================================================

--- SPY ---
  Return                    -39.93%
  Buy & Hold Return         17.90%
  Max Drawdown              -43.04%
  Sharpe Ratio              -1.94
  Sortino Ratio             -1.75
  Calmar Ratio              -0.53
  Profit Factor             0.52
  Expectancy                -0.34%
  SQN                       -2.12
  # Trades                  146
  Win Rate                  43.84%
  Best Trade                5.25%
  Worst Trade               -10.45%
  Avg Trade                 -0.35%
  Exposure Time             59.20%
  Equity Final              60070.59$
  Equity Peak               102991.28$
  Avg Drawdown              -11.16%
  Max Drawdown Duration     418 days 00:00:00
  Max Trade Duration        12 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -22.65%
  Ann. Volatility           11.67%

--- BTC ---
  Return                    -14.06%
  Buy & Hold Return         17.39%
  Max Drawdown              -24.16%
  Sharpe Ratio              -0.40
  Sortino Ratio             -0.55
  Calmar Ratio              -0.30
  Profit Factor             0.75
  Expectancy                -0.49%
  SQN                       -0.59
  # Trades                  45
  Win Rate                  48.89%
  Best Trade                16.65%
  Worst Trade               -12.14%
  Avg Trade                 -0.61%
  Exposure Time             13.68%
  Equity Final              85935.23$
  Equity Peak               101846.21$
  Avg Drawdown              -8.78%
  Max Drawdown Duration     524 days 00:00:00
  Max Trade Duration        5 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -7.29%
  Ann. Volatility           18.06%

--- QQQ ---
  Return                    -43.21%
  Buy & Hold Return         22.08%
  Max Drawdown              -46.63%
  Sharpe Ratio              -1.88
  Sortino Ratio             -1.66
  Calmar Ratio              -0.53
  Profit Factor             0.56
  Expectancy                -0.36%
  SQN                       -2.22
  # Trades                  145
  Win Rate                  44.83%
  Best Trade                5.29%
  Worst Trade               -10.66%
  Avg Trade                 -0.37%
  Exposure Time             59.60%
  Equity Final              56787.72$
  Equity Peak               104943.95$
  Avg Drawdown              -9.90%
  Max Drawdown Duration     420 days 00:00:00
  Max Trade Duration        12 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -24.81%
  Ann. Volatility           13.20%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — yaduvansi-v1-price-action-yaduvansi-122-guardeer
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    internal_lookback = 5
    swing_lookback = 50
    atr_length = 200

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate pivot highs and lows for internal structure
        self.internal_high = self.I(
            lambda: high.rolling(self.internal_lookback * 2 + 1, center=True).max()
        )
        self.internal_low = self.I(
            lambda: low.rolling(self.internal_lookback * 2 + 1, center=True).min()
        )
        
        # Calculate pivot highs and lows for swing structure
        self.swing_high = self.I(
            lambda: high.rolling(self.swing_lookback * 2 + 1, center=True).max()
        )
        self.swing_low = self.I(
            lambda: low.rolling(self.swing_lookback * 2 + 1, center=True).min()
        )
        
        # ATR for volatility measurement
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_length)
        
        # Track trend states
        self.internal_trend = 0
        self.swing_trend = 0
        
    def next(self):
        if len(self.data) < self.swing_lookback * 2 + 2:
            return
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        current_internal_high = self.internal_high[-1]
        current_internal_low = self.internal_low[-1]
        current_swing_high = self.swing_high[-1]
        current_swing_low = self.swing_low[-1]
        
        # Internal structure bullish break of structure
        if current_internal_high != 0 and close > current_internal_high:
            if self.internal_trend < 0:
                # Change of Character
                self.buy()
            elif self.internal_trend == 0:
                # Break of Structure
                self.buy()
            self.internal_trend = 1
        
        # Internal structure bearish break of structure
        if current_internal_low != 0 and close < current_internal_low:
            if self.internal_trend > 0:
                # Change of Character
                self.sell()
            elif self.internal_trend == 0:
                # Break of Structure
                self.sell()
            self.internal_trend = -1
        
        # Swing structure bullish break of structure
        if current_swing_high != 0 and close > current_swing_high:
            if self.swing_trend < 0:
                # Swing Change of Character
                self.buy()
            elif self.swing_trend == 0:
                # Swing Break of Structure
                self.buy()
            self.swing_trend = 1
        
        # Swing structure bearish break of structure
        if current_swing_low != 0 and close < current_swing_low:
            if self.swing_trend > 0:
                # Swing Change of Character
                self.sell()
            elif self.swing_trend == 0:
                # Swing Break of Structure
                self.sell()
            self.swing_trend = -1
        
        # Fair Value Gap detection (simplified bullish FVG)
        if len(self.data) >= 3:
            h2 = self.data.High[-3]
            l2 = self.data.Low[-3]
            c1 = self.data.Close[-2]
            h_curr = self.data.High[-1]
            
            # Bullish FVG: current low > previous candle close and previous candle close > 2 candles ago high
            if h_curr > c1 > h2:
                if self.swing_trend >= 0:
                    self.buy()
        
        # Fair Value Gap detection (simplified bearish FVG)
        if len(self.data) >= 3:
            l2 = self.data.Low[-3]
            c1 = self.data.Close[-2]
            l_curr = self.data.Low[-1]
            
            # Bearish FVG: current high < previous candle close and previous candle close < 2 candles ago low
            if l_curr < c1 < l2:
                if self.swing_trend <= 0:
                    self.sell()
        
        # Exit on reversal signals
        if self.position.is_long:
            if self.internal_trend < 0 and self.swing_trend < 0:
                self.position.close()
        
        if self.position.is_short:
            if self.internal_trend > 0 and self.swing_trend > 0:
                self.position.close()


if __name__ == "__main__":
    bt = Backtest(
        data=pd.read_csv("data.csv", index_col=0, parse_dates=True),
        strategy=TvStrategy,
        cash=10000,
        commission=0.002,
    )
    
    results = bt.run()
    print(results)
    bt.plot()