"""
DS-TV Backtest Results: 2b2t-123-on-closing-basis
============================================================

--- SPY ---
  Return                    -23.38%
  Buy & Hold Return         38.66%
  Max Drawdown              -33.80%
  Sharpe Ratio              -0.90
  Sortino Ratio             -1.09
  Calmar Ratio              -0.37
  Profit Factor             0.63
  Expectancy                -0.71%
  SQN                       -0.82
  # Trades                  31
  Win Rate                  45.16%
  Best Trade                8.57%
  Worst Trade               -14.53%
  Avg Trade                 -0.81%
  Exposure Time             88.20%
  Equity Final              76615.89$
  Equity Peak               115738.55$
  Avg Drawdown              -4.65%
  Max Drawdown Duration     553 days 00:00:00
  Max Trade Duration        75 days 00:00:00
  Avg Trade Duration        21 days 00:00:00
  Ann. Return               -12.56%
  Ann. Volatility           14.03%

--- BTC ---
  Return                    18.24%
  Buy & Hold Return         37.68%
  Max Drawdown              -24.62%
  Sharpe Ratio              0.30
  Sortino Ratio             0.53
  Calmar Ratio              0.35
  Profit Factor             1.21
  Expectancy                0.97%
  SQN                       0.26
  # Trades                  17
  Win Rate                  41.18%
  Best Trade                42.78%
  Worst Trade               -17.60%
  Avg Trade                 0.03%
  Exposure Time             43.37%
  Equity Final              118239.29$
  Equity Peak               118944.63$
  Avg Drawdown              -7.92%
  Max Drawdown Duration     449 days 00:00:00
  Max Trade Duration        51 days 00:00:00
  Avg Trade Duration        19 days 00:00:00
  Ann. Return               8.73%
  Ann. Volatility           28.65%

--- QQQ ---
  Return                    -44.30%
  Buy & Hold Return         39.38%
  Max Drawdown              -47.40%
  Sharpe Ratio              -1.65
  Sortino Ratio             -1.67
  Calmar Ratio              -0.54
  Profit Factor             0.41
  Expectancy                -1.72%
  SQN                       -1.44
  # Trades                  29
  Win Rate                  20.69%
  Best Trade                14.70%
  Worst Trade               -21.44%
  Avg Trade                 -1.94%
  Exposure Time             94.80%
  Equity Final              55702.30$
  Equity Peak               103193.79$
  Avg Drawdown              -25.55%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        76 days 00:00:00
  Avg Trade Duration        24 days 00:00:00
  Ann. Return               -25.54%
  Ann. Volatility           15.47%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — 2b2t-123-on-closing-basis
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLen = 14
    atrMult = 1.5
    sweepTol = 1.0
    rrRatio = 2.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.atr_values = self.I(pta.atr, high, low, close, length=self.atrLen)
        self.atr_adjusted = self.I(lambda: self.atr_values * self.atrMult if self.atr_values is not None else pd.Series(0, index=close.index))
        
        self.dir = 1
        self.ch = self.data.High[0]
        self.ch_bar = 0
        self.cl = self.data.Low[0]
        self.cl_bar = 0
        
        self.dir_c = 1
        self.ch_c = self.data.Close[0]
        self.ch_bar_c = 0
        self.cl_c = self.data.Close[0]
        self.cl_bar_c = 0
        
        self.last_ph = None
        self.last_ph_bar = None
        self.prev_ph = None
        self.prev_ph_bar = None
        
        self.last_pl = None
        self.last_pl_bar = None
        self.prev_pl = None
        self.prev_pl_bar = None
        
        self.active_2t = False
        self.sweep_2t_mode = False
        self.sweep_2t_high = None
        
        self.active_2b = False
        self.sweep_2b_mode = False
        self.sweep_2b_low = None
        
        self.last_ph_c = None
        self.last_ph_bar_c = None
        self.prev_ph_c = None
        self.prev_ph_bar_c = None
        
        self.last_pl_c = None
        self.last_pl_bar_c = None
        self.prev_pl_c = None
        self.prev_pl_bar_c = None
        
        self.active_123b = False
        self.trig_123b = None
        self.sl_123b = None
        self.start_123b = None
        
        self.active_123s = False
        self.trig_123s = None
        self.sl_123s = None
        self.start_123s = None
        
        self.trade_dir = 0
        self.stop_loss = None
        self.target_price = None
        self.entry_price = None

    def next(self):
        idx = len(self.data) - 1
        atr_val = self.atr_adjusted[-1] if not np.isnan(self.atr_adjusted[-1]) else 0
        
        new_ph = False
        new_pl = False
        
        if self.dir == 1:
            if self.data.High[idx] > self.ch:
                self.ch = self.data.High[idx]
                self.ch_bar = idx
            if self.data.Close[idx] < self.ch - atr_val:
                self.dir = -1
                new_ph = True
                self.cl = self.data.Low[idx]
                self.cl_bar = idx
        else:
            if self.data.Low[idx] < self.cl:
                self.cl = self.data.Low[idx]
                self.cl_bar = idx
            if self.data.Close[idx] > self.cl + atr_val:
                self.dir = 1
                new_pl = True
                self.ch = self.data.High[idx]
                self.ch_bar = idx
        
        new_ph_c = False
        new_pl_c = False
        
        if self.dir_c == 1:
            if self.data.Close[idx] > self.ch_c:
                self.ch_c = self.data.Close[idx]
                self.ch_bar_c = idx
            if self.data.Close[idx] < self.ch_c - atr_val:
                self.dir_c = -1
                new_ph_c = True
                self.cl_c = self.data.Close[idx]
                self.cl_bar_c = idx
        else:
            if self.data.Close[idx] < self.cl_c:
                self.cl_c = self.data.Close[idx]
                self.cl_bar_c = idx
            if self.data.Close[idx] > self.cl_c + atr_val:
                self.dir_c = 1
                new_pl_c = True
                self.ch_c = self.data.Close[idx]
                self.ch_bar_c = idx
        
        if new_ph:
            self.prev_ph = self.last_ph
            self.prev_ph_bar = self.last_ph_bar
            self.last_ph = self.ch
            self.last_ph_bar = self.ch_bar
            self.active_2t = True
            self.sweep_2t_mode = False
            self.sweep_2t_high = None
        
        if new_pl:
            self.prev_pl = self.last_pl
            self.prev_pl_bar = self.last_pl_bar
            self.last_pl = self.cl
            self.last_pl_bar = self.cl_bar
            self.active_2b = True
            self.sweep_2b_mode = False
            self.sweep_2b_low = None
        
        if new_ph_c:
            self.prev_ph_c = self.last_ph_c
            self.prev_ph_bar_c = self.last_ph_bar_c
            self.last_ph_c = self.ch_c
            self.last_ph_bar_c = self.ch_bar_c
        
        if new_pl_c:
            self.prev_pl_c = self.last_pl_c
            self.prev_pl_bar_c = self.last_pl_bar_c
            self.last_pl_c = self.cl_c
            self.last_pl_bar_c = self.cl_bar_c
        
        if new_pl_c and self.prev_pl_c is not None and self.last_ph_c is not None:
            if self.last_ph_bar_c > self.prev_pl_bar_c and self.last_ph_bar_c < self.last_pl_bar_c:
                if self.last_pl_c > self.prev_pl_c:
                    self.active_123b = True
                    self.trig_123b = self.last_ph_c
                    self.sl_123b = self.last_pl_c
                    self.start_123b = self.last_ph_bar_c
        
        if new_ph_c and self.prev_ph_c is not None and self.last_pl_c is not None:
            if self.last_pl_bar_c > self.prev_ph_bar_c and self.last_pl_bar_c < self.last_ph_bar_c:
                if self.last_ph_c < self.prev_ph_c:
                    self.active_123s = True
                    self.trig_123s = self.last_pl_c
                    self.sl_123s = self.last_ph_c
                    self.start_123s = self.last_pl_bar_c
        
        trigger_2b = False
        trigger_2t = False
        trigger_123b = False
        trigger_123s = False
        
        tol = self.sweepTol / 100.0
        
        if self.active_2b and self.last_pl is not None and idx > self.last_pl_bar:
            if self.data.Low[idx] < self.last_pl:
                self.sweep_2b_mode = True
                if self.sweep_2b_low is None:
                    self.sweep_2b_low = self.data.Low[idx]
                else:
                    self.sweep_2b_low = min(self.sweep_2b_low, self.data.Low[idx])
            
            if self.sweep_2b_mode and self.last_pl > 0:
                if ((self.last_pl - self.sweep_2b_low) / self.last_pl) > tol:
                    self.active_2b = False
                    self.sweep_2b_mode = False
            
            if self.sweep_2b_mode and self.data.Close[idx] > self.last_pl:
                trigger_2b = True
                self.active_2b = False
                self.sweep_2b_mode = False
        
        if self.active_2t and self.last_ph is not None and idx > self.last_ph_bar:
            if self.data.High[idx] > self.last_ph:
                self.sweep_2t_mode = True
                if self.sweep_2t_high is None:
                    self.sweep_2t_high = self.data.High[idx]
                else:
                    self.sweep_2t_high = max(self.sweep_2t_high, self.data.High[idx])
            
            if self.sweep_2t_mode and self.last_ph > 0:
                if ((self.sweep_2t_high - self.last_ph) / self.last_ph) > tol:
                    self.active_2t = False
                    self.sweep_2t_mode = False
            
            if self.sweep_2t_mode and self.data.Close[idx] < self.last_ph:
                trigger_2t = True
                self.active_2t = False
                self.sweep_2t_mode = False
        
        if self.active_123b and self.data.Close[idx] > self.trig_123b:
            trigger_123b = True
            self.active_123b = False
        
        if self.active_123s and self.data.Close[idx] < self.trig_123s:
            trigger_123s = True
            self.active_123s = False
        
        if trigger_2b:
            self.trade_dir = 1
            self.stop_loss = self.sweep_2b_low
            self.entry_price = self.data.Close[idx]
            self.target_price = self.entry_price + ((self.entry_price - self.stop_loss) * self.rrRatio)
            if not self.position:
                self.buy()
        
        if trigger_2t:
            self.trade_dir = -1
            self.stop_loss = self.sweep_2t_high
            self.entry_price = self.data.Close[idx]
            self.target_price = self.entry_price - ((self.stop_loss - self.entry_price) * self.rrRatio)
            if self.position:
                self.sell()
        
        if trigger_123b:
            self.trade_dir = 1
            self.stop_loss = self.sl_123b
            self.entry_price = self.data.Close[idx]
            self.target_price = self.entry_price + ((self.entry_price - self.stop_loss) * self.rrRatio)
            if not self.position:
                self.buy()
        
        if trigger_123s:
            self.trade_dir = -1
            self.stop_loss = self.sl_123s
            self.entry_price = self.data.Close[idx]
            self.target_price = self.entry_price - ((self.stop_loss - self.entry_price) * self.rrRatio)
            if self.position:
                self.sell()
        
        if self.position and self.trade_dir == 1:
            if self.data.Low[idx] <= self.stop_loss or self.data.High[idx] >= self.target_price:
                self.sell()
                self.trade_dir = 0
        
        if self.position and self.trade_dir == -1:
            if self.data.High[idx] >= self.stop_loss or self.data.Low[idx] <= self.target_price:
                self.buy()
                self.trade_dir = 0


if __name__ == "__main__":
    bt = Backtest(pd.read_csv("data.csv", parse_dates=True, index_col=0), TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()