"""
DS-TV Backtest Results: atr-value-box
============================================================

--- SPY ---
  Return                    -36.00%
  Buy & Hold Return         38.66%
  Max Drawdown              -42.89%
  Sharpe Ratio              -2.07
  Sortino Ratio             -2.54
  Calmar Ratio              -0.47
  Profit Factor             0.49
  Expectancy                -0.23%
  SQN                       -2.46
  # Trades                  185
  Win Rate                  30.81%
  Best Trade                11.61%
  Worst Trade               -2.04%
  Avg Trade                 -0.24%
  Exposure Time             42.60%
  Equity Final              64002.12$
  Equity Peak               112067.03$
  Avg Drawdown              -13.97%
  Max Drawdown Duration     271 days 00:00:00
  Max Trade Duration        41 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -20.14%
  Ann. Volatility           9.75%

--- BTC ---
  Return                    111.44%
  Buy & Hold Return         37.68%
  Max Drawdown              -19.33%
  Sharpe Ratio              1.06
  Sortino Ratio             2.50
  Calmar Ratio              2.34
  Profit Factor             94.42
  Expectancy                21.52%
  SQN                       1.05
  # Trades                  6
  Win Rate                  83.33%
  Best Trade                126.84%
  Worst Trade               -1.38%
  Avg Trade                 15.05%
  Exposure Time             79.21%
  Equity Final              211435.96$
  Equity Peak               218583.92$
  Avg Drawdown              -4.17%
  Max Drawdown Duration     238 days 00:00:00
  Max Trade Duration        572 days 00:00:00
  Avg Trade Duration        97 days 00:00:00
  Ann. Return               45.33%
  Ann. Volatility           42.64%

--- QQQ ---
  Return                    -55.47%
  Buy & Hold Return         39.38%
  Max Drawdown              -61.25%
  Sharpe Ratio              -2.80
  Sortino Ratio             -2.50
  Calmar Ratio              -0.55
  Profit Factor             0.54
  Expectancy                -0.26%
  SQN                       -3.47
  # Trades                  302
  Win Rate                  33.11%
  Best Trade                7.32%
  Worst Trade               -3.09%
  Avg Trade                 -0.26%
  Exposure Time             76.20%
  Equity Final              44531.38$
  Equity Peak               113537.34$
  Avg Drawdown              -13.38%
  Max Drawdown Duration     521 days 00:00:00
  Max Trade Duration        80 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -33.48%
  Ann. Volatility           11.94%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — atr-value-box
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atr_length = 14
    atr_threshold = 2.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_length)
        self.atr_percent = self.I(lambda: (self.atr / close * 100) if self.atr is not None else pd.Series(0, index=close.index))

    def next(self):
        if len(self.data) < self.atr_length + 1:
            return
        
        current_atr_percent = self.atr_percent[-1]
        
        if current_atr_percent > self.atr_threshold and not self.position:
            self.buy()
        elif current_atr_percent < self.atr_threshold and self.position:
            self.sell()