"""
DS-TV Backtest Results: atr-credit-spread-strike-guide
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — atr-credit-spread-strike-guide
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atr_length = 20
    atr_multiple = 3

    def init(self):
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        close = pd.Series(self.data.Close)
        
        # Calculate ATR
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_length)
        
        # Store close for calculations
        self.close_series = close

    def next(self):
        # Get current values
        if len(self.data) < self.atr_length:
            return
        
        current_close = self.data.Close[-1]
        current_atr = self.atr[-1]
        
        if current_atr is None or np.isnan(current_atr):
            return
        
        # Calculate ATR percentage
        atr_pct = (current_atr / current_close) * 100.0
        distance_pct = atr_pct * self.atr_multiple
        
        # Calculate levels
        lower_level = current_close * (1.0 - distance_pct / 100.0)
        upper_level = current_close * (1.0 + distance_pct / 100.0)
        
        # Trading logic: buy near lower level, sell near upper level
        if self.data.Close[-1] <= lower_level and not self.position:
            self.buy()
        elif self.data.Close[-1] >= upper_level and self.position:
            self.sell()


if __name__ == "__main__":
    # Load data
    data = pd.read_csv("data.csv", parse_dates=True, index_col=0)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()