"""
DS-TV Backtest Results: atr-stop-distance-ticks-mintick-based
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — atr-stop-distance-ticks-mintick-based
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLen = 20
    mult = 1.5
    roundMode = "Round"

    def init(self):
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        close = pd.Series(self.data.Close)
        
        # Calculate ATR in price units
        atr_result = self.I(pta.atr, high, low, close, length=self.atrLen)
        
        # Store ATR for use in next()
        self.atr_price = atr_result
        
        # Mintick assumption (for stocks typically 0.01)
        self.mintick = 0.01

    def next(self):
        if len(self.atr_price) < self.atrLen:
            return
        
        # Get current ATR value
        atr_val = self.atr_price[-1]
        
        if atr_val is None or np.isnan(atr_val):
            return
        
        # Convert ATR to ticks using mintick
        raw_ticks = (atr_val / self.mintick) * self.mult
        
        # Apply rounding based on roundMode
        if self.roundMode == "Ceil":
            stop_ticks = int(np.ceil(raw_ticks))
        elif self.roundMode == "Floor":
            stop_ticks = int(np.floor(raw_ticks))
        else:  # "Round"
            stop_ticks = int(np.round(raw_ticks))
        
        # Simple trading logic: buy when stop distance is low, sell when high
        if stop_ticks < 10:
            if not self.position:
                self.buy()
        elif stop_ticks > 20:
            if self.position:
                self.sell()