"""
DS-TV Backtest Results: atradx-quiet-dashboard-vwap-slope
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — atradx-quiet-dashboard-vwap-slope
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atr_len = 14
    adx_len = 14
    ma_type = "SMA"
    use_atr_quartile_gate = False
    use_adx_gate = True
    adx_gate_max = 20.0
    vwap_slope_lookback = 3
    vwap_flat_ticks = 2.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # ATR and ADX
        self.atr_pts = self.I(lambda: pta.atr(high, low, close, length=self.atr_len) or pd.Series(0.0, index=close.index))
        self.atr_pct = self.I(lambda: self.atr_pts / close)
        
        adx_result = self.I(lambda: pta.adx(high, low, close, length=self.adx_len) or pd.DataFrame(0.0, index=close.index, columns=['ADX_14']))
        self.adx_val = self.I(lambda: adx_result.iloc[:, 0] if isinstance(adx_result, pd.DataFrame) else adx_result)
        
        # 1H and 4H averages (using rolling means)
        tf_seconds = 60
        len_1h = max(1, int(round(3600 / tf_seconds)))
        len_4h = max(1, int(round(14400 / tf_seconds)))
        
        self.avg_1h_pts = self.I(lambda: self.atr_pts.rolling(window=len_1h).mean() or pd.Series(0.0, index=close.index))
        self.avg_4h_pts = self.I(lambda: self.atr_pts.rolling(window=len_4h).mean() or pd.Series(0.0, index=close.index))
        
        self.avg_1h_pct = self.I(lambda: self.atr_pct.rolling(window=len_1h).mean() or pd.Series(0.0, index=close.index))
        self.avg_4h_pct = self.I(lambda: self.atr_pct.rolling(window=len_4h).mean() or pd.Series(0.0, index=close.index))
        
        # Percentiles for 1H
        self.q25_1h = self.I(lambda: self.atr_pct.rolling(window=len_1h).quantile(0.25) or pd.Series(0.0, index=close.index))
        self.q50_1h = self.I(lambda: self.atr_pct.rolling(window=len_1h).quantile(0.50) or pd.Series(0.0, index=close.index))
        self.q75_1h = self.I(lambda: self.atr_pct.rolling(window=len_1h).quantile(0.75) or pd.Series(0.0, index=close.index))
        
        # Percentiles for 4H
        self.q25_4h = self.I(lambda: self.atr_pct.rolling(window=len_4h).quantile(0.25) or pd.Series(0.0, index=close.index))
        self.q50_4h = self.I(lambda: self.atr_pct.rolling(window=len_4h).quantile(0.50) or pd.Series(0.0, index=close.index))
        self.q75_4h = self.I(lambda: self.atr_pct.rolling(window=len_4h).quantile(0.75) or pd.Series(0.0, index=close.index))
        
        # 4D averages and percentiles (using 4-bar rolling)
        len_4d = 4
        self.avg_4d_pts = self.I(lambda: self.atr_pts.rolling(window=len_4d).mean() or pd.Series(0.0, index=close.index))
        self.avg_4d_pct = self.I(lambda: self.atr_pct.rolling(window=len_4d).mean() or pd.Series(0.0, index=close.index))
        
        self.q25_4d = self.I(lambda: self.atr_pct.rolling(window=len_4d).quantile(0.25) or pd.Series(0.0, index=close.index))
        self.q50_4d = self.I(lambda: self.atr_pct.rolling(window=len_4d).quantile(0.50) or pd.Series(0.0, index=close.index))
        self.q75_4d = self.I(lambda: self.atr_pct.rolling(window=len_4d).quantile(0.75) or pd.Series(0.0, index=close.index))
        
        # VWAP calculations
        hlc3 = (high + low + close) / 3
        self.vwap_curr = self.I(lambda: pta.vwap(high, low, close, volume) or pd.Series(close.iloc[0], index=close.index))
        
        self.vwap_slope_curr = self.I(lambda: self._calc_vwap_slope(self.vwap_curr, self.vwap_slope_lookback))
        
        # Multi-timeframe VWAP for alignment (simplified as current)
        self.vwap_1m = self.I(lambda: self.vwap_curr)
        self.vwap_15m = self.I(lambda: self.vwap_curr.rolling(window=15).mean())
        self.vwap_60m = self.I(lambda: self.vwap_curr.rolling(window=60).mean())

    def _calc_vwap_slope(self, vwap_series, lookback):
        slope = pd.Series(np.nan, index=vwap_series.index)
        for i in range(lookback, len(vwap_series)):
            slope.iloc[i] = vwap_series.iloc[i] - vwap_series.iloc[i - lookback]
        return slope

    def next(self):
        if len(self.data) < max(self.atr_len, self.adx_len, self.vwap_slope_lookback) + 5:
            return
        
        atr_pct = self.atr_pct[-1]
        atr_pts = self.atr_pts[-1]
        adx_val = self.adx_val[-1]
        
        avg_1h_pct = self.avg_1h_pct[-1]
        avg_4h_pct = self.avg_4h_pct[-1]
        avg_4d_pct = self.avg_4d_pct[-1]
        
        q50_1h = self.q50_1h[-1]
        q50_4h = self.q50_4h[-1]
        q50_4d = self.q50_4d[-1]
        
        # QUIET logic
        quiet_by_avgs = (atr_pct < avg_1h_pct) and (atr_pct < avg_4h_pct) and (atr_pct < avg_4d_pct)
        quiet_by_quart = (atr_pct <= q50_1h) and (atr_pct <= q50_4h) and (atr_pct <= q50_4d)
        
        if self.use_atr_quartile_gate:
            atr_ok = quiet_by_avgs and quiet_by_quart
        else:
            atr_ok = quiet_by_avgs
        
        if self.use_adx_gate:
            adx_ok = adx_val < self.adx_gate_max
        else:
            adx_ok = True
        
        trade_allowed = atr_ok and adx_ok
        
        # VWAP alignment
        close_price = self.data.Close[-1]
        vwap_1m = self.vwap_1m[-1]
        vwap_15m = self.vwap_15m[-1]
        vwap_60m = self.vwap_60m[-1]
        
        above_all_vwaps = (close_price > vwap_1m) and (close_price > vwap_15m) and (close_price > vwap_60m)
        below_all_vwaps = (close_price < vwap_1m) and (close_price < vwap_15m) and (close_price < vwap_60m)
        
        # Trading logic
        if trade_allowed:
            if above_all_vwaps and not self.position:
                self.buy()
            elif below_all_vwaps and self.position:
                self.sell()
        else:
            if self.position:
                self.sell()