"""
DS-TV Backtest Results: bank-cre-stress-short-risk-overlay-dashboard
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(atr(14),20)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "sma(atr(14),20)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(atr(14),20)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — bank-cre-stress-short-risk-overlay-dashboard
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate EMAs
        self.ema50 = self.I(pta.ema, close, length=50)
        self.ema200 = self.I(pta.ema, close, length=200)
        
        # Calculate ATR and ATR average
        self.atr = self.I(pta.atr, high, low, close, length=14)
        self.atr_avg = self.I(pta.sma, self.atr, length=20)
        
        # Calculate 20-period lowest low
        self.lowest_20 = self.I(lambda: low.rolling(window=20).min())
        
        # Bank risk categorization (hardcoded for this strategy)
        self.ticker = str(self.data._name).upper() if hasattr(self.data, '_name') else ""
        
        self.critical_banks = {"DCOM", "EGBN", "OZK", "LOB"}
        self.high_banks = {"VLY", "FLG", "ZION", "WAL"}
        self.elevated_banks = {"SNV", "RF", "CMA", "TFC"}
        self.short_bias_banks = {"FVCB", "BHB", "VLY", "FLG", "EGBN"}
        self.failed_banks = {"MCBT"}
        
        self.is_critical = self.ticker in self.critical_banks
        self.is_high = self.ticker in self.high_banks
        self.is_elevated = self.ticker in self.elevated_banks
        self.is_short_bias = self.ticker in self.short_bias_banks
        self.is_failed = self.ticker in self.failed_banks

    def next(self):
        if len(self.data) < 20:
            return
        
        close = self.data.Close[-1]
        ema50 = self.ema50[-1]
        ema200 = self.ema200[-1]
        atr = self.atr[-1]
        atr_avg = self.atr_avg[-1]
        lowest_20 = self.lowest_20[-1]
        
        if pd.isna(atr) or pd.isna(atr_avg) or pd.isna(lowest_20):
            return
        
        # Price stress conditions
        trend_break = close < ema200
        range_break = close < lowest_20
        vol_stress = atr > atr_avg * 1.3
        
        price_stress = trend_break and range_break
        
        # Trading logic based on bank risk and price stress
        high_risk_bank = self.is_critical or self.is_short_bias or self.is_high or self.is_elevated or self.is_failed
        
        # Entry: Buy signal on price stress for high-risk banks (betting on reversal/bounce)
        # Or short bias when stress is detected
        if high_risk_bank and price_stress and not self.position:
            self.buy()
        
        # Exit: Sell when price recovers above EMA50
        elif self.position and close > ema50:
            self.sell()
        
        # Alternative exit: Exit after significant move
        elif self.position and len(self) % 20 == 0:
            self.sell()