"""
DS-TV Backtest Results: ct-lvai-liquidity-vacuum-absorption-indicator
============================================================

--- SPY ---
  Return                    8.43%
  Buy & Hold Return         36.39%
  Max Drawdown              -3.06%
  Sharpe Ratio              0.87
  Sortino Ratio             1.28
  Calmar Ratio              1.36
  Profit Factor             4.73
  Expectancy                4.37%
  SQN                       0.64
  # Trades                  2
  Win Rate                  50.00%
  Best Trade                11.09%
  Worst Trade               -2.34%
  Avg Trade                 4.16%
  Exposure Time             20.20%
  Equity Final              108433.90$
  Equity Peak               110579.34$
  Avg Drawdown              -0.92%
  Max Drawdown Duration     251 days 00:00:00
  Max Trade Duration        131 days 00:00:00
  Avg Trade Duration        71 days 00:00:00
  Ann. Return               4.17%
  Ann. Volatility           4.81%

--- BTC ---
  Return                    14.31%
  Buy & Hold Return         1.20%
  Max Drawdown              -11.64%
  Sharpe Ratio              0.43
  Sortino Ratio             0.71
  Calmar Ratio              0.59
  Profit Factor             nan
  Expectancy                7.90%
  SQN                       1.42
  # Trades                  2
  Win Rate                  100.00%
  Best Trade                13.74%
  Worst Trade               2.06%
  Avg Trade                 7.74%
  Exposure Time             16.01%
  Equity Final              114311.98$
  Equity Peak               120519.32$
  Avg Drawdown              -4.54%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        69 days 00:00:00
  Avg Trade Duration        58 days 00:00:00
  Ann. Return               6.91%
  Ann. Volatility           15.97%

--- QQQ ---
  Return                    7.95%
  Buy & Hold Return         39.47%
  Max Drawdown              -2.50%
  Sharpe Ratio              1.11
  Sortino Ratio             1.83
  Calmar Ratio              1.57
  Profit Factor             nan
  Expectancy                8.00%
  SQN                       nan
  # Trades                  1
  Win Rate                  100.00%
  Best Trade                8.00%
  Worst Trade               8.00%
  Avg Trade                 8.00%
  Exposure Time             8.80%
  Equity Final              107954.21$
  Equity Peak               109811.93$
  Avg Drawdown              -0.95%
  Max Drawdown Duration     196 days 00:00:00
  Max Trade Duration        63 days 00:00:00
  Avg Trade Duration        63 days 00:00:00
  Ann. Return               3.93%
  Ann. Volatility           3.55%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — ct-lvai-liquidity-vacuum-absorption-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Preset parameters
    preset = "FAST"
    use_custom = False
    lv_len_input = 30
    norm_len_input = 100
    vac_thresh = 70
    heal_thresh = 40

    def init(self):
        # Determine parameters based on preset
        if self.use_custom:
            lv_len = self.lv_len_input
            norm_len = self.norm_len_input
        else:
            if self.preset == "TWITCHY":
                lv_len = 15
                norm_len = 60
            elif self.preset == "FAST":
                lv_len = 30
                norm_len = 100
            elif self.preset == "MEDIUM":
                lv_len = 50
                norm_len = 200
            else:  # SLOW
                lv_len = 100
                norm_len = 400

        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # Calculate True Range
        def calc_tr():
            tr_data = pta.true_range(high, low, close)
            return tr_data if tr_data is not None else pd.Series(0, index=close.index)

        tr = self.I(calc_tr)

        # Calculate Z-score of True Range (volatility shock)
        def calc_vol_shock():
            tr_vals = pta.true_range(high, low, close)
            if tr_vals is None:
                return pd.Series(0, index=close.index)
            tr_mean = pta.sma(tr_vals, length=lv_len)
            tr_std = tr_vals.rolling(window=lv_len).std()
            vol_shock = (tr_vals - tr_mean) / (tr_std + 1e-6)
            return vol_shock.abs()

        vol_shock = self.I(calc_vol_shock)

        # Calculate efficiency ratio
        def calc_efficiency():
            net_move = (close - close.shift(lv_len)).abs()
            price_changes = close.diff().abs()
            total_move = price_changes.rolling(window=lv_len).sum()
            efficiency = net_move / (total_move + 1e-6)
            return efficiency.fillna(0)

        efficiency = self.I(calc_efficiency)

        # Calculate LVAI raw score
        def calc_lvai_raw():
            eff = calc_efficiency()
            vs = calc_vol_shock()
            return vs * (1 - eff)

        lvai_raw = self.I(calc_lvai_raw)

        # Normalize LVAI
        def calc_lvai_normalized():
            raw = calc_lvai_raw()
            lo = raw.rolling(window=norm_len).min()
            hi = raw.rolling(window=norm_len).max()
            lvai_norm = 100 * (raw - lo) / ((hi - lo) + 1e-6)
            return lvai_norm.fillna(50)

        self.lvai = self.I(calc_lvai_normalized)
        self.efficiency = efficiency
        self.vol_shock = vol_shock

    def next(self):
        # Trading logic based on LVAI states
        lvai_current = self.lvai[-1]
        efficiency_current = self.efficiency[-1]

        # Vacuum state: LVAI > 70 and efficiency < 0.3
        vacuum = lvai_current > self.vac_thresh and efficiency_current < 0.3

        # Healthy state: LVAI < 40 and efficiency > 0.5
        healthy = lvai_current < self.heal_thresh and efficiency_current > 0.5

        # Entry logic: Buy when transitioning to healthy, sell when entering vacuum
        if len(self.lvai) > 1:
            vacuum_prev = (self.lvai[-2] > self.vac_thresh and 
                          self.efficiency[-2] < 0.3)
            healthy_prev = (self.lvai[-2] < self.heal_thresh and 
                           self.efficiency[-2] > 0.5)

            # Entry on vacuum detection (signal to reduce risk or prepare for volatility)
            if vacuum and not vacuum_prev:
                if self.position:
                    self.position.close()

            # Entry on healthy detection (favorable conditions for trend following)
            if healthy and not healthy_prev:
                if not self.position:
                    self.buy()

            # Exit on vacuum if long
            if vacuum and self.position:
                self.position.close()