"""
DS-TV Backtest Results: dca-onetwo
============================================================

--- SPY ---
  Return                    -35.10%
  Buy & Hold Return         41.94%
  Max Drawdown              -37.07%
  Sharpe Ratio              -2.07
  Sortino Ratio             -1.97
  Calmar Ratio              -0.53
  Profit Factor             0.60
  Expectancy                -0.17%
  SQN                       -2.62
  # Trades                  248
  Win Rate                  42.34%
  Best Trade                3.03%
  Worst Trade               -6.78%
  Avg Trade                 -0.18%
  Exposure Time             99.20%
  Equity Final              64903.94$
  Equity Peak               102093.84$
  Avg Drawdown              -7.96%
  Max Drawdown Duration     692 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -19.58%
  Ann. Volatility           9.43%

--- BTC ---
  Return                    -13.56%
  Buy & Hold Return         46.22%
  Max Drawdown              -34.67%
  Sharpe Ratio              -0.30
  Sortino Ratio             -0.42
  Calmar Ratio              -0.20
  Profit Factor             0.98
  Expectancy                -0.02%
  SQN                       -0.40
  # Trades                  256
  Win Rate                  47.66%
  Best Trade                12.31%
  Worst Trade               -8.88%
  Avg Trade                 -0.06%
  Exposure Time             70.04%
  Equity Final              86438.98$
  Equity Peak               119447.33$
  Avg Drawdown              -6.19%
  Max Drawdown Duration     386 days 00:00:00
  Max Trade Duration        2 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -7.02%
  Ann. Volatility           23.50%

--- QQQ ---
  Return                    -35.40%
  Buy & Hold Return         42.67%
  Max Drawdown              -38.36%
  Sharpe Ratio              -1.64
  Sortino Ratio             -1.59
  Calmar Ratio              -0.52
  Profit Factor             0.68
  Expectancy                -0.17%
  SQN                       -2.23
  # Trades                  248
  Win Rate                  47.18%
  Best Trade                3.22%
  Worst Trade               -6.92%
  Avg Trade                 -0.18%
  Exposure Time             99.20%
  Equity Final              64600.12$
  Equity Peak               102637.16$
  Avg Drawdown              -8.40%
  Max Drawdown Duration     691 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -19.77%
  Ann. Volatility           12.04%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — dca-onetwo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        # Calculate the time difference to detect 10-minute bar changes
        self.time_series = pd.Series(self.data.index)
        self.prev_time = None
        self.bar_alert_triggered = False

    def next(self):
        current_time = self.data.index[-1]
        
        # Detect if we're at a new 10-minute bar
        if self.prev_time is not None:
            time_diff = current_time - self.prev_time
            # Check if 10 minutes have passed (600 seconds)
            if time_diff.total_seconds() >= 600:
                new_10min_bar = True
            else:
                new_10min_bar = False
        else:
            new_10min_bar = False
        
        self.prev_time = current_time
        
        # Generate buy signal on new 10-minute bar
        if new_10min_bar:
            if not self.position:
                self.buy()
            else:
                self.position.close()