"""
DS-TV Backtest Results: diamond-v5-institutional-smc-liquidity-engine
============================================================

--- SPY ---
  Return                    -6.54%
  Buy & Hold Return         40.20%
  Max Drawdown              -6.92%
  Sharpe Ratio              -0.98
  Sortino Ratio             -1.12
  Calmar Ratio              -0.48
  Profit Factor             0.00
  Expectancy                -6.57%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -6.57%
  Worst Trade               -6.57%
  Avg Trade                 -6.57%
  Exposure Time             6.00%
  Equity Final              93461.83$
  Equity Peak               100409.38$
  Avg Drawdown              -4.49%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        42 days 00:00:00
  Ann. Return               -3.35%
  Ann. Volatility           3.42%

--- BTC ---
  Return                    -6.57%
  Buy & Hold Return         0.29%
  Max Drawdown              -10.47%
  Sharpe Ratio              -0.60
  Sortino Ratio             -0.74
  Calmar Ratio              -0.32
  Profit Factor             0.00
  Expectancy                -10.90%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -10.90%
  Worst Trade               -10.90%
  Avg Trade                 -10.90%
  Exposure Time             3.56%
  Equity Final              93429.38$
  Equity Peak               104356.91$
  Avg Drawdown              -4.90%
  Max Drawdown Duration     583 days 00:00:00
  Max Trade Duration        25 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               -3.34%
  Ann. Volatility           5.53%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         45.93%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — diamond-v5-institutional-smc-liquidity-engine
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Core parameters
    swing_left = 5
    swing_right = 3
    ema_len = 50
    slope_bars = 5
    min_slope_atr = 0.1
    
    sweep_lookback = 3
    cluster_tol = 0.1
    atr_len = 14
    sl_buffer = 0.5
    
    vol_len = 20
    rsi_lb = 10
    min_score = 5
    tp_rr = 2.0
    
    # Market detection (default to Forex)
    mrkt_gold = False
    mrkt_indices = False
    
    # Market-specific tolerances
    sweep_tol_val = 0.5
    wick_ratio_val = 0.15
    disp_body_val = 0.55
    vol_mult_val = 1.2
    fvg_min_val = 0.03
    confirm_win_val = 6
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Core indicators
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_len)
        self.vol_avg = self.I(pta.sma, volume, length=self.vol_len)
        self.ema_val = self.I(pta.ema, close, length=self.ema_len)
        self.rsi_val = self.I(pta.rsi, close, length=14)
        
        # Pivot highs/lows detection using rolling max/min
        def get_pivot_high(src, left, right):
            result = pd.Series(np.nan, index=src.index)
            for i in range(left, len(src) - right):
                window = src.iloc[i-left:i+right+1]
                if src.iloc[i] == window.max() and src.iloc[i] == src.iloc[i]:
                    result.iloc[i] = src.iloc[i]
            return result
        
        def get_pivot_low(src, left, right):
            result = pd.Series(np.nan, index=src.index)
            for i in range(left, len(src) - right):
                window = src.iloc[i-left:i+right+1]
                if src.iloc[i] == window.min() and src.iloc[i] == src.iloc[i]:
                    result.iloc[i] = src.iloc[i]
            return result
        
        self.ph = self.I(lambda: get_pivot_high(high, self.swing_left, self.swing_right))
        self.pl = self.I(lambda: get_pivot_low(low, self.swing_left, self.swing_right))
        
        # State variables
        self.structure_state = 0
        self.protected_level = None
        self.target_level = None
        self.range_high = None
        self.range_low = None
        self.pd_mid = None
        
        self.sw_high_price = []
        self.sw_high_idx = []
        self.sw_low_price = []
        self.sw_low_idx = []
        
        self.mem_bar = []
        self.mem_trend = []
        self.mem_level = []
        self.mem_extreme = []
        self.mem_score = []
        self.mem_is_cluster = []
        
        self.entry_sig = False
        self.entry_dir = 0
        self.entry_sl = None
        self.entry_tp = None
        self.final_q = 0
        self.fvg_top = None
        self.fvg_bot = None
        
        self.last_entry_bar = -100
        self.position_active = False

    def next(self):
        idx = len(self.data) - 1
        close = self.data.Close[-1]
        open_ = self.data.Open[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        volume = self.data.Volume[-1]
        
        atr = self.atr[-1] if not np.isnan(self.atr[-1]) else 0.001
        vol_avg = self.vol_avg[-1] if not np.isnan(self.vol_avg[-1]) else volume
        ema_val = self.ema_val[-1] if not np.isnan(self.ema_val[-1]) else close
        rsi_val = self.rsi_val[-1] if not np.isnan(self.rsi_val[-1]) else 50
        
        # Initialize structure on first bar
        if self.structure_state == 0:
            self.structure_state = 1 if close > ema_val else -1
            self.protected_level = low if not np.isnan(self.pl[-1]) else low
            self.target_level = high if not np.isnan(self.ph[-1]) else high
            self.range_high = high
            self.range_low = low
        
        # Update pivot arrays
        if not np.isnan(self.ph[-1]):
            self.sw_high_price.insert(0, self.ph[-1])
            self.sw_high_idx.insert(0, idx)
            if len(self.sw_high_price) > 10:
                self.sw_high_price.pop()
                self.sw_high_idx.pop()
        
        if not np.isnan(self.pl[-1]):
            self.sw_low_price.insert(0, self.pl[-1])
            self.sw_low_idx.insert(0, idx)
            if len(self.sw_low_price) > 10:
                self.sw_low_price.pop()
                self.sw_low_idx.pop()
        
        # Structure updates
        is_break_up = close > self.target_level if self.target_level is not None else False
        is_break_dn = close < self.target_level if self.target_level is not None else False
        is_choch_up = close > self.protected_level if self.protected_level is not None else False
        is_choch_dn = close < self.protected_level if self.protected_level is not None else False
        
        if self.structure_state == 1:
            if self.target_level is not None and is_break_up:
                self.protected_level = self.sw_low_price[0] if len(self.sw_low_price) > 0 else self.protected_level
                self.target_level = None
                self.range_high = high
                self.range_low = self.protected_level
            elif self.protected_level is not None and is_choch_dn:
                self.structure_state = -1
                self.target_level = self.protected_level
                self.protected_level = self.sw_high_price[0] if len(self.sw_high_price) > 0 else high
                self.range_high = self.protected_level
                self.range_low = low
        
        elif self.structure_state == -1:
            if self.target_level is not None and is_break_dn:
                self.protected_level = self.sw_high_price[0] if len(self.sw_high_price) > 0 else self.protected_level
                self.target_level = None
                self.range_low = low
                self.range_high = self.protected_level
            elif self.protected_level is not None and is_choch_up:
                self.structure_state = 1
                self.target_level = self.protected_level
                self.protected_level = self.sw_low_price[0] if len(self.sw_low_price) > 0 else low
                self.range_low = self.protected_level
                self.range_high = high
        
        # Update range
        if self.structure_state == 1:
            self.range_high = max(self.range_high, high)
        else:
            self.range_low = min(self.range_low, low)
        
        self.pd_mid = (self.range_high + self.range_low) / 2
        
        # Determine active trend
        active_trend = self.structure_state
        
        # Sweep detection
        is_sweep = False
        sweep_q = 0
        
        if active_trend != 0:
            arr_p = self.sw_low_price if active_trend == 1 else self.sw_high_price
            count = min(len(arr_p), self.sweep_lookback)
            c_range = max(0.00001, high - low)
            
            if count > 0:
                for i in range(count):
                    target = arr_p[i]
                    penetrated = (low < target and close > target) if active_trend == 1 else (high > target and close < target)
                    depth = abs(target - (low if active_trend == 1 else high))
                    
                    if penetrated and depth <= (atr * self.sweep_tol_val):
                        wick = (min(open_, close) - low) if active_trend == 1 else (high - max(open_, close))
                        w_ratio = wick / c_range
                        body_ok = (min(open_, close) >= target) if active_trend == 1 else (max(open_, close) <= target)
                        
                        if w_ratio >= self.wick_ratio_val and body_ok:
                            q = 0
                            vol_ok = volume > vol_avg * self.vol_mult_val
                            q += (3 if self.mrkt_indices else 2) if vol_ok else 0
                            q += 1
                            
                            cl = sum(1 for j in range(count) if abs(target - arr_p[j]) <= (atr * self.cluster_tol))
                            q += 3 if cl >= 2 else 0
                            
                            pd_ok = (close < self.pd_mid) if active_trend == 1 else (close > self.pd_mid)
                            q += 2 if pd_ok else -3
                            
                            rsi_div = (rsi_val > self.rsi_val[-self.rsi_lb] if self.rsi_lb < len(self.rsi_val) else False) if active_trend == 1 else (rsi_val < self.rsi_val[-self.rsi_lb] if self.rsi_lb < len(self.rsi_val) else False)
                            q += 2 if rsi_div else 0
                            
                            sweep_q = q
                            is_sweep = True
                            
                            self.mem_bar.append(idx)
                            self.mem_trend.append(active_trend)
                            self.mem_level.append(target)
                            self.mem_extreme.append(low if active_trend == 1 else high)
                            self.mem_score.append(q)
                            self.mem_is_cluster.append(cl >= 2)
                            break
        
        # Confirmation & entry
        self.entry_sig = False
        to_rem = []
        
        if len(self.mem_bar) > 0:
            for i in range(len(self.mem_bar)):
                mem_idx = self.mem_bar[i]
                trd = self.mem_trend[i]
                scr = self.mem_score[i]
                ext = self.mem_extreme[i]
                age = idx - mem_idx
                
                if age > self.confirm_win_val:
                    to_rem.append(i)
                elif age > 0:
                    is_b = trd == 1
                    candle_ok = (close > open_) if is_b else (close < open_)
                    body = abs(close - open_)
                    disp_ok = body >= (atr * self.disp_body_val)
                    
                    # FVG check
                    min_gap = atr * self.fvg_min_val
                    gap = (low - self.data.High[-3]) if is_b else (self.data.Low[-3] - high)
                    fvg_exists = (gap > min_gap and close > open_) if is_b else (gap > min_gap and close < open_)
                    
                    if candle_ok and disp_ok and fvg_exists:
                        v_bonus = 1 if (volume > vol_avg * self.vol_mult_val) else 0
                        tot = scr + 2 + v_bonus + (2 if fvg_exists else 0)
                        
                        if tot >= self.min_score:
                            sl_dist = abs(close - ext) + (atr * self.sl_buffer)
                            calc_sl = ext + (-1.0 if is_b else 1.0) * (atr * self.sl_buffer)
                            calc_tp = close + (1.0 if is_b else -1.0) * (sl_dist * self.tp_rr)
                            
                            self.entry_sig = True
                            self.entry_dir = trd
                            self.entry_sl = calc_sl
                            self.entry_tp = calc_tp
                            self.final_q = tot
                            to_rem.append(i)
                            break
        
        # Remove processed entries
        for i in sorted(to_rem, reverse=True):
            self.mem_bar.pop(i)
            self.mem_trend.pop(i)
            self.mem_score.pop(i)
            self.mem_level.pop(i)
            self.mem_extreme.pop(i)
            self.mem_is_cluster.pop(i)
        
        # Execute trades
        if self.entry_sig:
            if self.entry_dir == 1 and not self.position:
                self.buy()
                self.last_entry_bar = idx
            elif self.entry_dir == -1 and not self.position:
                self.sell()
                self.last_entry_bar = idx
        
        # Exit logic
        if self.position:
            if self.position.is_long:
                if close <= self.entry_sl or close >= self.entry_tp:
                    self.position.close()
            elif self.position.is_short:
                if close >= self.entry_sl or close <= self.entry_tp:
                    self.position.close()


if __name__ == '__main__':
    from datetime import datetime
    
    bt = Backtest(
        pd.read_csv('data.csv', index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.001,
        exclusive_orders=True
    )
    
    stats = bt.run()
    print(stats)
    bt.plot()