"""
DS-TV Backtest Results: fair-value-gap-signals-ualgo
============================================================

--- SPY ---
  Return                    4.56%
  Buy & Hold Return         39.08%
  Max Drawdown              -2.07%
  Sharpe Ratio              0.62
  Sortino Ratio             1.09
  Calmar Ratio              1.10
  Profit Factor             2.41
  Expectancy                0.93%
  SQN                       0.82
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                3.82%
  Worst Trade               -1.87%
  Avg Trade                 0.90%
  Exposure Time             11.60%
  Equity Final              104558.32$
  Equity Peak               106176.59$
  Avg Drawdown              -0.85%
  Max Drawdown Duration     172 days 00:00:00
  Max Trade Duration        33 days 00:00:00
  Avg Trade Duration        16 days 00:00:00
  Ann. Return               2.27%
  Ann. Volatility           3.69%

--- BTC ---
  Return                    -7.04%
  Buy & Hold Return         14.14%
  Max Drawdown              -15.33%
  Sharpe Ratio              -0.38
  Sortino Ratio             -0.49
  Calmar Ratio              -0.23
  Profit Factor             0.00
  Expectancy                -4.29%
  SQN                       -8.37
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -3.91%
  Worst Trade               -4.67%
  Avg Trade                 -4.29%
  Exposure Time             1.64%
  Equity Final              92957.90$
  Equity Peak               109790.11$
  Avg Drawdown              -15.33%
  Max Drawdown Duration     345 days 00:00:00
  Max Trade Duration        9 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -3.58%
  Ann. Volatility           9.31%

--- QQQ ---
  Return                    19.55%
  Buy & Hold Return         42.00%
  Max Drawdown              -2.79%
  Sharpe Ratio              1.56
  Sortino Ratio             2.93
  Calmar Ratio              3.37
  Profit Factor             10.98
  Expectancy                3.73%
  SQN                       1.91
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                8.90%
  Worst Trade               -1.72%
  Avg Trade                 3.65%
  Exposure Time             15.60%
  Equity Final              119549.00$
  Equity Peak               119549.00$
  Avg Drawdown              -1.10%
  Max Drawdown Duration     162 days 00:00:00
  Max Trade Duration        32 days 00:00:00
  Avg Trade Duration        22 days 00:00:00
  Ann. Return               9.42%
  Ann. Volatility           6.05%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fair-value-gap-signals-ualgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atr_length = 14
    max_visible = 3
    use_atr_filter = True
    mitigation_type = "Close"

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_length)
        self.vol_avg = self.I(pta.sma, volume, length=20)
        
        self.gaps = []
        self.position_entry_bar = None
        self.in_position = False

    def next(self):
        if len(self.data) < 3:
            return
        
        current_idx = len(self.data) - 1
        
        high_now = self.data.High[-1]
        high_2 = self.data.High[-3]
        low_now = self.data.Low[-1]
        low_2 = self.data.Low[-3]
        close_now = self.data.Close[-1]
        volume_now = self.data.Volume[-1]
        atr_now = self.atr[-1] if self.atr[-1] is not np.nan else 0
        vol_avg_now = self.vol_avg[-1] if self.vol_avg[-1] is not np.nan else volume_now
        
        fvg_bull = low_now > high_2
        fvg_bear = high_now < low_2
        
        if self.use_atr_filter and atr_now > 0:
            gap_size_bull = low_now - high_2
            gap_size_bear = low_2 - high_now
            if fvg_bull and gap_size_bull < atr_now:
                fvg_bull = False
            if fvg_bear and gap_size_bear < atr_now:
                fvg_bear = False
        
        if fvg_bull:
            new_gap = {
                'type': 'bull',
                'top': low_now,
                'bottom': high_2,
                'index': current_idx - 1,
                'status': 'Fresh',
                'isActive': True,
                'maxVelocity': 0.0,
                'testVolume': 0.0,
                'testStartVolume': 0.0,
                'testCount': 0,
                'maxDepth': 0.0,
                'signal_generated': False
            }
            self.gaps.append(new_gap)
        
        if fvg_bear:
            new_gap = {
                'type': 'bear',
                'top': high_now,
                'bottom': low_2,
                'index': current_idx - 1,
                'status': 'Fresh',
                'isActive': True,
                'maxVelocity': 0.0,
                'testVolume': 0.0,
                'testStartVolume': 0.0,
                'testCount': 0,
                'maxDepth': 0.0,
                'signal_generated': False
            }
            self.gaps.append(new_gap)
        
        any_signal = False
        any_filled = False
        
        for gap in self.gaps:
            if not gap['isActive']:
                continue
            
            gap_size = abs(gap['top'] - gap['bottom'])
            can_test = current_idx > gap['index'] + 1
            is_inside = can_test and (high_now >= gap['bottom'] and low_now <= gap['top'])
            
            if can_test:
                if gap['type'] == 'bull':
                    current_depth = max(0, gap['top'] - low_now)
                else:
                    current_depth = max(0, high_now - gap['bottom'])
                
                gap['maxDepth'] = max(gap['maxDepth'], current_depth)
            
            if is_inside:
                bar_range = high_now - low_now
                if bar_range > 0:
                    body_ratio = abs(close_now - self.data.Open[-1]) / bar_range
                    direction_bonus = 0.0
                    if gap['type'] == 'bull' and close_now > self.data.Open[-1]:
                        direction_bonus = 0.2
                    elif gap['type'] == 'bear' and close_now < self.data.Open[-1]:
                        direction_bonus = 0.2
                    
                    current_velocity = min(body_ratio + direction_bonus, 1.0)
                    gap['maxVelocity'] = max(gap['maxVelocity'], current_velocity)
            
            if is_inside:
                gap['testVolume'] += volume_now
                
                if gap['status'] == 'Fresh':
                    gap['status'] = 'Testing'
                    gap['testCount'] = 1
                    gap['testStartVolume'] = volume_now
            else:
                if gap['status'] == 'Testing':
                    gap['status'] = 'Tested'
            
            filled_inverse = False
            if can_test:
                if self.mitigation_type == "Close":
                    filled_inverse = (gap['type'] == 'bull' and close_now < gap['bottom']) or \
                                    (gap['type'] == 'bear' and close_now > gap['top'])
                else:
                    filled_inverse = (gap['type'] == 'bull' and low_now < gap['bottom']) or \
                                    (gap['type'] == 'bear' and high_now > gap['top'])
            
            if filled_inverse:
                gap['status'] = 'Filled'
                gap['isActive'] = False
                any_filled = True
            else:
                if is_inside and gap['testVolume'] > vol_avg_now * 0.5:
                    rejected = False
                    if gap['type'] == 'bull':
                        rejected = low_now < gap['top'] and close_now > gap['top']
                    else:
                        rejected = high_now > gap['bottom'] and close_now < gap['bottom']
                    
                    if rejected and not gap['signal_generated']:
                        gap['status'] = 'Rejected'
                        gap['signal_generated'] = True
                        any_signal = True
        
        if any_signal and not self.in_position:
            if self.position:
                self.position.close()
            self.buy()
            self.in_position = True
            self.position_entry_bar = current_idx
        
        if any_filled and self.in_position:
            if self.position:
                self.position.close()
            self.in_position = False
        
        if self.in_position and self.position_entry_bar is not None:
            bars_held = current_idx - self.position_entry_bar
            if bars_held > 20:
                if self.position:
                    self.position.close()
                self.in_position = False
        
        if len(self.gaps) > 100:
            self.gaps = [g for g in self.gaps if g['isActive'] or g['signal_generated']]


if __name__ == '__main__':
    bt = Backtest(
        data=pd.read_csv('path/to/your/data.csv', index_col=0, parse_dates=True),
        strategy=TvStrategy,
        cash=10000,
        commission=.002
    )
    results = bt.run()
    print(results)
    bt.plot()