"""
DS-TV Backtest Results: fast-moving-average-period
============================================================

--- SPY ---
  ERROR: Indicator "_calc_fas…" error. See traceback above.

--- BTC ---
  ERROR: Indicator "_calc_fas…" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "_calc_fas…" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — fast-moving-average-period
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ma_type = "EMA"
    min_p = 2
    max_p = 200
    step = 1
    lookback = 1
    atr_len = 20
    vol_thresh = 1.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.atr = self.I(pta.atr, high, low, close, length=self.atr_len)
        
        self.fastest_lower_p = self.I(self._calc_fastest_lower)
        self.fastest_upper_p = self.I(self._calc_fastest_upper)
        self.is_high_vol = self.I(self._calc_high_vol)
        self.chaos = self.I(self._calc_chaos)
        self.is_flipping = self.I(self._calc_flipping)
        
        self.ma_history = {}
        for p in range(self.min_p, self.max_p + 1, self.step):
            self.ma_history[p] = []

    def _update_ma_history(self):
        close_arr = self.data.Close
        
        for p in range(self.min_p, self.max_p + 1, self.step):
            if self.ma_type == "EMA":
                if len(self.ma_history[p]) == 0:
                    current_ma_val = close_arr[-1]
                else:
                    alpha = 2.0 / (p + 1.0)
                    prev_ma = self.ma_history[p][-1]
                    current_ma_val = (close_arr[-1] * alpha) + (prev_ma * (1.0 - alpha))
            else:
                lookback_bars = min(p, len(close_arr))
                current_ma_val = np.mean(close_arr[-lookback_bars:])
            
            self.ma_history[p].append(current_ma_val)

    def _calc_fastest_lower(self):
        self._update_ma_history()
        
        if len(self.data.Close) < self.lookback + 1:
            return np.nan
        
        fastest_lower_p = np.nan
        
        for p in range(self.min_p, self.max_p + 1, self.step):
            if len(self.ma_history[p]) < self.lookback + 1:
                continue
            
            lower_u = True
            
            for j in range(self.lookback):
                hist_idx = len(self.ma_history[p]) - 2 - j
                if hist_idx < 0:
                    lower_u = False
                    break
                
                hist_ma = self.ma_history[p][hist_idx]
                low_val = self.data.Low[-(j + 1)]
                
                if low_val <= hist_ma:
                    lower_u = False
                    break
            
            if lower_u:
                fastest_lower_p = float(p)
                break
        
        return fastest_lower_p

    def _calc_fastest_upper(self):
        self._update_ma_history()
        
        if len(self.data.Close) < self.lookback + 1:
            return np.nan
        
        fastest_upper_p = np.nan
        
        for p in range(self.min_p, self.max_p + 1, self.step):
            if len(self.ma_history[p]) < self.lookback + 1:
                continue
            
            upper_u = True
            
            for j in range(self.lookback):
                hist_idx = len(self.ma_history[p]) - 2 - j
                if hist_idx < 0:
                    upper_u = False
                    break
                
                hist_ma = self.ma_history[p][hist_idx]
                high_val = self.data.High[-(j + 1)]
                
                if high_val >= hist_ma:
                    upper_u = False
                    break
            
            if upper_u:
                fastest_upper_p = float(p)
                break
        
        return fastest_upper_p

    def _calc_high_vol(self):
        if len(self.data.Close) < 2:
            return False
        
        current_tr = max(
            self.data.High[-1] - self.data.Low[-1],
            abs(self.data.High[-1] - self.data.Close[-2]),
            abs(self.data.Low[-1] - self.data.Close[-2])
        )
        
        if len(self.atr) < 1 or self.atr[-1] is None or np.isnan(self.atr[-1]):
            return False
        
        return current_tr > (self.atr[-1] * self.vol_thresh)

    def _calc_chaos(self):
        if len(self.fastest_lower_p) < 1 or len(self.fastest_upper_p) < 1:
            return False
        
        lower_p = self.fastest_lower_p[-1]
        upper_p = self.fastest_upper_p[-1]
        
        return np.isnan(lower_p) and np.isnan(upper_p)

    def _calc_flipping(self):
        if len(self.fastest_lower_p) < 2 or len(self.fastest_upper_p) < 2:
            return False
        
        lower_p = self.fastest_lower_p[-1]
        upper_p = self.fastest_upper_p[-1]
        lower_p_prev = self.fastest_lower_p[-2]
        upper_p_prev = self.fastest_upper_p[-2]
        
        both_exist = not np.isnan(lower_p) and not np.isnan(upper_p)
        both_exist_prev = not np.isnan(lower_p_prev) and not np.isnan(upper_p_prev)
        
        if not (both_exist and both_exist_prev):
            return False
        
        s_over_r = lower_p > upper_p
        s_over_r_prev = lower_p_prev > upper_p_prev
        
        return (s_over_r and not s_over_r_prev) or (not s_over_r and s_over_r_prev)

    def next(self):
        if len(self.fastest_lower_p) < 2 or len(self.fastest_upper_p) < 2:
            return
        
        lower_p = self.fastest_lower_p[-1]
        upper_p = self.fastest_upper_p[-1]
        chaos = self.chaos[-1]
        is_flipping = self.is_flipping[-1]
        is_high_vol = self.is_high_vol[-1]
        
        both_exist = not np.isnan(lower_p) and not np.isnan(upper_p)
        s_over_r = lower_p > upper_p if both_exist else False
        
        entry_signal = False
        exit_signal = False
        
        if chaos:
            if is_high_vol:
                entry_signal = True
        elif both_exist:
            if is_flipping:
                entry_signal = True
            elif s_over_r:
                entry_signal = True
        
        if np.isnan(lower_p) and np.isnan(upper_p):
            exit_signal = True
        
        if entry_signal and not self.position:
            self.buy()
        elif exit_signal and self.position:
            self.sell()


if __name__ == "__main__":
    import yfinance as yf
    
    data = yf.download("AAPL", start="2020-01-01", end="2023-12-31")
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()