"""
DS-TV Backtest Results: gaspard98-donchian-channel-trend-colored-highs-lows
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gaspard98-donchian-channel-trend-colored-highs-lows
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate Donchian Channel
        self.donchian_high = self.I(lambda: high.rolling(self.length).max())
        self.donchian_low = self.I(lambda: low.rolling(self.length).min())
        self.donchian_mid = self.I(lambda: (high.rolling(self.length).max() + low.rolling(self.length).min()) / 2)
        
        # Track trend state
        self.is_bull = True

    def next(self):
        if len(self.data) < self.length + 1:
            return
        
        current_high = self.donchian_high[-1]
        current_low = self.donchian_low[-1]
        prev_high = self.donchian_high[-2]
        prev_low = self.donchian_low[-2]
        
        # Detect new highs and lows
        new_high = current_high > prev_high
        new_low = current_low < prev_low
        
        # Determine trend (priority to new lows)
        if new_high:
            self.is_bull = True
        if new_low:
            self.is_bull = False
        
        # Trading logic
        current_price = self.data.Close[-1]
        
        # Buy signal: price touches lower band and trend is bullish
        if current_price <= current_low and self.is_bull and not self.position:
            self.buy()
        
        # Sell signal: price touches upper band and trend is bearish
        if current_price >= current_high and not self.is_bull and self.position:
            self.sell()
        
        # Exit long if trend turns bearish
        if self.is_bull == False and self.position:
            self.sell()
        
        # Exit short if trend turns bullish
        if self.is_bull == True and not self.position:
            pass


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()