"""
DS-TV Backtest Results: gcm-hybrid-supertrend
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — gcm-hybrid-supertrend
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ATR for SuperTrend
        self.atr_14 = self.I(lambda: pta.atr(high, low, close, length=14) or pd.Series(0, index=close.index))
        
        # SuperTrend with auto settings (factor=2.0, period=10)
        self.supertrend = self.I(self._calculate_supertrend, high, low, close)
        
        # Track direction changes
        self.prev_direction = 0
        self.bars_since_change = 0
        self.dead_point = None
        self.current_direction = 0
        self.final_st = None
        
    def _calculate_supertrend(self, high, low, close):
        factor = 2.0
        period = 10
        
        hl_avg = (high + low) / 2
        atr = pta.atr(high, low, close, length=period)
        
        if atr is None:
            return pd.Series(0, index=close.index)
        
        basic_ub = hl_avg + factor * atr
        basic_lb = hl_avg - factor * atr
        
        final_ub = basic_ub.copy()
        final_lb = basic_lb.copy()
        
        for i in range(1, len(close)):
            final_ub.iloc[i] = basic_ub.iloc[i] if basic_ub.iloc[i] < final_ub.iloc[i-1] or close.iloc[i-1] > final_ub.iloc[i-1] else final_ub.iloc[i-1]
            final_lb.iloc[i] = basic_lb.iloc[i] if basic_lb.iloc[i] > final_lb.iloc[i-1] or close.iloc[i-1] < final_lb.iloc[i-1] else final_lb.iloc[i-1]
        
        supertrend = pd.Series(index=close.index, dtype=float)
        direction = pd.Series(index=close.index, dtype=float)
        
        supertrend.iloc[0] = final_ub.iloc[0]
        direction.iloc[0] = -1
        
        for i in range(1, len(close)):
            if close.iloc[i] <= final_ub.iloc[i]:
                supertrend.iloc[i] = final_ub.iloc[i]
                direction.iloc[i] = -1
            else:
                supertrend.iloc[i] = final_lb.iloc[i]
                direction.iloc[i] = 1
        
        return supertrend
    
    def next(self):
        if len(self.data) < 2:
            return
        
        current_st = self.supertrend[-1]
        prev_st = self.supertrend[-2] if len(self.supertrend) > 1 else current_st
        current_close = self.data.Close[-1]
        
        # Detect trend changes
        if current_close <= current_st and self.current_direction != -1:
            self.current_direction = -1
            self.dead_point = prev_st
            self.bars_since_change = 0
        elif current_close >= current_st and self.current_direction != 1:
            self.current_direction = 1
            self.dead_point = prev_st
            self.bars_since_change = 0
        else:
            self.bars_since_change += 1
        
        # Safety window logic
        safety_bars = 3
        
        if self.current_direction < 0:
            if self.bars_since_change <= safety_bars:
                self.final_st = self.dead_point
                if current_close < self.dead_point:
                    self.current_direction = 1.0
            else:
                self.final_st = current_st
                if current_close < current_st:
                    self.current_direction = 1.0
        elif self.current_direction > 0:
            if self.bars_since_change <= safety_bars:
                self.final_st = self.dead_point
                if current_close > self.dead_point:
                    self.current_direction = -1.0
            else:
                self.final_st = current_st
                if current_close > current_st:
                    self.current_direction = -1.0
        
        # Trading logic based on trend direction
        if not self.position:
            if self.current_direction < 0:  # Bullish
                self.buy()
            elif self.current_direction > 0:  # Bearish
                self.sell()
        else:
            if self.position.is_long and self.current_direction > 0:
                self.position.close()
            elif self.position.is_short and self.current_direction < 0:
                self.position.close()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()