"""
DS-TV Backtest Results: glorifiedgamblers-gann-flip-model-gfm-pub-test-2
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — glorifiedgamblers-gann-flip-model-gfm-pub-test-2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime
import pytz


class TvStrategy(Strategy):
    # Gann session parameters
    gann_hour_start = 8
    gann_min_start = 0
    gann_hour_end = 9
    gann_min_end = 0
    
    # Filter parameters
    chop_threshold = 3
    vol_lookback = 20
    
    # RSI divergence parameters
    rsi_div_lbL = 5
    rsi_div_lbR = 5
    rsi_div_lower = 5
    rsi_div_upper = 60

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Volume indicators
        self.vol_ma = self.I(pta.sma, volume, length=self.vol_lookback)
        self.high_volume = volume > self.vol_ma
        
        # RSI and moving averages
        self.rsi_val = self.I(pta.rsi, close, length=14)
        self.sma20 = self.I(pta.sma, close, length=20)
        self.ema9 = self.I(pta.ema, close, length=9)
        
        # Track session state
        self.gann_high = None
        self.gann_low = None
        self.gann_locked = False
        self.break_count = 0
        self.broken_up = False
        self.broken_down = False
        self.break_was_close_up = False
        self.break_was_close_down = False
        self.last_day = None
        
        # For trading logic
        self.last_flip_signal = None

    def _is_gann_session(self, bar_time):
        """Check if current time is within Gann session"""
        try:
            et_tz = pytz.timezone('America/New_York')
            et_time = bar_time.astimezone(et_tz)
            et_hour = et_time.hour
            et_min = et_time.minute
            
            gann_start_mins = self.gann_hour_start * 60 + self.gann_min_start
            gann_end_mins = self.gann_hour_end * 60 + self.gann_min_end
            current_mins = et_hour * 60 + et_min
            
            return current_mins >= gann_start_mins and current_mins < gann_end_mins
        except:
            return False

    def _is_new_day(self, current_time, last_time):
        """Check if we've crossed into a new day"""
        if last_time is None:
            return True
        try:
            et_tz = pytz.timezone('America/New_York')
            curr_et = current_time.astimezone(et_tz)
            last_et = last_time.astimezone(et_tz)
            return curr_et.date() != last_et.date()
        except:
            return False

    def next(self):
        # Get current bar time
        bar_time = self.data.index[-1]
        is_new_day = self._is_new_day(bar_time, self.last_day)
        self.last_day = bar_time
        
        # Reset on new day
        if is_new_day:
            self.gann_high = None
            self.gann_low = None
            self.gann_locked = False
            self.break_count = 0
            self.broken_up = False
            self.broken_down = False
            self.break_was_close_up = False
            self.break_was_close_down = False
        
        close = self.data.Close[-1]
        high = self.data.High[-1]
        low = self.data.Low[-1]
        
        is_gann_session = self._is_gann_session(bar_time)
        
        # Build Gann box during session
        if is_gann_session and not self.gann_locked:
            if self.gann_high is None:
                self.gann_high = high
                self.gann_low = low
            else:
                self.gann_high = max(self.gann_high, high)
                self.gann_low = min(self.gann_low, low)
        
        # Lock box when session ends
        if not is_gann_session and self.gann_high is not None and not self.gann_locked:
            self.gann_locked = True
        
        # Only process if box is locked
        if not self.gann_locked or self.gann_high is None or self.gann_low is None:
            return
        
        # Check for breaks
        close_prev = self.data.Close[-2] if len(self.data.Close) > 1 else close
        
        es_break_up_close = self.gann_locked and close > self.gann_high and close_prev <= self.gann_high
        es_break_down_close = self.gann_locked and close < self.gann_low and close_prev >= self.gann_low
        es_wick_up = self.gann_locked and high > self.gann_high and close <= self.gann_high and not es_break_up_close
        es_wick_down = self.gann_locked and low < self.gann_low and close >= self.gann_low and not es_break_down_close
        
        if es_break_up_close or es_break_down_close:
            self.break_count += 1
        
        is_choppy = self.break_count >= self.chop_threshold
        
        # Track first break direction
        if (es_break_up_close or es_wick_up) and not self.broken_up:
            self.broken_up = True
            self.break_was_close_up = es_break_up_close
        
        if (es_break_down_close or es_wick_down) and not self.broken_down:
            self.broken_down = True
            self.break_was_close_down = es_break_down_close
        
        # Gann Flip detection
        gann_flip_long = self.broken_down and close > self.gann_low and close_prev <= self.gann_low
        gann_flip_short = self.broken_up and close < self.gann_high and close_prev >= self.gann_high
        
        # Check RSI conditions
        rsi = self.rsi_val[-1] if self.rsi_val[-1] is not None else 50
        rsi_neutral = rsi > 30 and rsi < 70
        
        # Check MA conditions
        sma20 = self.sma20[-1]
        ema9 = self.ema9[-1]
        above_sma = close > sma20
        below_sma = close < sma20
        above_ema = close > ema9
        below_ema = close < ema9
        
        # Scoring
        score_long = 0
        score_long += 3 if gann_flip_long else 0
        score_long += 1 if self.break_was_close_down else 0
        score_long += 1 if rsi_neutral else 0
        score_long += 1 if above_sma else 0
        score_long += 1 if above_ema else 0
        score_long += 1 if self.high_volume[-1] else 0
        score_long -= 2 if is_choppy else 0
        score_long = max(0, min(10, score_long))
        
        score_short = 0
        score_short += 3 if gann_flip_short else 0
        score_short += 1 if self.break_was_close_up else 0
        score_short += 1 if rsi_neutral else 0
        score_short += 1 if below_sma else 0
        score_short += 1 if below_ema else 0
        score_short += 1 if self.high_volume[-1] else 0
        score_short -= 2 if is_choppy else 0
        score_short = max(0, min(10, score_short))
        
        # Trading logic: Buy on strong long flip, sell on strong short flip
        if gann_flip_long and score_long >= 5 and not self.position:
            self.buy()
            self.last_flip_signal = 'long'
        elif gann_flip_short and score_short >= 5 and not self.position:
            self.sell()
            self.last_flip_signal = 'short'
        
        # Exit logic: Close position on opposite flip signal or if choppy
        if is_choppy and self.position:
            self.position.close()
        elif self.position and self.last_flip_signal == 'long' and gann_flip_short:
            self.position.close()
        elif self.position and self.last_flip_signal == 'short' and gann_flip_long:
            self.position.close()


if __name__ == '__main__':
    # Load data
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()