"""
DS-TV Backtest Results: guacs-daily-atr-box-remaining-locked-w-extensions
============================================================

--- SPY ---
  Return                    -43.82%
  Buy & Hold Return         38.66%
  Max Drawdown              -45.69%
  Sharpe Ratio              -2.08
  Sortino Ratio             -2.09
  Calmar Ratio              -0.55
  Profit Factor             0.47
  Expectancy                -0.48%
  SQN                       -2.45
  # Trades                  113
  Win Rate                  35.40%
  Best Trade                6.61%
  Worst Trade               -11.62%
  Avg Trade                 -0.50%
  Exposure Time             96.20%
  Equity Final              56182.61$
  Equity Peak               103451.85$
  Avg Drawdown              -24.33%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        41 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               -25.22%
  Ann. Volatility           12.13%

--- BTC ---
  Return                    -27.40%
  Buy & Hold Return         37.68%
  Max Drawdown              -37.99%
  Sharpe Ratio              -0.68
  Sortino Ratio             -0.78
  Calmar Ratio              -0.39
  Profit Factor             0.67
  Expectancy                -0.70%
  SQN                       -1.22
  # Trades                  66
  Win Rate                  46.97%
  Best Trade                6.88%
  Worst Trade               -14.46%
  Avg Trade                 -0.79%
  Exposure Time             35.43%
  Equity Final              72601.90$
  Equity Peak               103517.36$
  Avg Drawdown              -19.05%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        21 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -14.77%
  Ann. Volatility           21.73%

--- QQQ ---
  Return                    -45.44%
  Buy & Hold Return         39.38%
  Max Drawdown              -49.53%
  Sharpe Ratio              -1.72
  Sortino Ratio             -1.74
  Calmar Ratio              -0.53
  Profit Factor             0.54
  Expectancy                -0.54%
  SQN                       -2.04
  # Trades                  103
  Win Rate                  43.69%
  Best Trade                8.94%
  Worst Trade               -15.74%
  Avg Trade                 -0.58%
  Exposure Time             96.20%
  Equity Final              54564.72$
  Equity Peak               106210.04$
  Avg Drawdown              -17.67%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        47 days 00:00:00
  Avg Trade Duration        7 days 00:00:00
  Ann. Return               -26.31%
  Ann. Volatility           15.34%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — guacs-daily-atr-box-remaining-locked-w-extensions
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atr_len = 14
    use_prev_day_atr = True
    max_segments = 6

    def init(self):
        self.atr = self.I(lambda: pta.atr(
            pd.Series(self.data.High),
            pd.Series(self.data.Low),
            pd.Series(self.data.Close),
            length=self.atr_len
        ))
        
        self.current_day = None
        self.day_high = None
        self.day_low = None
        self.prev_day_high = None
        self.prev_day_low = None
        self.open_d = None
        self.atr_d = None
        self.locked = False
        self.seg0_top = None
        self.seg0_bot = None
        self.lock_side = ""
        self.position_entry_price = None

    def next(self):
        # Get current bar datetime
        current_time = self.data.index[len(self.data) - 1]
        current_day = current_time.date()
        
        # Check if new day
        if self.current_day is None or current_day != self.current_day:
            self.current_day = current_day
            self.day_high = self.data.High[-1]
            self.day_low = self.data.Low[-1]
            self.prev_day_high = None
            self.prev_day_low = None
            self.open_d = self.data.Open[-1]
            
            # Get ATR value
            if self.atr[-1] is not None and not np.isnan(self.atr[-1]):
                if self.use_prev_day_atr and len(self.atr) > 1:
                    self.atr_d = self.atr[-2]
                else:
                    self.atr_d = self.atr[-1]
            
            self.locked = False
            self.seg0_top = None
            self.seg0_bot = None
            self.lock_side = ""
        else:
            # Update intraday high/low
            self.prev_day_high = self.day_high
            self.prev_day_low = self.day_low
            self.day_high = max(self.day_high, self.data.High[-1])
            self.day_low = min(self.day_low, self.data.Low[-1])
        
        # Calculate base upper/lower
        if self.atr_d is None:
            return
        
        base_upper = self.open_d + self.atr_d
        base_lower = self.open_d - self.atr_d
        
        # Calculate excursions
        up_excursion = max(0.0, self.day_high - self.open_d)
        dn_excursion = max(0.0, self.open_d - self.day_low)
        
        # Remaining budget box
        rem_lower = base_lower + up_excursion
        rem_upper = base_upper - dn_excursion
        
        # Check range filled
        range_filled = self.atr_d > 0 and (self.day_high - self.day_low) >= self.atr_d
        
        # Lock segment 0 on first fill
        made_new_high = self.prev_day_high is not None and self.day_high > self.prev_day_high
        made_new_low = self.prev_day_low is not None and self.day_low < self.prev_day_low
        
        if not self.locked and range_filled:
            self.locked = True
            
            if made_new_high and not made_new_low:
                self.seg0_bot = self.day_low
                self.seg0_top = self.day_low + self.atr_d
                self.lock_side = "LOW-ANCHORED"
            elif made_new_low and not made_new_high:
                self.seg0_top = self.day_high
                self.seg0_bot = self.day_high - self.atr_d
                self.lock_side = "HIGH-ANCHORED"
            else:
                down_dominant = dn_excursion > up_excursion
                if down_dominant:
                    self.seg0_top = self.day_high
                    self.seg0_bot = self.day_high - self.atr_d
                    self.lock_side = "HIGH-ANCHORED*"
                else:
                    self.seg0_bot = self.day_low
                    self.seg0_top = self.day_low + self.atr_d
                    self.lock_side = "LOW-ANCHORED*"
        
        # Use locked or remaining values
        seg0_top = self.seg0_top if self.locked and self.seg0_top is not None else rem_upper
        seg0_bot = self.seg0_bot if self.locked and self.seg0_bot is not None else rem_lower
        
        # Calculate extensions
        if self.locked and self.seg0_bot is not None and self.seg0_top is not None:
            dist_down = max(0.0, self.seg0_bot - self.day_low)
            dist_up = max(0.0, self.day_high - self.seg0_top)
            
            ext_down_count = (int(np.floor(dist_down / self.atr_d)) + 1) if (dist_down > 0 and self.atr_d > 0) else 0
            ext_up_count = (int(np.floor(dist_up / self.atr_d)) + 1) if (dist_up > 0 and self.atr_d > 0) else 0
            
            ext_down_count = min(ext_down_count, self.max_segments)
            ext_up_count = min(ext_up_count, self.max_segments)
            
            # Trading logic based on extensions
            current_price = self.data.Close[-1]
            
            # Buy signal: price touches lower extension and is above it
            if ext_down_count > 0 and current_price < self.seg0_bot:
                if not self.position:
                    self.buy()
                    self.position_entry_price = current_price
            
            # Sell signal: price touches upper extension and is below it
            elif ext_up_count > 0 and current_price > self.seg0_top:
                if self.position:
                    self.sell()
            
            # Exit if price reverses back into locked segment
            elif self.position and seg0_bot <= current_price <= seg0_top:
                if current_price > self.position_entry_price:
                    self.sell()
        else:
            # Pre-lock trading: buy near remaining lower, sell near remaining upper
            current_price = self.data.Close[-1]
            
            if not self.locked:
                if not self.position and current_price <= rem_lower + (self.atr_d * 0.1):
                    self.buy()
                    self.position_entry_price = current_price
                elif self.position and current_price >= rem_upper - (self.atr_d * 0.1):
                    self.sell()