"""
DS-TV Backtest Results: hiddenridder-reversal-vix
============================================================

--- SPY ---
  Return                    -13.75%
  Buy & Hold Return         37.08%
  Max Drawdown              -18.63%
  Sharpe Ratio              -0.66
  Sortino Ratio             -0.85
  Calmar Ratio              -0.39
  Profit Factor             0.37
  Expectancy                -0.83%
  SQN                       -1.64
  # Trades                  15
  Win Rate                  13.33%
  Best Trade                3.97%
  Worst Trade               -4.01%
  Avg Trade                 -0.85%
  Exposure Time             23.40%
  Equity Final              86246.41$
  Equity Peak               105989.39$
  Avg Drawdown              -11.17%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        30 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               -7.19%
  Ann. Volatility           10.83%

--- BTC ---
  Return                    -2.88%
  Buy & Hold Return         1.03%
  Max Drawdown              -20.03%
  Sharpe Ratio              -0.08
  Sortino Ratio             -0.12
  Calmar Ratio              -0.07
  Profit Factor             0.94
  Expectancy                -0.09%
  SQN                       -0.13
  # Trades                  21
  Win Rate                  28.57%
  Best Trade                21.72%
  Worst Trade               -5.10%
  Avg Trade                 -0.24%
  Exposure Time             31.46%
  Equity Final              97118.19$
  Equity Peak               115960.80$
  Avg Drawdown              -6.81%
  Max Drawdown Duration     286 days 00:00:00
  Max Trade Duration        48 days 00:00:00
  Avg Trade Duration        10 days 00:00:00
  Ann. Return               -1.45%
  Ann. Volatility           17.10%

--- QQQ ---
  Return                    -19.08%
  Buy & Hold Return         40.87%
  Max Drawdown              -26.66%
  Sharpe Ratio              -0.79
  Sortino Ratio             -0.98
  Calmar Ratio              -0.38
  Profit Factor             0.36
  Expectancy                -1.03%
  SQN                       -1.94
  # Trades                  20
  Win Rate                  20.00%
  Best Trade                4.85%
  Worst Trade               -4.92%
  Avg Trade                 -1.06%
  Exposure Time             27.60%
  Equity Final              80918.08$
  Equity Peak               110323.12$
  Avg Drawdown              -6.52%
  Max Drawdown Duration     551 days 00:00:00
  Max Trade Duration        29 days 00:00:00
  Avg Trade Duration        9 days 00:00:00
  Ann. Return               -10.12%
  Ann. Volatility           12.89%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — hiddenridder-reversal-vix
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len1 = 2
    len2 = 19
    len3 = 60

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Invert close data to simulate VIX (negative)
        vix_data = close * -1
        
        # Calculate EMAs
        self.ema_fast = self.I(pta.ema, vix_data, length=self.len1)
        self.ema_slow = self.I(pta.ema, vix_data, length=self.len2)
        self.ema_very_slow = self.I(pta.ema, vix_data, length=self.len3)

    def next(self):
        # Check if we have valid indicator values
        if len(self.ema_fast) < 2 or len(self.ema_slow) < 2:
            return
        
        # Crossover: emaFast crosses above emaSlow (VIX falling = SPX Sell signal)
        if crossover(self.ema_fast, self.ema_slow):
            if self.position:
                self.position.close()
            else:
                self.sell()
        
        # Crossunder: emaFast crosses below emaSlow (VIX rising = SPX Buy signal)
        elif crossover(self.ema_slow, self.ema_fast):
            if self.position:
                self.position.close()
            else:
                self.buy()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()