"""
DS-TV Backtest Results: initial-balance-pro-ib
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — initial-balance-pro-ib
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime, time


class TvStrategy(Strategy):
    # IB Session parameters
    ib_start_hour = 9
    ib_start_min = 30
    ib_end_hour = 10
    ib_end_min = 30
    
    # Filters
    min_ib_points = 5.0
    show_mid_signal = True
    
    def init(self):
        pass
    
    def next(self):
        # Get current bar time info
        current_time = self.data.index[len(self.data) - 1]
        
        # Check if in IB session
        in_ib = self._is_in_ib_session(current_time)
        ib_just_formed = self._is_ib_end(current_time)
        is_regular_session = self._is_regular_session(current_time)
        
        # Initialize or update IB values
        if not hasattr(self, 'ib_high'):
            self.ib_high = np.nan
            self.ib_low = np.nan
            self.ib_mid = np.nan
            self.ib_formed = False
            self.ib_start_bar = None
            self.signal_fired = False
            self.last_day = None
            self.vwap_sum = 0.0
            self.vwap_vol = 0.0
        
        # Reset on new day
        cur_day = current_time.day
        if self.last_day != cur_day:
            self.ib_high = np.nan
            self.ib_low = np.nan
            self.ib_mid = np.nan
            self.ib_formed = False
            self.ib_start_bar = None
            self.signal_fired = False
            self.vwap_sum = 0.0
            self.vwap_vol = 0.0
            self.last_day = cur_day
        
        # Build IB
        if in_ib:
            if self.ib_start_bar is None:
                self.ib_start_bar = len(self.data) - 1
            
            if np.isnan(self.ib_high):
                self.ib_high = self.data.High[-1]
            else:
                self.ib_high = max(self.ib_high, self.data.High[-1])
            
            if np.isnan(self.ib_low):
                self.ib_low = self.data.Low[-1]
            else:
                self.ib_low = min(self.ib_low, self.data.Low[-1])
        
        # IB just formed
        if ib_just_formed and not np.isnan(self.ib_high) and not self.ib_formed:
            self.ib_formed = True
            self.ib_mid = (self.ib_high + self.ib_low) / 2.0
            self.signal_fired = False
            ib_range = self.ib_high - self.ib_low
        
        # Trading signals - first touch of IB mid only
        if self.show_mid_signal and self.ib_formed and not np.isnan(self.ib_mid):
            was_above_mid = len(self.data) > 1 and self.data.Close[-2] > self.ib_mid
            was_below_mid = len(self.data) > 1 and self.data.Close[-2] < self.ib_mid
            
            current_close = self.data.Close[-1]
            current_high = self.data.High[-1]
            current_low = self.data.Low[-1]
            current_ib_high = self.ib_high
            current_ib_low = self.ib_low
            
            long_condition = (
                self.ib_formed and
                not np.isnan(self.ib_mid) and
                was_above_mid and
                current_low <= self.ib_mid and
                current_close > self.ib_mid and
                current_close < current_ib_high and
                is_regular_session and
                not in_ib and
                not self.signal_fired
            )
            
            short_condition = (
                self.ib_formed and
                not np.isnan(self.ib_mid) and
                was_below_mid and
                current_high >= self.ib_mid and
                current_close < self.ib_mid and
                current_close > current_ib_low and
                is_regular_session and
                not in_ib and
                not self.signal_fired
            )
            
            if long_condition:
                if not self.position:
                    self.buy()
                self.signal_fired = True
            elif short_condition:
                if self.position:
                    self.position.close()
                self.signal_fired = True
            
            # Exit on reverse condition
            if self.position and self.position.is_long:
                if current_close < self.ib_mid:
                    self.position.close()
            elif self.position and self.position.is_short:
                if current_close > self.ib_mid:
                    self.position.close()
    
    def _is_in_ib_session(self, dt):
        """Check if current time is within IB session"""
        h = dt.hour
        m = dt.minute
        cur = h * 60 + m
        s_t = self.ib_start_hour * 60 + self.ib_start_min
        e_t = self.ib_end_hour * 60 + self.ib_end_min
        return cur >= s_t and cur < e_t
    
    def _is_ib_end(self, dt):
        """Check if current time is at IB end"""
        h = dt.hour
        m = dt.minute
        return h == self.ib_end_hour and m == self.ib_end_min
    
    def _is_regular_session(self, dt):
        """Check if in regular trading session (9:30 - 16:00)"""
        h = dt.hour
        m = dt.minute
        cur = h * 60 + m
        return cur >= (9 * 60 + 30) and cur < (16 * 60 + 0)


if __name__ == '__main__':
    # Example usage - adjust path and symbol as needed
    data = pd.read_csv('data.csv', index_col='Date', parse_dates=True)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)
    bt.plot()