"""
DS-TV Backtest Results: jensens-convexity-score
============================================================

--- SPY ---
  Return                    5.81%
  Buy & Hold Return         36.58%
  Max Drawdown              -18.73%
  Sharpe Ratio              0.21
  Sortino Ratio             0.32
  Calmar Ratio              0.15
  Profit Factor             1.15
  Expectancy                0.28%
  SQN                       0.03
  # Trades                  6
  Win Rate                  83.33%
  Best Trade                9.84%
  Worst Trade               -11.00%
  Avg Trade                 0.09%
  Exposure Time             36.60%
  Equity Final              105805.98$
  Equity Peak               112846.65$
  Avg Drawdown              -2.76%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        134 days 00:00:00
  Avg Trade Duration        43 days 00:00:00
  Ann. Return               2.89%
  Ann. Volatility           14.04%

--- BTC ---
  Return                    -13.56%
  Buy & Hold Return         0.29%
  Max Drawdown              -43.55%
  Sharpe Ratio              -0.31
  Sortino Ratio             -0.41
  Calmar Ratio              -0.16
  Profit Factor             1.62
  Expectancy                1.32%
  SQN                       0.17
  # Trades                  15
  Win Rate                  66.67%
  Best Trade                17.43%
  Worst Trade               -20.26%
  Avg Trade                 0.99%
  Exposure Time             32.28%
  Equity Final              86439.12$
  Equity Peak               140472.12$
  Avg Drawdown              -6.35%
  Max Drawdown Duration     170 days 00:00:00
  Max Trade Duration        127 days 00:00:00
  Avg Trade Duration        15 days 00:00:00
  Ann. Return               -7.02%
  Ann. Volatility           22.42%

--- QQQ ---
  Return                    2.11%
  Buy & Hold Return         42.25%
  Max Drawdown              -22.70%
  Sharpe Ratio              0.06
  Sortino Ratio             0.10
  Calmar Ratio              0.05
  Profit Factor             0.46
  Expectancy                -1.00%
  SQN                       -0.53
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                1.71%
  Worst Trade               -8.86%
  Avg Trade                 -1.08%
  Exposure Time             26.20%
  Equity Final              102113.82$
  Equity Peak               109834.37$
  Avg Drawdown              -4.54%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        143 days 00:00:00
  Avg Trade Duration        37 days 00:00:00
  Ann. Return               1.06%
  Ann. Volatility           16.46%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — jensens-convexity-score
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    period_short = 50
    period_long = 120
    min_samples = 30
    alert_buy_threshold = 25
    alert_sell_threshold = -25

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.score_50 = self.I(self._calc_convexity_score_50, close)
        self.score_100 = self.I(self._calc_convexity_score_100, close)

    def _calc_convexity_score_50(self, close):
        return self._calc_convexity_score(close, self.period_short)

    def _calc_convexity_score_100(self, close):
        return self._calc_convexity_score(close, self.period_long)

    def _calc_convexity_score(self, close, length):
        scores = []
        
        for idx in range(len(close)):
            if idx < length:
                scores.append(np.nan)
                continue
            
            window_close = close.iloc[idx - length + 1:idx + 1].values
            
            upside_returns = []
            downside_returns = []
            all_returns = []
            
            for i in range(len(window_close) - 1):
                log_return = np.log(window_close[i] / window_close[i + 1])
                all_returns.append(log_return)
                
                if log_return > 0:
                    upside_returns.append(log_return)
                elif log_return < 0:
                    downside_returns.append(log_return)
            
            upside_count = len(upside_returns)
            downside_count = len(downside_returns)
            valid_data = upside_count >= (self.min_samples / 2) and downside_count >= (self.min_samples / 2)
            
            if not valid_data or len(all_returns) < 2 or upside_count < 2 or downside_count < 2:
                scores.append(np.nan)
                continue
            
            upside_vol = np.std(upside_returns)
            downside_vol = np.std(downside_returns)
            total_vol = np.std(all_returns)
            
            if total_vol == 0:
                scores.append(np.nan)
                continue
            
            convexity_score = (np.power(upside_vol, 2) - np.power(downside_vol, 2)) / np.power(total_vol, 2) * 100
            scores.append(convexity_score)
        
        return pd.Series(scores)

    def next(self):
        if len(self.data) < self.period_short + 10:
            return
        
        score_current = self.score_50[-1]
        
        if np.isnan(score_current):
            return
        
        if len(self.score_50) > 1:
            score_prev = self.score_50[-2]
            if not np.isnan(score_prev):
                if score_current > self.alert_buy_threshold and score_prev <= self.alert_buy_threshold:
                    if not self.position:
                        self.buy()
                
                if score_current < self.alert_sell_threshold and score_prev >= self.alert_sell_threshold:
                    if self.position:
                        self.position.close()
        
        if score_current > 50:
            if not self.position:
                self.buy()
        
        if score_current < -50:
            if self.position:
                self.position.close()
        
        if len(self.score_50) > 1:
            if crossover(self.score_50, 0):
                if not self.position:
                    self.buy()
            elif crossover(0, self.score_50):
                if self.position:
                    self.position.close()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()