"""
DS-TV Backtest Results: kurtosis-model
============================================================

--- SPY ---
  Return                    -41.00%
  Buy & Hold Return         36.64%
  Max Drawdown              -45.60%
  Sharpe Ratio              -2.06
  Sortino Ratio             -2.04
  Calmar Ratio              -0.51
  Profit Factor             0.56
  Expectancy                -0.29%
  SQN                       -2.02
  # Trades                  169
  Win Rate                  44.38%
  Best Trade                6.39%
  Worst Trade               -8.06%
  Avg Trade                 -0.30%
  Exposure Time             57.60%
  Equity Final              59002.44$
  Equity Peak               108451.26$
  Avg Drawdown              -12.12%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        31 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -23.35%
  Ann. Volatility           11.32%

--- BTC ---
  Return                    -25.60%
  Buy & Hold Return         -3.15%
  Max Drawdown              -31.91%
  Sharpe Ratio              -1.47
  Sortino Ratio             -1.46
  Calmar Ratio              -0.43
  Profit Factor             0.53
  Expectancy                -0.68%
  SQN                       -1.75
  # Trades                  50
  Win Rate                  42.00%
  Best Trade                7.32%
  Worst Trade               -9.26%
  Avg Trade                 -0.73%
  Exposure Time             10.94%
  Equity Final              74401.58$
  Equity Peak               109271.03$
  Avg Drawdown              -11.38%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        6 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -13.73%
  Ann. Volatility           9.32%

--- QQQ ---
  Return                    -45.02%
  Buy & Hold Return         39.92%
  Max Drawdown              -47.67%
  Sharpe Ratio              -1.91
  Sortino Ratio             -1.86
  Calmar Ratio              -0.55
  Profit Factor             0.60
  Expectancy                -0.34%
  SQN                       -2.00
  # Trades                  165
  Win Rate                  39.39%
  Best Trade                6.54%
  Worst Trade               -9.35%
  Avg Trade                 -0.36%
  Exposure Time             64.00%
  Equity Final              54979.06$
  Equity Peak               103397.06$
  Avg Drawdown              -47.67%
  Max Drawdown Duration     466 days 00:00:00
  Max Trade Duration        31 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -26.03%
  Ann. Volatility           13.66%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — kurtosis-model
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Parameters from Pine Script
    lookback = 30
    nn_learning_rate = 0.01
    nn_beta1 = 0.9
    nn_beta2 = 0.999

    def init(self):
        # Calculate log returns
        close = pd.Series(self.data.Close)
        log_ret = np.log(close / close.shift(1))
        
        # Rolling mean and std dev of log returns
        self.mu = self.I(lambda: log_ret.rolling(self.lookback).mean())
        self.sigma = self.I(lambda: log_ret.rolling(self.lookback).std())
        
        # Calculate rolling excess kurtosis via 4th central moment
        def calculate_kurtosis(series):
            result = pd.Series(np.nan, index=series.index)
            mu_vals = series.rolling(self.lookback).mean()
            sigma_vals = series.rolling(self.lookback).std()
            
            for i in range(self.lookback, len(series)):
                if i < self.lookback or pd.isna(mu_vals.iloc[i]) or sigma_vals.iloc[i] <= 0:
                    continue
                window = series.iloc[i-self.lookback:i]
                mu_val = mu_vals.iloc[i]
                sigma_val = sigma_vals.iloc[i]
                deviations = window - mu_val
                sum4 = (deviations ** 4).sum()
                s2 = sigma_val * sigma_val
                kurt_raw = sum4 / self.lookback / (s2 * s2) - 3.0
                result.iloc[i] = np.clip(kurt_raw, -2.0, 30.0)
            return result
        
        self.kurt = self.I(calculate_kurtosis, log_ret)
        
        # Store NN state
        self.nn_weights = [0.25, 0.25, 0.25, 0.25]
        self.nn_m = [0.0, 0.0, 0.0, 0.0]
        self.nn_v = [0.0, 0.0, 0.0, 0.0]
        self.nn_t = 0
        self.prev_inputs = [0.0, 0.0, 0.0, 0.0]
        self.prev_net = 0.0
        
        # Backtest metrics
        self.bt_errors = []

    def tanh_f(self, x):
        """Custom tanh with clamping"""
        xc = np.clip(x, -20.0, 20.0)
        ep = np.exp(xc)
        em = np.exp(-xc)
        return (ep - em) / (ep + em)

    def nn_forward(self, x0, x1, x2, x3):
        """Neural network forward pass"""
        net = self.nn_weights[0] * x0 + self.nn_weights[1] * x1 + \
              self.nn_weights[2] * x2 + self.nn_weights[3] * x3
        nn_out = 28.0 * self.tanh_f(net / 28.0)
        return np.clip(nn_out, -2.0, 30.0), net

    def nn_update(self, x0, x1, x2, x3, current_kurt):
        """Adam optimizer update for NN weights"""
        if self.prev_net == 0.0 and self.prev_inputs[0] == 0.0:
            return
        
        self.nn_t += 1
        
        # Compute error and gradient
        prev_out = 28.0 * self.tanh_f(self.prev_net / 28.0)
        err = prev_out - current_kurt
        dtanh = 1.0 - self.tanh_f(self.prev_net / 28.0) ** 2
        dloss = 2.0 * err * dtanh
        
        gradients = [dloss * self.prev_inputs[i] for i in range(4)]
        
        # Adam updates
        eps = 1e-8
        for i in range(4):
            self.nn_m[i] = self.nn_beta1 * self.nn_m[i] + (1.0 - self.nn_beta1) * gradients[i]
            self.nn_v[i] = self.nn_beta2 * self.nn_v[i] + (1.0 - self.nn_beta2) * gradients[i] ** 2
            
            mh = self.nn_m[i] / (1.0 - self.nn_beta1 ** self.nn_t)
            vh = self.nn_v[i] / (1.0 - self.nn_beta2 ** self.nn_t)
            
            self.nn_weights[i] -= self.nn_learning_rate * mh / (np.sqrt(vh) + eps)

    def next(self):
        # Skip if insufficient data
        if len(self.data) < self.lookback * 2:
            return
        
        # Current kurtosis
        if pd.isna(self.kurt[-1]):
            return
        
        current_kurt = self.kurt[-1]
        
        # Prepare NN inputs (lagged kurtosis values)
        lag1 = max(1, self.lookback // 4)
        lag2 = max(1, self.lookback // 2)
        lag3 = max(1, 3 * self.lookback // 4)
        
        x0 = current_kurt
        x1 = self.kurt[-lag1] if len(self.data) > lag1 else current_kurt
        x2 = self.kurt[-lag2] if len(self.data) > lag2 else current_kurt
        x3 = self.kurt[-lag3] if len(self.data) > lag3 else current_kurt
        
        # NN forward pass
        nn_out, net = self.nn_forward(x0, x1, x2, x3)
        
        # NN training/update (only if we have previous bar data)
        if len(self.data) > lag3 + 1:
            self.nn_update(x0, x1, x2, x3, current_kurt)
        
        # Store for next bar
        self.prev_inputs = [x0, x1, x2, x3]
        self.prev_net = net
        
        # Trading logic based on kurtosis and NN projection
        # Buy signal: kurtosis rising above normal (leptokurtic) and NN projects further rise
        # Sell signal: kurtosis falling below normal (platykurtic) or NN projects decline
        
        nn_trend = nn_out - current_kurt
        
        if current_kurt > 0.5 and nn_trend > 0:
            # Leptokurtic (fat tails) and rising
            if not self.position:
                self.buy()
        elif current_kurt < -0.5 or (nn_trend < -0.1 and self.position):
            # Platykurtic (thin tails) or declining
            if self.position:
                self.sell()
        elif current_kurt > 3.0 and self.position:
            # Extreme kurtosis - risk management exit
            self.sell()