"""
DS-TV Backtest Results: modern-real-time-adr-session-hub-v2
============================================================

--- SPY ---
  Return                    -19.29%
  Buy & Hold Return         41.94%
  Max Drawdown              -19.57%
  Sharpe Ratio              -1.63
  Sortino Ratio             -1.93
  Calmar Ratio              -0.52
  Profit Factor             0.58
  Expectancy                -0.18%
  SQN                       -1.91
  # Trades                  113
  Win Rate                  38.94%
  Best Trade                6.39%
  Worst Trade               -4.10%
  Avg Trade                 -0.19%
  Exposure Time             45.20%
  Equity Final              80706.08$
  Equity Peak               100266.12$
  Avg Drawdown              -9.98%
  Max Drawdown Duration     710 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -10.24%
  Ann. Volatility           6.27%

--- BTC ---
  Return                    -17.26%
  Buy & Hold Return         46.22%
  Max Drawdown              -26.10%
  Sharpe Ratio              -0.59
  Sortino Ratio             -0.70
  Calmar Ratio              -0.35
  Profit Factor             0.84
  Expectancy                -0.20%
  SQN                       -0.75
  # Trades                  88
  Win Rate                  48.86%
  Best Trade                10.02%
  Worst Trade               -12.73%
  Avg Trade                 -0.26%
  Exposure Time             24.08%
  Equity Final              82737.84$
  Equity Peak               111961.88$
  Avg Drawdown              -5.21%
  Max Drawdown Duration     403 days 00:00:00
  Max Trade Duration        1 days 00:00:00
  Avg Trade Duration        1 days 00:00:00
  Ann. Return               -9.03%
  Ann. Volatility           15.39%

--- QQQ ---
  Return                    -25.08%
  Buy & Hold Return         42.67%
  Max Drawdown              -28.42%
  Sharpe Ratio              -1.60
  Sortino Ratio             -1.92
  Calmar Ratio              -0.48
  Profit Factor             0.61
  Expectancy                -0.24%
  SQN                       -1.97
  # Trades                  120
  Win Rate                  39.17%
  Best Trade                6.54%
  Worst Trade               -4.61%
  Avg Trade                 -0.25%
  Exposure Time             48.00%
  Equity Final              74919.45$
  Equity Peak               101405.40$
  Avg Drawdown              -9.76%
  Max Drawdown Duration     705 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -13.54%
  Ann. Volatility           8.48%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — modern-real-time-adr-session-hub-v2
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    adr_period = 5
    asr_period = 5
    asr_mult = 1.0
    ext_length = 25
    
    def init(self):
        # We'll calculate ADR and ASR levels in next()
        # Initialize tracking variables
        self.daily_high = None
        self.daily_low = None
        self.session_high = None
        self.session_low = None
        self.session_open = None
        self.prev_day = None
        self.adr_history = []
        self.asr_history = []
        self.last_adr_high = None
        self.last_adr_low = None
        self.last_asr_high = None
        self.last_asr_low = None
        self.last_adr_mid = None
        
    def next(self):
        current_date = pd.Timestamp(self.data.index[-1]).date()
        prev_date = pd.Timestamp(self.data.index[-2]).date() if len(self.data) > 1 else None
        
        # Track daily high/low
        if current_date != self.prev_day or self.prev_day is None:
            if self.prev_day is not None and self.daily_high is not None and self.daily_low is not None:
                daily_range = self.daily_high - self.daily_low
                self.adr_history.append(daily_range)
                if len(self.adr_history) > self.adr_period:
                    self.adr_history.pop(0)
            
            self.daily_high = self.data.High[-1]
            self.daily_low = self.data.Low[-1]
            self.prev_day = current_date
        else:
            self.daily_high = max(self.daily_high, self.data.High[-1])
            self.daily_low = min(self.daily_low, self.data.Low[-1])
        
        # Calculate weighted average daily range
        if len(self.adr_history) > 0:
            weights = np.arange(1, len(self.adr_history) + 1)
            avg_daily_range = np.average(self.adr_history, weights=weights)
        else:
            avg_daily_range = self.data.High[-1] - self.data.Low[-1]
        
        # Calculate ADR levels
        adr_high = self.daily_low + avg_daily_range
        adr_low = self.daily_high - avg_daily_range
        adr_mid = (self.daily_high + self.daily_low) / 2.0
        
        # Calculate session range (simplified - using intraday extremes)
        if self.session_high is None:
            self.session_high = self.data.High[-1]
            self.session_low = self.data.Low[-1]
            self.session_open = self.data.Open[-1]
        else:
            self.session_high = max(self.session_high, self.data.High[-1])
            self.session_low = min(self.session_low, self.data.Low[-1])
        
        # Calculate ASR levels
        avg_session_range = (avg_daily_range * 0.6) * self.asr_mult
        asr_high = self.session_open + (avg_session_range / 2.0)
        asr_low = self.session_open - (avg_session_range / 2.0)
        
        # Calculate daily and session usage
        daily_used = ((self.daily_high - self.daily_low) / avg_daily_range) * 100 if avg_daily_range > 0 else 0
        session_used = ((self.session_high - self.session_low) / avg_session_range) * 100 if avg_session_range > 0 else 0
        
        is_exhausted = daily_used >= 100 or session_used >= 100
        
        # Store levels for trading logic
        self.last_adr_high = adr_high
        self.last_adr_low = adr_low
        self.last_adr_mid = adr_mid
        self.last_asr_high = asr_high
        self.last_asr_low = asr_low
        
        close = self.data.Close[-1]
        
        # Trading logic: Use ADR levels for range-based trading
        # Buy near ADR low with reversal signal (close above ADR low and above midpoint)
        # Sell near ADR high with reversal signal (close below ADR high and below midpoint)
        
        if len(self.data) > 1:
            prev_close = self.data.Close[-2]
            
            # Entry signals based on ADR levels
            if not self.position:
                # Bullish entry: price crossed above ADR low and is above midpoint
                if prev_close <= adr_low and close > adr_low and close > adr_mid:
                    self.buy()
                # Bearish entry: price crossed below ADR high and is below midpoint
                elif prev_close >= adr_high and close < adr_high and close < adr_mid:
                    self.sell()
            else:
                # Exit logic based on exhaustion or opposite level touch
                if self.position.is_long:
                    # Take profit at ADR high or exit on exhaustion
                    if close >= adr_high or is_exhausted:
                        self.position.close()
                elif self.position.is_short:
                    # Take profit at ADR low or exit on exhaustion
                    if close <= adr_low or is_exhausted:
                        self.position.close()


if __name__ == "__main__":
    # Example backtest setup
    from datetime import datetime
    
    # Load data (example with sample data)
    data = pd.read_csv("data.csv", index_col=0, parse_dates=True)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.001)
    results = bt.run()
    print(results)
    bt.plot()