"""
DS-TV Backtest Results: msd-momentum-stall-detector
============================================================

--- SPY ---
  Return                    37.20%
  Buy & Hold Return         39.08%
  Max Drawdown              -18.68%
  Sharpe Ratio              0.91
  Sortino Ratio             1.58
  Calmar Ratio              0.93
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              137195.67$
  Equity Peak               137499.05$
  Avg Drawdown              -1.79%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               17.28%
  Ann. Volatility           19.07%

--- BTC ---
  Return                    7.36%
  Buy & Hold Return         14.14%
  Max Drawdown              -38.24%
  Sharpe Ratio              0.10
  Sortino Ratio             0.16
  Calmar Ratio              0.09
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              107355.97$
  Equity Peak               162258.45$
  Avg Drawdown              -6.70%
  Max Drawdown Duration     238 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               3.61%
  Ann. Volatility           34.89%

--- QQQ ---
  Return                    40.14%
  Buy & Hold Return         42.00%
  Max Drawdown              -22.75%
  Sharpe Ratio              0.75
  Sortino Ratio             1.30
  Calmar Ratio              0.81
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              140143.41$
  Equity Peak               144847.50$
  Avg Drawdown              -2.94%
  Max Drawdown Duration     125 days 00:00:00
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               18.54%
  Ann. Volatility           24.75%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — msd-momentum-stall-detector
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    
    def init(self):
        close = pd.Series(self.data.Close)
        
        # Moving Averages
        self.sma5 = self.I(pta.sma, close, length=5)
        self.sma20 = self.I(pta.sma, close, length=20)
    
    def next(self):
        # Need at least 3 bars back to calculate slopes
        if len(self.data) < 4:
            return
        
        close = self.data.Close[-1]
        sma5_curr = self.sma5[-1]
        sma5_2bar = self.sma5[-3]
        sma5_3bar = self.sma5[-4]
        
        sma20_curr = self.sma20[-1]
        sma20_2bar = self.sma20[-3]
        sma20_3bar = self.sma20[-4]
        
        # Slopes (2-bar and 3-bar lookback)
        sell_slope5_2 = (sma5_curr - sma5_2bar) / 2
        sell_slope5_3 = (sma5_curr - sma5_3bar) / 3
        sell_slope20_2 = (sma20_curr - sma20_2bar) / 2
        sell_slope20_3 = (sma20_curr - sma20_3bar) / 3
        
        # Accelerations & Delta
        sell_accel5 = sell_slope5_2 - sell_slope5_3
        sell_accel20 = sell_slope20_2 - sell_slope20_3
        sell_delta2 = sell_slope5_2 - sell_slope20_2
        sell_delta3 = sell_slope5_3 - sell_slope20_3
        sell_deltaConv = abs(sell_delta2) - abs(sell_delta3)
        
        # Distances
        sell_dist5 = ((close - sma5_curr) / sma5_curr) * 100 if sma5_curr != 0 else 0
        sell_dist20 = ((close - sma20_curr) / sma20_curr) * 100 if sma20_curr != 0 else 0
        sell_spread = ((sma5_curr - sma20_curr) / sma20_curr) * 100 if sma20_curr != 0 else 0
        
        # SELL Conditions
        sell_c1 = close > sma5_curr and sell_dist5 < 1.0
        sell_c2 = close > sma20_curr and sell_dist20 < 1.5
        sell_c3 = abs(sell_spread) < 0.5
        sell_c4 = sell_accel5 < -0.3
        sell_c5 = sell_accel20 < 0
        sell_c6 = sell_deltaConv < -0.3
        
        crash_sell = sell_c1 and sell_c2 and sell_c3 and sell_c4 and sell_c5 and sell_c6
        
        # Trading logic: sell on crash signal, buy on recovery (absence of crash signal)
        if crash_sell:
            if self.position:
                self.sell()
        else:
            if not self.position:
                self.buy()


if __name__ == "__main__":
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()