"""
DS-TV Backtest Results: nasdaq-mtf-scanner
============================================================

--- SPY ---
  ERROR: -1

--- BTC ---
  ERROR: -1

--- QQQ ---
  ERROR: -1

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — nasdaq-mtf-scanner
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    dv_bull_threshold = 0.58
    dv_bear_threshold = 0.42

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate Delta Volume Flow for current timeframe
        spread = high - low
        spread = spread.replace(0, 1e-8)
        
        buy_volume = volume * (close - low) / spread
        sell_volume = volume * (high - close) / spread
        
        total_vol = buy_volume + sell_volume
        total_vol = total_vol.replace(0, 1e-8)
        
        self.dv_ratio = buy_volume / total_vol
        self.delta = np.where(close > close.shift(1), volume, np.where(close < close.shift(1), -volume, 0))
        self.is_green = close > close.shift(1)
        
        # Direction signal based on delta + DV alignment
        self.direction = np.where(
            (self.delta > 0) & (self.dv_ratio > 0.5),
            1,
            np.where(
                (self.delta < 0) & (self.dv_ratio < 0.5),
                -1,
                0
            )
        )

    def next(self):
        if len(self.data) < 2:
            return
        
        # Get current bar values
        current_dv = self.dv_ratio[-1]
        current_delta = self.delta[-1]
        current_green = self.is_green[-1]
        current_direction = self.direction[-1]
        
        # Hidden signal detection
        hidden_buy = current_dv > self.dv_bull_threshold and not current_green
        hidden_sell = current_dv < self.dv_bear_threshold and current_green
        
        # Simple composite score based on current bar
        score = 0
        if current_delta > 0 and current_dv > 0.5:
            score += 2
        elif current_delta < 0 and current_dv < 0.5:
            score -= 2
            
        if current_dv > self.dv_bull_threshold:
            score += 1
        elif current_dv < self.dv_bear_threshold:
            score -= 1
            
        if hidden_buy:
            score += 2
        elif hidden_sell:
            score -= 2
        
        # Trading logic based on score
        if not self.position:
            if score >= 3:
                self.buy()
            elif score <= -3:
                self.buy()  # Short proxy via sell signal
        else:
            # Exit on reversal
            if self.position.is_long and score <= -2:
                self.position.close()
            elif self.position.is_long and score >= 2:
                # Hold or adjust
                pass


if __name__ == "__main__":
    # Load data - using a default stock for backtesting
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()