"""
DS-TV Backtest Results: orb-scalper-pro-930-ny
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         37.60%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         11.87%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         40.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — orb-scalper-pro-930-ny
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover
from datetime import datetime, timedelta


class TvStrategy(Strategy):
    # ORB Settings
    orb_mins = 5
    show_box = True
    show_mid = True
    show_ext = True
    
    # Signal Settings
    show_sigs = True
    one_per_day = True
    show_retest = True
    show_failed = True
    use_vol = False
    vol_len = 20
    
    # Risk / Levels
    show_lvls = True
    tp_mult = 2.0
    sl_mult = 0.5
    
    # Volume Filter
    vol_boost_mult = 1.5
    early_break_hhmm = 1000
    
    # VWAP / EMAs / Levels
    show_vwap = True
    show_emas = True
    show_pdhl = True

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate ATR for range normalization
        self.atr5 = self.I(pta.atr, high, low, close, length=5)
        
        # Volume MA
        self.vol_ma = self.I(pta.sma, volume, length=self.vol_len)
        
        # EMAs
        self.ema9 = self.I(pta.ema, close, length=9)
        self.ema21 = self.I(pta.ema, close, length=21)
        
        # Custom VWAP tracking (simplified - use close as proxy for RTH VWAP)
        self.vwap = self.I(lambda: self._calc_vwap(high, low, close, volume))
        
        # Track ORB state
        self.orb_high = None
        self.orb_low = None
        self.orb_mid = None
        self.orb_rng = None
        self.orb_ready = False
        self.pre_market_ref = None
        self.gap_up = False
        self.gap_down = False
        
        # Signal state
        self.buy_done = False
        self.sell_done = False
        self.bull_break = False
        self.bear_break = False
        self.last_signal = None
        
        # Track previous bar values for crossover detection
        self.prev_close = None
        self.prev_vol = None
        self.in_orb_window = False
        self.last_day = None

    def _calc_vwap(self, high, low, close, volume):
        """Calculate VWAP as HLC3 weighted by volume"""
        hlc3 = (high + low + close) / 3
        tp_vol = hlc3 * volume
        cum_tp_vol = tp_vol.cumsum()
        cum_vol = volume.cumsum()
        vwap = cum_tp_vol / cum_vol
        return vwap

    def _get_time_components(self):
        """Extract hour and minute from current bar time"""
        if len(self.data) == 0:
            return None, None
        bar_time = self.data.index[-1]
        hour = bar_time.hour
        minute = bar_time.minute
        hhmm = hour * 100 + minute
        return hour, minute, hhmm

    def _update_orb_state(self):
        """Update ORB high/low tracking"""
        hour, minute, hhmm = self._get_time_components()
        
        if hhmm is None:
            return
        
        # ORB window: 9:30 to 9:35 (or orbMins)
        orb_end_mins = 30 + self.orb_mins
        orb_end_hour = 9 + orb_end_mins // 60
        orb_end_min = orb_end_mins % 60
        orb_end_hhmm = orb_end_hour * 100 + orb_end_min
        
        in_orb = hhmm >= 930 and hhmm < orb_end_hhmm
        
        # Reset on new day
        current_day = self.data.index[-1].date()
        if self.last_day != current_day:
            self.orb_high = None
            self.orb_low = None
            self.orb_mid = None
            self.orb_rng = None
            self.orb_ready = False
            self.pre_market_ref = None
            self.gap_up = False
            self.gap_down = False
            self.buy_done = False
            self.sell_done = False
            self.bull_break = False
            self.bear_break = False
            self.last_day = current_day
        
        # Track pre-market reference
        if hhmm < 930:
            self.pre_market_ref = self.data.Close[-1]
        
        # Update ORB range during ORB window
        if in_orb:
            if self.orb_high is None:
                self.orb_high = self.data.High[-1]
                self.orb_low = self.data.Low[-1]
            else:
                self.orb_high = max(self.orb_high, self.data.High[-1])
                self.orb_low = min(self.orb_low, self.data.Low[-1])
        else:
            # ORB formation complete
            if self.orb_high is not None and not self.orb_ready:
                self.orb_mid = (self.orb_high + self.orb_low) / 2
                self.orb_rng = self.orb_high - self.orb_low
                self.orb_ready = True
                
                # Gap detection
                if self.pre_market_ref is not None:
                    self.gap_up = self.orb_low > self.pre_market_ref
                    self.gap_down = self.orb_high < self.pre_market_ref

    def _calculate_score(self, is_long):
        """Calculate setup grade score (0-7 points)"""
        score = 0
        
        if not self.orb_ready or self.vol_ma[-1] is None:
            return 0
        
        # VWAP alignment (2 pts) - most important
        if not np.isnan(self.vwap[-1]):
            if is_long and self.data.Close[-1] > self.vwap[-1]:
                score += 2
            elif not is_long and self.data.Close[-1] < self.vwap[-1]:
                score += 2
        
        # Volume boost (1 pt)
        vol_boosted = self.data.Volume[-1] >= self.vol_ma[-1] * self.vol_boost_mult
        if vol_boosted:
            score += 1
        
        # Early break (1 pt)
        hour, minute, hhmm = self._get_time_components()
        if hhmm is not None and hhmm < self.early_break_hhmm:
            score += 1
        
        # Gap direction (1 pt)
        if is_long and self.gap_up:
            score += 1
        elif not is_long and self.gap_down:
            score += 1
        
        # EMA trend (1 pt)
        if not np.isnan(self.ema9[-1]) and not np.isnan(self.ema21[-1]):
            if is_long and self.ema9[-1] > self.ema21[-1]:
                score += 1
            elif not is_long and self.ema9[-1] < self.ema21[-1]:
                score += 1
        
        # Normal range (1 pt)
        if not np.isnan(self.atr5[-1]) and self.atr5[-1] > 0:
            if self.orb_rng >= self.atr5[-1] * 0.05 and self.orb_rng <= self.atr5[-1] * 4.0:
                score += 1
        
        return score

    def _get_grade(self, score):
        """Convert score to letter grade"""
        if score >= 6:
            return "A+"
        elif score >= 4:
            return "A"
        elif score >= 2:
            return "B"
        else:
            return "C"

    def _is_in_signal_window(self):
        """Check if current time is in signal window (9:35-10:30)"""
        hour, minute, hhmm = self._get_time_components()
        if hhmm is None:
            return False
        return hhmm >= 935 and hhmm <= 1030

    def next(self):
        """Main strategy logic"""
        # Update ORB state
        self._update_orb_state()
        
        # Skip if insufficient data
        if len(self.data) < 2:
            return
        
        # Check volume filter
        vol_ok = not self.use_vol or (self.vol_ma[-1] is not None and 
                                      self.data.Volume[-1] >= self.vol_ma[-1])
        
        # Check if in signal window
        in_window = self._is_in_signal_window()
        
        if not self.orb_ready or not in_window or not vol_ok:
            return
        
        # Primary breakout signals
        buy_break = crossover(self.data.Close, self.orb_high)
        sell_break = crossover(self.orb_low, self.data.Close)
        
        if buy_break:
            self.bull_break = True
        if sell_break:
            self.bear_break = True
        
        # Apply one-per-day filter
        buy_signal = buy_break and (not self.one_per_day or not self.buy_done)
        sell_signal = sell_break and (not self.one_per_day or not self.sell_done)
        
        if buy_signal:
            self.buy_done = True
        if sell_signal:
            self.sell_done = True
        
        # Retest signals
        retest_buy = (self.show_retest and self.bull_break and not buy_signal and in_window and
                     self.data.Low[-1] <= self.orb_high and 
                     self.data.Close[-1] > self.orb_high and 
                     self.data.Close[-2] > self.orb_high)
        
        retest_sell = (self.show_retest and self.bear_break and not sell_signal and in_window and
                      self.data.High[-1] >= self.orb_low and 
                      self.data.Close[-1] < self.orb_low and 
                      self.data.Close[-2] < self.orb_low)
        
        # Failed ORB / Fade signals
        failed_bull = self.show_failed and self.bull_break and in_window and crossover(self.orb_high, self.data.Close)
        failed_bear = self.show_failed and self.bear_break and in_window and crossover(self.data.Close, self.orb_low)
        
        # Execute trades
        if buy_signal:
            long_score = self._calculate_score(True)
            if self.position.size <= 0:
                self.buy()
                self.last_signal = f"BUY [{self._get_grade(long_score)}]"
        
        elif sell_signal:
            short_score = self._calculate_score(False)
            if self.position.size >= 0:
                self.sell()
                self.last_signal = f"SELL [{self._get_grade(short_score)}]"
        
        elif retest_buy:
            long_score = self._calculate_score(True)
            if self.position.size <= 0:
                self.buy()
                self.last_signal = f"RETEST LONG [{self._get_grade(long_score)}]"
        
        elif retest_sell:
            short_score = self._calculate_score(False)
            if self.position.size >= 0:
                self.sell()
                self.last_signal = f"RETEST SHORT [{self._get_grade(short_score)}]"
        
        elif failed_bull:
            short_score = self._calculate_score(False)
            if self.position.size >= 0:
                self.sell()
                self.last_signal = f"FADE SHORT [{self._get_grade(short_score)}]"
        
        elif failed_bear:
            long_score = self._calculate_score(True)
            if self.position.size <= 0:
                self.buy()
                self.last_signal = f"FADE LONG [{self._get_grade(long_score)}]"


if __name__ == "__main__":
    # Load your OHLCV data
    data = pd.read_csv("your_data.csv", index_col=0, parse_dates=True)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()