"""
DS-TV Backtest Results: regalrides-pro-indicator
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — regalrides-pro-indicator
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy
from datetime import datetime, timedelta


class TvStrategy(Strategy):
    session_hour = 9
    session_minute = 15
    rr_multiple = 2.0
    
    def init(self):
        self.first_high = None
        self.first_low = None
        self.signal_triggered = False
        self.entry_price = None
        self.stop_loss = None
        self.target_price = None
        self.trade_side = ""
        self.last_day = None
        self.first_candle_index = None
        self.entry_index = None
    
    def next(self):
        current_time = self.data.index[-1]
        current_bar_hour = current_time.hour
        current_bar_minute = current_time.minute
        current_day = current_time.date()
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        if self.last_day != current_day:
            self.first_high = None
            self.first_low = None
            self.signal_triggered = False
            self.entry_price = None
            self.stop_loss = None
            self.target_price = None
            self.trade_side = ""
            self.first_candle_index = None
            self.entry_index = None
            self.last_day = current_day
        
        is_first_candle = (current_bar_hour == self.session_hour and 
                          current_bar_minute == self.session_minute)
        
        second_hour = (self.session_hour + 1) % 24 if self.session_minute + 15 >= 60 else self.session_hour
        second_minute = (self.session_minute + 15) % 60
        is_second_candle = (current_bar_hour == second_hour and 
                           current_bar_minute == second_minute)
        
        if is_first_candle:
            self.first_high = current_high
            self.first_low = current_low
            self.first_candle_index = len(self.data) - 1
        
        if is_second_candle and not self.signal_triggered:
            if self.first_high is not None and current_close > self.first_high:
                self.signal_triggered = True
                self.trade_side = "BUY"
                self.entry_price = current_close
                self.stop_loss = self.first_low
                risk = self.entry_price - self.stop_loss
                self.target_price = self.entry_price + (risk * self.rr_multiple)
                self.entry_index = len(self.data) - 1
                self.buy()
            
            elif self.first_low is not None and current_close < self.first_low:
                self.signal_triggered = True
                self.trade_side = "SELL"
                self.entry_price = current_close
                self.stop_loss = self.first_high
                risk = self.stop_loss - self.entry_price
                self.target_price = self.entry_price - (risk * self.rr_multiple)
                self.entry_index = len(self.data) - 1
                self.sell()
        
        if self.signal_triggered:
            if self.trade_side == "BUY" and self.position:
                if current_low <= self.stop_loss or current_high >= self.target_price:
                    self.sell()
            
            elif self.trade_side == "SELL" and self.position:
                if current_high >= self.stop_loss or current_low <= self.target_price:
                    self.buy()


if __name__ == "__main__":
    import yfinance as yf
    
    symbol = "AAPL"
    data = yf.download(symbol, start="2023-01-01", end="2024-01-01", interval="15m")
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.001)
    results = bt.run()
    print(results)
    bt.plot()