"""
DS-TV Backtest Results: scalpboard-pro
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         38.66%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         37.68%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         39.38%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — scalpboard-pro
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    natr_len = 14
    avg_vol_len = 20
    corr_period = 20
    threshold_natr_4h = 0.45
    threshold_natr_1d = 2.0
    threshold_rel_vol = 1.5
    threshold_day_vol = 100000000
    threshold_short = 1.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate ATR for NATR calculations
        self.atr = self.I(pta.atr, high, low, close, length=self.natr_len)
        
        # NATR 15min equivalent (using current timeframe as proxy)
        self.natr_current = self.I(lambda: (self.atr / close) * 100 if len(self.atr) > 0 else pd.Series(0, index=close.index))
        
        # Volume * Close for daily volume calculation
        self.vol_usd = self.I(lambda: volume * close)
        
        # SMA of volume for relative volume
        self.vol_sma = self.I(pta.sma, volume, length=7)
        
        # Relative volume calculation
        self.rel_vol = self.I(lambda: (volume / self.vol_sma) if len(self.vol_sma) > 0 and self.vol_sma[-1] != 0 else pd.Series(1.0, index=volume.index))
        
        # Daily volume in USD
        self.daily_vol_usd = self.I(lambda: volume * close)
        
        # High and Low for level checks
        self.high_level = self.I(lambda: high.rolling(window=1).max())
        self.low_level = self.I(lambda: low.rolling(window=1).min())
        
        # Previous low (shifted by 1)
        self.prev_low = self.I(lambda: low.shift(1))

    def next(self):
        # Current values
        natr = self.natr_current[-1] if len(self.natr_current) > 0 else 0
        rel_vol = self.rel_vol[-1] if len(self.rel_vol) > 0 else 0
        daily_vol = self.daily_vol_usd[-1] if len(self.daily_vol_usd) > 0 else 0
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        # Get previous low value
        prev_low_val = self.prev_low[-1] if len(self.prev_low) > 0 and self.prev_low[-1] is not None else 0
        high_level_val = self.high_level[-1] if len(self.high_level) > 0 else current_high
        
        # Long Setup conditions
        long_setup = (
            natr < self.threshold_natr_4h and
            rel_vol > self.threshold_rel_vol and
            current_close > high_level_val * 0.995 and
            current_close < high_level_val * 1.005 and
            daily_vol > self.threshold_day_vol
        )
        
        # Short Setup conditions
        short_setup = (
            natr > self.threshold_short and
            rel_vol > self.threshold_rel_vol and
            current_close < prev_low_val * 1.005 and
            prev_low_val > 0 and
            daily_vol > self.threshold_day_vol
        )
        
        # Trading logic
        if long_setup and not self.position:
            self.buy()
        elif short_setup and self.position:
            self.sell()
        elif not long_setup and not short_setup and self.position:
            self.sell()


if __name__ == "__main__":
    # Load data
    data = pd.read_csv("data.csv", index_col=0, parse_dates=True)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=0.002)
    stats = bt.run()
    print(stats)
    bt.plot()