"""
DS-TV Backtest Results: session-anchor-range
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — session-anchor-range
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    session_start_hour = 9
    session_start_minute = 30
    session_end_hour = 16
    session_end_minute = 0

    def init(self):
        self.anchor_high = None
        self.anchor_low = None
        self.anchor_time = None
        self.in_session = False
        self.was_in_session = False
        
    def next(self):
        current_time = pd.Timestamp(self.data.index[-1])
        current_hour = current_time.hour
        current_minute = current_time.minute
        
        session_start = self.session_start_hour + self.session_start_minute / 60.0
        session_end = self.session_end_hour + self.session_end_minute / 60.0
        current_time_decimal = current_hour + current_minute / 60.0
        
        self.in_session = session_start <= current_time_decimal < session_end
        
        is_first_in_session = self.in_session and not self.was_in_session
        
        if is_first_in_session:
            self.anchor_high = self.data.High[-1]
            self.anchor_low = self.data.Low[-1]
            self.anchor_time = current_time
        
        if self.anchor_high is not None and self.anchor_low is not None:
            current_price = self.data.Close[-1]
            
            if current_price >= self.anchor_high and len(self.trades) == 0:
                self.buy()
            elif current_price <= self.anchor_low and len(self.trades) > 0:
                self.sell()
            
            if not self.in_session and self.was_in_session:
                if len(self.trades) > 0:
                    self.sell()
        
        self.was_in_session = self.in_session