"""
DS-TV Backtest Results: shalli-rsi-shalli
============================================================

--- SPY ---
  Return                    5.48%
  Buy & Hold Return         38.66%
  Max Drawdown              -15.81%
  Sharpe Ratio              0.22
  Sortino Ratio             0.34
  Calmar Ratio              0.17
  Profit Factor             2.07
  Expectancy                0.50%
  SQN                       0.90
  # Trades                  11
  Win Rate                  63.64%
  Best Trade                3.29%
  Worst Trade               -1.87%
  Avg Trade                 0.49%
  Exposure Time             35.20%
  Equity Final              105478.82$
  Equity Peak               107988.21$
  Avg Drawdown              -2.45%
  Max Drawdown Duration     206 days 00:00:00
  Max Trade Duration        65 days 00:00:00
  Avg Trade Duration        23 days 00:00:00
  Ann. Return               2.72%
  Ann. Volatility           12.64%

--- BTC ---
  Return                    6.10%
  Buy & Hold Return         37.68%
  Max Drawdown              -20.90%
  Sharpe Ratio              0.14
  Sortino Ratio             0.22
  Calmar Ratio              0.14
  Profit Factor             1.23
  Expectancy                0.54%
  SQN                       0.20
  # Trades                  21
  Win Rate                  28.57%
  Best Trade                28.40%
  Worst Trade               -12.02%
  Avg Trade                 0.24%
  Exposure Time             34.34%
  Equity Final              106104.63$
  Equity Peak               114041.22$
  Avg Drawdown              -7.15%
  Max Drawdown Duration     284 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        11 days 00:00:00
  Ann. Return               3.00%
  Ann. Volatility           20.99%

--- QQQ ---
  Return                    -4.45%
  Buy & Hold Return         39.38%
  Max Drawdown              -24.33%
  Sharpe Ratio              -0.16
  Sortino Ratio             -0.23
  Calmar Ratio              -0.09
  Profit Factor             0.84
  Expectancy                -0.21%
  SQN                       -0.30
  # Trades                  17
  Win Rate                  29.41%
  Best Trade                10.03%
  Worst Trade               -2.83%
  Avg Trade                 -0.27%
  Exposure Time             40.20%
  Equity Final              95545.02$
  Equity Peak               110225.12$
  Avg Drawdown              -4.09%
  Max Drawdown Duration     537 days 00:00:00
  Max Trade Duration        83 days 00:00:00
  Avg Trade Duration        17 days 00:00:00
  Ann. Return               -2.27%
  Ann. Volatility           14.59%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — shalli-rsi-shalli
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 14
    smooth = 14
    ob_value = 80
    os_value = 20

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)

        # Calculate highest and lowest
        def calc_highest():
            return high.rolling(window=self.length).max()

        def calc_lowest():
            return low.rolling(window=self.length).min()

        highest = self.I(calc_highest)
        lowest = self.I(calc_lowest)

        # Calculate augmented RSI components
        def calc_arsi():
            upper = high.rolling(window=self.length).max()
            lower = low.rolling(window=self.length).min()
            r = upper - lower

            d = close.diff()
            diff = pd.Series(index=close.index, dtype=float)

            for i in range(len(close)):
                if i == 0:
                    diff.iloc[i] = 0
                elif upper.iloc[i] > upper.iloc[i - 1]:
                    diff.iloc[i] = r.iloc[i]
                elif lower.iloc[i] < lower.iloc[i - 1]:
                    diff.iloc[i] = -r.iloc[i]
                else:
                    diff.iloc[i] = d.iloc[i]

            num = pta.ema(diff, length=self.length)
            if num is None:
                num = pd.Series(0, index=close.index)

            abs_diff = diff.abs()
            den = pta.ema(abs_diff, length=self.length)
            if den is None:
                den = pd.Series(1, index=close.index)

            den = den.replace(0, 1)
            arsi = (num / den) * 50 + 50

            return arsi

        self.arsi = self.I(calc_arsi)

        # Calculate signal line
        def calc_signal():
            upper = high.rolling(window=self.length).max()
            lower = low.rolling(window=self.length).min()
            r = upper - lower

            d = close.diff()
            diff = pd.Series(index=close.index, dtype=float)

            for i in range(len(close)):
                if i == 0:
                    diff.iloc[i] = 0
                elif upper.iloc[i] > upper.iloc[i - 1]:
                    diff.iloc[i] = r.iloc[i]
                elif lower.iloc[i] < lower.iloc[i - 1]:
                    diff.iloc[i] = -r.iloc[i]
                else:
                    diff.iloc[i] = d.iloc[i]

            num = pta.ema(diff, length=self.length)
            if num is None:
                num = pd.Series(0, index=close.index)

            abs_diff = diff.abs()
            den = pta.ema(abs_diff, length=self.length)
            if den is None:
                den = pd.Series(1, index=close.index)

            den = den.replace(0, 1)
            arsi = (num / den) * 50 + 50

            signal = pta.ema(arsi, length=self.smooth)
            if signal is None:
                signal = pd.Series(50, index=close.index)

            return signal

        self.signal = self.I(calc_signal)

    def next(self):
        if len(self.data) < self.length + self.smooth:
            return

        arsi_val = self.arsi[-1]
        signal_val = self.signal[-1]

        # Buy when ARSI crosses above signal line from oversold region
        if crossover(self.arsi, self.signal):
            if arsi_val < self.ob_value:
                if not self.position:
                    self.buy()

        # Sell when ARSI crosses below signal line from overbought region
        elif crossover(self.signal, self.arsi):
            if arsi_val > self.os_value:
                if self.position:
                    self.position.close()