"""
DS-TV Backtest Results: sizetale
============================================================

--- SPY ---
  ERROR: object of type 'TvStrategy' has no len()

--- BTC ---
  ERROR: object of type 'TvStrategy' has no len()

--- QQQ ---
  ERROR: object of type 'TvStrategy' has no len()

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — sizetale
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Position sizing parameters
    max_loss = 3000
    R = 120
    n_entries = 10
    lot_size = 0
    boost_entry = 0
    boost_mult = 2
    
    def init(self):
        pass
    
    def next(self):
        # This is a position sizing indicator, not a trading strategy
        # It calculates entry levels and risk based on stop loss and freeze levels
        # For backtesting purposes, we'll implement a simple breakout-based entry
        
        if len(self) < 2:
            return
        
        # Simple entry logic: buy on close above previous high, sell on close below previous low
        prev_high = self.data.High[-2]
        prev_low = self.data.Low[-2]
        current_close = self.data.Close[-1]
        
        # Long entry: break above previous high
        if current_close > prev_high and not self.position:
            self.buy()
        
        # Exit: close below entry or fixed stop
        elif self.position and current_close < self.position.open_price * 0.97:
            self.position.close()


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    results = bt.run()
    print(results)