"""
DS-TV Backtest Results: stable-stocks-ema-extension-smh
============================================================

--- SPY ---
  Return                    -6.00%
  Buy & Hold Return         35.76%
  Max Drawdown              -14.70%
  Sharpe Ratio              -0.29
  Sortino Ratio             -0.38
  Calmar Ratio              -0.21
  Profit Factor             0.89
  Expectancy                -0.04%
  SQN                       -0.49
  # Trades                  127
  Win Rate                  59.06%
  Best Trade                3.56%
  Worst Trade               -5.89%
  Avg Trade                 -0.04%
  Exposure Time             75.00%
  Equity Final              93996.69$
  Equity Peak               100000.00$
  Avg Drawdown              -14.70%
  Max Drawdown Duration     672 days 00:00:00
  Max Trade Duration        19 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -3.07%
  Ann. Volatility           10.44%

--- BTC ---
  Return                    0.79%
  Buy & Hold Return         -2.17%
  Max Drawdown              -30.07%
  Sharpe Ratio              0.02
  Sortino Ratio             0.03
  Calmar Ratio              0.01
  Profit Factor             1.02
  Expectancy                0.02%
  SQN                       0.03
  # Trades                  74
  Win Rate                  62.16%
  Best Trade                10.02%
  Worst Trade               -14.62%
  Avg Trade                 -0.06%
  Exposure Time             36.80%
  Equity Final              100793.50$
  Equity Peak               119059.67$
  Avg Drawdown              -9.06%
  Max Drawdown Duration     264 days 00:00:00
  Max Trade Duration        16 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               0.40%
  Ann. Volatility           22.72%

--- QQQ ---
  Return                    -12.58%
  Buy & Hold Return         39.41%
  Max Drawdown              -23.41%
  Sharpe Ratio              -0.48
  Sortino Ratio             -0.58
  Calmar Ratio              -0.28
  Profit Factor             0.82
  Expectancy                -0.10%
  SQN                       -0.75
  # Trades                  124
  Win Rate                  58.06%
  Best Trade                5.21%
  Worst Trade               -9.02%
  Avg Trade                 -0.11%
  Exposure Time             72.80%
  Equity Final              87415.41$
  Equity Peak               103379.04$
  Avg Drawdown              -6.59%
  Max Drawdown Duration     579 days 00:00:00
  Max Trade Duration        30 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               -6.55%
  Ann. Volatility           13.71%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — stable-stocks-ema-extension-smh
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ema_length = 9
    ema34_length = 34
    ema8_length = 8
    ext10_pct = 10
    ext25_pct = 25
    ext35_pct = 35

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate EMAs
        self.ema9 = self.I(pta.ema, close, length=self.ema_length)
        self.ema34 = self.I(pta.ema, close, length=self.ema34_length)
        self.ema8 = self.I(pta.ema, close, length=self.ema8_length)
        
        # Calculate extension levels
        self.ema34_ext10_upper = self.I(lambda: self.ema34 * (1 + self.ext10_pct / 100))
        self.ema34_ext10_lower = self.I(lambda: self.ema34 * (1 - self.ext10_pct / 100))
        self.ema34_ext25_upper = self.I(lambda: self.ema34 * (1 + self.ext25_pct / 100))
        self.ema34_ext25_lower = self.I(lambda: self.ema34 * (1 - self.ext25_pct / 100))
        self.ema34_ext35_upper = self.I(lambda: self.ema34 * (1 + self.ext35_pct / 100))
        self.ema34_ext35_lower = self.I(lambda: self.ema34 * (1 - self.ext35_pct / 100))

    def next(self):
        # Skip if not enough data
        if len(self.data) < 4:
            return
        
        # Get current values
        close_curr = self.data.Close[-1]
        close_prev1 = self.data.Close[-2]
        close_prev2 = self.data.Close[-3]
        
        ema34_val = self.ema34[-1]
        ema8_val = self.ema8[-1]
        ema34_prev1 = self.ema34[-2]
        ema8_prev1 = self.ema8[-2]
        
        # Check for crossovers
        cross_up = crossover(self.ema8, self.ema34)
        cross_down = crossover(self.ema34, self.ema8)
        
        # Check if cross happened in last 3 bars
        cross_up_recent = False
        cross_down_recent = False
        
        if len(self.data) >= 4:
            ema8_2 = self.ema8[-3]
            ema34_2 = self.ema34[-3]
            ema8_3 = self.ema8[-4] if len(self.data) >= 5 else ema8_2
            ema34_3 = self.ema34[-4] if len(self.data) >= 5 else ema34_2
            
            # Check if cross happened 1-3 bars ago
            cross_up_recent = (ema8_prev1 > ema34_prev1) or (ema8_2 > ema34_2) or (ema8_3 > ema34_3)
            cross_down_recent = (ema8_prev1 < ema34_prev1) or (ema8_2 < ema34_2) or (ema8_3 < ema34_3)
        
        # Bullish condition: cross up recent AND 2 consecutive higher closes
        bullish = cross_up_recent and close_curr > close_prev1 and close_prev1 > close_prev2
        
        # Bearish condition: cross down recent AND 2 consecutive lower closes
        bearish = cross_down_recent and close_curr < close_prev1 and close_prev1 < close_prev2
        
        # Trading logic
        if bullish:
            if self.position:
                self.position.close()
            self.buy()
        elif bearish:
            if self.position:
                self.position.close()