"""
DS-TV Backtest Results: standard-deviation-ruler
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "λ" shape: (), returned value: 590.4057482711463)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "λ" shape: (), returned value: 94869.92710875538)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "λ" shape: (), returned value: 524.3060523746941)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — standard-deviation-ruler
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    b_mult_1 = 1.0
    b_mult_2 = 2.0
    b_mult_3 = 2.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate VWAP using pandas_ta
        self.vwap = self.I(lambda: pta.vwap(high, low, close, volume) if pta.vwap(high, low, close, volume) is not None else pd.Series(close.mean(), index=close.index))
        
        # Calculate standard deviation
        self.std_dev = self.I(lambda: close.rolling(window=20).std() if len(close) >= 20 else pd.Series(0, index=close.index))
        
        # Calculate deviation bands
        self.dev_ua = self.I(lambda: self.vwap[-1] + (self.b_mult_1 * self.std_dev[-1]) if len(self.vwap) > 0 and len(self.std_dev) > 0 and self.std_dev[-1] is not None else pd.Series(close.mean(), index=close.index))
        self.dev_la = self.I(lambda: self.vwap[-1] - (self.b_mult_1 * self.std_dev[-1]) if len(self.vwap) > 0 and len(self.std_dev) > 0 and self.std_dev[-1] is not None else pd.Series(close.mean(), index=close.index))
        
        self.dev_ub = self.I(lambda: self.vwap[-1] + (self.b_mult_2 * self.std_dev[-1]) if len(self.vwap) > 0 and len(self.std_dev) > 0 and self.std_dev[-1] is not None else pd.Series(close.mean(), index=close.index))
        self.dev_lb = self.I(lambda: self.vwap[-1] - (self.b_mult_2 * self.std_dev[-1]) if len(self.vwap) > 0 and len(self.std_dev) > 0 and self.std_dev[-1] is not None else pd.Series(close.mean(), index=close.index))
        
        self.dev_uc = self.I(lambda: self.vwap[-1] + (self.b_mult_3 * self.std_dev[-1]) if len(self.vwap) > 0 and len(self.std_dev) > 0 and self.std_dev[-1] is not None else pd.Series(close.mean(), index=close.index))
        self.dev_lc = self.I(lambda: self.vwap[-1] - (self.b_mult_3 * self.std_dev[-1]) if len(self.vwap) > 0 and len(self.std_dev) > 0 and self.std_dev[-1] is not None else pd.Series(close.mean(), index=close.index))
        
        self.close_series = close

    def next(self):
        if len(self.data) < 2:
            return
        
        current_price = self.data.Close[-1]
        
        # Buy signal: price crosses above lower band C
        if self.position:
            # Exit logic
            if current_price > self.vwap[-1]:
                self.sell()
        else:
            # Entry logic: price touches lower band and bounces
            if current_price < self.dev_lc[-1] and len(self.data) > 1:
                if self.data.Close[-2] < self.data.Close[-1]:
                    self.buy()