"""
DS-TV Backtest Results: standard-deviation-ob-pressure
============================================================

--- SPY ---
  Return                    -60.53%
  Buy & Hold Return         39.08%
  Max Drawdown              -61.41%
  Sharpe Ratio              -3.85
  Sortino Ratio             -3.09
  Calmar Ratio              -0.61
  Profit Factor             0.38
  Expectancy                -0.31%
  SQN                       -3.70
  # Trades                  294
  Win Rate                  27.89%
  Best Trade                13.73%
  Worst Trade               -12.01%
  Avg Trade                 -0.32%
  Exposure Time             90.40%
  Equity Final              39466.22$
  Equity Peak               102274.07$
  Avg Drawdown              -16.44%
  Max Drawdown Duration     643 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -37.41%
  Ann. Volatility           9.72%

--- BTC ---
  Return                    -23.57%
  Buy & Hold Return         14.14%
  Max Drawdown              -32.64%
  Sharpe Ratio              -0.69
  Sortino Ratio             -0.83
  Calmar Ratio              -0.38
  Profit Factor             0.38
  Expectancy                -0.85%
  SQN                       -1.99
  # Trades                  57
  Win Rate                  31.58%
  Best Trade                6.60%
  Worst Trade               -13.95%
  Avg Trade                 -0.91%
  Exposure Time             28.45%
  Equity Final              76426.25$
  Equity Peak               102937.61$
  Avg Drawdown              -18.51%
  Max Drawdown Duration     659 days 00:00:00
  Max Trade Duration        35 days 00:00:00
  Avg Trade Duration        4 days 00:00:00
  Ann. Return               -12.56%
  Ann. Volatility           18.09%

--- QQQ ---
  Return                    -60.86%
  Buy & Hold Return         42.00%
  Max Drawdown              -64.17%
  Sharpe Ratio              -3.07
  Sortino Ratio             -2.52
  Calmar Ratio              -0.59
  Profit Factor             0.46
  Expectancy                -0.36%
  SQN                       -2.90
  # Trades                  258
  Win Rate                  30.23%
  Best Trade                18.32%
  Worst Trade               -16.42%
  Avg Trade                 -0.37%
  Exposure Time             91.80%
  Equity Final              39135.98$
  Equity Peak               106708.59$
  Avg Drawdown              -16.39%
  Max Drawdown Duration     661 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        3 days 00:00:00
  Ann. Return               -37.68%
  Ann. Volatility           12.27%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — standard-deviation-ob-pressure
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    len = 20
    max_sigma = 6

    def init(self):
        close = pd.Series(self.data.Close)
        
        self.ma = self.I(pta.rma, close, length=self.len)
        
        def calc_stdev(src):
            return src.rolling(window=self.len).std()
        
        self.dev = self.I(calc_stdev, close)
        
        self.upper_1 = self.I(lambda: self.ma + self.dev)
        self.lower_1 = self.I(lambda: self.ma - self.dev)
        self.upper_2 = self.I(lambda: self.ma + 2 * self.dev)
        self.lower_2 = self.I(lambda: self.ma - 2 * self.dev)
        self.upper_3 = self.I(lambda: self.ma + 3 * self.dev)
        self.lower_3 = self.I(lambda: self.ma - 3 * self.dev)

    def next(self):
        if len(self.data) < self.len + 1:
            return
        
        current_price = self.data.Close[-1]
        current_ma = self.ma[-1]
        current_dev = self.dev[-1]
        
        if np.isnan(current_ma) or np.isnan(current_dev):
            return
        
        upper_1 = current_ma + current_dev
        lower_1 = current_ma - current_dev
        upper_2 = current_ma + 2 * current_dev
        lower_2 = current_ma - 2 * current_dev
        upper_3 = current_ma + 3 * current_dev
        lower_3 = current_ma - 3 * current_dev
        
        if not self.position:
            if current_price <= lower_3 and current_price < self.data.Close[-2]:
                self.buy()
            elif current_price <= lower_2 and current_price < self.data.Close[-2]:
                self.buy()
            elif current_price <= lower_1 and current_price < self.data.Close[-2]:
                self.buy()
        else:
            if current_price >= upper_3:
                self.sell()
            elif current_price >= upper_2:
                self.sell()
            elif current_price >= upper_1:
                self.sell()
            elif current_price <= lower_3:
                self.sell()