"""
DS-TV Backtest Results: top-down-htf-candles-confirmed
============================================================

--- SPY ---
  Return                    -22.99%
  Buy & Hold Return         43.93%
  Max Drawdown              -23.78%
  Sharpe Ratio              -2.62
  Sortino Ratio             -2.60
  Calmar Ratio              -0.52
  Profit Factor             0.34
  Expectancy                -0.40%
  SQN                       -3.05
  # Trades                  63
  Win Rate                  33.33%
  Best Trade                1.53%
  Worst Trade               -4.13%
  Avg Trade                 -0.40%
  Exposure Time             25.60%
  Equity Final              77007.50$
  Equity Peak               101028.31$
  Avg Drawdown              -12.42%
  Max Drawdown Duration     683 days 00:00:00
  Max Trade Duration        3 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -12.34%
  Ann. Volatility           4.71%

--- BTC ---
  Return                    -18.00%
  Buy & Hold Return         44.64%
  Max Drawdown              -19.33%
  Sharpe Ratio              -0.89
  Sortino Ratio             -1.04
  Calmar Ratio              -0.49
  Profit Factor             0.69
  Expectancy                -0.44%
  SQN                       -1.15
  # Trades                  45
  Win Rate                  46.67%
  Best Trade                11.96%
  Worst Trade               -8.88%
  Avg Trade                 -0.49%
  Exposure Time             12.45%
  Equity Final              81996.21$
  Equity Peak               101649.46$
  Avg Drawdown              -10.87%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        2 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -9.44%
  Ann. Volatility           10.58%

--- QQQ ---
  Return                    -30.60%
  Buy & Hold Return         44.93%
  Max Drawdown              -30.67%
  Sharpe Ratio              -2.76
  Sortino Ratio             -2.54
  Calmar Ratio              -0.55
  Profit Factor             0.32
  Expectancy                -0.53%
  SQN                       -3.18
  # Trades                  66
  Win Rate                  27.27%
  Best Trade                1.87%
  Worst Trade               -6.00%
  Avg Trade                 -0.54%
  Exposure Time             27.00%
  Equity Final              69396.64$
  Equity Peak               100093.40$
  Avg Drawdown              -16.30%
  Max Drawdown Duration     678 days 00:00:00
  Max Trade Duration        4 days 00:00:00
  Avg Trade Duration        2 days 00:00:00
  Ann. Return               -16.82%
  Ann. Volatility           6.09%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — top-down-htf-candles-confirmed
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # HTF Settings
    htf_auto = True
    htf_manual = "60"
    num_candles = 8
    
    # Display
    gap_bars = 5
    candle_w = 8
    candle_gap = 2
    show_wicks = True
    show_labels = True
    show_pair = True
    
    # Liquidity & Structure
    show_swings = True
    swing_len = 3
    show_fvg = True
    show_bos = True
    extend_lvls = True
    extend_bars = 50
    
    # Trade Management
    tp_pct = 0.5
    sl_pct = 0.25
    max_bars = 40
    cooldown = 5
    rsi_len = 14
    rsi_ob = 70
    rsi_os = 30
    confirm_b = 2
    show_sig = True
    show_tpsl = True
    
    def init(self):
        # Initialize HTF data storage
        self.htf_data = {}
        self.signal_history = []
        
        # Calculate RSI
        close = pd.Series(self.data.Close)
        self.rsi = self.I(pta.rsi, close, length=self.rsi_len)
        
        # State tracking
        self.in_trade = False
        self.is_long = False
        self.entry_price = None
        self.entry_bar = None
        self.last_sig_bar = -self.cooldown
        self.tp = None
        self.sl = None
        
        # Prev bar trackers for cross detection
        self.prev_close = None
        self.prev_htf_h = None
        self.prev_htf_l = None
        self.prev_htf_mid = None
        self.prev_htf_o = None
        
        # Confirmation counters
        self.bars_above_l = 0
        self.bars_below_h = 0
        self.bars_above_mid = 0
        self.bars_below_mid = 0
        self.bars_above_o = 0
        self.bars_below_o = 0

    def get_htf_values(self):
        """Extract HTF values from current bar"""
        # In backtesting with single timeframe data, we approximate HTF using lookback
        # This is a simplified version - in production use proper multi-timeframe data
        lookback = 4  # Approximate HTF bars lookback
        
        if len(self.data) < lookback + 1:
            return None, None, None, None, None
        
        # Get approximate HTF candle
        close_arr = self.data.Close
        high_arr = self.data.High
        low_arr = self.data.Low
        open_arr = self.data.Open
        
        idx = -lookback
        htf_o = float(open_arr[idx])
        htf_h = float(high_arr[max(-len(high_arr), idx):].max())
        htf_l = float(low_arr[max(-len(low_arr), idx):].min())
        htf_c = float(close_arr[-1])
        
        return htf_o, htf_h, htf_l, htf_c, None

    def next(self):
        # Get HTF values
        htf_o, htf_h, htf_l, htf_c, _ = self.get_htf_values()
        
        if htf_o is None or htf_h is None or htf_l is None:
            return
        
        current_close = self.data.Close[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        
        # Calculate HTF levels
        htf_mid = (htf_h + htf_l) / 2.0 if not np.isnan(htf_h) and not np.isnan(htf_l) else None
        htf_range = htf_h - htf_l if not np.isnan(htf_h) and not np.isnan(htf_l) else None
        
        # HTF bias
        htf_bull = htf_c >= htf_o
        
        # Update confirmation counters
        if self.prev_htf_l is None or self.prev_htf_l == htf_l:
            if current_close > htf_l:
                self.bars_above_l += 1
            else:
                self.bars_above_l = 0
        else:
            self.bars_above_l = 0
        
        if self.prev_htf_h is None or self.prev_htf_h == htf_h:
            if current_close < htf_h:
                self.bars_below_h += 1
            else:
                self.bars_below_h = 0
        else:
            self.bars_below_h = 0
        
        if htf_mid is not None:
            if self.prev_htf_mid is None or self.prev_htf_mid == htf_mid:
                if current_close > htf_mid:
                    self.bars_above_mid += 1
                else:
                    self.bars_above_mid = 0
                if current_close < htf_mid:
                    self.bars_below_mid += 1
                else:
                    self.bars_below_mid = 0
            else:
                self.bars_above_mid = 0
                self.bars_below_mid = 0
        
        if htf_o is not None:
            if self.prev_htf_o is None or self.prev_htf_o == htf_o:
                if current_close > htf_o:
                    self.bars_above_o += 1
                else:
                    self.bars_above_o = 0
                if current_close < htf_o:
                    self.bars_below_o += 1
                else:
                    self.bars_below_o = 0
            else:
                self.bars_above_o = 0
                self.bars_below_o = 0
        
        # Check for trade exits
        if self.in_trade:
            tp_hit = (self.is_long and current_high >= self.tp) or (not self.is_long and current_low <= self.tp)
            sl_hit = (self.is_long and current_low <= self.sl) or (not self.is_long and current_high >= self.sl)
            time_exit = (len(self.data) - self.entry_bar) >= self.max_bars
            
            if tp_hit or sl_hit or time_exit:
                self.position.close()
                self.in_trade = False
        
        # Check for entry signals
        rsi_val = self.rsi[-1]
        bars_since_sig = len(self.data) - self.last_sig_bar
        
        if not self.in_trade and bars_since_sig >= self.cooldown:
            buy_signal = False
            sell_signal = False
            
            # HTF LOW (SSL reclaim) — buy
            if self.prev_htf_l == htf_l and self.bars_above_l == self.confirm_b and rsi_val < self.rsi_ob:
                buy_signal = True
            
            # HTF HIGH (BSL reclaim) — sell
            if self.prev_htf_h == htf_h and self.bars_below_h == self.confirm_b and rsi_val > self.rsi_os:
                sell_signal = True
            
            # HTF MID — both directions
            if htf_mid is not None and self.prev_htf_mid == htf_mid:
                if self.bars_above_mid == self.confirm_b and rsi_val < self.rsi_ob:
                    buy_signal = True
                if self.bars_below_mid == self.confirm_b and rsi_val > self.rsi_os:
                    sell_signal = True
            
            # HTF OPEN — both directions
            if htf_o is not None and self.prev_htf_o == htf_o:
                if self.bars_above_o == self.confirm_b and rsi_val < self.rsi_ob:
                    buy_signal = True
                if self.bars_below_o == self.confirm_b and rsi_val > self.rsi_os:
                    sell_signal = True
            
            # Execute buy signal
            if buy_signal:
                # TP = nearest HTF level above entry
                tp_candidates = []
                if htf_mid is not None and htf_mid > current_close:
                    tp_candidates.append(htf_mid)
                if htf_h > current_close:
                    tp_candidates.append(htf_h)
                
                if tp_candidates:
                    tp_target = min(tp_candidates)
                else:
                    tp_target = current_close * (1 + self.tp_pct / 100)
                
                sl_target = current_close * (1 - self.sl_pct / 100)
                
                self.buy()
                self.in_trade = True
                self.is_long = True
                self.entry_price = current_close
                self.entry_bar = len(self.data)
                self.last_sig_bar = len(self.data)
                self.tp = tp_target
                self.sl = sl_target
            
            # Execute sell signal
            elif sell_signal:
                # TP = nearest HTF level below entry
                tp_candidates = []
                if htf_mid is not None and htf_mid < current_close:
                    tp_candidates.append(htf_mid)
                if htf_l < current_close:
                    tp_candidates.append(htf_l)
                
                if tp_candidates:
                    tp_target = max(tp_candidates)
                else:
                    tp_target = current_close * (1 - self.tp_pct / 100)
                
                sl_target = current_close * (1 + self.sl_pct / 100)
                
                self.sell()
                self.in_trade = True
                self.is_long = False
                self.entry_price = current_close
                self.entry_bar = len(self.data)
                self.last_sig_bar = len(self.data)
                self.tp = tp_target
                self.sl = sl_target
        
        # Update prev bar trackers
        self.prev_close = current_close
        self.prev_htf_h = htf_h
        self.prev_htf_l = htf_l
        self.prev_htf_mid = htf_mid
        self.prev_htf_o = htf_o


if __name__ == "__main__":
    # Load your data here
    # Example: df = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    # For demonstration, create sample data
    dates = pd.date_range(start='2023-01-01', periods=1000, freq='1h')
    np.random.seed(42)
    closes = 100 + np.cumsum(np.random.randn(1000) * 0.5)
    highs = closes + np.abs(np.random.randn(1000) * 0.3)
    lows = closes - np.abs(np.random.randn(1000) * 0.3)
    opens = closes.shift(1).fillna(closes.iloc[0])
    volumes = np.random.randint(1000, 5000, 1000)
    
    df = pd.DataFrame({
        'Open': opens,
        'High': highs,
        'Low': lows,
        'Close': closes,
        'Volume': volumes
    }, index=dates)
    
    # Run backtest
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()