"""
DS-TV Backtest Results: vep-engine-sp-bps-strategy-filter
============================================================

--- SPY ---
  ERROR: Indicator "_calc_pass" error. See traceback above.

--- BTC ---
  ERROR: Indicator "_calc_pass" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "_calc_pass" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — vep-engine-sp-bps-strategy-filter
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    minPrice = 10
    minMktCapB = 10
    ma21Len = 21
    ma50Len = 50
    ma200Len = 200
    useRSI = True
    rsiLen = 14
    rsiMin = 45
    hvLen = 30
    ivLen = 10
    ivLookback = 252
    ivMode = "StdDev Proxy"
    dteDays = 45
    intervalWidth = 1.0
    vrpMin = 1.05
    ivRankMin = 40
    ivPctMin = 40
    useSPXFilter = False

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        self.ma21 = self.I(pta.sma, close, length=self.ma21Len)
        self.ma50 = self.I(pta.sma, close, length=self.ma50Len)
        self.ma200 = self.I(pta.sma, close, length=self.ma200Len)
        
        self.rsi = self.I(pta.rsi, close, length=self.rsiLen)
        
        log_returns = np.log(close / close.shift(1))
        self.hv = self.I(lambda x: pta.stdev(x, length=self.hvLen) * np.sqrt(252) * 100.0, log_returns)
        self.iv_proxy = self.I(lambda x: pta.stdev(x, length=self.ivLen) * np.sqrt(252) * 100.0, log_returns)
        
        avg_ret = self.I(pta.sma, log_returns, length=self.dteDays)
        st_ret = self.I(pta.stdev, log_returns, length=self.dteDays)
        
        self.iv_rank = self.I(self._calc_iv_rank, close)
        self.iv_pct = self.I(self._calc_iv_pct, close)
        
        self.atr = self.I(pta.atr, high, low, close, length=14)
        
        self.pass_filter = self.I(self._calc_pass, close, high, low)
        self.pullback_score = self.I(self._calc_pullback_score, close, high, low)
        
        self.in_trade = False

    def _calc_iv_rank(self, close_series):
        if len(close_series) < self.ivLookback:
            return pd.Series([np.nan] * len(close_series))
        
        iv_low = close_series.rolling(window=self.ivLookback).min()
        iv_high = close_series.rolling(window=self.ivLookback).max()
        
        iv_rank = pd.Series(index=close_series.index, dtype=float)
        for i in range(len(close_series)):
            if iv_high.iloc[i] != iv_low.iloc[i]:
                iv_rank.iloc[i] = 100.0 * (close_series.iloc[i] - iv_low.iloc[i]) / (iv_high.iloc[i] - iv_low.iloc[i])
            else:
                iv_rank.iloc[i] = np.nan
        
        return iv_rank

    def _calc_iv_pct(self, close_series):
        if len(close_series) < self.ivLookback:
            return pd.Series([np.nan] * len(close_series))
        
        iv_pct = pd.Series(index=close_series.index, dtype=float)
        for i in range(len(close_series)):
            if i < self.ivLookback - 1:
                iv_pct.iloc[i] = np.nan
            else:
                lookback_slice = close_series.iloc[i-self.ivLookback+1:i+1]
                cnt = (lookback_slice <= close_series.iloc[i]).sum()
                iv_pct.iloc[i] = 100.0 * cnt / self.ivLookback
        
        return iv_pct

    def _calc_pass(self, close_series, high_series, low_series):
        pass_series = pd.Series([False] * len(close_series), index=close_series.index)
        
        for i in range(len(close_series)):
            price_ok = close_series.iloc[i] >= self.minPrice
            
            trend_ok = (close_series.iloc[i] > self.ma21.iloc[i] and 
                       close_series.iloc[i] > self.ma50.iloc[i] and 
                       close_series.iloc[i] > self.ma200.iloc[i])
            
            rsi_ok = (not self.useRSI or 
                     (not np.isnan(self.rsi.iloc[i]) and self.rsi.iloc[i] >= self.rsiMin))
            
            vrp = self.iv_proxy.iloc[i] / self.hv.iloc[i] if (not np.isnan(self.hv.iloc[i]) and self.hv.iloc[i] > 0 and not np.isnan(self.iv_proxy.iloc[i])) else np.nan
            vrp_ok = not np.isnan(vrp) and vrp >= self.vrpMin
            
            iv_rank_ok = not np.isnan(self.iv_rank.iloc[i]) and self.iv_rank.iloc[i] >= self.ivRankMin
            iv_pct_ok = not np.isnan(self.iv_pct.iloc[i]) and self.iv_pct.iloc[i] >= self.ivPctMin
            
            vol_ok = vrp_ok and (iv_rank_ok or iv_pct_ok)
            
            pass_series.iloc[i] = price_ok and trend_ok and rsi_ok and vol_ok
        
        return pass_series

    def _calc_pullback_score(self, close_series, high_series, low_series):
        score_series = pd.Series([0.0] * len(close_series), index=close_series.index)
        
        for i in range(len(close_series)):
            score = 0.0
            
            if close_series.iloc[i] > self.ma50.iloc[i]:
                score += 15.0
            
            if close_series.iloc[i] > self.ma200.iloc[i]:
                score += 10.0
            
            if self.ma50.iloc[i] > self.ma200.iloc[i]:
                score += 10.0
            
            if close_series.iloc[i] <= self.ma21.iloc[i] and close_series.iloc[i] >= self.ma50.iloc[i]:
                score += 25.0
            elif close_series.iloc[i] > self.ma21.iloc[i] and ((close_series.iloc[i] - self.ma21.iloc[i]) / self.ma21.iloc[i]) <= 0.03:
                score += 20.0
            elif close_series.iloc[i] < self.ma21.iloc[i] and close_series.iloc[i] > self.ma50.iloc[i]:
                score += 15.0
            elif self.ma50.iloc[i] > 0 and abs(close_series.iloc[i] - self.ma50.iloc[i]) / self.ma50.iloc[i] <= 0.03 and close_series.iloc[i] > self.ma200.iloc[i]:
                score += 10.0
            
            if not np.isnan(self.rsi.iloc[i]):
                if 40 <= self.rsi.iloc[i] <= 55:
                    score += 20.0
                elif 35 <= self.rsi.iloc[i] <= 60:
                    score += 12.0
                elif 30 <= self.rsi.iloc[i] <= 65:
                    score += 5.0
            
            if not np.isnan(self.atr.iloc[i]) and self.atr.iloc[i] > 0:
                if close_series.iloc[i] >= self.data.Open[i]:
                    score += 10.0
                elif (self.data.Open[i] - close_series.iloc[i]) <= self.atr.iloc[i]:
                    score += 10.0
                elif (self.data.Open[i] - close_series.iloc[i]) <= 1.5 * self.atr.iloc[i]:
                    score += 5.0
            
            score = min(100.0, max(0.0, score))
            score_series.iloc[i] = score
        
        return score_series

    def next(self):
        current_pass = self.pass_filter[-1]
        current_pullback = self.pullback_score[-1]
        
        if not self.position:
            if current_pass and current_pullback >= 55:
                self.buy()
                self.in_trade = True
        else:
            if not current_pass or current_pullback < 40:
                self.position.close()
                self.in_trade = False


if __name__ == "__main__":
    data = pd.read_csv("data.csv", index_col=0, parse_dates=True)
    
    bt = Backtest(data, TvStrategy, cash=100000, commission=0.001)
    stats = bt.run()
    print(stats)
    bt.plot()