"""
DS-TV Backtest Results: vix-range-levels-rule-of-16
============================================================

--- SPY ---
  Return                    51.32%
  Buy & Hold Return         41.94%
  Max Drawdown              -14.18%
  Sharpe Ratio              1.20
  Sortino Ratio             2.35
  Calmar Ratio              1.64
  Profit Factor             4.19
  Expectancy                4.83%
  SQN                       1.75
  # Trades                  8
  Win Rate                  75.00%
  Best Trade                13.82%
  Worst Trade               -6.38%
  Avg Trade                 4.58%
  Exposure Time             79.60%
  Equity Final              151315.11$
  Equity Peak               151650.82$
  Avg Drawdown              -1.53%
  Max Drawdown Duration     147 days 00:00:00
  Max Trade Duration        174 days 00:00:00
  Avg Trade Duration        72 days 00:00:00
  Ann. Return               23.21%
  Ann. Volatility           19.28%

--- BTC ---
  Return                    45.02%
  Buy & Hold Return         46.22%
  Max Drawdown              -29.85%
  Sharpe Ratio              0.52
  Sortino Ratio             0.99
  Calmar Ratio              0.68
  Profit Factor             1.25
  Expectancy                0.53%
  SQN                       0.63
  # Trades                  118
  Win Rate                  56.78%
  Best Trade                11.51%
  Worst Trade               -14.31%
  Avg Trade                 0.38%
  Exposure Time             83.45%
  Equity Final              145020.00$
  Equity Peak               205118.40$
  Avg Drawdown              -3.73%
  Max Drawdown Duration     181 days 00:00:00
  Max Trade Duration        33 days 00:00:00
  Avg Trade Duration        5 days 00:00:00
  Ann. Return               20.39%
  Ann. Volatility           39.23%

--- QQQ ---
  Return                    31.22%
  Buy & Hold Return         42.67%
  Max Drawdown              -22.17%
  Sharpe Ratio              0.67
  Sortino Ratio             1.18
  Calmar Ratio              0.66
  Profit Factor             1.94
  Expectancy                1.35%
  SQN                       1.15
  # Trades                  23
  Win Rate                  65.22%
  Best Trade                16.09%
  Worst Trade               -6.92%
  Avg Trade                 1.22%
  Exposure Time             82.20%
  Equity Final              131218.58$
  Equity Peak               139231.16$
  Avg Drawdown              -2.75%
  Max Drawdown Duration     193 days 00:00:00
  Max Trade Duration        152 days 00:00:00
  Avg Trade Duration        25 days 00:00:00
  Ann. Return               14.68%
  Ann. Volatility           21.84%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — vix-range-levels-rule-of-16
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    volatility_multiplier = 1.0
    line_length = 20

    def init(self):
        pass

    def next(self):
        if len(self.data) < 2:
            return
        
        prev_close = self.data.Close[-2]
        current_close = self.data.Close[-1]
        
        vix_value = 20
        
        move_pct = (vix_value / 16.0) * self.volatility_multiplier
        exp_move = prev_close * move_pct / 100.0
        
        upper_1x = prev_close + exp_move
        lower_1x = prev_close - exp_move
        upper_15x = prev_close + exp_move * 1.5
        lower_15x = prev_close - exp_move * 1.5
        upper_2x = prev_close + exp_move * 2.0
        lower_2x = prev_close - exp_move * 2.0
        
        if not self.position:
            if current_close > upper_1x:
                self.buy()
            elif current_close < lower_1x:
                self.buy()
        else:
            if current_close < lower_2x or current_close > upper_2x:
                self.position.close()


if __name__ == '__main__':
    from datetime import datetime
    import yfinance as yf
    
    data = yf.download('SBIN.NS', start='2023-01-01', end='2024-01-01')
    
    bt = Backtest(data, TvStrategy, cash=100000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()