"""
DS-TV Backtest Results: volatility-atr-volume-combo
============================================================

--- SPY ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(λ,5)" shape: , returned value: None)

--- BTC ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (731,); indicator "sma(λ,5)" shape: , returned value: None)

--- QQQ ---
  ERROR: Indicators must return (optionally a tuple of) numpy.arrays of same length as `data` (data shape: (500,); indicator "sma(λ,5)" shape: , returned value: None)

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volatility-atr-volume-combo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    atrLength = 14
    volSmoothing = 20
    atrWeight = 0.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate ATR
        atr = self.I(pta.atr, high, low, close, length=self.atrLength)
        
        # Normalize ATR as % of price
        atr_norm = self.I(lambda: (atr / close * 100) if atr is not None else pd.Series(0, index=close.index))
        
        # Volume calculations
        avg_vol = self.I(pta.sma, volume, length=self.volSmoothing)
        vol_ratio = self.I(lambda: (volume / avg_vol * 100) if avg_vol is not None else pd.Series(100, index=volume.index))
        
        # Combined volatility index
        volatility_score = self.I(lambda: self.atrWeight * atr_norm + (1 - self.atrWeight) * vol_ratio)
        
        # Smoothed volatility score
        self.v_score_smooth = self.I(pta.sma, volatility_score, length=5)
        
        # Baseline
        self.baseline = self.I(pta.sma, self.v_score_smooth, length=50)
        
        # Store for regime detection
        self.high_vol_threshold = self.baseline * 1.2
        self.low_vol_threshold = self.baseline * 0.8

    def next(self):
        # Check if we have valid data
        if len(self.data) < 60:
            return
        
        # Get current values
        current_score = self.v_score_smooth[-1]
        current_baseline = self.baseline[-1]
        high_threshold = self.high_vol_threshold[-1]
        low_threshold = self.low_vol_threshold[-1]
        
        # Detect volatility regimes
        high_vol = current_score > high_threshold
        low_vol = current_score < low_threshold
        
        # Trading logic based on volatility regimes
        # Buy on low volatility (potential breakout setup)
        if low_vol and not self.position:
            self.buy()
        
        # Exit on high volatility (risk management)
        elif high_vol and self.position:
            self.sell()
        
        # Also exit if volatility returns to normal from low vol
        elif not low_vol and not high_vol and self.position:
            if self.position.size > 0:
                self.sell()