"""
DS-TV Backtest Results: volatility-adjusted-rate-of-change-quantalgo
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         46.22%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — volatility-adjusted-rate-of-change-quantalgo
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    sensitivity = 1.0
    atr_length = 10
    ma_type = 'EMA'
    ma_length = 3
    upper_threshold = 0.5
    lower_threshold = -0.5
    upper_extreme = 1.5
    lower_extreme = -1.5

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Calculate ATR
        atr = self.I(pta.atr, high, low, close, length=self.atr_length)
        
        # Calculate price momentum (change / ATR)
        def calc_momentum():
            momentum = close.diff() / atr
            return momentum
        
        momentum = self.I(calc_momentum)
        
        # Calculate volatility-adjusted ROC with smoothing
        def calc_va_roc():
            adj_momentum = momentum * self.sensitivity
            
            if self.ma_type == 'SMA':
                result = pta.sma(adj_momentum, length=self.ma_length)
            elif self.ma_type == 'EMA':
                result = pta.ema(adj_momentum, length=self.ma_length)
            elif self.ma_type == 'WMA':
                result = pta.wma(adj_momentum, length=self.ma_length)
            elif self.ma_type == 'RMA':
                result = pta.rma(adj_momentum, length=self.ma_length)
            elif self.ma_type == 'HMA':
                result = pta.hma(adj_momentum, length=self.ma_length)
            elif self.ma_type == 'VWMA':
                volume = pd.Series(self.data.Volume)
                result = pta.vwma(adj_momentum, volume, length=self.ma_length)
            elif self.ma_type == 'DEMA':
                e1 = pta.ema(adj_momentum, length=self.ma_length)
                e2 = pta.ema(e1, length=self.ma_length)
                result = 2 * e1 - e2
            elif self.ma_type == 'TEMA':
                e1 = pta.ema(adj_momentum, length=self.ma_length)
                e2 = pta.ema(e1, length=self.ma_length)
                e3 = pta.ema(e2, length=self.ma_length)
                result = 3 * e1 - 3 * e2 + e3
            else:
                result = pta.ema(adj_momentum, length=self.ma_length)
            
            return result if result is not None else pd.Series(0, index=close.index)
        
        self.va_roc = self.I(calc_va_roc)

    def next(self):
        # Entry and exit based on volatility-adjusted ROC crossover thresholds
        
        # Buy signal: oscillator crosses above upper threshold
        if len(self.va_roc) > 1:
            if crossover(self.va_roc, self.upper_threshold):
                if not self.position:
                    self.buy()
        
        # Sell signal: oscillator crosses below lower threshold
        if len(self.va_roc) > 1:
            if crossover(self.lower_threshold, self.va_roc):
                if self.position:
                    self.position.close()


if __name__ == '__main__':
    from backtesting.test import GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()