"""
DS-TV Backtest Results: z-score-normal-distribution-with-alerts
============================================================

--- SPY ---
  Return                    19.52%
  Buy & Hold Return         39.08%
  Max Drawdown              -18.30%
  Sharpe Ratio              0.73
  Sortino Ratio             1.10
  Calmar Ratio              0.51
  Profit Factor             1.84
  Expectancy                1.41%
  SQN                       0.79
  # Trades                  14
  Win Rate                  42.86%
  Best Trade                14.56%
  Worst Trade               -6.49%
  Avg Trade                 1.24%
  Exposure Time             57.80%
  Equity Final              119520.97$
  Equity Peak               123424.40$
  Avg Drawdown              -2.41%
  Max Drawdown Duration     250 days 00:00:00
  Max Trade Duration        77 days 00:00:00
  Avg Trade Duration        29 days 00:00:00
  Ann. Return               9.40%
  Ann. Volatility           12.83%

--- BTC ---
  Return                    19.20%
  Buy & Hold Return         14.14%
  Max Drawdown              -18.99%
  Sharpe Ratio              0.38
  Sortino Ratio             0.63
  Calmar Ratio              0.48
  Profit Factor             1.42
  Expectancy                1.38%
  SQN                       0.59
  # Trades                  22
  Win Rate                  50.00%
  Best Trade                16.47%
  Worst Trade               -9.64%
  Avg Trade                 1.00%
  Exposure Time             42.13%
  Equity Final              119195.73$
  Equity Peak               142661.67$
  Avg Drawdown              -4.36%
  Max Drawdown Duration     143 days 00:00:00
  Max Trade Duration        39 days 00:00:00
  Avg Trade Duration        13 days 00:00:00
  Ann. Return               9.16%
  Ann. Volatility           24.43%

--- QQQ ---
  Return                    19.30%
  Buy & Hold Return         42.00%
  Max Drawdown              -20.23%
  Sharpe Ratio              0.58
  Sortino Ratio             0.87
  Calmar Ratio              0.46
  Profit Factor             1.69
  Expectancy                2.16%
  SQN                       0.50
  # Trades                  10
  Win Rate                  40.00%
  Best Trade                20.33%
  Worst Trade               -8.62%
  Avg Trade                 1.69%
  Exposure Time             50.20%
  Equity Final              119299.25$
  Equity Peak               126457.91$
  Avg Drawdown              -3.44%
  Max Drawdown Duration     230 days 00:00:00
  Max Trade Duration        97 days 00:00:00
  Avg Trade Duration        35 days 00:00:00
  Ann. Return               9.30%
  Ann. Volatility           15.91%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — z-score-normal-distribution-with-alerts
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    length = 20

    def init(self):
        close = pd.Series(self.data.Close)
        
        # Calculate mean (SMA)
        self.mean = self.I(pta.sma, close, length=self.length)
        
        # Calculate standard deviation
        self.stdDev = self.I(lambda x: x.rolling(self.length).std(), close)
        
        # Calculate Z-Score
        self.zScore = self.I(lambda: (close - self.mean) / (self.stdDev + 1e-10))

    def next(self):
        if len(self.data) < self.length:
            return
        
        # Get current Z-Score value
        z_current = self.zScore[-1]
        z_previous = self.zScore[-2] if len(self.zScore) > 1 else z_current
        
        # Buy signal: Z-Score crosses above -2 (oversold)
        if z_previous <= -2.0 and z_current > -2.0:
            if not self.position:
                self.buy()
        
        # Sell signal: Z-Score crosses below +2 (overbought)
        elif z_previous >= 2.0 and z_current < 2.0:
            if self.position:
                self.position.close()
        
        # Alternative sell: Z-Score crosses below -2 from above (mean reversion continuation)
        elif z_previous >= -2.0 and z_current < -2.0:
            if self.position:
                self.position.close()
        
        # Exit on extreme moves (Z > 3 or Z < -3)
        elif z_current > 3.0 or z_current < -3.0:
            if self.position:
                self.position.close()


if __name__ == "__main__":
    from datetime import datetime
    
    # Load data
    df = pd.read_csv('data.csv', index_col=0, parse_dates=True)
    
    # Run backtest
    bt = Backtest(df, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()