// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © SuprAlgo

//@version=6
//@author=supralgo

//   _________                     _____  .__                  
//  /   _____/__ _______________  /  _  \ |  |    ____   ____  
//  \_____  \|  |  \____ \_  __ \/  /_\  \|  |   / ___\ /  _ \ 
//  /        \  |  /  |_> >  | \/    |    \  |__/ /_/  >  <_> )
// /_______  /____/|   __/|__|  \____|__  /____/\___  / \____/ 
//         \/      |__|                 \/     /_____/         

indicator("High Volatility Zones by Volumes [SuprAlgo]", format = format.volume)

// === SETTINGS ===

maSmooth = input.string("SMA", title="Moving Average Type", options=["SMA", "EMA"], group = "Settings",display = display.data_window)
maLength = input.int(200, title="Moving Average Length", minval = 0, group = "Settings",display = display.data_window)
Multiplier_Vol = input.float(1, "Moving Average Multiplier", minval = 0, group = "Settings",display = display.data_window)

// === OVERLAYS SETTINGS ===

color color_bullish = input.color(#03ff00, "Bullish Color",group = "Overlays",display = display.data_window)
color color_bearish = input.color(#ff0000, "Bearish Color",group = "Overlays",display = display.data_window)

BGZones = input.bool(true, inline = "3", title="Background Zones",group = "Overlays", display = display.data_window)
BGTransp = input.int(75, title="", inline = "3", minval = 0,maxval = 100,group = "Overlays",display = display.data_window, tooltip = "Opacity\n\nYou can adjust the opacity of the High-Volatility Zones background.\n\nA value of 0 means fully visible, while 100 makes them completely invisible.")

VolumeColors = input.bool(true, inline = "4", title="Heatmap Volume ",group = "Overlays", display = display.data_window)
VolTransp = input.int(0, title="", inline = "4", minval = 0,maxval = 100,group = "Overlays",display = display.data_window, tooltip = "Opacity\n\nYou can adjust the opacity of the volume bars outside High-Volatility Volume bars above the VWMA.\n\nA value of 0 means fully visible, while 100 makes them completely invisible.")

bool ma_draws = input.bool(true, "Volume Weighted Moving Average",group = "Overlays", inline = "5",display = display.data_window)
maColor = input.color(color.white, title="", inline = "5",group = "Overlays",display = display.data_window) 

// === VOLUME WEIGHTED MOVING AVERAGE CALCULATION ===

ma_vol = maSmooth == "EMA" ? ta.ema(volume, maLength) : maSmooth == "SMA" ? ta.sma(volume, maLength) : na
ma_vol_final = ma_vol * Multiplier_Vol

// === OVERLAYS CALCULATION ===

volume_color = close > open ? color_bullish : close < open ? color_bearish : color.white
bool is_valid_ma = (volume >= ma_vol_final)
color ma_gradient_color = color.from_gradient(volume - (ma_vol * Multiplier_Vol), (-ma_vol * Multiplier_Vol), (ma_vol * Multiplier_Vol),color_bullish,color_bearish)
barcolor_to_use = VolumeColors ? (volume > ma_vol_final ? color.new(ma_gradient_color, 0) : color.new(ma_gradient_color, VolTransp)) : (volume > ma_vol_final ? color.new(volume_color, 0) : color.new(volume_color, VolTransp))

// === VOLUME / BACKGROUND / VWMA PLOTS ===

plot(volume, style=plot.style_columns, color=barcolor_to_use, title="Volume", format = format.volume, editable = false,display = display.all)
plot(ma_draws  ? ma_vol_final : na, title="Volume Weighted Moving Average", linestyle = plot.linestyle_dotted,color=color.new(maColor, 0), linewidth=1, editable = false, format = format.volume, display = display.all)
bgcolor(BGZones ? (is_valid_ma ? color.new(barcolor_to_use, BGTransp) : color.new(barcolor_to_use, BGTransp)) : (is_valid_ma ? color.new(barcolor_to_use, 100) : color.new(barcolor_to_use, 100)), editable = false, force_overlay = true)

// === ALERT CONDITION ===

alertcondition(is_valid_ma, "🔔 High Volatility Volume above the VWMA", "🔥 High Volatility Volume above the VWMA detected! 🔥")
