//@version=5
indicator(title="J - ATR Trend Channel", overlay=true)

//------------------------------
fastLen            = input.int(defval=6,   title="Fast Length")
ATRPeriod          = input.int(defval=16,  title="ATR Period")
ATRMultip          = input.float(defval=5.1, title="ATR Multiplier")
candleStickBackground = input.bool(defval=true, title="Band Fill")
//------------------------------

aTR = ta.atr(ATRPeriod)
nl  = ATRMultip * aTR

var float defATR  = na
var float defATR1 = na
var float defATR2 = na

defATR  := close > nz(defATR[1])  and close[1] > nz(defATR[1])  ? math.max(nz(defATR[1]),  close - nl) : close < nz(defATR[1])  and close[1] < nz(defATR[1])  ? math.min(nz(defATR[1]),  close + nl) : close > nz(defATR[1])  ? close - nl : close + nl
defATR1 := close > nz(defATR1[1]) and close[1] > nz(defATR1[1]) ? math.max(nz(defATR1[1]), close - nl) : close < nz(defATR1[1]) and close[1] < nz(defATR1[1]) ? math.min(nz(defATR1[1]), close + nl) : close < nz(defATR1[1]) ? close + nl : close + nl
defATR2 := close > nz(defATR2[1]) and close[1] > nz(defATR2[1]) ? math.max(nz(defATR2[1]), close - nl) : close < nz(defATR2[1]) and close[1] < nz(defATR2[1]) ? math.min(nz(defATR2[1]), close + nl) : close > nz(defATR2[1]) ? close + nl : close - nl

plot(defATR, color=color.new(color.yellow, 50), linewidth=1, title="ATR Trailing Stop")

//--------

cc = ta.sma(close, fastLen)
oo = ta.sma(open,  fastLen)
hh = ta.sma(high,  fastLen)
ll = ta.sma(low,   fastLen)
lv = math.abs(cc - oo) / (hh - ll)

var float a = na
a := lv * close + (1 - lv) * nz(a[1], close)

//--------

ss  = defATR  > a ? defATR  - (defATR  - a) / 2 : defATR  + (a - defATR)  / 2
ss1 = defATR1 > a ? defATR1 - (defATR1 - a) / 2 : defATR1 + (a - defATR1) / 2
ss2 = defATR2 > a ? defATR2 - (defATR2 - a) / 2 : defATR2 + (a - defATR2) / 2

p11 = plot(ss,  color=color.new(color.fuchsia, 20), linewidth=1, title="Mid Band")
p22 = plot(ss1, color=color.new(color.lime,    20), linewidth=1, title="Bull Band")
p33 = plot(ss2, color=color.new(color.blue,    20), linewidth=1, title="Bear Band")

fill(p11, p22, color=defATR < defATR1 ? color.new(color.lime,    candleStickBackground ? 93 : 100) : na)
fill(p11, p33, color=defATR > defATR2 ? color.new(color.fuchsia, candleStickBackground ? 93 : 100) : na)

//==========================================================================================================

jlong  = ta.crossover(a,  defATR)
jshort = ta.crossunder(a, defATR)

plotshape(jlong,  title="Long",  text="Long",  textcolor=color.white, style=shape.labelup,   size=size.tiny, location=location.belowbar, color=color.new(color.lime,    0))
plotshape(jshort, title="Short", text="Short", textcolor=color.white, style=shape.labeldown, size=size.tiny, location=location.abovebar, color=color.new(color.fuchsia, 0))

alertcondition(jlong,  title="Long",  message="ATR Trend Channel: Long Signal")
alertcondition(jshort, title="Short", message="ATR Trend Channel: Short Signal")
