"""
DS-TV Backtest Results: absorption-signals
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         39.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.00%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — absorption-signals
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Absorption Settings
    abs_volume_lookback = 20
    abs_zscore_threshold = 1.5
    abs_wick_threshold = 0.30
    
    # Confidence Settings
    abs_min_confidence = 2
    abs_require_multi_bar = True
    abs_multi_bar_tolerance = 0.3
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        open_ = pd.Series(self.data.Open)
        volume = pd.Series(self.data.Volume)
        
        # ATR calculation
        self.atr = self.I(pta.atr, high, low, close, length=14)
        
        # Volume analysis
        self.avg_volume = self.I(pta.sma, volume, length=self.abs_volume_lookback)
        self.stdev_volume = self.I(lambda: volume.rolling(self.abs_volume_lookback).std())
        
        # Bar delta (simplified - using close - open as proxy)
        self.bar_delta = self.I(lambda: close - open_)
        
        # Store previous values for multi-bar confirmation
        self.prev_bull_level = np.nan
        self.prev_bull_bar = 0
        self.prev_bear_level = np.nan
        self.prev_bear_bar = 0
        
        # Tracking for signals
        self.last_bullish_signal = -100
        self.last_bearish_signal = -100
    
    def next(self):
        if len(self.data) < self.abs_volume_lookback + 5:
            return
        
        # Current bar values
        current_close = self.data.Close[-1]
        current_open = self.data.Open[-1]
        current_high = self.data.High[-1]
        current_low = self.data.Low[-1]
        current_volume = self.data.Volume[-1]
        current_atr = self.atr[-1]
        avg_vol = self.avg_volume[-1]
        stdev_vol = self.stdev_volume[-1]
        bar_delta = self.bar_delta[-1]
        
        # Volume Z-score
        if stdev_vol > 0:
            volume_zscore = (current_volume - avg_vol) / stdev_vol
        else:
            volume_zscore = 0
        
        volume_anomaly = volume_zscore >= self.abs_zscore_threshold
        
        # Wick calculations
        bar_range = current_high - current_low
        upper_wick = current_high - max(current_open, current_close)
        lower_wick = min(current_open, current_close) - current_low
        
        if bar_range > 0:
            upper_wick_pct = upper_wick / bar_range
            lower_wick_pct = lower_wick / bar_range
        else:
            upper_wick_pct = 0
            lower_wick_pct = 0
        
        # Absorption detection
        bullish_absorption = bar_delta < 0 and volume_anomaly and (current_close >= current_open)
        bearish_absorption = bar_delta > 0 and volume_anomaly and (current_close <= current_open)
        
        # Confidence scoring for bullish
        bull_confidence = 0.0
        if bullish_absorption:
            bull_confidence = 1.0
            if volume_zscore >= 2.0:
                bull_confidence += 1.0
            if volume_zscore >= 3.0:
                bull_confidence += 1.0
            if abs(bar_delta) >= 2.0:
                bull_confidence += 1.0
            if lower_wick_pct >= 0.4:
                bull_confidence += 1.0
            bull_confidence = min(bull_confidence, 5.0)
        
        # Confidence scoring for bearish
        bear_confidence = 0.0
        if bearish_absorption:
            bear_confidence = 1.0
            if volume_zscore >= 2.0:
                bear_confidence += 1.0
            if volume_zscore >= 3.0:
                bear_confidence += 1.0
            if abs(bar_delta) >= 2.0:
                bear_confidence += 1.0
            if upper_wick_pct >= 0.4:
                bear_confidence += 1.0
            bear_confidence = min(bear_confidence, 5.0)
        
        # Trading logic
        bull_signal = bullish_absorption and bull_confidence >= self.abs_min_confidence
        bear_signal = bearish_absorption and bear_confidence >= self.abs_min_confidence
        
        # Entry on bullish absorption signal
        if bull_signal and len(self.data) - self.last_bullish_signal > 5:
            if not self.position:
                self.buy()
            self.last_bullish_signal = len(self.data)
        
        # Entry on bearish absorption signal
        if bear_signal and len(self.data) - self.last_bearish_signal > 5:
            if self.position:
                self.position.close()
            self.last_bearish_signal = len(self.data)
        
        # Exit logic - simple time-based or reversal
        if self.position:
            if len(self.data) - self.last_bullish_signal > 20:
                self.position.close()
            elif bear_signal and bull_confidence < bear_confidence:
                self.position.close()