"""
DS-TV Backtest Results: mapa-de-calor-de-volume
============================================================

--- SPY ---
  Return                    -19.33%
  Buy & Hold Return         39.08%
  Max Drawdown              -38.62%
  Sharpe Ratio              -0.64
  Sortino Ratio             -0.79
  Calmar Ratio              -0.27
  Profit Factor             0.85
  Expectancy                -1.34%
  SQN                       -0.24
  # Trades                  4
  Win Rate                  75.00%
  Best Trade                14.73%
  Worst Trade               -36.06%
  Avg Trade                 -3.90%
  Exposure Time             59.60%
  Equity Final              80667.50$
  Equity Peak               131103.49$
  Avg Drawdown              -3.26%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        189 days 00:00:00
  Avg Trade Duration        109 days 00:00:00
  Ann. Return               -10.26%
  Ann. Volatility           15.95%

--- BTC ---
  Return                    -30.00%
  Buy & Hold Return         14.14%
  Max Drawdown              -33.82%
  Sharpe Ratio              -0.86
  Sortino Ratio             -0.92
  Calmar Ratio              -0.48
  Profit Factor             0.22
  Expectancy                -13.63%
  SQN                       -0.79
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                10.97%
  Worst Trade               -63.12%
  Avg Trade                 -20.56%
  Exposure Time             34.75%
  Equity Final              70001.66$
  Equity Peak               104910.38$
  Avg Drawdown              -14.95%
  Max Drawdown Duration     554 days 00:00:00
  Max Trade Duration        122 days 00:00:00
  Avg Trade Duration        64 days 00:00:00
  Ann. Return               -16.31%
  Ann. Volatility           19.01%

--- QQQ ---
  Return                    -61.20%
  Buy & Hold Return         42.00%
  Max Drawdown              -66.42%
  Sharpe Ratio              -2.02
  Sortino Ratio             -1.71
  Calmar Ratio              -0.57
  Profit Factor             0.00
  Expectancy                -21.40%
  SQN                       nan
  # Trades                  1
  Win Rate                  0.00%
  Best Trade                -21.40%
  Worst Trade               -21.40%
  Avg Trade                 -21.40%
  Exposure Time             14.20%
  Equity Final              38800.48$
  Equity Peak               103734.99$
  Avg Drawdown              -24.85%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        105 days 00:00:00
  Avg Trade Duration        105 days 00:00:00
  Ann. Return               -37.95%
  Ann. Volatility           18.79%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — mapa-de-calor-de-volume
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    periodoVol = 20
    v_lv1 = 1.2
    v_lv2 = 2.0
    v_lv3 = 3.0
    v_lv4 = 4.5
    cor_alta_r = 8
    cor_alta_g = 153
    cor_alta_b = 129
    cor_baixa_r = 242
    cor_baixa_g = 54
    cor_baixa_b = 69

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        volume = pd.Series(self.data.Volume)
        
        # Calculate volume moving average
        self.volMedia = self.I(pta.sma, volume, length=self.periodoVol)
        
        # Calculate relative volume
        def calc_vol_relativo():
            vol_rel = volume / self.volMedia
            return vol_rel.fillna(1.0)
        
        self.volRelativo = self.I(calc_vol_relativo)
        
        # Track if candle is up or down
        def is_up():
            return (close >= open_).astype(float)
        
        self.ehAlta = self.I(is_up)
        
        # Store colors for visualization
        self.colors = []

    def next(self):
        # Get current values
        vol_rel = self.volRelativo[-1]
        eh_alta = self.ehAlta[-1] > 0.5
        
        # Determine base color based on direction
        if eh_alta:
            r = self.cor_alta_r
            g = self.cor_alta_g
            b = self.cor_alta_b
        else:
            r = self.cor_baixa_r
            g = self.cor_baixa_g
            b = self.cor_baixa_b
        
        # Determine intensity based on volume level
        if vol_rel >= self.v_lv4:
            intensity = 4
        elif vol_rel >= self.v_lv3:
            intensity = 3
        elif vol_rel >= self.v_lv2:
            intensity = 2
        elif vol_rel >= self.v_lv1:
            intensity = 1
        else:
            intensity = 0
        
        # Trading logic: Buy on strong up candles with high volume, sell on strong down candles with high volume
        if eh_alta and vol_rel >= self.v_lv2 and not self.position:
            self.buy()
        elif not eh_alta and vol_rel >= self.v_lv2 and self.position:
            self.sell()


if __name__ == "__main__":
    from datetime import datetime
    
    # Load data (example with EURUSD)
    data = pd.read_csv("data.csv", index_col=0, parse_dates=True)
    
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()