"""
DS-TV Backtest Results: vsa-simple
============================================================

--- SPY ---
  Return                    -18.96%
  Buy & Hold Return         36.39%
  Max Drawdown              -25.47%
  Sharpe Ratio              -0.85
  Sortino Ratio             -1.19
  Calmar Ratio              -0.39
  Profit Factor             0.28
  Expectancy                -4.37%
  SQN                       -0.79
  # Trades                  4
  Win Rate                  50.00%
  Best Trade                6.70%
  Worst Trade               -20.03%
  Avg Trade                 -4.91%
  Exposure Time             36.60%
  Equity Final              81042.45$
  Equity Peak               108491.03$
  Avg Drawdown              -12.25%
  Max Drawdown Duration     283 days 00:00:00
  Max Trade Duration        228 days 00:00:00
  Avg Trade Duration        67 days 00:00:00
  Ann. Return               -10.05%
  Ann. Volatility           11.83%

--- BTC ---
  Return                    -29.46%
  Buy & Hold Return         1.20%
  Max Drawdown              -40.02%
  Sharpe Ratio              -1.15
  Sortino Ratio             -1.21
  Calmar Ratio              -0.40
  Profit Factor             0.29
  Expectancy                -6.00%
  SQN                       -0.97
  # Trades                  7
  Win Rate                  57.14%
  Best Trade                12.67%
  Worst Trade               -41.34%
  Avg Trade                 -7.64%
  Exposure Time             16.14%
  Equity Final              70540.19$
  Equity Peak               113536.92$
  Avg Drawdown              -9.95%
  Max Drawdown Duration     522 days 00:00:00
  Max Trade Duration        42 days 00:00:00
  Avg Trade Duration        17 days 00:00:00
  Ann. Return               -15.99%
  Ann. Volatility           13.88%

--- QQQ ---
  Return                    -19.83%
  Buy & Hold Return         39.47%
  Max Drawdown              -31.52%
  Sharpe Ratio              -0.72
  Sortino Ratio             -1.01
  Calmar Ratio              -0.33
  Profit Factor             0.31
  Expectancy                -5.09%
  SQN                       -0.81
  # Trades                  4
  Win Rate                  25.00%
  Best Trade                9.24%
  Worst Trade               -21.53%
  Avg Trade                 -5.75%
  Exposure Time             36.40%
  Equity Final              80173.63$
  Equity Peak               111412.07$
  Avg Drawdown              -8.74%
  Max Drawdown Duration     283 days 00:00:00
  Max Trade Duration        203 days 00:00:00
  Avg Trade Duration        66 days 00:00:00
  Ann. Return               -10.54%
  Ann. Volatility           14.70%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — vsa-simple
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    ma_length = 30

    def init(self):
        volume = pd.Series(self.data.Volume)
        self.ma = self.I(pta.sma, volume, length=self.ma_length)
        self.volume_series = self.I(lambda: pd.Series(self.data.Volume))

    def next(self):
        if len(self.ma) < 2:
            return
        
        current_volume = self.data.Volume[-1]
        current_ma = self.ma[-1]
        
        if current_ma is None or np.isnan(current_ma):
            return
        
        # Buy signal: volume spike above 3x MA (high volume confirmation)
        if current_volume > current_ma * 3:
            if not self.position:
                self.buy()
        # Sell signal: volume drops below 0.5x MA (low volume, potential weakness)
        elif current_volume < current_ma * 0.5:
            if self.position:
                self.sell()


if __name__ == '__main__':
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)