// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Since 2020 Zofesu

//@version=6
indicator("Liquidity Magnets [Zofesu]", shorttitle="Zofesu - Liquidity Magnets", overlay = true, max_lines_count = 500)

// --- SETTINGS ---
tf_input       = input.timeframe("480", "Select TF for both signals and magnets")
show_leverage  = input.bool(true, "Show liquidation magnets")
show_yellow    = input.bool(true, "Show 4% magnets (Yellow lines)")
lookback       = input.int(20, "Lookback for Swing High/Low")
line_len       = input.int(10, "Line length (in bars)", minval=1)
sens           = input.float(10.0, "Signal Sensitivity %", minval=0, maxval=100, tooltip="0 means you will see every sweep. 100 means it must hit the 4% line exactly.")

// --- COLOR SETTINGS ---
group_colors = "Color settings"
color_bear_1 = input.color(color.new(#b80000, 0), "Bearish Magnet 10%", group=group_colors)
color_bear_2 = input.color(color.new(#ffee00, 30), "Bearish Magnet 4%", group=group_colors)
color_bull_1 = input.color(color.new(#009705, 0), "Bullish Magnet 10%", group=group_colors)
color_bull_2 = input.color(color.new(#ffee00, 30), "Bullish Magnet 4%", group=group_colors)

// --- FUNCTION FOR LOGIC ---
get_signals() =>
    hi_p = ta.highest(high, lookback)
    lo_p = ta.lowest(low, lookback)
    
    // Baselines
    upper_4 = hi_p * 1.04
    lower_4 = lo_p * 0.96
    
    // Raw sweep
    s_down_raw = low < lo_p[1] and close > lo_p[1]
    s_up_raw   = high > hi_p[1] and close < hi_p[1]
    
    dist_up   = (high - hi_p[1]) / (upper_4 - hi_p[1]) * 100
    dist_down = (lo_p[1] - low) / (lo_p[1] - lower_4) * 100
    
    s_up   = s_up_raw and dist_up >= sens
    s_down = s_down_raw and dist_down >= sens
    
    [s_down, s_up, hi_p, lo_p]

// --- OBTAINING MTF DATA ---
[sweep_down, sweep_up, hi_mtf, lo_mtf] = request.security(syminfo.tickerid, tf_input, get_signals(), lookahead = barmerge.lookahead_on)

// --- LIQUIDATION MAGNETS (Line Logic) ---
if show_leverage
    if ta.change(hi_mtf) != 0
        line.new(bar_index, hi_mtf * 1.10, bar_index + line_len, hi_mtf * 1.10, color = color_bear_1, width = 2)
        if show_yellow
            line.new(bar_index, hi_mtf * 1.04, bar_index + line_len, hi_mtf * 1.04, color = color_bear_2, width = 1)
    
    if ta.change(lo_mtf) != 0
        line.new(bar_index, lo_mtf * 0.90, bar_index + line_len, lo_mtf * 0.90, color = color_bull_1, width = 2)
        if show_yellow
            line.new(bar_index, lo_mtf * 0.96, bar_index + line_len, lo_mtf * 0.96, color = color_bull_2, width = 1)

// --- SIGNALING ON THE CHART ---
plotshape(sweep_down, "STOP-RUN LONG", shape.triangleup, location.belowbar, color = color.rgb(154, 157, 160), size = size.small)
plotshape(sweep_up, "STOP-RUN SHORT", shape.triangledown, location.abovebar, color = color.rgb(154, 157, 160), size = size.small)

// Candlestick coloring
barcolor(sweep_down ? color.rgb(2, 2, 2) : sweep_up ? color.rgb(0, 0, 0) : na)
