//@version=5
indicator('MIDAS Curves[5 groups]', shorttitle='MIDAS [5]', overlay=true)

//plot(bar_index, style=plot.style_area, color=color.yellow, transp=100) DEBUG for TB-F

//------------------------------------------------------------------------------
// Inputs

md1_enabled = input.bool(false, '#1 Enable', group='1')
md1_date = input.time(timestamp('01 Jun 2025 00:00 +0000'), '#1 Start Time', group='1')
md1_src_high = input.source(high, '#1 high', group='1')
md1_src_mid = input.source(hl2, '#1 mid', group='1')
md1_src_low = input.source(low, '#1 low', group='1')
md1_lbl_color = input.color(color.red, '#1 label color', group='1')
md1_lbl_text = input.string('1', '#1 label text', group='1')
md1_lbl_text_color = input.color(color.white, '#1 label text color', group='1')
md1_lbl_size = input.string(size.tiny, title='1# label size', options=[size.tiny, size.small, size.normal, size.large, size.huge], group='1')

md1_enabled_ofset = input.bool(false, '#1 Offset channel', group='1')
md1_offset_source = input.source(low, '#1 Offset source', group='1')
md1_offset_value_high = input.float(0, '#1 Offset high', step=0.0001, group='1')
md1_offset_value_low = input.float(0, '#1 Offset low', step=0.0001, group='1')

//----

md2_enabled = input.bool(false, '#2 Enable', group='2')
md2_date = input.time(timestamp('01 Jun 2025 01:00 +0000'), '#2 Start Time', group='2')
md2_src_high = input.source(high, '#2 high', group='2')
md2_src_mid = input.source(hl2, '#2 mid', group='2')
md2_src_low = input.source(low, '#2 low', group='2')
md2_lbl_color = input.color(color.blue, '#2 label color', group='2')
md2_lbl_text = input.string('2', '#2 label text', group='2')
md2_lbl_text_color = input.color(color.white, '#2 label text color', group='2')
md2_lbl_size = input.string(size.tiny, title='2# label size', options=[size.tiny, size.small, size.normal, size.large, size.huge], group='2')

md2_enabled_ofset = input.bool(false, '#2 Offset channel', group='2')
md2_offset_source = input.source(low, '#2 Offset source', group='2')
md2_offset_value_high = input.float(0, '#2 Offset high', step=0.0001, group='2')
md2_offset_value_low = input.float(0, '#2 Offset low', step=0.0001, group='2')

//----

md3_enabled = input.bool(false, '#3 Enable', group='3')
md3_date = input.time(timestamp('01 Jun 2025 01:00 +0000'), '#3 Start Time', group='3')
md3_src_high = input.source(high, '#3 high', group='3')
md3_src_mid = input.source(hl2, '#3 mid', group='3')
md3_src_low = input.source(low, '#3 low', group='3')
md3_lbl_color = input.color(color.green, '#3 label color', group='3')
md3_lbl_text = input.string('3', '#3 label text', group='3')
md3_lbl_text_color = input.color(color.white, '#3 label text color', group='3')
md3_lbl_size = input.string(size.tiny, title='3# label size', options=[size.tiny, size.small, size.normal, size.large, size.huge], group='3')

md3_enabled_ofset = input.bool(false, '#3 Offset channel', group='3')
md3_offset_source = input.source(low, '#3 Offset source', group='3')
md3_offset_value_high = input.float(0, '#3 Offset high', step=0.0001, group='3')
md3_offset_value_low = input.float(0, '#3 Offset low', step=0.0001, group='3')

//----

md4_enabled = input.bool(false, '#4 Enable', group='4')
md4_date = input.time(timestamp('01 Jun 2025 01:00 +0000'), '#4 Start Time', group='4')
md4_src_high = input.source(high, '#4 high', group='4')
md4_src_mid = input.source(hl2, '#4 mid', group='4')
md4_src_low = input.source(low, '#4 low', group='4')
md4_lbl_color = input.color(color.purple, '#4 label color', group='4')
md4_lbl_text = input.string('4', '#4 label text', group='4')
md4_lbl_text_color = input.color(color.white, '#4 label text color', group='4')
md4_lbl_size = input.string(size.tiny, title='4# label size', options=[size.tiny, size.small, size.normal, size.large, size.huge], group='4')

md4_enabled_ofset = input.bool(false, '#4 Offset channel', group='4')
md4_offset_source = input.source(low, '#4 Offset source', group='4')
md4_offset_value_high = input.float(0, '#4 Offset high', step=0.0001, group='4')
md4_offset_value_low = input.float(0, '#4 Offset low', step=0.0001, group='4')

//----

md5_enabled = input.bool(false, '#5 Enable', group='5')
md5_date = input.time(timestamp('01 Jun 2025 01:00 +0000'), '#5 Start Time', group='5')
md5_src_high = input.source(high, '#5 high', group='5')
md5_src_mid = input.source(hl2, '#5 mid', group='5')
md5_src_low = input.source(low, '#5 low', group='5')
md5_lbl_color = input.color(color.orange, '#5 label color', group='5')
md5_lbl_text = input.string('5', '#5 label text', group='5')
md5_lbl_text_color = input.color(color.white, '#5 label text color', group='5')
md5_lbl_size = input.string(size.tiny, title='5# label size', options=[size.tiny, size.small, size.normal, size.large, size.huge], group='5')

md5_enabled_ofset = input.bool(false, '#5 Offset channel', group='5')
md5_offset_source = input.source(low, '#5 Offset source', group='5')
md5_offset_value_high = input.float(0, '#5 Offset high', step=0.0001, group='5')
md5_offset_value_low = input.float(0, '#5 Offset low', step=0.0001, group='5')

//----

// md6_enabled   = input(true, '#6 Enable', group = '6')
// md6_date      = input(timestamp('01 Jun 2025 01:00 +0000'), '#6 Start Time', type=input.time, group = '6')
// md6_src_high  = input(high, '#6 high', group = '6')
// md6_src_mid   = input(hl2, '#6 mid', group = '6')
// md6_src_low   = input(low, '#6 low', group = '6')
// md6_lbl_color   = input(color.black, '#6 label color', group = '6')
// md6_lbl_text   = input("6", '#6 label text', group = '6')
// md6_lbl_text_color   = input(color.white, '#6 label text color', group = '6')
// md6_lbl_size = input(size.tiny, title = '6# label size', options=[size.tiny, size.small, size.normal,size.large, size.huge], group = '6')

// md7_enabled   = input(true, '#7 Enable', group = '7')
// md7_date      = input(timestamp('01 Jun 2025 01:00 +0000'), '#7 Start Time', type=input.time, group = '7')
// md7_src_high  = input(high, '#7 high', group = '7')
// md7_src_mid   = input(hl2, '#7 mid', group = '7')
// md7_src_low   = input(low, '#7 low', group = '7')
// md7_lbl_color   = input(color.black, '#7 label color', group = '7')
// md7_lbl_text   = input("7", '#7 label text', group = '7')
// md7_lbl_text_color   = input(color.white, '#7 label text color', group = '7')
// md7_lbl_size = input(size.tiny, title = '7# label size', options=[size.tiny, size.small, size.normal,size.large, size.huge], group = '7')

// md8_enabled   = input(true, '#8 Enable', group = '8')
// md8_date      = input(timestamp('01 Jun 2025 01:00 +0000'), '#8 Start Time', type=input.time, group = '8')
// md8_src_high  = input(high, '#8 high', group = '8')
// md8_src_mid   = input(hl2, '#8 mid', group = '8')
// md8_src_low   = input(low, '#8 low', group = '8')
// md8_lbl_color   = input(color.black, '#8 label color', group = '8')
// md8_lbl_text   = input("8", '#8 label text', group = '8')
// md8_lbl_text_color   = input(color.white, '#8 label text color', group = '8')
// md8_lbl_size = input(size.tiny, title = '8# label size', options=[size.tiny, size.small, size.normal,size.large, size.huge], group = '8')


// tbf_D_input        = input(10, title="TBF Curve D parameter")
// tbf_D = tbf_D_input * 10000000
//------------------------------------------------------------------------------
// Helper label function
plabel(ptext, pcolor, ptextcolor, psize) =>
    label.new(bar_index, na, text=str.tostring(ptext), color=pcolor, textcolor=ptextcolor, size=psize, style=label.style_label_down, yloc=yloc.abovebar)

//------------------------------------------------------------------------------
// MIDAS Curve Calculation ORIGINAL
// midasCurve(src, anchor_time) =>
//     var float startVol = na
//     var float startVolPrice = na
//     var float cumVol = 0.0
//     var float cumVolPrice = 0.0
//     float result = na

//     in_range = time >= anchor_time
//     if in_range
//         cumVol += volume
//         cumVolPrice += volume * src
//         if na(startVol)
//             startVol := cumVol
//             startVolPrice := cumVolPrice
//         result := (cumVolPrice - startVolPrice) / (cumVol - startVol)

//     result

//------------------------------------------------------------------------------
// MIDAS Curve Calculation 
midasCurve(src, anchor_time) =>
    var float startVol = na
    var float startVolPrice = na
    var float cumVol = 0.0
    var float cumVolPrice = 0.0
    float result = na

    in_range = time >= anchor_time
    if in_range
        cumVol += volume
        cumVolPrice += volume * src
        if na(startVol)
            startVol := volume
            startVolPrice := volume * src
            result := src  // set the first value directly to the price at anchor
            result
        else
            cumVol += volume
            cumVolPrice += volume * src
            result := (cumVolPrice - startVolPrice) / (cumVol - startVol)
            result
    result

//------------------------------------------------------------------------------

// TBF Curve Calculation (based on your formula)
// tbfCurve(src, anchor_time, D) =>
//     var float vol_at_anchor = na
//     var float priceVol_at_anchor = na
//     float result = na
//     float xi = 0.0
//     float yi = 0.0

//     in_range = time >= anchor_time
//     if in_range
//         xi := nz(xi[1]) + volume
//         yi := nz(yi[1]) + src * volume
//         if na(vol_at_anchor)
//             vol_at_anchor := xi
//             priceVol_at_anchor := yi
//         dij = xi - vol_at_anchor
//         e = dij * (1 - dij / D)
//         result := e != 0 ? (yi - priceVol_at_anchor) / e : na

//     result

//------------------------------------------------------------------------------
// MIDAS #1

md1_active = md1_enabled and time >= md1_date
midas1_high = midasCurve(md1_src_high, md1_date)
midas1_mid = midasCurve(md1_src_mid, md1_date)
midas1_low = midasCurve(md1_src_low, md1_date)

midas1_offset_high = midasCurve(md1_offset_source, md1_date)
midas1_offset_low = midasCurve(md1_offset_source, md1_date)

// tbf1_high = tbfCurve(md1_src_high, md1_date, tbf_D)
// tbf1_mid  = tbfCurve(md1_src_mid, md1_date, tbf_D)
// tbf1_low  = tbfCurve(md1_src_low, md1_date, tbf_D)

if md1_active and time[0] <= md1_date
    plabel(md1_lbl_text, md1_lbl_color, md1_lbl_text_color, md1_lbl_size)

plot1_high = plot(md1_enabled ? midas1_high : na, color=color.new(color.red, 0), title='1 MIDAS High', linewidth=1)
plot1_mid = plot(md1_enabled ? midas1_mid : na, color=color.new(color.red, 0), title='1 MIDAS Mid', linewidth=1)
plot1_low = plot(md1_enabled ? midas1_low : na, color=color.new(color.red, 0), title='1 MIDAS Low', linewidth=1)
fill(plot1_high, plot1_low, color=color.new(color.red, 50), title='1 MIDAS Fill')

plot1_high_offset = plot(md1_enabled_ofset ? midas1_offset_high + md1_offset_value_high : na, color=color.new(color.red, 0), title='1 Offset high', linewidth=1)
plot1_low_offset = plot(md1_enabled_ofset ? midas1_offset_low - md1_offset_value_low : na, color=color.new(color.red, 0), title='1 Offset low', linewidth=1)


//------------------------------------------------------------------------------
// MIDAS #2

md2_active = md2_enabled and time >= md2_date
midas2_high = midasCurve(md2_src_high, md2_date)
midas2_mid = midasCurve(md2_src_mid, md2_date)
midas2_low = midasCurve(md2_src_low, md2_date)

midas2_offset_high = midasCurve(md2_offset_source, md2_date)
midas2_offset_low = midasCurve(md2_offset_source, md2_date)

if md2_active and time[1] < md2_date
    plabel(md2_lbl_text, md2_lbl_color, md2_lbl_text_color, md2_lbl_size)

plot2_high = plot(md2_enabled ? midas2_high : na, color=color.new(color.blue, 0), title='2 MIDAS High', linewidth=1)
plot2_mid = plot(md2_enabled ? midas2_mid : na, color=color.new(color.blue, 0), title='2 MIDAS Mid', linewidth=1)
plot2_low = plot(md2_enabled ? midas2_low : na, color=color.new(color.blue, 0), title='2 MIDAS Low', linewidth=1)
fill(plot2_high, plot2_low, color=color.new(color.blue, 50), title='2 MIDAS Fill')

plot2_high_offset = plot(md2_enabled_ofset ? midas2_offset_high + md2_offset_value_high : na, color=color.new(color.blue, 0), title='2 Offset high', linewidth=1)
plot2_low_offset = plot(md2_enabled_ofset ? midas2_offset_low - md2_offset_value_low : na, color=color.new(color.blue, 0), title='2 Offset low', linewidth=1)

//------------------------------------------------------------------------------
// MIDAS #3

md3_active = md3_enabled and time >= md3_date
midas3_high = midasCurve(md3_src_high, md3_date)
midas3_mid = midasCurve(md3_src_mid, md3_date)
midas3_low = midasCurve(md3_src_low, md3_date)

midas3_offset_high = midasCurve(md3_offset_source, md3_date)
midas3_offset_low = midasCurve(md3_offset_source, md3_date)

if md3_active and time[1] < md3_date
    plabel(md3_lbl_text, md3_lbl_color, md3_lbl_text_color, md3_lbl_size)

plot3_high = plot(md3_enabled ? midas3_high : na, color=color.new(color.green, 0), title='3 MIDAS High', linewidth=1)
plot3_mid = plot(md3_enabled ? midas3_mid : na, color=color.new(color.green, 0), title='3 MIDAS Mid', linewidth=1)
plot3_low = plot(md3_enabled ? midas3_low : na, color=color.new(color.green, 0), title='3 MIDAS Low', linewidth=1)
fill(plot3_high, plot3_low, color=color.new(color.green, 50), title='3 MIDAS Fill')

plot3_high_offset = plot(md3_enabled_ofset ? midas3_offset_high + md3_offset_value_high : na, color=color.new(color.green, 0), title='3 Offset high', linewidth=1)
plot3_low_offset = plot(md3_enabled_ofset ? midas3_offset_low - md3_offset_value_low : na, color=color.new(color.green, 0), title='3 Offset low', linewidth=1)

//------------------------------------------------------------------------------
// MIDAS #4

md4_active = md4_enabled and time >= md4_date
midas4_high = midasCurve(md4_src_high, md4_date)
midas4_mid = midasCurve(md4_src_mid, md4_date)
midas4_low = midasCurve(md4_src_low, md4_date)

midas4_offset_high = midasCurve(md4_offset_source, md4_date)
midas4_offset_low = midasCurve(md4_offset_source, md4_date)

if md4_active and time[1] < md4_date
    plabel(md4_lbl_text, md4_lbl_color, md4_lbl_text_color, md4_lbl_size)

plot4_high = plot(md4_enabled ? midas4_high : na, color=color.new(color.purple, 0), title='4 MIDAS High', linewidth=1)
plot4_mid = plot(md4_enabled ? midas4_mid : na, color=color.new(color.purple, 0), title='4 MIDAS Mid', linewidth=1)
plot4_low = plot(md4_enabled ? midas4_low : na, color=color.new(color.purple, 0), title='4 MIDAS Low', linewidth=1)
fill(plot4_high, plot4_low, color=color.new(color.purple, 50), title='4 MIDAS Fill')

plot4_high_offset = plot(md4_enabled_ofset ? midas4_offset_high + md4_offset_value_high : na, color=color.new(color.purple, 0), title='4 Offset high', linewidth=1)
plot4_low_offset = plot(md4_enabled_ofset ? midas4_offset_low - md4_offset_value_low : na, color=color.new(color.purple, 0), title='4 Offset low', linewidth=1)

//------------------------------------------------------------------------------
// MIDAS #5

md5_active = md5_enabled and time >= md5_date
midas5_high = midasCurve(md5_src_high, md5_date)
midas5_mid = midasCurve(md5_src_mid, md5_date)
midas5_low = midasCurve(md5_src_low, md5_date)

midas5_offset_high = midasCurve(md5_offset_source, md5_date)
midas5_offset_low = midasCurve(md5_offset_source, md5_date)

if md5_active and time[1] < md5_date
    plabel(md5_lbl_text, md5_lbl_color, md5_lbl_text_color, md5_lbl_size)

plot5_high = plot(md5_enabled ? midas5_high : na, color=color.new(color.orange, 0), title='5 MIDAS High', linewidth=1)
plot5_mid = plot(md5_enabled ? midas5_mid : na, color=color.new(color.orange, 0), title='5 MIDAS Mid', linewidth=1)
plot5_low = plot(md5_enabled ? midas5_low : na, color=color.new(color.orange, 0), title='5 MIDAS Low', linewidth=1)
fill(plot5_high, plot5_low, color=color.new(color.orange, 50), title='5 MIDAS Fill')

plot5_high_offset = plot(md5_enabled_ofset ? midas5_offset_high + md5_offset_value_high : na, color=color.new(color.orange, 0), title='5 Offset high', linewidth=1)
plot5_low_offset = plot(md5_enabled_ofset ? midas5_offset_low - md5_offset_value_low : na, color=color.new(color.orange, 0), title='5 Offset low', linewidth=1)

//------------------------------------------------------------------------------
// MIDAS #6

// md6_active = md6_enabled and time >= md6_date
// midas6_high = midasCurve(md6_src_high, md6_date)
// midas6_mid  = midasCurve(md6_src_mid, md6_date)
// midas6_low  = midasCurve(md6_src_low, md6_date)

// if md6_active and time[1] < md6_date
//     plabel(md6_lbl_text, md6_lbl_color, md6_lbl_text_color,md6_lbl_size)

// plot6_high = plot(md6_enabled ? midas6_high : na, color=color.black, title="6 MIDAS High", linewidth=1)
// plot6_mid  = plot(md6_enabled ? midas6_mid  : na, color=color.black, title="6 MIDAS Mid", linewidth=1)
// plot6_low  = plot(md6_enabled ? midas6_low  : na, color=color.black, title="6 MIDAS Low", linewidth=1)
// fill(plot6_high, plot6_low, color=color.new(color.blue, 50), title="6 MIDAS Fill")

//------------------------------------------------------------------------------
// MIDAS #7

// md7_active = md7_enabled and time >= md7_date
// midas7_high = midasCurve(md7_src_high, md7_date)
// midas7_mid  = midasCurve(md7_src_mid, md7_date)
// midas7_low  = midasCurve(md7_src_low, md7_date)

// if md7_active and time[1] < md7_date
//     plabel(md7_lbl_text, md7_lbl_color, md7_lbl_text_color,md7_lbl_size)

// plot7_high = plot(md7_enabled ? midas7_high : na, color=color.black, title="7 MIDAS High", linewidth=1)
// plot7_mid  = plot(md7_enabled ? midas7_mid  : na, color=color.black, title="7 MIDAS Mid", linewidth=1)
// plot7_low  = plot(md7_enabled ? midas7_low  : na, color=color.black, title="7 MIDAS Low", linewidth=1)
// fill(plot7_high, plot7_low, color=color.new(color.blue, 50), title="7 MIDAS Fill")

//------------------------------------------------------------------------------
// MIDAS #8

// md8_active = md8_enabled and time >= md8_date
// midas8_high = midasCurve(md8_src_high, md8_date)
// midas8_mid  = midasCurve(md8_src_mid, md8_date)
// midas8_low  = midasCurve(md8_src_low, md8_date)

// if md8_active and time[1] < md8_date
//     plabel(md8_lbl_text, md8_lbl_color, md8_lbl_text_color,md8_lbl_size)

// plot8_high = plot(md8_enabled ? midas8_high : na, color=color.black, title="8 MIDAS High", linewidth=1)
// plot8_mid  = plot(md8_enabled ? midas8_mid  : na, color=color.black, title="8 MIDAS Mid", linewidth=1)
// plot8_low  = plot(md8_enabled ? midas8_low  : na, color=color.black, title="8 MIDAS Low", linewidth=1)
// fill(plot8_high, plot8_low, color=color.new(color.blue, 50), title="8 MIDAS Fill")
