//@version=6
indicator("Smooth Trader Concepts - Supporting Indicator", overlay = true, format = format.volume, max_lines_count = 500, max_labels_count = 500, max_boxes_count = 500)
import PineCoders/lower_tf/5 as PCltf

//#region  ———————————————————— Declarations
const int MIN_IN_SECONDS = 3600
const string ATR_GROUP =  "ATR Configurations"
const string VWAP_GROUP = "VWAP Time Divided"
const string PSVAR_GROUP = "High Volume Candles"
const string VIDYA_GROUP = "Trend"

const array<string> VIDYA_1MIN_PRESET = array.from("1", "30S", "15S", "10S", "5S")
const array<string> VIDYA_5MIN_PRESET = array.from("5", "3", "2", "1", "30S", "15S")
const array<string> VIDYA_15MIN_PRESET = array.from("15", "8", "5", "3", "2", "1")
const array<string> VIDYA_30MIN_PRESET = array.from("30", "15", "8", "5", "3", "1")
const array<string> VIDYA_1HR_PRESET = array.from("60", "30", "15", "8", "5", "3")
const array<string> VIDYA_4HR_PRESET = array.from("240", "120", "60", "30", "15")
const array<string> VIDYA_DAY_PRESET = array.from("720", "360", "180", "60", "30")
const array<string> VIDYA_WEEK_PRESET = array.from("3D", "1D", "720", "360", "240")
const array<string> VIDYA_MONTH_PRESET = array.from("2W", "1W", "3D", "1D", "720")

const string MV_CLOUD_GROUP = "MV CLOUD"
const string SIGNALS_GROUP = "Signals"
const string KEY_LEVELS_GROUP = "Key Levels"
const string OBR_GROUP = "OBR"
//#endregion

//#region ATR
inputAtrEnabled = input.bool(true, "Enable", group=ATR_GROUP)
inputAtrLength = input.int(14, "Length", group=ATR_GROUP)
inputAtrFrameWidth = input.int(1, "Frame Width", group=ATR_GROUP)
inputAtrFrameColor = input.color(color.white, "Frame Color", group=ATR_GROUP)
inputAtrUseBgColor = input.bool(false, "Use Custom Background Color", group=ATR_GROUP)
inputAtrBgColor = inputAtrUseBgColor ? input.color(color.rgb(0, 0, 0), "Custom Background Color", group=ATR_GROUP) : chart.bg_color
//#endregion

//#region VWAP
inputVwapSession   = input.string("1D", "VWAP Reset Anchor", options = ["1D", "2D", "3D", "W", "14D", "M", "12M"], group = VWAP_GROUP)
inputVwapBand1Mult = input.int(1, "Band 1 & 2 Multiplier         ", inline = "12", group = VWAP_GROUP)
inputVwapBand2Mult = input.int(2, "",                      inline = "12", group = VWAP_GROUP)
inputVwapBand3Mult = input.int(3, "Band 3 & 4 Multiplier         ", inline = "13", group = VWAP_GROUP)
inputVwapBand4Mult = input.int(4, "",                      inline = "13", group = VWAP_GROUP)
bool inputVwapDisplayCurrent = input.string('Show Current', title='Time Divided VWAP             ', options = ['Show Current', "Hide Current"], group = VWAP_GROUP, inline="00") == 'Show Current'
bool inputVwapDisplayPrevious = input.string("Hide Previous", title='', options = ['Show Previous', "Hide Previous"], group = VWAP_GROUP, inline="00") == 'Show Previous'
inputVwap1BandEnabled = input.bool(true, title='Current Band 1                   ', group = VWAP_GROUP, inline="01")
inputVwap2BandEnabled = input.bool(true, title='Current Band 2                   ', group = VWAP_GROUP, inline="02")
inputVwap3BandEnabled = input.bool(true, title='Current Band 3                   ', group = VWAP_GROUP, inline="03")
inputVwap4BandEnabled = input.bool(true, title='Current Band 4                   ', group = VWAP_GROUP, inline="04")
inputVwapBandColor  = input.color(#9c28b1, title='Current Color', group = VWAP_GROUP, inline="05")
inputVwapPrevBandColor = color.maroon
inputVwapPrev1BandEnabled = input(false, title='Previous Band 1', group = VWAP_GROUP, inline="01")
inputVwapPrev2BandEnabled = input(false, title='Previous Band 2', group = VWAP_GROUP, inline="02")
inputVwapPrev3BandEnabled = input(false, title='Previous Band 3', group = VWAP_GROUP, inline="03")
inputVwapPrev4BandEnabled = input(false, title='Previous Band 4', group = VWAP_GROUP, inline="04")
//#endregion

//#region OBR 
inputOrbEnable = input.bool(false, "Enable", group = OBR_GROUP)
inputObrTf1 = input.timeframe("15", "Timeframe 1", inline = "00", group = OBR_GROUP)
inputObrTf1Enabled = input.bool(true, "", inline = "00", group = OBR_GROUP) 
  and timeframe.in_seconds(inputObrTf1) >= 60
  and timeframe.in_seconds(inputObrTf1) <= timeframe.in_seconds("D") 
inputObrTf2 = input.timeframe("60", "Timeframe 2", inline = "01", group = OBR_GROUP)
inputObrTf2Enabled = input.bool(false, "", inline = "01", group = OBR_GROUP) 
  and timeframe.in_seconds(inputObrTf2) >= 60
  and timeframe.in_seconds(inputObrTf2) <= timeframe.in_seconds("D") 
use_custom_session = input.bool(false, "Use Custom Session", group = OBR_GROUP)
custom_session = input.session("1300-1400", "Custom Session", group = OBR_GROUP)
custom_sesseion_timezone = input.string("America/New_York", "Custom Session Timezone", group = OBR_GROUP, tooltip="Timezone for the custom session", 
  options=["America/New_York", "Australia/Sydney", "Asia/Tokyo", "Europe/London", "Europe/Luxembourg", "Singapore", "UTC"])
inputObrShowHistorical = input.bool(true, "Historical OBR", group = OBR_GROUP)
inputObrShowHistoricalLabel = input.bool(false, "Show Historical OBR Label", group = OBR_GROUP)
inputObrHighColor = input.color(color.green, "High Color", inline = "02", group = OBR_GROUP)
inputObrLowColor = input.color(color.red, "Low Color", inline = "02", group = OBR_GROUP)

inputOBRLabelBarsOffset  = input.int(15, "Visual: Label Offset Bars", group = OBR_GROUP)
inputOBRLineBarsOffset   = input.int(10, "Visual: Line Offset Bars", group = OBR_GROUP)
//#endregion

//#region Key Levels 
inputKeyLevelsEnabled = input.bool(false, "Enable Key Levels", group = KEY_LEVELS_GROUP)

inputDayHighLowEnabled = input.bool(true, "Daily High/Low            ", group = KEY_LEVELS_GROUP, inline="inputDayHighLow")
inputPrevDayHighLowEnabled = input.bool(true, "Previous Day High/Low   ", group = KEY_LEVELS_GROUP, inline="inputPrevDayHighLow")
inputDayOpenEnabled = input.bool(true, "Daily Open               ", group = KEY_LEVELS_GROUP, inline="inputDayOpen")
inputPrevWeekHighLowEnabled = input.bool(true, "Previous Week High/Low  ", group = KEY_LEVELS_GROUP, inline="inputPrevWeekHighLow")
inputPrevMonthHighLowEnabled = input.bool(true, "Previous Month High/Low ", group = KEY_LEVELS_GROUP, inline="inputPrevMonthHighLow")
inputDayHighColor = input.color(color.green, "", group = KEY_LEVELS_GROUP, inline="inputDayHighLow")
inputDayLowColor = input.color(color.red, "", group = KEY_LEVELS_GROUP, inline="inputDayHighLow")
inputPrevDayHighColor = input.color(color.green, "", group = KEY_LEVELS_GROUP, inline="inputPrevDayHighLow")
inputPrevDayLowColor = input.color(color.red, "", group = KEY_LEVELS_GROUP, inline="inputPrevDayHighLow")
inputDayOpenColor = input.color(color.blue, "", group = KEY_LEVELS_GROUP, inline="inputDayOpen")
inputPrevWeekHighColor = input.color(color.green, "", group = KEY_LEVELS_GROUP, inline="inputPrevWeekHighLow")
inputPrevWeekLowColor = input.color(color.red, "", group = KEY_LEVELS_GROUP, inline="inputPrevWeekHighLow")
inputPrevMonthHighColor = input.color(color.green, "", group = KEY_LEVELS_GROUP, inline="inputPrevMonthHighLow")
inputPrevMonthLowColor = input.color(color.red, "", group = KEY_LEVELS_GROUP, inline="inputPrevMonthHighLow")

inputOvernightSess = input.session("1800-0930", "Overnight Session", group = KEY_LEVELS_GROUP)
inputOvernightTz   = input.string("America/New_York", "Overnight Session Tz", group = KEY_LEVELS_GROUP, tooltip="Timezone for the key levels",
  options=["America/New_York", "Australia/Sydney", "Asia/Tokyo", "Europe/London", "Europe/Luxembourg", "Singapore", "UTC"])
inputOvernightHighLowEnabled = input.bool(true, "Overnight High/Low        ", group = KEY_LEVELS_GROUP, inline="inputOvernightHighLow")
inputOvernightHighColor = input.color(color.orange, "", group = KEY_LEVELS_GROUP, inline="inputOvernightHighLow")
inputOvernightLowColor = input.color(color.orange, "", group = KEY_LEVELS_GROUP, inline="inputOvernightHighLow")

inputKeyCusTz = input.string("America/New_York", "Custom Timezone", group = KEY_LEVELS_GROUP, tooltip="Timezone for the key levels",
  options=["America/New_York", "Australia/Sydney", "Asia/Tokyo", "Europe/London", "Europe/Luxembourg", "Singapore", "UTC"])
inputDayCusTzHighLowEnabled     = input.bool(false, "Custom Timezone Daily High/Low        ", group = KEY_LEVELS_GROUP, inline="inputDayCusTzHighLow")
inputPrevDayCusTzHighLowEnabled = input.bool(false, "Custom Timezone Previous Day High/Low", group = KEY_LEVELS_GROUP, inline="inputPrevDayCusTzHighLow")
inputDayCusTzOpenEnabled        = input.bool(false, "Custom Timezone Day Open           ", group = KEY_LEVELS_GROUP, inline="inputDayCusTzOpen")
inputDayCusTzHighColor          = input.color(color.green, "", group = KEY_LEVELS_GROUP, inline="inputDayCusTzHighLow")
inputDayCusTzLowColor           = input.color(color.red, "", group = KEY_LEVELS_GROUP, inline="inputDayCusTzHighLow")
inputPrevDayCusTzHighColor      = input.color(color.green, "", group = KEY_LEVELS_GROUP, inline="inputPrevDayCusTzHighLow")
inputPrevDayCusTzLowColor       = input.color(color.red, "", group = KEY_LEVELS_GROUP, inline="inputPrevDayCusTzHighLow")
inputDayCusTzOpenColor          = input.color(color.blue, "", group = KEY_LEVELS_GROUP, inline="inputDayCusTzOpen")

inputKeyLevelsLabelBarsOffset  = input.int(15, "Visual: Label Offset Bars", group = KEY_LEVELS_GROUP)
inputKeyLevelsLineBarsOffset   = input.int(10, "Visual: Line Offset Bars", group = KEY_LEVELS_GROUP)

var timePerBar = time_close - time
timeinrange(res, sess, tz) => not na(time(res, sess, tz))

var overnightHi = high
var overnightLo = low
var overnightTm = int(na)
var overnightHiTm = int(na)
var overnightLoTm = int(na)

isOvernightSession = timeinrange("", inputOvernightSess, inputOvernightTz)
if isOvernightSession
    if not isOvernightSession[1]
        overnightHi := high
        overnightLo := low
        overnightTm := time
    else
        if high >= overnightHi
            overnightHi := high
            overnightHiTm := time
        if low <= overnightLo
            overnightLo := low
            overnightLoTm := time

var dailyHi = float(na) 
var dailyLo = float(na)
var dailyHiTm = int(na) 
var dailyLoTm = int(na)
var prevDayHi = float(na) 
var prevDayLo = float(na)
var prevDayHiTm = int(na) 
var prevDayLoTm = int(na)
var prevDayTimeClose = int(na)
var dailyOpen = float(na)
if dayofmonth != dayofmonth[1]
    prevDayHi := dailyHi
    prevDayLo := dailyLo
    prevDayHiTm := dailyHiTm
    prevDayLoTm := dailyLoTm
    dailyHi := high
    dailyHiTm := time
    dailyLo := low
    dailyLoTm := time
    prevDayTimeClose := time
    dailyOpen := open
else 
    if high > dailyHi or na(dailyHi)
        dailyHi := high
        dailyHiTm := time
    if low < dailyLo or na(dailyLo)
        dailyLo := low
        dailyLoTm := time

var dailyCusTzHi = float(na) 
var dailyCusTzLo = float(na)
var dailyCusTzHiTm = int(na) 
var dailyCusTzLoTm = int(na)
var prevDayCusTzHi = float(na) 
var prevDayCusTzLo = float(na)
var prevDayCusTzHiTm = int(na) 
var prevDayCusTzLoTm = int(na)
var prevDayCusTzTimeClose = int(na)
var dailyCusTzOpen = float(na)
if dayofmonth(time, inputKeyCusTz) != dayofmonth(time, inputKeyCusTz)[1]
    prevDayCusTzHi := dailyCusTzHi
    prevDayCusTzLo := dailyCusTzLo
    prevDayCusTzHiTm := dailyCusTzHiTm
    prevDayCusTzLoTm := dailyCusTzLoTm
    dailyCusTzHi := high
    dailyCusTzHiTm := time
    dailyCusTzLo := low
    dailyCusTzLoTm := time
    prevDayCusTzTimeClose := time
    dailyCusTzOpen := open
else 
    if high > dailyCusTzHi or na(dailyCusTzHi)
        dailyCusTzHi := high
        dailyCusTzHiTm := time
    if low < dailyCusTzLo or na(dailyCusTzLo)
        dailyCusTzLo := low
        dailyCusTzLoTm := time

[prevWeekHi , prevWeekLo , prevWeekTimeClose ] = request.security(syminfo.tickerid, "W", [high[1], low[1], time[1]], barmerge.gaps_off, barmerge.lookahead_on)
[prevMonthHi, prevMonthLo, prevMonthTimeClose] = request.security(syminfo.tickerid, "M", [high[1], low[1], time[1]], barmerge.gaps_off, barmerge.lookahead_on)
[overnightHiTm5, overnightLoTm5, overnightHi5, overnightLo5, overnightTm5,
  prevDayHi5, prevDayLo5, prevDayHiTm5, prevDayLoTm5, 
  dailyHi5, dailyHiTm5, dailyLo5, dailyLoTm5, 
  prevDayTimeClose5, dailyOpen5,
  prevDayCusTzHi5, prevDayCusTzLo5, prevDayCusTzHiTm5, prevDayCusTzLoTm5, 
  dailyCusTzHi5, dailyCusTzHiTm5, dailyCusTzLo5, dailyCusTzLoTm5, 
  prevDayCusTzTimeClose5, dailyCusTzOpen5
  ] = request.security(syminfo.tickerid, "5", 
  [
      overnightHiTm, overnightLoTm, overnightHi, overnightLo, overnightTm,
      prevDayHi, prevDayLo, prevDayHiTm, prevDayLoTm, 
      dailyHi, dailyHiTm, dailyLo, dailyLoTm, 
      prevDayTimeClose, dailyOpen,
      prevDayCusTzHi, prevDayCusTzLo, prevDayCusTzHiTm, prevDayCusTzLoTm,
      dailyCusTzHi, dailyCusTzHiTm, dailyCusTzLo, dailyCusTzLoTm,
      prevDayCusTzTimeClose, dailyCusTzOpen
  ], barmerge.gaps_off, barmerge.lookahead_on)

if timeframe.in_seconds() < timeframe.in_seconds("5")
    prevDayHi             := prevDayHi5
    prevDayLo             := prevDayLo5
    prevDayHiTm           := prevDayHiTm5
    prevDayLoTm           := prevDayLoTm5
    dailyHi               := dailyHi5
    dailyHiTm             := dailyHiTm5
    dailyLo               := dailyLo5
    dailyLoTm             := dailyLoTm5
    prevDayTimeClose      := prevDayTimeClose5
    dailyOpen             := dailyOpen5
    prevDayCusTzHi        := prevDayCusTzHi5
    prevDayCusTzLo        := prevDayCusTzLo5
    prevDayCusTzHiTm      := prevDayCusTzHiTm5
    prevDayCusTzLoTm      := prevDayCusTzLoTm5
    dailyCusTzHi          := dailyCusTzHi5
    dailyCusTzHiTm        := dailyCusTzHiTm5
    dailyCusTzLo          := dailyCusTzLo5
    dailyCusTzLoTm        := dailyCusTzLoTm5
    prevDayCusTzTimeClose := prevDayCusTzTimeClose5
    dailyCusTzOpen        := dailyCusTzOpen5

[dailyHiSecurity, dailyLoSecurity, prevDayHiSecurity, prevDayLoSecurity, dailyOpenSecurity, dailyTimeSecurity, prevDailyTimeSecurity] =
  request.security(syminfo.tickerid, "D", [high, low, high[1], low[1], open, time, time[1]], barmerge.gaps_off, barmerge.lookahead_on)

useAltDailyCalc = true
if useAltDailyCalc
    dailyHi := dailyHiSecurity
    dailyLo := dailyLoSecurity
    prevDayHi := prevDayHiSecurity
    prevDayLo := prevDayLoSecurity
    dailyOpen := dailyOpenSecurity
    dailyHiTm := dailyTimeSecurity
    dailyLoTm := dailyTimeSecurity
    prevDayHiTm := prevDailyTimeSecurity
    prevDayLoTm := prevDailyTimeSecurity
    prevDayTimeClose := dailyTimeSecurity

var dailyHiLine          = line(na), var dailyHiLabel        = not inputDayHighLowEnabled          ? label(na) : label.new(time, close, text="Daily High",                        style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputDayHighColor,          size=size.small)
var dailyLoLine          = line(na), var dailyLoLabel        = not inputDayHighLowEnabled          ? label(na) : label.new(time, close, text="Daily Low",                         style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputDayLowColor,           size=size.small)
var prevDayHiLine        = line(na), var prevDayHiLabel      = not inputPrevDayHighLowEnabled      ? label(na) : label.new(time, close, text="Prev Day High",                     style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevDayHighColor,      size=size.small)
var prevDayLoLine        = line(na), var prevDayLoLabel      = not inputPrevDayHighLowEnabled      ? label(na) : label.new(time, close, text="Prev Day Low",                      style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevDayLowColor,       size=size.small)
var dailyOpenLine        = line(na), var dailyOpenLabel      = not inputDayOpenEnabled             ? label(na) : label.new(time, close, text="Daily Open",                        style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputDayOpenColor,          size=size.small)
var overnightLoLine      = line(na), var overnightLoLabel    = not inputOvernightHighLowEnabled    ? label(na) : label.new(time, close, text="Overnight Low",                     style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputOvernightLowColor,     size=size.small)
var overnightHiLine      = line(na), var overnightHiLabel    = not inputOvernightHighLowEnabled    ? label(na) : label.new(time, close, text="Overnight High",                    style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputOvernightHighColor,    size=size.small)
var prevWeekHiLine       = line(na), var prevWeekHiLabel     = not inputPrevWeekHighLowEnabled     ? label(na) : label.new(time, close, text="Prev Week High",                    style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevWeekHighColor,     size=size.small)
var prevWeekLoLine       = line(na), var prevWeekLoLabel     = not inputPrevWeekHighLowEnabled     ? label(na) : label.new(time, close, text="Prev Week Low",                     style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevWeekLowColor,      size=size.small)
var prevMonthHiLine      = line(na), var prevMonthHiLabel    = not inputPrevMonthHighLowEnabled    ? label(na) : label.new(time, close, text="Prev Month High",                   style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevMonthHighColor,    size=size.small)
var prevMonthLoLine      = line(na), var prevMonthLoLabel    = not inputPrevMonthHighLowEnabled    ? label(na) : label.new(time, close, text="Prev Month Low" ,                   style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevMonthLowColor,     size=size.small)
var dailyCusTzHiLine     = line(na), var dailyCusTzHiLabel   = not inputDayCusTzHighLowEnabled     ? label(na) : label.new(time, close, text="Custom Timezone Daily High",        style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputDayCusTzHighColor,     size=size.small)
var dailyCusTzLoLine     = line(na), var dailyCusTzLoLabel   = not inputDayCusTzHighLowEnabled     ? label(na) : label.new(time, close, text="Custom Timezone Daily Low",         style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputDayCusTzLowColor,      size=size.small)
var prevDayCusTzHiLine   = line(na), var prevDayCusTzHiLabel = not inputPrevDayCusTzHighLowEnabled ? label(na) : label.new(time, close, text="Custom Timezone Previous Day High", style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevDayCusTzHighColor, size=size.small)
var prevDayCusTzLoLine   = line(na), var prevDayCusTzLoLabel = not inputPrevDayCusTzHighLowEnabled ? label(na) : label.new(time, close, text="Custom Timezone Previous Day Low",  style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputPrevDayCusTzLowColor,  size=size.small)
var dailyCusTzOpenLine   = line(na), var dailyCusTzOpenLabel = not inputDayCusTzOpenEnabled        ? label(na) : label.new(time, close, text="Custom Timezone Daily Open",        style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputDayCusTzOpenColor,     size=size.small)

if inputKeyLevelsEnabled and barstate.islast
    if inputDayHighLowEnabled
        dailyHiLine.delete()
        dailyLoLine.delete()
        dailyHiLine := line.new(dailyHiTm, dailyHi, time + timePerBar * inputKeyLevelsLineBarsOffset, dailyHi, xloc.bar_time, extend.none, color=inputDayHighColor, width = 1)
        dailyLoLine := line.new(dailyLoTm, dailyLo, time + timePerBar * inputKeyLevelsLineBarsOffset, dailyLo, xloc.bar_time, extend.none, color=inputDayLowColor, width = 1)
        dailyHiLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, dailyHi)
        dailyLoLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, dailyLo)
    if inputPrevDayHighLowEnabled
        prevDayHiLine.delete()
        prevDayLoLine.delete()
        prevDayHiLine := line.new(prevDayHiTm, prevDayHi, time + timePerBar * inputKeyLevelsLineBarsOffset, prevDayHi, xloc.bar_time, extend.none, color=inputPrevDayHighColor, width = 1)
        prevDayLoLine := line.new(prevDayLoTm, prevDayLo, time + timePerBar * inputKeyLevelsLineBarsOffset, prevDayLo, xloc.bar_time, extend.none, color=inputPrevDayLowColor, width = 1)
        prevDayHiLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevDayHi)
        prevDayLoLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevDayLo)
    if inputDayOpenEnabled
        dailyOpenLine.delete()
        dailyOpenLine := line.new(prevDayTimeClose, dailyOpen , time + timePerBar * inputKeyLevelsLineBarsOffset , dailyOpen , xloc.bar_time, extend.none,color=inputDayOpenColor, width = 1)
        dailyOpenLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, dailyOpen)
    if inputOvernightHighLowEnabled and timeframe.isintraday
        overnightLoLine.delete()
        overnightHiLine.delete()
        overnightHiLine := line.new(overnightTm5, overnightHi5 , time + timePerBar * inputKeyLevelsLineBarsOffset, overnightHi5, xloc.bar_time, extend.none,color=inputOvernightHighColor, width = 1)
        overnightLoLine := line.new(overnightTm5, overnightLo5 , time + timePerBar * inputKeyLevelsLineBarsOffset, overnightLo5, xloc.bar_time, extend.none,color=inputOvernightLowColor, width = 1)
        overnightHiLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, overnightHi5)
        overnightLoLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, overnightLo5)
    if inputPrevWeekHighLowEnabled
        prevWeekHiLine.delete()
        prevWeekLoLine.delete() 
        prevWeekHiLine := line.new(prevWeekTimeClose, prevWeekHi, time + timePerBar * inputKeyLevelsLineBarsOffset, prevWeekHi , xloc.bar_time, extend.none, color=inputPrevWeekHighColor, width = 1)
        prevWeekLoLine := line.new(prevWeekTimeClose, prevWeekLo, time + timePerBar * inputKeyLevelsLineBarsOffset, prevWeekLo , xloc.bar_time, extend.none, color=inputPrevWeekLowColor, width = 1)
        prevWeekHiLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevWeekHi)
        prevWeekLoLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevWeekLo)
    if inputPrevMonthHighLowEnabled
        prevMonthHiLine.delete()
        prevMonthLoLine.delete()
        prevMonthHiLine := line.new(prevMonthTimeClose, prevMonthHi, time + timePerBar * inputKeyLevelsLineBarsOffset, prevMonthHi , xloc.bar_time, extend.none, color=inputPrevMonthHighColor, width = 1)
        prevMonthLoLine := line.new(prevMonthTimeClose, prevMonthLo, time + timePerBar * inputKeyLevelsLineBarsOffset, prevMonthLo , xloc.bar_time, extend.none, color=inputPrevMonthLowColor, width = 1)
        prevMonthHiLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevMonthHi)
        prevMonthLoLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevMonthLo)
    if inputDayCusTzHighLowEnabled
        dailyCusTzHiLine.delete()
        dailyCusTzLoLine.delete()
        dailyCusTzHiLine := line.new(dailyCusTzHiTm, dailyCusTzHi, time + timePerBar * inputKeyLevelsLineBarsOffset, dailyCusTzHi, xloc.bar_time, extend.none, color=inputDayCusTzHighColor, width = 1)
        dailyCusTzLoLine := line.new(dailyCusTzLoTm, dailyCusTzLo, time + timePerBar * inputKeyLevelsLineBarsOffset, dailyCusTzLo, xloc.bar_time, extend.none, color=inputDayCusTzLowColor, width = 1)
        dailyCusTzHiLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, dailyCusTzHi)
        dailyCusTzLoLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, dailyCusTzLo)
    if inputPrevDayCusTzHighLowEnabled
        prevDayCusTzHiLine.delete()
        prevDayCusTzLoLine.delete()
        prevDayCusTzHiLine := line.new(prevDayCusTzHiTm, prevDayCusTzHi, time + timePerBar * inputKeyLevelsLineBarsOffset, prevDayCusTzHi, xloc.bar_time, extend.none, color=inputPrevDayCusTzHighColor, width = 1)
        prevDayCusTzLoLine := line.new(prevDayCusTzLoTm, prevDayCusTzLo, time + timePerBar * inputKeyLevelsLineBarsOffset, prevDayCusTzLo, xloc.bar_time, extend.none, color=inputPrevDayCusTzLowColor, width = 1)
        prevDayCusTzHiLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevDayCusTzHi)
        prevDayCusTzLoLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, prevDayCusTzLo)
    if inputDayCusTzOpenEnabled
        dailyCusTzOpenLine.delete()
        dailyCusTzOpenLine := line.new(prevDayCusTzTimeClose, dailyCusTzOpen , time + timePerBar * inputKeyLevelsLineBarsOffset, dailyCusTzOpen , xloc.bar_time, extend.none,color=inputDayCusTzOpenColor, width = 1)
        dailyCusTzOpenLabel.set_xy(time + timePerBar * inputKeyLevelsLabelBarsOffset, dailyCusTzOpen)
//#endregion

//#region PVSRA
bool inputPVSRAHighVolDisplay    = input.bool(true, "Enable", group = PSVAR_GROUP)
bool inputPVSRAMedVolDisplay     = input.bool(true, "Show Medium Volume Candle", group = PSVAR_GROUP)
color inputPVSRAHighVolBullColor = input.color(#1ef00c, "High Volume Candle    ▲", inline="00", group = PSVAR_GROUP)
color inputPVSRAHighVolBearColor = input.color(#e91aac, "▼", inline="00", group = PSVAR_GROUP)
color inputPVSRAMedVolBullColor  = input.color(#0cf0e0, "Medium Volume Candle  ▲", inline="01", group = PSVAR_GROUP)
color inputPVSRAMedVolBearColor  = input.color(color.purple, "▼", inline="01", group = PSVAR_GROUP)
string inputPVSRADisplayOption   = input.string("Candle Coloring", "Display", ["Candle Coloring", "Diamond"], group = PSVAR_GROUP)
string inputPVSRABullDiamondPos  = input.string("Below", "Bullish Diamond", ["Above", "Below"], group = PSVAR_GROUP)
string inputPVSRABearDiamondPos  = input.string("Above", "Bearish Diamond", ["Above", "Below"], group = PSVAR_GROUP)
bool  inputPVSRADisplayColoring  = inputPVSRAHighVolDisplay and inputPVSRADisplayOption == "Candle Coloring"
bool  inputPVSRASDisplayDiamond  = inputPVSRAHighVolDisplay and inputPVSRADisplayOption == "Diamond"
//#endregion

//#region MV Cloud
inputMVCloudEnabled        = input.bool(true, "Enable", group = MV_CLOUD_GROUP)
inputMVCloudEMAColor       = input.color(#0cf0e0, "MV Cloud Color            ▲", inline = "00", group = MV_CLOUD_GROUP)
inputMVCloudVWAPColor      = input.color(#e93cb6, "▼", inline = "00", group = MV_CLOUD_GROUP)
inputMVCloudPreset     = input.string("Agressive", "Preset", ["Agressive", "Moderate", "Conservative"], group = MV_CLOUD_GROUP)
//#endregion

//#region VWAP
f_timeframeAnchoredVwap(string tf = "1D", int stdevMult = 0) =>
    var float prevVwap = na
    var float prevUpper = na 
    var float prevLower = na
    sessionChange = bool(ta.change(time(tf)))
    [currVwap, currUpper, currLower] = ta.vwap(hlc3, sessionChange, stdevMult)
    if sessionChange 
        prevVwap := currVwap[1]
        prevUpper := currUpper[1] 
        prevLower := currLower[1]

    [currVwap, currUpper, currLower, prevVwap, prevUpper, prevLower]
//#endregion

//#region PVSRA
f_PVSRA() =>
    float averageVolume    = ta.sma(volume[1], 10)
    float currentCandleMag = volume * (high - low)
    float largestMagCandle = ta.highest(currentCandleMag[1], 10)
    if volume >= 2*averageVolume or currentCandleMag >= largestMagCandle
        close > open ? 2 : -2 
    else if volume >= 1.5 * averageVolume
        close > open ? 1 : -1     
//#endregion 

//#region VIDYA
method vidya(series float src, int p) =>
    cmo = ta.cmo(src, 10)
    smoothedCmo = ta.sma(cmo, 14)
    absCmo = math.abs(smoothedCmo)
    alpha = 2.0 / (p + 1)
    adaptiveAlpha = alpha * absCmo / 100.0
    float vidya = na
    vidya := adaptiveAlpha * src + (1 - adaptiveAlpha) * nz(vidya[1], src)
    vidya

method zScore(series float sample, float mu, int p) =>
    (sample - mu) / ta.stdev(sample - mu, p)

method getMTF(series float src, array<string> tfs) =>
    allSrc = array.new<float>()
    for tf in tfs
        float vidyaTF = request.security(syminfo.tickerid, tf, src[1], lookahead = barmerge.lookahead_on)
        allSrc.push(hl2.zScore(vidyaTF, 200))
    allSrc
//#endregion

//#region MV Cloud 
method runningVwap(series float src, int length) =>
    // accumulators
    var float cumPriceVolume = na    
    var float cumVolume = na   
    var float cumVariance = na   
    pv = src * volume
    cumPriceVolume  := nz(cumPriceVolume[1])  + pv     - nz(pv[length])
    cumVolume := nz(cumVolume[1]) + volume - nz(volume[length])
    vwap = cumPriceVolume / cumVolume
    syntheicVariance = volume * (src - nz(vwap[1])) * (src - vwap)
    cumVariance  := nz(cumVariance[1]) + syntheicVariance - nz(syntheicVariance[length])
    vwap
//#endregion

//#region ATR
atr = ta.atr(length = inputAtrLength)
//#endregion
//#region VWAP
[vwap1, upper1, lower1, prevVwap1, prevUpper1, prevLower1] = f_timeframeAnchoredVwap("1D", 1)
[_, upper2, lower2, _, prevUpper2, prevLower2] = f_timeframeAnchoredVwap("1D", 2)
[_, upper3, lower3, _, prevUpper3, prevLower3] = f_timeframeAnchoredVwap("1D", 3)
[_, upper4, lower4, _, prevUpper4, prevLower4] = f_timeframeAnchoredVwap("1D", 4)
//#endregion

//#region OBR 
f_obrSessionLabelText(tf) =>
    tfInSec = timeframe.in_seconds(tf)
    if tfInSec >= 3600 and tfInSec % 3600 == 0
        tfInHours = tfInSec / 3600
        str.tostring(tfInHours) + " hour"
    else if tfInSec < 60
        str.tostring(tfInSec) + " sec" 
    else if tfInSec % 60 == 0
        tfInMin = tfInSec / 60
        str.tostring(tfInMin) + " min"
    else
        tf

var float obr1High = na 
var float obr1Low = na
var float obr2High = na 
var float obr2Low = na
var int obrStart = time
var label obrHighTf1Label = not inputObrTf1Enabled ? label(na) : label.new(time, close, text=f_obrSessionLabelText(inputObrTf1) + " OBR High", style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputObrHighColor, size=size.small)
var label obrLowTf1Label  = not inputObrTf1Enabled ? label(na) : label.new(time, close, text=f_obrSessionLabelText(inputObrTf1) + " OBR Low" , style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputObrLowColor, size=size.small)
var label obrHighTf2Label = not inputObrTf2Enabled ? label(na) : label.new(time, close, text=f_obrSessionLabelText(inputObrTf2) + " OBR High", style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputObrHighColor, size=size.small)
var label obrLowTf2Label  = not inputObrTf2Enabled ? label(na) : label.new(time, close, text=f_obrSessionLabelText(inputObrTf2) + " OBR Low" , style=label.style_label_left, xloc=xloc.bar_time, yloc=yloc.price, color=inputObrLowColor, size=size.small)

inSession = timeinrange("", custom_session, custom_sesseion_timezone)
isStartBar = use_custom_session ? inSession and not inSession[1] : session.isfirstbar_regular 
if isStartBar
    obr1High  := high 
    obr1Low   := low  
    obr2High  := high 
    obr2Low   := low  
    obrStart  := time

if time < obrStart + timeframe.in_seconds(inputObrTf1) * 1000  
    obr1High  := math.max(high, obr1High) 
    obr1Low   := math.min(low , obr1Low )  
if time < obrStart + timeframe.in_seconds(inputObrTf2) * 1000  
    obr2High  := math.max(high, obr2High) 
    obr2Low   := math.min(low , obr2Low )  

[obrTf1High, obrTf1Low, obrTf2High, obrTf2Low, obrMtfStart] = request.security(syminfo.tickerid, "1", [obr1High, obr1Low, obr2High, obr2Low, obrStart], barmerge.gaps_off, barmerge.lookahead_off)
obrTf1Start = obrMtfStart
obrTf2Start = obrMtfStart
//#endregion

//#region PVSRA
pvsra = f_PVSRA()
//#endregion

//#region MV Cloud
mvCloudVWAPLength = switch inputMVCloudPreset
    "Agressive" => 50
    "Moderate" => 100
    => 200
mvCloudVwap = hlc3.runningVwap(mvCloudVWAPLength)
mvCloudEma = ta.ema(close, 21)
mvCloudBullishCrossover = mvCloudEma > mvCloudVwap
mvCloudBearishCrossover = mvCloudEma < mvCloudVwap
//#endregion

//#region ATR

atrTable = inputAtrEnabled ? table.new(position.top_right, 2, 2, frame_width = inputAtrFrameWidth, frame_color = inputAtrFrameColor, force_overlay = true, bgcolor = inputAtrBgColor) : table(na)
if inputAtrEnabled and barstate.islast
    atrTable.cell(0, 0, "Smooth Trader Toolkit", text_color = chart.fg_color)
    atrTable.cell(0, 1, "ATR", text_color = chart.fg_color)
    atrTable.merge_cells(0,0,1,0)
    atrTable.cell(1, 1, str.tostring(math.round_to_mintick(atr)), text_color = chart.fg_color)
//#endregion

//#region VWAP
plot(inputVwapDisplayCurrent? vwap1 : na, force_overlay = true, color = inputVwapBandColor)
plot(inputVwapDisplayPrevious ? prevVwap1 : na, force_overlay = true, color = inputVwapPrevBandColor)
vwapUpperBand1 = plot(not inputVwap1BandEnabled ? na : upper1, color = color.new(color.black, 100), force_overlay = true)
vwapUpperBand2 = plot(not inputVwap2BandEnabled ? na : upper2, color = color.new(color.black, 100), force_overlay = true)
vwapUpperBand3 = plot(not inputVwap3BandEnabled ? na : upper3, color = color.new(color.black, 100), force_overlay = true)
vwapUpperBand4 = plot(not inputVwap4BandEnabled ? na : upper4, color = color.new(color.black, 100), force_overlay = true)
vwapLowerBand1 = plot(not inputVwap1BandEnabled ? na : lower1, color = color.new(color.black, 100), force_overlay = true)
vwapLowerBand2 = plot(not inputVwap2BandEnabled ? na : lower2, color = color.new(color.black, 100), force_overlay = true)
vwapLowerBand3 = plot(not inputVwap3BandEnabled ? na : lower3, color = color.new(color.black, 100), force_overlay = true)
vwapLowerBand4 = plot(not inputVwap4BandEnabled ? na : lower4, color = color.new(color.black, 100), force_overlay = true)
fill(vwapUpperBand4, vwapUpperBand3, title="VWAP Fill  3", color = color.new(inputVwapBandColor, 45))
fill(vwapUpperBand3, vwapUpperBand2, title="VWAP Fill  2", color = color.new(inputVwapBandColor, 60))
fill(vwapUpperBand2, vwapUpperBand1, title="VWAP Fill  1", color = color.new(inputVwapBandColor, 75))
fill(vwapUpperBand1, vwapLowerBand1, title="VWAP Fill  0", color = color.new(inputVwapBandColor, 90))
fill(vwapLowerBand1, vwapLowerBand2, title="VWAP Fill -1", color = color.new(inputVwapBandColor, 75))
fill(vwapLowerBand2, vwapLowerBand3, title="VWAP Fill -2", color = color.new(inputVwapBandColor, 60))
fill(vwapLowerBand3, vwapLowerBand4, title="VWAP Fill -3", color = color.new(inputVwapBandColor, 45))
vwapPrevUpperBand1 = plot(not inputVwapPrev1BandEnabled ? na : prevUpper1[1], color = color.new(color.black, 100), force_overlay = true)
vwapPrevUpperBand2 = plot(not inputVwapPrev1BandEnabled ? na : prevUpper2[1], color = color.new(color.black, 100), force_overlay = true)
vwapPrevUpperBand3 = plot(not inputVwapPrev1BandEnabled ? na : prevUpper3[1], color = color.new(color.black, 100), force_overlay = true)
vwapPrevUpperBand4 = plot(not inputVwapPrev1BandEnabled ? na : prevUpper3[1], color = color.new(color.black, 100), force_overlay = true)
vwapPrevLowerBand1 = plot(not inputVwapPrev1BandEnabled ? na : prevLower1[1], color = color.new(color.black, 100), force_overlay = true)
vwapPrevLowerBand2 = plot(not inputVwapPrev1BandEnabled ? na : prevLower2[1], color = color.new(color.black, 100), force_overlay = true)
vwapPrevLowerBand3 = plot(not inputVwapPrev1BandEnabled ? na : prevLower3[1], color = color.new(color.black, 100), force_overlay = true)
vwapPrevLowerBand4 = plot(not inputVwapPrev1BandEnabled ? na : prevLower3[1], color = color.new(color.black, 100), force_overlay = true)
fill(vwapPrevUpperBand4, vwapPrevUpperBand3, title="Prev VWAP Fill  3", color = color.new(inputVwapPrevBandColor, 45))
fill(vwapPrevUpperBand3, vwapPrevUpperBand2, title="Prev VWAP Fill  2", color = color.new(inputVwapPrevBandColor, 60))
fill(vwapPrevUpperBand2, vwapPrevUpperBand1, title="Prev VWAP Fill  1", color = color.new(inputVwapPrevBandColor, 75))
fill(vwapPrevUpperBand1, vwapPrevLowerBand1, title="Prev VWAP Fill  0", color = color.new(inputVwapPrevBandColor, 90))
fill(vwapPrevLowerBand1, vwapPrevLowerBand2, title="Prev VWAP Fill -1", color = color.new(inputVwapPrevBandColor, 90))
fill(vwapPrevLowerBand2, vwapPrevLowerBand3, title="Prev VWAP Fill -2", color = color.new(inputVwapPrevBandColor, 90))
fill(vwapPrevLowerBand3, vwapPrevLowerBand4, title="Prev VWAP Fill -3", color = color.new(inputVwapPrevBandColor, 90))
//#endregion

//#region OBR 
var line obrHighTf1Line = na
var line obrLowTf1Line = na
var line obrHighTf2Line = na
var line obrLowTf2Line = na

if inputOrbEnable
    if inputObrTf1Enabled
        if obrTf1Start != obrTf1Start[1] and inputObrShowHistorical
            obrHighTf1Line.set_x2(time[1])
            obrLowTf1Line.set_x2(time[1])
            obrHighTf1Line.copy()
            obrLowTf1Line.copy()
            if inputObrShowHistoricalLabel
                obrHighTf1Label.set_x(time[1])
                obrLowTf1Label.set_x(time[1])
                obrHighTf1Label.copy()
                obrLowTf1Label.copy()
        line.delete(obrHighTf1Line)
        line.delete(obrLowTf1Line)
        obrHighTf1Line := line.new(obrTf1Start, obrTf1High, time + timePerBar * inputOBRLineBarsOffset, obrTf1High, xloc.bar_time,  force_overlay = true, color = inputObrHighColor, width = 2) 
        obrLowTf1Line := line.new(obrTf1Start, obrTf1Low, time + timePerBar * inputOBRLineBarsOffset, obrTf1Low, xloc.bar_time,  force_overlay = true, color = inputObrLowColor, width = 2)
        obrHighTf1Label.set_xy(time + timePerBar * inputOBRLabelBarsOffset, obrTf1High)
        obrLowTf1Label.set_xy( time + timePerBar * inputOBRLabelBarsOffset, obrTf1Low)

    if inputObrTf2Enabled
        if obrTf2Start != obrTf2Start[1] and inputObrShowHistorical
            obrHighTf2Line.set_x2(time[1])
            obrLowTf2Line.set_x2(time[1])
            obrHighTf2Line.copy()
            obrLowTf2Line.copy()
            if inputObrShowHistoricalLabel
                obrHighTf2Label.set_x(time[1])
                obrLowTf2Label.set_x(time[1])
                obrHighTf2Label.copy()
                obrLowTf2Label.copy()
        line.delete(obrHighTf2Line)
        line.delete(obrLowTf2Line)
        obrHighTf2Line := line.new(obrTf2Start, obrTf2High, time + timePerBar * inputOBRLineBarsOffset, obrTf2High, xloc.bar_time,  force_overlay = true, color = inputObrHighColor, width = 2) 
        obrLowTf2Line := line.new(obrTf2Start, obrTf2Low, time + timePerBar * inputOBRLineBarsOffset, obrTf2Low, xloc.bar_time,  force_overlay = true, color = inputObrLowColor, width = 2)
        obrHighTf2Label.set_xy(time + timePerBar * inputOBRLabelBarsOffset, obrTf2High)
        obrLowTf2Label.set_xy( time + timePerBar * inputOBRLabelBarsOffset, obrTf2Low)
//#endregion

//#region PVSRA 
color pvsraColor = switch 
    pvsra == +2  => inputPVSRAHighVolBullColor
    pvsra == -2  => inputPVSRAHighVolBearColor
    pvsra == +1  => inputPVSRAMedVolDisplay ? inputPVSRAMedVolBullColor : na
    pvsra == -1  => inputPVSRAMedVolDisplay ? inputPVSRAMedVolBearColor : na
    => na

plotshape(pvsra == +2 and inputPVSRASDisplayDiamond, "High Bull Volume", style = shape.diamond, color = pvsraColor, force_overlay = true, size= size.small, location = inputPVSRABullDiamondPos  == 'Above' ? location.abovebar : location.belowbar)
plotshape(pvsra == -2 and inputPVSRASDisplayDiamond, "Low Bear Volume", style = shape.diamond, color = pvsraColor, force_overlay = true, size= size.small, location = inputPVSRABearDiamondPos  == 'Above' ? location.abovebar : location.belowbar)
plotshape(pvsra == +1 and inputPVSRASDisplayDiamond, "Med Bull Volume", style = shape.diamond, color = pvsraColor, force_overlay = true, size= size.small, location = inputPVSRABullDiamondPos  == 'Above' ? location.abovebar : location.belowbar)
plotshape(pvsra == -1 and inputPVSRASDisplayDiamond, "Med Bear Volume", style = shape.diamond, color = pvsraColor, force_overlay = true, size= size.small, location = inputPVSRABearDiamondPos  == 'Above' ? location.abovebar : location.belowbar)
//#endregion

//#region MV Cloud
mvCloudPlotEma = plot(not inputMVCloudEnabled ? na : mvCloudEma , 'MV Cloud EMA', color=inputMVCloudEMAColor, force_overlay = true)
mvCloudPlotVwap = plot(not inputMVCloudEnabled ? na : mvCloudVwap , 'MV Cloud VWAP', color=inputMVCloudVWAPColor, force_overlay = true)
fill(mvCloudPlotEma, mvCloudPlotVwap, title='MV Cloud', color = mvCloudEma > mvCloudVwap ? color.new(inputMVCloudEMAColor, 75) : color.new(inputMVCloudVWAPColor, 75))
//#endregion

//#region Candle Coloring
color candleColor = switch 
    inputPVSRADisplayColoring and  pvsra == +2  => inputPVSRAHighVolBullColor
    inputPVSRADisplayColoring and  pvsra == -2  => inputPVSRAHighVolBearColor
    inputPVSRADisplayColoring and  pvsra == +1  => inputPVSRAMedVolDisplay ? inputPVSRAMedVolBullColor : na
    inputPVSRADisplayColoring and  pvsra == -1  => inputPVSRAMedVolDisplay ? inputPVSRAMedVolBearColor : na
    => na

plotcandle(open, high, low, close, "Candle Coloring", color = candleColor, wickcolor = candleColor, bordercolor = candleColor, force_overlay = false)
//#endregion
