// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © MisinkoMaster

//@version=6
indicator("Volume Bands", "Volume Bands | MisinkoMaster", overlay = true, behind_chart = false)
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Get User Defined Inputs
src = input.source(close, "Source", group = "Volume Bands")
len = input.int(14, "Source Length", group = "Volume Bands")
mlen = input.int(14, "Median Length", group = "Volume Bands")
vlen = input.int(14,"ATR Length", group = "Volume Bands")
mulu = input.float(1.35, "Multiplier upper", step = 0.01, group = "Volume Bands")
muld = input.float(1.35, "Multiplier lower", step = 0.01, group = "Volume Bands")
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Calculations
xm = ta.hma(src, math.round(math.sqrt(len)))
xr = 0.0
for i = 0 to len-1
    if volume[i] == ta.highest(volume, len)
        xr := xm[i]

x = ta.median(xr, mlen)
atr = ta.atr(vlen)

upper = x+atr*mulu
lower = x-atr*muld
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Trend Logic
var trend = 0

L = src > upper
S = src < lower

if L and not S
    trend := 1
if S
    trend := -1
///////////////////////////////////////////////////////////////////////////////////////////
//Plotting
upSeries   = trend == 1  ? lower : na
downSeries = trend == -1 ? upper : na

var col = color.rgb(72, 72, 72)
if trend == 1
    col := color.rgb(0, 255, 187)
if trend == -1
    col := color.rgb(255, 0, 157)
a = plot(upSeries,   "Upper", color = color.rgb(0, 255, 187), style = plot.style_linebr)
b = plot(downSeries, "Lower", color = color.rgb(255, 0, 157), style = plot.style_linebr)
c = plot(close, display = display.none, editable = false)

fill(a, c, color.rgb(0, 255, 187, 50))
fill(b, c, color.rgb(255, 0, 157, 50))

plotshape(trend > trend[1] ? upSeries : na, style = shape.labelup, location = location.absolute, size = size.normal, color = color.rgb(0, 255, 187), text = "𝓛𝓸𝓷𝓰", textcolor = color.rgb(7, 83, 63))
plotshape(trend < trend[1] ? downSeries : na, style = shape.labeldown,location = location.absolute, size = size.normal,color = color.rgb(255, 0, 157), text = "𝓢𝓱𝓸𝓻𝓽", textcolor = color.rgb(146, 11, 94))

plotcandle(open, high, low, close, color = col, bordercolor = col, wickcolor = col)
