// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © UkutaLabs

 //   ██╗   ██╗██╗  ██╗██╗   ██╗████████╗ █████╗ ██╗      █████╗ ██████╗ ███████╗
 //   ██║   ██║██║ ██╔╝██║   ██║╚══██╔══╝██╔══██╗██║     ██╔══██╗██╔══██╗██╔════╝
 //   ██║   ██║█████╔╝ ██║   ██║   ██║   ███████║██║     ███████║██████╔╝███████╗
 //   ██║   ██║██╔═██╗ ██║   ██║   ██║   ██╔══██║██║     ██╔══██║██╔══██╗╚════██║
 //   ╚██████╔╝██║  ██╗╚██████╔╝   ██║   ██║  ██║███████╗██║  ██║██████╔╝███████║
 //    ╚═════╝ ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚══════╝

//@version=6
indicator("Adaptive Volatility Squeeze [UkutaLabs]")
import UkutaLabs/UkutaLabs_General_library/8 as ulgl

//--------------------------------------------------
// INPUTS
//--------------------------------------------------

//string MAType = input.string(defval="EMA", title="Moving Average Type", options=["EMA", "SMA"], group="Configuration")
string InputSource = input.string(defval="Close", title="Input Source", options=["Open","Close","High","Low","(H+L)/2","(H+L+C)/3","(O+H+L+C)/4","(H+L+C+C)/4"], group="Configuration")

LengthBB = input.int(20, "Length", group="Bollinger Bands")
MultiplierBB = input.float(2.0, "Multiplier", group="Bollinger Bands")

LengthKC = input.int(20, "Length", group="Keltner Channel")
MultiplierKC = input.float(1.5, "Multiplier", group="Keltner Channel")

PressureFast = input.int(8, "Fast EMA", group="Pressure")
PressureSlow = input.int(21, "Slow EMA", group="Pressure")

LengthVolume = input.int(20, "Lookback Period", group="Volume")
MultiplierVolume = input.float(1.5, "Expansion Multiplier", group="Volume")

//--------------------------------------------------
// BOLLINGER BANDS
//--------------------------------------------------

InputValue = ulgl.GetInputSource(InputSource)

Basis = ta.sma(InputValue, LengthBB)
Deviation = ta.stdev(InputValue, LengthBB)

UpperBB = Basis + Deviation * MultiplierBB
LowerBB = Basis - Deviation * MultiplierBB

WidthBB = UpperBB - LowerBB

//--------------------------------------------------
// KELTNER CHANNEL
//--------------------------------------------------

EmaKC = ta.ema(InputValue, LengthKC)
ATRange = ta.atr(LengthKC)

UpperKC = EmaKC + ATRange * MultiplierKC
LowerKC = EmaKC - ATRange * MultiplierKC

WidthKC = UpperKC - LowerKC

//--------------------------------------------------
// SQUEEZE STRENGTH
//--------------------------------------------------

SqueezeRatio = WidthBB / WidthKC

Extreme = SqueezeRatio < 0.6
Strong = SqueezeRatio >= 0.6 and SqueezeRatio < 0.8
Mild = SqueezeRatio >= 0.8 and SqueezeRatio < 1.0

SqueezeOn = SqueezeRatio < 1

//--------------------------------------------------
// SQUEEZE DURATION
//--------------------------------------------------

var SqueezeBars = 0
SqueezeBars := SqueezeOn ? SqueezeBars + 1 : 0

//--------------------------------------------------
// DIRECTIONAL PRESSURE
//--------------------------------------------------

FastEMA = ta.ema(InputValue, PressureFast)
SlowEMA = ta.ema(InputValue, PressureSlow)

Pressure = FastEMA - SlowEMA

pressureMA = ta.ema(Pressure, PressureFast+PressureSlow)

//--------------------------------------------------
// VOLUME EXPANSION
//--------------------------------------------------

VolumeMA = ta.sma(InputValue, LengthVolume)
VolumeExpansion = InputValue > VolumeMA * MultiplierVolume

//--------------------------------------------------
// HISTOGRAM COLOR
//--------------------------------------------------

HistColor =
     Pressure > 0 and VolumeExpansion ?  color.lime :
     Pressure > 0 ? color.new(color.green, 30) :
     Pressure < 0 and VolumeExpansion ? color.red :
     color.new(color.maroon, 30) 

//--------------------------------------------------
// SQUEEZE DOT COLOR
//--------------------------------------------------

SqueezeColor =
     Extreme ? color.purple :
     Strong ? color.red :
     Mild ? color.orange :
     color.white

//--------------------------------------------------
// PLOTS
//--------------------------------------------------

// Momentum Histogram
plot(Pressure, style=plot.style_histogram, color=HistColor, linewidth=4, title="Directional Pressure")

// Squeeze Dots
plotshape(
     SqueezeOn,
     style=shape.cross,
     location=location.absolute,
     color=SqueezeColor,
     size=size.tiny,
     title="Squeeze State")


//Pressure MA
plot(pressureMA, title="Pressure MA", style=plot.style_line, linewidth=2, color=color.yellow)
