// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Tiagorocha1989
//                              ████████╗ ████████╗  ████████╗  ███████╗   ██████╗        ██████╗   ██████╗   ██████╗ ██╗   ██╗ ████████╗
//                              ╚══██╔══╝ ╚══██╔══╝  ██╔═══██║  ██╔════╝  ██╔═══██╗       ██╔══██╗ ██╔═══██╗ ██╔════╝ ██║   ██║ ██╔═══██║
//                                 ██║       ██║     ████████║  ██║ ███║  ██║   ██║       ██████╔╝ ██║   ██║ ██║      ████████║ ████████║
//                                 ██║       ██║     ██╔═══██║  ██║  ██║  ██║   ██║       ██╔══██╗ ██║   ██║ ██║      ██║   ██║ ██╔═══██║
//                                 ██║    ████████╗  ██║   ██║  ███████║  ╚██████╔╝       ██║  ██║ ╚██████╔╝ ╚██████╗ ██║   ██║ ██║   ██║
//@version=6
indicator('Double Money Flow Index - DMFI | TR', 'DMFI | TR →', false)
import TradingView/ta/12
//╔═════════════════╗
//║     Input's     ║
//╚═════════════════╝
Color_Mode =        input.string('Classic', 'Color Choice', group = '🎨 Color', options = ['Classic', 'Modern', 'Robust', 'Accented', 'Monochrome', 'Moderate', 'Aqua', 'Cosmic'])
Length_DMFI =       input.int(14, title = 'Length MFI:', group='⚙️ DMFI Setting', inline = 'MFI')
Source_DMFI =       input(close, title = '', group='⚙️ DMFI Setting', inline = 'MFI')
Signal_DMFI =       input.string('50', 'Entry/Exit Signal', group='⚙️ DMFI Setting', options = ['50', 'DMFI MA'],tooltip = 'Choose Entry/Exit Point')
Length_MA_DMFI =    input.int(365, title = 'Length MA', group='📊 DMFI MA', inline = 'MFI MA')
Source_MA_DMFI =    input.string('EMA', 'Moving Average', group='📊 DMFI MA', inline = 'MA', options=['EMA', 'SMA', 'RMA', 'WMA', 'VWMA', 'HMA', 'DEMA', 'TEMA', 'TRIMA', 'FRAMA', 'SWMA', 'T3'])
T_Factor =          input.float(0.7, 'T3 Factor', minval=0, maxval=1, step=0.05, group='📊 DMFI MA', tooltip = 'For Moving Average = T3')
//╔═════════════════════════════════╗
//║     MOVING AVERAGE ENGINE       ║
//╚═════════════════════════════════╝
ma(source, length, factor, type) =>
     type == 'EMA'   ? ta.ema(source, length) :
     type == 'SMA'   ? ta.sma(source, length) :
     type == 'RMA'   ? ta.rma(source, length) :
     type == 'WMA'   ? ta.wma(source, length) :
     type == 'VWMA'  ? ta.vwma(source, length) :
     type == 'HMA'   ? ta.hma(source, length) :
     type == 'DEMA'  ? ta.dema(source, length) :
     type == 'TEMA'  ? ta.tema(source, length) :
     type == 'TRIMA' ? ta.trima(source, length) :
     type == 'FRAMA' ? ta.frama(source, length) :
     type == 'SWMA'  ? ta.swma(source) :
     type == 'T3'    ? ta.t3(source, length, factor) :
     na
//╔═════════════════╗
//║     Color       ║
//╚═════════════════╝
[UpC, DnC] = switch Color_Mode
    'Classic' =>    [#008800, #ff0000]
    'Modern' =>     [#ffffff, #b721ff]
    'Robust' =>     [#ffbb00, #770737]
    'Accented' =>   [#8c5cf7, #e83e8c]
    'Monochrome' => [#e9ecef, #495057]
    'Moderate' =>   [#43a047, #e53935]
    'Aqua' =>       [#00a8e8, #f18f01]
    'Cosmic' =>     [#e83e8c, #6f2da8]
//╔════════════════════════╗
//║      Calculation       ║
//╚════════════════════════╝
MFI = ta.mfi(Source_DMFI,Length_DMFI)
DMFI = 2 * MFI - ta.mfi(MFI, Length_DMFI)
DMFI_MA =  ma(DMFI, Length_MA_DMFI, T_Factor, Source_MA_DMFI)
float Entry_DMFI = Signal_DMFI == 'DMFI MA' ? DMFI_MA : 50.0
isBull_DMFI = DMFI > Entry_DMFI
isBear_DMFI = DMFI < Entry_DMFI
Bull_DMFI = ta.crossover(DMFI, Entry_DMFI)
Bear_DMFI = ta.crossunder(DMFI, Entry_DMFI)
//╔════════════════════════╗
//║          Plot          ║
//╚════════════════════════╝
Plot_DMFI =         plot(DMFI, color = DMFI > Entry_DMFI ? color.new(UpC, 50):color.new(DnC, 50), linewidth = 3)
Plot_Entry_DMFI =   plot(Entry_DMFI,color = color.yellow)
fill(Plot_DMFI, Plot_Entry_DMFI, 120, Entry_DMFI, top_color = color.new(UpC, 0),    bottom_color = color.new(UpC, 100), title = 'Overbought Fill')
fill(Plot_DMFI, Plot_Entry_DMFI, Entry_DMFI, 0, top_color = color.new(DnC, 100), bottom_color = color.new(DnC, 0), title = 'Oversold Fill')
fill(Plot_DMFI, Plot_Entry_DMFI, DMFI < Entry_DMFI ? DMFI : Entry_DMFI, DMFI < Entry_DMFI ? Entry_DMFI : DMFI, DMFI < Entry_DMFI ? DnC : #00000000, DMFI < Entry_DMFI ? #00000000 : UpC)
plotcandle(open, high, low, close, 'Bar Color', isBull_DMFI ? UpC : isBear_DMFI ? DnC : na, isBull_DMFI ? UpC : isBear_DMFI ? DnC : na, bordercolor = isBull_DMFI ? UpC : isBear_DMFI ? DnC : na, force_overlay = true)
plotshape(Bull_DMFI, 'LONG' , shape.triangleup  , location.belowbar, UpC,    0, size = size.small, force_overlay = true)
plotshape(Bear_DMFI, 'SHORT', shape.triangledown, location.abovebar, DnC,    0, size = size.small, force_overlay = true)
bgcolor(isBull_DMFI ? color.new(UpC, 95) : isBear_DMFI ? color.new(DnC, 95) : na, title='Zone Background', force_overlay = true)
//╔════════════════════════╗
//║          VIEW          ║
//╚════════════════════════╝
var table Table_DMFI = table.new(position.middle_right, 1, 1, border_width = 1)
var label DMFILabel = na
if barstate.islast
    table.cell(Table_DMFI, 0, 0, text = isBull_DMFI ? '⬆️ Bullish' : '⬇️ Bearish', text_color = isBull_DMFI ? UpC : DnC,text_size = size.huge)
    if not na(DMFILabel)
        label.delete(DMFILabel)
    DMFILabel := label.new(bar_index + 5, DMFI, text =  str.tostring(DMFI, '#.##'), color = DMFI > Entry_DMFI ? color.new(UpC, 20) : DMFI < Entry_DMFI ? color.new(DnC, 20) : color.gray, style = label.style_label_left, size = size.large, textcolor = #000000)
//╔════════════════════════╗
//║         Alerts         ║
//╚════════════════════════╝
alertcondition(Bull_DMFI, title= 'LONG', message= '{{ticker}} LONG')
alertcondition(Bear_DMFI, title= 'SHORT', message= '{{ticker}} SHORT')
