//@version=6
indicator(title = 'HiddenRidder - 3 DMI - 3 in 1 Overlay', max_lines_count = 500, max_boxes_count = 500, max_bars_back = 500)

//auto higher time frame
HTF5Min = timeframe.period == '1' ? '5' :
 timeframe.period == '2' ? '5' :
 timeframe.period == '3' ? '5' :
 timeframe.period == '5' ? '15' :
 timeframe.period == '15' ? '60' :
 timeframe.period == '60' ? '240' :
 timeframe.period == 'D' ? 'W' :
 'D'

// //
HTF15Min = timeframe.period == '1' ? '15' :
 timeframe.period == '2' ? '15' :
 timeframe.period == '3' ? '15' :
 timeframe.period == '5' ? '15' :
 timeframe.period == '15' ? '120' :
 timeframe.period == '60' ? '480' :
 timeframe.period == 'D' ? 'W' :
 'W'
// //
//////////// Good for 1/3/5 min timeframe ///////////
ADXindicator1 = input(true, title = 'ADX indicator')
ADX5Mindiftime1 = input(true, title = 'ADX Diff HTF5Min')
ADX15Mindiftime1 = input(true, title = 'ADX Diff HTF15Min')

////////////////////////////////// ADX ///////////////////////////////////////
ADXbull_color = input.color(color(color.rgb(2, 167, 2)), 'ADX Bullish Color')
ADXbear_color = input.color(color(color.rgb(255, 0, 0)), 'ADX Bearish Color')
ADXside_color = input.color(color(color.rgb(201, 201, 201)), 'ADX Side Color')

/////////// HTF 5/15 mins ///////////

// lensig = input.int(14, title = 'ADX Smoothing', minval = 1, maxval = 50)
len = input.int(9, minval=1, title="DI Length")
lensig = input.int(14, title="ADX Smoothing", minval=1)
up = ta.change(high)
down = -ta.change(low)

plusDM = na(up) ? na : up > down and up > 0 ? up : 0
minusDM = na(down) ? na : down > up and down > 0 ? down : 0
trur = ta.rma(ta.tr, len)
plus = fixnan(100 * ta.rma(plusDM, len) / trur)
minus = fixnan(100 * ta.rma(minusDM, len) / trur)
sum = plus + minus
adx = 100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), len)
adx2 =100 * ta.rma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), lensig)


//////////////////////// ADX Current TF ///////////////////////
plot(ADXindicator1 ? adx : na, color=color.rgb(0, 37, 245,1), title="ADX",linewidth = 1) //,display = display.none
plot(ADXindicator1 ? ta.ema(plus, 2): na, color = color.rgb(76, 175, 79, 0), title = '+DI',linewidth = 1)
plot(ADXindicator1 ? ta.ema(minus, 2): na, color = color.rgb(255, 82, 82, 0), title = '-DI',linewidth = 1)

l0 = hline(ADXindicator1 ?0: na, color = color.gray, linestyle = hline.style_solid)
l20 =hline(ADXindicator1 ?20: na, color = color.gray)
l25 = hline(ADXindicator1 ?25: na, color = color.gray)

PlusColor = ADXindicator1 and ta.ema(plus, 2) > 25 and ta.ema(minus, 2) < 20 ? color.rgb(68, 187, 55, 80) : na
fill(hline(70,display = display.none),l25,PlusColor,title = "background Plus Current")

MinusColor = ADXindicator1 and ta.ema(plus, 2) < 25 and ta.ema(minus, 2) > 20 ? color.rgb(219, 5, 5, 80) : na
fill(l20,l0,MinusColor,title = "background Minus Current")

l100 =hline(ADXindicator1 ?-100 : na, color = color.gray, linestyle = hline.style_solid)

////////////// ADX 5 Min TF //////////////
plus5HTF = ADX5Mindiftime1 ? request.security(syminfo.tickerid, HTF5Min, plus) : na
minus5HTF = ADX5Mindiftime1 ? request.security(syminfo.tickerid, HTF5Min, minus) : na

pp5 = plot(ADX5Mindiftime1 ? plus5HTF - 80: na, color = color.rgb(76, 175, 79, 10), title = 'plus5HTF+DI',linewidth = 2)
pm5 = plot(ADX5Mindiftime1 ? minus5HTF - 80: na, color = color.rgb(255, 82, 82, 10), title = 'minus5HTF-DI',linewidth = 2)
l55 = hline(ADX5Mindiftime1 ? -55 : na, color = color.gray,linestyle = hline.style_dashed)
l60 = hline(ADX5Mindiftime1 ? -60 : na, color = color.gray, linestyle = hline.style_dashed)

P5HTFColor = ADX5Mindiftime1 and (plus5HTF - 80) > -55 and (minus5HTF - 80) < -60 ? color.rgb(68, 187, 55, 90) : na
fill(l0,l55,P5HTFColor,title = "background Plus 5HTM")

M5HTFColor = ADX5Mindiftime1 and (plus5HTF - 80) < -60 and (minus5HTF - 80) > -55 ? color.rgb(219, 5, 5, 90) : na
fill(l60,l100,M5HTFColor,title = "background Minus 5HTM")

////////////// ADX15 Min TF //////////////

plus15HTF = ADX15Mindiftime1 ? request.security(syminfo.tickerid, HTF15Min, plus) : na
minus15HTF = ADX15Mindiftime1 ? request.security(syminfo.tickerid, HTF15Min, minus) : na

plot(ADX15Mindiftime1 ? plus15HTF - 150: na, color = color.rgb(76, 175, 79, 20), title = 'plus15HTF+DI',linewidth = 2)
plot(ADX15Mindiftime1 ? minus15HTF - 150: na, color = color.rgb(255, 82, 82, 20), title = 'minus15HTF-DI',linewidth = 2)

l125 =hline(ADX15Mindiftime1 ? -125: na, color = #770101, linestyle = hline.style_dashed)
l130 =hline(ADX15Mindiftime1 ? -130: na, color = color.gray,linestyle = hline.style_dashed)
l150 = hline(ADX15Mindiftime1 ? -150: na, color = color.gray, linestyle = hline.style_dashed,display = display.none)
P15HTFColor = ADX15Mindiftime1 and (plus15HTF - 150) > -125 and (minus15HTF - 150) < -130 ? color.rgb(68, 187, 55, 90) : na
fill(l100,l150,P15HTFColor,title = "background Plus 15HTM")

M15HTFColor = ADX15Mindiftime1 and (plus15HTF - 150) < -130 and (minus15HTF - 150) > -125 ? color.rgb(219, 5, 5, 90) : na
fill(hline(-170),l130,M15HTFColor,title = "background Minus 15HTM")
