//@version=6
indicator("Levex - Oscillator", overlay=false, precision=2)

[macdLine, signalLine, histLine] = ta.macd(close, 12, 26, 9)

hist_color = histLine >= 0 ? (histLine[1] < histLine ? #26A69A : #B2DFDB) : (histLine[1] > histLine ? #FF5252 : #FFCDD2)

plot(histLine, color=hist_color, style=plot.style_columns, title="Histogram")
hline(0, "Zero Line", color=color.gray, linestyle=hline.style_dotted)
