// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ChartNChill

//@version=6
indicator("Pi Cycle Top Oscillator", "PCT Osc.", precision = 5)

// =========================================================================
// CONSTANTS
// =========================================================================
const int CHART_START_DATE = timestamp('Oct 05 2009')
const int RATIO_START_DATE = timestamp("Dec 13 2010")
const int MS_IN_DAY        = 86400000

const int TOP_DATE_1 = timestamp("Aug 05 2011")
const int TOP_DATE_2 = timestamp("Jun 08 2013")
const int TOP_DATE_3 = timestamp("Feb 09 2014")
const int TOP_DATE_4 = timestamp("Jan 24 2018")
const int TOP_DATE_5 = timestamp("Apr 17 2021")
const float TOP_VALUE_1 = 1.45778
const float TOP_VALUE_2 = 1.23288
const float TOP_VALUE_3 = 1.17626
const float TOP_VALUE_4 = 1.05852
const float TOP_VALUE_5 = 1.00351

// Top line coefficients
const float TOP_A           = -0.1511868254833189
const float TOP_B           = 5.007692389976341
const int TOP_OFFSET_DAYS   = -53
// R^2 = 0.9975630343502776
// Without second top
// TOP_B = 5.345343094961821  
// TOP_A = -0.1640503870210359
// R^2 = 0.9986199022076031

const int BOTTOM_DATE_1 = timestamp("Jan 04 2012")
const int BOTTOM_DATE_2 = timestamp("Apr 30 2015")
const int BOTTOM_DATE_3 = timestamp("Mar 09 2019")
const int BOTTOM_DATE_4 = timestamp("Oct 01 2022")
const float BOTTOM_VALUE_1 = 0.32272
const float BOTTOM_VALUE_2 = 0.30844
const float BOTTOM_VALUE_3 = 0.30961
const float BOTTOM_VALUE_4 = 0.28646
// Bottom line coefficients
const float BOTTOM_K = -0.0000000000000939
const float BOTTOM_B = 0.3256784268173674

// STRINGS
const string VIEW_FIT_LINES  = "Fit Lines"
const string VIEW_NORMALIZED = "Normalized"
const string TT_ZONE_LEVEL   = "Value between 0.01 and 0.99"

// COLORS
const color RATIO_COLOR   = #FFA500
const color RANGE_COLOR   = #87CEEB
const color SELL_COLOR    = color.new(color.red, 40)
const color BUY_COLOR     = color.new(color.green, 40)
const color NEUTRAL_COLOR = color.blue

// =========================================================================
// INPUTS
// =========================================================================
string viewInput = input.string(
     defval = VIEW_FIT_LINES,
     title = "View",
     options = [VIEW_FIT_LINES, VIEW_NORMALIZED])

float sellZoneLevelInput = input.float(
     defval = 0.90,
     title = "Sell Zone Level",
     minval = 0.01,
     maxval = 0.99,
     step = 0.01,
     tooltip = TT_ZONE_LEVEL)

float buyZoneLevelInput = input.float(
     defval = 0.10,
     title = "Buy Zone Level",
     minval = 0.01,
     maxval = 0.99,
     step = 0.01,
     tooltip = TT_ZONE_LEVEL)

// =========================================================================
// CALCULATIONS
// =========================================================================
float sma111Daily = request.security(
     symbol = syminfo.tickerid,
     timeframe = "1D",
     expression = ta.sma(close, 111))

float sma350x2Daily = request.security(
     symbol = syminfo.tickerid,
     timeframe = "1D",
     expression = ta.sma(close, 350) * 2.0)

float ratioValue = sma111Daily / sma350x2Daily

// Chart Lines
float bottomLine = BOTTOM_K * (time - RATIO_START_DATE) + BOTTOM_B
float topLine = TOP_A * math.log(time - RATIO_START_DATE + TOP_OFFSET_DAYS * MS_IN_DAY) + TOP_B
float middleLine = bottomLine + (topLine - bottomLine) / 2.0

// Risk
float riskValue = (ratioValue - bottomLine) / (topLine - bottomLine)

// Buy & Sell Zones
float sellLevelValue = bottomLine + (topLine - bottomLine) * sellZoneLevelInput
float buyLevelValue = bottomLine + (topLine - bottomLine) * buyZoneLevelInput

// =========================================================================
// VISUALS
// =========================================================================
bool fitLinesView = viewInput == VIEW_FIT_LINES

// FIT LINES
bottomPlot = plot(
     series = fitLinesView ? bottomLine : na,
     title = "Bottom Line",
     color = RANGE_COLOR,
     linewidth = 2)

topPlot = plot(
     series = fitLinesView ? topLine : na,
     title = "Top Line",
     color = RANGE_COLOR,
     linewidth = 2)

plot(
     series = fitLinesView ? middleLine : na,
     title = "Middle Line",
     color = RANGE_COLOR,
     linewidth = 1)

hline(
     price = fitLinesView ? 1.0 : na,
     title = "Pi Cicle Top Signal / 1.0",
     color = color.white,
     linewidth = 2)

// Buy & sell Zones
sellLevelPlot = plot(
     series = fitLinesView ? sellLevelValue : na,
     title = "Sell Level",
     color = SELL_COLOR)

buyLevelPlot = plot(
     series = fitLinesView ? buyLevelValue : na,
     title = "Buy Level",
     color = BUY_COLOR)

fill(
     plot1 = sellLevelPlot,
     plot2 = topPlot,
     color = fitLinesView ? SELL_COLOR : na,
     title = "Sell Zone")

fill(
     plot1 = buyLevelPlot,
     plot2 = bottomPlot,
     color = fitLinesView ? BUY_COLOR : na,
     title = "Buy Zone")

plot(
     series = fitLinesView ? ratioValue : na,
     title = "Pi Cycle Ratio",
     color = RATIO_COLOR,
     linewidth = 2)

// OSCILLATOR
topOscLine = hline(
     price = fitLinesView ? na : 1.0,
     title = "Oscillator 1.0",
     color = RANGE_COLOR,
     linestyle = hline.style_solid,
     linewidth = 2)

bottomOscLine = hline(
     price = fitLinesView ? na : 0.0,
     title = "Oscillator 0.0",
     color = RANGE_COLOR,
     linestyle = hline.style_solid,
     linewidth = 2)

hline(
     price = fitLinesView ? na : 0.5,
     title = "Oscillator 0.5",
     color = RANGE_COLOR,
     linestyle = hline.style_solid)

// Buy & sell Zones
sellLevelOsc = hline(
     price = fitLinesView ? na : sellZoneLevelInput,
     title = "Sell Level Osc",
     color = na)

buyLevelOsc = hline(
     price = fitLinesView ? na : buyZoneLevelInput,
     title = "Buy Level Osc",
     color = na)

fill(
     hline1 = sellLevelOsc,
     hline2 = topOscLine,
     color = fitLinesView ? na : SELL_COLOR,
     title = "Sell Zone Osc")

fill(
     hline1 = buyLevelOsc,
     hline2 = bottomOscLine,
     color = fitLinesView ? na : BUY_COLOR,
     title = "Buy Zone Osc")

plot(
     series = fitLinesView ? na : riskValue,
     title = "Oscillator",
     color = RATIO_COLOR,
     linewidth = 2,
     precision = 2)

// RISK DISPLAY
var table riskTable = table.new(
     position = position.top_right, 
     columns = 2, 
     rows = 1)

if barstate.islast
    table.cell(
         table_id = riskTable, 
         column = 0, 
         row = 0, 
         text = "Risk", 
         text_color = color.white)

    table.cell(
         table_id = riskTable, 
         column = 1, 
         row = 0, 
         text = str.tostring(riskValue, "#.##"), 
         text_color = color.white)

// CHART VIEW
plot(
     series = close,
     title = "Chart View",
     color = riskValue <= 0.10 ? BUY_COLOR : riskValue >= 0.90 ? SELL_COLOR : NEUTRAL_COLOR,
     linewidth = 2,
     precision = 2,
     force_overlay = true)

// Timestamps in Data Window for future fitting
plotchar(TOP_DATE_1 - RATIO_START_DATE, 'Top1 Adj.', display = display.data_window, precision = 0)
plotchar(TOP_DATE_2 - RATIO_START_DATE, 'Top2 Adj.', display = display.data_window, precision = 0)
plotchar(TOP_DATE_3 - RATIO_START_DATE, 'Top3 Adj.', display = display.data_window, precision = 0)
plotchar(TOP_DATE_4 - RATIO_START_DATE, 'Top4 Adj.', display = display.data_window, precision = 0)
plotchar(TOP_DATE_5 - RATIO_START_DATE, 'Top5 Adj.', display = display.data_window, precision = 0)

plotchar(BOTTOM_DATE_1 - RATIO_START_DATE, 'Bottom1 Adj.', display = display.data_window, precision = 0, color = color.orange)
plotchar(BOTTOM_DATE_2 - RATIO_START_DATE, 'Bottom2 Adj.', display = display.data_window, precision = 0, color = color.orange)
plotchar(BOTTOM_DATE_3 - RATIO_START_DATE, 'Bottom3 Adj.', display = display.data_window, precision = 0, color = color.orange)
plotchar(BOTTOM_DATE_4 - RATIO_START_DATE, 'Bottom4 Adj.', display = display.data_window, precision = 0, color = color.orange)
