//@version=5
indicator(title="Relative Strength Index", shorttitle="RSI", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
len = input.int(14, minval=1, title="Length")
src = input(close, "Source")
BullHi  = hline( 80   , "Bull Control Zone High", color.aqua) 
BullLo  = hline( 61.8 , "Bull Control Zone Low", color.aqua)
MidLine = hline( 50   , "Midline", color.white) 
BearHi  = hline( 38.2 , "Bear Control Zone High", color.purple)
BearLo  = hline( 20   , "Bear Control Zone Low", color.purple)
fill(BullHi, BullLo, color.new(color.aqua, 70), "Bull Control Zone", true, true)
fill(BearHi, BearLo, color.new(color.purple, 70), "Bear Control Zone", true, true)


up = ta.rma(math.max(ta.change(src), 0), len)
down = ta.rma(-math.min(ta.change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))


plot(rsi, "RSI", color=#7E57C2)
