// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Nathanl19

//@version=6
indicator("Stochastic Signal", shorttitle = "SS")

periodK = input.int(21, "%K Length", minval=1)
smoothK = input.int(8, "%K Smoothing", minval=1)
periodD = input.int(8, "%D Smoothing", minval=1)

k = ta.sma(ta.stoch(close, high, low, periodK), smoothK)
d = ta.sma(k, periodD)

plot(k, "%K", color=#ffffff, linewidth=1, style=plot.style_cross)
plot(d, "%D", color=color.rgb(0, 204, 255), linewidth=2, style=plot.style_line)

h0 = hline(80, "Upper Band", color=#787B86)
hline(50, "Middle Band", color=color.new(#787B86, 50))
h1 = hline(20, "Lower Band", color=#787B86)
fill(h0, h1, color=color.rgb(33, 150, 243, 90), title="Background")

//----- Bull Bear Condition -----
bull = ta.crossover(k, d)
bear = ta.crossunder(k, d)

bullFilter = bull and k < 20
bearFilter = bear and k > 80

if bullFilter
    label.new(bar_index, k, style=label.style_circle, color=color.green, size=size.tiny)

if bearFilter
    label.new(bar_index, k, style=label.style_circle, color=color.red, size=size.tiny)
