//@version=6
indicator(title="Stochastic RSI w. Timeframe", shorttitle="Stoch RSI TF", format=format.price, precision=2)

// ─────────────────────────────────────────────────────────────────────────────
// Inputs
// ─────────────────────────────────────────────────────────────────────────────
groupTF    = "Timeframe"
tf         = input.timeframe("", "Timeframe", group=groupTF)

groupParams = "Parameters"
smoothK     = input.int(3,  "K",                 group=groupParams, minval=1)
smoothD     = input.int(3,  "D",                 group=groupParams, minval=1)
lengthRSI   = input.int(14, "RSI Length",        group=groupParams, minval=1)
lengthStoch = input.int(14, "Stochastic Length", group=groupParams, minval=1)
src         = input(close,  title="RSI Source",  group=groupParams)

// ─────────────────────────────────────────────────────────────────────────────
// Core calculation
// ─────────────────────────────────────────────────────────────────────────────
calcStochRSI(float _src, int _lengthRSI, int _lengthStoch, int _smoothK, int _smoothD) =>
    _rsi = ta.rsi(_src, _lengthRSI)
    _k   = ta.sma(ta.stoch(_rsi, _rsi, _rsi, _lengthStoch), _smoothK)
    _d   = ta.sma(_k, _smoothD)
    [_k, _d]

// ─────────────────────────────────────────────────────────────────────────────
// Request from selected timeframe
// ─────────────────────────────────────────────────────────────────────────────
[k, d] = request.security(syminfo.tickerid, tf, calcStochRSI(src, lengthRSI, lengthStoch, smoothK, smoothD), lookahead=barmerge.lookahead_off)

// ─────────────────────────────────────────────────────────────────────────────
// Plots
// ─────────────────────────────────────────────────────────────────────────────
plot(k, "K", color=#2962FF)
plot(d, "D", color=#FF6D00)
h0 = hline(80, "Upper Band", color=#787B86)
hline(50, "Middle Band", color=color.new(#787B86, 50))
h1 = hline(20, "Lower Band", color=#787B86)
fill(h0, h1, color=color.rgb(33, 150, 243, 90), title="Background")
