"""
DS-TV Backtest Results: analog-flow-indicatorkedarc-quant
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         41.94%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  ERROR: '_Array' object has no attribute 'values'

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         42.67%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — analog-flow-indicatorkedarc-quant
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    winLen = 40
    ahead = 30
    scanDepth = 600
    metric = "Euclidean"
    pickMode = "Top-3"
    buildMode = "EMA-Blend"
    sLen = 15
    normOn = True
    seekOpp = False

    def init(self):
        self.pattern_matches = []
        self.last_signal = None

    def _steps(self, arr):
        if len(arr) < 2:
            return np.array([])
        return np.diff(arr)

    def _z_score(self, v):
        v = np.array(v)
        if len(v) == 0:
            return v
        mu = np.mean(v)
        sd = np.std(v)
        if sd == 0.0:
            return np.zeros_like(v, dtype=float)
        return (v - mu) / sd

    def _distance(self, a, b, kind="Euclidean"):
        a = np.array(a)
        b = np.array(b)
        n = min(len(a), len(b))
        if n == 0:
            return float('inf')
        
        if kind == "Euclidean":
            return np.sqrt(np.sum((a[:n] - b[:n]) ** 2))
        elif kind == "Manhattan":
            return np.sum(np.abs(a[:n] - b[:n]))
        else:  # Cosine
            dot = np.sum(a[:n] * b[:n])
            na2 = np.sqrt(np.sum(a[:n] ** 2))
            nb2 = np.sqrt(np.sum(b[:n] ** 2))
            denom = na2 * nb2
            if denom == 0.0:
                return 1.0
            return 1.0 - dot / denom

    def _ema_array(self, a, length):
        a = np.array(a)
        if len(a) == 0:
            return a
        out = np.zeros_like(a, dtype=float)
        k = 2.0 / (length + 1.0)
        acc = a[0]
        out[0] = acc
        for i in range(1, len(a)):
            acc = a[i] * k + acc * (1.0 - k)
            out[i] = acc
        return out

    def next(self):
        if len(self.data) < self.winLen + self.ahead + self.scanDepth + 20:
            return

        close = self.data.Close
        bar_idx = len(self.data) - 1

        # Reference window (last winLen bars)
        ref_prices = close[-self.winLen-1:][::-1].values
        ref_s_raw = self._steps(ref_prices)
        ref_s = self._z_score(ref_s_raw) if self.normOn else ref_s_raw

        # Search for analogous patterns
        eff_scan = max(self.scanDepth, self.winLen + self.ahead + 20)
        first_end = self.ahead + 1
        last_end = self.ahead + eff_scan
        last_allowed = min(last_end, bar_idx - self.winLen)

        k_want = 1 if self.pickMode == "Top-1" else 2 if self.pickMode == "Top-2" else 3 if self.pickMode == "Top-3" else 5

        top_dists = []
        top_ends = []

        if last_allowed >= first_end:
            for end_ago in range(first_end, last_allowed + 1):
                if bar_idx - end_ago < self.winLen:
                    continue
                
                cand_prices = close[bar_idx - end_ago - self.winLen:bar_idx - end_ago + 1][::-1].values
                if len(cand_prices) < self.winLen + 1:
                    continue
                
                cand_s_raw = self._steps(cand_prices)
                cand_s = self._z_score(cand_s_raw) if self.normOn else cand_s_raw
                dist = self._distance(ref_s, cand_s, self.metric)

                if len(top_dists) < k_want:
                    top_dists.append(dist)
                    top_ends.append(end_ago)
                else:
                    if not self.seekOpp:
                        worst_idx = np.argmax(top_dists)
                        if dist < top_dists[worst_idx]:
                            top_dists[worst_idx] = dist
                            top_ends[worst_idx] = end_ago
                    else:
                        worst_idx = np.argmin(top_dists)
                        if dist > top_dists[worst_idx]:
                            top_dists[worst_idx] = dist
                            top_ends[worst_idx] = end_ago

        k_have = len(top_ends)
        
        if k_have > 0:
            eps = 1e-10
            weights = []
            wsum = 0.0
            for d in top_dists:
                w = 1.0 / max(d, eps)
                weights.append(w)
                wsum += w

            # Weighted forward steps
            agg = np.zeros(self.ahead)
            for i in range(k_have):
                end_ago = top_ends[i]
                wi = weights[i] / wsum
                for h in range(self.ahead):
                    if bar_idx - end_ago + 1 + h < len(close):
                        v_next = close[bar_idx - end_ago - h]
                        v_curr = close[bar_idx - end_ago + 1 - h]
                        step = v_next - v_curr
                        agg[h] += wi * step

            # Optional smoothing
            if self.buildMode == "EMA-Blend":
                agg = self._ema_array(agg, self.sLen)

            # Generate projected price path
            base = close[-1]
            cur = base
            projected_prices = [cur]
            
            for h in range(self.ahead):
                st = agg[h]
                if self.buildMode == "MeanStep":
                    nxt = base + st
                else:
                    nxt = cur + st
                projected_prices.append(nxt)
                cur = nxt

            # Simple trading logic based on projected path
            current_price = close[-1]
            avg_projected = np.mean(projected_prices[1:])
            direction = 1 if avg_projected > current_price else -1

            if direction > 0 and not self.position:
                self.buy()
                self.last_signal = "buy"
            elif direction < 0 and self.position:
                self.sell()
                self.last_signal = "sell"
        else:
            # No matches found, flatten if in position
            if self.position:
                self.sell()


if __name__ == "__main__":
    from backtesting.test import GOOG

    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()