"""
DS-TV Backtest Results: bk-ak-reaper-drone
============================================================

--- SPY ---
  ERROR: Indicator "λ" error. See traceback above.

--- BTC ---
  ERROR: Indicator "λ" error. See traceback above.

--- QQQ ---
  ERROR: Indicator "λ" error. See traceback above.

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — bk-ak-reaper-drone
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # Core settings
    sumLen = 25
    rsiLen = 14
    longLen = 255
    normLen = 200
    zSoftCap = 2.5
    ratioCap = 10.0
    
    # Component weights
    wCore = 1.50
    wLTF = 1.25
    wCMF = 0.75
    wOBV = 0.75
    wVWAP = 0.75
    wCVD = 0.50
    
    # Threshold settings
    netSmoothL = 5
    useAutoThr = True
    thrManual = 0.70
    autoLen = 300
    autoK = 1.2
    thrMin = 0.30
    thrMax = 0.95
    
    # Spring signal settings
    maxLinger = 3
    minCompAgree = 2
    cooldown = 8
    
    # Trend settings
    trendMode = "Off"
    emaFastL = 21
    emaSlowL = 55

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        hlc3 = (high + 2 * close + low) / 4
        
        # Helper functions
        def safe_div(n, d, eps=1e-6):
            return np.where(np.abs(d) < eps, 0.0, n / d)
        
        def cap(x, cap_val):
            return np.minimum(np.maximum(x, -cap_val), cap_val)
        
        def z_score(src, length):
            df = pd.DataFrame(src)
            m = df.rolling(length).mean().values.flatten()
            s = df.rolling(length).std().values.flatten()
            return np.where(s == 0, 0.0, (src - m) / s)
        
        def tanh(x):
            x = cap(x, 10.0)
            e2 = np.exp(2.0 * x)
            return (e2 - 1.0) / (e2 + 1.0)
        
        def unit(z, softcap):
            return tanh(z / softcap)
        
        # Component 1: NVI vs PVI
        pvi = self.I(lambda: pta.pvi(close, volume) or pd.Series(0, index=close.index))
        nvi = self.I(lambda: pta.nvi(close, volume) or pd.Series(0, index=close.index))
        
        ema_pvi = self.I(lambda: pta.ema(pvi, length=self.longLen))
        ema_nvi = self.I(lambda: pta.ema(nvi, length=self.longLen))
        
        dumb_dev = pvi - ema_pvi
        smart_dev = nvi - ema_nvi
        
        drsi = self.I(lambda: pta.rsi(dumb_dev, length=self.rsiLen))
        srsi = self.I(lambda: pta.rsi(smart_dev, length=self.rsiLen))
        
        r_buy = self.I(lambda: cap(safe_div(srsi, drsi), self.ratioCap))
        r_sell = self.I(lambda: cap(safe_div(100.0 - srsi, 100.0 - drsi), self.ratioCap))
        
        buy_sum = self.I(lambda: pd.Series(r_buy).rolling(self.sumLen).sum())
        sell_sum = self.I(lambda: pd.Series(r_sell).rolling(self.sumLen).sum())
        
        core_z = self.I(lambda: z_score(buy_sum - sell_sum, self.normLen))
        self.core_u = self.I(lambda: unit(core_z, self.zSoftCap))
        
        # Component 2: LTF Intrabar Flow (simplified as close momentum)
        flow_fallback = self.I(lambda: safe_div(
            np.where(close > close.shift(1), volume, 0) - np.where(close < close.shift(1), volume, 0),
            pd.Series(volume).rolling(self.sumLen).mean()
        ))
        ltf_z = self.I(lambda: z_score(flow_fallback, self.normLen))
        self.ltf_u = self.I(lambda: unit(ltf_z, self.zSoftCap))
        
        # Component 3: CMF
        mfm = self.I(lambda: np.where(
            high != low,
            (2.0 * close - high - low) / (high - low),
            0.0
        ))
        mfv = self.I(lambda: mfm * volume)
        cmf_raw = self.I(lambda: safe_div(
            pd.Series(mfv).rolling(self.sumLen).sum(),
            pd.Series(volume).rolling(self.sumLen).sum()
        ))
        cmf_z = self.I(lambda: z_score(cmf_raw, self.normLen))
        self.cmf_u = self.I(lambda: unit(cmf_z, self.zSoftCap))
        
        # Component 4: OBV Impulse
        obv_imp = self.I(lambda: pta.ema(
            np.sign(close.diff()) * volume,
            length=self.sumLen
        ))
        obv_z = self.I(lambda: z_score(obv_imp, self.normLen))
        self.obv_u = self.I(lambda: unit(obv_z, self.zSoftCap))
        
        # Component 5: VWAP Deviation
        vwap_val = self.I(lambda: pta.vwap(high, low, close) or pd.Series(0, index=close.index))
        vwap_ref = self.I(lambda: np.where(vwap_val == 0, pd.Series(close).rolling(self.sumLen).mean(), vwap_val))
        atr_val = self.I(lambda: pta.atr(high, low, close, length=14))
        vwap_dev = self.I(lambda: safe_div(close - vwap_ref, np.maximum(atr_val, 1e-6)))
        vwap_z = self.I(lambda: z_score(vwap_dev, self.normLen))
        self.vwap_u = self.I(lambda: unit(vwap_z, self.zSoftCap))
        
        # Component 6: CVD (simplified)
        self.cvd_u = self.I(lambda: unit(z_score(
            np.where(close > close.shift(1), volume, -volume),
            self.normLen
        ), self.zSoftCap))
        
        # Net signal
        base_w = self.wCore + self.wLTF + self.wCMF + self.wOBV + self.wVWAP
        self.net_raw = self.I(lambda: (
            self.wCore * self.core_u +
            self.wLTF * self.ltf_u +
            self.wCMF * self.cmf_u +
            self.wOBV * self.obv_u +
            self.wVWAP * self.vwap_u
        ) / base_w)
        
        self.net_sig = self.I(lambda: pta.ema(self.net_raw, length=self.netSmoothL))
        
        # Threshold
        abs_n = self.I(lambda: np.abs(self.net_sig))
        m_abs = self.I(lambda: pd.Series(abs_n).rolling(self.autoLen).mean())
        s_abs = self.I(lambda: pd.Series(abs_n).rolling(self.autoLen).std())
        self.thr_dyn = self.I(lambda: np.minimum(self.thrMax, np.maximum(self.thrMin, m_abs + self.autoK * s_abs)))
        
        # Trend
        self.ema_fast = self.I(lambda: pta.ema(close, length=self.emaFastL))
        self.ema_slow = self.I(lambda: pta.ema(close, length=self.emaSlowL))
        
        # Slope
        self.slope = self.I(lambda: self.net_sig - self.net_sig.shift(1))
        
    def next(self):
        if len(self.data) < 50:
            return
        
        net_sig = self.net_sig[-1]
        slope = self.slope[-1]
        thr = self.thr_dyn[-1] if self.useAutoThr else self.thrManual
        
        # Simple entry logic based on net signal and threshold
        in_bear_zone = net_sig < -thr
        in_bull_zone = net_sig > thr
        
        bull_bias = self.ema_fast[-1] > self.ema_slow[-1]
        bear_bias = self.ema_fast[-1] < self.ema_slow[-1]
        
        # Entry conditions (simplified spring logic)
        can_enter_long = (
            in_bear_zone and slope > 0 and bull_bias and not self.position
        )
        can_enter_short = (
            in_bull_zone and slope < 0 and bear_bias and not self.position
        )
        
        if can_enter_long:
            self.buy()
        elif can_enter_short:
            self.sell()
        
        # Exit logic (simple threshold cross)
        if self.position:
            if self.position.is_long and net_sig < -thr * 0.5:
                self.position.close()
            elif self.position.is_short and net_sig > thr * 0.5:
                self.position.close()


if __name__ == "__main__":
    from datetime import datetime, timedelta
    
    # Example backtest
    bt = Backtest(
        pd.read_csv('data.csv', index_col=0, parse_dates=True),
        TvStrategy,
        cash=10000,
        commission=0.001
    )
    
    stats = bt.run()
    print(stats)
    bt.plot()