"""
DS-TV Backtest Results: momentum-de-pips-institucional
============================================================

--- SPY ---
  Return                    0.00%
  Buy & Hold Return         17.90%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- BTC ---
  Return                    0.00%
  Buy & Hold Return         17.39%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

--- QQQ ---
  Return                    0.00%
  Buy & Hold Return         22.08%
  Max Drawdown              -0.00%
  Sharpe Ratio              nan
  Sortino Ratio             nan
  Calmar Ratio              nan
  Profit Factor             nan
  Expectancy                nan%
  SQN                       nan
  # Trades                  0
  Win Rate                  nan%
  Best Trade                nan%
  Worst Trade               nan%
  Avg Trade                 nan%
  Exposure Time             0.00%
  Equity Final              100000.00$
  Equity Peak               100000.00$
  Avg Drawdown              nan%
  Max Drawdown Duration     nan
  Max Trade Duration        nan
  Avg Trade Duration        nan
  Ann. Return               0.00%
  Ann. Volatility           0.00%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — momentum-de-pips-institucional
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    periodos = 200

    def init(self):
        close = pd.Series(self.data.Close)
        open_ = pd.Series(self.data.Open)
        
        # Calculate pip size (using a standard assumption of 0.0001 for forex)
        pip = 0.0001 * 10
        
        # Movement in pips
        mov = (close - open_) / pip
        
        # Classification of pips
        pips_pos = mov.apply(lambda x: x if x > 0 else 0)
        pips_neg = mov.apply(lambda x: x if x < 0 else 0)
        
        # Accumulated pips
        sum_pos = self.I(lambda: pips_pos.rolling(window=self.periodos).sum())
        sum_neg = self.I(lambda: pips_neg.rolling(window=self.periodos).sum())
        
        # Delta
        delta = self.I(lambda: (pips_pos.rolling(window=self.periodos).sum() + 
                                pips_neg.rolling(window=self.periodos).sum()))
        
        # Candle count
        bull = close.apply(lambda x: 1 if close[close.index[-1]] > open_[open_.index[-1]] else 0)
        bear = close.apply(lambda x: 1 if close[close.index[-1]] < open_[open_.index[-1]] else 0)
        
        bull_count = self.I(lambda: (close > open_).rolling(window=self.periodos).sum())
        bear_count = self.I(lambda: (close < open_).rolling(window=self.periodos).sum())
        
        # Bull percentage
        bull_percent = self.I(lambda: bull_count * 100 / self.periodos)
        
        # Ratio
        ratio = self.I(lambda: np.abs(sum_pos / (sum_neg + 0.0001)))
        
        # Momentum
        momentum = self.I(lambda: delta / self.periodos)
        
        # Store for later use
        self.sum_pos = sum_pos
        self.sum_neg = sum_neg
        self.delta = delta
        self.bull_percent = bull_percent
        self.momentum = momentum

    def next(self):
        # Bull dominance: bull_percent > 60 and delta > 0
        bull_dom = self.bull_percent[-1] > 60 and self.delta[-1] > 0
        
        # Bear dominance: bull_percent < 40 and delta < 0
        bear_dom = self.bull_percent[-1] < 40 and self.delta[-1] < 0
        
        # Entry logic
        if bull_dom and not self.position:
            self.buy()
        elif bear_dom and self.position:
            self.sell()
        elif bear_dom and not self.position:
            self.sell()
        elif bull_dom and self.position:
            pass


if __name__ == "__main__":
    from backtesting.test import SMA, GOOG
    
    bt = Backtest(GOOG, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()