"""
DS-TV Backtest Results: nexous-cl-quantum-pulse-alpha-lorentzian-probabilistic-engin
============================================================

--- SPY ---
  Return                    27.42%
  Buy & Hold Return         40.20%
  Max Drawdown              -18.70%
  Sharpe Ratio              0.74
  Sortino Ratio             1.25
  Calmar Ratio              0.69
  Profit Factor             94.26
  Expectancy                3.49%
  SQN                       3.03
  # Trades                  7
  Win Rate                  85.71%
  Best Trade                8.03%
  Worst Trade               -0.26%
  Avg Trade                 3.45%
  Exposure Time             77.00%
  Equity Final              127420.19$
  Equity Peak               128152.42$
  Avg Drawdown              -1.79%
  Max Drawdown Duration     127 days 00:00:00
  Max Trade Duration        225 days 00:00:00
  Avg Trade Duration        80 days 00:00:00
  Ann. Return               12.99%
  Ann. Volatility           17.58%

--- BTC ---
  Return                    71.51%
  Buy & Hold Return         0.29%
  Max Drawdown              -23.68%
  Sharpe Ratio              0.76
  Sortino Ratio             1.58
  Calmar Ratio              1.31
  Profit Factor             2.92
  Expectancy                6.13%
  SQN                       1.00
  # Trades                  11
  Win Rate                  63.64%
  Best Trade                63.10%
  Worst Trade               -20.35%
  Avg Trade                 4.48%
  Exposure Time             86.73%
  Equity Final              171506.50$
  Equity Peak               178654.45$
  Avg Drawdown              -5.57%
  Max Drawdown Duration     223 days 00:00:00
  Max Trade Duration        173 days 00:00:00
  Avg Trade Duration        58 days 00:00:00
  Ann. Return               30.91%
  Ann. Volatility           40.54%

--- QQQ ---
  Return                    -10.92%
  Buy & Hold Return         45.93%
  Max Drawdown              -28.12%
  Sharpe Ratio              -0.32
  Sortino Ratio             -0.40
  Calmar Ratio              -0.20
  Profit Factor             0.57
  Expectancy                -1.03%
  SQN                       -0.50
  # Trades                  8
  Win Rate                  62.50%
  Best Trade                5.21%
  Worst Trade               -17.55%
  Avg Trade                 -1.27%
  Exposure Time             75.40%
  Equity Final              89084.80$
  Equity Peak               113912.06$
  Avg Drawdown              -5.11%
  Max Drawdown Duration     307 days 00:00:00
  Max Trade Duration        143 days 00:00:00
  Avg Trade Duration        69 days 00:00:00
  Ann. Return               -5.66%
  Ann. Volatility           17.95%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — nexous-cl-quantum-pulse-alpha-lorentzian-probabilistic-engin
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    q_len = 14
    q_sens = 2.0

    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        
        # Quantum Engine
        q_sma = self.I(pta.sma, close, length=self.q_len)
        q_stdev = self.I(lambda: close.rolling(self.q_len).std())
        self.q_zscore = self.I(lambda: (close - q_sma) / q_stdev)
        
        # Quantum Ribbon
        sma_20 = self.I(pta.sma, close, length=20)
        stdev_20 = self.I(lambda: close.rolling(20).std())
        self.up_line = self.I(lambda: sma_20 + (stdev_20 * self.q_sens))
        self.dn_line = self.I(lambda: sma_20 - (stdev_20 * self.q_sens))
        
        # EMA 50
        self.ema_50 = self.I(pta.ema, close, length=50)

    def next(self):
        # Check if we have enough data
        if len(self.data) < 51:
            return
        
        # Long signal: Z-score crosses above -1.5 AND price above EMA50
        if crossover(self.q_zscore, -1.5):
            if self.data.Close[-1] > self.ema_50[-1]:
                self.buy()
        
        # Short signal: Z-score crosses below 1.5 AND price below EMA50
        if crossover(1.5, self.q_zscore):
            if self.data.Close[-1] < self.ema_50[-1]:
                self.sell()