"""
DS-TV Backtest Results: squeezeintraday-scalps
============================================================

--- SPY ---
  Return                    1.51%
  Buy & Hold Return         40.20%
  Max Drawdown              -19.21%
  Sharpe Ratio              0.05
  Sortino Ratio             0.07
  Calmar Ratio              0.04
  Profit Factor             0.79
  Expectancy                -0.71%
  SQN                       -0.35
  # Trades                  7
  Win Rate                  57.14%
  Best Trade                6.08%
  Worst Trade               -10.45%
  Avg Trade                 -0.91%
  Exposure Time             66.00%
  Equity Final              101505.40$
  Equity Peak               109718.16$
  Avg Drawdown              -3.04%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        144 days 00:00:00
  Avg Trade Duration        69 days 00:00:00
  Ann. Return               0.76%
  Ann. Volatility           15.75%

--- BTC ---
  Return                    -26.65%
  Buy & Hold Return         0.29%
  Max Drawdown              -28.23%
  Sharpe Ratio              -1.04
  Sortino Ratio             -1.19
  Calmar Ratio              -0.51
  Profit Factor             0.00
  Expectancy                -21.38%
  SQN                       -3.90
  # Trades                  2
  Win Rate                  0.00%
  Best Trade                -14.40%
  Worst Trade               -28.37%
  Avg Trade                 -21.69%
  Exposure Time             21.48%
  Equity Final              73350.78$
  Equity Peak               102209.45$
  Avg Drawdown              -28.23%
  Max Drawdown Duration     615 days 00:00:00
  Max Trade Duration        86 days 00:00:00
  Avg Trade Duration        78 days 00:00:00
  Ann. Return               -14.34%
  Ann. Volatility           13.73%

--- QQQ ---
  Return                    -26.15%
  Buy & Hold Return         45.93%
  Max Drawdown              -35.97%
  Sharpe Ratio              -0.92
  Sortino Ratio             -1.03
  Calmar Ratio              -0.39
  Profit Factor             0.25
  Expectancy                -5.43%
  SQN                       -1.08
  # Trades                  5
  Win Rate                  60.00%
  Best Trade                4.51%
  Worst Trade               -24.12%
  Avg Trade                 -6.12%
  Exposure Time             47.40%
  Equity Final              73849.24$
  Equity Peak               105955.05$
  Avg Drawdown              -7.90%
  Max Drawdown Duration     355 days 00:00:00
  Max Trade Duration        129 days 00:00:00
  Avg Trade Duration        70 days 00:00:00
  Ann. Return               -14.17%
  Ann. Volatility           15.35%

============================================================
Unoptimized run. No parameter tuning applied.

Source: TradingView Community Script — squeezeintraday-scalps
Generated by DeepStack TradingView Pipeline
"""

import numpy as np
import pandas as pd
import pandas_ta as pta
from backtesting import Backtest, Strategy
from backtesting.lib import crossover


class TvStrategy(Strategy):
    # EMA Settings
    ema5_len = 5
    ema9_len = 9
    ema21_len = 21
    ema34_len = 34
    ma50_len = 50
    ma100_len = 100
    
    # Structure MA Settings
    use50 = True
    use100 = False
    ma_type50 = "EMA"
    ma_type100 = "EMA"
    
    # Volume Settings
    vol_avg_len = 20
    vol_threshold = 0.9
    
    def init(self):
        close = pd.Series(self.data.Close)
        high = pd.Series(self.data.High)
        low = pd.Series(self.data.Low)
        volume = pd.Series(self.data.Volume)
        
        # Calculate EMAs
        self.ema5 = self.I(pta.ema, close, length=self.ema5_len)
        self.ema9 = self.I(pta.ema, close, length=self.ema9_len)
        self.ema21 = self.I(pta.ema, close, length=self.ema21_len)
        self.ema34 = self.I(pta.ema, close, length=self.ema34_len)
        
        # Calculate Structure MAs (50 and 100)
        if self.use50:
            if self.ma_type50 == "EMA":
                self.ma50 = self.I(pta.ema, close, length=self.ma50_len)
            else:
                self.ma50 = self.I(pta.sma, close, length=self.ma50_len)
        else:
            self.ma50 = self.I(lambda x: pd.Series(np.nan, index=x.index), close)
        
        if self.use100:
            if self.ma_type100 == "EMA":
                self.ma100 = self.I(pta.ema, close, length=self.ma100_len)
            else:
                self.ma100 = self.I(pta.sma, close, length=self.ma100_len)
        else:
            self.ma100 = self.I(lambda x: pd.Series(np.nan, index=x.index), close)
        
        # Volume average
        self.vol_avg = self.I(pta.sma, volume, length=self.vol_avg_len)
        
        # Price source (hlc3)
        self.price = self.I(lambda c, h, l: (c + h + l) / 3, close, high, low)

    def next(self):
        # Get current values
        ema5_val = self.ema5[-1]
        ema9_val = self.ema9[-1]
        ema21_val = self.ema21[-1]
        ema34_val = self.ema34[-1]
        price_val = self.price[-1]
        vol_val = self.data.Volume[-1]
        vol_avg_val = self.vol_avg[-1]
        
        # Handle MA50 and MA100
        ma50_val = self.ma50[-1] if self.use50 else np.nan
        ma100_val = self.ma100[-1] if self.use100 else np.nan
        
        # Volume support check
        volume_supportive = vol_val >= vol_avg_val * self.vol_threshold
        
        # Trend Structure Logic
        bull_structure = (
            ema21_val > ema34_val and
            (not self.use50 or ema34_val > ma50_val) and
            (not self.use100 or ma50_val > ma100_val)
        )
        
        bear_structure = (
            ema21_val < ema34_val and
            (not self.use50 or ema34_val < ma50_val) and
            (not self.use100 or ma50_val < ma100_val)
        )
        
        # Trend signals
        trend_bullish = ema5_val > ema9_val and bull_structure
        trend_bearish = ema5_val < ema9_val and bear_structure
        
        # Crossover signals
        bull_cross = crossover(self.ema5, self.ema9)
        bear_cross = crossover(self.ema9, self.ema5)
        
        # Trading signals
        call_signal = (
            bull_cross and
            price_val > ema34_val and
            trend_bullish
        )
        
        put_signal = (
            bear_cross and
            price_val < ema34_val and
            trend_bearish
        )
        
        # Execute trades with volume confirmation
        if call_signal and volume_supportive:
            if self.position:
                self.position.close()
            self.buy()
        elif put_signal and volume_supportive:
            if self.position:
                self.position.close()
            self.sell()


if __name__ == "__main__":
    import yfinance as yf
    
    # Download sample data
    data = yf.download("SPY", start="2023-01-01", end="2024-01-01", progress=False)
    
    # Run backtest
    bt = Backtest(data, TvStrategy, cash=10000, commission=.002)
    stats = bt.run()
    print(stats)
    bt.plot()